Repository ansible/aap-docs, pull requests merged in 2023-09, with the labels that each got.

#319 AAP-14809-Revisions1: Resolved comments from google doc
  downstream/assemblies/aap-hardening/assembly-hardening-aap.adoc
  downstream/images/aap-ref-architecture-322.png
  downstream/modules/aap-hardening/con-aap-additional-software.adoc
  downstream/modules/aap-hardening/con-automation-use-secrets.adoc
  downstream/modules/aap-hardening/con-controller-configuration.adoc
  downstream/modules/aap-hardening/con-controller-stig-considerations.adoc
  downstream/modules/aap-hardening/con-credential-management-planning.adoc
  downstream/modules/aap-hardening/con-install-secure-host.adoc
  downstream/modules/aap-hardening/con-installation.adoc
  downstream/modules/aap-hardening/con-logging-log-capture.adoc
  downstream/modules/aap-hardening/con-network-firewall-services-planning.adoc
  downstream/modules/aap-hardening/con-platform-components.adoc
  downstream/modules/aap-hardening/con-rhel-host-planning.adoc
  downstream/modules/aap-hardening/proc-configure-centralized-logging.adoc
  downstream/modules/aap-hardening/proc-configure-external-authentication.adoc
  downstream/modules/aap-hardening/proc-controller-stig-considerations.adoc
  downstream/modules/aap-hardening/proc-disaster-recovery-operations.adoc
  downstream/modules/aap-hardening/proc-fapolicyd.adoc
  downstream/modules/aap-hardening/proc-file-systems-mounted-noexec.adoc
  downstream/modules/aap-hardening/proc-install-user-pki.adoc
  downstream/modules/aap-hardening/proc-namespaces.adoc
  downstream/modules/aap-hardening/ref-architecture.adoc
  downstream/modules/aap-hardening/ref-auditing-incident-detection.adoc
  downstream/modules/aap-hardening/ref-automation-controller-operational-secrets.adoc
  downstream/modules/aap-hardening/ref-dns-load-balancing.adoc
  downstream/modules/aap-hardening/ref-infrastructure-as-code.adoc
  downstream/modules/aap-hardening/ref-initial-configuration.adoc
  downstream/modules/aap-hardening/ref-security-variables-install-inventory.adoc
  downstream/modules/aap-hardening/ref-sensitive-variables-install-inventory.adoc
  downstream/modules/aap-hardening/ref-sudo-nopasswd.adoc
  downstream/modules/aap-hardening/ref-updates-upgrades.adoc
Labels: AAP Hardening, Ready for review, Needs backport to 2.4, Ready for technical review, 2.4

#327 [2.4] AAP-14809-Revisions1: Fix AAP acronym (#319)
  downstream/assemblies/aap-hardening/assembly-hardening-aap.adoc
  downstream/images/aap-ref-architecture-322.png
  downstream/modules/aap-hardening/con-aap-additional-software.adoc
  downstream/modules/aap-hardening/con-automation-use-secrets.adoc
  downstream/modules/aap-hardening/con-controller-configuration.adoc
  downstream/modules/aap-hardening/con-controller-stig-considerations.adoc
  downstream/modules/aap-hardening/con-credential-management-planning.adoc
  downstream/modules/aap-hardening/con-install-secure-host.adoc
  downstream/modules/aap-hardening/con-installation.adoc
  downstream/modules/aap-hardening/con-logging-log-capture.adoc
  downstream/modules/aap-hardening/con-network-firewall-services-planning.adoc
  downstream/modules/aap-hardening/con-platform-components.adoc
  downstream/modules/aap-hardening/con-rhel-host-planning.adoc
  downstream/modules/aap-hardening/proc-configure-centralized-logging.adoc
  downstream/modules/aap-hardening/proc-configure-external-authentication.adoc
  downstream/modules/aap-hardening/proc-controller-stig-considerations.adoc
  downstream/modules/aap-hardening/proc-disaster-recovery-operations.adoc
  downstream/modules/aap-hardening/proc-fapolicyd.adoc
  downstream/modules/aap-hardening/proc-file-systems-mounted-noexec.adoc
  downstream/modules/aap-hardening/proc-install-user-pki.adoc
  downstream/modules/aap-hardening/proc-namespaces.adoc
  downstream/modules/aap-hardening/ref-architecture.adoc
  downstream/modules/aap-hardening/ref-auditing-incident-detection.adoc
  downstream/modules/aap-hardening/ref-automation-controller-operational-secrets.adoc
  downstream/modules/aap-hardening/ref-dns-load-balancing.adoc
  downstream/modules/aap-hardening/ref-infrastructure-as-code.adoc
  downstream/modules/aap-hardening/ref-initial-configuration.adoc
  downstream/modules/aap-hardening/ref-security-variables-install-inventory.adoc
  downstream/modules/aap-hardening/ref-sensitive-variables-install-inventory.adoc
  downstream/modules/aap-hardening/ref-sudo-nopasswd.adoc
  downstream/modules/aap-hardening/ref-updates-upgrades.adoc
Labels: AAP Hardening, Backported to 2.4, 2.4

#330 Correct typo
  downstream/modules/platform/proc-defining-node-types.adoc
  downstream/modules/platform/ref-multiple-hybrid-nodes.adoc
Labels: Needs backport to 2.4

#313 Added playbooks information
  aap-common/proc-aap-playbooks.adoc
  aap-common/ref-aap-using-playbooks.adoc
  stories/topics/proc-gcp-generate-restore-yml-file.adoc
  stories/topics/proc-gcp-running-upgrade.adoc
Labels: documentation, Ansible on AWS, AAP on GCP

#333 AAP-14809-edits updated master.adoc feedback
  downstream/titles/aap-hardening/docinfo.xml
  downstream/titles/aap-hardening/master.adoc
Labels: AAP Hardening, 2.4

#334 AAP-14809-edits updated master.adoc feedback (#333)
  downstream/titles/aap-hardening/docinfo.xml
  downstream/titles/aap-hardening/master.adoc
Labels: AAP Hardening, 2.4

#335 Add NTP configuration to AAP installation
  downstream/assemblies/platform/assembly-system-requirements.adoc
Labels: Needs backport to 2.4

#336 AAP-14809-abstract additional fixes to hardening guide
  downstream/images/aap_ref_arch_2.4.1.png
  downstream/modules/aap-hardening/con-planning-considerations.adoc
  downstream/modules/aap-hardening/con-rbac.adoc
  downstream/titles/aap-hardening/docinfo.xml
Labels: AAP Hardening, Ready for review, 2.4

#337 AAP-14809-abstract additional fixes to hardening guide (#336)
  downstream/images/aap_ref_arch_2.4.1.png
  downstream/modules/aap-hardening/con-planning-considerations.adoc
  downstream/modules/aap-hardening/con-rbac.adoc
  downstream/titles/aap-hardening/docinfo.xml
Labels: AAP Hardening, Ready for review, 2.4

#341 AAP-14809-accessibility updated terms for accessibility compliance
  downstream/modules/aap-hardening/con-controller-stig-considerations.adoc
  downstream/modules/aap-hardening/proc-configure-centralized-logging.adoc
  downstream/modules/aap-hardening/ref-automation-controller-operational-secrets.adoc
  downstream/modules/aap-hardening/ref-security-variables-install-inventory.adoc
Labels: AAP Hardening, Ready for review, 2.4

#344 AAP-14809-accessibility updated terms for accessibility compliance (#…
  downstream/modules/aap-hardening/con-controller-stig-considerations.adoc
  downstream/modules/aap-hardening/proc-configure-centralized-logging.adoc
  downstream/modules/aap-hardening/ref-automation-controller-operational-secrets.adoc
  downstream/modules/aap-hardening/ref-security-variables-install-inventory.adoc
Labels: AAP Hardening, Ready for review, 2.4

#332 Create Section 2 'licensing' of Controller UG
  downstream/assemblies/platform/assembly-controller-licensing.adoc
  downstream/modules/platform/ref-controller-license-support.adoc
  downstream/modules/platform/ref-controller-licenses.adoc
  downstream/modules/platform/ref-controller-node-counting.adoc
  downstream/modules/platform/ref-controller-trial-evaluation.adoc
  downstream/titles/controller/controller-user-guide/master.adoc
Labels: documentation, Needs backport to 2.4, Ready for technical review, Controller

#346 Create Section 2 'licensing' of Controller UG (#332)
  downstream/assemblies/platform/assembly-controller-licensing.adoc
  downstream/modules/platform/ref-controller-license-support.adoc
  downstream/modules/platform/ref-controller-licenses.adoc
  downstream/modules/platform/ref-controller-node-counting.adoc
  downstream/modules/platform/ref-controller-trial-evaluation.adoc
  downstream/titles/controller/controller-user-guide/master.adoc
Labels: 2.4

#348 Correct typo in installation guide
  downstream/modules/platform/ref-hub-variables.adoc
Labels: Ready for review, Needs backport to 2.4, Needs backport to 2.3, Needs backport to 2.2

#350 Correct typo in installation guide (#348)
  downstream/modules/platform/ref-hub-variables.adoc
Labels: 2.3

#351 Correct typo in installation guide (#348)
  downstream/modules/platform/ref-hub-variables.adoc
Labels: 2.4

#278 Configuring automation controller on OCP
  downstream/assemblies/platform/assembly-configure-controller-OCP.adoc
  downstream/modules/platform/proc-configure-controller-OCP.adoc
  downstream/titles/ocp_performance_guide/master.adoc
Labels: Ready for review, 2.3, Needs backport to 2.3, Technical review complete, 2.4

#352 Configuring automation controller on OCP (#278)
  downstream/assemblies/platform/assembly-configure-controller-OCP.adoc
  downstream/modules/platform/proc-configure-controller-OCP.adoc
  downstream/titles/ocp_performance_guide/master.adoc
Labels: 2.4

#358 AAP-15176: fixes broken link in operations guide v2.3
  downstream/assemblies/platform/assembly-aap-manifest-files.adoc
Labels: 2.3

#355 AAP-15176: fixes broken link in automation mesh guide v2.3
  downstream/assemblies/platform/assembly-setting-up-automation-mesh.adoc
Labels: 2.3, Automation Mesh

#302 Replaced URL
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
  downstream/modules/builder/con-ansible-config-file-path.adoc
  downstream/modules/dev-guide/proc-create-collections.adoc
  downstream/modules/platform/con-building-an-execution-environment-in-a-disconnected-environment.adoc
Labels: Needs backport to 2.4, Ready for technical review, 2.4

#359 Replaced cloud.redhat.com with console.redhat.com (#302)
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
  downstream/modules/builder/con-ansible-config-file-path.adoc
  downstream/modules/dev-guide/proc-create-collections.adoc
  downstream/modules/platform/con-building-an-execution-environment-in-a-disconnected-environment.adoc
Labels: 2.4

#347 Create 'Search' Section 7 of Controller UG
  downstream/assemblies/platform/assembly-controller-search.adoc
  downstream/images/search-bar-key.png
  downstream/images/sort-order-example.png
  downstream/modules/platform/con-controller-overview-details.adoc
  downstream/modules/platform/ref-controller-other-search-considerations.adoc
  downstream/modules/platform/ref-controller-search-sort.adoc
  downstream/modules/platform/ref-controller-search-tips.adoc
  downstream/modules/platform/ref-controller-search-values-related-fields.adoc
  downstream/modules/platform/ref-controller-values-for-search-fields.adoc
  downstream/titles/controller/controller-user-guide/master.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#363 Create 'Search' Section 7 of Controller UG (#347)
  downstream/assemblies/platform/assembly-controller-search.adoc
  downstream/images/search-bar-key.png
  downstream/images/sort-order-example.png
  downstream/modules/platform/con-controller-overview-details.adoc
  downstream/modules/platform/ref-controller-other-search-considerations.adoc
  downstream/modules/platform/ref-controller-search-sort.adoc
  downstream/modules/platform/ref-controller-search-tips.adoc
  downstream/modules/platform/ref-controller-search-values-related-fields.adoc
  downstream/modules/platform/ref-controller-values-for-search-fields.adoc
  downstream/titles/controller/controller-user-guide/master.adoc
Labels: Controller, 2.4

#287 Building controller modules (#1273)
  downstream/assemblies/platform/assembly-controller-credentials.adoc
  downstream/assemblies/platform/assembly-controller-dashboard.adoc
  downstream/assemblies/platform/assembly-controller-inventories.adoc
  downstream/assemblies/platform/assembly-controller-job-templates.adoc
  downstream/assemblies/platform/assembly-controller-login.adoc
  downstream/assemblies/platform/assembly-controller-managing-subscriptions.adoc
  downstream/assemblies/platform/assembly-controller-organizations.adoc
  downstream/assemblies/platform/assembly-controller-projects.adoc
  downstream/assemblies/platform/assembly-controller-users.adoc
  downstream/images/controller-credentials-demo-details.png
  downstream/images/controller-demo-project-details.png
  downstream/images/controller-gs-demo-project-sync-icon-hover.png
  downstream/images/controller-gs-job-templates-launch.png
  downstream/images/controller-gs-licenseaccepted.png
  downstream/images/controller-gs-subscription-management.png
  downstream/images/controller-gs-templates-demo.png
  downstream/images/controller-home-dashboard.png
  downstream/images/controller-host-metrics.png
  downstream/images/controller-inventories-default-access-list-view.png
  downstream/images/controller-inventories-demo-details.png
  downstream/images/controller-job-template-demo-details.png
  downstream/images/controller-license-non-compliant.png
  downstream/images/controller-organization-list-view-edit-icon.png
  downstream/images/controller-tower-hierarchy.png
  downstream/images/controller-users-access-view.png
  downstream/images/gs-controller-license-non-compliant.png
  downstream/modules/eda/proc-eda-view-activation-output.adoc
  downstream/modules/platform/con-controller-create-users.adoc
  downstream/modules/platform/con-controller-groups-hosts.adoc
  downstream/modules/platform/con-controller-host-metric-utilities.adoc
  downstream/modules/platform/con-controller-keep-subscription-in-compliance.adoc
  downstream/modules/platform/proc-controller-add-groups-hosts.adoc
  downstream/modules/platform/proc-controller-create-credential.adoc
  downstream/modules/platform/proc-controller-create-inventory.adoc
  downstream/modules/platform/proc-controller-edit-an-organization.adoc
  downstream/modules/platform/proc-controller-edit-credential.adoc
  downstream/modules/platform/proc-controller-edit-job-template.adoc
  downstream/modules/platform/proc-controller-edit-project.adoc
  downstream/modules/platform/proc-controller-getting-started-with-job-templates.adoc
  downstream/modules/platform/proc-controller-importing-subscriptions.adoc
  downstream/modules/platform/proc-controller-logging-in.adoc
  downstream/modules/platform/proc-controller-obtaining-subscriptions.adoc
  downstream/modules/platform/proc-controller-review-organizations.adoc
  downstream/modules/platform/proc-controller-run-job-template.adoc
  downstream/modules/platform/proc-controller-set-up-project.adoc
  downstream/modules/platform/proc-controller-sync-project.adoc
  downstream/modules/platform/proc-controller-viewing-dashboard.adoc
  downstream/titles/controller/controller-getting-started/docinfo.xml
  downstream/titles/controller/controller-getting-started/images
  downstream/titles/controller/controller-getting-started/master.adoc
Labels: Ready for review, Needs backport to 2.4, 2.4

#365 Controller modules for getting started guide (#287)
  downstream/assemblies/platform/assembly-controller-credentials.adoc
  downstream/assemblies/platform/assembly-controller-dashboard.adoc
  downstream/assemblies/platform/assembly-controller-inventories.adoc
  downstream/assemblies/platform/assembly-controller-job-templates.adoc
  downstream/assemblies/platform/assembly-controller-login.adoc
  downstream/assemblies/platform/assembly-controller-managing-subscriptions.adoc
  downstream/assemblies/platform/assembly-controller-organizations.adoc
  downstream/assemblies/platform/assembly-controller-projects.adoc
  downstream/assemblies/platform/assembly-controller-users.adoc
  downstream/images/controller-credentials-demo-details.png
  downstream/images/controller-demo-project-details.png
  downstream/images/controller-gs-demo-project-sync-icon-hover.png
  downstream/images/controller-gs-job-templates-launch.png
  downstream/images/controller-gs-licenseaccepted.png
  downstream/images/controller-gs-subscription-management.png
  downstream/images/controller-gs-templates-demo.png
  downstream/images/controller-home-dashboard.png
  downstream/images/controller-host-metrics.png
  downstream/images/controller-inventories-default-access-list-view.png
  downstream/images/controller-inventories-demo-details.png
  downstream/images/controller-job-template-demo-details.png
  downstream/images/controller-license-non-compliant.png
  downstream/images/controller-organization-list-view-edit-icon.png
  downstream/images/controller-tower-hierarchy.png
  downstream/images/controller-users-access-view.png
  downstream/images/gs-controller-license-non-compliant.png
  downstream/modules/eda/proc-eda-view-activation-output.adoc
  downstream/modules/platform/con-controller-create-users.adoc
  downstream/modules/platform/con-controller-groups-hosts.adoc
  downstream/modules/platform/con-controller-host-metric-utilities.adoc
  downstream/modules/platform/con-controller-keep-subscription-in-compliance.adoc
  downstream/modules/platform/proc-controller-add-groups-hosts.adoc
  downstream/modules/platform/proc-controller-create-credential.adoc
  downstream/modules/platform/proc-controller-create-inventory.adoc
  downstream/modules/platform/proc-controller-edit-an-organization.adoc
  downstream/modules/platform/proc-controller-edit-credential.adoc
  downstream/modules/platform/proc-controller-edit-job-template.adoc
  downstream/modules/platform/proc-controller-edit-project.adoc
  downstream/modules/platform/proc-controller-getting-started-with-job-templates.adoc
  downstream/modules/platform/proc-controller-importing-subscriptions.adoc
  downstream/modules/platform/proc-controller-logging-in.adoc
  downstream/modules/platform/proc-controller-obtaining-subscriptions.adoc
  downstream/modules/platform/proc-controller-review-organizations.adoc
  downstream/modules/platform/proc-controller-run-job-template.adoc
  downstream/modules/platform/proc-controller-set-up-project.adoc
  downstream/modules/platform/proc-controller-sync-project.adoc
  downstream/modules/platform/proc-controller-viewing-dashboard.adoc
  downstream/titles/controller/controller-getting-started/docinfo.xml
  downstream/titles/controller/controller-getting-started/images
  downstream/titles/controller/controller-getting-started/master.adoc
Labels: 2.4

#367 AAP-15836: Fix typos
  downstream/modules/aap-hardening/proc-configure-centralized-logging.adoc
Labels: AAP Hardening, Ready for review, Needs backport to 2.4, Technical review complete, 2.4

#369 [2.4] AAP-15836: Removed reference to the word button (#367)
  downstream/modules/aap-hardening/proc-configure-centralized-logging.adoc
Labels: AAP Hardening, Ready for review, Backported to 2.4, 2.4

#370 Create Section 3 'Login' of the Controller UG
  downstream/assemblies/platform/assembly-controller-login.adoc
  downstream/modules/platform/proc-controller-logging-in.adoc
  downstream/titles/controller/controller-user-guide/master.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#371 Create Section 3 'Login' of the Controller UG (#370)
  downstream/assemblies/platform/assembly-controller-login.adoc
  downstream/modules/platform/proc-controller-logging-in.adoc
  downstream/titles/controller/controller-user-guide/master.adoc
Labels: 2.4

#381 Add temporary file to repo-management title directory
  downstream/titles/hub/repo-management/temp.adoc
Labels: Docathon

#382 Delete temporary file
  downstream/titles/hub/repo-management/temp.adoc
Labels: Docathon

#386 AAP-15793 Update Managing collections section of Managing Content book
  downstream/assemblies/hub/assembly-managing-collections-hub.adoc
  downstream/modules/hub/con-approval.adoc
  downstream/modules/hub/con-namespaces.adoc
  downstream/modules/hub/proc-approve-collection.adoc
  downstream/modules/hub/proc-create-content-developers.adoc
  downstream/modules/hub/proc-reject-collections.adoc
  downstream/modules/hub/proc-uploading-collections.adoc
  downstream/titles/hub/managing-content/master.adoc
Labels: Ready for review, Docathon

#385 AAP 15788 [HubDocathon] Chapter 4 of the Getting started with automation hub guide
  downstream/modules/hub/proc-delete-collection.adoc
  downstream/modules/hub/proc-upload-collection.adoc
Labels: Ready for review, Draft, Docathon, Needs backport to 2.4, 2.4

#384 [HubDocathon] Created 'Managing Content' Chapter 1
  downstream/assemblies/hub/assembly-faq.adoc
  downstream/assemblies/hub/assembly-managing-cert-valid-content.adoc
  downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc
  downstream/assemblies/hub/assembly-synclists.adoc
  downstream/assemblies/hub/assembly-validated-content.adoc
  downstream/modules/hub/proc-configure-ansible-galaxy-cli-verify.adoc
  downstream/modules/hub/proc-downloading-signature-public-keys.adoc
  downstream/modules/hub/proc-set-community-remote.adoc
  downstream/modules/hub/proc-set-rhcertified-remote.adoc
  downstream/modules/hub/proc-using-content-signing-services-in-pah.adoc
Labels: documentation, Ready for review, Docathon

#379 Create section 4 'Subscriptions' of the Controller UG
  downstream/assemblies/platform/assembly-controller-managing-subscriptions.adoc
  downstream/images/aap-subscriptions.png
  downstream/images/subscription-allocations-create.png
  downstream/images/subscription-allocations-details-bottom.png
  downstream/images/subscription-allocations-empty.png
  downstream/images/ug-host-metrics-awx-manage-config.png
  downstream/images/ug-host-metrics.png
  downstream/modules/platform/con-controller-host-metric-utilities.adoc
  downstream/modules/platform/con-controller-keep-subscription-in-compliance.adoc
  downstream/modules/platform/proc-controller-adding-subscription-manually.adoc
  downstream/modules/platform/proc-controller-api-endpoint-functions.adoc
  downstream/modules/platform/proc-controller-attaching-subscriptions.adoc
  downstream/modules/platform/proc-controller-awx-manage-utility.adoc
  downstream/modules/platform/proc-controller-importing-subscriptions.adoc
  downstream/modules/platform/proc-controller-obtaining-subscriptions-manifest.adoc
  downstream/modules/platform/proc-controller-obtaining-subscriptions.adoc
  downstream/modules/platform/ref-controller-subscription-types.adoc
  downstream/titles/controller/controller-user-guide/master.adoc
Labels: documentation, Needs backport to 2.4, Ready for technical review, Controller, 2.4

#393 Create section 4 'Subscriptions' of the Controller UG (#379)
  downstream/assemblies/platform/assembly-controller-managing-subscriptions.adoc
  downstream/images/aap-subscriptions.png
  downstream/images/subscription-allocations-create.png
  downstream/images/subscription-allocations-details-bottom.png
  downstream/images/subscription-allocations-empty.png
  downstream/images/ug-host-metrics-awx-manage-config.png
  downstream/images/ug-host-metrics.png
  downstream/modules/platform/con-controller-host-metric-utilities.adoc
  downstream/modules/platform/con-controller-keep-subscription-in-compliance.adoc
  downstream/modules/platform/proc-controller-adding-subscription-manually.adoc
  downstream/modules/platform/proc-controller-api-endpoint-functions.adoc
  downstream/modules/platform/proc-controller-attaching-subscriptions.adoc
  downstream/modules/platform/proc-controller-awx-manage-utility.adoc
  downstream/modules/platform/proc-controller-importing-subscriptions.adoc
  downstream/modules/platform/proc-controller-obtaining-subscriptions-manifest.adoc
  downstream/modules/platform/proc-controller-obtaining-subscriptions.adoc
  downstream/modules/platform/ref-controller-subscription-types.adoc
  downstream/titles/controller/controller-user-guide/master.adoc
Labels: Controller, 2.4

#394 Replace link description of automation controller with automation hub
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
Labels: Ready for review, Needs backport to 2.4, Needs backport to 2.3

#391 AAP-15785: Revised titles and sections
  downstream/assemblies/hub/assembly-user-access.adoc
  downstream/assemblies/hub/assembly-view-only-access.adoc
  downstream/modules/hub/con-enable-view-only.adoc
  downstream/modules/hub/con-user-access.adoc
  downstream/modules/hub/proc-create-content-developers.adoc
  downstream/modules/hub/proc-create-groups.adoc
Labels: Docathon, Peer review complete, Automation Hub, 2.4

#401 AAP-15782 - Added overview and clarification between AH and PAH
  downstream/assemblies/hub/assembly-hub-overview.adoc
Labels: documentation, Ready for review

#390 AAP-15759: Docathon updates to Repo Management ch. 2 pt. 2
  downstream/assemblies/hub/assembly-repo-management.adoc
  downstream/modules/hub/con-approval-pipeline.adoc
  downstream/modules/hub/con-repo-rbac.adoc
  downstream/modules/hub/proc-adding-collections-repository.adoc
  downstream/modules/hub/proc-create-repository.adoc
  downstream/modules/hub/proc-provide-repository-access.adoc
  downstream/modules/hub/proc-revert-repository-version.adoc
Labels: Docathon

#400 AAP-15795: Docathon edits to remote management sections
  downstream/assemblies/hub/assembly-repo-sync.adoc
  downstream/modules/hub/proc-basic-repo-sync.adoc
  downstream/modules/hub/proc-create-remote.adoc
  downstream/modules/hub/proc-export-collection.adoc
  downstream/modules/hub/proc-import-collection.adoc
  downstream/modules/hub/proc-provide-remote-access.adoc
Labels: Ready for review, Docathon

#388 AAP-15796
  downstream/assemblies/hub/assembly-container-user-access.adoc
  downstream/assemblies/hub/assembly-delete-container.adoc
  downstream/assemblies/hub/assembly-managing-container-registry.adoc
  downstream/assemblies/hub/assembly-managing-containers-hub.adoc
  downstream/assemblies/hub/assembly-populate-container-registry.adoc
  downstream/assemblies/hub/assembly-working-with-signed-containers.adoc
  downstream/modules/hub/con-container-registry.adoc
  downstream/modules/hub/proc-add-container-readme.adoc
  downstream/modules/hub/proc-add-group-to-container-repo.adoc
  downstream/modules/hub/proc-add-user-to-group.adoc
  downstream/modules/hub/proc-adding-an-execution-environment.adoc
  downstream/modules/hub/proc-adding-containers-remotely-to-the-automation-hub.adoc
  downstream/modules/hub/proc-assigning-permissions.adoc
  downstream/modules/hub/proc-configuring-the-client-to-verify-signatures.adoc
  downstream/modules/hub/proc-create-credential.adoc
  downstream/modules/hub/proc-create-groups.adoc
  downstream/modules/hub/proc-delete-container.adoc
  downstream/modules/hub/proc-deploying-your-system-for-container-signing.adoc
  downstream/modules/hub/proc-obtain-images.adoc
  downstream/modules/hub/proc-pull-image.adoc
  downstream/modules/hub/proc-pushing-container-images-from-your-local.adoc
  downstream/modules/hub/proc-sync-image.adoc
  downstream/modules/hub/proc-tag-image.adoc
  downstream/modules/hub/proc-tag-pulled-image.adoc
  downstream/modules/hub/proc-using-podman-ensure-image-signed.adoc
  downstream/modules/hub/proc-using-policies-with-signed-images.adoc
Labels: Docathon

#399 AAP-15793-a Docathon: Managing Collections in AH
  downstream/modules/hub/proc-approve-collection.adoc
  downstream/modules/hub/proc-create-content-developers.adoc
  downstream/modules/hub/proc-reject-collections.adoc
Labels: Draft, Docathon

#403 Update hybrid nodes table to add more clarity
  downstream/modules/platform/ref-system-requirements.adoc
Labels: Ready for review, Needs backport to 2.1

#406 Making edits to UI as per test environment
  downstream/assemblies/hub/assembly-repo-management.adoc
  downstream/assemblies/hub/assembly-user-access.adoc
  downstream/modules/hub/con-user-access.adoc
  downstream/modules/hub/proc-add-user-to-group.adoc
  downstream/modules/hub/proc-adding-collections-repository.adoc
  downstream/modules/hub/proc-approve-collection.adoc
  downstream/modules/hub/proc-basic-repo-sync.adoc
  downstream/modules/hub/proc-create-api-token.adoc
  downstream/modules/hub/proc-create-content-developers.adoc
  downstream/modules/hub/proc-create-groups.adoc
  downstream/modules/hub/proc-create-namespace.adoc
  downstream/modules/hub/proc-create-remote.adoc
  downstream/modules/hub/proc-create-repository.adoc
  downstream/modules/hub/proc-create-super-users.adoc
  downstream/modules/hub/proc-create-users.adoc
  downstream/modules/hub/proc-delete-namespace.adoc
  downstream/modules/hub/proc-delete-user.adoc
  downstream/modules/hub/proc-edit-namespace.adoc
  downstream/modules/hub/proc-export-collection.adoc
  downstream/modules/hub/proc-import-collection.adoc
  downstream/modules/hub/proc-provide-remote-access.adoc
  downstream/modules/hub/proc-provide-repository-access.adoc
  downstream/modules/hub/proc-reject-collections.adoc
  downstream/modules/hub/proc-revert-repository-version.adoc
  downstream/modules/hub/proc-review-collection-imports.adoc
  downstream/modules/hub/proc-set-community-remote.adoc
  downstream/modules/hub/proc-set-rhcertified-remote.adoc
  downstream/modules/hub/proc-uploading-collections.adoc
  downstream/modules/hub/ref-permissions.adoc
Labels: Docathon

#407 Minor change in installation line
  downstream/modules/platform/proc-installing-containerized-aap.adoc
Labels: Needs backport to 2.4, 2.4

#408 Minor change in installation line (#407)
  downstream/modules/platform/proc-installing-containerized-aap.adoc
Labels: Backported to 2.4, 2.4

#413 AAP-15802 Updated automation hub scenario to include info on RHSSO install
  downstream/modules/platform/ref-standalone-hub-inventory.adoc
  downstream/titles/aap-installation-guide/master.adoc
Labels: Ready for review, 2.4

#397 Create 'User Interface' section of Controller UG
  downstream/assemblies/platform/assembly-controller-search.adoc
  downstream/assemblies/platform/assembly-controller-user-interface.adoc
  downstream/images/activity-stream-event-log.png
  downstream/images/activitystream.png
  downstream/images/examine.png
  downstream/images/leftpencil.png
  downstream/images/search.png
  downstream/images/ug-dashboard-job-activity.png
  downstream/images/ug-dashboard-jobs-view.png
  downstream/images/ug-dashboard-recent-jobs.png
  downstream/images/ug-dashboard-recent-templates.png
  downstream/images/ug-dashboard-schedule-view.png
  downstream/images/users-activity-stream.png
  downstream/modules/platform/con-controller-access.adoc
  downstream/modules/platform/con-controller-administration.adoc
  downstream/modules/platform/con-controller-overview-details.adoc
  downstream/modules/platform/con-controller-resources.adoc
  downstream/modules/platform/con-controller-settings.adoc
  downstream/modules/platform/con-controller-views.adoc
  downstream/modules/platform/proc-controller-activity-stream.adoc
  downstream/modules/platform/proc-controller-awx-manage-utility.adoc
  downstream/modules/platform/proc-controller-host-metrics.adoc
  downstream/modules/platform/proc-controller-jobs-view.adoc
  downstream/modules/platform/proc-controller-obtaining-subscriptions-manifest.adoc
  downstream/modules/platform/proc-controller-schedules-view.adoc
  downstream/modules/platform/proc-controller-viewing-dashboard.adoc
  downstream/modules/platform/proc-controller-workflow-approvals.adoc
  downstream/titles/controller/controller-user-guide/master.adoc
Labels: Ready for review, Needs backport to 2.4, Controller, 2.4

#416 Create 'User Interface' section of Controller UG (#397)
  downstream/assemblies/platform/assembly-controller-search.adoc
  downstream/assemblies/platform/assembly-controller-user-interface.adoc
  downstream/images/activity-stream-event-log.png
  downstream/images/activitystream.png
  downstream/images/examine.png
  downstream/images/leftpencil.png
  downstream/images/search.png
  downstream/images/ug-dashboard-job-activity.png
  downstream/images/ug-dashboard-jobs-view.png
  downstream/images/ug-dashboard-recent-jobs.png
  downstream/images/ug-dashboard-recent-templates.png
  downstream/images/ug-dashboard-schedule-view.png
  downstream/images/users-activity-stream.png
  downstream/modules/platform/con-controller-access.adoc
  downstream/modules/platform/con-controller-administration.adoc
  downstream/modules/platform/con-controller-overview-details.adoc
  downstream/modules/platform/con-controller-resources.adoc
  downstream/modules/platform/con-controller-settings.adoc
  downstream/modules/platform/con-controller-views.adoc
  downstream/modules/platform/proc-controller-activity-stream.adoc
  downstream/modules/platform/proc-controller-awx-manage-utility.adoc
  downstream/modules/platform/proc-controller-host-metrics.adoc
  downstream/modules/platform/proc-controller-jobs-view.adoc
  downstream/modules/platform/proc-controller-obtaining-subscriptions-manifest.adoc
  downstream/modules/platform/proc-controller-schedules-view.adoc
  downstream/modules/platform/proc-controller-viewing-dashboard.adoc
  downstream/modules/platform/proc-controller-workflow-approvals.adoc
  downstream/titles/controller/controller-user-guide/master.adoc
Labels: Controller, 2.4

#417 Reword About the Ansible command line interface to improve clarity
  downstream/modules/core/con-about-ansible-cli.adoc
Labels: Ready for review, Needs backport to 2.4, Needs backport to 2.3, Needs backport to 2.2, Needs backport to 2.1

#422 Added login lines for hub and EDA in accessing section. Clarified pat…
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/platform/ref-accessing-control-auto-hub-eda-control.adoc
Labels: Needs backport to 2.4, 2.4

#424 Added login lines for hub and EDA in accessing section. Clarified pat…
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/platform/ref-accessing-control-auto-hub-eda-control.adoc
Labels: Backported to 2.4

#426 Corrected login names for hub and eda. Added an uninstallation section.
  downstream/modules/platform/ref-accessing-control-auto-hub-eda-control.adoc
Labels: Needs backport to 2.4, 2.4

#427 Corrected login names for hub and eda. Added an uninstallation sectio…
  downstream/modules/platform/ref-accessing-control-auto-hub-eda-control.adoc
Labels: Backported to 2.4, 2.4

#398 AAP-13785 New minimum requirement for EDA controller section
  downstream/assemblies/platform/assembly-system-requirements.adoc
  downstream/modules/platform/ref-eda-system-requirements.adoc
Labels: Ready for review, Needs backport to 2.4, 2.4

#429 AAP-15686: Add edited network ports diagram
  downstream/images/aap-network-ports-protocols-314.png
  downstream/modules/aap-hardening/con-network-firewall-services-planning.adoc
Labels: AAP Hardening, Ready for review, Needs backport to 2.4, 2.4

#430 [2.4] AAP-15686 Add edited network ports diagram #429
  downstream/images/aap-network-ports-protocols-314.png
  downstream/modules/aap-hardening/con-network-firewall-services-planning.adoc
Labels: AAP Hardening, Ready for review, Backported to 2.4, 2.4

#431 Remove duplicate content from Platform Planning Guide
  downstream/modules/platform/ref-postgresql-requirements.adoc
Labels: Ready for review, Needs backport to 2.4, Needs backport to 2.3

#409 Adding Credentials chapter to EDA user guide
  downstream/assemblies/eda/assembly-eda-credentials.adoc
  downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc
  downstream/modules/eda/con-credentials-list-view.adoc
  downstream/modules/eda/proc-eda-delete-credential.adoc
  downstream/modules/eda/proc-eda-edit-credential.adoc
  downstream/modules/eda/proc-eda-set-up-credential.adoc
  downstream/modules/eda/proc-eda-set-up-new-decision-environment.adoc
  downstream/modules/eda/proc-eda-set-up-new-project.adoc
  downstream/titles/eda/eda-user-guide/docinfo.xml
  downstream/titles/eda/eda-user-guide/master.adoc
Labels: Ready for review, Needs backport to 2.4, Technical review complete, 2.4

#435 Adding Credentials chapter to EDA user guide (#409)
  downstream/assemblies/eda/assembly-eda-credentials.adoc
  downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc
  downstream/modules/eda/con-credentials-list-view.adoc
  downstream/modules/eda/proc-eda-delete-credential.adoc
  downstream/modules/eda/proc-eda-edit-credential.adoc
  downstream/modules/eda/proc-eda-set-up-credential.adoc
  downstream/modules/eda/proc-eda-set-up-new-decision-environment.adoc
  downstream/modules/eda/proc-eda-set-up-new-project.adoc
  downstream/titles/eda/eda-user-guide/docinfo.xml
  downstream/titles/eda/eda-user-guide/master.adoc
Labels: 2.4

#436 Editing title in EDA user guide
  downstream/assemblies/eda/assembly-eda-set-up-token.adoc
  downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc
Labels: Needs backport to 2.4, 2.4

#412 AAP-15803 modified planning guide master and module
  downstream/assemblies/hub/assembly-high-availability-hub-requirements.adoc
  downstream/assemblies/platform/assembly-aap-platform-components.adoc
  downstream/assemblies/platform/assembly-deploy-high-availability-hub.adoc
  downstream/assemblies/platform/assembly-installing-high-availability-hub.adoc
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
  downstream/assemblies/platform/assembly-system-requirements.adoc
  downstream/modules/hub/con-network-storage-reqs.adoc
  downstream/modules/hub/con-required-shared-filesystem.adoc
  downstream/modules/platform/con-about-ha-hub.adoc
  downstream/modules/platform/con-ha-hub-installation.adoc
  downstream/modules/platform/proc-install-ha-hub-selinux.adoc
  downstream/modules/platform/ref-automation-hub-requirements.adoc
  downstream/modules/platform/ref-ha-hub-reqs.adoc
  downstream/titles/aap-installation-guide/master.adoc
Labels: Docathon, 2.4

#444 Managing collections chapter - editorial review
  downstream/archive/archived-modules/con-namespaces.adoc
  downstream/assemblies/hub/assembly-managing-collections-hub.adoc
  downstream/assemblies/hub/assembly-managing-private-collections.adoc
  downstream/assemblies/hub/assembly-working-with-namespaces.adoc
  downstream/modules/hub/con-approval.adoc
  downstream/modules/hub/proc-approve-collection.adoc
  downstream/modules/hub/proc-create-content-developers.adoc
  downstream/modules/hub/proc-create-namespace.adoc
  downstream/modules/hub/proc-delete-namespace.adoc
  downstream/modules/hub/proc-edit-namespace.adoc
  downstream/modules/hub/proc-reject-collections.adoc
  downstream/modules/hub/proc-review-collection-imports.adoc
  downstream/modules/hub/proc-uploading-collections.adoc
Labels: Ready for review, Docathon

#440 it-15782 - Incorporated changes based on editorial review
  downstream/assemblies/hub/assembly-configure-hub-primary.adoc
  downstream/assemblies/hub/assembly-hub-create-api-token.adoc
  downstream/assemblies/hub/assembly-hub-overview.adoc
  downstream/modules/hub/con-offline-token-active.adoc
  downstream/modules/hub/proc-configure-automation-hub-server-cli.adoc
  downstream/modules/hub/proc-configure-automation-hub-server-gui.adoc
  downstream/modules/hub/proc-create-api-token-pah.adoc
  downstream/modules/hub/proc-create-api-token.adoc
  downstream/titles/hub/getting-started/master.adoc
Labels: Ready for review, Docathon

#447 AAP-15788A Applied updates from editorial review for original branch AAP-15788 / PR #385
  downstream/assemblies/hub/assembly-uploading-content-hub.adoc
  downstream/modules/hub/proc-delete-collection.adoc
  downstream/modules/hub/proc-upload-collection.adoc
Labels: Ready for review, Docathon, Needs backport to 2.4

#439 Editorial corrections to first chapter of Managing Content Guide
  downstream/assemblies/hub/assembly-collections-and-content-signing-in-pah.adoc
  downstream/assemblies/hub/assembly-faq.adoc
  downstream/assemblies/hub/assembly-managing-cert-valid-content.adoc
  downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc
  downstream/assemblies/hub/assembly-synclists.adoc
  downstream/assemblies/hub/assembly-validated-content.adoc
  downstream/modules/hub/con-rh-certified-synclist.adoc
  downstream/modules/hub/proc-configure-ansible-galaxy-cli-verify.adoc
  downstream/modules/hub/proc-configure-content-signing-on-pah.adoc
  downstream/modules/hub/proc-create-synclist.adoc
  downstream/modules/hub/proc-downloading-signature-public-keys.adoc
  downstream/modules/hub/proc-obtaining-org-collection-url.adoc
  downstream/modules/hub/proc-set-community-remote.adoc
  downstream/modules/hub/proc-set-rhcertified-remote.adoc
  downstream/modules/hub/proc-using-content-signing-services-in-pah.adoc
Labels: documentation, Docathon, Needs backport to 2.4, 2.4

#303 Create self-managed AAP on Azure docs
  attributes/attributes.adoc
  stories/assembly-smazure-intro.adoc
  titles/sm-aap-on-azure/aap-common
  titles/sm-aap-on-azure/attributes
  titles/sm-aap-on-azure/images
  titles/sm-aap-on-azure/sm-aap-on-azure.asciidoc
  titles/sm-aap-on-azure/stories
  titles/sm-aap-on-azure/stories.adoc
Labels: AAP on clouds, Draft, self-managed AAP on Azure

#425 Create 'Organizations' section of Controller UG
  downstream/assemblies/platform/assembly-controller-organizations.adoc
  downstream/images/disassociate.png
  downstream/images/organizations-add-users-for-example-organization.png
  downstream/images/organizations-add-users-roles.png
  downstream/images/organizations-home-showing-example-organization.png
  downstream/images/organizations-max-hosts-error-output-view.png
  downstream/images/organizations-new-organization-form.png
  downstream/images/organizations-notifications-samples-list.png
  downstream/images/organizations-show-record-for-example-organization.png
  downstream/images/organizations-show-users-permissions-organization.png
  downstream/images/warning-deletion-dependencies.png
  downstream/modules/platform/con-controller-access-organizations.adoc
  downstream/modules/platform/proc-controller-add-organization-user.adoc
  downstream/modules/platform/proc-controller-create-organization.adoc
  downstream/modules/platform/ref-controller-organization-notifications.adoc
  downstream/titles/controller/controller-user-guide/master.adoc
Labels: documentation, Needs backport to 2.4, Not ready for peer review, Controller, 2.4

#434 Editorial review edits
  downstream/assemblies/hub/assembly-container-user-access.adoc
  downstream/assemblies/hub/assembly-delete-container.adoc
  downstream/assemblies/hub/assembly-managing-container-registry.adoc
  downstream/assemblies/hub/assembly-managing-containers-hub.adoc
  downstream/assemblies/hub/assembly-populate-container-registry.adoc
  downstream/assemblies/hub/assembly-pull-image.adoc
  downstream/assemblies/hub/assembly-setup-container-repository.adoc
  downstream/assemblies/hub/assembly-working-with-signed-containers.adoc
  downstream/modules/hub/proc-add-container-readme.adoc
  downstream/modules/hub/proc-add-group-to-container-repo.adoc
  downstream/modules/hub/proc-add-user-to-group.adoc
  downstream/modules/hub/proc-adding-an-execution-environment.adoc
  downstream/modules/hub/proc-adding-containers-remotely-to-the-automation-hub.adoc
  downstream/modules/hub/proc-assigning-permissions.adoc
  downstream/modules/hub/proc-configuring-the-client-to-verify-signatures.adoc
  downstream/modules/hub/proc-create-credential.adoc
  downstream/modules/hub/proc-create-groups.adoc
  downstream/modules/hub/proc-deploying-your-system-for-container-signing.adoc
  downstream/modules/hub/proc-obtain-images.adoc
  downstream/modules/hub/proc-pull-image.adoc
  downstream/modules/hub/proc-push-container.adoc
  downstream/modules/hub/proc-pushing-container-images-from-your-local.adoc
  downstream/modules/hub/proc-sync-image.adoc
  downstream/modules/hub/proc-tag-image.adoc
  downstream/modules/hub/proc-using-policies-with-signed-images.adoc
  downstream/modules/hub/ref-container-permissions.adoc
Labels: Docathon

#450 Create 'Organizations' section of Controller UG (#425)
  downstream/assemblies/platform/assembly-controller-organizations.adoc
  downstream/images/disassociate.png
  downstream/images/organizations-add-users-for-example-organization.png
  downstream/images/organizations-add-users-roles.png
  downstream/images/organizations-home-showing-example-organization.png
  downstream/images/organizations-max-hosts-error-output-view.png
  downstream/images/organizations-new-organization-form.png
  downstream/images/organizations-notifications-samples-list.png
  downstream/images/organizations-show-record-for-example-organization.png
  downstream/images/organizations-show-users-permissions-organization.png
  downstream/images/warning-deletion-dependencies.png
  downstream/modules/platform/con-controller-access-organizations.adoc
  downstream/modules/platform/proc-controller-add-organization-user.adoc
  downstream/modules/platform/proc-controller-create-organization.adoc
  downstream/modules/platform/ref-controller-organization-notifications.adoc
  downstream/titles/controller/controller-user-guide/master.adoc
Labels: documentation, Controller, 2.4

#405 AAP-16032: Docathon updates to Disconnected Installation chapter
  downstream/assemblies/platform/assembly-disconnected-installation.adoc
  downstream/modules/platform/con-aap-installation-on-disconnected-rhel.adoc
  downstream/modules/platform/proc-accessing-rpm-repositories-for-locally-mounted-dvd.adoc
  downstream/modules/platform/proc-adding-a-subscription-manifest-to-aap-without-an-internet-connection.adoc
  downstream/modules/platform/proc-completing-post-installation-tasks.adoc
  downstream/modules/platform/proc-creating-a-new-web-server-to-host-repositories.adoc
  downstream/modules/platform/proc-installing-the-aap-setup-bundle.adoc
  downstream/modules/platform/proc-synchronizing-rpm-repositories-by-using-reposync.adoc
Labels: Ready for review

#448 AAP-15785-Revisions: Revisions based on editorial review
  downstream/assemblies/hub/assembly-view-only-access.adoc
  downstream/modules/hub/con-enable-view-only.adoc
  downstream/modules/hub/con-user-access.adoc
  downstream/modules/hub/proc-add-user-to-group.adoc
  downstream/modules/hub/proc-assigning-permissions.adoc
  downstream/modules/hub/proc-create-content-developers.adoc
  downstream/modules/hub/proc-create-groups.adoc
  downstream/modules/hub/proc-create-super-users.adoc
  downstream/modules/hub/proc-create-users.adoc
  downstream/modules/hub/ref-permissions.adoc
Labels: Ready for review, Docathon, Automation Hub

#415 AAP-16032: Docathon edits to Disconnected Installation chapter pt. 2
  downstream/modules/platform/con-building-an-execution-environment-in-a-disconnected-environment.adoc
  downstream/modules/platform/proc-approving-the-imported-collection.adoc
  downstream/modules/platform/proc-creating-collection-namespace.adoc
  downstream/modules/platform/proc-importing-collections-into-private-automation-hub.adoc
  downstream/modules/platform/proc-installing-the-ansible-builder-rpm.adoc
Labels: Ready for review, Docathon

#459 Backport-2.4-398 AAP-13785 New minimum requirement for EDA controller section
  downstream/assemblies/platform/assembly-system-requirements.adoc
  downstream/modules/platform/ref-eda-system-requirements.adoc
Labels: Ready for review, Backported to 2.4, 2.4

#456 Create 'Users' section of Controller UG
  downstream/assemblies/platform/assembly-controller-users.adoc
  downstream/images/users-add-permissions-form.png
  downstream/images/users-create-user-form-types.png
  downstream/images/users-edit-user-form.png
  downstream/images/users-home-users-checked-delete.png
  downstream/images/users-organizations-list-for-example-user.png
  downstream/images/users-permissions-IG-roles.png
  downstream/images/users-permissions-IG-select.png
  downstream/images/users-permissions-list-for-example-user.png
  downstream/images/users-token-assignment-example.png
  downstream/images/users-token-information-example.png
  downstream/modules/platform/con-controller-create-users.adoc
  downstream/modules/platform/proc-controller-add-organization-user.adoc
  downstream/modules/platform/proc-controller-creating-a-user.adoc
  downstream/modules/platform/proc-controller-deleting-a-user.adoc
  downstream/modules/platform/proc-controller-user-permissions.adoc
  downstream/modules/platform/proc-controller-user-tokens.adoc
  downstream/modules/platform/ref-controller-user-organizations.adoc
  downstream/modules/platform/ref-controller-user-roles.adoc
  downstream/modules/platform/ref-controller-user-teams.adoc
  downstream/titles/controller/controller-user-guide/master.adoc
Labels: Ready for review, Needs backport to 2.4, Controller, 2.4

#461 Create 'Users' section of Controller UG (#456)
  downstream/assemblies/platform/assembly-controller-users.adoc
  downstream/images/users-add-permissions-form.png
  downstream/images/users-create-user-form-types.png
  downstream/images/users-edit-user-form.png
  downstream/images/users-home-users-checked-delete.png
  downstream/images/users-organizations-list-for-example-user.png
  downstream/images/users-permissions-IG-roles.png
  downstream/images/users-permissions-IG-select.png
  downstream/images/users-permissions-list-for-example-user.png
  downstream/images/users-token-assignment-example.png
  downstream/images/users-token-information-example.png
  downstream/modules/platform/con-controller-create-users.adoc
  downstream/modules/platform/proc-controller-add-organization-user.adoc
  downstream/modules/platform/proc-controller-creating-a-user.adoc
  downstream/modules/platform/proc-controller-deleting-a-user.adoc
  downstream/modules/platform/proc-controller-user-permissions.adoc
  downstream/modules/platform/proc-controller-user-tokens.adoc
  downstream/modules/platform/ref-controller-user-organizations.adoc
  downstream/modules/platform/ref-controller-user-roles.adoc
  downstream/modules/platform/ref-controller-user-teams.adoc
  downstream/titles/controller/controller-user-guide/master.adoc
Labels: documentation, Controller, 2.4

#464 Improve automation content navigator frequently asked questions section
  downstream/modules/navigator/ref-faq-navigator.adoc
Labels: Needs backport to 2.4

#462 Create section 21 "Job Templates" of the Controller UG (#414)
  downstream/assemblies/platform/assembly-controller-inventory-templates.adoc
  downstream/assemblies/platform/assembly-ug-controller-job-templates.adoc
  downstream/images/ug-Variable_Precedence_Hierarchy.png
  downstream/images/ug-job-template-become.png
  downstream/images/ug-job-template-completed-jobs-view.png
  downstream/images/ug-job-template-completed-notifications-view.png
  downstream/images/ug-job-template-create-survey.png
  downstream/images/ug-job-template-details.png
  downstream/images/ug-job-template-launch.png
  downstream/images/ug-job-template-rearrange-survey.png
  downstream/images/ug-job-templates-home.png
  downstream/images/ug-job-templates-options-use-factcache.png
  downstream/images/ug-job-templates-options-webhooks.png
  downstream/images/ug-job-templates-schedules.png
  downstream/images/ug-jobs-fact-cache-timeout.png
  downstream/images/ug-organizations-add-users-for-example-organization.png
  downstream/images/ug-permissions-tab-roles-assigned.png
  downstream/images/ug-provisioning-callbacks-config.png
  downstream/images/ug-sliced-job-shown-jobs-list-view.png
  downstream/images/ug-warning-deletion.png
  downstream/modules/platform/con-controller-benefits-fact-caching.adoc
  downstream/modules/platform/con-controller-cloud-credentials.adoc
  downstream/modules/platform/con-controller-fact-caching.adoc
  downstream/modules/platform/con-controller-fact-scan-job-templates.adoc
  downstream/modules/platform/con-controller-provisioning-callbacks.adoc
  downstream/modules/platform/con-controller-relaunch-job-template.adoc
  downstream/modules/platform/con-controller-scheduling-job-templates.adoc
  downstream/modules/platform/con-controller-surveys.adoc
  downstream/modules/platform/con-controller-view-completed-jobs.adoc
  downstream/modules/platform/con-controller-work-with-notifications.adoc
  downstream/modules/platform/proc-controller-adding-permissions.adoc
  downstream/modules/platform/proc-controller-copy-a-job-template.adoc
  downstream/modules/platform/proc-controller-create-job-template.adoc
  downstream/modules/platform/proc-controller-create-survey.adoc
  downstream/modules/platform/proc-controller-delete-job-template.adoc
  downstream/modules/platform/proc-controller-enable-provision-callbacks.adoc
  downstream/modules/platform/proc-controller-launch-job-template.adoc
  downstream/modules/platform/proc-controller-pass-extra-variables-provisioning-callbacks.adoc
  downstream/modules/platform/ref-controller-aws-cloud.adoc
  downstream/modules/platform/ref-controller-azure-cloud.adoc
  downstream/modules/platform/ref-controller-custom-fact-scans.adoc
  downstream/modules/platform/ref-controller-extra-variables.adoc
  downstream/modules/platform/ref-controller-fact-scan-playbooks.adoc
  downstream/modules/platform/ref-controller-google-cloud.adoc
  downstream/modules/platform/ref-controller-job-template-variables.adoc
  downstream/modules/platform/ref-controller-openstack-cloud.adoc
  downstream/modules/platform/ref-controller-optional-survey-questions.adoc
  downstream/modules/platform/ref-controller-pre-scan-setup.adoc
  downstream/modules/platform/ref-controller-supported-oses.adoc
  downstream/modules/platform/ref-controller-vmware-cloud.adoc
  downstream/titles/controller/controller-user-guide/master.adoc
Labels: 2.4

#463 Create 'Teams' section for Controller UG
  downstream/assemblies/platform/assembly-controller-organizations.adoc
  downstream/assemblies/platform/assembly-controller-teams.adoc
  downstream/assemblies/platform/assembly-controller-users.adoc
  downstream/images/organizations-teams-list.png
  downstream/images/rightrocket.png
  downstream/images/teams-create-new-team.png
  downstream/images/teams-example-team-successfully-created.png
  downstream/images/teams-permissions-sample-roles.png
  downstream/images/teams-permissions-template-roles.png
  downstream/images/teams-permissions-templates-select.png
  downstream/images/teams-users-add-permissions-form.png
  downstream/images/visualizer.png
  downstream/modules/platform/proc-controller-creating-a-team.adoc
  downstream/modules/platform/proc-controller-team-add-permissions.adoc
  downstream/modules/platform/proc-controller-team-add-user.adoc
  downstream/modules/platform/ref-controller-team-access.adoc
  downstream/modules/platform/ref-controller-team-roles.adoc
  downstream/titles/controller/controller-user-guide/master.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#467 Create 'Teams' section for Controller UG (#463)
  downstream/assemblies/platform/assembly-controller-organizations.adoc
  downstream/assemblies/platform/assembly-controller-teams.adoc
  downstream/assemblies/platform/assembly-controller-users.adoc
  downstream/images/organizations-teams-list.png
  downstream/images/rightrocket.png
  downstream/images/teams-create-new-team.png
  downstream/images/teams-example-team-successfully-created.png
  downstream/images/teams-permissions-sample-roles.png
  downstream/images/teams-permissions-template-roles.png
  downstream/images/teams-permissions-templates-select.png
  downstream/images/teams-users-add-permissions-form.png
  downstream/images/visualizer.png
  downstream/modules/platform/proc-controller-creating-a-team.adoc
  downstream/modules/platform/proc-controller-team-add-permissions.adoc
  downstream/modules/platform/proc-controller-team-add-user.adoc
  downstream/modules/platform/ref-controller-team-access.adoc
  downstream/modules/platform/ref-controller-team-roles.adoc
  downstream/titles/controller/controller-user-guide/master.adoc
Labels: documentation, Controller, 2.4

#465 Improve automation content navigator frequently asked questions secti…
  downstream/modules/navigator/ref-faq-navigator.adoc
Labels: 2.4

#476 Add script for self-managed Azure sync to prod repo
  bin/sync_cloud_docs.sh
Labels: AAP on clouds, self-managed AAP on Azure

#481 Correct variable typo for automationhub_pg_password
  downstream/assemblies/platform/assembly-install-upgrade-pah.adoc
  downstream/modules/central-auth/proc-aap-configure-centralauth.adoc
Labels: Needs backport to 2.4, Needs backport to 2.3, Needs backport to 2.2

#484 Correct variable typo for automationhub_pg_password (#481)
  downstream/modules/central-auth/proc-aap-configure-centralauth.adoc
  downstream/titles/hub/install/master.adoc
Labels: 2.4

#483 Correct variable typo for automationhub_pg_password (#481)
  downstream/modules/central-auth/proc-aap-configure-centralauth.adoc
  downstream/titles/hub/install/master.adoc
Labels: 2.3

#479 [EDA] Adding pull policy admonition
  downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc
Labels: Ready for review, Needs backport to 2.4, Technical review complete, 2.4

#475 Create section 23 "Workflows" of the Controller UG
  downstream/assemblies/platform/assembly-ug-controller-workflows.adoc
  downstream/images/ug-node-all-scenarios-wf.png
  downstream/images/ug-wf-node-convergence.png
  downstream/images/ug-wf-node-delete-scenario.png
  downstream/images/ug-wf-root-node-always.png
  downstream/images/ug-wf-sibling-nodes-all-edge-types.png
  downstream/images/ug-workflow-diagram.png
  downstream/modules/platform/con-controller-job-slice-considerations.adoc
  downstream/modules/platform/con-controller-role-based-access-controls.adoc
  downstream/modules/platform/con-controller-workflow-scenarios.adoc
  downstream/modules/platform/con-controller-workflow-states.adoc
  downstream/modules/platform/ref-controller-extra-variables.adoc
  downstream/modules/platform/ref-controller-workflows-extra-variables.adoc
  downstream/titles/controller/controller-user-guide/master.adoc
Labels: Ready for review, Needs backport to 2.4, Controller, 2.4

#469 Create 'Credentials' section of Controller UG
  downstream/assemblies/platform/assembly-controller-credentials.adoc
  downstream/attributes/attributes.adoc
  downstream/images/credential-types-drop-down-menu.png
  downstream/images/credentials-create-credential.png
  downstream/images/credentials-create-galaxy-credential.png
  downstream/images/credentials-demo-edit-details.png
  downstream/images/credentials-home-with-jt-detail.png
  downstream/images/credentials-home-with-permissions-detail.png
  downstream/images/job-template-completed-jobs-view.png
  downstream/images/teams-users-list.png
  downstream/modules/platform/con-controller-benefits-fact-caching.adoc
  downstream/modules/platform/con-controller-view-completed-jobs.adoc
  downstream/modules/platform/proc-controller-create-credential.adoc
  downstream/modules/platform/proc-controller-credential-create-openshift-account.adoc
  downstream/modules/platform/ref-controller-credential-GCE.adoc
  downstream/modules/platform/ref-controller-credential-GPG-public-key.adoc
  downstream/modules/platform/ref-controller-credential-aap.adoc
  downstream/modules/platform/ref-controller-credential-aws.adoc
  downstream/modules/platform/ref-controller-credential-azure-key.adoc
  downstream/modules/platform/ref-controller-credential-azure-resource.adoc
  downstream/modules/platform/ref-controller-credential-centrify-vault.adoc
  downstream/modules/platform/ref-controller-credential-container-registry.adoc
  downstream/modules/platform/ref-controller-credential-cyberark-central.adoc
  downstream/modules/platform/ref-controller-credential-cyberark-conjur.adoc
  downstream/modules/platform/ref-controller-credential-galaxy-hub.adoc
  downstream/modules/platform/ref-controller-credential-gitHub-pat.adoc
  downstream/modules/platform/ref-controller-credential-gitLab-pat.adoc
  downstream/modules/platform/ref-controller-credential-hashiCorp-secret.adoc
  downstream/modules/platform/ref-controller-credential-insights.adoc
  downstream/modules/platform/ref-controller-credential-machine.adoc
  downstream/modules/platform/ref-controller-credential-network.adoc
  downstream/modules/platform/ref-controller-credential-openShift.adoc
  downstream/modules/platform/ref-controller-credential-openStack.adoc
  downstream/modules/platform/ref-controller-credential-satellite.adoc
  downstream/modules/platform/ref-controller-credential-source-control.adoc
  downstream/modules/platform/ref-controller-credential-thycotic-server.adoc
  downstream/modules/platform/ref-controller-credential-thycotic-vault.adoc
  downstream/modules/platform/ref-controller-credential-types.adoc
  downstream/modules/platform/ref-controller-credential-vault.adoc
  downstream/modules/platform/ref-controller-credential-virtualization.adoc
  downstream/modules/platform/ref-controller-credential-vmware-vcenter.adoc
  downstream/modules/platform/ref-controller-credentials-getting-started.adoc
  downstream/modules/platform/ref-controlller-credential-hashiCorp-vault.adoc
  downstream/titles/controller/controller-user-guide/master.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#489 Create 'Credentials' section of Controller UG (#469)
  downstream/assemblies/platform/assembly-controller-credentials.adoc
  downstream/attributes/attributes.adoc
  downstream/images/credential-types-drop-down-menu.png
  downstream/images/credentials-create-credential.png
  downstream/images/credentials-create-galaxy-credential.png
  downstream/images/credentials-demo-edit-details.png
  downstream/images/credentials-home-with-jt-detail.png
  downstream/images/credentials-home-with-permissions-detail.png
  downstream/images/job-template-completed-jobs-view.png
  downstream/images/teams-users-list.png
  downstream/modules/platform/con-controller-benefits-fact-caching.adoc
  downstream/modules/platform/con-controller-view-completed-jobs.adoc
  downstream/modules/platform/proc-controller-create-credential.adoc
  downstream/modules/platform/proc-controller-credential-create-openshift-account.adoc
  downstream/modules/platform/ref-controller-credential-GCE.adoc
  downstream/modules/platform/ref-controller-credential-GPG-public-key.adoc
  downstream/modules/platform/ref-controller-credential-aap.adoc
  downstream/modules/platform/ref-controller-credential-aws.adoc
  downstream/modules/platform/ref-controller-credential-azure-key.adoc
  downstream/modules/platform/ref-controller-credential-azure-resource.adoc
  downstream/modules/platform/ref-controller-credential-centrify-vault.adoc
  downstream/modules/platform/ref-controller-credential-container-registry.adoc
  downstream/modules/platform/ref-controller-credential-cyberark-central.adoc
  downstream/modules/platform/ref-controller-credential-cyberark-conjur.adoc
  downstream/modules/platform/ref-controller-credential-galaxy-hub.adoc
  downstream/modules/platform/ref-controller-credential-gitHub-pat.adoc
  downstream/modules/platform/ref-controller-credential-gitLab-pat.adoc
  downstream/modules/platform/ref-controller-credential-hashiCorp-secret.adoc
  downstream/modules/platform/ref-controller-credential-insights.adoc
  downstream/modules/platform/ref-controller-credential-machine.adoc
  downstream/modules/platform/ref-controller-credential-network.adoc
  downstream/modules/platform/ref-controller-credential-openShift.adoc
  downstream/modules/platform/ref-controller-credential-openStack.adoc
  downstream/modules/platform/ref-controller-credential-satellite.adoc
  downstream/modules/platform/ref-controller-credential-source-control.adoc
  downstream/modules/platform/ref-controller-credential-thycotic-server.adoc
  downstream/modules/platform/ref-controller-credential-thycotic-vault.adoc
  downstream/modules/platform/ref-controller-credential-types.adoc
  downstream/modules/platform/ref-controller-credential-vault.adoc
  downstream/modules/platform/ref-controller-credential-virtualization.adoc
  downstream/modules/platform/ref-controller-credential-vmware-vcenter.adoc
  downstream/modules/platform/ref-controller-credentials-getting-started.adoc
  downstream/modules/platform/ref-controlller-credential-hashiCorp-vault.adoc
  downstream/titles/controller/controller-user-guide/master.adoc
Labels: documentation, Controller, 2.4

#491 AAP-16133 - Updating URLs to fix broken links from docathon retructuring
  downstream/assemblies/dev-guide/assembly-tools-components.adoc
  downstream/assemblies/hub/assembly-managing-cert-valid-content.adoc
  downstream/modules/aap-hardening/con-rbac.adoc
  downstream/modules/hub/con-repo-rbac.adoc
  downstream/modules/hub/proc-delete-namespace.adoc
  downstream/modules/hub/proc-provide-remote-access.adoc
  downstream/modules/hub/proc-provide-repository-access.adoc
  downstream/modules/hub/proc-set-community-remote.adoc
  downstream/modules/hub/proc-set-rhcertified-remote.adoc
  downstream/modules/platform/ref-hub-configs.adoc
  downstream/titles/hub/managing-content/docinfo.xml
  downstream/titles/hub/managing-content/master.adoc
Labels: Ready for review, Docathon, Needs backport to 2.4

#492 AAP-16133 [Backport] - Updating URLs to fix broken links from docathon
  downstream/assemblies/dev-guide/assembly-tools-components.adoc
  downstream/assemblies/hub/assembly-managing-cert-valid-content.adoc
  downstream/modules/aap-hardening/con-rbac.adoc
  downstream/modules/hub/con-repo-rbac.adoc
  downstream/modules/hub/proc-delete-namespace.adoc
  downstream/modules/hub/proc-provide-remote-access.adoc
  downstream/modules/hub/proc-provide-repository-access.adoc
  downstream/modules/hub/proc-set-community-remote.adoc
  downstream/modules/hub/proc-set-rhcertified-remote.adoc
  downstream/modules/platform/ref-hub-configs.adoc
  downstream/titles/hub/managing-content/docinfo.xml
  downstream/titles/hub/managing-content/master.adoc
Labels: Ready for review, Docathon, 2.4

#496 Correct typo of FQDN abbreviation
  downstream/modules/platform/con-install-scenario-examples.adoc
  downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
  downstream/modules/platform/ref-guidelines-hosts-groups.adoc
Labels: Ready for review, Needs backport to 2.4, Needs backport to 2.3, Needs backport to 2.2, Needs backport to 2.1

#497 Correct typo of FQDN abbreviation (#496)
  downstream/modules/platform/con-install-scenario-examples.adoc
  downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
  downstream/modules/platform/ref-guidelines-hosts-groups.adoc
Labels: 2.4

#498 Correct typo of FQDN abbreviation (#496)
  downstream/modules/platform/con-install-scenario-examples.adoc
  downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
  downstream/modules/platform/ref-guidelines-hosts-groups.adoc
Labels: 2.3

#499 Correct typo of FQDN abbreviation (#496)
  downstream/modules/platform/ref-guidelines-hosts-groups.adoc
  downstream/modules/platform/ref-standalone-hub-ext-database-inventory.adoc
  downstream/modules/platform/ref-standalone-hub-inventory.adoc
Labels: 2.2

#500 Correct typo of FQDN abbreviation (#496)
  downstream/modules/platform/ref-standalone-hub-ext-database-inventory.adoc
  downstream/modules/platform/ref-standalone-hub-inventory.adoc
Labels: 2.1

#490 Create section 24 "Workflow Job Templates" of the Controller UG
  downstream/assemblies/platform/assembly-ug-controller-job-templates.adoc
  downstream/assemblies/platform/assembly-ug-controller-workflow-job-templates.adoc
  downstream/images/ug-create-new-wf-template.png
  downstream/images/ug-wf-templates-home.png
  downstream/modules/platform/proc-controller-create-job-template.adoc
  downstream/modules/platform/proc-controller-create-workflow-template.adoc
  downstream/titles/controller/controller-user-guide/master.adoc
Labels: Needs backport to 2.4, Controller, 2.4

#501 Create Section 12 'Custom Credentials' of the Controller UG
  downstream/assemblies/platform/assembly-controller-custom-credentials.adoc
  downstream/images/credential-types-create-new.png
  downstream/images/credential-types-delete-confirmation.png
  downstream/images/credential-types-home-empty.png
  downstream/images/credential-types-home-with-example-types.png
  downstream/images/credential-types-new-listed-verify.png
  downstream/images/credential-types-new-listed.png
  downstream/images/organizations-galaxy-credentials.png
  downstream/modules/platform/proc-controller-create-credential-type.adoc
  downstream/modules/platform/ref-controller-api-considerations.adoc
  downstream/modules/platform/ref-controller-content-sourcing.adoc
  downstream/modules/platform/ref-get-started-credential-types.adoc
  downstream/titles/controller/controller-user-guide/master.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#503 Create Section 12 'Custom Credentials' of the Controller UG (#501)
  downstream/assemblies/platform/assembly-controller-custom-credentials.adoc
  downstream/images/credential-types-create-new.png
  downstream/images/credential-types-delete-confirmation.png
  downstream/images/credential-types-home-empty.png
  downstream/images/credential-types-home-with-example-types.png
  downstream/images/credential-types-new-listed-verify.png
  downstream/images/credential-types-new-listed.png
  downstream/images/organizations-galaxy-credentials.png
  downstream/modules/platform/proc-controller-create-credential-type.adoc
  downstream/modules/platform/ref-controller-api-considerations.adoc
  downstream/modules/platform/ref-controller-content-sourcing.adoc
  downstream/modules/platform/ref-get-started-credential-types.adoc
  downstream/titles/controller/controller-user-guide/master.adoc
Labels: Controller, 2.4

#507 Fixed broken link for unbound DNS (#506)
  downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc
Labels: Backported to 2.4

#505 Create 'Secrets Management' section of Controller UG
  downstream/assemblies/platform/assembly-controller-secret-management.adoc
  downstream/images/credentials-create-azure-kms-credential.png
  downstream/images/credentials-create-centrify-vault-credential.png
  downstream/images/credentials-create-cyberark-ccp-credential.png
  downstream/images/credentials-create-cyberark-conjur-credential.png
  downstream/images/credentials-create-hashicorp-kv-credential.png
  downstream/images/credentials-create-hashicorp-ssh-credential.png
  downstream/images/credentials-create-thycotic-devops-credential.png
  downstream/images/credentials-create-thycotic-server-credential.png
  downstream/images/credentials-link-credential-prompt.png
  downstream/images/credentials-link-metadata-prompt.png
  downstream/images/credentials-link-metadata-test-error.png
  downstream/images/leftkey.png
  downstream/images/question_circle.png
  downstream/images/sync.png
  downstream/modules/platform/proc-controller-configure-secret-lookups.adoc
  downstream/modules/platform/ref-azure-key-vault-lookup.adoc
  downstream/modules/platform/ref-centrify-vault-lookup.adoc
  downstream/modules/platform/ref-controller-metadata-credential-input.adoc
  downstream/modules/platform/ref-cyberark-ccp-lookup.adoc
  downstream/modules/platform/ref-cyberark-conjur-lookup.adoc
  downstream/modules/platform/ref-hashicorp-signed-ssh.adoc
  downstream/modules/platform/ref-hashicorp-vault-lookup.adoc
  downstream/modules/platform/ref-thycotic-devops-vault.adoc
  downstream/modules/platform/ref-thycotic-secret-server.adoc
  downstream/titles/controller/controller-user-guide/master.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#508 Create 'Secrets Management' section of Controller UG (#505)
  downstream/assemblies/platform/assembly-controller-secret-management.adoc
  downstream/images/credentials-create-azure-kms-credential.png
  downstream/images/credentials-create-centrify-vault-credential.png
  downstream/images/credentials-create-cyberark-ccp-credential.png
  downstream/images/credentials-create-cyberark-conjur-credential.png
  downstream/images/credentials-create-hashicorp-kv-credential.png
  downstream/images/credentials-create-hashicorp-ssh-credential.png
  downstream/images/credentials-create-thycotic-devops-credential.png
  downstream/images/credentials-create-thycotic-server-credential.png
  downstream/images/credentials-link-credential-prompt.png
  downstream/images/credentials-link-metadata-prompt.png
  downstream/images/credentials-link-metadata-test-error.png
  downstream/images/leftkey.png
  downstream/images/question_circle.png
  downstream/images/sync.png
  downstream/modules/platform/proc-controller-configure-secret-lookups.adoc
  downstream/modules/platform/ref-azure-key-vault-lookup.adoc
  downstream/modules/platform/ref-centrify-vault-lookup.adoc
  downstream/modules/platform/ref-controller-metadata-credential-input.adoc
  downstream/modules/platform/ref-cyberark-ccp-lookup.adoc
  downstream/modules/platform/ref-cyberark-conjur-lookup.adoc
  downstream/modules/platform/ref-hashicorp-signed-ssh.adoc
  downstream/modules/platform/ref-hashicorp-vault-lookup.adoc
  downstream/modules/platform/ref-thycotic-devops-vault.adoc
  downstream/modules/platform/ref-thycotic-secret-server.adoc
  downstream/titles/controller/controller-user-guide/master.adoc
Labels: documentation, Controller, 2.4

#509 Correct broken link typo in Containerized AAP Installation Guide
  downstream/modules/platform/ref-aap-containerized-dns-config.adoc
Labels: Ready for review, Needs backport to 2.4

#511 Correct broken link typo in Containerized AAP Installation Guide (#509)
  downstream/modules/platform/ref-aap-containerized-dns-config.adoc
Labels: 2.4

#510 Create 'Applications' section of the Controller UG
  downstream/assemblies/platform/assembly-controller-applications.adoc
  downstream/images/apps-client-id-popup.png
  downstream/images/apps-create-new.png
  downstream/images/apps-list-view-empty.png
  downstream/images/apps-list-view-examples.png
  downstream/images/apps-tokens-list-view-example2.png
  downstream/images/apps-tokens-list-view-examples.png
  downstream/images/users-token-information-example (1).png
  downstream/modules/platform/proc-controller-apps-create-tokens.adoc
  downstream/modules/platform/proc-controller-create-application.adoc
  downstream/modules/platform/ref-controller-applications-getting-started.adoc
  downstream/modules/platform/ref-controller-apps-add-tokens.adoc
  downstream/titles/controller/controller-user-guide/master.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#512 Create 'Applications' section of the Controller UG (#510)
  downstream/assemblies/platform/assembly-controller-applications.adoc
  downstream/images/apps-client-id-popup.png
  downstream/images/apps-create-new.png
  downstream/images/apps-list-view-empty.png
  downstream/images/apps-list-view-examples.png
  downstream/images/apps-tokens-list-view-example2.png
  downstream/images/apps-tokens-list-view-examples.png
  downstream/images/users-token-information-example (1).png
  downstream/modules/platform/proc-controller-apps-create-tokens.adoc
  downstream/modules/platform/proc-controller-create-application.adoc
  downstream/modules/platform/ref-controller-applications-getting-started.adoc
  downstream/modules/platform/ref-controller-apps-add-tokens.adoc
  downstream/titles/controller/controller-user-guide/master.adoc
Labels: documentation, Controller, 2.4

#515 Create 'Execution Environments' section of Controller UG.
  downstream/assemblies/platform/assembly-controller-execution-environments.adoc
  downstream/images/ee-details-templates-list.png
  downstream/images/ee-new-ee-form-filled.png
  downstream/images/job-template-with-example-ee-selected.png
  downstream/images/mount-containers-playbook-run-podspec.png
  downstream/images/settings-paths2expose-iso-jobs-mount-containers.png
  downstream/images/settings-paths2expose-iso-jobs.png
  downstream/modules/platform/proc-controller-apps-create-tokens.adoc
  downstream/modules/platform/proc-controller-ee-mount-options.adoc
  downstream/modules/platform/proc-controller-use-an-exec-env.adoc
  downstream/modules/platform/ref-controller-build-exec-envs.adoc
  downstream/modules/platform/ref-controller-building-exec-env.adoc
  downstream/modules/platform/ref-controller-install-builder.adoc
  downstream/modules/platform/ref-controller-run-the-builder.adoc
  downstream/titles/controller/controller-user-guide/master.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#504 Create section 24 "Workflow Job Templates" of the Controller UG
  downstream/assemblies/platform/assembly-ug-controller-job-templates.adoc
  downstream/assemblies/platform/assembly-ug-controller-workflow-job-templates.adoc
  downstream/images/compass.png
  downstream/images/link-icon.png
  downstream/images/plus_icon_dark.png
  downstream/images/ug-wf-add-node-selections.png
  downstream/images/ug-wf-add-template-example.png
  downstream/images/ug-wf-add-template-nodes.png
  downstream/images/ug-wf-add-template.png
  downstream/images/ug-wf-approval-node.png
  downstream/images/ug-wf-create-new-add-template-split.png
  downstream/images/ug-wf-create-sibling-node.png
  downstream/images/ug-wf-create-siblings.png
  downstream/images/ug-wf-dropdown-list.png
  downstream/images/ug-wf-editor-convergent-node-all.png
  downstream/images/ug-wf-editor-create.png
  downstream/images/ug-wf-editor-insert-node-template.png
  downstream/images/ug-wf-list-view-copy-example.png
  downstream/images/ug-wf-node-approval-notifications.png
  downstream/images/ug-wf-node-approval-rbac.png
  downstream/images/ug-wf-node-link-scenario.png
  downstream/images/ug-wf-prompt-button-inventory-wizard.png
  downstream/images/ug-wf-prompt-button-wizard.png
  downstream/images/ug-wf-template-jobID-detail.png
  downstream/images/ug-wf-template-launch.png
  downstream/images/ug-wf-template-saved.png
  downstream/modules/platform/con-controller-view-completed-workflow-jobs.adoc
  downstream/modules/platform/con-controller-work-with-permissions.adoc
  downstream/modules/platform/con-controller-workflow-job-surveys.adoc
  downstream/modules/platform/con-controller-workflow-notifications.adoc
  downstream/modules/platform/con-controller-workflow-visualizer.adoc
  downstream/modules/platform/proc-controller-build-workflow.adoc
  downstream/modules/platform/proc-controller-building-nodes-scenarios.adoc
  downstream/modules/platform/proc-controller-copy-workflow-job-template.adoc
  downstream/modules/platform/proc-controller-create-survey.adoc
  downstream/modules/platform/proc-controller-create-workflow-template.adoc
  downstream/modules/platform/proc-controller-edit-nodes.adoc
  downstream/modules/platform/proc-controller-launch-workflow-template.adoc
  downstream/modules/platform/proc-controller-scheduling-job-templates.adoc
  downstream/modules/platform/proc-controller-scheduling-workflow-job-templates.adoc
  downstream/modules/platform/ref-controller-approval-nodes.adoc
  downstream/modules/platform/ref-controller-workflow-job-template-extra-variables.adoc
  downstream/modules/platform/ug-wf-prompt-button-inventory-wizard.png
Labels: Needs backport to 2.4, Controller, 2.4

#519 Create section 24 "Workflow Job Templates" of the Controller UG (#504)
  downstream/assemblies/platform/assembly-ug-controller-job-templates.adoc
  downstream/assemblies/platform/assembly-ug-controller-workflow-job-templates.adoc
  downstream/images/compass.png
  downstream/images/link-icon.png
  downstream/images/plus_icon_dark.png
  downstream/images/ug-wf-add-node-selections.png
  downstream/images/ug-wf-add-template-example.png
  downstream/images/ug-wf-add-template-nodes.png
  downstream/images/ug-wf-add-template.png
  downstream/images/ug-wf-approval-node.png
  downstream/images/ug-wf-create-new-add-template-split.png
  downstream/images/ug-wf-create-sibling-node.png
  downstream/images/ug-wf-create-siblings.png
  downstream/images/ug-wf-dropdown-list.png
  downstream/images/ug-wf-editor-convergent-node-all.png
  downstream/images/ug-wf-editor-create.png
  downstream/images/ug-wf-editor-insert-node-template.png
  downstream/images/ug-wf-list-view-copy-example.png
  downstream/images/ug-wf-node-approval-notifications.png
  downstream/images/ug-wf-node-approval-rbac.png
  downstream/images/ug-wf-node-link-scenario.png
  downstream/images/ug-wf-prompt-button-inventory-wizard.png
  downstream/images/ug-wf-prompt-button-wizard.png
  downstream/images/ug-wf-template-jobID-detail.png
  downstream/images/ug-wf-template-launch.png
  downstream/images/ug-wf-template-saved.png
  downstream/modules/platform/con-controller-view-completed-workflow-jobs.adoc
  downstream/modules/platform/con-controller-work-with-permissions.adoc
  downstream/modules/platform/con-controller-workflow-job-surveys.adoc
  downstream/modules/platform/con-controller-workflow-notifications.adoc
  downstream/modules/platform/con-controller-workflow-visualizer.adoc
  downstream/modules/platform/proc-controller-build-workflow.adoc
  downstream/modules/platform/proc-controller-building-nodes-scenarios.adoc
  downstream/modules/platform/proc-controller-copy-workflow-job-template.adoc
  downstream/modules/platform/proc-controller-create-survey.adoc
  downstream/modules/platform/proc-controller-create-workflow-template.adoc
  downstream/modules/platform/proc-controller-edit-nodes.adoc
  downstream/modules/platform/proc-controller-launch-workflow-template.adoc
  downstream/modules/platform/proc-controller-scheduling-job-templates.adoc
  downstream/modules/platform/proc-controller-scheduling-workflow-job-templates.adoc
  downstream/modules/platform/ref-controller-approval-nodes.adoc
  downstream/modules/platform/ref-controller-workflow-job-template-extra-variables.adoc
  downstream/modules/platform/ug-wf-prompt-button-inventory-wizard.png
Labels: Controller, 2.4

#520 Added rsync to download command
  downstream/modules/platform/proc-installing-ansible-core.adoc
Labels: Ready for review, 2.4

#525 AAP-15839 [Backport] - replaced information in system requirements section with link
  downstream/modules/platform/ref-system-requirements.adoc
Labels: Ready for review, Backported to 2.4, 2.4

#526 AAP-16182: Updated network ports and protocols diagram
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
Labels: AAP Hardening, Ready for review, Needs backport to 2.4, 2.4
