Repository ansible/aap-docs, pull requests merged in 2023-12, with the labels that each got.

#845 [WIP] AAP-18144: Editorial edits
  downstream/assemblies/platform/assembly-system-requirements.adoc
  downstream/modules/platform/proc-benchmark-postgresql.adoc
  downstream/modules/platform/proc-enable-hstore-extension.adoc
  downstream/modules/platform/ref-automation-hub-requirements.adoc
  downstream/modules/platform/ref-controller-system-requirements.adoc
  downstream/modules/platform/ref-ha-hub-reqs.adoc
  downstream/modules/platform/ref-postgresql-requirements.adoc
  downstream/modules/platform/ref-system-requirements.adoc
Labels: Needs backport to 2.4, Not ready for peer review, 2.4

#854 [2.4] AAP-18144: Peer review edits (#845)
  downstream/assemblies/platform/assembly-system-requirements.adoc
  downstream/modules/platform/proc-benchmark-postgresql.adoc
  downstream/modules/platform/proc-enable-hstore-extension.adoc
  downstream/modules/platform/ref-automation-hub-requirements.adoc
  downstream/modules/platform/ref-controller-system-requirements.adoc
  downstream/modules/platform/ref-ha-hub-reqs.adoc
  downstream/modules/platform/ref-postgresql-requirements.adoc
  downstream/modules/platform/ref-system-requirements.adoc
Labels: Ready for review, Backported to 2.4, 2.4

#856 Updated titles of few topics per gerund format
  lightspeed/assemblies/assembly_requesting-task-recommendations.adoc
  lightspeed/modules/con_lightspeed-key-features.adoc
  lightspeed/modules/proc_install-code-bot.adoc
  lightspeed/modules/proc_manually-scan-repo.adoc
  lightspeed/modules/proc_multi-task-recs.adoc
  lightspeed/modules/proc_provide-feedback.adoc
  lightspeed/modules/proc_view-training-matches.adoc
  lightspeed/titles/lightspeed-release-notes/docinfo.xml
  lightspeed/titles/lightspeed-user-guide/docinfo.xml
Labels: Lightspeed

#858 Update release note heading hierarchy (#857)
  downstream/titles/release-notes/master.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-11.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-12.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-13.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-14.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-2.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-21.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-22.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-23.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-24.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-3.adoc
Labels: 2.4

#862 Adding step for controller websocket configuration (#860)
  downstream/modules/platform/proc-configuring-discovery.adoc
Labels: documentation, 2.3, Backported to 2.4, 2.4

#863 Adding step for controller websocket configuration (#860)
  downstream/modules/platform/proc-configuring-discovery.adoc
Labels: documentation, 2.3, Backported to 2.3

#864 AAP-18144-Typos: Correcting typos
  downstream/modules/platform/proc-benchmark-postgresql.adoc
  downstream/modules/platform/ref-controller-system-requirements.adoc
  downstream/modules/platform/ref-system-requirements.adoc
Labels: Ready for review, Needs backport to 2.4, 2.4

#865 [2.4] AAP-18144-Typos: Correcting typos (#864)
  downstream/modules/platform/proc-benchmark-postgresql.adoc
  downstream/modules/platform/ref-controller-system-requirements.adoc
  downstream/modules/platform/ref-system-requirements.adoc
Labels: Ready for review, Backported to 2.4

#861 AAP acronym removed
  downstream/assemblies/central-auth/assembly-configuring-central-auth-generic-oidc-settings.adoc
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
  downstream/modules/central-auth/proc-configure-central-auth-generic-oidc-settings.adoc
  downstream/modules/dev-guide/proc-downloading-base-ees.adoc
  downstream/modules/platform/proc-choosing-obtaining-installer.adoc
  downstream/modules/platform/proc-controller-adding-an-instance.adoc
  downstream/modules/platform/proc-create-secret-key-secret.adoc
  downstream/modules/platform/proc-installing-the-aap-setup-bundle.adoc
  downstream/modules/platform/proc-installing-the-ansible-builder-rpm.adoc
  downstream/modules/platform/proc-installing-with-internet.adoc
  downstream/modules/platform/proc-installing-without-internet.adoc
Labels: Ready for review, Needs backport to 2.4, 2.4

#796 PPAH edits
  downstream/assemblies/hub/assembly_ppah-installation.adoc
  downstream/modules/hub/proc_ppah-install-dev.adoc
  downstream/modules/hub/proc_ppah-install-ha.adoc
  downstream/modules/hub/proc_ppah-online-offline-install.adoc
  downstream/modules/hub/proc_ppah-pre-install.adoc
Labels: PPAH

#870 AAP acronym removed (#861)
  downstream/assemblies/central-auth/assembly-configuring-central-auth-generic-oidc-settings.adoc
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
  downstream/modules/central-auth/proc-configure-central-auth-generic-oidc-settings.adoc
  downstream/modules/dev-guide/proc-downloading-base-ees.adoc
  downstream/modules/platform/proc-choosing-obtaining-installer.adoc
  downstream/modules/platform/proc-controller-adding-an-instance.adoc
  downstream/modules/platform/proc-create-secret-key-secret.adoc
  downstream/modules/platform/proc-installing-the-aap-setup-bundle.adoc
  downstream/modules/platform/proc-installing-the-ansible-builder-rpm.adoc
  downstream/modules/platform/proc-installing-with-internet.adoc
  downstream/modules/platform/proc-installing-without-internet.adoc
Labels: Backported to 2.4, 2.4

#871 Update release notes to include GA of AAP on Power and Z
  downstream/titles/release-notes/topics/aap-24.adoc
Labels: Ready for review, Needs backport to 2.4, AAP Release notes

#872 Update release notes to include GA of AAP on Power and Z (#871)
  downstream/titles/release-notes/topics/aap-24.adoc
Labels: 2.4

#873 Changed description for secrets lookup procedure
  downstream/assemblies/platform/assembly-controller-secret-management.adoc
  downstream/images/type-details.png
  downstream/modules/platform/proc-controller-configure-secret-lookups.adoc
Labels: documentation, Needs backport to 2.4, Technical review complete, Controller, 2.4

#874 Changed description for secrets lookup procedure (#873)
  downstream/assemblies/platform/assembly-controller-secret-management.adoc
  downstream/images/type-details.png
  downstream/modules/platform/proc-controller-configure-secret-lookups.adoc
Labels: Backported to 2.4, 2.4

#876 Fixed typo
  downstream/modules/platform/ref-hub-variables.adoc
Labels: Needs backport to 2.4, 2.4

#875 PPAH: final updates
  downstream/assemblies/hub/assembly_ppah-installation.adoc
  downstream/modules/hub/proc_ppah-install-ha.adoc
Labels: PPAH

#880 AAP-18291: Added troubleshooting info. for cleaning up bot PRs
  lightspeed/assemblies/assembly_using-code-bot-for-suggestions.adoc
  lightspeed/modules/proc_troubleshooting-code-bot.adoc
Labels: Lightspeed

#855 AAP-18404: Added info. about removing licenses for deactivated users
  lightspeed/assemblies/assembly_assigning-seat-licenses.adoc
  lightspeed/modules/proc_remove-seat-licenses.adoc
Labels: Lightspeed

#881 PPAH: delete duplicate module
  downstream/assemblies/hub/assembly_ppah-installation.adoc
  downstream/modules/hub/proc_ppah-pre-install.adoc
Labels: PPAH

#889 Corrected port definitions
  downstream/modules/platform/con-ha-hub-installation.adoc
  downstream/modules/platform/proc-installing-the-aap-setup-bundle.adoc
  downstream/modules/platform/ref-example-platform-ext-database-customer-provided.adoc
  downstream/modules/platform/ref-example-platform-ext-database-inventory.adoc
  downstream/modules/platform/ref-platform-non-inst-database-inventory.adoc
  downstream/modules/platform/ref-single-controller-ext-customer-managed-db.adoc
  downstream/modules/platform/ref-single-controller-ext-installer-managed-db.adoc
  downstream/modules/platform/ref-standalone-hub-ext-database-customer-provided.adoc
  downstream/modules/platform/ref-standalone-hub-ext-database-inventory.adoc
  downstream/modules/platform/ref-standalone-hub-inventory.adoc
Labels: Needs backport to 2.4, 2.4

#890 Corrected port definitions (#889)
  downstream/modules/platform/con-ha-hub-installation.adoc
  downstream/modules/platform/proc-installing-the-aap-setup-bundle.adoc
  downstream/modules/platform/ref-example-platform-ext-database-customer-provided.adoc
  downstream/modules/platform/ref-example-platform-ext-database-inventory.adoc
  downstream/modules/platform/ref-platform-non-inst-database-inventory.adoc
  downstream/modules/platform/ref-single-controller-ext-customer-managed-db.adoc
  downstream/modules/platform/ref-single-controller-ext-installer-managed-db.adoc
  downstream/modules/platform/ref-standalone-hub-ext-database-customer-provided.adoc
  downstream/modules/platform/ref-standalone-hub-ext-database-inventory.adoc
  downstream/modules/platform/ref-standalone-hub-inventory.adoc
Labels: Backported to 2.4, 2.4

#891 PPAH Delete sync script from ppah-main branch
  bin/sync_ppah_docs.sh
Labels: PPAH

#892 Remove PPAH from main downstream docs branch
  downstream/titles/ppah/ppah-install/aap-common
  downstream/titles/ppah/ppah-install/attributes
  downstream/titles/ppah/ppah-install/docinfo.xml
  downstream/titles/ppah/ppah-install/hub
  downstream/titles/ppah/ppah-install/images
  downstream/titles/ppah/ppah-install/master.adoc
  downstream/titles/ppah/ppah-install/snippets
Labels: PPAH

#893 Updated variable names
  downstream/modules/platform/ref-controller-use-credentials-in-playbooks.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#894 Updated variable names (#893)
  downstream/modules/platform/ref-controller-use-credentials-in-playbooks.adoc
Labels: Backported to 2.4, 2.4

#878 AAP-14712 Add content to upgrade/migration guide for disabling activations for EDA
  downstream/modules/platform/con-aap-upgrade-planning.adoc
Labels: Ready for review, Needs backport to 2.4, Technical review complete, 2.4

#896 Add umask requirement to controller system requirements
  downstream/modules/platform/ref-controller-system-requirements.adoc
Labels: Ready for review, Needs backport to 2.4, Needs backport to 2.3, Needs backport to 2.2

#898 Fixing broken link
  downstream/modules/platform/proc-controller-create-job-template.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#899 Fixing broken link (#898)
  downstream/modules/platform/proc-controller-create-job-template.adoc
Labels: documentation, Backported to 2.4, Controller, 2.4

#883 AAP-13268-18 added section 18.5 Additional settings for automation c…
  downstream/assemblies/platform/assembly-ag-controller-config.adoc
  downstream/modules/platform/con-controller-additional-settings.adoc
Labels: Ready for review, Ready for technical review, Technical review complete, 2.4

#903 AAP-13268-18 added section 18.5 Additional settings for automation c……
  downstream/assemblies/platform/assembly-ag-controller-config.adoc
  downstream/modules/platform/con-controller-additional-settings.adoc
Labels: Ready for review, 2.4

#901 Add umask requirement to controller system requirements (#896)
  downstream/modules/platform/ref-controller-system-requirements.adoc
Labels: 2.3

#900 Add umask requirement to controller system requirements (#896)
  downstream/modules/platform/ref-controller-system-requirements.adoc
Labels: 2.4

#886 AAP-13268 updated Ch 14 of Controller Admin Guide
  downstream/assemblies/platform/assembly-controller-improving-performance.adoc
  downstream/modules/platform/con-controller-capacity-planning-operator.adoc
  downstream/modules/platform/con-controller-control-nodes.adoc
  downstream/modules/platform/con-controller-database-use-improvements.adoc
  downstream/modules/platform/con-controller-execution-nodes.adoc
  downstream/modules/platform/con-controller-hop-nodes.adoc
  downstream/modules/platform/con-controller-hybrid-nodes.adoc
  downstream/modules/platform/con-controller-job-events-processing.adoc
  downstream/modules/platform/con-controller-job-scheduling-improvements.adoc
  downstream/modules/platform/con-controller-ldap-enhancements.adoc
  downstream/modules/platform/con-controller-metrics-enhancements.adoc
  downstream/modules/platform/con-controller-metrics-monitor-controller.adoc
  downstream/modules/platform/con-controller-monitor-controller.adoc
  downstream/modules/platform/con-controller-node-size-choice.adoc
  downstream/modules/platform/con-controller-stability-improvements.adoc
  downstream/modules/platform/con-controller-system-level-monitoring.adoc
  downstream/modules/platform/con-controller-task-manager-settings.adoc
  downstream/modules/platform/con-controller-tuning.adoc
  downstream/modules/platform/con-controller-vertical-scaling-improvement.adoc
  downstream/modules/platform/proc-controller-disabling-live-events.adoc
  downstream/modules/platform/proc-controller-managing-live-events.adoc
  downstream/modules/platform/ref-controller-capacity-instance-container.adoc
  downstream/modules/platform/ref-controller-capacity-planning-exercise.adoc
  downstream/modules/platform/ref-controller-capacity-planning.adoc
  downstream/modules/platform/ref-controller-controller-settings.adoc
  downstream/modules/platform/ref-controller-database-settings.adoc
  downstream/modules/platform/ref-controller-example-workload-reqs.adoc
  downstream/modules/platform/ref-controller-internal-cluster-routing.adoc
  downstream/modules/platform/ref-controller-live-events.adoc
  downstream/modules/platform/ref-controller-metrics-monitoring.adoc
  downstream/modules/platform/ref-controller-node-types.adoc
  downstream/modules/platform/ref-controller-performance-improvements.adoc
  downstream/modules/platform/ref-controller-performance-troubleshooting.adoc
  downstream/modules/platform/ref-controller-settings-control-execution-nodes.adoc
  downstream/modules/platform/ref-controller-settings-job-events.adoc
  downstream/modules/platform/ref-controller-settings-scheduling-jobs.adoc
  downstream/modules/platform/ref-controller-settings-to-modify-events.adoc
  downstream/modules/platform/ref-controller-web-service-tuning.adoc
  downstream/modules/platform/ref-controller-workload-characteristics.adoc
  downstream/modules/platform/ref-ratio-control-execution.adoc
  downstream/modules/platform/ref-scaling-control-nodes.adoc
  downstream/modules/platform/ref-scaling-execution-nodes.adoc
  downstream/modules/platform/ref-scaling-hop-nodes.adoc
Labels: Ready for review, 2.4

#906 AAP-13268-B fixed broken xrefs in PR 886
  downstream/modules/platform/ref-controller-performance-troubleshooting.adoc
Labels: Ready for review, 2.4

#904 2.4 backport: AAP-13268 updated Ch 14 of Controller Admin Guide (#886)
  downstream/assemblies/platform/assembly-controller-improving-performance.adoc
  downstream/modules/platform/con-controller-capacity-planning-operator.adoc
  downstream/modules/platform/con-controller-control-nodes.adoc
  downstream/modules/platform/con-controller-database-use-improvements.adoc
  downstream/modules/platform/con-controller-execution-nodes.adoc
  downstream/modules/platform/con-controller-hop-nodes.adoc
  downstream/modules/platform/con-controller-hybrid-nodes.adoc
  downstream/modules/platform/con-controller-job-events-processing.adoc
  downstream/modules/platform/con-controller-job-scheduling-improvements.adoc
  downstream/modules/platform/con-controller-ldap-enhancements.adoc
  downstream/modules/platform/con-controller-metrics-enhancements.adoc
  downstream/modules/platform/con-controller-metrics-monitor-controller.adoc
  downstream/modules/platform/con-controller-monitor-controller.adoc
  downstream/modules/platform/con-controller-node-size-choice.adoc
  downstream/modules/platform/con-controller-stability-improvements.adoc
  downstream/modules/platform/con-controller-system-level-monitoring.adoc
  downstream/modules/platform/con-controller-task-manager-settings.adoc
  downstream/modules/platform/con-controller-tuning.adoc
  downstream/modules/platform/con-controller-vertical-scaling-improvement.adoc
  downstream/modules/platform/proc-controller-disabling-live-events.adoc
  downstream/modules/platform/proc-controller-managing-live-events.adoc
  downstream/modules/platform/ref-controller-capacity-instance-container.adoc
  downstream/modules/platform/ref-controller-capacity-planning-exercise.adoc
  downstream/modules/platform/ref-controller-capacity-planning.adoc
  downstream/modules/platform/ref-controller-controller-settings.adoc
  downstream/modules/platform/ref-controller-database-settings.adoc
  downstream/modules/platform/ref-controller-example-workload-reqs.adoc
  downstream/modules/platform/ref-controller-internal-cluster-routing.adoc
  downstream/modules/platform/ref-controller-live-events.adoc
  downstream/modules/platform/ref-controller-metrics-monitoring.adoc
  downstream/modules/platform/ref-controller-node-types.adoc
  downstream/modules/platform/ref-controller-performance-improvements.adoc
  downstream/modules/platform/ref-controller-performance-troubleshooting.adoc
  downstream/modules/platform/ref-controller-settings-control-execution-nodes.adoc
  downstream/modules/platform/ref-controller-settings-job-events.adoc
  downstream/modules/platform/ref-controller-settings-scheduling-jobs.adoc
  downstream/modules/platform/ref-controller-settings-to-modify-events.adoc
  downstream/modules/platform/ref-controller-web-service-tuning.adoc
  downstream/modules/platform/ref-controller-workload-characteristics.adoc
  downstream/modules/platform/ref-ratio-control-execution.adoc
  downstream/modules/platform/ref-scaling-control-nodes.adoc
  downstream/modules/platform/ref-scaling-execution-nodes.adoc
  downstream/modules/platform/ref-scaling-hop-nodes.adoc
Labels: Ready for review, 2.4

#909 Corrections to controller admin guide
  downstream/modules/platform/proc-controller-attaching-subscriptions.adoc
  downstream/titles/controller/controller-admin-guide/docinfo.xml
  downstream/titles/controller/controller-admin-guide/master.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#910 Corrections to controller admin guide (#909)
  downstream/modules/platform/proc-controller-attaching-subscriptions.adoc
  downstream/titles/controller/controller-admin-guide/docinfo.xml
  downstream/titles/controller/controller-admin-guide/master.adoc
Labels: Backported to 2.4, Controller, 2.4

#911 Corrections to controller admin guide part 2
  downstream/assemblies/platform/assembly-controller-metrics.adoc
  downstream/assemblies/platform/assembly-controller-token-based-authentication.adoc
  downstream/modules/platform/con-controller-multi-cred-background.adoc
  downstream/modules/platform/con-controller-understand-architecture.adoc
  downstream/modules/platform/proc-controller-adding-an-instance.adoc
  downstream/modules/platform/proc-controller-github-enterprise-org-settings.adoc
  downstream/modules/platform/proc-controller-github-enterprise-settings.adoc
  downstream/modules/platform/proc-controller-github-enterprise-team-settings.adoc
  downstream/modules/platform/proc-controller-github-organization-setttings.adoc
  downstream/modules/platform/proc-controller-google-oauth2-settings.adoc
  downstream/modules/platform/proc-controller-manage-instances.adoc
  downstream/modules/platform/proc-controller-management-notifications.adoc
  downstream/modules/platform/proc-controller-managing-live-events.adoc
  downstream/modules/platform/proc-controller-prevent-LDAP-attributes.adoc
  downstream/modules/platform/proc-controller-scheduling-deletion.adoc
  downstream/modules/platform/proc-controller-set-up-LDAP.adoc
  downstream/modules/platform/proc-controller-set-up-SAML.adoc
  downstream/modules/platform/proc-controller-set-up-generic-oidc.adoc
  downstream/modules/platform/proc-controller-set-up-tacacs+.adoc
  downstream/modules/platform/ref-controller-AD-and-kerberos-credentials.adoc
  downstream/modules/platform/ref-controller-activity-stream-schema.adoc
  downstream/modules/platform/ref-controller-analytics-reports.adoc
  downstream/modules/platform/ref-controller-auth-code-grant-type.adoc
  downstream/modules/platform/ref-controller-change-admin-password.adoc
  downstream/modules/platform/ref-controller-database-settings.adoc
  downstream/modules/platform/ref-controller-internal-cluster-routing.adoc
  downstream/modules/platform/ref-controller-loggers.adoc
  downstream/modules/platform/ref-controller-performance-troubleshooting.adoc
  downstream/modules/platform/ref-controller-revoke-access-token.adoc
  downstream/modules/platform/ref-controller-scm-inv-source-fields.adoc
  downstream/modules/platform/ref-controller-settings-job-events.adoc
  downstream/modules/platform/ref-controller-setup-considerations.adoc
  downstream/modules/platform/ref-controller-team-mapping.adoc
  downstream/modules/platform/ref-controller-unified-jobs-table-csv.adoc
  downstream/modules/platform/ref-controller-use-an-unreleased-module.adoc
  downstream/modules/platform/ref-controller-use-callback-plugins.adoc
  downstream/modules/platform/ref-instances-prerequisites.adoc
  downstream/modules/platform/ref-scaling-execution-nodes.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#912 Corrections to controller admin guide part 2 (#911)
  downstream/assemblies/platform/assembly-controller-metrics.adoc
  downstream/assemblies/platform/assembly-controller-token-based-authentication.adoc
  downstream/modules/platform/con-controller-multi-cred-background.adoc
  downstream/modules/platform/con-controller-understand-architecture.adoc
  downstream/modules/platform/proc-controller-adding-an-instance.adoc
  downstream/modules/platform/proc-controller-github-enterprise-org-settings.adoc
  downstream/modules/platform/proc-controller-github-enterprise-settings.adoc
  downstream/modules/platform/proc-controller-github-enterprise-team-settings.adoc
  downstream/modules/platform/proc-controller-github-organization-setttings.adoc
  downstream/modules/platform/proc-controller-google-oauth2-settings.adoc
  downstream/modules/platform/proc-controller-manage-instances.adoc
  downstream/modules/platform/proc-controller-management-notifications.adoc
  downstream/modules/platform/proc-controller-managing-live-events.adoc
  downstream/modules/platform/proc-controller-prevent-LDAP-attributes.adoc
  downstream/modules/platform/proc-controller-scheduling-deletion.adoc
  downstream/modules/platform/proc-controller-set-up-LDAP.adoc
  downstream/modules/platform/proc-controller-set-up-SAML.adoc
  downstream/modules/platform/proc-controller-set-up-generic-oidc.adoc
  downstream/modules/platform/proc-controller-set-up-tacacs+.adoc
  downstream/modules/platform/ref-controller-AD-and-kerberos-credentials.adoc
  downstream/modules/platform/ref-controller-activity-stream-schema.adoc
  downstream/modules/platform/ref-controller-analytics-reports.adoc
  downstream/modules/platform/ref-controller-auth-code-grant-type.adoc
  downstream/modules/platform/ref-controller-change-admin-password.adoc
  downstream/modules/platform/ref-controller-database-settings.adoc
  downstream/modules/platform/ref-controller-internal-cluster-routing.adoc
  downstream/modules/platform/ref-controller-loggers.adoc
  downstream/modules/platform/ref-controller-performance-troubleshooting.adoc
  downstream/modules/platform/ref-controller-revoke-access-token.adoc
  downstream/modules/platform/ref-controller-scm-inv-source-fields.adoc
  downstream/modules/platform/ref-controller-settings-job-events.adoc
  downstream/modules/platform/ref-controller-setup-considerations.adoc
  downstream/modules/platform/ref-controller-team-mapping.adoc
  downstream/modules/platform/ref-controller-unified-jobs-table-csv.adoc
  downstream/modules/platform/ref-controller-use-an-unreleased-module.adoc
  downstream/modules/platform/ref-controller-use-callback-plugins.adoc
  downstream/modules/platform/ref-instances-prerequisites.adoc
  downstream/modules/platform/ref-scaling-execution-nodes.adoc
Labels: documentation, Backported to 2.4, Controller, 2.4

#913 Add instructions to configure content signing
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
Labels: Docathon, Needs backport to 2.4, 2.4

#914 Add instructions to configure content signing (#913)
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
Labels: Backported to 2.4, Docathon, 2.4
