Repository ansible/aap-docs, pull requests merged in 2024-09, with the labels that each got.

#1810 Adding post install steps for VM install
  downstream/assemblies/platform/assembly-VM-eda-controller-install.adoc
  downstream/assemblies/platform/assembly-eda-controller-post-install.adoc
  downstream/modules/platform/con-VM-install-eda-post-steps.adoc
  downstream/titles/eda-controller/eda-controller-install/docinfo.xml
  downstream/titles/eda-controller/eda-controller-install/master.adoc
Labels: documentation, Ready for review, 2.4

#1811 fixing note adminotions (#1809)
  downstream/assemblies/platform/assembly-configure-aap-operator.adoc
  downstream/modules/platform/con-ocp-supported-install.adoc
  downstream/modules/platform/proc-configure-ldap-hub-ocp.adoc
  downstream/modules/platform/proc-operator-deploy-central-config.adoc
Labels: documentation, 2.5, AAP operator

#1813 Update node procedure
  downstream/modules/platform/proc-define-mesh-node-types.adoc
Labels: 2.5, Needs backport to 2.5

#1814 Update node procedure (#1813)
  downstream/modules/platform/proc-define-mesh-node-types.adoc
Labels: 2.5, Backported to 2.5

#1798 Converting google doc draft into acsiidoc
  images/saas-exe-node-private.png
  stories/topics/con-saas-account-management.adoc
  stories/topics/con-saas-application-monitoring-and-customer-audits.adoc
  stories/topics/con-saas-automation-mesh.adoc
  stories/topics/con-saas-backup-and-diaster-recovery.adoc
  stories/topics/con-saas-billing.adoc
  stories/topics/con-saas-connectivity.adoc
  stories/topics/con-saas-control-plane.adoc
  stories/topics/con-saas-customer-access.adoc
  stories/topics/con-saas-deployment-self-service.adoc
  stories/topics/con-saas-dns.adoc
  stories/topics/con-saas-encryption.adoc
  stories/topics/con-saas-execution-plane.adoc
  stories/topics/con-saas-hosted-components.adoc
  stories/topics/con-saas-identity-and-access-management.adoc
  stories/topics/con-saas-infastructure-monitoring.adoc
  stories/topics/con-saas-limited-support-status.adoc
  stories/topics/con-saas-monitoring.adoc
  stories/topics/con-saas-networking-with-overlapping-CDIR-blocks.adoc
  stories/topics/con-saas-regions.adoc
  stories/topics/con-saas-responsibilities.adoc
  stories/topics/con-saas-shape.adoc
  stories/topics/con-saas-sla.adoc
  stories/topics/con-saas-sre-access-and-management.adoc
  stories/topics/con-saas-status-notification.adoc
  stories/topics/con-saas-support.adoc
Labels: documentation, AAP on clouds, Ansible on AWS, Ready for review, SaaS on AWS

#1816 AAP-29296 removed subscription info
  downstream/archive/archived-assemblies/platform/assembly-attaching-subscriptions.adoc
  downstream/titles/aap-planning-guide/master.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#1817 AAP-30336 remove subscription info from operations guide
  downstream/archive/archived-assemblies/platform/assembly-aap-manifest-files.adoc
  downstream/titles/aap-operations-guide/master.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#1818 [Backport] - AAP-29504 - Created snippets for repeated authentication information (#1758)
  downstream/snippets/snip-gw-authentication-additional-auth-fields.adoc
  downstream/snippets/snip-gw-authentication-common-checkboxes.adoc
  downstream/snippets/snip-gw-authentication-verification.adoc
Labels: Ready for review, 2.5

#1821 AAP-30336 remove subscription info from operations guide (#1817)
  downstream/archive/archived-assemblies/platform/assembly-aap-manifest-files.adoc
  downstream/titles/aap-operations-guide/master.adoc
Labels: Ready for review, 2.5

#1822 AAP-29296 removed subscription info (#1816)
  downstream/archive/archived-assemblies/platform/assembly-attaching-subscriptions.adoc
  downstream/titles/aap-planning-guide/master.adoc
Labels: Ready for review, 2.5

#1825 [Backport] am-formatting-2 - Fixing issues with document structure/chapter breakdown (#1819)
  downstream/assemblies/platform/assembly-gw-config-authentication-type.adoc
  downstream/assemblies/platform/assembly-gw-configure-authentication.adoc
  downstream/modules/platform/proc-controller-google-oauth2-settings.adoc
  downstream/modules/platform/proc-controller-set-up-generic-oidc.adoc
  downstream/titles/central-auth/master.adoc
Labels: Ready for review, 2.5

#1801 AAP-21776 Convert HA Redis conceptual content
  downstream/images/gw-clustered-redis.png
  downstream/images/gw-single-node-redis.png
  downstream/modules/platform/con-gw-cache-queue.adoc
  downstream/modules/platform/con-gw-centralized-redis.adoc
  downstream/modules/platform/con-gw-clustered-redis.adoc
  downstream/modules/platform/con-gw-single-node-redis.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#1826 improving user orientation and some minor style tweaks
  downstream/modules/platform/proc-aap-controller-backup.adoc
  downstream/modules/platform/proc-aap-controller-restore.adoc
  downstream/modules/platform/proc-aap-controller-yaml-backup.adoc
  downstream/modules/platform/proc-aap-hub-backup.adoc
  downstream/modules/platform/proc-aap-hub-restore.adoc
  downstream/modules/platform/proc-aap-platform-gateway-backup.adoc
  downstream/modules/platform/proc-aap-platform-gateway-restore.adoc
Labels: documentation, Ready for review, 2.5, AAP operator, Needs backport to 2.5

#1827 improving user orientation and some minor style tweaks (#1826)
  downstream/modules/platform/proc-aap-controller-backup.adoc
  downstream/modules/platform/proc-aap-controller-restore.adoc
  downstream/modules/platform/proc-aap-controller-yaml-backup.adoc
  downstream/modules/platform/proc-aap-hub-backup.adoc
  downstream/modules/platform/proc-aap-hub-restore.adoc
  downstream/modules/platform/proc-aap-platform-gateway-backup.adoc
  downstream/modules/platform/proc-aap-platform-gateway-restore.adoc
Labels: documentation, Ready for review, 2.5, AAP operator

#1828 Create directories for supported topologies doc
  downstream/assemblies/topologies/assembly-container-topologies.adoc
  downstream/assemblies/topologies/assembly-overview-supported-deployment-models.adoc
  downstream/assemblies/topologies/assembly-rpm-topologies.adoc
  downstream/assemblies/topologies/topologies
  downstream/attributes/attributes.adoc
  downstream/titles/topologies/aap-common
  downstream/titles/topologies/attributes
  downstream/titles/topologies/docinfo.xml
  downstream/titles/topologies/images
  downstream/titles/topologies/master.adoc
  downstream/titles/topologies/topologies
Labels: 2.5, Needs backport to 2.5

#1829 Create directories for supported topologies doc (#1828)
  downstream/assemblies/topologies/assembly-container-topologies.adoc
  downstream/assemblies/topologies/assembly-overview-supported-deployment-models.adoc
  downstream/assemblies/topologies/assembly-rpm-topologies.adoc
  downstream/assemblies/topologies/topologies
  downstream/attributes/attributes.adoc
  downstream/titles/topologies/aap-common
  downstream/titles/topologies/attributes
  downstream/titles/topologies/docinfo.xml
  downstream/titles/topologies/images
  downstream/titles/topologies/master.adoc
  downstream/titles/topologies/topologies
Labels: 2.5

#1831 Add info on configuring load balancer for container installer
  downstream/modules/platform/proc-installing-containerized-aap.adoc
Labels: 2.5, Needs backport to 2.5

#1832 Add info on configuring load balancer for container installer (#1831)
  downstream/modules/platform/proc-installing-containerized-aap.adoc
Labels: 2.5

#1833 [Backport] AAP-21776 Convert HA Redis conceptual content (#1801)
  downstream/images/gw-clustered-redis.png
  downstream/images/gw-single-node-redis.png
  downstream/modules/platform/con-gw-cache-queue.adoc
  downstream/modules/platform/con-gw-centralized-redis.adoc
  downstream/modules/platform/con-gw-clustered-redis.adoc
  downstream/modules/platform/con-gw-single-node-redis.adoc
Labels: Ready for review, 2.5

#1836 Fix the title for Managing content document
  downstream/titles/hub/managing-content/docinfo.xml
  downstream/titles/hub/managing-content/master.adoc
Labels: Ready for review, Title change, 2.5, Needs backport to 2.5

#1834 2.4 Add rpm release notes RHSA-2024:6428
  downstream/titles/release-notes/master.adoc
  downstream/titles/release-notes/topics/rpm-24-72.adoc
  downstream/titles/release-notes/topics/rpm-version-table.adoc
Labels: AAP Release notes, 2.4

#1793 Adding new content for 2.5 to rulebook act. chapter
  downstream/assemblies/eda/assembly-eda-rulebook-activations.adoc
  downstream/modules/eda/con-eda-rulebook-activation-list-view.adoc
  downstream/modules/eda/proc-eda-activate-webhook.adoc
  downstream/modules/eda/proc-eda-delete-rulebook-activations.adoc
  downstream/modules/eda/proc-eda-enable-rulebook-activations.adoc
  downstream/modules/eda/proc-eda-restart-rulebook-activations.adoc
  downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc
  downstream/modules/eda/proc-eda-view-activation-output.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#1838 Adding new content for 2.5 to rulebook act. chapter (#1793)
  downstream/assemblies/eda/assembly-eda-rulebook-activations.adoc
  downstream/modules/eda/con-eda-rulebook-activation-list-view.adoc
  downstream/modules/eda/proc-eda-activate-webhook.adoc
  downstream/modules/eda/proc-eda-delete-rulebook-activations.adoc
  downstream/modules/eda/proc-eda-enable-rulebook-activations.adoc
  downstream/modules/eda/proc-eda-restart-rulebook-activations.adoc
  downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc
  downstream/modules/eda/proc-eda-view-activation-output.adoc
Labels: documentation, 2.5, Backported to 2.5

#1837 AAP-28228 added OCP assembly
  downstream/assemblies/topologies/assembly-ocp-topologies.adoc
  downstream/titles/topologies/master.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#1839 AAP-28228 added OCP assembly (#1837)
  downstream/assemblies/topologies/assembly-ocp-topologies.adoc
  downstream/titles/topologies/master.adoc
Labels: Ready for review, 2.5

#1841 Add RPM and CONT modules to topology docs
  downstream/assemblies/topologies/assembly-container-topologies.adoc
  downstream/assemblies/topologies/assembly-rpm-topologies.adoc
  downstream/modules/topologies/ref-cont-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-b.adoc
Labels: 2.5, Needs backport to 2.5

#1840 2.4 Add rpm-24-71 to async release notes
  downstream/titles/release-notes/master.adoc
  downstream/titles/release-notes/topics/installer-24-71.adoc
  downstream/titles/release-notes/topics/installer-version-table.adoc
  downstream/titles/release-notes/topics/rpm-24-71.adoc
  downstream/titles/release-notes/topics/rpm-24-72.adoc
  downstream/titles/release-notes/topics/rpm-version-table.adoc
Labels: AAP Release notes, 2.4

#1842 2.5 Add RPM and CONT modules to topology docs (#1841)
  downstream/assemblies/topologies/assembly-container-topologies.adoc
  downstream/assemblies/topologies/assembly-rpm-topologies.adoc
  downstream/modules/topologies/ref-cont-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-b.adoc
Labels: 2.5

#1844 Fix Managing content document title to remove AAP
  downstream/titles/hub/managing-content/docinfo.xml
  downstream/titles/hub/managing-content/master.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#1845 [Backport] Fix Managing content document title to remove AAP (#1844)
  downstream/titles/hub/managing-content/docinfo.xml
  downstream/titles/hub/managing-content/master.adoc
Labels: Ready for review, Title change, 2.5

#1849 Add CONT-A-ENV-A to topology docs
  downstream/assemblies/topologies/assembly-container-topologies.adoc
  downstream/modules/topologies/ref-cont-a-env-a.adoc
Labels: 2.5, Needs backport to 2.5

#1850 Add CONT-A-ENV-A to topology docs (#1849)
  downstream/assemblies/topologies/assembly-container-topologies.adoc
  downstream/modules/topologies/ref-cont-a-env-a.adoc
Labels: 2.5

#1852 2.5 Update containerized install guide (#1851)
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/platform/proc-downloading-containerized-aap.adoc
  downstream/modules/platform/proc-installing-ansible-core.adoc
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc
  downstream/modules/platform/proc-uninstalling-containerized-aap.adoc
  downstream/modules/platform/proc-using-postinstall.adoc
  downstream/modules/platform/ref-accessing-control-auto-hub-eda-control.adoc
  downstream/modules/platform/ref-adding-execution-nodes.adoc
  downstream/modules/platform/ref-containerized-troubleshoot-install.adoc
  downstream/modules/platform/ref-enabling-automation-hub-collection-and-container-signing.adoc
  downstream/modules/platform/ref-using-custom-receptor-signing-keys.adoc
  downstream/modules/platform/ref-using-custom-tls-certificates.adoc
Labels: 2.5

#1853 AAP-19988 (#1846)
  downstream/assemblies/central-auth/assembly-central-auth-automate-keycloak.adoc
  downstream/modules/platform/proc-central-auth-install-dependencies.adoc
  downstream/modules/platform/proc-central-auth-install-keycloak.adoc
  downstream/modules/platform/ref-controller-database-settings.adoc
Labels: Ready for review, 2.4

#1812 Add Event filter chapter to EDA user guide
  downstream/assemblies/eda/assembly-eda-event-filter-plugins.adoc
  downstream/modules/eda/con-eda-author-event-filters.adoc
  downstream/titles/eda/eda-user-guide/master.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#1854 Add Event filter chapter to EDA user guide (#1812)
  downstream/assemblies/eda/assembly-eda-event-filter-plugins.adoc
  downstream/modules/eda/con-eda-author-event-filters.adoc
  downstream/titles/eda/eda-user-guide/master.adoc
Labels: documentation, 2.5, Backported to 2.5

#1855 2.4 Add bundle installer 2.4-7.2 release notes
  downstream/titles/release-notes/master.adoc
  downstream/titles/release-notes/topics/installer-24-72.adoc
  downstream/titles/release-notes/topics/installer-version-table.adoc
Labels: AAP Release notes, 2.4

#1857 AAP-28228-A added ref modules for OCP (#1843)
  downstream/assemblies/topologies/assembly-ocp-topologies.adoc
  downstream/modules/topologies/ref-ocp-a-env-a.adoc
  downstream/modules/topologies/ref-ocp-b-env-a.adoc
Labels: Ready for review, 2.5

#1856 Update topologies based on feedback
  downstream/assemblies/topologies/assembly-container-topologies.adoc
  downstream/assemblies/topologies/assembly-ocp-topologies.adoc
  downstream/assemblies/topologies/assembly-overview-supported-deployment-models.adoc
  downstream/assemblies/topologies/assembly-rpm-topologies.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/topologies/ref-cont-a-env-a.adoc
  downstream/modules/topologies/ref-cont-b-env-a.adoc
  downstream/modules/topologies/ref-mesh-nodes.adoc
  downstream/modules/topologies/ref-rpm-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-b.adoc
  downstream/titles/topologies/docinfo.xml
  downstream/titles/topologies/master.adoc
Labels: 2.5, Needs backport to 2.5

#1859 2.5 Update topologies based on feedback (#1856)
  downstream/assemblies/topologies/assembly-container-topologies.adoc
  downstream/assemblies/topologies/assembly-ocp-topologies.adoc
  downstream/assemblies/topologies/assembly-overview-supported-deployment-models.adoc
  downstream/assemblies/topologies/assembly-rpm-topologies.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/topologies/ref-cont-a-env-a.adoc
  downstream/modules/topologies/ref-cont-b-env-a.adoc
  downstream/modules/topologies/ref-mesh-nodes.adoc
  downstream/modules/topologies/ref-rpm-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-b.adoc
  downstream/titles/topologies/docinfo.xml
  downstream/titles/topologies/master.adoc
Labels: 2.5

#1858 AAP-28228-B updated OCP-A-ENV-A
  downstream/modules/topologies/ref-ocp-a-env-a.adoc
  downstream/modules/topologies/ref-ocp-b-env-a.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#1861 AAP-29177 updated FDQN guidelines
  downstream/modules/platform/ref-guidelines-hosts-groups.adoc
Labels: Ready for review, Needs backport to 2.4, Technical review complete, 2.4

#1862 AAP-29177 updated FDQN guidelines (#1861)
  downstream/modules/platform/ref-guidelines-hosts-groups.adoc
Labels: Ready for review, 2.4

#1863 AAP-29118 - Update Creating a user with UI changes
  downstream/assemblies/platform/assembly-controller-teams.adoc
  downstream/modules/platform/proc-controller-creating-a-user.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#1865 [Backport] AAP-29918 - Update Creating a user with UI changes (#1863)
  downstream/assemblies/platform/assembly-controller-teams.adoc
  downstream/modules/platform/proc-controller-creating-a-user.adoc
Labels: Ready for review, 2.5

#1866 aap-30853 topology and minor updates
  downstream/assemblies/platform/assembly-installing-controller-operator.adoc
  downstream/modules/platform/con-about-operator.adoc
  downstream/modules/platform/proc-configuring-controller-ldap-security.adoc
  downstream/modules/platform/proc-controller-ingress-options.adoc
  downstream/modules/platform/proc-operator-deploy-central-config.adoc
  downstream/modules/platform/proc-operator-link-components.adoc
Labels: documentation, 2.5, AAP operator, Needs backport to 2.5

#1808 Updated RHEL requirements
  downstream/modules/platform/ref-system-requirements.adoc
Labels: 2.3

#1873 Update gateway snippet to include link to the Getting started guide
  downstream/snippets/snip-gateway-component-description.adoc
Labels: Ready for review, snippets, 2.5, Needs backport to 2.5

#1876 Adding link to authentication
  downstream/modules/platform/proc-configuring-controller-ldap-security.adoc
Labels: documentation, Ready for review, 2.5, AAP operator, Needs backport to 2.5

#1877 Adding link to authentication (#1876)
  downstream/modules/platform/proc-configuring-controller-ldap-security.adoc
Labels: documentation, Ready for review, 2.5, AAP operator

#1878 Remove field from procedure
  downstream/modules/platform/proc-controller-configure-system.adoc
Labels: documentation, 2.5, Backported to 2.5

#1879 Remove field from procedure (#1878)
  downstream/modules/platform/proc-controller-configure-system.adoc
Labels: 2.5, Backported to 2.5

#1824 AAP-26519-A created structure for new book title: Using AA
  downstream/titles/analytics/aap-common/apache-2.0-license.adoc
  downstream/titles/analytics/aap-common/assembly-aap-common.adoc
  downstream/titles/analytics/aap-common/boilerplate.adoc
  downstream/titles/analytics/aap-common/external-site-disclaimer.adoc
  downstream/titles/analytics/aap-common/gplv3-license-text.adoc
  downstream/titles/analytics/aap-common/making-open-source-more-inclusive.adoc
  downstream/titles/analytics/aap-common/providing-feedback.adoc
  downstream/titles/analytics/attributes/attributes.adoc
  downstream/titles/analytics/docinfo.xml
  downstream/titles/analytics/master.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#1880 AAP-26519-A created structure for new book title: Using AA (#1824)
  downstream/titles/analytics/aap-common/apache-2.0-license.adoc
  downstream/titles/analytics/aap-common/assembly-aap-common.adoc
  downstream/titles/analytics/aap-common/boilerplate.adoc
  downstream/titles/analytics/aap-common/external-site-disclaimer.adoc
  downstream/titles/analytics/aap-common/gplv3-license-text.adoc
  downstream/titles/analytics/aap-common/making-open-source-more-inclusive.adoc
  downstream/titles/analytics/aap-common/providing-feedback.adoc
  downstream/titles/analytics/attributes/attributes.adoc
  downstream/titles/analytics/docinfo.xml
  downstream/titles/analytics/master.adoc
Labels: Ready for review, 2.5

#1881 [Backport] Update gateway snippet to include link to the Getting started guide (#1873)
  downstream/snippets/snip-gateway-component-description.adoc
Labels: Ready for review, 2.5

#1872 AAP-30863 update 2.4 docs for automatic Analytics opt in changes
  downstream/modules/platform/proc-aap-activate-with-credentials.adoc
  downstream/modules/platform/proc-aap-activate-with-manifest.adoc
  downstream/modules/platform/ref-controller-automation-analytics.adoc
Labels: Ready for review, Technical review complete, 2.4

#1883 AAP19528_a - Implement peer review changes from backport PR#1882
  downstream/assemblies/platform/assembly-gateway-licensing.adoc
  downstream/modules/platform/proc-aap-activate-with-credentials.adoc
  downstream/modules/platform/ref-controller-node-counting.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#1884 [Backport] AAP19528_a - Implement peer review changes from backport PR#1882 (#1883)
  downstream/assemblies/platform/assembly-gateway-licensing.adoc
  downstream/modules/platform/proc-aap-activate-with-credentials.adoc
  downstream/modules/platform/ref-controller-node-counting.adoc
Labels: Ready for review, 2.5

#1885 Update containerized install guide
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/platform/proc-downloading-containerized-aap.adoc
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc
  downstream/modules/platform/proc-using-postinstall.adoc
  downstream/titles/aap-containerized-install/docinfo.xml
Labels: 2.5, Needs backport to 2.5

#1886 2.5 Update containerized install guide (#1885)
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/platform/proc-downloading-containerized-aap.adoc
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc
  downstream/modules/platform/proc-using-postinstall.adoc
Labels: 2.5

#1887 Rename navigator guide to Using content navigator
  downstream/titles/navigator-guide/docinfo.xml
  downstream/titles/navigator-guide/master.adoc
Labels: Needs backport to 2.5

#1888 2.5 Rename navigator guide to Using content navigator (#1887)
  downstream/titles/navigator-guide/docinfo.xml
  downstream/titles/navigator-guide/master.adoc
Labels: Title change

#1889 AAP30863-a - Updated 2.4 subscription import to reflect analytics opt in changes
  downstream/modules/platform/proc-controller-importing-subscriptions.adoc
Labels: Ready for review, 2.4

#1874 AAP18813 - Adding OAuth/Application content to the access management guide
  downstream/assemblies/platform/assembly-controller-applications.adoc
  downstream/assemblies/platform/assembly-gw-token-based-authentication.adoc
  downstream/modules/platform/proc-controller-apps-create-tokens.adoc
  downstream/modules/platform/proc-controller-create-application.adoc
  downstream/modules/platform/ref-controller-app-token-functions.adoc
  downstream/modules/platform/ref-controller-applications-getting-started.adoc
  downstream/modules/platform/ref-controller-revoke-access-token.adoc
  downstream/modules/platform/ref-gw-access-rules-apps-tokens.adoc
  downstream/modules/platform/ref-gw-application-functions.adoc
  downstream/modules/platform/ref-gw-request-token-after-expiration.adoc
Labels: Peer review complete, 2.5, Needs backport to 2.5

#1890 Remove attributes from job-explorer title
  downstream/titles/analytics/job-explorer/master.adoc
Labels: 2.3, Title change

#1891 Update title attributes for navigator
  downstream/attributes/attributes.adoc
Labels: Title change, 2.5, Backported to 2.5

#1892 2.5 Update title attributes for navigator (#1891)
  downstream/attributes/attributes.adoc
Labels: Title change, 2.5

#1897 2.5 AAP-27695 Add Ansible plug-in for RHDH Installation doc (#1634)
  downstream/assemblies/devtools/assembly-rhdh-configure.adoc
  downstream/assemblies/devtools/assembly-rhdh-install-ocp.adoc
  downstream/assemblies/devtools/assembly-rhdh-install.adoc
  downstream/assemblies/devtools/assembly-rhdh-intro.adoc
  downstream/assemblies/devtools/assembly-rhdh-uninstall-ocp.adoc
  downstream/assemblies/devtools/assembly-rhdh-upgrade-ocp.adoc
  downstream/assemblies/devtools/assembly-rhdh-upgrading-uninstalling.adoc
  downstream/attributes/attributes.adoc
  downstream/images/rhdh-ansible-plugin-architecture.png
  downstream/images/rhdh-check-devtools-container.png
  downstream/images/rhdh-check-plugin-config.png
  downstream/images/rhdh-plugin-registry.png
  downstream/modules/devtools/proc-rhdh-add-additional-scm.adoc
  downstream/modules/devtools/proc-rhdh-add-devtools-container.adoc
  downstream/modules/devtools/proc-rhdh-add-plugin-config.adoc
  downstream/modules/devtools/proc-rhdh-add-plugin-software-templates.adoc
  downstream/modules/devtools/proc-rhdh-add-pull-secret-helm.adoc
  downstream/modules/devtools/proc-rhdh-configure-aap-details.adoc
  downstream/modules/devtools/proc-rhdh-configure-devspaces.adoc
  downstream/modules/devtools/proc-rhdh-configure-devtools-server.adoc
  downstream/modules/devtools/proc-rhdh-configure-optional-integrations.adoc
  downstream/modules/devtools/proc-rhdh-configure-pah-url.adoc
  downstream/modules/devtools/proc-rhdh-configure-rbac.adoc
  downstream/modules/devtools/proc-rhdh-configure-telemetry.adoc
  downstream/modules/devtools/proc-rhdh-create-plugin-registry.adoc
  downstream/modules/devtools/proc-rhdh-devtools-sidecar.adoc
  downstream/modules/devtools/proc-rhdh-download-plugins.adoc
  downstream/modules/devtools/proc-rhdh-enable-rhdh-authentication.adoc
  downstream/modules/devtools/proc-rhdh-uninstall-ocp.adoc
  downstream/modules/devtools/proc-rhdh-update-plugin-registry.adoc
  downstream/modules/devtools/proc-rhdh-update-plugins-version-numbers.adoc
  downstream/modules/devtools/proc-rhdh-warning-aap-ooc.adoc
  downstream/modules/devtools/proc-rhdh-warning-invalid-aap-config.adoc
  downstream/modules/devtools/proc-rhdh-warning-invalid-aap-subscription.adoc
  downstream/modules/devtools/proc-rhdh-warning-unable-authenticate-aap.adoc
  downstream/modules/devtools/proc-rhdh-warning-unable-connect-aap.adoc
  downstream/modules/devtools/ref-rhdh-about-plugins.adoc
  downstream/modules/devtools/ref-rhdh-about-rhdh.adoc
  downstream/modules/devtools/ref-rhdh-architecture.adoc
  downstream/modules/devtools/ref-rhdh-install-ocp-prereqs.adoc
  downstream/modules/devtools/ref-rhdh-plugin-subscription-warning.adoc
  downstream/titles/aap-plugin-rhdh-install/docinfo.xml
  downstream/titles/aap-plugin-rhdh-install/master.adoc
  downstream/titles/aap-plugin-rhdh-install/snippets
Labels: 2.5

#1898 AAP-27696 Create Using Ansible Plug-ins guide (#1635)
  downstream/assemblies/devtools/assembly-rhdh-example.adoc
  downstream/assemblies/devtools/assembly-rhdh-feedback.adoc
  downstream/assemblies/devtools/assembly-rhdh-using.adoc
  downstream/images/rhdh-feedback-form.png
  downstream/images/rhdh-plugin-dashboard.png
  downstream/images/rhdh-vscode-run-playbook.png
  downstream/modules/devtools/proc-rhdh-create.adoc
  downstream/modules/devtools/proc-rhdh-develop-projects-devspaces.adoc
  downstream/modules/devtools/proc-rhdh-develop-projects.adoc
  downstream/modules/devtools/proc-rhdh-execute-automation-devspaces.adoc
  downstream/modules/devtools/proc-rhdh-firewall-example-create-playbook.adoc
  downstream/modules/devtools/proc-rhdh-firewall-example-discover.adoc
  downstream/modules/devtools/proc-rhdh-firewall-example-edit.adoc
  downstream/modules/devtools/proc-rhdh-firewall-example-learn.adoc
  downstream/modules/devtools/proc-rhdh-firewall-example-new-playbook.adoc
  downstream/modules/devtools/proc-rhdh-set-up-controller-project.adoc
  downstream/modules/devtools/proc-rhdh-view.adoc
  downstream/modules/devtools/ref-rhdh-dashboard.adoc
  downstream/modules/devtools/ref-rhdh-discover-collections.adoc
  downstream/modules/devtools/ref-rhdh-learning.adoc
  downstream/titles/aap-plugin-rhdh-using/docinfo.xml
  downstream/titles/aap-plugin-rhdh-using/master.adoc
  downstream/titles/aap-plugin-rhdh-using/snippets
Labels: 2.5

#1899 Update topology doc title
  downstream/attributes/attributes.adoc
  downstream/titles/topologies/docinfo.xml
  downstream/titles/topologies/master.adoc
Labels: 2.5, Needs backport to 2.5

#1893 AAP-25619 Symlinks for Analytics doc
  downstream/titles/analytics/aap-common
  downstream/titles/analytics/aap-common/apache-2.0-license.adoc
  downstream/titles/analytics/aap-common/assembly-aap-common.adoc
  downstream/titles/analytics/aap-common/boilerplate.adoc
  downstream/titles/analytics/aap-common/external-site-disclaimer.adoc
  downstream/titles/analytics/aap-common/gplv3-license-text.adoc
  downstream/titles/analytics/aap-common/making-open-source-more-inclusive.adoc
  downstream/titles/analytics/aap-common/providing-feedback.adoc
  downstream/titles/analytics/analytics
  downstream/titles/analytics/attributes
  downstream/titles/analytics/attributes/attributes.adoc
  downstream/titles/analytics/images
  downstream/titles/analytics/snippets
Labels: Ready for review, Needs backport to 2.5

#1901 2.5 AAP-25619 Symlinks for Analytics doc (#1893)
  downstream/titles/analytics/aap-common
  downstream/titles/analytics/aap-common/apache-2.0-license.adoc
  downstream/titles/analytics/aap-common/assembly-aap-common.adoc
  downstream/titles/analytics/aap-common/boilerplate.adoc
  downstream/titles/analytics/aap-common/external-site-disclaimer.adoc
  downstream/titles/analytics/aap-common/gplv3-license-text.adoc
  downstream/titles/analytics/aap-common/making-open-source-more-inclusive.adoc
  downstream/titles/analytics/aap-common/providing-feedback.adoc
  downstream/titles/analytics/analytics
  downstream/titles/analytics/attributes
  downstream/titles/analytics/attributes/attributes.adoc
  downstream/titles/analytics/images
  downstream/titles/analytics/snippets
Labels: 2.5

#1900 2.5 Update topology doc title (#1899)
  downstream/attributes/attributes.adoc
  downstream/titles/topologies/docinfo.xml
  downstream/titles/topologies/master.adoc
Labels: Title change, Attributes, 2.5

#1902 Add diagrams and inventory files to topology guide
  downstream/images/cont-a-env-a.png
  downstream/images/cont-b-env-a.png
  downstream/images/rpm-b-env-a.png
  downstream/images/rpm-b-env-b.png
  downstream/modules/topologies/ref-cont-a-env-a.adoc
  downstream/modules/topologies/ref-cont-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-b.adoc
Labels: 2.5, Needs backport to 2.5

#1903 2.5 Add diagrams and inventory files to topology guide (#1902)
  downstream/images/cont-a-env-a.png
  downstream/images/cont-b-env-a.png
  downstream/images/rpm-b-env-a.png
  downstream/images/rpm-b-env-b.png
  downstream/modules/topologies/ref-cont-a-env-a.adoc
  downstream/modules/topologies/ref-cont-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-b.adoc
Labels: 2.5

#1905 Add Redis config info to containerized installer guide
  downstream/modules/platform/proc-installing-containerized-aap.adoc
Labels: 2.5, Needs backport to 2.5

#1907 2.5 Add Redis config info to containerized installer guide (#1905)
  downstream/modules/platform/proc-installing-containerized-aap.adoc
Labels: 2.5

#1908 Update links in inventory files for containerized install
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/topologies/ref-cont-a-env-a.adoc
Labels: 2.5, Needs backport to 2.5

#1909 2.5 Update links in inventory files for containerized install (#1908)
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/topologies/ref-cont-a-env-a.adoc
Labels: 2.5

#1910 updating topology link
  downstream/modules/platform/con-about-operator.adoc
Labels: documentation, 2.5, AAP operator

#1911 updating topology link (#1910)
  downstream/modules/platform/con-about-operator.adoc
Labels: documentation, 2.5, AAP operator

#1912 Update url & references to topology guide
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/assemblies/topologies/assembly-overview-tested-deployment-models.adoc
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/titles/topologies/master.adoc
Labels: 2.5, Needs backport to 2.5

#1913 2.5 Update url & references to topology guide (#1912)
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/assemblies/topologies/assembly-overview-tested-deployment-models.adoc
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/titles/topologies/master.adoc
Labels: 2.5

#1906 AAP-26519-B archived analytics titles
  downstream/archive/archived-titles/analytics/automation-savings-planner/docinfo.xml
  downstream/archive/archived-titles/analytics/automation-savings-planner/master.adoc
  downstream/archive/archived-titles/analytics/automation-savings/docinfo.xml
  downstream/archive/archived-titles/analytics/automation-savings/master.adoc
  downstream/archive/archived-titles/analytics/job-explorer/docinfo.xml
  downstream/archive/archived-titles/analytics/job-explorer/master.adoc
  downstream/archive/archived-titles/analytics/reports/docinfo.xml
  downstream/archive/archived-titles/analytics/reports/master.adoc
  downstream/titles/analytics/automation-savings-planner/aap-common
  downstream/titles/analytics/automation-savings-planner/analytics
  downstream/titles/analytics/automation-savings-planner/attributes
  downstream/titles/analytics/automation-savings-planner/images
  downstream/titles/analytics/automation-savings/aap-common
  downstream/titles/analytics/automation-savings/analytics
  downstream/titles/analytics/automation-savings/attributes
  downstream/titles/analytics/job-explorer/.gitkeep
  downstream/titles/analytics/job-explorer/aap-common
  downstream/titles/analytics/job-explorer/analytics
  downstream/titles/analytics/job-explorer/attributes
  downstream/titles/analytics/master.adoc
  downstream/titles/analytics/reports/aap-common
  downstream/titles/analytics/reports/analytics
  downstream/titles/analytics/reports/attributes
Labels: Ready for review, 2.5, Needs backport to 2.5

#1916 2.3 Remove attributes from title names
  downstream/titles/aap-installation-guide/master.adoc
  downstream/titles/aap-operations-guide/master.adoc
  downstream/titles/aap-operator-backup/master.adoc
  downstream/titles/aap-operator-installation/master.adoc
  downstream/titles/aap-planning-guide/master.adoc
  downstream/titles/automation-mesh/docinfo.xml
  downstream/titles/automation-mesh/master.adoc
  downstream/titles/central-auth/master.adoc
  downstream/titles/dev-guide/master.adoc
  downstream/titles/hub/configuring-private-hub-rh-certified/master.adoc
  downstream/titles/hub/getting-started/master.adoc
  downstream/titles/hub/high-availability/master.adoc
  downstream/titles/hub/install/master.adoc
  downstream/titles/hub/manage-containers/master.adoc
  downstream/titles/ocp_performance_guide/master.adoc
  downstream/titles/upgrade/master.adoc
  downstream/titles/worker-install/master.adoc
Labels: 2.3

#1917 AAP-29296-B updated About the installer inventory file
  downstream/assemblies/platform/assembly-inventory-introduction.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#1918 AAP-29296-B updated About the installer inventory file (#1917)
  downstream/assemblies/platform/assembly-inventory-introduction.adoc
Labels: Ready for review, 2.5

#1895 AAP-31307 Add attributes for title URLs
  downstream/attributes/attributes.adoc
Labels: Attributes, 2.5, Needs backport to 2.5

#1896 2.4 AAP-31308 Attributes for title names and URLs
  downstream/attributes/attributes.adoc
Labels: Ready for review, Attributes, 2.4

#1920 2.5 AAP-31307 Add attributes for title URLs (#1895)
  downstream/attributes/attributes.adoc
Labels: 2.5

#1921 AAP18813 - Adding OAuth/Application content to the access management guid (#1874)
  downstream/assemblies/platform/assembly-controller-applications.adoc
  downstream/assemblies/platform/assembly-gw-token-based-authentication.adoc
  downstream/modules/platform/proc-controller-apps-create-tokens.adoc
  downstream/modules/platform/proc-controller-create-application.adoc
  downstream/modules/platform/ref-controller-app-token-functions.adoc
  downstream/modules/platform/ref-controller-applications-getting-started.adoc
  downstream/modules/platform/ref-controller-revoke-access-token.adoc
  downstream/modules/platform/ref-gw-access-rules-apps-tokens.adoc
  downstream/modules/platform/ref-gw-application-functions.adoc
  downstream/modules/platform/ref-gw-request-token-after-expiration.adoc
Labels: Ready for review, 2.5

#1922 2.4 Use attributes to reference Navigator Title and URL (#1894)
  downstream/assemblies/platform/assembly-migrate-legacy-venv-to-ee.adoc
  downstream/assemblies/troubleshooting-aap/assembly-troubleshoot-playbooks.adoc
  downstream/modules/devtools/proc-devtools-extension-run-ansible-navigator.adoc
  downstream/modules/devtools/proc-devtools-testing-playbook.adoc
Labels: 2.4

#1923 2.5 Use attributes to reference Navigator Title and URL (#1894)
  downstream/assemblies/platform/assembly-migrate-legacy-venv-to-ee.adoc
  downstream/assemblies/troubleshooting-aap/assembly-troubleshoot-playbooks.adoc
  downstream/modules/devtools/proc-devtools-extension-run-ansible-navigator.adoc
  downstream/modules/devtools/proc-devtools-testing-playbook.adoc
Labels: 2.5

#1924 AAP-26512 - Update example for SAML Security Config per SME feedback
  downstream/modules/platform/proc-controller-set-up-SAML.adoc
Labels: Ready for review, Needs backport to 2.4, 2.4, 2.5, Needs backport to 2.5

#1926 AAP-30395 Fix JSON example and update devtools attribute
  downstream/attributes/attributes.adoc
  downstream/modules/devtools/proc-devtools-install-container.adoc
Labels: Needs backport to 2.4, Attributes, Needs backport to 2.5

#1928 2.4 AAP-30395 Fix JSON example and update devtools attribute (#1926)
  downstream/attributes/attributes.adoc
  downstream/modules/devtools/proc-devtools-install-container.adoc
Labels: 2.4

#1927 2.5 AAP-30395 Fix JSON example and update devtools attribute (#1926)
  downstream/attributes/attributes.adoc
  downstream/modules/devtools/proc-devtools-install-container.adoc
Labels: Attributes, 2.5

#1925 [Backport] AAP-26512 - Update example for SAML Security Config per SME feedback
  downstream/modules/platform/proc-controller-set-up-SAML.adoc
Labels: Ready for review, 2.5

#1930 AAP-25769 Update ansible-core and PlatformDownloadURL attributes for 2.5
  downstream/attributes/attributes.adoc
Labels: Attributes, 2.5, Needs backport to 2.5

#1932 2.5 AAP-25769 Update ansible-core and PlatformDownloadURL attributes for …
  downstream/attributes/attributes.adoc
Labels: Attributes, 2.5

#1867 Removing TBDs from Controller docs
  downstream/assemblies/platform/assembly-ag-controller-usability-analytics.adoc
  downstream/assemblies/platform/assembly-controller-secret-management.adoc
  downstream/modules/platform/con-controller-overview-details.adoc
  downstream/modules/platform/con-controller-role-based-access-controls.adoc
  downstream/modules/platform/proc-controller-configure-analytics.adoc
  downstream/modules/platform/proc-controller-importing-subscriptions.adoc
  downstream/modules/platform/proc-controller-view-host.adoc
  downstream/modules/platform/ref-controller-analytics-reports.adoc
  downstream/modules/platform/ref-controller-automation-analytics.adoc
  downstream/modules/platform/ref-controller-content-sourcing.adoc
  downstream/titles/controller/controller-admin-guide/master.adoc
  downstream/titles/controller/controller-user-guide/master.adoc
Labels: documentation, Controller, 2.5, Needs backport to 2.5

#1933 [Backport] Removing TBDs from Controller docs (#1867)
  downstream/assemblies/platform/assembly-ag-controller-usability-analytics.adoc
  downstream/assemblies/platform/assembly-controller-secret-management.adoc
  downstream/modules/platform/con-controller-overview-details.adoc
  downstream/modules/platform/con-controller-role-based-access-controls.adoc
  downstream/modules/platform/proc-controller-configure-analytics.adoc
  downstream/modules/platform/proc-controller-importing-subscriptions.adoc
  downstream/modules/platform/proc-controller-view-host.adoc
  downstream/modules/platform/ref-controller-analytics-reports.adoc
  downstream/modules/platform/ref-controller-automation-analytics.adoc
  downstream/modules/platform/ref-controller-content-sourcing.adoc
  downstream/titles/controller/controller-admin-guide/master.adoc
  downstream/titles/controller/controller-user-guide/master.adoc
Labels: Ready for review, 2.5

#1934 Include peer review fixes for PR 1933
  downstream/modules/platform/con-controller-role-based-access-controls.adoc
  downstream/modules/platform/proc-controller-create-instance-group.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#1935 [Backport] Include peer review fixes for PR 1933 (#1934)
  downstream/modules/platform/con-controller-role-based-access-controls.adoc
  downstream/modules/platform/proc-controller-create-instance-group.adoc
Labels: Ready for review, 2.5

#1870 Adding note about building EE image
  downstream/modules/builder/proc-executing-build.adoc
  downstream/modules/platform/ref-controller-install-builder.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#1938 2.5 AAP-30403 Add registry.redhat.io auth procedure to devtools (#1937)
  downstream/assemblies/devtools/assembly-devtools-install.adoc
  downstream/modules/devtools/con-devtools-requirements.adoc
  downstream/modules/devtools/proc-devtools-install-container.adoc
  downstream/modules/devtools/proc-devtools-setup-registry-redhat-io.adoc
Labels: 2.5

#1939 2.4 AAP-30403 Add registry.redhat.io auth procedure to devtools (#1937)
  downstream/assemblies/devtools/assembly-devtools-install.adoc
  downstream/modules/devtools/con-devtools-requirements.adoc
  downstream/modules/devtools/proc-devtools-install-container.adoc
  downstream/modules/devtools/proc-devtools-setup-registry-redhat-io.adoc
Labels: 2.4

#1940 Adding note about building EE image (#1870)
  downstream/modules/builder/proc-executing-build.adoc
  downstream/modules/platform/ref-controller-install-builder.adoc
Labels: documentation, 2.5, Backported to 2.5

#1904 AAP-30807 - Converting Overview and System requirements assemblies into repo
  downstream/assemblies/platform/assembly-platform-install-overview.adoc
  downstream/assemblies/platform/assembly-system-requirements.adoc
  downstream/modules/platform/proc-benchmark-postgresql.adoc
  downstream/modules/platform/proc-enable-hstore-extension.adoc
  downstream/modules/platform/proc-setup-postgresql-ext-database.adoc
  downstream/modules/platform/ref-automation-hub-requirements.adoc
  downstream/modules/platform/ref-controller-system-requirements.adoc
  downstream/modules/platform/ref-eda-system-requirements.adoc
  downstream/modules/platform/ref-gateway-system-requirements.adoc
  downstream/modules/platform/ref-ha-hub-reqs.adoc
  downstream/modules/platform/ref-postgresql-requirements.adoc
  downstream/modules/platform/ref-system-requirements.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#1942 AAP-30716 Add YAML separator in devtools example
  downstream/modules/devtools/proc-devtools-writing-first-playbook.adoc
Labels: Needs backport to 2.4, 2.4, 2.5, Needs backport to 2.5

#1943 AAP-30807 - Converting Overview and System requirements assemblies in…
  downstream/assemblies/platform/assembly-platform-install-overview.adoc
  downstream/assemblies/platform/assembly-system-requirements.adoc
  downstream/modules/platform/proc-benchmark-postgresql.adoc
  downstream/modules/platform/proc-enable-hstore-extension.adoc
  downstream/modules/platform/proc-setup-postgresql-ext-database.adoc
  downstream/modules/platform/ref-automation-hub-requirements.adoc
  downstream/modules/platform/ref-controller-system-requirements.adoc
  downstream/modules/platform/ref-eda-system-requirements.adoc
  downstream/modules/platform/ref-gateway-system-requirements.adoc
  downstream/modules/platform/ref-ha-hub-reqs.adoc
  downstream/modules/platform/ref-postgresql-requirements.adoc
  downstream/modules/platform/ref-system-requirements.adoc
Labels: documentation, 2.5

#1946 2.4AAP-30716 Add YAML separator in devtools example (#1942)
  downstream/modules/devtools/proc-devtools-writing-first-playbook.adoc
Labels: 2.4

#1945 2.5 AAP-30716 Add YAML separator in devtools example (#1942)
  downstream/modules/devtools/proc-devtools-writing-first-playbook.adoc
Labels: 2.5

#1944 Update procedures for automation mesh
  downstream/modules/platform/proc-define-mesh-node-types.adoc
  downstream/modules/platform/proc-set-up-virtual-machines.adoc
Labels: documentation, Automation Mesh, 2.5

#1947 Update procedures for automation mesh (#1944)
  downstream/modules/platform/proc-define-mesh-node-types.adoc
  downstream/modules/platform/proc-set-up-virtual-machines.adoc
Labels: documentation, Automation Mesh, 2.5

#1955 [2.5] AAP-30807: Edit 2.4 links (#1936)
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
  downstream/modules/platform/con-adding-subscription-manifest.adoc
  downstream/modules/platform/con-ha-hub-installation.adoc
  downstream/modules/platform/con-install-scenario-recommendations.adoc
  downstream/modules/platform/proc-running-setup-script.adoc
  downstream/modules/platform/proc-set-registry-username-password.adoc
  downstream/modules/platform/proc-verify-aap-installation.adoc
  downstream/modules/platform/ref-gateway-controller-ext-db.adoc
  downstream/modules/platform/ref-gateway-controller-hub-eda-ext-db.adoc
Labels: documentation, 2.5, Backported to 2.5

#1956 AAP-30592 - Divide the Platform gateway settings into separate procedures by option
  downstream/assemblies/platform/assembly-gw-settings.adoc
  downstream/modules/platform/proc-controller-configure-subscriptions.adoc
  downstream/modules/platform/proc-settings-gw-additional-options.adoc
  downstream/modules/platform/proc-settings-gw-custom-login.adoc
  downstream/modules/platform/proc-settings-gw-password-security.adoc
  downstream/modules/platform/proc-settings-gw-security-options.adoc
  downstream/modules/platform/proc-settings-gw-session-options.adoc
  downstream/modules/platform/proc-settings-platform-gateway.adoc
  downstream/modules/platform/proc-settings-troubleshooting.adoc
  downstream/modules/platform/proc-settings-user-preferences.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#1954 AAP-29066 Getting started guide conceptual overview ascii conversion
  downstream/assemblies/platform/assembly-gs-key-functionality.adoc
  downstream/modules/platform/con-gs-automation-content.adoc
  downstream/modules/platform/con-gs-automation-execution.adoc
  downstream/modules/platform/con-gs-automation-mesh.adoc
  downstream/modules/platform/con-gs-dashboard-components.adoc
  downstream/modules/platform/con-gs-developer-tools.adoc
  downstream/modules/platform/con-gs-final-set-up.adoc
  downstream/titles/getting-started/snippets
Labels: Not ready for peer review, Main, 2.5, Needs backport to 2.5

#1957 [Backport] AAP-30592 - Divide the Platform gateway settings into separate procedures by option (#1956)
  downstream/assemblies/platform/assembly-gw-settings.adoc
  downstream/modules/platform/proc-controller-configure-subscriptions.adoc
  downstream/modules/platform/proc-settings-gw-additional-options.adoc
  downstream/modules/platform/proc-settings-gw-custom-login.adoc
  downstream/modules/platform/proc-settings-gw-password-security.adoc
  downstream/modules/platform/proc-settings-gw-security-options.adoc
  downstream/modules/platform/proc-settings-gw-session-options.adoc
  downstream/modules/platform/proc-settings-platform-gateway.adoc
  downstream/modules/platform/proc-settings-troubleshooting.adoc
  downstream/modules/platform/proc-settings-user-preferences.adoc
Labels: Ready for review, 2.5

#1958 backport to 2.5: AAP-29066 Getting started guide conceptual overview ascii conversion …
  downstream/assemblies/platform/assembly-gs-key-functionality.adoc
  downstream/modules/platform/con-gs-automation-content.adoc
  downstream/modules/platform/con-gs-automation-execution.adoc
  downstream/modules/platform/con-gs-automation-mesh.adoc
  downstream/modules/platform/con-gs-dashboard-components.adoc
  downstream/modules/platform/con-gs-developer-tools.adoc
  downstream/modules/platform/con-gs-final-set-up.adoc
  downstream/titles/getting-started/snippets
Labels: 2.5

#1953 AAP-29296-D added platform gateway content to the planning guide
  downstream/assemblies/platform/assembly-aap-platform-components.adoc
  downstream/assemblies/platform/assembly-inventory-introduction.adoc
  downstream/modules/platform/con-about-platform-gateway.adoc
  downstream/modules/platform/ref-guidelines-hosts-groups.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#1919 AAP-29296-C updated diagrams
  downstream/assemblies/platform/assembly-aap-architecture.adoc
  downstream/images/OCP_B_Env_A.png
  downstream/images/aap-network-ports-protocols.png
  downstream/modules/platform/con-aap-example-architecture.adoc
  downstream/modules/platform/ref-example-CONT-architecture.adoc
  downstream/modules/platform/ref-example-OCP-architecture.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#1960 AAP-29296-D added platform gateway content to the planning guide (#1953)
  downstream/assemblies/platform/assembly-aap-platform-components.adoc
  downstream/assemblies/platform/assembly-inventory-introduction.adoc
  downstream/modules/platform/con-about-platform-gateway.adoc
  downstream/modules/platform/ref-guidelines-hosts-groups.adoc
Labels: Ready for review, 2.5

#1961 AAP-29296-C updated diagrams (#1919)
  downstream/assemblies/platform/assembly-aap-architecture.adoc
  downstream/images/OCP_B_Env_A.png
  downstream/images/aap-network-ports-protocols.png
  downstream/modules/platform/con-aap-example-architecture.adoc
  downstream/modules/platform/ref-example-CONT-architecture.adoc
  downstream/modules/platform/ref-example-OCP-architecture.adoc
Labels: Ready for review, 2.5

#1871 Edits to key functionality chapter
  downstream/assemblies/platform/assembly-gs-auto-dev.adoc
  downstream/images/AAP_dashboard_2.5.png
  downstream/modules/platform/con-gs-dashboard-components.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#1963 Edits to key functionality chapter (#1871)
  downstream/assemblies/platform/assembly-gs-auto-dev.adoc
  downstream/images/AAP_dashboard_2.5.png
  downstream/modules/platform/con-gs-dashboard-components.adoc
Labels: documentation, 2.5, Backported to 2.5

#1962 AAP-29296-E updated tested deployment models
  downstream/titles/aap-planning-guide/master.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#1966 AAP-28228-C added xrefs to topology table
  downstream/assemblies/topologies/assembly-overview-tested-deployment-models.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#1968 AAP-28228-C added xrefs to topology table (#1966)
  downstream/assemblies/topologies/assembly-overview-tested-deployment-models.adoc
Labels: Ready for review, 2.5

#1959 AAP-31307a Add title, URL attributes for Lightspeed
  downstream/attributes/attributes.adoc
Labels: Needs backport to 2.4, 2.4, 2.5, Needs backport to 2.5

#1969 AAP-29296-E updated tested deployment models (#1962)
  downstream/titles/aap-planning-guide/master.adoc
Labels: Ready for review, 2.5

#1967 AAP-29296-F added HA redis content
  downstream/assemblies/platform/assembly-HA-redis.adoc
  downstream/modules/platform/con-gw-clustered-redis.adoc
  downstream/titles/aap-planning-guide/master.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#1971 AAP-29296-F added HA redis content (#1967)
  downstream/assemblies/platform/assembly-HA-redis.adoc
  downstream/modules/platform/con-gw-clustered-redis.adoc
  downstream/titles/aap-planning-guide/master.adoc
Labels: Ready for review, 2.5

#1973 2.5 AAP-29500 Update devcontainer.json (#1972)
  downstream/modules/devtools/proc-devtools-install-container.adoc
Labels: 2.5

#1974 AAP-29500 Update devcontainer.json (#1972)
  downstream/modules/devtools/proc-devtools-install-container.adoc
Labels: 2.4

#1975 AAP-30807 Remove git artefacts
  downstream/modules/platform/ref-automation-hub-requirements.adoc
Labels: 2.5

#1977 21776 - changed single-node to standalone Redis and other fixes
  downstream/assemblies/platform/assembly-HA-redis.adoc
  downstream/assemblies/topologies/assembly-overview-tested-deployment-models.adoc
  downstream/modules/platform/con-gw-centralized-redis.adoc
  downstream/modules/platform/con-gw-clustered-redis.adoc
  downstream/modules/platform/con-gw-single-node-redis.adoc
  downstream/modules/platform/ref-example-CONT-architecture.adoc
  downstream/modules/platform/ref-example-OCP-architecture.adoc
  downstream/titles/aap-planning-guide/master.adoc
  downstream/titles/aap-planning-guide/topologies
Labels: Ready for review, 2.5, Needs backport to 2.5

#1981 [Backport] 21776 - changed single-node to standalone Redis and other fixes (#1977)
  downstream/assemblies/platform/assembly-HA-redis.adoc
  downstream/assemblies/topologies/assembly-overview-tested-deployment-models.adoc
  downstream/modules/platform/con-gw-centralized-redis.adoc
  downstream/modules/platform/con-gw-clustered-redis.adoc
  downstream/modules/platform/con-gw-single-node-redis.adoc
  downstream/modules/platform/ref-example-CONT-architecture.adoc
  downstream/modules/platform/ref-example-OCP-architecture.adoc
  downstream/titles/aap-planning-guide/master.adoc
  downstream/titles/aap-planning-guide/topologies
Labels: Ready for review, 2.5

#1983 opg-fix - Removed activating manifest files
  downstream/titles/aap-operations-guide/master.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#1985 cae-fix - Correcting broken xrefs due to information moving to a new document
  downstream/assemblies/platform/assembly-controller-secret-management.adoc
  downstream/modules/platform/ref-controller-config-json.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#1984 AAP-31577 Add attribute for unified platform dashboard
  downstream/attributes/attributes.adoc
Labels: 2.5, Needs backport to 2.5

#1988 2.5 AAP-31577 Add attribute for unified platform dashboard (#1984)
  downstream/attributes/attributes.adoc
Labels: Attributes, 2.5

#1986 [Backport] cae-fix - Correcting broken xrefs due to information moving to a new document (#1985)
  downstream/assemblies/platform/assembly-controller-secret-management.adoc
  downstream/modules/platform/ref-controller-config-json.adoc
Labels: Ready for review, 2.5

#1987 [Backport] opg-fix - Removed activating manifest files because this is now covered in the access management guide (#1983)
  downstream/titles/aap-operations-guide/master.adoc
Labels: Ready for review, 2.5

#1989 2.4 Add RPM 2.4-7.3 async release notes
  downstream/titles/release-notes/master.adoc
  downstream/titles/release-notes/topics/rpm-24-73.adoc
  downstream/titles/release-notes/topics/rpm-version-table.adoc
Labels: AAP Release notes, 2.4

#1991 Update topology docs based on feedback
  downstream/modules/topologies/ref-rpm-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-b.adoc
Labels: 2.5, Needs backport to 2.5

#1992 2.5 Update topology docs based on feedback (#1991)
  downstream/modules/topologies/ref-rpm-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-b.adoc
Labels: 2.5

#1990 Update to the Appendixes 1-6 for Automation Platform guide 2.5
  downstream/assemblies/platform/assembly-appendix-inventory-file-vars.adoc
  downstream/modules/platform/ref-ansible-inventory-variables.adoc
  downstream/modules/platform/ref-controller-variables.adoc
  downstream/modules/platform/ref-eda-controller-variables.adoc
  downstream/modules/platform/ref-gateway-variables.adoc
  downstream/modules/platform/ref-general-inventory-variables.adoc
  downstream/modules/platform/ref-hub-variables.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#1995 AAP-30602 - Include step to register and update commands to include sudo
  downstream/modules/platform/proc-attaching-subscriptions.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#1994 AAP-30807-A: Add General variables for container
  downstream/assemblies/platform/assembly-appendix-inventory-file-vars.adoc
  downstream/modules/platform/ref-general-inventory-variables.adoc
Labels: documentation, 2.5, Needs backport to 2.5
