Repository ansible/aap-docs, pull requests merged in 2024-03, with the labels that each got.

#1049 Adding injectors information
  downstream/modules/platform/ref-controller-credential-aap.adoc
  downstream/modules/platform/ref-controller-credential-insights.adoc
  downstream/modules/platform/ref-controller-credential-virtualization.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#1055 Adding injectors information (#1049)
  downstream/modules/platform/ref-controller-credential-aap.adoc
  downstream/modules/platform/ref-controller-credential-insights.adoc
  downstream/modules/platform/ref-controller-credential-virtualization.adoc
Labels: documentation, Backported to 2.4, Controller, 2.4

#1056 Add installer-2.4-6 release notes
  downstream/titles/release-notes/master.adoc
  downstream/titles/release-notes/topics/eda-24.adoc
  downstream/titles/release-notes/topics/installer-24-6.adoc
Labels: Ready for review, Needs backport to 2.4

#1057 Add installer-2.4-6 release notes (#1056)
  downstream/titles/release-notes/master.adoc
  downstream/titles/release-notes/topics/eda-24.adoc
  downstream/titles/release-notes/topics/installer-24-6.adoc
Labels: 2.4

#1058 AAP-17672 Updating install guide on building execution environnments …
  downstream/assemblies/platform/assembly-disconnected-installation.adoc
  downstream/modules/platform/con-building-an-execution-environment-in-a-disconnected-environment.adoc
  downstream/modules/platform/proc-building-the-custom-execution-environment.adoc
  downstream/modules/platform/proc-creating-the-custom-execution-environment-definition.adoc
  downstream/modules/platform/proc-installing-the-ansible-builder-rpm.adoc
  downstream/modules/platform/proc-upgrading-between-minor-aap-releases.adoc
  downstream/modules/platform/proc-uploading-the-custom-execution-environment-to-the-private-hub.adoc
Labels: Ready for review, 2.4

#1063 Correct heading level for installer 2.4-6 release notes
  downstream/titles/release-notes/master.adoc
Labels: Ready for review, Needs backport to 2.4

#1031 Create structure for operator-based mesh guide
  downstream/assemblies/platform/assembly-automation-mesh-operator-aap.adoc
  downstream/assemblies/platform/assembly-planning-mesh.adoc
  downstream/attributes/attributes.adoc
  downstream/images/MeshIngress.png
  downstream/images/instances_list_view2.png
  downstream/modules/platform/con-about-automation-mesh.adoc
  downstream/modules/platform/con-automation-mesh-node-types.adoc
  downstream/modules/platform/proc-connecting-nodes-through-mesh-ingress.adoc
  downstream/modules/platform/proc-define-mesh-node-types.adoc
  downstream/modules/platform/proc-pulling-the-secret.adoc
  downstream/modules/platform/proc-run-jobs-on-execution-nodes.adoc
  downstream/modules/platform/proc-set-up-virtual-machines.adoc
  downstream/modules/platform/ref-operator-mesh-prerequisites.adoc
  downstream/modules/platform/ref-removing-instances.adoc
  downstream/titles/operator-mesh/aap-common
  downstream/titles/operator-mesh/attributes
  downstream/titles/operator-mesh/docinfo.xml
  downstream/titles/operator-mesh/images
  downstream/titles/operator-mesh/master.adoc
  downstream/titles/operator-mesh/platform
Labels: documentation, Needs backport to 2.4, 2.4

#1065 Create structure for operator-based mesh guide (#1031)
  downstream/assemblies/platform/assembly-automation-mesh-operator-aap.adoc
  downstream/assemblies/platform/assembly-planning-mesh.adoc
  downstream/attributes/attributes.adoc
  downstream/images/MeshIngress.png
  downstream/images/instances_list_view2.png
  downstream/modules/platform/con-about-automation-mesh.adoc
  downstream/modules/platform/con-automation-mesh-node-types.adoc
  downstream/modules/platform/proc-connecting-nodes-through-mesh-ingress.adoc
  downstream/modules/platform/proc-define-mesh-node-types.adoc
  downstream/modules/platform/proc-pulling-the-secret.adoc
  downstream/modules/platform/proc-run-jobs-on-execution-nodes.adoc
  downstream/modules/platform/proc-set-up-virtual-machines.adoc
  downstream/modules/platform/ref-operator-mesh-prerequisites.adoc
  downstream/modules/platform/ref-removing-instances.adoc
  downstream/titles/operator-mesh/aap-common
  downstream/titles/operator-mesh/attributes
  downstream/titles/operator-mesh/docinfo.xml
  downstream/titles/operator-mesh/images
  downstream/titles/operator-mesh/master.adoc
  downstream/titles/operator-mesh/platform
Labels: documentation, Backported to 2.4, 2.4

#1066 Replace plain text with attributes for content in the eda module
  downstream/modules/eda/con-about-event-driven-ansible.adoc
  downstream/modules/eda/proc-eda-build-a-custom-decision-environment.adoc
  downstream/modules/eda/proc-eda-set-up-token.adoc
  downstream/modules/eda/ref-installing-eda-controller-on-aap.adoc
Labels: Ready for review, Needs backport to 2.4

#1068 Added information to inventory variable. (#1053)
  downstream/modules/platform/ref-controller-variables.adoc
  downstream/modules/platform/ref-hub-variables.adoc
Labels: documentation, Backported to 2.4, 2.4

#1069 Add title for Automation Controller API Guide
  downstream/titles/controller/controller-api-guide/aap-common
  downstream/titles/controller/controller-api-guide/attributes
  downstream/titles/controller/controller-api-guide/docinfo.xml
  downstream/titles/controller/controller-api-guide/images
  downstream/titles/controller/controller-api-guide/master.adoc
  downstream/titles/controller/controller-api-guide/platform
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#1070 Add title for Automation Controller API Guide (#1069)
  downstream/titles/controller/controller-api-guide/aap-common
  downstream/titles/controller/controller-api-guide/attributes
  downstream/titles/controller/controller-api-guide/docinfo.xml
  downstream/titles/controller/controller-api-guide/images
  downstream/titles/controller/controller-api-guide/master.adoc
  downstream/titles/controller/controller-api-guide/platform
Labels: documentation, Backported to 2.4, Controller, 2.4

#1071 Corrected typo
  downstream/modules/platform/ref-controller-variables.adoc
Labels: documentation, Needs backport to 2.4, 2.4

#1072 Corrected typo (#1071)
  downstream/modules/platform/ref-controller-variables.adoc
Labels: Backported to 2.4, 2.4

#1074 Replace plain text with attributes for content in the hub module (#1073)
  downstream/modules/hub/proc-add-user-to-group.adoc
  downstream/modules/hub/proc-assigning-permissions.adoc
  downstream/modules/hub/proc-configure-automation-hub-server-gui.adoc
  downstream/modules/hub/proc-configure-content-signing-on-pah.adoc
  downstream/modules/hub/proc-create-credential.adoc
  downstream/modules/hub/proc-create-groups.adoc
  downstream/modules/hub/proc-deploying-your-system-for-container-signing.adoc
  downstream/modules/hub/proc-shared-filesystem.adoc
  downstream/modules/hub/proc-using-content-signing-services-in-pah.adoc
Labels: 2.4

#1075 Create section 1 of controller API guide
  downstream/assemblies/platform/assembly-controller-api-access-resources.adoc
  downstream/assemblies/platform/assembly-controller-api-auth-methods.adoc
  downstream/assemblies/platform/assembly-controller-api-browsing-api.adoc
  downstream/assemblies/platform/assembly-controller-api-conventions.adoc
  downstream/assemblies/platform/assembly-controller-api-filter.adoc
  downstream/assemblies/platform/assembly-controller-api-pagination.adoc
  downstream/assemblies/platform/assembly-controller-api-readonly-fields.adoc
  downstream/assemblies/platform/assembly-controller-api-search.adoc
  downstream/assemblies/platform/assembly-controller-api-sorting.adoc
  downstream/assemblies/platform/assembly-controller-api-tools.adoc
  downstream/modules/platform/ref-controller-api-tools.adoc
  downstream/titles/controller/controller-api-guide/master.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#1076 Create section 1 of controller API guide (#1075)
  downstream/assemblies/platform/assembly-controller-api-access-resources.adoc
  downstream/assemblies/platform/assembly-controller-api-auth-methods.adoc
  downstream/assemblies/platform/assembly-controller-api-browsing-api.adoc
  downstream/assemblies/platform/assembly-controller-api-conventions.adoc
  downstream/assemblies/platform/assembly-controller-api-filter.adoc
  downstream/assemblies/platform/assembly-controller-api-pagination.adoc
  downstream/assemblies/platform/assembly-controller-api-readonly-fields.adoc
  downstream/assemblies/platform/assembly-controller-api-search.adoc
  downstream/assemblies/platform/assembly-controller-api-sorting.adoc
  downstream/assemblies/platform/assembly-controller-api-tools.adoc
  downstream/modules/platform/ref-controller-api-tools.adoc
  downstream/titles/controller/controller-api-guide/master.adoc
Labels: Backported to 2.4, 2.4

#1080 Updating LDAP CA steps
  downstream/modules/platform/proc-controller-import-CA-cert-LDAP.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#1082 Updating LDAP CA steps (#1080)
  downstream/modules/platform/proc-controller-import-CA-cert-LDAP.adoc
Labels: documentation, Backported to 2.4, Controller, 2.4

#1083 Add bundle installer 2.4-6 release notes
  downstream/titles/release-notes/master.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-6.adoc
  downstream/titles/release-notes/topics/installer-24-6.adoc
Labels: Ready for review, Needs backport to 2.4, AAP Release notes

#1084 Add bundle installer 2.4-6 release notes (#1083)
  downstream/titles/release-notes/master.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-6.adoc
  downstream/titles/release-notes/topics/installer-24-6.adoc
Labels: AAP Release notes, 2.4

#1085 AAP 21323
  downstream/images/instances_create_details.png
  downstream/images/instances_create_new.png
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#1086 AAP 21323 (#1085)
  downstream/images/instances_create_details.png
  downstream/images/instances_create_new.png
Labels: documentation, Backported to 2.4, Controller, 2.4

#1087 Create section 2 of controller API guide
  downstream/assemblies/platform/assembly-controller-api-browsing-api.adoc
  downstream/images/api-questionmark.png
  downstream/modules/platform/proc-controller-api-browsing-api.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#1088 Create section 2 of controller API guide (#1087)
  downstream/assemblies/platform/assembly-controller-api-browsing-api.adoc
  downstream/images/api-questionmark.png
  downstream/modules/platform/proc-controller-api-browsing-api.adoc
Labels: documentation, Backported to 2.4, Controller, 2.4

#1078 AAP-15176: fixes broken links in getting started with ansible playbooks guide
  downstream/modules/playbooks/ref-create-variables.adoc
Labels: Ready for review, Needs backport to 2.4, 2.4, Main

#1089 Backport to 2.4 - AAP-15176: fixes broken links in getting started with ansible playbooks guide (#1078)
  downstream/modules/playbooks/ref-create-variables.adoc
Labels: Backported to 2.4, 2.4

#1091 Added secrets lookup section (#1081)
  downstream/assemblies/platform/assembly-controller-secret-management.adoc
  downstream/images/credentials-create-aws-secret-credential.png
  downstream/modules/platform/proc-controller-configure-secret-lookups.adoc
  downstream/modules/platform/ref-aws-secrets-manager-lookup.adoc
  downstream/modules/platform/ref-controller-metadata-credential-input.adoc
Labels: Backported to 2.4, Controller, 2.4

#1090 AAP-20343: Created docs for post GA bot improvements feature
  lightspeed/assemblies/assembly_managing-admin-dashboard-telemetry.adoc
  lightspeed/assemblies/assembly_using-code-bot-for-suggestions.adoc
  lightspeed/images/ansible-code-bot-dashboard-kebab-icon.png
  lightspeed/modules/con-manage-repo-scans.adoc
  lightspeed/modules/con_telemetry-data-collection-notice.adoc
  lightspeed/modules/con_training-data.adoc
  lightspeed/modules/proc_add-remove-repo-from-scans.adoc
  lightspeed/modules/proc_configure-repo-scan.adoc
  lightspeed/modules/proc_install-code-bot.adoc
  lightspeed/modules/proc_manually-scan-repo.adoc
  lightspeed/modules/proc_obtain-config-wca-and-model-id.adoc
  lightspeed/modules/proc_view-repo-scan-history.adoc
  lightspeed/titles/lightspeed-release-notes/master.adoc
  lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-7march2024.adoc
Labels: Ready for review, Lightspeed

#1093 Commented out include statement (#1092)
  downstream/assemblies/platform/assembly-automation-mesh-operator-aap.adoc
  downstream/modules/platform/ref-removing-instances.adoc
Labels: Backported to 2.4, 2.4

#1095 Backport to 2.4: AAP-20141: adds note about api token never expiring (#1077)
  downstream/modules/hub/proc-create-api-token-pah.adoc
  downstream/modules/hub/proc-create-api-token.adoc
Labels: Automation Hub, 2.4

#1096 AAP-18653-updates: Added telemetry data collection notice and release…
  lightspeed/assemblies/assembly_managing-admin-dashboard-telemetry.adoc
  lightspeed/modules/con_telemetry-data-collection-notice.adoc
  lightspeed/modules/con_training-data.adoc
  lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-7march2024.adoc
Labels: Ready for review, Lightspeed

#1094 Create sections 3, 4, 5, 6, and 7 of controller API guide
  downstream/assemblies/platform/assembly-controller-api-conventions.adoc
  downstream/assemblies/platform/assembly-controller-api-filter.adoc
  downstream/assemblies/platform/assembly-controller-api-pagination.adoc
  downstream/assemblies/platform/assembly-controller-api-search.adoc
  downstream/assemblies/platform/assembly-controller-api-sorting.adoc
  downstream/modules/platform/proc-controller-api-browsing-api.adoc
  downstream/modules/platform/proc-controller-api-filtering.adoc
  downstream/modules/platform/proc-controller-api-sorting.adoc
  downstream/modules/platform/proc-controller-api-using-pagination.adoc
  downstream/modules/platform/ref-controller-api-advanced-queries.adoc
  downstream/modules/platform/ref-controller-api-conventions.adoc
  downstream/modules/platform/ref-controller-api-field-lookups.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#1097 Create sections 3, 4, 5, 6, and 7 of controller API guide (#1094)
  downstream/assemblies/platform/assembly-controller-api-conventions.adoc
  downstream/assemblies/platform/assembly-controller-api-filter.adoc
  downstream/assemblies/platform/assembly-controller-api-pagination.adoc
  downstream/assemblies/platform/assembly-controller-api-search.adoc
  downstream/assemblies/platform/assembly-controller-api-sorting.adoc
  downstream/modules/platform/proc-controller-api-browsing-api.adoc
  downstream/modules/platform/proc-controller-api-filtering.adoc
  downstream/modules/platform/proc-controller-api-sorting.adoc
  downstream/modules/platform/proc-controller-api-using-pagination.adoc
  downstream/modules/platform/ref-controller-api-advanced-queries.adoc
  downstream/modules/platform/ref-controller-api-conventions.adoc
  downstream/modules/platform/ref-controller-api-field-lookups.adoc
Labels: documentation, Backported to 2.4, Controller, 2.4

#1100 Create sections 8 and 9 of controller API guide
  downstream/assemblies/platform/assembly-controller-api-access-resources.adoc
  downstream/assemblies/platform/assembly-controller-api-readonly-fields.adoc
  downstream/modules/platform/con-controller-api-identifier-format-protocol.adoc
  downstream/modules/platform/con-controller-api-readonly-fields.adoc
  downstream/modules/platform/ref-controller-api-config-settings.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#1101 Create sections 8 and 9 of controller API guide (#1100)
  downstream/assemblies/platform/assembly-controller-api-access-resources.adoc
  downstream/assemblies/platform/assembly-controller-api-readonly-fields.adoc
  downstream/modules/platform/con-controller-api-identifier-format-protocol.adoc
  downstream/modules/platform/con-controller-api-readonly-fields.adoc
  downstream/modules/platform/ref-controller-api-config-settings.adoc
Labels: documentation, Backported to 2.4, Controller, 2.4

#1103 Add requirement for UBI CDN FQDN (#1099)
  downstream/modules/platform/con-building-an-execution-environment-in-a-disconnected-environment.adoc
Labels: Backported to 2.4, 2.4

#1112 2.4 Update .gitignore
  .gitignore
Labels: repo

#1113 Update .gitignore to ignore .vscode directory
  .gitignore
Labels: repo

#1114 Correcting Typo
  downstream/modules/platform/proc-controller-set-up-generic-oidc.adoc
Labels: Needs backport to 2.4

#1106 Replace plain text with attributes for content in the navigator module
  downstream/assemblies/navigator/assembly-review-ee-navigator.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/navigator/con-navigator-collections.adoc
  downstream/modules/navigator/proc-browse-collections-tui.adoc
  downstream/modules/navigator/proc-installing-navigator-rhel-rpm.adoc
  downstream/modules/navigator/proc-review-ee-tui.adoc
  downstream/modules/navigator/ref-navigator-command-summary.adoc
Labels: Ready for review, Needs backport to 2.4

#1116 Replace plain text with attributes for content in the navigator modul…
  downstream/assemblies/navigator/assembly-review-ee-navigator.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/navigator/con-navigator-collections.adoc
  downstream/modules/navigator/proc-browse-collections-tui.adoc
  downstream/modules/navigator/proc-installing-navigator-rhel-rpm.adoc
  downstream/modules/navigator/proc-review-ee-tui.adoc
  downstream/modules/navigator/ref-navigator-command-summary.adoc
Labels: 2.4

#1050 AAP-18707 Updated procedure with EDA max running activations
  downstream/modules/platform/proc-deploy-eda-controller-with-aap-operator-ocp.adoc
  downstream/modules/platform/ref-eda-controller-variables.adoc
  downstream/modules/platform/ref-eda-system-requirements.adoc
  downstream/modules/platform/ref-single-controller-hub-eda-with-managed-db.adoc
Labels: Ready for review, Needs backport to 2.4, Technical review complete, 2.4, 2.5

#1102 Create sections 10 of controller API guide
  downstream/assemblies/platform/assembly-controller-api-auth-methods.adoc
  downstream/assemblies/platform/assembly-controller-api-tools.adoc
  downstream/images/api_oauth2_json_returned_token_value.png
  downstream/images/session-auth-architecture.png
  downstream/modules/platform/con-controller-api-basic-auth.adoc
  downstream/modules/platform/con-controller-api-oauth2-token.adoc
  downstream/modules/platform/con-controller-api-sso-auth.adoc
  downstream/modules/platform/con-controller-api-tools.adoc
  downstream/modules/platform/proc-controller-api-session-auth.adoc
  downstream/titles/controller/controller-api-guide/docinfo.xml
  downstream/titles/controller/controller-api-guide/master.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#1118 Create sections 10 of controller API guide (#1102)
  downstream/assemblies/platform/assembly-controller-api-auth-methods.adoc
  downstream/assemblies/platform/assembly-controller-api-tools.adoc
  downstream/images/api_oauth2_json_returned_token_value.png
  downstream/images/session-auth-architecture.png
  downstream/modules/platform/con-controller-api-basic-auth.adoc
  downstream/modules/platform/con-controller-api-oauth2-token.adoc
  downstream/modules/platform/con-controller-api-sso-auth.adoc
  downstream/modules/platform/con-controller-api-tools.adoc
  downstream/modules/platform/proc-controller-api-session-auth.adoc
  downstream/titles/controller/controller-api-guide/docinfo.xml
  downstream/titles/controller/controller-api-guide/master.adoc
Labels: documentation, Backported to 2.4, Controller, 2.4

#1120 Replace plain text with attributes for content in the platform module…
  downstream/modules/platform/con-aap-example-architecture.adoc
  downstream/modules/platform/con-aap-upgrade-planning.adoc
  downstream/modules/platform/con-aap-upgrade-prereq.adoc
  downstream/modules/platform/con-aap-upgrades-legacy.adoc
  downstream/modules/platform/con-about-eda-controller.adoc
  downstream/modules/platform/con-about-navigator.adoc
  downstream/modules/platform/con-about-operator.adoc
  downstream/modules/platform/con-about-pa-hub.adoc
  downstream/modules/platform/con-controller-deprovision-instance-groups.adoc
  downstream/modules/platform/con-install-scenario-recommendations.adoc
  downstream/modules/platform/con-operator-additional-resources.adoc
  downstream/modules/platform/con-persisting-data-from-auto-runs.adoc
  downstream/modules/platform/con-single-eda-controller-with-internal-database.adoc
  downstream/modules/platform/con-why-ee.adoc
  downstream/modules/platform/con-why-migrate-ansible-29.adoc
Labels: 2.4

#1121 Final review of the Controller API Overview
  downstream/modules/platform/con-controller-api-identifier-format-protocol.adoc
  downstream/modules/platform/proc-controller-api-session-auth.adoc
  downstream/modules/platform/ref-controller-api-advanced-queries.adoc
  downstream/modules/platform/ref-controller-api-config-settings.adoc
  downstream/modules/platform/ref-controller-api-field-lookups.adoc
  downstream/titles/controller/controller-api-overview/aap-common
  downstream/titles/controller/controller-api-overview/attributes
  downstream/titles/controller/controller-api-overview/docinfo.xml
  downstream/titles/controller/controller-api-overview/images
  downstream/titles/controller/controller-api-overview/master.adoc
  downstream/titles/controller/controller-api-overview/platform
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#1122 Final review of the Controller API Overview (#1121)
  downstream/modules/platform/con-controller-api-identifier-format-protocol.adoc
  downstream/modules/platform/proc-controller-api-session-auth.adoc
  downstream/modules/platform/ref-controller-api-advanced-queries.adoc
  downstream/modules/platform/ref-controller-api-config-settings.adoc
  downstream/modules/platform/ref-controller-api-field-lookups.adoc
  downstream/titles/controller/controller-api-overview/aap-common
  downstream/titles/controller/controller-api-overview/attributes
  downstream/titles/controller/controller-api-overview/docinfo.xml
  downstream/titles/controller/controller-api-overview/images
  downstream/titles/controller/controller-api-overview/master.adoc
  downstream/titles/controller/controller-api-overview/platform
Labels: documentation, Backported to 2.4, Controller, 2.4

#1127 Combine operator-mesh info with Controller Admin
  downstream/assemblies/platform/assembly-controller-instances.adoc
  downstream/modules/platform/proc-define-mesh-node-types.adoc
  downstream/modules/platform/proc-set-up-virtual-machines.adoc
  downstream/modules/platform/ref-operator-mesh-prerequisites.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#1133 Combine operator-mesh info with Controller Admin (#1127)
  downstream/assemblies/platform/assembly-controller-instances.adoc
  downstream/modules/platform/proc-define-mesh-node-types.adoc
  downstream/modules/platform/proc-set-up-virtual-machines.adoc
  downstream/modules/platform/ref-operator-mesh-prerequisites.adoc
Labels: Backported to 2.4, 2.4

#1131 Added link to Managing Content
  downstream/assemblies/hub/assembly-managing-collections-hub.adoc
Labels: Needs backport to 2.4, 2.4

#1134 Added link to Managing Content (#1131)
  downstream/assemblies/hub/assembly-managing-collections-hub.adoc
Labels: Backported to 2.4, 2.4

#1132 Adding missing info to extra vars section
  downstream/assemblies/platform/assembly-controller-awx-manage-utility.adoc
  downstream/modules/platform/ref-controller-extra-variables.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#1135 Adding missing info to extra vars section (#1132)
  downstream/assemblies/platform/assembly-controller-awx-manage-utility.adoc
  downstream/modules/platform/ref-controller-extra-variables.adoc
Labels: documentation, Backported to 2.4, Controller, 2.4

#1130 AAP-20863: Adds EDA controller variables to procedure for changing SSL certification
  downstream/modules/platform/proc-change-ssl-installer.adoc
  downstream/modules/platform/ref-eda-controller-variables.adoc
Labels: Ready for review, Needs backport to 2.4, 2.4, Main

#1137 AAP-20863: Adds EDA controller variables to procedure for changing SSL certification (#1130)
  downstream/modules/platform/proc-change-ssl-installer.adoc
  downstream/modules/platform/ref-eda-controller-variables.adoc
Labels: Backported to 2.4, 2.4

#1139 AAP-19591: Added RH and IBM support links
  lightspeed/modules/proc_provide-feedback.adoc
  lightspeed/modules/proc_troubleshooting-lightspeed-config.adoc
Labels: Ready for review, Lightspeed

#1140 Modified link addresses (#1138)
  downstream/assemblies/platform/assembly-controller-topology-viewer.adoc
  downstream/assemblies/platform/assembly-custom-inventory-scripts.adoc
  downstream/modules/platform/con-why-automation-mesh.adoc
  downstream/modules/platform/proc-controller-access-topology-viewer.adoc
  downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
Labels: Backported to 2.4, 2.4

#1141 Update controller admin guide LDAP info
  downstream/modules/platform/proc-controller-set-up-LDAP.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#1143 Replace plain text with attributes for content in the platform module
  downstream/modules/platform/con-why-migrate-venvs-ee.adoc
  downstream/modules/platform/proc-apply-selinux-context.adoc
  downstream/modules/platform/proc-choosing-obtaining-installer.adoc
  downstream/modules/platform/proc-configuring-controller-ldap-security.adoc
  downstream/modules/platform/proc-controller-awx-manage-utility.adoc
  downstream/modules/platform/proc-controller-importing-subscriptions.adoc
  downstream/modules/platform/proc-controller-use-an-exec-env.adoc
  downstream/modules/platform/proc-create-password-hashes.adoc
  downstream/modules/platform/proc-customizing-pod-specs.adoc
  downstream/modules/platform/proc-deprovisioning-mesh-nodes.adoc
  downstream/modules/platform/proc-install-cli-aap-operator.adoc
  downstream/modules/platform/proc-installing-with-internet.adoc
  downstream/modules/platform/proc-update-ee-image-locations.adoc
  downstream/modules/platform/proc-update-rhsso-client.adoc
  downstream/modules/platform/proc-upgrade-installer.adoc
  downstream/modules/platform/proc-verify-controller-installation.adoc
  downstream/modules/platform/ref-container-resource-requirements.adoc
  downstream/modules/platform/ref-controller-amazon-web-services.adoc
  downstream/modules/platform/ref-controller-automation-analytics.adoc
  downstream/modules/platform/ref-controller-aws-cloud.adoc
Labels: Ready for review, Needs backport to 2.4

#1128 Altered smart inventory details
  downstream/modules/platform/ref-controller-smart-inventories.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#1149 Correction to The _awx-manage_ Utility section
  downstream/assemblies/platform/assembly-controller-awx-manage-utility.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#1148 Altered smart inventory details (#1128)
  downstream/modules/platform/ref-controller-smart-inventories.adoc
Labels: documentation, Backported to 2.4, Controller, 2.4

#1150 Correction to The _awx-manage_ Utility section (#1149)
  downstream/assemblies/platform/assembly-controller-awx-manage-utility.adoc
Labels: documentation, Backported to 2.4, Controller, 2.4

#1151 Replace plain text with attributes for content in the platform module
  downstream/modules/platform/ref-controller-build-arg-defaults.adoc
  downstream/modules/platform/ref-controller-building-exec-env.adoc
  downstream/modules/platform/ref-controller-cluster-install.adoc
  downstream/modules/platform/ref-controller-config-options.adoc
  downstream/modules/platform/ref-controller-config-version.adoc
  downstream/modules/platform/ref-controller-credential-GCE.adoc
  downstream/modules/platform/ref-controller-credential-aws.adoc
  downstream/modules/platform/ref-controller-dependencies.adoc
  downstream/modules/platform/ref-controller-ee-configuration-options.adoc
  downstream/modules/platform/ref-controller-ee-definition.adoc
  downstream/modules/platform/ref-controller-images.adoc
  downstream/modules/platform/ref-controller-notification-email.adoc
  downstream/modules/platform/ref-controller-setup-considerations.adoc
  downstream/modules/platform/ref-controller-supported-oses.adoc
  downstream/modules/platform/ref-controller-system-requirements.adoc
  downstream/modules/platform/ref-converting-playbook-examples.adoc
  downstream/modules/platform/ref-enabling-automation-hub-collection-and-container-signing.adoc
  downstream/modules/platform/ref-hub-variables.adoc
Labels: Ready for review, Needs backport to 2.4

#1156 Replace plain text with attributes for content in the platform module…
  downstream/modules/platform/ref-controller-build-arg-defaults.adoc
  downstream/modules/platform/ref-controller-building-exec-env.adoc
  downstream/modules/platform/ref-controller-cluster-install.adoc
  downstream/modules/platform/ref-controller-config-options.adoc
  downstream/modules/platform/ref-controller-config-version.adoc
  downstream/modules/platform/ref-controller-credential-GCE.adoc
  downstream/modules/platform/ref-controller-credential-aws.adoc
  downstream/modules/platform/ref-controller-dependencies.adoc
  downstream/modules/platform/ref-controller-ee-configuration-options.adoc
  downstream/modules/platform/ref-controller-ee-definition.adoc
  downstream/modules/platform/ref-controller-images.adoc
  downstream/modules/platform/ref-controller-notification-email.adoc
  downstream/modules/platform/ref-controller-setup-considerations.adoc
  downstream/modules/platform/ref-controller-supported-oses.adoc
  downstream/modules/platform/ref-controller-system-requirements.adoc
  downstream/modules/platform/ref-converting-playbook-examples.adoc
  downstream/modules/platform/ref-enabling-automation-hub-collection-and-container-signing.adoc
  downstream/modules/platform/ref-hub-variables.adoc
Labels: 2.4

#1157 Replace plain text with attributes for content in the aap-hardening module
  downstream/assemblies/aap-hardening/assembly-intro-to-aap-hardening.adoc
  downstream/modules/aap-hardening/con-aap-additional-software.adoc
  downstream/modules/aap-hardening/con-controller-stig-considerations.adoc
  downstream/modules/aap-hardening/con-external-credential-vault.adoc
  downstream/modules/aap-hardening/con-hardening-guide-audience.adoc
  downstream/modules/aap-hardening/con-install-secure-host.adoc
  downstream/modules/aap-hardening/con-logging-log-capture.adoc
  downstream/modules/aap-hardening/con-network-firewall-services-planning.adoc
  downstream/modules/aap-hardening/con-rbac.adoc
  downstream/modules/aap-hardening/con-rhel-host-planning.adoc
  downstream/modules/aap-hardening/con-user-authentication-planning.adoc
  downstream/modules/aap-hardening/proc-configure-centralized-logging.adoc
  downstream/modules/aap-hardening/proc-controller-stig-considerations.adoc
  downstream/modules/aap-hardening/proc-disaster-recovery-operations.adoc
  downstream/modules/aap-hardening/proc-fapolicyd.adoc
  downstream/modules/aap-hardening/proc-file-systems-mounted-noexec.adoc
  downstream/modules/aap-hardening/proc-namespaces.adoc
  downstream/modules/aap-hardening/ref-architecture.adoc
  downstream/modules/aap-hardening/ref-auditing-incident-detection.adoc
  downstream/modules/aap-hardening/ref-automation-controller-authentication.adoc
  downstream/modules/aap-hardening/ref-automation-controller-operational-secrets.adoc
  downstream/modules/aap-hardening/ref-dns-load-balancing.adoc
  downstream/modules/aap-hardening/ref-infrastructure-as-code.adoc
  downstream/modules/aap-hardening/ref-ntp.adoc
  downstream/modules/aap-hardening/ref-private-automation-hub-authentication.adoc
  downstream/modules/aap-hardening/ref-security-variables-install-inventory.adoc
  downstream/modules/aap-hardening/ref-sudo-nopasswd.adoc
Labels: Needs backport to 2.4

#1158 Replace plain text with attributes for content in the aap-hardening m…
  downstream/assemblies/aap-hardening/assembly-intro-to-aap-hardening.adoc
  downstream/modules/aap-hardening/con-aap-additional-software.adoc
  downstream/modules/aap-hardening/con-controller-stig-considerations.adoc
  downstream/modules/aap-hardening/con-external-credential-vault.adoc
  downstream/modules/aap-hardening/con-hardening-guide-audience.adoc
  downstream/modules/aap-hardening/con-install-secure-host.adoc
  downstream/modules/aap-hardening/con-logging-log-capture.adoc
  downstream/modules/aap-hardening/con-network-firewall-services-planning.adoc
  downstream/modules/aap-hardening/con-rbac.adoc
  downstream/modules/aap-hardening/con-rhel-host-planning.adoc
  downstream/modules/aap-hardening/con-user-authentication-planning.adoc
  downstream/modules/aap-hardening/proc-configure-centralized-logging.adoc
  downstream/modules/aap-hardening/proc-controller-stig-considerations.adoc
  downstream/modules/aap-hardening/proc-disaster-recovery-operations.adoc
  downstream/modules/aap-hardening/proc-fapolicyd.adoc
  downstream/modules/aap-hardening/proc-file-systems-mounted-noexec.adoc
  downstream/modules/aap-hardening/proc-namespaces.adoc
  downstream/modules/aap-hardening/ref-architecture.adoc
  downstream/modules/aap-hardening/ref-auditing-incident-detection.adoc
  downstream/modules/aap-hardening/ref-automation-controller-authentication.adoc
  downstream/modules/aap-hardening/ref-automation-controller-operational-secrets.adoc
  downstream/modules/aap-hardening/ref-dns-load-balancing.adoc
  downstream/modules/aap-hardening/ref-infrastructure-as-code.adoc
  downstream/modules/aap-hardening/ref-ntp.adoc
  downstream/modules/aap-hardening/ref-private-automation-hub-authentication.adoc
  downstream/modules/aap-hardening/ref-security-variables-install-inventory.adoc
  downstream/modules/aap-hardening/ref-sudo-nopasswd.adoc
Labels: 2.4

#1159 Replace plain text with attributes for content in the builder module
  downstream/modules/builder/con-about-ee.adoc
  downstream/modules/builder/con-container_file.adoc
  downstream/modules/builder/con-ee-precedence.adoc
  downstream/modules/builder/proc-customize-ee-image.adoc
  downstream/modules/builder/proc-push-execenv-to-hub.adoc
  downstream/modules/builder/ref-build-args-base-image.adoc
Labels: Ready for review, 2.3

#1160 Replace plain text with attributes for content in the builder module …
  downstream/modules/builder/con-about-ee.adoc
  downstream/modules/builder/con-container_file.adoc
  downstream/modules/builder/con-ee-precedence.adoc
  downstream/modules/builder/proc-customize-ee-image.adoc
  downstream/modules/builder/proc-push-execenv-to-hub.adoc
  downstream/modules/builder/ref-build-args-base-image.adoc
Labels: 2.2

#1161 Update repo URL in README
  README.adoc
Labels: Needs backport to 2.4, Needs backport to 2.3, Needs backport to 2.2, Needs backport to 2.1, Needs backport to 2.0-ea

#1168 Replace plain text with attributes for content in the core module
  downstream/modules/core/con-ansible-roles.adoc
  downstream/modules/core/con-content-collections.adoc
  downstream/modules/core/con-execution-environments.adoc
Labels: 2.3

#1169 Replace plain text with attributes for content in the core module (#1…
  downstream/modules/core/con-ansible-roles.adoc
  downstream/modules/core/con-content-collections.adoc
  downstream/modules/core/con-execution-environments.adoc
Labels: 2.2

#1155 Editorial changes to Chaps 1-8 Controller UG
  downstream/assemblies/platform/assembly-UG-overview.adoc
  downstream/assemblies/platform/assembly-controller-licensing.adoc
  downstream/assemblies/platform/assembly-controller-login.adoc
  downstream/assemblies/platform/assembly-controller-managing-subscriptions.adoc
  downstream/assemblies/platform/assembly-controller-search.adoc
  downstream/assemblies/platform/assembly-controller-user-interface.adoc
  downstream/assemblies/platform/assembly-controller-users.adoc
  downstream/modules/platform/con-controller-administration.adoc
  downstream/modules/platform/con-controller-create-users.adoc
  downstream/modules/platform/con-controller-host-metric-utilities.adoc
  downstream/modules/platform/con-controller-keep-subscription-in-compliance.adoc
  downstream/modules/platform/con-controller-overview-details.adoc
  downstream/modules/platform/con-controller-settings.adoc
  downstream/modules/platform/proc-controller-adding-subscription-manually.adoc
  downstream/modules/platform/proc-controller-api-endpoint-functions.adoc
  downstream/modules/platform/proc-controller-attaching-subscriptions.adoc
  downstream/modules/platform/proc-controller-creating-a-user.adoc
  downstream/modules/platform/proc-controller-deleting-a-user.adoc
  downstream/modules/platform/proc-controller-importing-subscriptions.adoc
  downstream/modules/platform/proc-controller-logging-in.adoc
  downstream/modules/platform/proc-controller-obtaining-subscriptions-manifest.adoc
  downstream/modules/platform/proc-controller-obtaining-subscriptions.adoc
  downstream/modules/platform/proc-controller-user-permissions.adoc
  downstream/modules/platform/proc-controller-user-tokens.adoc
  downstream/modules/platform/ref-controller-dependencies.adoc
  downstream/modules/platform/ref-controller-licenses.adoc
  downstream/modules/platform/ref-controller-search-tips.adoc
  downstream/modules/platform/ref-controller-trial-evaluation.adoc
  downstream/modules/platform/ref-controller-user-organizations.adoc
  downstream/modules/platform/ref-controller-user-roles.adoc
  downstream/modules/platform/ref-controller-user-teams.adoc
  downstream/titles/controller/controller-user-guide/master.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#1170 Editorial changes to Chaps 1-8 Controller UG (#1155)
  downstream/assemblies/platform/assembly-UG-overview.adoc
  downstream/assemblies/platform/assembly-controller-licensing.adoc
  downstream/assemblies/platform/assembly-controller-login.adoc
  downstream/assemblies/platform/assembly-controller-managing-subscriptions.adoc
  downstream/assemblies/platform/assembly-controller-search.adoc
  downstream/assemblies/platform/assembly-controller-user-interface.adoc
  downstream/assemblies/platform/assembly-controller-users.adoc
  downstream/modules/platform/con-controller-administration.adoc
  downstream/modules/platform/con-controller-create-users.adoc
  downstream/modules/platform/con-controller-host-metric-utilities.adoc
  downstream/modules/platform/con-controller-keep-subscription-in-compliance.adoc
  downstream/modules/platform/con-controller-overview-details.adoc
  downstream/modules/platform/con-controller-settings.adoc
  downstream/modules/platform/proc-controller-adding-subscription-manually.adoc
  downstream/modules/platform/proc-controller-api-endpoint-functions.adoc
  downstream/modules/platform/proc-controller-attaching-subscriptions.adoc
  downstream/modules/platform/proc-controller-creating-a-user.adoc
  downstream/modules/platform/proc-controller-deleting-a-user.adoc
  downstream/modules/platform/proc-controller-importing-subscriptions.adoc
  downstream/modules/platform/proc-controller-logging-in.adoc
  downstream/modules/platform/proc-controller-obtaining-subscriptions-manifest.adoc
  downstream/modules/platform/proc-controller-obtaining-subscriptions.adoc
  downstream/modules/platform/proc-controller-user-permissions.adoc
  downstream/modules/platform/proc-controller-user-tokens.adoc
  downstream/modules/platform/ref-controller-dependencies.adoc
  downstream/modules/platform/ref-controller-licenses.adoc
  downstream/modules/platform/ref-controller-search-tips.adoc
  downstream/modules/platform/ref-controller-trial-evaluation.adoc
  downstream/modules/platform/ref-controller-user-organizations.adoc
  downstream/modules/platform/ref-controller-user-roles.adoc
  downstream/modules/platform/ref-controller-user-teams.adoc
  downstream/titles/controller/controller-user-guide/master.adoc
Labels: documentation, Backported to 2.4, Controller, 2.4

#1171 Correction to Controller UG
  downstream/modules/platform/ref-controller-dependencies.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#1172 Correction to Controller UG (#1171)
  downstream/modules/platform/ref-controller-dependencies.adoc
Labels: Backported to 2.4, 2.4

#1173 AAP-21516 Update links to use BaseURL attribute in platform assemblies
  downstream/assemblies/platform/assembly-ag-controller-backup-and-restore.adoc
  downstream/assemblies/platform/assembly-ag-controller-security-best-practices.adoc
  downstream/assemblies/platform/assembly-ag-instance-and-container-groups.adoc
  downstream/assemblies/platform/assembly-automation-mesh-operator-aap.adoc
  downstream/assemblies/platform/assembly-controller-credentials.adoc
  downstream/assemblies/platform/assembly-controller-instances.adoc
  downstream/assemblies/platform/assembly-controller-inventories.adoc
  downstream/assemblies/platform/assembly-controller-job-templates.adoc
  downstream/assemblies/platform/assembly-disconnected-installation.adoc
  downstream/assemblies/platform/assembly-install-aap-operator.adoc
  downstream/assemblies/platform/assembly-install-upgrade-pah.adoc
  downstream/assemblies/platform/assembly-installing-aap-operator-cli.adoc
  downstream/assemblies/platform/assembly-installing-controller-operator.adoc
  downstream/assemblies/platform/assembly-installing-hub-operator.adoc
  downstream/assemblies/platform/assembly-inventory-file-importing.adoc
  downstream/assemblies/platform/assembly-migrate-legacy-venv-to-ee.adoc
  downstream/assemblies/platform/assembly-planning-installation.adoc
  downstream/assemblies/platform/assembly-platform-install-overview.adoc
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
  downstream/assemblies/platform/assembly-setting-up-automation-mesh.adoc
  downstream/assemblies/platform/assembly-supported-installation-scenarios.adoc
  downstream/assemblies/platform/assembly-system-requirements.adoc
  downstream/assemblies/platform/assembly-using-rhsso-operator-with-automation-hub.adoc
Labels: Needs backport to 2.4, 2.4

#1174 Update OCPLatest version to 4.15
  downstream/attributes/attributes.adoc
Labels: Needs backport to 2.4, Attributes, 2.4

#1175 Replace plain text with attributes for content in the dev-guide module.
  downstream/modules/dev-guide/proc-create-collections.adoc
  downstream/modules/dev-guide/proc-create-role.adoc
Labels: Ready for review, 2.3

#1177 Replace plain text with attributes for content in the dev-guide modul…
  downstream/modules/dev-guide/proc-create-collections.adoc
  downstream/modules/dev-guide/proc-create-role.adoc
Labels: 2.2

#1178 2.4 Update OCPLatest version to 4.15 (#1174)
  downstream/attributes/attributes.adoc
Labels: Attributes, 2.4

#1176 2.4 AAP-21516 Update links to use BaseURL attribute in platform assemblie…
  downstream/assemblies/platform/assembly-ag-controller-backup-and-restore.adoc
  downstream/assemblies/platform/assembly-ag-controller-security-best-practices.adoc
  downstream/assemblies/platform/assembly-ag-instance-and-container-groups.adoc
  downstream/assemblies/platform/assembly-automation-mesh-operator-aap.adoc
  downstream/assemblies/platform/assembly-controller-credentials.adoc
  downstream/assemblies/platform/assembly-controller-instances.adoc
  downstream/assemblies/platform/assembly-controller-inventories.adoc
  downstream/assemblies/platform/assembly-controller-job-templates.adoc
  downstream/assemblies/platform/assembly-disconnected-installation.adoc
  downstream/assemblies/platform/assembly-install-aap-operator.adoc
  downstream/assemblies/platform/assembly-install-upgrade-pah.adoc
  downstream/assemblies/platform/assembly-installing-aap-operator-cli.adoc
  downstream/assemblies/platform/assembly-installing-controller-operator.adoc
  downstream/assemblies/platform/assembly-installing-hub-operator.adoc
  downstream/assemblies/platform/assembly-inventory-file-importing.adoc
  downstream/assemblies/platform/assembly-migrate-legacy-venv-to-ee.adoc
  downstream/assemblies/platform/assembly-planning-installation.adoc
  downstream/assemblies/platform/assembly-platform-install-overview.adoc
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
  downstream/assemblies/platform/assembly-setting-up-automation-mesh.adoc
  downstream/assemblies/platform/assembly-supported-installation-scenarios.adoc
  downstream/assemblies/platform/assembly-system-requirements.adoc
  downstream/assemblies/platform/assembly-using-rhsso-operator-with-automation-hub.adoc
Labels: 2.4

#1145 Removing unnecessary Azure DNS allowlist.
  stories/topics/proc-azure-update-route-tables.adoc
Labels: AAP on clouds, AAP on Azure

#1179 Replace plain text with attributes for content in the automation-hub …
  downstream/modules/automation-hub/con-about-automation-hub.adoc
  downstream/modules/automation-hub/con-ansible-galaxy-client.adoc
  downstream/modules/automation-hub/con-collections.adoc
  downstream/modules/automation-hub/con-create-api-token.adoc
  downstream/modules/automation-hub/con-user-access.adoc
  downstream/modules/automation-hub/proc-adding-an-execution-environment.adoc
  downstream/modules/automation-hub/proc-configure-automation-hub-server-cli.adoc
  downstream/modules/automation-hub/proc-configure-automation-hub-server-gui.adoc
  downstream/modules/automation-hub/proc-configure-content-signing-on-pah.adoc
  downstream/modules/automation-hub/proc-create-api-token-pah.adoc
  downstream/modules/automation-hub/proc-create-credential.adoc
  downstream/modules/automation-hub/proc-create-super-users.adoc
  downstream/modules/automation-hub/proc-create-users.adoc
  downstream/modules/automation-hub/proc-delete-namespace.adoc
  downstream/modules/automation-hub/proc-deploying-your-system-for-container-signing.adoc
  downstream/modules/automation-hub/proc-set-community-remote.adoc
  downstream/modules/automation-hub/proc-shared-filesystem.adoc
  downstream/modules/automation-hub/proc-upload-collection.adoc
  downstream/modules/automation-hub/proc-using-content-signing-services-in-pah.adoc
  downstream/modules/automation-hub/ref-permissions.adoc
Labels: 2.3

#1180 Replace plain text with attributes for content in the automation-hub …
  downstream/modules/automation-hub/con-about-automation-hub.adoc
  downstream/modules/automation-hub/con-ansible-galaxy-client.adoc
  downstream/modules/automation-hub/con-collections.adoc
  downstream/modules/automation-hub/con-user-access.adoc
  downstream/modules/automation-hub/proc-configure-automation-hub-server-cli.adoc
  downstream/modules/automation-hub/proc-configure-automation-hub-server-gui.adoc
  downstream/modules/automation-hub/proc-configure-content-signing-on-pah.adoc
  downstream/modules/automation-hub/proc-create-super-users.adoc
  downstream/modules/automation-hub/proc-create-users.adoc
  downstream/modules/automation-hub/proc-set-community-remote.adoc
  downstream/modules/automation-hub/proc-upload-collection.adoc
  downstream/modules/automation-hub/proc-using-content-signing-services-in-pah.adoc
  downstream/modules/automation-hub/ref-permissions.adoc
Labels: 2.2

#1181 Replacing variables
  downstream/assemblies/hub/assembly_ppah-installation.adoc
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/hub/proc-sync-image.adoc
  downstream/modules/hub/proc_ppah-download-aap.adoc
  downstream/modules/hub/proc_ppah-install-ansible-core.adoc
  downstream/modules/hub/proc_ppah-install-dev.adoc
  downstream/modules/hub/proc_ppah-install-ha.adoc
  downstream/modules/hub/proc_ppah-online-offline-install.adoc
  downstream/modules/hub/proc_ppah-prepare-rhel-host.adoc
  downstream/modules/hub/ref_ppah-access.adoc
  downstream/modules/hub/ref_ppah-config.adoc
  downstream/modules/platform/con-aap-example-architecture.adoc
  downstream/modules/platform/con-persisting-data-from-auto-runs.adoc
  downstream/modules/platform/con-single-eda-controller-with-internal-database.adoc
  downstream/modules/platform/proc-downloading-containerized-aap.adoc
  downstream/modules/platform/proc-install-ansible-colls.adoc
  downstream/modules/platform/proc-installing-ansible-core.adoc
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc
  downstream/modules/platform/proc-uninstalling-containerized-aap.adoc
  downstream/modules/platform/proc-update-ee-image-locations.adoc
  downstream/modules/platform/proc-using-postinstall.adoc
  downstream/modules/platform/ref-aap-containerized-dns-config.adoc
  downstream/modules/platform/ref-accessing-control-auto-hub-eda-control.adoc
  downstream/modules/platform/ref-ldap-config-on-pah.adoc
Labels: Needs backport to 2.4, Needs backport to 2.3, Needs backport to 2.2, Needs backport to 2.1

#1182 Replacing variables (#1181)
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/hub/proc-sync-image.adoc
  downstream/modules/platform/con-aap-example-architecture.adoc
  downstream/modules/platform/con-persisting-data-from-auto-runs.adoc
  downstream/modules/platform/con-single-eda-controller-with-internal-database.adoc
  downstream/modules/platform/proc-downloading-containerized-aap.adoc
  downstream/modules/platform/proc-install-ansible-colls.adoc
  downstream/modules/platform/proc-installing-ansible-core.adoc
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc
  downstream/modules/platform/proc-uninstalling-containerized-aap.adoc
  downstream/modules/platform/proc-update-ee-image-locations.adoc
  downstream/modules/platform/proc-using-postinstall.adoc
  downstream/modules/platform/ref-aap-containerized-dns-config.adoc
  downstream/modules/platform/ref-accessing-control-auto-hub-eda-control.adoc
  downstream/modules/platform/ref-ldap-config-on-pah.adoc
Labels: 2.4

#1183 rename :_content-type: variable
  downstream/modules/automation-hub/proc-sync-image.adoc
  downstream/modules/platform/con-aap-example-architecture.adoc
  downstream/modules/platform/proc-update-ee-image-locations.adoc
  downstream/modules/platform/proc_configuring-tls-with-aap-operator.adoc
  downstream/modules/platform/ref-ldap-config-on-pah.adoc
Labels: 2.3

#1185 Replace plain text with attributes for content in the navigator module
  downstream/modules/navigator/con-navigator-collections.adoc
  downstream/modules/navigator/proc-browse-collections-tui.adoc
  downstream/modules/navigator/proc-installing-navigator-rhel-pip.adoc
  downstream/modules/navigator/proc-installing-navigator-rhel-rpm.adoc
  downstream/modules/navigator/proc-installing-navigator-rhel-tar.adoc
  downstream/modules/navigator/proc-review-docs-tui.adoc
  downstream/modules/navigator/proc-review-ee-tui.adoc
  downstream/modules/navigator/ref-faq-navigator.adoc
  downstream/modules/navigator/ref-navigator-command-summary.adoc
Labels: 2.3

#1186 Replace plain text with attributes for content in the navigator modul…
  downstream/modules/navigator/con-navigator-collections.adoc
  downstream/modules/navigator/proc-browse-collections-tui.adoc
  downstream/modules/navigator/proc-installing-navigator-rhel-pip.adoc
  downstream/modules/navigator/proc-installing-navigator-rhel-rpm.adoc
  downstream/modules/navigator/proc-installing-navigator-rhel-tar.adoc
  downstream/modules/navigator/proc-review-docs-tui.adoc
  downstream/modules/navigator/proc-review-ee-tui.adoc
  downstream/modules/navigator/ref-faq-navigator.adoc
  downstream/modules/navigator/ref-navigator-command-summary.adoc
Labels: 2.2

#1187 AAP-22221 fixed formatting issues
  downstream/assemblies/analytics/assembly-automation-savings-planner.adoc
  downstream/modules/analytics/con-automation-savings-plan.adoc
  downstream/titles/analytics/automation-savings-planner/master.adoc
Labels: Ready for review, 2.2, 2.3, 2.4

#1189 AAP-22221 fixed formatting issues (#1187)
  downstream/assemblies/analytics/assembly-automation-savings-planner.adoc
  downstream/modules/analytics/con-automation-savings-plan.adoc
  downstream/titles/analytics/automation-savings-planner/master.adoc
Labels: Ready for review, 2.3

#1190 AAP-22221 fixed formatting issues (#1187)
  downstream/assemblies/analytics/assembly-automation-savings-planner.adoc
  downstream/modules/analytics/con-automation-savings-plan.adoc
  downstream/titles/analytics/automation-savings-planner/master.adoc
Labels: Ready for review, 2.2

#1191 AAP-22221 fixed formatting issues (#1187)
  downstream/assemblies/analytics/assembly-automation-savings-planner.adoc
  downstream/modules/analytics/con-automation-savings-plan.adoc
  downstream/titles/analytics/automation-savings-planner/master.adoc
Labels: Ready for review, 2.4
