Repository ansible/aap-docs, pull requests merged in 2024-12, with the labels that each got.

#2647 Removed incorrect statement
  downstream/modules/platform/proc-completing-post-installation-tasks.adoc
Labels: 2.4

#2648 Add async rns for async 2.5-5
  downstream/titles/release-notes/async/aap-25-4-18-nov.adoc
  downstream/titles/release-notes/async/aap-25-5-4-dec.adoc
  downstream/titles/release-notes/master.adoc
Labels: AAP Release notes, 2.5, Needs backport to 2.5

#2650 2.5 Add async rns for async 2.5-5 (#2648)
  downstream/titles/release-notes/async/aap-25-4-18-nov.adoc
  downstream/titles/release-notes/async/aap-25-5-4-dec.adoc
  downstream/titles/release-notes/master.adoc
Labels: AAP Release notes, 2.5

#2652 2.4 Update async release notes
  downstream/titles/release-notes/master.adoc
  downstream/titles/release-notes/topics/async-24-26-3-dec.adoc
Labels: AAP Release notes, 2.4

#2651 Update 2.5-5 async release notes
  downstream/titles/release-notes/async/aap-25-5-3-dec.adoc
  downstream/titles/release-notes/master.adoc
Labels: AAP Release notes, 2.5, Needs backport to 2.5

#2653 2.5 Update 2.5-5 async release notes (#2651)
  downstream/titles/release-notes/async/aap-25-5-3-dec.adoc
  downstream/titles/release-notes/master.adoc
Labels: AAP Release notes, 2.5

#2620 Updates subscription info for Satellite users in managing automation content guide
  downstream/assemblies/hub/assembly-populate-container-registry.adoc
Labels: 2.5

#2654 Backport to 2.5: Updates subscription info for Satellite users in managing automation content guide
  downstream/assemblies/hub/assembly-populate-container-registry.adoc
Labels: 2.5

#2655 AAP-36921: Added info. about receptor_datadir variable
  downstream/modules/platform/ref-receptor-inventory-variables.adoc
Labels: Ready for review, Technical review complete, Needs backport to 2.5

#2656 AAP-36921-update: Added info. about receptor_datadir variable
  downstream/modules/platform/ref-receptor-inventory-variables.adoc
Labels: 2.5, Needs backport to 2.5

#2658 Corrected formatting error
  downstream/assemblies/platform/assembly-controller-logging-aggregation.adoc
Labels: Needs backport to 2.4, 2.4, 2.5, Needs backport to 2.5

#2659 Corrected formatting error (#2658)
  downstream/assemblies/platform/assembly-controller-logging-aggregation.adoc
Labels: 2.5, Backported to 2.5

#2660 Corrected formatting error (#2658)
  downstream/assemblies/platform/assembly-controller-logging-aggregation.adoc
Labels: Backported to 2.4, 2.4

#2662 Backport PR #2656 from main to 2.5.
  downstream/modules/platform/ref-receptor-inventory-variables.adoc
Labels: Ready for review, Backported to 2.5

#2664 AAP-36921-2.4: Added info. about receptor variables
  downstream/modules/platform/ref-controller-variables.adoc
Labels: Ready for review, 2.4

#2661 Editing curl command
  downstream/modules/platform/proc-controller-enable-provision-callbacks.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4, 2.5, Needs backport to 2.5

#2665 Editing curl command (#2661)
  downstream/modules/platform/proc-controller-enable-provision-callbacks.adoc
Labels: documentation, Controller, 2.5, Backported to 2.5

#2666 Editing curl command (#2661)
  downstream/modules/platform/proc-controller-enable-provision-callbacks.adoc
Labels: documentation, Backported to 2.4, Controller, 2.4

#2667 Add hub_seed_collections to inventory vars appendix
  downstream/modules/platform/ref-hub-variables.adoc
Labels: 2.5, Needs backport to 2.5

#2668 2.5 Add hub_seed_collections to inventory vars appendix (#2667)
  downstream/modules/platform/ref-hub-variables.adoc
Labels: 2.5

#2663 AAP-36614 Apply updates for EDA max activations and correct link to OCP appendix
  downstream/modules/eda/proc-modifying-activations-after-install.adoc
  downstream/modules/platform/con-operator-custom-resources.adoc
Labels: documentation, Ready for review, Technical review complete, 2.5, Needs backport to 2.5

#2671 AAP-15176: fixes broken links from nov broken links report
  downstream/modules/aap-hardening/con-logging-log-capture.adoc
  downstream/modules/platform/proc-gs-use-base-execution-env.adoc
Labels: AAP Hardening, 2.5, Needs backport to 2.5

#2673 AAP-37105: fixes incorrect link in the RPM Install guide
  downstream/modules/platform/con-adding-subscription-manifest.adoc
Labels: 2.5, Needs backport to 2.5

#2674 Backport to 2.5: AAP-37105: fixes incorrect link (#2673)
  downstream/modules/platform/con-adding-subscription-manifest.adoc
Labels: 2.5

#2669 Adding edits from AAP-35971
  downstream/modules/topologies/ref-ocp-a-env-a.adoc
  downstream/modules/topologies/ref-ocp-b-env-a.adoc
Labels: documentation, 2.5, AAP operator

#2676 adding edits from AAP-35971 (#2669)
  downstream/modules/topologies/ref-ocp-a-env-a.adoc
  downstream/modules/topologies/ref-ocp-b-env-a.adoc
Labels: documentation, 2.5, AAP operator

#2675 AAP-37117 adding a proc on decoding the base64 password
  downstream/modules/platform/proc-cli-get-controller-pwd.adoc
Labels: documentation, 2.5, AAP operator, Needs backport to 2.5

#2677 AAP-37117 adding a proc on decoding the base64 password (#2675)
  downstream/modules/platform/proc-cli-get-controller-pwd.adoc
Labels: 2.5, AAP operator

#2680 Removing 20 node limit from 2.4 doc
  downstream/modules/platform/ref-controller-setup-considerations.adoc
Labels: documentation, Backported to 2.4, Controller, 2.4

#2679 Add more context to containerized uninstall
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/platform/proc-reinstalling-containerized-aap.adoc
  downstream/modules/platform/proc-uninstalling-containerized-aap.adoc
  downstream/modules/platform/ref-controller-variables.adoc
  downstream/modules/platform/ref-eda-controller-variables.adoc
  downstream/modules/platform/ref-gateway-variables.adoc
  downstream/modules/platform/ref-hub-variables.adoc
Labels: 2.5, Needs backport to 2.5

#2681 2.5 Add more context to containerized uninstall (#2679)
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/platform/proc-reinstalling-containerized-aap.adoc
  downstream/modules/platform/proc-uninstalling-containerized-aap.adoc
  downstream/modules/platform/ref-controller-variables.adoc
  downstream/modules/platform/ref-eda-controller-variables.adoc
  downstream/modules/platform/ref-gateway-variables.adoc
  downstream/modules/platform/ref-hub-variables.adoc
Labels: 2.5

#2683 Update inventory file examples
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/topologies/ref-cont-a-env-a.adoc
  downstream/modules/topologies/ref-cont-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-b.adoc
  downstream/modules/topologies/ref-rpm-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-b.adoc
Labels: 2.5, Needs backport to 2.5

#2684 2.5 Update inventory file examples (#2683)
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/topologies/ref-cont-a-env-a.adoc
  downstream/modules/topologies/ref-cont-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-b.adoc
  downstream/modules/topologies/ref-rpm-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-b.adoc
Labels: 2.5

#2687 AAP-36934 added note on external databases (#2685)
  downstream/modules/platform/ref-guidelines-hosts-groups.adoc
Labels: Ready for review, 2.5

#2688 AAP-36937: Added info. external database and variable behavior
  downstream/modules/platform/proc-setup-postgresql-ext-database.adoc
  downstream/modules/platform/ref-database-inventory-variables.adoc
Labels: Ready for review, Technical review complete, 2.5, Needs backport to 2.5

#2689 Backport pull request #2688 from main to 2.5
  downstream/modules/platform/proc-setup-postgresql-ext-database.adoc
  downstream/modules/platform/ref-database-inventory-variables.adoc
Labels: Ready for review, 2.5, Backported to 2.5

#2690 Fix error in Lightspeed RN
  lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-11dec2024.adoc
Labels: Lightspeed

#2682 AAP-36858: updates subscription info in managing automation content guide
  downstream/assemblies/hub/assembly-populate-container-registry.adoc
  downstream/modules/hub/proc-obtain-images.adoc
Labels: Automation Hub, 2.5

#2695 AAP-37559a Update version for Ansible Inside 1.3
  ansible-inside/stories/asssembly-ansible-inside-install-intro.adoc
  ansible-inside/titles/reporting-guide/docinfo.xml
  ansible-inside/topics/proc-ansible-inside-install-registry.adoc
Labels: Ansible Inside

#2694 backport to 2.5: AAP-36858: updates subscription info in managing automation content guide
  downstream/assemblies/hub/assembly-populate-container-registry.adoc
  downstream/modules/hub/proc-obtain-images.adoc
Labels: 2.5

#2697 backport to 2.4: AAP-36858: updates subscription info in managing automation content guide
  downstream/assemblies/hub/assembly-populate-container-registry.adoc
  downstream/modules/hub/proc-obtain-images.adoc
Labels: 2.4

#2698 AAP-36858: removes satellite link from section on pulling EEs
  downstream/modules/hub/proc-obtain-images.adoc
Labels: 2.5

#2699 backport to 2.5: AAP-36858 removes satellite link from section on pulling EEs (#2698)
  downstream/modules/hub/proc-obtain-images.adoc
Labels: 2.5

#2692 Fixing errors in inventory plugin sections
  downstream/modules/platform/proc-controller-inv-source-aap.adoc
  downstream/modules/platform/proc-controller-inv-source-insights.adoc
  downstream/modules/platform/proc-controller-inv-source-openstack.adoc
  downstream/modules/platform/proc-controller-inv-source-rh-virt.adoc
Labels: documentation, Controller, 2.4

#2693 Update inventory file variable
  downstream/modules/platform/ref-gateway-controller-ext-db.adoc
  downstream/modules/platform/ref-gateway-controller-hub-eda-ext-db.adoc
  downstream/modules/platform/ref-gateway-controller-hub-ext-db.adoc
  downstream/modules/platform/ref-general-inventory-variables.adoc
Labels: 2.5, Needs backport to 2.5

#2701 Adding later versions to chapter 4.1 of OCP perf guide
  downstream/modules/platform/proc-configure-controller-OCP.adoc
Labels: documentation, 2.5, AAP operator, Needs backport to 2.5

#2702 Update inventory file variable (#2693)
  downstream/modules/platform/ref-gateway-controller-ext-db.adoc
  downstream/modules/platform/ref-gateway-controller-hub-eda-ext-db.adoc
  downstream/modules/platform/ref-gateway-controller-hub-ext-db.adoc
  downstream/modules/platform/ref-general-inventory-variables.adoc
Labels: 2.5, Backported to 2.5

#2703 Adding later versions to chapter 4.1 of OCP perf guide (#2701)
  downstream/modules/platform/proc-configure-controller-OCP.adoc
Labels: 2.5, AAP operator

#2704 Add IBM support link to Tested deployment models
  downstream/assemblies/topologies/assembly-appendix-topology-resources.adoc
  downstream/titles/topologies/master.adoc
Labels: 2.5, Needs backport to 2.5

#2705 2.5 Add IBM support link to Tested deployment models (#2704)
  downstream/assemblies/topologies/assembly-appendix-topology-resources.adoc
  downstream/titles/topologies/master.adoc
Labels: 2.5, Backported to 2.5

#2711 AAP-33505 - Add clarifying note for SAML IDP extra_data details
  downstream/modules/platform/proc-controller-set-up-SAML.adoc
Labels: Ready for technical review, Not ready for peer review, 2.5, Needs backport to 2.5

#2716 [Backport] AAP-33505 - Add clarifying note for SAML IDP extra_data details (#2711)
  downstream/modules/platform/proc-controller-set-up-SAML.adoc
Labels: Ready for review, 2.5

#2717 AAP-35016 - Update Satellite version and minor formatting fix
  downstream/modules/platform/proc-aap-activate-with-credentials.adoc
  downstream/modules/platform/proc-aap-activate-with-manifest.adoc
  downstream/modules/platform/proc-aap-create-subscription-allocation.adoc
Labels: Ready for review, 2.5, Backported to 2.5, Needs backport to 2.5

#2718 [Backport] AAP-35016 - Update Satellite version and minor formatting fix (#2717)
  downstream/modules/platform/proc-aap-activate-with-credentials.adoc
  downstream/modules/platform/proc-aap-activate-with-manifest.adoc
  downstream/modules/platform/proc-aap-create-subscription-allocation.adoc
Labels: Ready for review, 2.5

#2719 Replaced satellite version number with the defined attribute
  downstream/modules/platform/proc-aap-create-subscription-allocation.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#2720 [Backport] Replaced satellite version number with the defined attribute (#2719)
  downstream/modules/platform/proc-aap-create-subscription-allocation.adoc
Labels: Ready for review, 2.5

#2722 2.5 Correct typo in link Backing up container-based Ansible Automation Pl…
  downstream/modules/platform/proc-backup-aap-container.adoc
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc
  downstream/modules/platform/proc-reinstalling-containerized-aap.adoc
  downstream/modules/platform/proc-uninstalling-containerized-aap.adoc
  downstream/modules/platform/proc-update-aap-container.adoc
Labels: 2.5, Backported to 2.5

#2723 AAP-37637 Deprovisioning edits
  stories/topics/con-saas-deployment-self-service.adoc
Labels: documentation, AAP on clouds, SaaS on AWS

#2724 Correcting credentials link in user guide
  downstream/modules/platform/proc-controller-azure-resource-manager.adoc
  downstream/modules/platform/proc-controller-inv-source-gce.adoc
Labels: documentation, Controller, 2.5, Needs backport to 2.5

#2725 Correcting credentials link in user guide (#2724)
  downstream/modules/platform/proc-controller-azure-resource-manager.adoc
  downstream/modules/platform/proc-controller-inv-source-gce.adoc
Labels: documentation, Controller, 2.5, Backported to 2.5

#2728 Add warning snippet about content syncing known issue
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/topologies/ref-cont-a-env-a.adoc
  downstream/modules/topologies/snippets
  downstream/snippets/known-issue-container-content-syncing.adoc
  downstream/titles/release-notes/topics/aap-25-known-issues.adoc
Labels: 2.5, Needs backport to 2.5

#2729 2.5 Add warning snippet about content syncing known issue (#2728)
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/topologies/ref-cont-a-env-a.adoc
  downstream/modules/topologies/snippets
  downstream/snippets/known-issue-container-content-syncing.adoc
  downstream/titles/release-notes/topics/aap-25-known-issues.adoc
Labels: 2.5, Backported to 2.5

#2731 Add comment in attributes for aap-on-gcp deprecation
  downstream/attributes/attributes.adoc
Labels: 2.5, Needs backport to 2.5

#2733 2.4 Add comment in attributes for aap-on-gcp deprecation (#2731)
  downstream/attributes/attributes.adoc
Labels: 2.4

#2734 DOCS-1791: Removes link to getting started guide in gateway snippet
  downstream/snippets/snip-gateway-component-description.adoc
Labels: snippets, 2.5
