Repository ansible/aap-docs, pull requests merged in 2024-02, with the labels that each got.

#981 Create Playbooks GS guide
  downstream/assemblies/playbooks/assembly-intro-to-playbooks.adoc
  downstream/assemblies/playbooks/assembly-networking-playbook.adoc
  downstream/assemblies/playbooks/assembly-playbook-gs.adoc
  downstream/assemblies/playbooks/assembly-playbook-practical-example.adoc
  downstream/assemblies/playbooks/playbooks
  downstream/attributes/attributes.adoc
  downstream/images/playbook.png
  downstream/modules/playbooks/proc-build-an-inventory.adoc
  downstream/modules/playbooks/proc-creating-a-playbook.adoc
  downstream/modules/playbooks/proc-run-ansible-network-playbook.adoc
  downstream/modules/playbooks/proc-starting-automation.adoc
  downstream/modules/playbooks/ref-create-variables.adoc
  downstream/modules/playbooks/ref-gathering-facts.adoc
  downstream/modules/playbooks/ref-how-do-playbooks-work.adoc
  downstream/modules/playbooks/ref-how-to-use-ansible-playbooks.adoc
  downstream/modules/playbooks/ref-playbook-execution.adoc
  downstream/modules/playbooks/ref-run-network-command.adoc
  downstream/modules/playbooks/ref-use-meta-groups.adoc
  downstream/titles/playbooks/playbooks-getting-started/aap-common
  downstream/titles/playbooks/playbooks-getting-started/assemblies
  downstream/titles/playbooks/playbooks-getting-started/docinfo.xml
  downstream/titles/playbooks/playbooks-getting-started/master.adoc
  downstream/titles/playbooks/playbooks-getting-started/modules
Labels: documentation, Needs backport to 2.4, 2.4

#959 Consolidated inventory file examples
  downstream/assemblies/platform/assembly-migrate-platform.adoc
  downstream/assemblies/platform/assembly-platform-install-overview.adoc
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
  downstream/assemblies/platform/assembly-platform-whats-next.adoc
  downstream/modules/platform/con-install-scenario-examples.adoc
  downstream/modules/platform/con-install-scenario-recommendations.adoc
  downstream/modules/platform/con-why-automation-mesh.adoc
  downstream/modules/platform/con-why-migrate-ansible-29.adoc
  downstream/modules/platform/con-why-migrate-ansible-core-213.adoc
  downstream/modules/platform/con-why-migrate-venvs-ee.adoc
  downstream/modules/platform/proc-configure-pulpcore-service.adoc
  downstream/modules/platform/proc-editing-inventory-file.adoc
  downstream/modules/platform/proc-update-ee-image-locations.adoc
  downstream/modules/platform/ref-connect-hub-to-rhsso.adoc
  downstream/modules/platform/ref-eda-controller-variables.adoc
  downstream/modules/platform/ref-single-controller-ext-customer-managed-db.adoc
  downstream/modules/platform/ref-single-controller-ext-installer-managed-db.adoc
  downstream/modules/platform/ref-single-controller-hub-eda-with-managed-db.adoc
  downstream/modules/platform/ref-standalone-controller-hub-ext-database-inventory.adoc
  downstream/modules/platform/ref-standalone-hub-inventory.adoc
  downstream/titles/aap-operations-guide/master.adoc
Labels: Needs backport to 2.4, Ready for technical review, 2.4

#990 Consolidated inventory file examples (#959)
  downstream/assemblies/platform/assembly-migrate-platform.adoc
  downstream/assemblies/platform/assembly-platform-install-overview.adoc
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
  downstream/assemblies/platform/assembly-platform-whats-next.adoc
  downstream/modules/platform/con-install-scenario-examples.adoc
  downstream/modules/platform/con-install-scenario-recommendations.adoc
  downstream/modules/platform/con-why-automation-mesh.adoc
  downstream/modules/platform/con-why-migrate-ansible-29.adoc
  downstream/modules/platform/con-why-migrate-ansible-core-213.adoc
  downstream/modules/platform/con-why-migrate-venvs-ee.adoc
  downstream/modules/platform/proc-configure-pulpcore-service.adoc
  downstream/modules/platform/proc-editing-inventory-file.adoc
  downstream/modules/platform/proc-update-ee-image-locations.adoc
  downstream/modules/platform/ref-connect-hub-to-rhsso.adoc
  downstream/modules/platform/ref-eda-controller-variables.adoc
  downstream/modules/platform/ref-single-controller-ext-customer-managed-db.adoc
  downstream/modules/platform/ref-single-controller-ext-installer-managed-db.adoc
  downstream/modules/platform/ref-single-controller-hub-eda-with-managed-db.adoc
  downstream/modules/platform/ref-standalone-controller-hub-ext-database-inventory.adoc
  downstream/modules/platform/ref-standalone-hub-inventory.adoc
  downstream/titles/aap-operations-guide/master.adoc
Labels: documentation, Backported to 2.4, 2.4

#989 AAP-10252: add note to remind user not to leave fields blank
  downstream/modules/platform/proc-configure-ldap-hub-ocp.adoc
Labels: 2.3, Needs backport to 2.4, Needs backport to 2.3, Not ready for peer review, 2.4, Main

#991 Backport to 2.4: AAP-10252 add note to remind user not to leave fields blank (#989)
  downstream/modules/platform/proc-configure-ldap-hub-ocp.adoc
Labels: 2.4

#992 Backport to 2.3: AAP-10252 add note to remind user not to leave fields blank (#989)
  downstream/modules/platform/proc-configure-ldap-hub-ocp.adoc
Labels: 2.3

#980 AAP-17700: Further updates to Builder documentation
  downstream/modules/builder/con-additional-build-files.adoc
  downstream/modules/builder/con-building-definition-file.adoc
  downstream/modules/builder/ref-scenario-using-authentication-ee.adoc
Labels: 2.4, Main

#994 Backport to 2.4: AAP-17700 Further updates to Builder documentation (#980)
  downstream/modules/builder/con-additional-build-files.adoc
  downstream/modules/builder/con-building-definition-file.adoc
  downstream/modules/builder/ref-scenario-using-authentication-ee.adoc
Labels: 2.4

#995 Correct mesh examples
  downstream/modules/platform/ref-mesh-minimum-resilient-config.adoc
  downstream/modules/platform/ref-mesh-segregated-execution_nodes.adoc
Labels: documentation, Needs backport to 2.4, 2.4

#996 Correct mesh examples (#995)
  downstream/modules/platform/ref-mesh-minimum-resilient-config.adoc
  downstream/modules/platform/ref-mesh-segregated-execution_nodes.adoc
Labels: documentation, Backported to 2.4, 2.4

#997 Add bundle installer 2.4-4 to release notes
  downstream/titles/release-notes/master.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-4.adoc
Labels: Ready for review, Needs backport to 2.4, AAP Release notes

#998 Add bundle installer 2.4-4 to release notes (#997)
  downstream/titles/release-notes/master.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-4.adoc
Labels: AAP Release notes, 2.4

#999 Update bundle installer 2.4-4 release notes based on SME feedback
  downstream/titles/release-notes/topics/bundle-installer-24-4.adoc
Labels: Ready for review, Needs backport to 2.4, AAP Release notes

#1000 Update bundle installer 2.4-4 release notes based on SME feedback (#999)
  downstream/titles/release-notes/topics/bundle-installer-24-4.adoc
Labels: AAP Release notes, 2.4

#1001 Changed information on Hashicorp Vault
  downstream/images/credentials-create-hashicorp-kv-credential.png
  downstream/images/credentials-create-hashicorp-ssh-credential.png
  downstream/images/credentials-machine-test-hashicorp-metadata.png
  downstream/modules/platform/ref-hashicorp-signed-ssh.adoc
  downstream/modules/platform/ref-hashicorp-vault-lookup.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#1004 Changed information on Hashicorp Vault (#1001)
  downstream/images/credentials-create-hashicorp-kv-credential.png
  downstream/images/credentials-create-hashicorp-ssh-credential.png
  downstream/images/credentials-machine-test-hashicorp-metadata.png
  downstream/modules/platform/ref-hashicorp-signed-ssh.adoc
  downstream/modules/platform/ref-hashicorp-vault-lookup.adoc
Labels: documentation, Backported to 2.4, Controller, 2.4

#1005 Set up files for Playbooks reference guide
  downstream/assemblies/playbooks/assembly-reference-test.adoc
  downstream/titles/playbooks/playbooks-reference/aap-common
  downstream/titles/playbooks/playbooks-reference/attributes
  downstream/titles/playbooks/playbooks-reference/docinfo.xml
  downstream/titles/playbooks/playbooks-reference/images
  downstream/titles/playbooks/playbooks-reference/master.adoc
  downstream/titles/playbooks/playbooks-reference/playbooks
Labels: documentation, Needs backport to 2.4, 2.4

#1006 Set up files for Playbooks reference guide (#1005)
  downstream/assemblies/playbooks/assembly-reference-test.adoc
  downstream/titles/playbooks/playbooks-reference/aap-common
  downstream/titles/playbooks/playbooks-reference/attributes
  downstream/titles/playbooks/playbooks-reference/docinfo.xml
  downstream/titles/playbooks/playbooks-reference/images
  downstream/titles/playbooks/playbooks-reference/master.adoc
  downstream/titles/playbooks/playbooks-reference/playbooks
Labels: documentation, Backported to 2.4, 2.4

#1002 Add bundle installer 2.4-5 to release notes
  downstream/titles/release-notes/master.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-11.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-12.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-13.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-14.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-2.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-21.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-22.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-23.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-24.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-3.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-4.adoc
  downstream/titles/release-notes/topics/eda-24.adoc
  downstream/titles/release-notes/topics/installer-24-2.adoc
  downstream/titles/release-notes/topics/installer-24-3.adoc
  downstream/titles/release-notes/topics/installer-24-4.adoc
  downstream/titles/release-notes/topics/installer-24-5.adoc
Labels: Ready for review, Needs backport to 2.4, AAP Release notes

#960 AAP-17292: Developed docs for Configuring custom models feature
  lightspeed/assemblies/assembly_configuring-custom-models.adoc
  lightspeed/assemblies/assembly_configuring-vscode-extension.adoc
  lightspeed/attributes/attributes.adoc
  lightspeed/modules/con_ansible-content-parser.adoc 
  lightspeed/modules/con_training-data.adoc
  lightspeed/modules/proc_configure-custom-models-lightspeed.adoc 
  lightspeed/modules/proc_configure-vscode-extension.adoc
  lightspeed/modules/proc_create-deploy-custom-model-ibm.adoc 
  lightspeed/modules/proc_generate-training-data-set.adoc 
  lightspeed/modules/proc_install-content-parser.adoc 
  lightspeed/modules/proc_merge-multiple-jsonl-files.adoc 
  lightspeed/modules/proc_provide-feedback.adoc
  lightspeed/modules/proc_resolve-ansible-lint-rule-violations.adoc 
  lightspeed/modules/proc_view-content-parser-output.adoc 
  lightspeed/titles/lightspeed-user-guide/master.adoc
Labels: Lightspeed

#1007 AAP-19173: correct formatting errors in Configuring Central Authentication Generic OICD
  downstream/modules/central-auth/proc-configure-central-auth-generic-oidc-settings.adoc
Labels: Needs backport to 2.4, 2.4, Main

#1010 BP to 2.4: AAP-19173 correct formatting errors (#1007)
  downstream/modules/central-auth/proc-configure-central-auth-generic-oidc-settings.adoc
Labels: Backported to 2.4, 2.4

#1012 AAP-19173: change "click on" to "click" per style guidelines
  downstream/modules/central-auth/proc-configure-central-auth-generic-oidc-settings.adoc
Labels: Backported to 2.4, 2.4

#1011 AAP-20739 Modify xrefs and include statements
  lightspeed/assemblies/assembly_configuring-custom-models.adoc
  lightspeed/assemblies/assembly_configuring-vscode-extension.adoc
  lightspeed/modules/con_ansible-content-parser.adoc
  lightspeed/modules/con_training-data.adoc
  lightspeed/modules/proc_configure-custom-models-lightspeed.adoc
  lightspeed/modules/proc_create-deploy-custom-model-ibm.adoc
  lightspeed/modules/proc_generate-training-data-set.adoc
  lightspeed/modules/proc_install-content-parser.adoc
  lightspeed/modules/proc_merge-multiple-jsonl-files.adoc
  lightspeed/modules/proc_resolve-ansible-lint-rule-violations.adoc
  lightspeed/modules/proc_view-content-parser-output.adoc
Labels: Lightspeed

#1013 AAP-20603: Updated content per consumption-based pricing changes
  lightspeed/assemblies/assembly_logging-in-out-portal.adoc
  lightspeed/assemblies/assembly_using-code-bot-for-suggestions.adoc
  lightspeed/modules/con-lightspeed-about.adoc
  lightspeed/modules/con_lightspeed-key-features.adoc
  lightspeed/modules/con_lightspeed-process.adoc
  lightspeed/modules/con_training-data.adoc
  lightspeed/modules/proc_configure-custom-models-lightspeed.adoc
  lightspeed/modules/proc_configure-vscode-extension.adoc
  lightspeed/modules/proc_install-code-bot.adoc
  lightspeed/modules/proc_log-in-administrator-portal.adoc
  lightspeed/modules/proc_log-into-portal.adoc
  lightspeed/modules/proc_log-out-of-portal.adoc
  lightspeed/modules/proc_multi-task-recs.adoc
  lightspeed/modules/proc_obtain-config-wca-and-model-id.adoc
  lightspeed/modules/proc_provide-feedback.adoc
  lightspeed/modules/proc_single-task-recs.adoc
  lightspeed/modules/proc_troubleshooting-lightspeed-config.adoc
  lightspeed/modules/proc_troubleshooting-vscode.adoc
  lightspeed/titles/lightspeed-release-notes/master.adoc
  lightspeed/titles/lightspeed-release-notes/modules/lightspeed-intro.adoc
  lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-15feb2024.adoc
  lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-25oct2023.adoc
  lightspeed/titles/lightspeed-user-guide/master.adoc
Labels: Lightspeed

#1015 AAP-18798 Added a note with link to article re: adding cgroup V2 enabled
  downstream/assemblies/eda/assembly-installation-eda-controller.adoc
  downstream/modules/platform/ref-eda-system-requirements.adoc
Labels: Ready for review, Needs backport to 2.4, Technical review complete, 2.4

#1020 adding proc-enable-hstore-extension.adoc to assembly
  downstream/assemblies/platform/assembly-installing-hub-operator.adoc
Labels: documentation, Needs backport to 2.4

#1023 adding proc-enable-hstore-extension.adoc to assembly (#1020)
  downstream/assemblies/platform/assembly-installing-hub-operator.adoc
Labels: documentation, Backported to 2.4

#1022 Backport-2.4-1015 Added a note with link to article re: adding cgroup V2 enabled (#1015)
  downstream/assemblies/eda/assembly-installation-eda-controller.adoc
  downstream/modules/platform/ref-eda-system-requirements.adoc
Labels: Ready for review

#1021 Corrections in Controller GS guide
  downstream/assemblies/platform/assembly-controller-credentials.adoc
  downstream/assemblies/platform/assembly-controller-dashboard.adoc
  downstream/assemblies/platform/assembly-controller-inventories.adoc
  downstream/assemblies/platform/assembly-controller-job-templates.adoc
  downstream/modules/platform/con-controller-keep-subscription-in-compliance.adoc
  downstream/modules/platform/proc-controller-add-groups-hosts.adoc
  downstream/modules/platform/proc-controller-create-credential.adoc
  downstream/modules/platform/proc-controller-create-inventory.adoc
  downstream/modules/platform/proc-controller-importing-subscriptions.adoc
  downstream/modules/platform/proc-controller-obtaining-subscriptions.adoc
  downstream/modules/platform/proc-controller-review-organizations.adoc
  downstream/modules/platform/proc-controller-run-job-template.adoc
  downstream/modules/platform/proc-controller-viewing-dashboard.adoc
  downstream/titles/controller/controller-getting-started/master.adoc
  downstream/titles/controller/controller-user-guide/master.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#1024 Corrections in Controller GS guide (#1021)
  downstream/assemblies/platform/assembly-controller-credentials.adoc
  downstream/assemblies/platform/assembly-controller-dashboard.adoc
  downstream/assemblies/platform/assembly-controller-inventories.adoc
  downstream/assemblies/platform/assembly-controller-job-templates.adoc
  downstream/modules/platform/con-controller-keep-subscription-in-compliance.adoc
  downstream/modules/platform/proc-controller-add-groups-hosts.adoc
  downstream/modules/platform/proc-controller-create-credential.adoc
  downstream/modules/platform/proc-controller-create-inventory.adoc
  downstream/modules/platform/proc-controller-importing-subscriptions.adoc
  downstream/modules/platform/proc-controller-obtaining-subscriptions.adoc
  downstream/modules/platform/proc-controller-review-organizations.adoc
  downstream/modules/platform/proc-controller-run-job-template.adoc
  downstream/modules/platform/proc-controller-viewing-dashboard.adoc
  downstream/titles/controller/controller-getting-started/master.adoc
  downstream/titles/controller/controller-user-guide/master.adoc
Labels: documentation, Backported to 2.4, Controller, 2.4

#1025 Removed statement on database support
  downstream/modules/platform/con-install-scenario-recommendations.adoc
Labels: documentation, Needs backport to 2.4, 2.4

#1026 Removed statement on database support (#1025)
  downstream/modules/platform/con-install-scenario-recommendations.adoc
Labels: Backported to 2.4, 2.4

#1028 Replace plain text with attribute for analytics module
  downstream/modules/analytics/proc-calculating-automation.adoc
Labels: Ready for review, Needs backport to 2.4

#1032 Update docs for workflow and job template limits
  downstream/assemblies/platform/assembly-ug-controller-job-templates.adoc
  downstream/assemblies/platform/assembly-ug-controller-workflow-job-templates.adoc
  downstream/modules/platform/proc-controller-create-job-template.adoc
  downstream/modules/platform/proc-controller-create-workflow-template.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#1034 Update docs for workflow and job template limits (#1032)
  downstream/assemblies/platform/assembly-ug-controller-job-templates.adoc
  downstream/assemblies/platform/assembly-ug-controller-workflow-job-templates.adoc
  downstream/modules/platform/proc-controller-create-job-template.adoc
  downstream/modules/platform/proc-controller-create-workflow-template.adoc
Labels: documentation, Backported to 2.4, Controller, 2.4

#1027 Removed duplicates and added missing lines
  downstream/modules/platform/ref-single-controller-hub-eda-with-managed-db.adoc
Labels: documentation, Needs backport to 2.4, Technical review complete, 2.4

#1035 Removed duplicates and added missing lines (#1027)
  downstream/modules/platform/ref-single-controller-hub-eda-with-managed-db.adoc
Labels: Backported to 2.4, 2.4

#1036 Replace plain text with attribute for content in the builder module
  downstream/modules/builder/con-about-ee.adoc
  downstream/modules/builder/con-ee-precedence.adoc
  downstream/modules/builder/proc-customize-ee-image.adoc
  downstream/modules/builder/ref-definition-file-images.adoc
Labels: Ready for review, Needs backport to 2.4

#1037 Replace plain text with attribute for content in the builder module (…
  downstream/modules/builder/con-about-ee.adoc
  downstream/modules/builder/con-ee-precedence.adoc
  downstream/modules/builder/proc-customize-ee-image.adoc
  downstream/modules/builder/ref-definition-file-images.adoc
Labels: 2.4

#1038 AAP-20823
  downstream/assemblies/platform/assembly-specify-dedicated-nodes.adoc
  downstream/modules/platform/con-alternative-capacity-limits.adoc
  downstream/modules/platform/con-pod-specification-mods.adoc
  downstream/modules/platform/proc-configure-controller-OCP.adoc
  downstream/modules/platform/proc-customizing-pod-specs.adoc
  downstream/modules/platform/proc-enable-pods-ref-images.adoc
  downstream/modules/platform/proc-set-custom-pod-timeout.adoc
  downstream/modules/platform/proc-specify-nodes-job-execution.adoc
  downstream/modules/platform/ref-assign-pods-to-nodes.adoc
  downstream/modules/platform/ref-container-resource-requirements.adoc
  downstream/modules/platform/ref-requests-limits.adoc
  downstream/modules/platform/ref-resource-management-pods-containers.adoc
  downstream/modules/platform/ref-resource-types.adoc
  downstream/modules/platform/ref-schedule-jobs-worker-nodes.adoc
  downstream/modules/platform/ref-set-requests-limits-for-containers.adoc
Labels: documentation, Ready for review, Needs backport to 2.4

#1039 AAP-20823 Editorial review on Considerations OCP doc (#1038)
  downstream/assemblies/platform/assembly-specify-dedicated-nodes.adoc
  downstream/modules/platform/con-alternative-capacity-limits.adoc
  downstream/modules/platform/con-pod-specification-mods.adoc
  downstream/modules/platform/proc-configure-controller-OCP.adoc
  downstream/modules/platform/proc-customizing-pod-specs.adoc
  downstream/modules/platform/proc-enable-pods-ref-images.adoc
  downstream/modules/platform/proc-set-custom-pod-timeout.adoc
  downstream/modules/platform/proc-specify-nodes-job-execution.adoc
  downstream/modules/platform/ref-assign-pods-to-nodes.adoc
  downstream/modules/platform/ref-container-resource-requirements.adoc
  downstream/modules/platform/ref-requests-limits.adoc
  downstream/modules/platform/ref-resource-management-pods-containers.adoc
  downstream/modules/platform/ref-resource-types.adoc
  downstream/modules/platform/ref-schedule-jobs-worker-nodes.adoc
  downstream/modules/platform/ref-set-requests-limits-for-containers.adoc
Labels: documentation, Backported to 2.4

#1040 remove-wca-prereq: Modified prereq for Ansible code bot
  lightspeed/assemblies/assembly_using-code-bot-for-suggestions.adoc
Labels: Lightspeed

#1041 Replace plain text with attributes for content in the core module
  downstream/modules/core/con-ansible-roles.adoc
  downstream/modules/core/con-content-collections.adoc
  downstream/modules/core/con-execution-environments.adoc
Labels: Ready for review, Needs backport to 2.4

#1042 Replace plain text with attributes for content in the core module (#1…
  downstream/modules/core/con-ansible-roles.adoc
  downstream/modules/core/con-content-collections.adoc
  downstream/modules/core/con-execution-environments.adoc
Labels: 2.4

#993 Renaming mesh guide
  downstream/assemblies/platform/assembly-planning-mesh.adoc
  downstream/modules/platform/con-about-automation-mesh.adoc
  downstream/modules/platform/con-automation-mesh-node-types.adoc
  downstream/modules/platform/proc-defining-node-types.adoc
  downstream/titles/automation-mesh/docinfo.xml
  downstream/titles/automation-mesh/master.adoc
Labels: Needs backport to 2.4, Title change, 2.4

#1043 Renaming mesh guide (#993)
  downstream/assemblies/platform/assembly-planning-mesh.adoc
  downstream/modules/platform/con-about-automation-mesh.adoc
  downstream/modules/platform/con-automation-mesh-node-types.adoc
  downstream/modules/platform/proc-defining-node-types.adoc
  downstream/titles/automation-mesh/docinfo.xml
  downstream/titles/automation-mesh/master.adoc
Labels: Backported to 2.4, Title change, 2.4

#1044 Replace plain text with attributes for content in the dev-guide module
  downstream/modules/dev-guide/proc-create-collections.adoc
  downstream/modules/dev-guide/proc-create-role.adoc
Labels: Ready for review, Needs backport to 2.4

#1045 Replace plain text with attributes for content in the dev-guide modul…
  downstream/modules/dev-guide/proc-create-collections.adoc
  downstream/modules/dev-guide/proc-create-role.adoc
Labels: 2.4

#1019 AAP-19025 add procedure for configuring proxy settings in automation hub
  downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc
  downstream/modules/hub/proc-configure-proxy-remote.adoc
  downstream/modules/hub/proc-set-community-remote.adoc
  downstream/modules/hub/proc-set-rhcertified-remote.adoc
Labels: documentation, Ready for review, Needs backport to 2.4, Technical review complete, Automation Hub, 2.4, Main

#1046 Add openssl commands to validate SSL certs
  downstream/modules/platform/proc-renew-ssl-cert.adoc
Labels: Ready for review, Needs backport to 2.4, Technical review complete

#1047 Add openssl commands to validate SSL certs (#1046)
  downstream/modules/platform/proc-renew-ssl-cert.adoc
Labels: 2.4

#1014 Added minimum requirements to doc
  downstream/modules/platform/ref-controller-system-requirements.adoc
Labels: documentation, Needs backport to 2.4, Ready for technical review, 2.4

#1048 Added minimum requirements to doc (#1014)
  downstream/modules/platform/ref-controller-system-requirements.adoc
Labels: Backported to 2.4, 2.4

#1003 AAP-17672 Updating install guide on building execution environnments
  downstream/assemblies/platform/assembly-disconnected-installation.adoc
  downstream/modules/platform/con-building-an-execution-environment-in-a-disconnected-environment.adoc
  downstream/modules/platform/proc-building-the-custom-execution-environment.adoc
  downstream/modules/platform/proc-creating-the-custom-execution-environment-definition.adoc
  downstream/modules/platform/proc-installing-the-ansible-builder-rpm.adoc
  downstream/modules/platform/proc-upgrading-between-minor-aap-releases.adoc
  downstream/modules/platform/proc-uploading-the-custom-execution-environment-to-the-private-hub.adoc
Labels: Ready for technical review, Not ready for peer review, 2.4

#1052 Bp to 2.4: AAP 19025 create procedure for updating proxy remote settings and updated link title
  downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc
  downstream/modules/hub/proc-configure-proxy-remote.adoc
  downstream/modules/hub/proc-set-community-remote.adoc
  downstream/modules/hub/proc-set-rhcertified-remote.adoc
Labels: Ready for review, Automation Hub, 2.4

#1054 BP to 2.4: AAP-18084 adds collection count variable to ansible automation hub variables table in appendix
  downstream/modules/platform/ref-hub-variables.adoc
Labels: 2.4
