Repository ansible/aap-docs, pull requests merged in 2024-07, with the labels that each got.

#1505 2.5 Adding manifest deprication warning to execution environments doc (#1…
  downstream/assemblies/hub/assembly-populate-container-registry.adoc
  downstream/modules/hub/proc-obtain-images.adoc
Labels: 2.5

#1506 Update containerized install guide to incorporate gateway
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/platform/proc-downloading-containerized-aap.adoc
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/platform/proc-using-postinstall.adoc
  downstream/modules/platform/ref-accessing-control-auto-hub-eda-control.adoc
  downstream/modules/platform/ref-using-custom-tls-certificates.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#1507 Update containerized install guide to incorporate gateway (#1506)
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/platform/proc-downloading-containerized-aap.adoc
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/platform/proc-using-postinstall.adoc
  downstream/modules/platform/ref-accessing-control-auto-hub-eda-control.adoc
  downstream/modules/platform/ref-using-custom-tls-certificates.adoc
Labels: 2.5

#1499 Create Containerized AAP Troubleshooting content
  downstream/assemblies/platform/assembly-appendix-troubleshoot-containerized-aap.adoc
  downstream/modules/platform/ref-containerized-troubleshoot-config.adoc
  downstream/modules/platform/ref-containerized-troubleshoot-install.adoc
  downstream/modules/platform/ref-containerized-troubleshoot-ref.adoc
  downstream/titles/aap-containerized-install/master.adoc
Labels: Ready for review, Needs backport to 2.4, Needs backport to 2.5

#1510 AAP-13268-EDA updated eda controller user guide (#1495)
  downstream/assemblies/eda/assembly-eda-performance-tuning.adoc
  downstream/modules/eda/con-characterizing-your-workload.adoc
  downstream/modules/eda/con-modifying-memory-limit.adoc
  downstream/modules/eda/con-modifying-simultaneous-activations.adoc
  downstream/modules/eda/con-system-level-monitoring.adoc
  downstream/modules/eda/proc-modifying-activations-after-install.adoc
  downstream/modules/eda/proc-modifying-activations-during-install.adoc
  downstream/modules/eda/proc-modifying-memory-after-install.adoc
  downstream/modules/eda/proc-modifying-memory-during-install.adoc
  downstream/modules/eda/ref-performance-troubleshooting.adoc
  downstream/titles/eda/eda-user-guide/master.adoc
Labels: 2.4

#1490 Create additional settings modules
  downstream/images/platform_gateway_full.png
  downstream/images/platform_gateway_settings_page.png
  downstream/images/troubleshooting_options.png
  downstream/images/user_preferences_page.png
  downstream/modules/platform/proc-custom-logos-images.adoc
  downstream/modules/platform/proc-settings-platform-gateway.adoc
  downstream/modules/platform/proc-settings-troubleshooting.adoc
  downstream/modules/platform/proc-settings-user-preferences.adoc
Labels: documentation, 2.5

#1512 Create additional settings modules (#1490)
  downstream/images/platform_gateway_full.png
  downstream/images/platform_gateway_settings_page.png
  downstream/images/troubleshooting_options.png
  downstream/images/user_preferences_page.png
  downstream/modules/platform/proc-custom-logos-images.adoc
  downstream/modules/platform/proc-settings-platform-gateway.adoc
  downstream/modules/platform/proc-settings-troubleshooting.adoc
  downstream/modules/platform/proc-settings-user-preferences.adoc
Labels: 2.5, Backported to 2.5

#1385 AAP-24694 Added note about rulebook activations shutting down and canceling jobs on controller.
  downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc
Labels: Ready for review, Needs backport to 2.4, Technical review complete, 2.4

#1516 Update Configuring Controller Chapter (#1487)
  downstream/assemblies/platform/assembly-ag-controller-config.adoc
  downstream/images/automation_analytics.png
  downstream/images/job-settings-full.png
  downstream/images/logging-settings.png
  downstream/images/settings_subscription_page.png
  downstream/images/subscriptions_first-page.png
  downstream/images/system-settings-full.png
  downstream/images/system_settings_page.png
  downstream/modules/platform/proc-controller-configure-analytics.adoc
  downstream/modules/platform/proc-controller-configure-jobs.adoc
  downstream/modules/platform/proc-controller-configure-subscriptions.adoc
  downstream/modules/platform/proc-controller-configure-system.adoc
  downstream/modules/platform/proc-controller-set-up-logging.adoc
  downstream/modules/platform/ref-controller-logging-settings.adoc
Labels: 2.5, Backported to 2.5

#1517 AAP-25848 Add Microsoft Entra ID attribute to downstream docs
  downstream/attributes/attributes.adoc
Labels: Needs backport to 2.4, Attributes, Needs backport to 2.5

#1518 2.4 AAP-25848 Add Microsoft Entra ID attribute to downstream docs (#1517)
  downstream/attributes/attributes.adoc
Labels: Attributes, 2.4

#1520 AAP-22995: Reused logout procedure in VS Code chapter
  lightspeed/assemblies/assembly_configuring-vscode-extension.adoc
  lightspeed/modules/proc_log-out-of-portal.adoc
Labels: Ready for review, Lightspeed

#1522 Backport to 2.4 for #1451
  downstream/modules/platform/proc-verify-controller-installation.adoc
  downstream/modules/platform/proc-verify-eda-controller-installation.adoc
  downstream/modules/platform/proc-verify-hub-installation.adoc
Labels: Ready for review, 2.4

#1503 AAP-25608: Lightspeed doc improvements
  lightspeed/assemblies/assembly_configuring-vscode-extension.adoc
  lightspeed/modules/con_lightspeed-key-features.adoc
  lightspeed/modules/con_lightspeed-process.adoc
  lightspeed/modules/proc_create-connection-secrets.adoc
  lightspeed/modules/proc_create-lightspeed-instance.adoc
  lightspeed/modules/proc_create-oauth-app.adoc
  lightspeed/modules/proc_install-aap-lightspeed-operator.adoc
  lightspeed/modules/proc_login-vscode-extension.adoc
  lightspeed/modules/proc_update-connection-secrets.adoc
  lightspeed/modules/proc_update-redirect-uri.adoc
  lightspeed/modules/proc_view-playbook-explanation.adoc
Labels: Ready for review, Lightspeed

#1513 AAP-25848 Change Azure Active Directory (AD) to Microsoft Entra ID
  attributes/attributes.adoc
  stories/topics/con-azure-security.adoc
  stories/topics/proc-azure-configure-ad-sso.adoc
  stories/topics/proc-azure-create-service-principal.adoc
Labels: AAP on clouds, AAP on Azure, Technical review complete

#1523 warned users about too much memory
  downstream/modules/platform/ref-automation-hub-requirements.adoc
Labels: Ready for review, Needs backport to 2.4, 2.4

#1504 Commit for AAP-22613 Remove SSO deployment references
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
  downstream/modules/platform/con-ha-hub-installation.adoc
  downstream/modules/platform/ref-controller-variables.adoc
  downstream/modules/platform/ref-hub-variables.adoc
  downstream/modules/platform/ref-single-controller-hub-eda-with-managed-db.adoc
Labels: Ready for review, Needs backport to 2.4, Ready for technical review, Technical review complete, 2.5

#1525 AAP-26616: Added info. that code bot doesn't need IBM watsonx Code Assistant
  lightspeed/assemblies/assembly_using-code-bot-for-suggestions.adoc
Labels: Ready for review, Lightspeed

#1526 AAP-23395: Reused known issue about using remote SSH extension from existing inline troubleshooting doc
  lightspeed/modules/proc_troubleshooting-vscode.adoc
Labels: Ready for review, Lightspeed

#1529 Created Open Source licenses
  downstream/aap-common/apache-2.0-license.adoc
  downstream/aap-common/gplv3-license-text.adoc
Labels: documentation, Backported to 2.4, 2.4, 2.5, Backported to 2.5

#1531 Fixed spelling error in Controller User Guide
  downstream/modules/platform/proc-controller-use-an-exec-env.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#1532 Fixed spelling error in Controller User Guide (#1531)
  downstream/modules/platform/proc-controller-use-an-exec-env.adoc
Labels: documentation, Backported to 2.4, Controller, 2.4

#1533 Fixed spelling error in Controller User Guide (#1531)
  downstream/modules/platform/proc-controller-use-an-exec-env.adoc
Labels: documentation, Controller, 2.5, Backported to 2.5

#812 aap-14811 Added modules for section 4.5
  downstream/assemblies/aap-hardening/assembly-aap-security-enabling.adoc
  downstream/assemblies/aap-hardening/assembly-aap-security-use-cases.adoc
  downstream/assemblies/aap-hardening/assembly-hardening-aap.adoc
  downstream/images/aap-workflow-example.png
  downstream/modules/aap-hardening/con-aap-as-SOC.adoc
  downstream/modules/aap-hardening/con-aap-patch-automation.adoc
  downstream/modules/aap-hardening/con-patch-automation.adoc
  downstream/modules/aap-hardening/ref-apply-defensive-security-controls.adoc
  downstream/modules/aap-hardening/ref-complex-patching-scenarios.adoc
  downstream/modules/aap-hardening/ref-installing-security-updates-only.adoc
  downstream/modules/aap-hardening/ref-keeping-everything-up-to-date.adoc
  downstream/modules/aap-hardening/ref-patching-examples.adoc
  downstream/modules/aap-hardening/ref-specifying-package-versions.adoc
  downstream/titles/aap-hardening/master.adoc
Labels: AAP Hardening, Draft

#1536 warned users about too much memory (#1523)
  downstream/modules/platform/ref-automation-hub-requirements.adoc
Labels: Needs backport to 2.4, 2.4

#1530 Created Open Source licenses (#1529)
  downstream/aap-common/apache-2.0-license.adoc
  downstream/aap-common/gplv3-license-text.adoc
Labels: 2.5, Backported to 2.5

#1541 AAP-24489 Add VS Code remote icon to images dir
  downstream/images/vscode-remote-icon.png
Labels: Needs backport to 2.4, 2.4, 2.5, Needs backport to 2.5

#1538 Adds new EDA 2.5 w/controller 2.4 adoc. Updates main assembly file.
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
  downstream/modules/platform/con-eda-2-5-with-controller-2-4.adoc
Labels: Ready for review, Needs backport to 2.5

#1543 AAP-26282 - Create snippet that describes the platform gateway
  downstream/snippets/snip-gateway-component-description.adoc
Labels: Ready for review, snippets, 2.5, Needs backport to 2.5

#1544 2.4 AAP-24489 Add VS Code remote icon to images dir (#1541)
  downstream/images/vscode-remote-icon.png
Labels: 2.4

#1545 2.5 AAP-24489 Add VS Code remote icon to images dir (#1541)
  downstream/images/vscode-remote-icon.png
Labels: 2.5

#1493 Deploy guide 2.5 updates
  downstream/assemblies/platform/assembly-configure-aap-operator.adoc
  downstream/modules/platform/proc-operator-deploy-central-config.adoc
Labels: documentation, 2.5, AAP operator, Needs backport to 2.5

#1547 Corrected table number
  downstream/modules/platform/ref-system-requirements.adoc
Labels: Needs backport to 2.4, 2.4, 2.5, Needs backport to 2.5

#1548 Corrected table number (#1547)
  downstream/modules/platform/ref-system-requirements.adoc
Labels: 2.5, Backported to 2.5

#1549 Corrected table number (#1547)
  downstream/modules/platform/ref-system-requirements.adoc
Labels: Backported to 2.4, 2.4

#1554 Deploy guide 2.5 updates (#1493)
  downstream/assemblies/platform/assembly-configure-aap-operator.adoc
  downstream/modules/platform/proc-operator-deploy-central-config.adoc
Labels: documentation, Ready for review, 2.5, AAP operator

#1553 Update VM install guide to incorporate gateway
  downstream/assemblies/platform/assembly-appendix-inventory-file-vars.adoc
  downstream/assemblies/platform/assembly-disconnected-installation.adoc
  downstream/assemblies/platform/assembly-platform-install-overview.adoc
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
  downstream/assemblies/platform/assembly-system-requirements.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/platform/con-install-scenario-recommendations.adoc
  downstream/modules/platform/proc-running-setup-script.adoc
  downstream/modules/platform/proc-upgrading-between-minor-aap-releases.adoc
  downstream/modules/platform/proc-verify-aap-installation.adoc
  downstream/modules/platform/ref-gateway-controller-ext-db.adoc
  downstream/modules/platform/ref-gateway-controller-hub-eda-ext-db.adoc
  downstream/modules/platform/ref-gateway-controller-hub-ext-db.adoc
  downstream/modules/platform/ref-gateway-system-requirements.adoc
  downstream/modules/platform/ref-gateway-variables.adoc
  downstream/modules/platform/ref-hub-variables.adoc
  downstream/modules/platform/ref-postgresql-requirements.adoc
  downstream/modules/platform/ref-system-requirements.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#1555 Update VM install guide to incorporate gateway (#1553)
  downstream/assemblies/platform/assembly-appendix-inventory-file-vars.adoc
  downstream/assemblies/platform/assembly-disconnected-installation.adoc
  downstream/assemblies/platform/assembly-platform-install-overview.adoc
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
  downstream/assemblies/platform/assembly-system-requirements.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/platform/con-install-scenario-recommendations.adoc
  downstream/modules/platform/proc-running-setup-script.adoc
  downstream/modules/platform/proc-upgrading-between-minor-aap-releases.adoc
  downstream/modules/platform/proc-verify-aap-installation.adoc
  downstream/modules/platform/ref-gateway-controller-ext-db.adoc
  downstream/modules/platform/ref-gateway-controller-hub-eda-ext-db.adoc
  downstream/modules/platform/ref-gateway-controller-hub-ext-db.adoc
  downstream/modules/platform/ref-gateway-system-requirements.adoc
  downstream/modules/platform/ref-gateway-variables.adoc
  downstream/modules/platform/ref-hub-variables.adoc
  downstream/modules/platform/ref-postgresql-requirements.adoc
  downstream/modules/platform/ref-system-requirements.adoc
Labels: 2.5

#1546 Added open source licence to Playbooks doc
  downstream/aap-common/apache-2.0-license.adoc
  downstream/aap-common/gplv3-license-text.adoc
  downstream/assemblies/playbooks/assembly-open-source-license.adoc
  downstream/modules/playbooks/ref-playbook-execution.adoc
  downstream/titles/playbooks/playbooks-getting-started/docinfo.xml
  downstream/titles/playbooks/playbooks-getting-started/master.adoc
Labels: Needs backport to 2.4, 2.4, 2.5, Needs backport to 2.5

#1557 Added open source licence to Playbooks doc (#1546)
  downstream/aap-common/apache-2.0-license.adoc
  downstream/aap-common/gplv3-license-text.adoc
  downstream/assemblies/playbooks/assembly-open-source-license.adoc
  downstream/modules/playbooks/ref-playbook-execution.adoc
  downstream/titles/playbooks/playbooks-getting-started/docinfo.xml
  downstream/titles/playbooks/playbooks-getting-started/master.adoc
Labels: 2.5, Backported to 2.5

#1558 Added open source licence to Playbooks doc (#1546)
  downstream/aap-common/apache-2.0-license.adoc
  downstream/aap-common/gplv3-license-text.adoc
  downstream/assemblies/playbooks/assembly-open-source-license.adoc
  downstream/modules/playbooks/ref-playbook-execution.adoc
  downstream/titles/playbooks/playbooks-getting-started/docinfo.xml
  downstream/titles/playbooks/playbooks-getting-started/master.adoc
Labels: Backported to 2.4, 2.4

#1559 Add new inventory source docs for OpenShift Virtualization
  downstream/assemblies/platform/assembly-controller-inventories.adoc
  downstream/modules/platform/proc-controller-inv-source-open-shift-virt.adoc
  downstream/modules/platform/ref-controller-inventory-plugins.adoc
Labels: documentation, Controller, 2.5, Needs backport to 2.5

#1552 AAP-18761 convert/create modules for the gateway dashboard
  downstream/modules/platform/con-gw-dash-components.adoc
  downstream/modules/platform/con-gw-dash-features.adoc
Labels: Ready for review, Dashboard, 2.5, Needs backport to 2.5

#1562 Pre-release updates for async release notes
  downstream/archive/archived-titles/release-notes/async/installer-24-11.adoc
  downstream/archive/archived-titles/release-notes/async/installer-24-12.adoc
  downstream/archive/archived-titles/release-notes/async/installer-24-13.adoc
  downstream/archive/archived-titles/release-notes/async/installer-24-14.adoc
  downstream/archive/archived-titles/release-notes/async/installer-24-21.adoc
  downstream/archive/archived-titles/release-notes/async/installer-24-22.adoc
  downstream/archive/archived-titles/release-notes/async/installer-24-23.adoc
  downstream/archive/archived-titles/release-notes/async/installer-24-24.adoc
  downstream/archive/archived-titles/release-notes/async/installer-24-6.adoc
  downstream/archive/archived-titles/release-notes/async/installer-24-61.adoc
  downstream/archive/archived-titles/release-notes/async/installer-24-62.adoc
  downstream/archive/archived-titles/release-notes/async/installer-24-7.adoc
  downstream/archive/archived-titles/release-notes/async/rpm-24-2.adoc
  downstream/archive/archived-titles/release-notes/async/rpm-24-3.adoc
  downstream/archive/archived-titles/release-notes/async/rpm-24-4.adoc
  downstream/archive/archived-titles/release-notes/async/rpm-24-5.adoc
  downstream/archive/archived-titles/release-notes/async/rpm-24-6.adoc
  downstream/archive/archived-titles/release-notes/async/rpm-24-7.adoc
  downstream/titles/release-notes/async/async-updates.adoc
  downstream/titles/release-notes/async/installer-version-table.adoc
  downstream/titles/release-notes/async/rpm-version-table.adoc
  downstream/titles/release-notes/master.adoc
  downstream/titles/release-notes/topics/eda-24.adoc
  downstream/titles/release-notes/topics/rpm-version-table.adoc
Labels: AAP Release notes, 2.5, Needs backport to 2.5

#1563 2.5 Pre-release updates for async release notes (#1562)
  downstream/archive/archived-titles/release-notes/async/installer-24-11.adoc
  downstream/archive/archived-titles/release-notes/async/installer-24-12.adoc
  downstream/archive/archived-titles/release-notes/async/installer-24-13.adoc
  downstream/archive/archived-titles/release-notes/async/installer-24-14.adoc
  downstream/archive/archived-titles/release-notes/async/installer-24-21.adoc
  downstream/archive/archived-titles/release-notes/async/installer-24-22.adoc
  downstream/archive/archived-titles/release-notes/async/installer-24-23.adoc
  downstream/archive/archived-titles/release-notes/async/installer-24-24.adoc
  downstream/archive/archived-titles/release-notes/async/installer-24-6.adoc
  downstream/archive/archived-titles/release-notes/async/installer-24-61.adoc
  downstream/archive/archived-titles/release-notes/async/installer-24-62.adoc
  downstream/archive/archived-titles/release-notes/async/installer-24-7.adoc
  downstream/archive/archived-titles/release-notes/async/rpm-24-2.adoc
  downstream/archive/archived-titles/release-notes/async/rpm-24-3.adoc
  downstream/archive/archived-titles/release-notes/async/rpm-24-4.adoc
  downstream/archive/archived-titles/release-notes/async/rpm-24-5.adoc
  downstream/archive/archived-titles/release-notes/async/rpm-24-6.adoc
  downstream/archive/archived-titles/release-notes/async/rpm-24-7.adoc
  downstream/titles/release-notes/async/async-updates.adoc
  downstream/titles/release-notes/async/installer-version-table.adoc
  downstream/titles/release-notes/async/rpm-version-table.adoc
  downstream/titles/release-notes/master.adoc
  downstream/titles/release-notes/topics/eda-24.adoc
  downstream/titles/release-notes/topics/rpm-version-table.adoc
Labels: AAP Release notes, 2.5

#1566 AAP-26400 added open source license to creating and using ees
  downstream/assemblies/builder/assembly-open-source-license.adoc
  downstream/titles/builder/docinfo.xml
  downstream/titles/builder/master.adoc
Labels: Ready for review, 2.4, 2.5

#1567 AAP-26400 added open source license to creating and using ees (#1566)
  downstream/assemblies/builder/assembly-open-source-license.adoc
  downstream/titles/builder/docinfo.xml
  downstream/titles/builder/master.adoc
Labels: Ready for review, 2.5

#1571 AAP-23850: Added info. about Red Hat and Lightspeed authentication options
  lightspeed/modules/proc_login-vscode-extension.adoc
Labels: Ready for review, Lightspeed

#1575 2.5titles - Update the 2.5 titles to follow style guidelines & subtitle cleanup
  downstream/titles/aap-containerized-install/docinfo.xml
  downstream/titles/aap-containerized-install/master.adoc
  downstream/titles/aap-hardening/docinfo.xml
  downstream/titles/aap-hardening/master.adoc
  downstream/titles/aap-installation-guide/docinfo.xml
  downstream/titles/aap-installation-guide/master.adoc
  downstream/titles/aap-operator-backup/docinfo.xml
  downstream/titles/aap-operator-backup/master.adoc
  downstream/titles/analytics/job-explorer/docinfo.xml
  downstream/titles/analytics/job-explorer/master.adoc
  downstream/titles/automation-mesh/docinfo.xml
  downstream/titles/automation-mesh/master.adoc
  downstream/titles/builder/docinfo.xml
  downstream/titles/builder/master.adoc
  downstream/titles/central-auth/docinfo.xml
  downstream/titles/central-auth/master.adoc
  downstream/titles/controller/controller-admin-guide/docinfo.xml
  downstream/titles/controller/controller-admin-guide/master.adoc
  downstream/titles/controller/controller-api-overview/docinfo.xml
  downstream/titles/controller/controller-api-overview/master.adoc
  downstream/titles/controller/controller-user-guide/docinfo.xml
  downstream/titles/controller/controller-user-guide/master.adoc
  downstream/titles/dev-guide/docinfo.xml
  downstream/titles/develop-automation-content/docinfo.xml
  downstream/titles/eda/eda-getting-started-guide/docinfo.xml
  downstream/titles/eda/eda-getting-started-guide/master.adoc
  downstream/titles/eda/eda-user-guide/docinfo.xml
  downstream/titles/eda/eda-user-guide/master.adoc
  downstream/titles/getting-started/docinfo.xml
  downstream/titles/getting-started/master.adoc
  downstream/titles/navigator-guide/docinfo.xml
  downstream/titles/navigator-guide/master.adoc
  downstream/titles/operator-mesh/docinfo.xml
  downstream/titles/operator-mesh/master.adoc
  downstream/titles/playbooks/playbooks-getting-started/docinfo.xml
  downstream/titles/playbooks/playbooks-getting-started/master.adoc
  downstream/titles/playbooks/playbooks-reference/docinfo.xml
  downstream/titles/playbooks/playbooks-reference/master.adoc
  downstream/titles/release-notes/docinfo.xml
  downstream/titles/release-notes/master.adoc
  downstream/titles/security-guide/docinfo.xml
  downstream/titles/security-guide/master.adoc
  downstream/titles/upgrade/docinfo.xml
  downstream/titles/upgrade/master.adoc
Labels: Ready for review, Title change, 2.5, Needs backport to 2.5

#1576 [Backport] - 2.5titles - Update the 2.5 titles to follow style guidelines & cleanup subtitles
  downstream/archive/archived-titles/dev-guide/docinfo.xml
  downstream/titles/aap-containerized-install/docinfo.xml
  downstream/titles/aap-containerized-install/master.adoc
  downstream/titles/aap-hardening/docinfo.xml
  downstream/titles/aap-hardening/master.adoc
  downstream/titles/aap-installation-guide/docinfo.xml
  downstream/titles/aap-installation-guide/master.adoc
  downstream/titles/aap-operator-backup/docinfo.xml
  downstream/titles/aap-operator-backup/master.adoc
  downstream/titles/analytics/job-explorer/docinfo.xml
  downstream/titles/analytics/job-explorer/master.adoc
  downstream/titles/automation-mesh/docinfo.xml
  downstream/titles/automation-mesh/master.adoc
  downstream/titles/builder/docinfo.xml
  downstream/titles/builder/master.adoc
  downstream/titles/central-auth/docinfo.xml
  downstream/titles/central-auth/master.adoc
  downstream/titles/controller/controller-admin-guide/docinfo.xml
  downstream/titles/controller/controller-admin-guide/master.adoc
  downstream/titles/controller/controller-api-overview/docinfo.xml
  downstream/titles/controller/controller-api-overview/master.adoc
  downstream/titles/controller/controller-user-guide/docinfo.xml
  downstream/titles/controller/controller-user-guide/master.adoc
  downstream/titles/develop-automation-content/docinfo.xml
  downstream/titles/eda/eda-getting-started-guide/docinfo.xml
  downstream/titles/eda/eda-getting-started-guide/master.adoc
  downstream/titles/eda/eda-user-guide/docinfo.xml
  downstream/titles/eda/eda-user-guide/master.adoc
  downstream/titles/getting-started/docinfo.xml
  downstream/titles/getting-started/master.adoc
  downstream/titles/navigator-guide/docinfo.xml
  downstream/titles/navigator-guide/master.adoc
  downstream/titles/operator-mesh/docinfo.xml
  downstream/titles/operator-mesh/master.adoc
  downstream/titles/playbooks/playbooks-getting-started/docinfo.xml
  downstream/titles/playbooks/playbooks-getting-started/master.adoc
  downstream/titles/playbooks/playbooks-reference/docinfo.xml
  downstream/titles/playbooks/playbooks-reference/master.adoc
  downstream/titles/release-notes/docinfo.xml
  downstream/titles/release-notes/master.adoc
  downstream/titles/security-guide/docinfo.xml
  downstream/titles/security-guide/master.adoc
  downstream/titles/upgrade/docinfo.xml
  downstream/titles/upgrade/master.adoc
Labels: Title change

#1579 2.4 Add 2.4-7.1 bundle installer release to release notes
  downstream/titles/release-notes/master.adoc
  downstream/titles/release-notes/topics/installer-24-71.adoc
  downstream/titles/release-notes/topics/installer-version-table.adoc
Labels: AAP Release notes, 2.4

#1580 Added note about removal of container images
  downstream/modules/platform/con-aap-upgrade-planning.adoc
  downstream/modules/platform/proc-running-setup-script-for-updates.adoc
Labels: Needs backport to 2.4, 2.4, 2.5, Needs backport to 2.5

#1514 AAP-22069 adding backup and restore via yaml chapters
  downstream/assemblies/platform/assembly-aap-backup.adoc
  downstream/assemblies/platform/assembly-aap-recovery.adoc
  downstream/modules/platform/proc-aap-controller-restore.adoc
  downstream/modules/platform/proc-aap-controller-yaml-backup.adoc
  downstream/modules/platform/proc-aap-controller-yaml-restore.adoc
Labels: documentation, Ready for review, Draft, 2.4, 2.5, AAP operator

#1581 Added note about removal of container images (#1580)
  downstream/modules/platform/con-aap-upgrade-planning.adoc
  downstream/modules/platform/proc-running-setup-script-for-updates.adoc
Labels: 2.5, Backported to 2.5

#1583 Added note about removal of container images (#1580)
  downstream/modules/platform/con-aap-upgrade-planning.adoc
  downstream/modules/platform/proc-running-setup-script-for-updates.adoc
Labels: Backported to 2.4, 2.4

#1585 Backport 1582 to 2.4
  downstream/assemblies/platform/assembly-aap-backup.adoc
  downstream/assemblies/platform/assembly-aap-recovery.adoc
  downstream/modules/platform/proc-aap-controller-restore.adoc
  downstream/modules/platform/proc-aap-controller-yaml-backup.adoc
  downstream/modules/platform/proc-aap-controller-yaml-restore.adoc
Labels: Ready for review, Needs backport to 2.4, 2.4

#1586 Backport 1582 to 2.5
  downstream/assemblies/platform/assembly-aap-backup.adoc
  downstream/assemblies/platform/assembly-aap-recovery.adoc
  downstream/modules/platform/proc-aap-controller-restore.adoc
  downstream/modules/platform/proc-aap-controller-yaml-backup.adoc
  downstream/modules/platform/proc-aap-controller-yaml-restore.adoc
Labels: documentation, 2.5, AAP operator, Needs backport to 2.5

#1587 creating PostgresVers attribute
  downstream/attributes/attributes.adoc
  downstream/modules/platform/proc-aap-controller-yaml-restore.adoc
Labels: documentation, 2.5

#1588 creating PostgresVers attribute (#1587)
  downstream/attributes/attributes.adoc
  downstream/modules/platform/proc-aap-controller-yaml-restore.adoc
Labels: documentation, 2.5

#1590 AAP-27282 - Updated attribute for credentials
  downstream/attributes/attributes.adoc
  downstream/modules/eda/proc-eda-set-up-credential.adoc
  downstream/modules/hub/proc-configure-automation-hub-server-gui.adoc
  downstream/modules/hub/proc-create-credential.adoc
  downstream/modules/platform/proc-controller-add-users-job-templates.adoc
  downstream/modules/platform/proc-controller-adding-gpg-key.adoc
  downstream/modules/platform/proc-controller-create-credential.adoc
  downstream/modules/platform/proc-controller-create-insights-credential.adoc
  downstream/modules/platform/proc-controller-edit-credential.adoc
  downstream/modules/platform/ref-controller-credentials-getting-started.adoc
Labels: Ready for review, Attributes, 2.5, Needs backport to 2.5

#1593 List RHEL 9.0 as supported in planning guide
  downstream/modules/platform/ref-system-requirements.adoc
Labels: 2.4

#1594 adding ingress and egress diagrams
  images/Egress.png
  images/Ingress+egress.png
  stories/topics/con-saas-intro.adoc
Labels: documentation, AAP on clouds, Ready for review, SaaS on AWS

#1556 Preparing the AAP Operator guides for EA
  downstream/assemblies/platform/assembly-aap-backup.adoc
  downstream/assemblies/platform/assembly-aap-recovery.adoc
  downstream/assemblies/platform/assembly-configure-aap-operator.adoc
  downstream/assemblies/platform/assembly-installing-controller-operator.adoc
  downstream/assemblies/platform/assembly-installing-hub-operator.adoc
  downstream/modules/platform/con-ocp-supported-install.adoc
  downstream/modules/platform/con-resource-operator-overview.adoc
  downstream/modules/platform/proc-access-hub-operator-ui.adoc
  downstream/modules/platform/proc-add-controller-access-token.adoc
  downstream/modules/platform/proc-cli-get-controller-pwd.adoc
  downstream/modules/platform/proc-configuring-controller-image-pull-policy.adoc
  downstream/modules/platform/proc-configuring-controller-ldap-security.adoc
  downstream/modules/platform/proc-configuring-controller-route-options.adoc
  downstream/modules/platform/proc-controller-ingress-options.adoc
  downstream/modules/platform/proc-enable-hstore-extension.adoc
  downstream/modules/platform/proc-hub-ingress-options.adoc
  downstream/modules/platform/proc-hub-route-options.adoc
  downstream/modules/platform/proc-install-cli-aap-operator.adoc
  downstream/modules/platform/proc-operator-access-aap.adoc
  downstream/modules/platform/proc-operator-external-db-controller.adoc
  downstream/modules/platform/proc-operator-external-db-hub.adoc
  downstream/modules/platform/proc-provision-ocp-storage-with-readwritemany.adoc
  downstream/titles/aap-operator-installation/master.adoc
Labels: documentation, Ready for review, Draft, 2.5, AAP operator

#1599 AAP-25260 Add Ansible plug-ins for developer hub titles
  downstream/titles/aap-plugin-rhdh-install/aap-common
  downstream/titles/aap-plugin-rhdh-install/attributes
  downstream/titles/aap-plugin-rhdh-install/devtools
  downstream/titles/aap-plugin-rhdh-install/docinfo.xml
  downstream/titles/aap-plugin-rhdh-install/images
  downstream/titles/aap-plugin-rhdh-install/master.adoc
  downstream/titles/aap-plugin-rhdh-using/aap-common
  downstream/titles/aap-plugin-rhdh-using/attributes
  downstream/titles/aap-plugin-rhdh-using/devtools
  downstream/titles/aap-plugin-rhdh-using/docinfo.xml
  downstream/titles/aap-plugin-rhdh-using/images
  downstream/titles/aap-plugin-rhdh-using/master.adoc
  downstream/titles/aap-plugin-rhdh/docinfo.xml
Labels: Needs backport to 2.4, 2.4, 2.5, Needs backport to 2.5

#1601 2.4 AAP-25260 Add Ansible plug-ins for developer hub titles (#1599)
  downstream/titles/aap-plugin-rhdh-install/aap-common
  downstream/titles/aap-plugin-rhdh-install/attributes
  downstream/titles/aap-plugin-rhdh-install/devtools
  downstream/titles/aap-plugin-rhdh-install/docinfo.xml
  downstream/titles/aap-plugin-rhdh-install/images
  downstream/titles/aap-plugin-rhdh-install/master.adoc
  downstream/titles/aap-plugin-rhdh-using/aap-common
  downstream/titles/aap-plugin-rhdh-using/attributes
  downstream/titles/aap-plugin-rhdh-using/devtools
  downstream/titles/aap-plugin-rhdh-using/docinfo.xml
  downstream/titles/aap-plugin-rhdh-using/images
  downstream/titles/aap-plugin-rhdh-using/master.adoc
Labels: 2.4

#1602 2.5 AAP-25260 Add Ansible plug-ins for developer hub titles (#1599)
  downstream/titles/aap-plugin-rhdh-install/aap-common
  downstream/titles/aap-plugin-rhdh-install/attributes
  downstream/titles/aap-plugin-rhdh-install/devtools
  downstream/titles/aap-plugin-rhdh-install/docinfo.xml
  downstream/titles/aap-plugin-rhdh-install/images
  downstream/titles/aap-plugin-rhdh-install/master.adoc
  downstream/titles/aap-plugin-rhdh-using/aap-common
  downstream/titles/aap-plugin-rhdh-using/attributes
  downstream/titles/aap-plugin-rhdh-using/devtools
  downstream/titles/aap-plugin-rhdh-using/docinfo.xml
  downstream/titles/aap-plugin-rhdh-using/images
  downstream/titles/aap-plugin-rhdh-using/master.adoc
Labels: 2.5

#1603 AAP-25260 Add assemblies for plug-ins for developer hub
  downstream/assemblies/devtools/assembly-rhdh-configure.adoc
  downstream/assemblies/devtools/assembly-rhdh-install.adoc
  downstream/assemblies/devtools/assembly-rhdh-intro.adoc
  downstream/assemblies/devtools/assembly-rhdh-planning.adoc
  downstream/assemblies/devtools/assembly-rhdh-upgrading-uninstalling.adoc
  downstream/assemblies/devtools/assembly-rhdh-using.adoc
Labels: 2.4

#1597 AAP-23850-update: Updated the authentication options content
  lightspeed/modules/proc_login-vscode-extension.adoc
Labels: Ready for review, Technical review complete, Lightspeed

#1598 Corrections to Configuring automation execution
  downstream/assemblies/platform/assembly-ag-controller-config.adoc
  downstream/assemblies/platform/assembly-inventory-file-importing.adoc
  downstream/modules/platform/proc-controller-configure-analytics.adoc
  downstream/modules/platform/proc-controller-configure-jobs.adoc
  downstream/modules/platform/proc-controller-configure-subscriptions.adoc
  downstream/modules/platform/proc-controller-configure-system.adoc
  downstream/modules/platform/ref-controller-capacity-planning-exercise.adoc
  downstream/modules/platform/ref-controller-capacity-planning.adoc
  downstream/modules/platform/ref-controller-cluster-management.adoc
  downstream/modules/platform/ref-controller-performance-troubleshooting.adoc
  downstream/titles/controller/controller-admin-guide/master.adoc
Labels: documentation, Controller, 2.5, Needs backport to 2.5

#1605 Corrections to Configuring automation execution (#1598)
  downstream/assemblies/platform/assembly-ag-controller-config.adoc
  downstream/assemblies/platform/assembly-inventory-file-importing.adoc
  downstream/modules/platform/proc-controller-configure-analytics.adoc
  downstream/modules/platform/proc-controller-configure-jobs.adoc
  downstream/modules/platform/proc-controller-configure-subscriptions.adoc
  downstream/modules/platform/proc-controller-configure-system.adoc
  downstream/modules/platform/ref-controller-capacity-planning-exercise.adoc
  downstream/modules/platform/ref-controller-capacity-planning.adoc
  downstream/modules/platform/ref-controller-cluster-management.adoc
  downstream/modules/platform/ref-controller-performance-troubleshooting.adoc
  downstream/titles/controller/controller-admin-guide/master.adoc
Labels: documentation, Controller, 2.5, Backported to 2.5

#1606 Added note to API guide for filtering exact matches
  downstream/modules/platform/ref-controller-api-field-lookups.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.5, Needs backport to 2.5

#1608 Added note to API guide for filtering exact matches (#1606)
  downstream/modules/platform/ref-controller-api-field-lookups.adoc
Labels: documentation, Backported to 2.4, Controller, 2.4

#1607 Added note to API guide for filtering exact matches (#1606)
  downstream/modules/platform/ref-controller-api-field-lookups.adoc
Labels: documentation, Controller, 2.5, Backported to 2.5

#1600 AAP-20808 Added new HS assembly and EDA HS process.
  downstream/assemblies/platform/assembly-horizontal-scaling.adoc
  downstream/modules/platform/con-hs-eda-controller.adoc
  downstream/modules/platform/con-hs-eda-sizing-scaling.adoc
  downstream/modules/platform/proc-hs-eda-setup.adoc
  downstream/titles/aap-installation-guide/master.adoc
Labels: Ready for review, Technical review complete, 2.5, Needs backport to 2.5

#1570 Make further changes to Controller Docs
  downstream/assemblies/platform/assembly-ag-instance-and-container-groups.adoc
  downstream/assemblies/platform/assembly-controller-activity-stream.adoc
  downstream/assemblies/platform/assembly-controller-credentials.adoc
  downstream/assemblies/platform/assembly-controller-inventories.adoc
  downstream/images/activity_stream_details.png
  downstream/images/activity_stream_page.png
  downstream/images/credential-types-drop-down-menu.png
  downstream/images/ug-scm-project-branching-emphasized.png
  downstream/modules/platform/con-controller-administration.adoc
  downstream/modules/platform/con-controller-capacity-determination.adoc
  downstream/modules/platform/con-controller-container-groups.adoc
  downstream/modules/platform/con-controller-infrastructure.adoc
  downstream/modules/platform/con-controller-overview-details.adoc
  downstream/modules/platform/proc-controller-add-users-job-templates.adoc
  downstream/modules/platform/proc-controller-create-container-group.adoc
  downstream/modules/platform/proc-controller-create-credential-type.adoc
  downstream/modules/platform/proc-controller-create-credential.adoc
  downstream/modules/platform/proc-controller-create-instance-group.adoc
  downstream/modules/platform/proc-controller-create-job-template.adoc
  downstream/modules/platform/proc-controller-define-filter-with-facts.adoc
  downstream/modules/platform/proc-controller-inv-source-open-shift-virt.adoc
  downstream/modules/platform/proc-controller-inv-source-terraform.adoc
  downstream/modules/platform/proc-controller-set-up-github-webhook.adoc
  downstream/modules/platform/proc-controller-set-up-gitlab-webhook.adoc
  downstream/modules/platform/ref-controller-aws-secrets-lookup.adoc
  downstream/modules/platform/ref-controller-content-sourcing.adoc
  downstream/modules/platform/ref-controller-credential-azure-key.adoc
  downstream/modules/platform/ref-controller-credential-bitbucket.adoc
  downstream/modules/platform/ref-controller-credential-centrify-vault.adoc
  downstream/modules/platform/ref-controller-credential-cyberark-central.adoc
  downstream/modules/platform/ref-controller-credential-cyberark-conjur.adoc
  downstream/modules/platform/ref-controller-credential-hashiCorp-secret.adoc
  downstream/modules/platform/ref-controller-credential-hashiCorp-vault.adoc
  downstream/modules/platform/ref-controller-credential-terraform.adoc
  downstream/modules/platform/ref-controller-credential-thycotic-server.adoc
  downstream/modules/platform/ref-controller-credential-thycotic-vault.adoc
  downstream/modules/platform/ref-controller-credential-types.adoc
  downstream/modules/platform/ref-controller-instance-group-capacity.adoc
  downstream/modules/platform/ref-controller-prompted-vault-credentials.adoc
  downstream/modules/platform/ref-get-started-credential-types.adoc
  downstream/modules/troubleshooting-aap/proc-troubleshoot-job-permissions.adoc
  downstream/titles/controller/controller-user-guide/master.adoc
Labels: documentation, Controller, 2.5, Needs backport to 2.5

#1614 Correct Vale errors in our aap-docs
  downstream/modules/dev-guide/proc-select-custom-venv-export.adoc
  downstream/modules/hub/con-approval-pipeline.adoc
  downstream/modules/hub/proc-pushing-container-images-from-your-local.adoc
  downstream/modules/platform/con-building-an-execution-environment-in-a-disconnected-environment.adoc
  downstream/modules/platform/con-controller-understand-architecture.adoc
  downstream/modules/platform/con-operator-upgrade-considerations.adoc
  downstream/modules/platform/proc-aap-activate-with-manifest.adoc
  downstream/modules/platform/proc-configure-upgraded-aap.adoc
  downstream/modules/platform/proc-controller-adding-subscription-manually.adoc
  downstream/modules/platform/proc-controller-deleting-a-user.adoc
  downstream/modules/platform/proc-controller-reset-tower-base.adoc
  downstream/modules/platform/proc-controller-run-ad-hoc-commands.adoc
  downstream/modules/platform/proc-controller-run-job-template.adoc
  downstream/modules/platform/proc-controller-set-up-SAML.adoc
  downstream/modules/platform/proc-creating-collection-namespace.adoc
  downstream/modules/platform/proc-creating-the-custom-execution-environment-definition.adoc
  downstream/modules/platform/proc-deprovision-group.adoc
  downstream/modules/platform/proc-installing-the-ansible-builder-rpm.adoc
  downstream/modules/platform/proc-operator-external-db-controller.adoc
  downstream/modules/platform/proc-operator-external-db-hub.adoc
  downstream/modules/platform/ref-controller-audit-functionality.adoc
  downstream/modules/platform/ref-controller-change-admin-password.adoc
  downstream/modules/platform/ref-controller-internal-services.adoc
  downstream/modules/platform/ref-controller-smart-host-filter.adoc
Labels: Needs backport to 2.5

#1611 updates to aap-common modules and small typo fix
  aap-common/external-site-disclaimer.adoc
  aap-common/providing-feedback.adoc
  stories/topics/proc-saas-set-up-private.adoc
  stories/topics/proc-saas-set-up-public.adoc
  stories/topics/ref-saas-default-configs.adoc
  stories/topics/ref-saas-planning-configs.adoc
Labels: documentation, AAP on clouds, Ready for review, SaaS on AWS

#1620 updating feedback and disclaimer modules in aap-common (#1612)
  downstream/aap-common/external-site-disclaimer.adoc
  downstream/aap-common/providing-feedback.adoc
Labels: documentation, Ready for review, 2.4

#1619 updating feedback and disclaimer modules in aap-common (#1612)
  downstream/aap-common/external-site-disclaimer.adoc
  downstream/aap-common/providing-feedback.adoc
Labels: documentation, Ready for review, 2.5

#1621 adding SME comments on final draft
  downstream/modules/platform/proc-cli-get-controller-pwd.adoc
Labels: documentation, Ready for review, 2.5, AAP operator

#1622 adding SME comments on final draft (#1621)
  downstream/modules/platform/proc-cli-get-controller-pwd.adoc
Labels: documentation, Ready for review, 2.5, AAP operator

#1623 AAP-27468: Updated connectivity requirements for VS Code
  lightspeed/assemblies/assembly_configuring-vscode-extension.adoc
Labels: Ready for review, Lightspeed

#1624 Add note to section on facts and host filters
  downstream/modules/platform/proc-controller-define-filter-with-facts.adoc
Labels: Controller, 2.4

#1625 updating apap-common disclaimer
  lightspeed/aap-common/external-site-disclaimer.adoc
Labels: documentation, Ready for review, Lightspeed

#1537 AAP-26663 added section 2.3.3 Applying defensive security controls
  downstream/assemblies/aap-hardening/assembly-hardening-aap.adoc
  downstream/modules/aap-hardening/ref-apply-defensive-security-controls.adoc
Labels: AAP Hardening, Ready for review, Draft, 2.5

#1596 AAP-25787: Created troubleshooting doc for Lightspeed on-premise deployment
  lightspeed/assemblies/assembly_troubleshooting-lightspeed.adoc
  lightspeed/modules/con_lightspeed-process.adoc
  lightspeed/modules/proc_troubleshooting-lightspeed-onpremise-config.adoc
Labels: Not ready for peer review, Lightspeed

#1628 Adding version 2.5 note on components
  downstream/assemblies/platform/assembly-configure-aap-operator.adoc
  downstream/assemblies/platform/assembly-installing-hub-operator.adoc
  downstream/assemblies/platform/assembly-operator-add-execution-nodes.adoc
  downstream/assemblies/platform/assembly-using-rhsso-operator-with-automation-hub.adoc
  downstream/modules/platform/con-about-operator.adoc
  downstream/modules/platform/con-ocp-supported-install.adoc
  downstream/modules/platform/proc-add-operator-execution-nodes.adoc
  downstream/modules/platform/proc-controller-ingress-options.adoc
  downstream/modules/platform/proc-create-keycloak-client.adoc
  downstream/modules/platform/proc-create-keycloak-instance.adoc
  downstream/modules/platform/proc-hub-ingress-options.adoc
  downstream/modules/platform/proc-install-aap-operator.adoc
  downstream/modules/platform/proc-install-cli-aap-operator.adoc
  downstream/modules/platform/proc-installing-hub-using-operator.adoc
  downstream/modules/platform/proc-operator-access-aap.adoc
  downstream/modules/platform/proc-operator-deploy-central-config.adoc
  downstream/modules/platform/proc-operator-external-db-controller.adoc
  downstream/modules/platform/proc-operator-external-db-hub.adoc
  downstream/modules/platform/proc-update-rhsso-client.adoc
Labels: documentation, Ready for review, 2.5, AAP operator, Needs backport to 2.5

#1631 Editorial review of entire doc ahead of 2.5 EA (#1628)
  downstream/assemblies/platform/assembly-configure-aap-operator.adoc
  downstream/assemblies/platform/assembly-installing-hub-operator.adoc
  downstream/assemblies/platform/assembly-operator-add-execution-nodes.adoc
  downstream/assemblies/platform/assembly-using-rhsso-operator-with-automation-hub.adoc
  downstream/modules/platform/con-about-operator.adoc
  downstream/modules/platform/con-ocp-supported-install.adoc
  downstream/modules/platform/proc-add-operator-execution-nodes.adoc
  downstream/modules/platform/proc-controller-ingress-options.adoc
  downstream/modules/platform/proc-create-keycloak-client.adoc
  downstream/modules/platform/proc-create-keycloak-instance.adoc
  downstream/modules/platform/proc-hub-ingress-options.adoc
  downstream/modules/platform/proc-install-aap-operator.adoc
  downstream/modules/platform/proc-install-cli-aap-operator.adoc
  downstream/modules/platform/proc-installing-hub-using-operator.adoc
  downstream/modules/platform/proc-operator-access-aap.adoc
  downstream/modules/platform/proc-operator-deploy-central-config.adoc
  downstream/modules/platform/proc-operator-external-db-controller.adoc
  downstream/modules/platform/proc-operator-external-db-hub.adoc
  downstream/modules/platform/proc-update-rhsso-client.adoc
Labels: documentation, 2.5, AAP operator

#1636 AAP-27894 Add async release notes for Ansible plug-ins 1.0.0
  downstream/titles/release-notes/master.adoc
  downstream/titles/release-notes/topics/ansible-plugins-1.0.0.adoc
  downstream/titles/release-notes/topics/snippets
Labels: AAP Release notes, 2.4

#1637 Editorial review on backup and recovery doc
  downstream/modules/platform/con-aap-backup-recommendations.adoc
  downstream/modules/platform/con-aap-backup-recovery.adoc
  downstream/modules/platform/proc-aap-controller-backup.adoc
  downstream/modules/platform/proc-aap-controller-restore.adoc
  downstream/modules/platform/proc-aap-controller-yaml-backup.adoc
  downstream/modules/platform/proc-aap-controller-yaml-restore.adoc
  downstream/modules/platform/proc-aap-hub-backup.adoc
  downstream/modules/platform/proc-aap-hub-restore.adoc
  downstream/modules/platform/proc-aap-platform-gateway-backup.adoc
  downstream/modules/platform/proc-aap-platform-gateway-restore.adoc
Labels: documentation, Ready for review, 2.5, AAP operator, Needs backport to 2.5

#1638 Editorial review on backup and recovery doc (#1637)
  downstream/modules/platform/con-aap-backup-recommendations.adoc
  downstream/modules/platform/con-aap-backup-recovery.adoc
  downstream/modules/platform/proc-aap-controller-backup.adoc
  downstream/modules/platform/proc-aap-controller-restore.adoc
  downstream/modules/platform/proc-aap-controller-yaml-backup.adoc
  downstream/modules/platform/proc-aap-controller-yaml-restore.adoc
  downstream/modules/platform/proc-aap-hub-backup.adoc
  downstream/modules/platform/proc-aap-hub-restore.adoc
  downstream/modules/platform/proc-aap-platform-gateway-backup.adoc
  downstream/modules/platform/proc-aap-platform-gateway-restore.adoc
Labels: documentation, 2.5, AAP operator

#1634 AAP-27695 Add Ansible plug-in for RHDH Installation doc
  downstream/assemblies/devtools/assembly-rhdh-configure.adoc
  downstream/assemblies/devtools/assembly-rhdh-install-ocp.adoc
  downstream/assemblies/devtools/assembly-rhdh-install.adoc
  downstream/assemblies/devtools/assembly-rhdh-intro.adoc
  downstream/assemblies/devtools/assembly-rhdh-uninstall-ocp.adoc
  downstream/assemblies/devtools/assembly-rhdh-upgrade-ocp.adoc
  downstream/assemblies/devtools/assembly-rhdh-upgrading-uninstalling.adoc
  downstream/attributes/attributes.adoc
  downstream/images/rhdh-ansible-plugin-architecture.png
  downstream/images/rhdh-check-devtools-container.png
  downstream/images/rhdh-check-plugin-config.png
  downstream/images/rhdh-plugin-registry.png
  downstream/modules/devtools/proc-rhdh-add-additional-scm.adoc
  downstream/modules/devtools/proc-rhdh-add-devtools-container.adoc
  downstream/modules/devtools/proc-rhdh-add-plugin-config.adoc
  downstream/modules/devtools/proc-rhdh-add-plugin-software-templates.adoc
  downstream/modules/devtools/proc-rhdh-add-pull-secret-helm.adoc
  downstream/modules/devtools/proc-rhdh-configure-aap-details.adoc
  downstream/modules/devtools/proc-rhdh-configure-devspaces.adoc
  downstream/modules/devtools/proc-rhdh-configure-devtools-server.adoc
  downstream/modules/devtools/proc-rhdh-configure-optional-integrations.adoc
  downstream/modules/devtools/proc-rhdh-configure-pah-url.adoc
  downstream/modules/devtools/proc-rhdh-configure-rbac.adoc
  downstream/modules/devtools/proc-rhdh-configure-telemetry.adoc
  downstream/modules/devtools/proc-rhdh-create-plugin-registry.adoc
  downstream/modules/devtools/proc-rhdh-devtools-sidecar.adoc
  downstream/modules/devtools/proc-rhdh-download-plugins.adoc
  downstream/modules/devtools/proc-rhdh-enable-rhdh-authentication.adoc
  downstream/modules/devtools/proc-rhdh-uninstall-ocp.adoc
  downstream/modules/devtools/proc-rhdh-update-plugin-registry.adoc
  downstream/modules/devtools/proc-rhdh-update-plugins-version-numbers.adoc
  downstream/modules/devtools/proc-rhdh-warning-aap-ooc.adoc
  downstream/modules/devtools/proc-rhdh-warning-invalid-aap-config.adoc
  downstream/modules/devtools/proc-rhdh-warning-invalid-aap-subscription.adoc
  downstream/modules/devtools/proc-rhdh-warning-unable-authenticate-aap.adoc
  downstream/modules/devtools/proc-rhdh-warning-unable-connect-aap.adoc
  downstream/modules/devtools/ref-rhdh-about-plugins.adoc
  downstream/modules/devtools/ref-rhdh-about-rhdh.adoc
  downstream/modules/devtools/ref-rhdh-architecture.adoc
  downstream/modules/devtools/ref-rhdh-install-ocp-prereqs.adoc
  downstream/modules/devtools/ref-rhdh-plugin-subscription-warning.adoc
  downstream/titles/aap-plugin-rhdh-install/docinfo.xml
  downstream/titles/aap-plugin-rhdh-install/master.adoc
  downstream/titles/aap-plugin-rhdh-install/snippets
Labels: Needs backport to 2.4, 2.4, 2.5, Needs backport to 2.5

#1635 AAP-27696 Create Using Ansible Plug-ins guide
  downstream/assemblies/devtools/assembly-rhdh-example.adoc
  downstream/assemblies/devtools/assembly-rhdh-feedback.adoc
  downstream/assemblies/devtools/assembly-rhdh-using.adoc
  downstream/images/rhdh-feedback-form.png
  downstream/images/rhdh-plugin-dashboard.png
  downstream/images/rhdh-vscode-run-playbook.png
  downstream/modules/devtools/proc-rhdh-create.adoc
  downstream/modules/devtools/proc-rhdh-develop-projects-devspaces.adoc
  downstream/modules/devtools/proc-rhdh-develop-projects.adoc
  downstream/modules/devtools/proc-rhdh-execute-automation-devspaces.adoc
  downstream/modules/devtools/proc-rhdh-firewall-example-create-playbook.adoc
  downstream/modules/devtools/proc-rhdh-firewall-example-discover.adoc
  downstream/modules/devtools/proc-rhdh-firewall-example-edit.adoc
  downstream/modules/devtools/proc-rhdh-firewall-example-learn.adoc
  downstream/modules/devtools/proc-rhdh-firewall-example-new-playbook.adoc
  downstream/modules/devtools/proc-rhdh-set-up-controller-project.adoc
  downstream/modules/devtools/proc-rhdh-view.adoc
  downstream/modules/devtools/ref-rhdh-dashboard.adoc
  downstream/modules/devtools/ref-rhdh-discover-collections.adoc
  downstream/modules/devtools/ref-rhdh-learning.adoc
  downstream/titles/aap-plugin-rhdh-using/docinfo.xml
  downstream/titles/aap-plugin-rhdh-using/master.adoc
  downstream/titles/aap-plugin-rhdh-using/snippets
Labels: Needs backport to 2.4, 2.4, 2.5, Needs backport to 2.5

#1640 2.4 AAP-27695 Add Ansible plug-in for RHDH Installation doc (#1634)
  downstream/assemblies/devtools/assembly-rhdh-configure.adoc
  downstream/assemblies/devtools/assembly-rhdh-install-ocp.adoc
  downstream/assemblies/devtools/assembly-rhdh-install.adoc
  downstream/assemblies/devtools/assembly-rhdh-intro.adoc
  downstream/assemblies/devtools/assembly-rhdh-uninstall-ocp.adoc
  downstream/assemblies/devtools/assembly-rhdh-upgrade-ocp.adoc
  downstream/assemblies/devtools/assembly-rhdh-upgrading-uninstalling.adoc
  downstream/attributes/attributes.adoc
  downstream/images/rhdh-ansible-plugin-architecture.png
  downstream/images/rhdh-check-devtools-container.png
  downstream/images/rhdh-check-plugin-config.png
  downstream/images/rhdh-plugin-registry.png
  downstream/modules/devtools/proc-rhdh-add-additional-scm.adoc
  downstream/modules/devtools/proc-rhdh-add-devtools-container.adoc
  downstream/modules/devtools/proc-rhdh-add-plugin-config.adoc
  downstream/modules/devtools/proc-rhdh-add-plugin-software-templates.adoc
  downstream/modules/devtools/proc-rhdh-add-pull-secret-helm.adoc
  downstream/modules/devtools/proc-rhdh-configure-aap-details.adoc
  downstream/modules/devtools/proc-rhdh-configure-devspaces.adoc
  downstream/modules/devtools/proc-rhdh-configure-devtools-server.adoc
  downstream/modules/devtools/proc-rhdh-configure-optional-integrations.adoc
  downstream/modules/devtools/proc-rhdh-configure-pah-url.adoc
  downstream/modules/devtools/proc-rhdh-configure-rbac.adoc
  downstream/modules/devtools/proc-rhdh-configure-telemetry.adoc
  downstream/modules/devtools/proc-rhdh-create-plugin-registry.adoc
  downstream/modules/devtools/proc-rhdh-devtools-sidecar.adoc
  downstream/modules/devtools/proc-rhdh-download-plugins.adoc
  downstream/modules/devtools/proc-rhdh-enable-rhdh-authentication.adoc
  downstream/modules/devtools/proc-rhdh-uninstall-ocp.adoc
  downstream/modules/devtools/proc-rhdh-update-plugin-registry.adoc
  downstream/modules/devtools/proc-rhdh-update-plugins-version-numbers.adoc
  downstream/modules/devtools/proc-rhdh-warning-aap-ooc.adoc
  downstream/modules/devtools/proc-rhdh-warning-invalid-aap-config.adoc
  downstream/modules/devtools/proc-rhdh-warning-invalid-aap-subscription.adoc
  downstream/modules/devtools/proc-rhdh-warning-unable-authenticate-aap.adoc
  downstream/modules/devtools/proc-rhdh-warning-unable-connect-aap.adoc
  downstream/modules/devtools/ref-rhdh-about-plugins.adoc
  downstream/modules/devtools/ref-rhdh-about-rhdh.adoc
  downstream/modules/devtools/ref-rhdh-architecture.adoc
  downstream/modules/devtools/ref-rhdh-install-ocp-prereqs.adoc
  downstream/modules/devtools/ref-rhdh-plugin-subscription-warning.adoc
  downstream/titles/aap-plugin-rhdh-install/docinfo.xml
  downstream/titles/aap-plugin-rhdh-install/master.adoc
  downstream/titles/aap-plugin-rhdh-install/snippets
Labels: 2.4

#1639 Update tech preview notice per supplementary style guide
  downstream/snippets/technology-preview.adoc
Labels: Needs backport to 2.4, snippets, 2.4, 2.5, Needs backport to 2.5

#1642 2.4 Update tech preview notice per supplementary style guide (#1639)
  downstream/snippets/technology-preview.adoc
Labels: snippets

#1643 2.5 Update tech preview notice per supplementary style guide (#1639)
  downstream/snippets/technology-preview.adoc
Labels: snippets

#1632 updating UI change
  downstream/modules/platform/con-ocp-supported-install.adoc
  downstream/modules/platform/proc-aap-platform-gateway-backup.adoc
  downstream/modules/platform/proc-aap-platform-gateway-restore.adoc
  downstream/modules/platform/proc-operator-aap-faq.adoc
  downstream/modules/platform/proc-operator-access-aap.adoc
  downstream/modules/platform/proc-operator-deploy-central-config.adoc
  downstream/modules/platform/proc-operator-link-components.adoc
Labels: documentation, 2.5, AAP operator

#1613 Updating module on creating an inventory
  downstream/modules/platform/proc-controller-adding-new-inventory.adoc
Labels: documentation, Controller, 2.5, Needs backport to 2.5

#1646 Updating module on creating an inventory (#1613)
  downstream/modules/platform/proc-controller-adding-new-inventory.adoc
Labels: 2.5, Backported to 2.5

#1644 updating UI change (#1632)
  downstream/modules/platform/con-ocp-supported-install.adoc
  downstream/modules/platform/proc-aap-platform-gateway-backup.adoc
  downstream/modules/platform/proc-aap-platform-gateway-restore.adoc
  downstream/modules/platform/proc-operator-aap-faq.adoc
  downstream/modules/platform/proc-operator-access-aap.adoc
  downstream/modules/platform/proc-operator-deploy-central-config.adoc
  downstream/modules/platform/proc-operator-link-components.adoc
Labels: documentation, 2.5, AAP operator

#1633 AAP-25614 Deprecate chapter on setting up controller tokens in EDA controller user guide
  downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc
  downstream/titles/eda/eda-user-guide/master.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#1604 AAP-20549 - Implementing gateway UI changes into the Operations guide
  downstream/aap-common/external-site-disclaimer.adoc
  downstream/assemblies/platform/assembly-platform-whats-next.adoc
  downstream/modules/platform/con-known-proxies.adoc
  downstream/modules/platform/con-sticky-sessions.adoc
  downstream/modules/platform/con-why-automation-mesh.adoc
  downstream/modules/platform/proc-aap-activate-with-credentials.adoc
  downstream/modules/platform/proc-aap-activate-with-manifest.adoc
  downstream/modules/platform/proc-configure-known-proxies.adoc
  downstream/modules/platform/proc-configuring-reverse-proxy.adoc
  downstream/modules/platform/proc-control-data-collection.adoc
  downstream/modules/platform/proc-enable-proxy-support.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#1647 AAP-19236 - Adding new modules for gateway access management
  downstream/modules/platform/con-gw-managing-access.adoc
  downstream/modules/platform/proc-gw-add-admin-organization.adoc
  downstream/modules/platform/proc-gw-add-admin-team.adoc
  downstream/modules/platform/proc-gw-add-team-organization.adoc
  downstream/modules/platform/proc-gw-delete-organization.adoc
  downstream/modules/platform/proc-gw-delete-team.adoc
  downstream/modules/platform/proc-gw-organizations-exec-env.adoc
  downstream/modules/platform/proc-gw-remove-roles-team.adoc
  downstream/modules/platform/proc-gw-remove-roles-user.adoc
  downstream/modules/platform/proc-gw-team-access-resources.adoc
  downstream/modules/platform/proc-gw-team-add-user.adoc
  downstream/modules/platform/proc-gw-team-list-view.adoc
  downstream/modules/platform/proc-gw-team-remove-user.adoc
  downstream/modules/platform/proc-gw-user-access-resources.adoc
  downstream/modules/platform/proc-gw-users-list-view.adoc
  downstream/snippets/snip-gw-roles-note-multiple-components.adoc
Labels: Ready for review, snippets, 2.5, Needs backport to 2.5

#1651 Amended note on facts and host filters
  downstream/modules/platform/proc-controller-define-filter-with-facts.adoc
Labels: documentation, Controller, 2.4

#1654 [Backport] AAP-19236 - Adding new modules for gateway access management (#1647)
  downstream/modules/platform/con-gw-managing-access.adoc
  downstream/modules/platform/proc-gw-add-admin-organization.adoc
  downstream/modules/platform/proc-gw-add-admin-team.adoc
  downstream/modules/platform/proc-gw-add-team-organization.adoc
  downstream/modules/platform/proc-gw-delete-organization.adoc
  downstream/modules/platform/proc-gw-delete-team.adoc
  downstream/modules/platform/proc-gw-organizations-exec-env.adoc
  downstream/modules/platform/proc-gw-remove-roles-team.adoc
  downstream/modules/platform/proc-gw-remove-roles-user.adoc
  downstream/modules/platform/proc-gw-team-access-resources.adoc
  downstream/modules/platform/proc-gw-team-add-user.adoc
  downstream/modules/platform/proc-gw-team-list-view.adoc
  downstream/modules/platform/proc-gw-team-remove-user.adoc
  downstream/modules/platform/proc-gw-user-access-resources.adoc
  downstream/modules/platform/proc-gw-users-list-view.adoc
  downstream/snippets/snip-gw-roles-note-multiple-components.adoc
Labels: Ready for review, 2.5

#1655 [Backport] AAP-20549 - Implementing gateway UI changes into the Operations guide (#1604)
  downstream/aap-common/external-site-disclaimer.adoc
  downstream/assemblies/platform/assembly-platform-whats-next.adoc
  downstream/modules/platform/con-known-proxies.adoc
  downstream/modules/platform/con-sticky-sessions.adoc
  downstream/modules/platform/con-why-automation-mesh.adoc
  downstream/modules/platform/proc-aap-activate-with-credentials.adoc
  downstream/modules/platform/proc-aap-activate-with-manifest.adoc
  downstream/modules/platform/proc-configure-known-proxies.adoc
  downstream/modules/platform/proc-configuring-reverse-proxy.adoc
  downstream/modules/platform/proc-control-data-collection.adoc
  downstream/modules/platform/proc-enable-proxy-support.adoc
Labels: Ready for review, 2.5

#1656 Correct attributes that don't resolve in code blocks
  downstream/modules/platform/ref-gateway-controller-hub-eda-ext-db.adoc
  downstream/modules/platform/ref-single-controller-hub-eda-with-managed-db.adoc
Labels: Needs backport to 2.4, Needs backport to 2.5

#1657 2.5 Correct attributes that don't resolve in code blocks (#1656)
  downstream/modules/platform/ref-gateway-controller-hub-eda-ext-db.adoc
  downstream/modules/platform/ref-single-controller-hub-eda-with-managed-db.adoc
Labels: 2.5

#1658 2.4 Correct attributes that don't resolve in code blocks (#1656)
  downstream/modules/platform/ref-single-controller-hub-eda-with-managed-db.adoc
Labels: 2.4

#1659 [DocX] Updating the UI steps of the EDA Chapter of the deploy guide
  downstream/modules/platform/proc-deploy-eda-controller-with-aap-operator-ocp.adoc
Labels: documentation, 2.4, 2.5, AAP operator

#1660 Updating the EDA section of the deploy guide (#1659)
  downstream/modules/platform/proc-deploy-eda-controller-with-aap-operator-ocp.adoc
Labels: documentation, Ready for review, 2.5, AAP operator

#1661 Updating the EDA section of the deploy guide (#1659)
  downstream/modules/platform/proc-deploy-eda-controller-with-aap-operator-ocp.adoc
Labels: documentation, Ready for review, 2.4, AAP operator

#1653 AAP-19236 - Add assemblies for Access Management and peer review changes for modules from 1647
  downstream/assemblies/platform/assembly-controller-organizations.adoc
  downstream/assemblies/platform/assembly-controller-teams.adoc
  downstream/assemblies/platform/assembly-controller-users.adoc
  downstream/assemblies/platform/assembly-gw-resources.adoc
  downstream/modules/platform/proc-gw-organizations-exec-env.adoc
  downstream/modules/platform/proc-gw-team-access-resources.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5
