Repository ansible/aap-docs, pull requests merged in 2024-11, with the labels that each got.

#2501 Updating path for REST api
  downstream/modules/platform/proc-controller-api-browsing-api.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4, 2.5, Needs backport to 2.5

#2505 AAP-34778 Crowdsource Minimalism suggestions
  stories/assembly-saas-intro.adoc
  stories/assembly-saas-post-install-config.adoc
  stories/assembly-saas-pull-push.adoc
  stories/assembly-saas-set-up.adoc
  stories/assembly-saas-subscribing.adoc
  stories/topics/con-saas-backup-and-diaster-recovery.adoc
  stories/topics/con-saas-identity-and-access-management.adoc
  stories/topics/con-saas-intro.adoc
  stories/topics/con-saas-provisioning.adoc
  stories/topics/proc-saas-set-up-private.adoc
  stories/topics/proc-saas-set-up-public.adoc
  stories/topics/ref-saas-egress-model.adoc
  stories/topics/ref-saas-mesh-ingress-model.adoc
  titles/saas-aws/stories.adoc
Labels: AAP on clouds, Ansible on AWS

#2506 Updating path for REST api (#2501)
  downstream/modules/platform/proc-controller-api-browsing-api.adoc
Labels: documentation, Controller, 2.5, Backported to 2.5

#2507 Updating path for REST api (#2501)
  downstream/modules/platform/proc-controller-api-browsing-api.adoc
Labels: documentation, Backported to 2.4, Controller, 2.4

#2497 aap-33475 2.5 specific edits
  downstream/assemblies/platform/assembly-using-rhsso-operator-with-automation-hub.adoc
  downstream/modules/platform/proc-creating-a-secret.adoc
  downstream/modules/platform/proc-operator-deploy-central-config.adoc
  downstream/modules/platform/proc-operator-link-components.adoc
Labels: 2.5, AAP operator, Needs backport to 2.5

#2508 aap-33475 2.5 specific edits (#2497)
  downstream/assemblies/platform/assembly-using-rhsso-operator-with-automation-hub.adoc
  downstream/modules/platform/proc-creating-a-secret.adoc
  downstream/modules/platform/proc-operator-deploy-central-config.adoc
  downstream/modules/platform/proc-operator-link-components.adoc
Labels: 2.5, AAP operator

#2509 Applying updates from AAP-35076
  downstream/assemblies/platform/assembly-using-rhsso-operator-with-automation-hub.adoc
  downstream/modules/platform/proc-operator-create_crs.adoc
  downstream/modules/platform/ref-operator-crs.adoc
Labels: 2.5, AAP operator

#2511 AAP-35119 updated overview to tested topologies
  downstream/assemblies/topologies/assembly-overview-tested-deployment-models.adoc
Labels: Ready for technical review, 2.5, Needs backport to 2.5

#2516 Add troubleshooting info for execution environments
  downstream/modules/platform/ref-containerized-troubleshoot-ref.adoc
Labels: 2.5, Needs backport to 2.5, Containerized AAP

#2517 AAP-35120 updated architecture introduction (#2510)
  downstream/assemblies/platform/assembly-aap-architecture.adoc
Labels: Ready for review, 2.5

#2518 AAP-35119 updated overview to tested topologies (#2511)
  downstream/assemblies/topologies/assembly-overview-tested-deployment-models.adoc
Labels: Ready for review, 2.5

#2519 2.5 Add troubleshooting info for execution environments (#2516)
  downstream/modules/platform/ref-containerized-troubleshoot-ref.adoc
Labels: 2.5, Containerized AAP

#2520 Applying updates from AAP-35076 (#2509)
  downstream/assemblies/platform/assembly-using-rhsso-operator-with-automation-hub.adoc
  downstream/modules/platform/proc-operator-create_crs.adoc
  downstream/modules/platform/ref-operator-crs.adoc
Labels: 2.5, AAP operator

#2521 adding in missing brackets
  downstream/modules/platform/proc-operator-create_crs.adoc
Labels: 2.5, AAP operator, Backported to 2.5

#2522 Clouds - Add attributes for current AAP version on Azure
  attributes/attributes.adoc
  stories/topics/con-azure-about.adoc
Labels: AAP on clouds, AAP on Azure

#2524 Adding in Priya's comments
  stories/assembly-saas-intro.adoc
  stories/assembly-saas-post-install-config.adoc
  stories/assembly-saas-pull-push.adoc
  stories/topics/con-saas-automation-mesh.adoc
  stories/topics/con-saas-deployment-self-service.adoc
  stories/topics/con-saas-execution-plane.adoc
  stories/topics/con-saas-networking-with-overlapping-CIDR-blocks.adoc
  stories/topics/con-saas-regions.adoc
  stories/topics/con-saas-shape.adoc
  stories/topics/con-saas-sre-access-and-management.adoc
  titles/saas-aws/docinfo.xml
Labels: AAP on clouds, Ansible on AWS

#2527 Added deprecation note for receptor. (#2512)
  downstream/titles/release-notes/topics/aap-25-deprecated-features.adoc
Labels: AAP Release notes, 2.5

#2373 Clouds - update attributes and boilerplate text
  aap-common/boilerplate.adoc
  attributes/attributes.adoc
  titles/aap-on-azure/stories.adoc
  titles/saas-aws/stories.adoc
Labels: AAP on clouds, AAP on Azure, SaaS on AWS

#2529 Clouds - add Azure and SaaS attributes to clouds attributes
  attributes/attributes.adoc
Labels: AAP on clouds, Attributes

#2531 2.5 Add attributes for Clouds docs (#2528)
  downstream/attributes/attributes.adoc
Labels: Attributes, 2.5

#2530 2.4 Add attributes for Clouds docs (#2528)
  downstream/attributes/attributes.adoc
Labels: Attributes, 2.4

#2532 Clouds: Update SaaS title attributes
  attributes/attributes.adoc
Labels: AAP on clouds, Attributes

#2533 Update SaaS title attributes in downstream docs
  downstream/attributes/attributes.adoc
Labels: Backported to 2.4, Attributes, Backported to 2.5

#2534 2.4 Update SaaS title attributes in downstream docs (#2533)
  downstream/attributes/attributes.adoc
Labels: Attributes, 2.4

#2535 2.5 Update SaaS title attributes in downstream docs (#2533)
  downstream/attributes/attributes.adoc
Labels: Attributes, 2.5

#2536 Clouds - update title-attribute file for SaaS doc
  titles/saas-aws/title-attributes.adoc
Labels: AAP on clouds, Attributes, SaaS on AWS

#2224 AAP-32141a Updates to RHDH Install doc
  downstream/assemblies/devtools/assembly-rhdh-install-ocp-helm.adoc
  downstream/assemblies/devtools/assembly-rhdh-install-ocp-operator.adoc
  downstream/assemblies/devtools/assembly-rhdh-ocp-configure-optional.adoc
  downstream/assemblies/devtools/assembly-rhdh-subscription-warnings.adoc
  downstream/assemblies/devtools/assembly-rhdh-uninstall-ocp-helm.adoc
  downstream/assemblies/devtools/assembly-rhdh-uninstall-ocp-operator.adoc
  downstream/assemblies/devtools/assembly-rhdh-uninstall-ocp.adoc
  downstream/assemblies/devtools/assembly-rhdh-uninstall.adoc
  downstream/assemblies/devtools/assembly-rhdh-upgrade-ocp-helm.adoc
  downstream/assemblies/devtools/assembly-rhdh-upgrade-ocp-operator.adoc
  downstream/assemblies/devtools/assembly-rhdh-upgrade-ocp.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/devtools/con-rhdh-install-ocp-prereqs.adoc
  downstream/modules/devtools/con-rhdh-recommended-preconfig.adoc
  downstream/modules/devtools/proc-rhdh-add-plugin-config.adoc
  downstream/modules/devtools/proc-rhdh-configure-devspaces.adoc
  downstream/modules/devtools/proc-rhdh-configure-optional-integrations.adoc
  downstream/modules/devtools/proc-rhdh-create-custom-configmap-operator-install.adoc
  downstream/modules/devtools/proc-rhdh-create-plugin-registry.adoc
  downstream/modules/devtools/proc-rhdh-download-plugins.adoc
  downstream/modules/devtools/proc-rhdh-install-dynamic-plugins-operator.adoc
  downstream/modules/devtools/proc-rhdh-operator-add-custom-configmap-cr.adoc
  downstream/modules/devtools/proc-rhdh-operator-install-add-plugins-app-config.adoc
  downstream/modules/devtools/proc-rhdh-uninstall-ocp-helm.adoc
  downstream/modules/devtools/proc-rhdh-uninstall-ocp-operator-plugins-cm.adoc
  downstream/modules/devtools/proc-rhdh-uninstall-ocp-operator-rhdh-cm.adoc
  downstream/modules/devtools/proc-rhdh-uninstall-ocp-operator-sidecar.adoc
  downstream/modules/devtools/proc-rhdh-uninstall-ocp-operator.adoc
  downstream/modules/devtools/proc-rhdh-uninstall-ocp-remove-sidecar-cr.adoc
  downstream/modules/devtools/proc-rhdh-update-plugin-registry.adoc
  downstream/modules/devtools/proc-rhdh-update-plugins-helm-version-numbers.adoc
  downstream/modules/devtools/proc-rhdh-update-plugins-operator-version-numbers.adoc
  downstream/modules/devtools/ref-rhdh-install-ocp-prereqs.adoc
  downstream/titles/aap-plugin-rhdh-install/master.adoc
Labels: Draft, 2.5, Needs backport to 2.5

#2539 AAP-32141 Add Installing on Operator chapter to RHDH install guide (#2149) (#2224)
  downstream/assemblies/devtools/assembly-rhdh-install-ocp-helm.adoc
  downstream/assemblies/devtools/assembly-rhdh-install-ocp-operator.adoc
  downstream/assemblies/devtools/assembly-rhdh-ocp-configure-optional.adoc
  downstream/assemblies/devtools/assembly-rhdh-subscription-warnings.adoc
  downstream/assemblies/devtools/assembly-rhdh-uninstall-ocp-helm.adoc
  downstream/assemblies/devtools/assembly-rhdh-uninstall-ocp-operator.adoc
  downstream/assemblies/devtools/assembly-rhdh-uninstall-ocp.adoc
  downstream/assemblies/devtools/assembly-rhdh-uninstall.adoc
  downstream/assemblies/devtools/assembly-rhdh-upgrade-ocp-helm.adoc
  downstream/assemblies/devtools/assembly-rhdh-upgrade-ocp-operator.adoc
  downstream/assemblies/devtools/assembly-rhdh-upgrade-ocp.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/devtools/con-rhdh-install-ocp-prereqs.adoc
  downstream/modules/devtools/con-rhdh-recommended-preconfig.adoc
  downstream/modules/devtools/proc-rhdh-add-plugin-config.adoc
  downstream/modules/devtools/proc-rhdh-backup-operator-configmap.adoc
  downstream/modules/devtools/proc-rhdh-configure-aap-details.adoc
  downstream/modules/devtools/proc-rhdh-configure-devspaces.adoc
  downstream/modules/devtools/proc-rhdh-configure-optional-integrations.adoc
  downstream/modules/devtools/proc-rhdh-create-custom-configmap-operator-install.adoc
  downstream/modules/devtools/proc-rhdh-create-plugin-registry.adoc
  downstream/modules/devtools/proc-rhdh-download-plugins.adoc
  downstream/modules/devtools/proc-rhdh-install-dynamic-plugins-operator.adoc
  downstream/modules/devtools/proc-rhdh-operator-add-custom-configmap-cr.adoc
  downstream/modules/devtools/proc-rhdh-operator-install-add-plugins-app-config.adoc
  downstream/modules/devtools/proc-rhdh-uninstall-ocp-helm.adoc
  downstream/modules/devtools/proc-rhdh-uninstall-ocp-operator-plugins-cm.adoc
  downstream/modules/devtools/proc-rhdh-uninstall-ocp-operator-rhdh-cm.adoc
  downstream/modules/devtools/proc-rhdh-uninstall-ocp-operator-sidecar.adoc
  downstream/modules/devtools/proc-rhdh-uninstall-ocp-operator.adoc
  downstream/modules/devtools/proc-rhdh-uninstall-ocp-remove-sidecar-cr.adoc
  downstream/modules/devtools/proc-rhdh-update-plugin-registry.adoc
  downstream/modules/devtools/proc-rhdh-update-plugins-helm-version-numbers.adoc
  downstream/modules/devtools/proc-rhdh-update-plugins-operator-version-numbers.adoc
  downstream/modules/devtools/ref-rhdh-install-ocp-prereqs.adoc
  downstream/titles/aap-plugin-rhdh-install/master.adoc
Labels: 2.5

#2538 Adding Red Hat to saas title
  attributes/attributes.adoc
  titles/saas-aws/docinfo.xml
  titles/saas-aws/master.adoc
  titles/saas-aws/title-attributes.adoc
Labels: AAP on clouds, Ansible on AWS

#2540 Add Red Hat to SaaS title attribute
  downstream/attributes/attributes.adoc
Labels: 2.5, Needs backport to 2.5

#2542 Add Red Hat to SaaS title attribute (#2540)
  downstream/attributes/attributes.adoc
Labels: 2.5

#2537 AAP-33062 - add more details for LDAP Group types
  downstream/modules/platform/proc-controller-set-up-LDAP.adoc
Labels: 2.5, Needs backport to 2.5

#2543 Backport 2149 2224 2.4
  downstream/assemblies/devtools/assembly-rhdh-install-ocp-helm.adoc
  downstream/assemblies/devtools/assembly-rhdh-install-ocp-operator.adoc
  downstream/assemblies/devtools/assembly-rhdh-ocp-configure-optional.adoc
  downstream/assemblies/devtools/assembly-rhdh-subscription-warnings.adoc
  downstream/assemblies/devtools/assembly-rhdh-uninstall-ocp-helm.adoc
  downstream/assemblies/devtools/assembly-rhdh-uninstall-ocp-operator.adoc
  downstream/assemblies/devtools/assembly-rhdh-uninstall-ocp.adoc
  downstream/assemblies/devtools/assembly-rhdh-uninstall.adoc
  downstream/assemblies/devtools/assembly-rhdh-upgrade-ocp-helm.adoc
  downstream/assemblies/devtools/assembly-rhdh-upgrade-ocp-operator.adoc
  downstream/assemblies/devtools/assembly-rhdh-upgrade-ocp.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/devtools/con-rhdh-install-ocp-prereqs.adoc
  downstream/modules/devtools/con-rhdh-recommended-preconfig.adoc
  downstream/modules/devtools/proc-rhdh-add-plugin-config.adoc
  downstream/modules/devtools/proc-rhdh-backup-operator-configmap.adoc
  downstream/modules/devtools/proc-rhdh-configure-aap-details.adoc
  downstream/modules/devtools/proc-rhdh-configure-devspaces.adoc
  downstream/modules/devtools/proc-rhdh-configure-optional-integrations.adoc
  downstream/modules/devtools/proc-rhdh-create-custom-configmap-operator-install.adoc
  downstream/modules/devtools/proc-rhdh-create-plugin-registry.adoc
  downstream/modules/devtools/proc-rhdh-download-plugins.adoc
  downstream/modules/devtools/proc-rhdh-install-dynamic-plugins-operator.adoc
  downstream/modules/devtools/proc-rhdh-operator-add-custom-configmap-cr.adoc
  downstream/modules/devtools/proc-rhdh-operator-install-add-plugins-app-config.adoc
  downstream/modules/devtools/proc-rhdh-uninstall-ocp-helm.adoc
  downstream/modules/devtools/proc-rhdh-uninstall-ocp-operator-plugins-cm.adoc
  downstream/modules/devtools/proc-rhdh-uninstall-ocp-operator-rhdh-cm.adoc
  downstream/modules/devtools/proc-rhdh-uninstall-ocp-operator-sidecar.adoc
  downstream/modules/devtools/proc-rhdh-uninstall-ocp-operator.adoc
  downstream/modules/devtools/proc-rhdh-uninstall-ocp-remove-sidecar-cr.adoc
  downstream/modules/devtools/proc-rhdh-update-plugin-registry.adoc
  downstream/modules/devtools/proc-rhdh-update-plugins-helm-version-numbers.adoc
  downstream/modules/devtools/proc-rhdh-update-plugins-operator-version-numbers.adoc
  downstream/modules/devtools/ref-rhdh-install-ocp-prereqs.adoc
  downstream/titles/aap-plugin-rhdh-install/master.adoc
Labels: 2.4

#2544 [Backport] AAP-33062 - add more details for LDAP Group types (#2537)
  downstream/modules/platform/proc-controller-set-up-LDAP.adoc
Labels: Ready for review, 2.5

#2545 Fix link in RPM upgrade guide
  downstream/modules/platform/proc-running-setup-script-for-updates.adoc
Labels: 2.5, Needs backport to 2.5

#2546 Fix link in RPM upgrade guide (#2545)
  downstream/modules/platform/proc-running-setup-script-for-updates.adoc
Labels: 2.5

#2547 Updated Satellite version
  downstream/attributes/attributes.adoc
Labels: 2.5, Needs backport to 2.5

#2548 Updated Satellite version (#2547)
  downstream/attributes/attributes.adoc
Labels: 2.5, Backported to 2.5

#2523 Updating "pods/log" resource
  downstream/modules/platform/proc-controller-create-container-group.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.5, Needs backport to 2.5

#2549 Add port 27199 to CONT-A-ENV-A in Supported deployment models
  downstream/modules/topologies/ref-cont-a-env-a.adoc
Labels: 2.5, Needs backport to 2.5

#2550 2.5 Add port 27199 to CONT-A-ENV-A in Supported deployment models (#2549)
  downstream/modules/topologies/ref-cont-a-env-a.adoc
Labels: 2.5

#2552 Updating "pods/log" resource (#2523)
  downstream/modules/platform/proc-controller-create-container-group.adoc
Labels: documentation, Backported to 2.4, Controller, 2.4

#2557 Added note about receptor not listening (#2514)
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
  downstream/modules/platform/proc-define-mesh-node-types.adoc
Labels: 2.5, Backported to 2.5

#2558 Added note about receptor not listening (#2514)
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
  downstream/modules/platform/proc-define-mesh-node-types.adoc
Labels: Backported to 2.4, 2.4

#2559 Add missing receptor vars to inventory appendix
  downstream/modules/platform/ref-ansible-inventory-variables.adoc
  downstream/modules/platform/ref-controller-variables.adoc
  downstream/modules/platform/ref-database-inventory-variables.adoc
  downstream/modules/platform/ref-receptor-inventory-variables.adoc
Labels: 2.5, Needs backport to 2.5

#2560 2.5 Add missing receptor vars to inventory appendix (#2559)
  downstream/modules/platform/ref-ansible-inventory-variables.adoc
  downstream/modules/platform/ref-controller-variables.adoc
  downstream/modules/platform/ref-database-inventory-variables.adoc
  downstream/modules/platform/ref-receptor-inventory-variables.adoc
Labels: 2.5

#2554 AAP 32543 Clouds - Add Service uptime section in SaaS
  attributes/attributes.adoc
  stories/assembly-saas-intro.adoc
  stories/assembly-saas-pull-push.adoc
  stories/topics/con-saas-automation.adoc
  stories/topics/con-saas-backup-and-diaster-recovery.adoc
  stories/topics/con-saas-control-plane.adoc
  stories/topics/con-saas-deployment-self-service.adoc
  stories/topics/con-saas-hosted-components.adoc
  stories/topics/con-saas-identity-and-access-management.adoc
  stories/topics/con-saas-service-uptime.adoc
Labels: AAP on clouds, SaaS on AWS

#2553 AAP-32543 Clarify options in mesh node types definition
  downstream/attributes/attributes.adoc
  downstream/modules/platform/proc-define-mesh-node-types.adoc
Labels: 2.5, Needs backport to 2.5

#2562 2.5 AAP-32543 Clarify options in mesh node types definition (#2553)
  downstream/attributes/attributes.adoc
  downstream/modules/platform/proc-define-mesh-node-types.adoc
Labels: 2.5

#2561 AAP-34041 plug-ins: view container logs on OCP UI
  downstream/modules/devtools/proc-rhdh-add-plugin-config.adoc
  downstream/modules/devtools/proc-rhdh-create-plugin-registry.adoc
Labels: Ready for review, Needs backport to 2.4, 2.4, 2.5, Needs backport to 2.5

#2564 2.5 AAP-34041 plug-ins: view container logs on OCP UI (#2561)
  downstream/modules/devtools/proc-rhdh-add-plugin-config.adoc
  downstream/modules/devtools/proc-rhdh-create-plugin-registry.adoc
Labels: 2.5

#2565 2.4 AAP-34041 plug-ins: view container logs on OCP UI (#2561)
  downstream/modules/devtools/proc-rhdh-add-plugin-config.adoc
  downstream/modules/devtools/proc-rhdh-create-plugin-registry.adoc
Labels: 2.4

#2566 AAP-15176: fixes broken link in Configuring automation execution guide
  downstream/modules/platform/proc-controller-cluster-deprovision-instances.adoc
Labels: 2.5, Needs backport to 2.5

#2567 backport to 2.5: AAP-15176 fixes broken link in Configuring automation execution guide (#2566)
  downstream/modules/platform/proc-controller-cluster-deprovision-instances.adoc
Labels: 2.5

#2563 Updating awx commands to gateway
  downstream/assemblies/platform/assembly-gw-token-based-authentication.adoc
  downstream/modules/platform/ref-controller-create-oauth2-token.adoc
  downstream/modules/platform/ref-controller-revoke-oauth2-token.adoc
  downstream/modules/platform/ref-controller-token-session-management.adoc
Labels: documentation, Technical review complete, 2.5, Needs backport to 2.5

#2568 Updating awx commands to gateway (#2563)
  downstream/assemblies/platform/assembly-gw-token-based-authentication.adoc
  downstream/modules/platform/ref-controller-create-oauth2-token.adoc
  downstream/modules/platform/ref-controller-revoke-oauth2-token.adoc
  downstream/modules/platform/ref-controller-token-session-management.adoc
Labels: documentation, 2.5, Backported to 2.5

#2569 AAP-35811 Azure doc cleanup before 2.5 work starts
  stories/assembly-azure-connecting-to-aap.adoc
  stories/topics/con-azure-about.adoc
  stories/topics/proc-azure-nw-private-deploy.adoc
  titles/aap-on-azure/docinfo.xml
  titles/aap-on-azure/master.adoc
  titles/aap-on-azure/title-attributes.adoc
Labels: AAP on clouds, AAP on Azure

#2571 2.5 Add shared storage info to Containerized installation (#2570)
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/platform/ref-hub-variables.adoc
Labels: 2.5

#2572 AAP-29301 Azure - update pod CIDR requirements
  stories/topics/con-azure-aks-cidr.adoc
Labels: AAP on clouds, AAP on Azure

#2573 AAP-29301a Azure - Fix pod service case
  stories/topics/con-azure-aks-cidr.adoc
Labels: AAP on clouds, AAP on Azure

#2574 AAP-35099: adds info for token management with PAH and keycloak
  downstream/assemblies/hub/assembly-hub-create-api-token.adoc
Labels: Automation Hub, 2.5, Needs backport to 2.5

#2575 Backport to 2.5: AAP-35099: adds info for token management with PAH and keycloak (#2574)
  downstream/assemblies/hub/assembly-hub-create-api-token.adoc
Labels: Automation Hub, 2.5

#2576 Backport to 2.4: AAP-35099: adds info for token management with PAH and keycloak (#2574)
  downstream/assemblies/hub/assembly-hub-create-api-token.adoc
Labels: Automation Hub, 2.4

#2577 AAP-35863 Clarifying hop nodes bullet
  stories/topics/con-saas-shape.adoc
Labels: AAP on clouds, Ansible on AWS

#2580 AAP-33304: Document case-sensitivity of authenticator map group triggers (#2579)
  downstream/modules/platform/con-gw-authenticator-map-triggers.adoc
Labels: 2.5

#2583 Editing sample service account details
  downstream/modules/platform/proc-controller-credential-create-openshift-account.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4, 2.5, Needs backport to 2.5

#2584 Revision of hardening guide (#2526)
  downstream/assemblies/aap-hardening/assembly-aap-security-enabling.adoc
  downstream/assemblies/aap-hardening/assembly-aap-security-use-cases.adoc
  downstream/assemblies/aap-hardening/assembly-hardening-aap.adoc
  downstream/assemblies/aap-hardening/assembly-intro-to-aap-hardening.adoc
  downstream/images/workflow.png
  downstream/modules/aap-hardening/.platform
  downstream/modules/aap-hardening/con-aap-additional-software.adoc
  downstream/modules/aap-hardening/con-benefits-of-patch-automation.adoc
  downstream/modules/aap-hardening/con-credential-management-planning.adoc
  downstream/modules/aap-hardening/con-day-two-operations.adoc
  downstream/modules/aap-hardening/con-deployment-methods.adoc
  downstream/modules/aap-hardening/con-install-secure-host.adoc
  downstream/modules/aap-hardening/con-installation.adoc
  downstream/modules/aap-hardening/con-logging-log-capture.adoc
  downstream/modules/aap-hardening/con-network-firewall-services-planning.adoc
  downstream/modules/aap-hardening/con-patch-automation-with-aap.adoc
  downstream/modules/aap-hardening/con-patching-examples.adoc
  downstream/modules/aap-hardening/con-planning-considerations.adoc
  downstream/modules/aap-hardening/con-platform-components.adoc
  downstream/modules/aap-hardening/con-product-overview.adoc
  downstream/modules/aap-hardening/con-rbac.adoc
  downstream/modules/aap-hardening/con-rhel-host-planning.adoc
  downstream/modules/aap-hardening/con-security-operations-center.adoc
  downstream/modules/aap-hardening/con-user-authentication-planning.adoc
  downstream/modules/aap-hardening/platform
  downstream/modules/aap-hardening/proc-configure-centralized-logging.adoc
  downstream/modules/aap-hardening/proc-configure-external-authentication.adoc
  downstream/modules/aap-hardening/proc-install-user-pki.adoc
  downstream/modules/aap-hardening/ref-aap-authentication.adoc
  downstream/modules/aap-hardening/ref-aap-operational-secrets.adoc
  downstream/modules/aap-hardening/ref-architecture.adoc
  downstream/modules/aap-hardening/ref-automation-controller-authentication.adoc
  downstream/modules/aap-hardening/ref-complex-patching-scenarios.adoc
  downstream/modules/aap-hardening/ref-dns-load-balancing.adoc
  downstream/modules/aap-hardening/ref-dns.adoc
  downstream/modules/aap-hardening/ref-infrastructure-as-code.adoc
  downstream/modules/aap-hardening/ref-initial-configuration.adoc
  downstream/modules/aap-hardening/ref-install-security-updates.adoc
  downstream/modules/aap-hardening/ref-keep-up-to-date.adoc
  downstream/modules/aap-hardening/ref-security-variables-install-inventory.adoc
  downstream/modules/aap-hardening/ref-sensitive-variables-install-inventory.adoc
  downstream/modules/aap-hardening/ref-specify-package-versions.adoc
  downstream/modules/platform/proc-controller-set-up-logging.adoc
  downstream/titles/aap-hardening/master.adoc
  downstream/titles/aap-hardening/platform
Labels: 2.5, Backported to 2.5

#2585 Editing sample service account details (#2583)
  downstream/modules/platform/proc-controller-credential-create-openshift-account.adoc
Labels: documentation, Controller, 2.5, Backported to 2.5

#2586 Editing sample service account details (#2583)
  downstream/modules/platform/proc-controller-credential-create-openshift-account.adoc
Labels: documentation, Backported to 2.4, Controller, 2.4

#2587 AAP-35957 updating Azure AD references to Microsoft Entra ID
  stories/topics/proc-azure-configure-ad-sso.adoc
Labels: AAP on clouds, AAP on Azure

#2590 Add container troubleshooting info
  downstream/assemblies/platform/assembly-appendix-troubleshoot-containerized-aap.adoc
  downstream/modules/platform/ref-containerized-troubleshoot-diagnosing.adoc
Labels: 2.5, Needs backport to 2.5

#2591 2.5 Add container troubleshooting info (#2590)
  downstream/assemblies/platform/assembly-appendix-troubleshoot-containerized-aap.adoc
  downstream/modules/platform/ref-containerized-troubleshoot-diagnosing.adoc
Labels: 2.5

#2592 Add mTLS configuration for external databases
  downstream/modules/platform/proc-setup-postgresql-ext-database.adoc
Labels: 2.5, Needs backport to 2.5

#2593 2.5 Add mTLS configuration for external databases (#2592)
  downstream/modules/platform/proc-setup-postgresql-ext-database.adoc
Labels: 2.5

#2595 Add release notes for async-2.5-4
  downstream/titles/release-notes/async/aap-25-4-18-nov.adoc
  downstream/titles/release-notes/master.adoc
Labels: AAP Release notes, 2.5, Needs backport to 2.5

#2596 2.5 Add release notes for async-2.5-4 (#2595)
  downstream/titles/release-notes/async/aap-25-4-18-nov.adoc
  downstream/titles/release-notes/master.adoc
Labels: AAP Release notes, 2.5

#2581 AAP-35928: reorganizes assemblies in Managing automation content
  downstream/assemblies/hub/assembly-managing-cert-valid-content.adoc
  downstream/assemblies/hub/assembly-managing-collections-hub.adoc
  downstream/assemblies/hub/assembly-managing-containers-hub.adoc
  downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc
  downstream/modules/hub/con-offline-token-active.adoc
  downstream/modules/hub/con-token-management-hub.adoc
  downstream/modules/hub/proc-create-api-token-pah.adoc
  downstream/modules/hub/proc-create-api-token.adoc
  downstream/titles/hub/managing-content/master.adoc
Labels: Automation Hub, 2.5, Needs backport to 2.5

#2603 Corrections to published text
  downstream/assemblies/aap-hardening/assembly-hardening-aap.adoc
  downstream/assemblies/aap-hardening/assembly-intro-to-aap-hardening.adoc
  downstream/modules/aap-hardening/con-aap-additional-software.adoc
  downstream/modules/aap-hardening/con-automation-use-secrets.adoc
  downstream/modules/aap-hardening/con-logging-log-capture.adoc
  downstream/modules/aap-hardening/proc-install-user-pki.adoc
  downstream/modules/aap-hardening/ref-aap-authentication.adoc
  downstream/modules/aap-hardening/ref-architecture.adoc
  downstream/modules/aap-hardening/ref-initial-configuration.adoc
  downstream/modules/aap-hardening/ref-sensitive-variables-install-inventory.adoc
Labels: 2.5, Needs backport to 2.5

#2604 Corrections to published text (#2603)
  downstream/assemblies/aap-hardening/assembly-hardening-aap.adoc
  downstream/assemblies/aap-hardening/assembly-intro-to-aap-hardening.adoc
  downstream/modules/aap-hardening/con-aap-additional-software.adoc
  downstream/modules/aap-hardening/con-automation-use-secrets.adoc
  downstream/modules/aap-hardening/con-logging-log-capture.adoc
  downstream/modules/aap-hardening/proc-install-user-pki.adoc
  downstream/modules/aap-hardening/ref-aap-authentication.adoc
  downstream/modules/aap-hardening/ref-architecture.adoc
  downstream/modules/aap-hardening/ref-initial-configuration.adoc
  downstream/modules/aap-hardening/ref-sensitive-variables-install-inventory.adoc
Labels: 2.5, Backported to 2.5

#2578 Adding Microsoft Entra ID reference to docs
  downstream/modules/aap-hardening/ref-automation-controller-authentication.adoc
  downstream/modules/platform/proc-controller-set-up-azure.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4, 2.5, Needs backport to 2.5

#2606 Adding Microsoft Entra ID reference to docs (#2578)
  downstream/modules/aap-hardening/ref-automation-controller-authentication.adoc
  downstream/modules/platform/proc-controller-set-up-azure.adoc
Labels: documentation, 2.5, Backported to 2.5

#2607 Adding Microsoft Entra ID reference to docs (#2578)
  downstream/modules/aap-hardening/ref-automation-controller-authentication.adoc
  downstream/modules/platform/proc-controller-set-up-azure.adoc
Labels: documentation, Backported to 2.4, 2.4

#2608 Re-adding controller auth ref
  downstream/modules/aap-hardening/ref-automation-controller-authentication.adoc
Labels: documentation, 2.4

#2609 backport to 2.5: AAP-35928: reorganizes assemblies in Managing automation content (#2581)
  downstream/assemblies/hub/assembly-managing-cert-valid-content.adoc
  downstream/assemblies/hub/assembly-managing-collections-hub.adoc
  downstream/assemblies/hub/assembly-managing-containers-hub.adoc
  downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc
  downstream/modules/hub/con-offline-token-active.adoc
  downstream/modules/hub/con-token-management-hub.adoc
  downstream/modules/hub/proc-create-api-token-pah.adoc
  downstream/modules/hub/proc-create-api-token.adoc
  downstream/titles/hub/managing-content/master.adoc
Labels: Automation Hub, 2.5

#2610 AAP-35215: Updated Lightspeed docs for playbook generation support on Lightspeed onpremise deployments
  lightspeed/assemblies/assembly_configuring-lightspeed-onpremise.adoc
  lightspeed/assemblies/assembly_generating-playbooks.adoc
  lightspeed/titles/lightspeed-release-notes/master.adoc
  lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-11dec2024.adoc
Labels: documentation, Lightspeed

#2611 Add note to LDAP configuration regarding signed certificates
  downstream/modules/platform/proc-controller-set-up-LDAP.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#2612 [Backport] Add note to LDAP configuration regarding signed certificates (#2611)
  downstream/modules/platform/proc-controller-set-up-LDAP.adoc
Labels: Ready for review, 2.5

#2614 Fixes module ascii formatting in the Managing automation content guide
  downstream/modules/hub/con-token-management-hub.adoc
Labels: Automation Hub, 2.5, Needs backport to 2.5

#2615 Backport to 2.5: fixes module ascii formatting (#2614)
  downstream/modules/hub/con-token-management-hub.adoc
Labels: Automation Hub, 2.5

#2602 AAP-32980-A Enhance docs re: the management of maximum running activations
  downstream/assemblies/platform/assembly-install-aap-operator.adoc
  downstream/modules/eda/con-modifying-simultaneous-activations.adoc
  downstream/modules/eda/proc-modifying-activations-during-install.adoc
  downstream/modules/platform/con-ocp-supported-install.adoc
  downstream/modules/platform/con-operator-custom-resources.adoc
  downstream/modules/platform/ref-operator-crs.adoc
Labels: documentation, Ready for review, Technical review complete, 2.5, Needs backport to 2.5

#2616 Adds context attribute to assembly in Managing automation content
  downstream/assemblies/hub/assembly-hub-create-api-token.adoc
  downstream/assemblies/hub/assembly-managing-cert-valid-content.adoc
  downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc
  downstream/modules/hub/con-offline-token-active.adoc
  downstream/modules/hub/con-token-management-hub.adoc
  downstream/modules/hub/proc-create-api-token-pah.adoc
  downstream/modules/hub/proc-create-api-token.adoc
  downstream/modules/hub/proc-create-requirements-file.adoc
  downstream/modules/hub/proc-set-community-remote.adoc
  downstream/modules/hub/proc-set-rhcertified-remote.adoc
Labels: Automation Hub, 2.5, Needs backport to 2.5

#2619 Backport to 2.5: Adds context attribute to assembly in Managing automation content
  downstream/assemblies/hub/assembly-hub-create-api-token.adoc
  downstream/assemblies/hub/assembly-managing-cert-valid-content.adoc
  downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc
  downstream/modules/hub/con-offline-token-active.adoc
  downstream/modules/hub/con-token-management-hub.adoc
  downstream/modules/hub/proc-create-api-token-pah.adoc
  downstream/modules/hub/proc-create-api-token.adoc
  downstream/modules/hub/proc-create-requirements-file.adoc
  downstream/modules/hub/proc-set-community-remote.adoc
  downstream/modules/hub/proc-set-rhcertified-remote.adoc
Labels: Automation Hub, 2.5

#2621 Fixes ascii error in Note in Managing automation content guide
  downstream/modules/hub/proc-create-api-token.adoc
Labels: Automation Hub, 2.5

#2622 AAP-36295 HTTPS updates
  downstream/assemblies/platform/assembly-configure-aap-operator.adoc
  downstream/modules/platform/proc-controller-set-up-SAML.adoc
  downstream/modules/platform/proc-operator-aap-faq.adoc
  downstream/modules/platform/proc-operator-enable-https-redirect.adoc
Labels: 2.5, AAP operator

#2623 AAP-36295 HTTPS updates (#2622)
  downstream/assemblies/platform/assembly-configure-aap-operator.adoc
  downstream/modules/platform/proc-controller-set-up-SAML.adoc
  downstream/modules/platform/proc-operator-aap-faq.adoc
  downstream/modules/platform/proc-operator-enable-https-redirect.adoc
Labels: 2.5, AAP operator

#2626 Correct azure module to work in 2.4 and 2.5 (#2624)
  downstream/modules/platform/proc-controller-set-up-azure.adoc
Labels: 2.5, Backported to 2.5

#2627 Adding custom inventory script example (#1941)
  downstream/modules/platform/ref-controller-scm-inv-source-fields.adoc
Labels: Controller, 2.5, Backported to 2.5

#2628 Adding custom inventory script example (#1941)
  downstream/modules/platform/ref-controller-scm-inv-source-fields.adoc
Labels: documentation, Backported to 2.4, Controller, 2.4

#2629 AAP-35860: Updated the prerequisites for Lightspeed onpremise
  lightspeed/modules/con_overview-lightspeed-onpremise.adoc
Labels: documentation, Lightspeed

#2630 AAP-35926: Updated the the docs with VSCode multi-line prompts feature
  lightspeed/modules/proc_multi-task-recs.adoc
Labels: documentation, Lightspeed

#2633 Remove controller variable
  downstream/modules/platform/ref-controller-variables.adoc
Labels: Needs backport to 2.4, 2.4, 2.5, Needs backport to 2.5

#2635 Removed 2.4 controller variable
  downstream/modules/platform/ref-controller-variables.adoc
Labels: 2.4

#2636 Add release note entry for AAP Service on AWS
  downstream/titles/release-notes/topics/aap-25.adoc
Labels: AAP Release notes, SaaS on AWS, Needs backport to 2.5

#2440 AAP-34003: Import AAP 2.5 attributes to Lightspeed docs
  lightspeed/attributes/attributes.adoc
Labels: Lightspeed

#2639 Update note format
  downstream/modules/platform/ref-gateway-controller-hub-eda-ext-db.adoc
Labels: 2.4, 2.5, Needs backport to 2.5

#2640 Update note format
  downstream/modules/platform/ref-gateway-controller-hub-eda-ext-db.adoc
Labels: 2.5, Backported to 2.5

#2641 Update note format
  downstream/modules/platform/ref-single-controller-hub-eda-with-managed-db.adoc
Labels: 2.4

#2617 Add note regarding unsupported backups for earlier releases
  downstream/modules/platform/proc-upgrading-between-minor-aap-releases.adoc
Labels: documentation, 2.4

#2642 Add IBM-Z to CONT topologies
  downstream/modules/topologies/ref-cont-a-env-a.adoc
  downstream/modules/topologies/ref-cont-b-env-a.adoc
Labels: 2.5, Needs backport to 2.5

#2643 2.5 Add IBM-Z to CONT topologies (#2642)
  downstream/modules/topologies/ref-cont-a-env-a.adoc
  downstream/modules/topologies/ref-cont-b-env-a.adoc
Labels: 2.5

#2638 Removed incorrect subsections
  downstream/modules/platform/proc-completing-post-installation-tasks.adoc
Labels: Ready for technical review, Technical review complete, 2.4

#2644 Minor edits to metrics utility section
  downstream/modules/platform/proc-configuring-the-metrics-utility.adoc
Labels: documentation, Controller, 2.4, 2.5

#2645 Minor edits to metrics utility section (#2644)
  downstream/modules/platform/proc-configuring-the-metrics-utility.adoc
Labels: documentation, Controller, 2.5, Backported to 2.5

#2646 Minor edits to metrics utility section (#2644)
  downstream/modules/platform/proc-configuring-the-metrics-utility.adoc
Labels: Backported to 2.4, Controller, 2.4
