Repository ansible/aap-docs, pull requests merged in 2024-04, with the labels that each got.

#1192 AAP-18088: adds info on download count configuration; fixes a namesapce error (#915)
  downstream/assemblies/platform/assembly-installing-hub-operator.adoc
  downstream/modules/platform/proc-installing-hub-using-operator.adoc
  downstream/modules/platform/ref-ocp-additional-configs.adoc
Labels: 2.4

#1195 Correct typo in Red Hat Ansible Automation Platform Installation Guide
  downstream/assemblies/platform/assembly-disconnected-installation.adoc
Labels: Needs backport to 2.4, Needs backport to 2.3, Needs backport to 2.2

#1197 Creating new section to operator deploy guide as part of AAP-20779
  downstream/assemblies/platform/assembly-operator-add-execution-nodes.adoc
  downstream/modules/platform/proc-add-operator-execution-nodes.adoc
  downstream/titles/aap-operator-installation/master.adoc
Labels: documentation, Needs backport to 2.4, 2.4

#1199 Creating new section to operator deploy guide as part of AAP-20779 (#…
  downstream/assemblies/platform/assembly-operator-add-execution-nodes.adoc
  downstream/modules/platform/proc-add-operator-execution-nodes.adoc
  downstream/titles/aap-operator-installation/master.adoc
Labels: documentation, Needs backport to 2.4, 2.4

#1188 AAP-19094: adds API URL to EDA user guide
  downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc
Labels: Ready for review, Needs backport to 2.4, Not ready for peer review, 2.4, Main

#1201 AAP-19094: adds API URL to EDA user guide (#1188)
  downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc
Labels: 2.4

#1193 Changes to execution environment pull policy
  downstream/modules/platform/proc-controller-use-an-exec-env.adoc
Labels: Needs backport to 2.4, Controller, 2.4

#1204 Changes to execution environment pull policy (#1193)
  downstream/modules/platform/proc-controller-use-an-exec-env.adoc
Labels: documentation, Backported to 2.4, Controller, 2.4

#1202 AAP-20287: Added info. about logging in to Ansible Lightspeed Service through VS Code extension
  lightspeed/assemblies/assembly_configuring-vscode-extension.adoc
  lightspeed/modules/proc_configure-vscode-extension.adoc
  lightspeed/modules/proc_login-vscode-extension.adoc
Labels: Ready for review, Lightspeed

#1205 Add bundle-installer-2.4-6.1 to release notes
  downstream/titles/release-notes/master.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-61.adoc
Labels: Ready for review, Needs backport to 2.4, AAP Release notes

#1207 Add bundle-installer-2.4-6.1 to release notes (#1205)
  downstream/titles/release-notes/master.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-61.adoc
Labels: AAP Release notes, 2.4

#1208 AAP-19094: fixed formatting to make API link inactive
  downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc
Labels: Needs backport to 2.4, 2.4, Main

#1206 Adding links to SAML auth in chapt. 21
  downstream/assemblies/platform/assembly-controller-set-up-social-authentication.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#1210 Adding links to SAML auth in chapt. 21 (#1206)
  downstream/assemblies/platform/assembly-controller-set-up-social-authentication.adoc
Labels: documentation, Controller, 2.4

#1212 Add symlink to images directory
  downstream/titles/aap-operator-installation/images
Labels: Needs backport to 2.4, 2.4

#1214 fixing typo and Icon size for AAP-20779
  downstream/modules/platform/proc-add-operator-execution-nodes.adoc
Labels: documentation, Needs backport to 2.4, 2.4

#1203 Update release notes based on feedback from minimalism session.
  downstream/snippets/deprecated-features.adoc
  downstream/snippets/technology-preview.adoc
  downstream/titles/release-notes/docinfo.xml
  downstream/titles/release-notes/snippets
  downstream/titles/release-notes/topics/aap-24.adoc
  downstream/titles/release-notes/topics/controller-440.adoc
  downstream/titles/release-notes/topics/eda-24.adoc
  downstream/titles/release-notes/topics/platform-intro.adoc
Labels: Ready for review, Needs backport to 2.4, AAP Release notes

#1215 backport 2.4
  downstream/modules/platform/proc-add-operator-execution-nodes.adoc
Labels: documentation, Needs backport to 2.4, 2.4

#1216 Update release notes based on feedback from minimalism session. (#1203)
  downstream/snippets/deprecated-features.adoc
  downstream/snippets/technology-preview.adoc
  downstream/titles/release-notes/docinfo.xml
  downstream/titles/release-notes/snippets
  downstream/titles/release-notes/topics/aap-24.adoc
  downstream/titles/release-notes/topics/controller-440.adoc
  downstream/titles/release-notes/topics/eda-24.adoc
  downstream/titles/release-notes/topics/platform-intro.adoc
Labels: AAP Release notes, 2.4

#1209 Backport to 2.4: AAP 19094 fixed formatting to make API link inactive (#1208)
  downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc
Labels: 2.4

#1219 AAP-22604 New Creating Ansible automation content book for devtools
  downstream/titles/develop-automation-content/aap-common
  downstream/titles/develop-automation-content/attributes
  downstream/titles/develop-automation-content/dev-guide
  downstream/titles/develop-automation-content/docinfo.xml
  downstream/titles/develop-automation-content/images
  downstream/titles/develop-automation-content/master.adoc
Labels: 2.5

#1220 Procedure for mounting the directory in the execution node
  downstream/assemblies/platform/assembly-controller-execution-environments.adoc
  downstream/modules/platform/proc-controller-ee-mount-execution-node.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#1221 Procedure for mounting the directory in the execution node (#1220)
  downstream/assemblies/platform/assembly-controller-execution-environments.adoc
  downstream/modules/platform/proc-controller-ee-mount-execution-node.adoc
Labels: documentation, Controller, 2.4

#1222 Amended eda inventory variable
  downstream/modules/platform/ref-eda-controller-variables.adoc
Labels: Needs backport to 2.4, 2.4

#1223 Amended eda inventory variable (#1222)
  downstream/modules/platform/ref-eda-controller-variables.adoc
Labels: Backported to 2.4

#1230 2.4 Update links to use BaseURL attribute in modules (#1228)
  downstream/modules/aap-hardening/con-install-secure-host.adoc
  downstream/modules/aap-hardening/con-logging-log-capture.adoc
  downstream/modules/aap-hardening/con-network-firewall-services-planning.adoc
  downstream/modules/aap-hardening/con-planning-considerations.adoc
  downstream/modules/aap-hardening/con-platform-components.adoc
  downstream/modules/aap-hardening/con-rbac.adoc
  downstream/modules/aap-hardening/con-rhel-host-planning.adoc
  downstream/modules/aap-hardening/ref-ntp.adoc
  downstream/modules/aap-hardening/ref-private-automation-hub-authentication.adoc
  downstream/modules/aap-hardening/ref-security-variables-install-inventory.adoc
  downstream/modules/builder/proc-customize-ee-image.adoc
  downstream/modules/builder/proc-installing-builder.adoc
  downstream/modules/builder/ref-scenario-using-authentication-ee.adoc
  downstream/modules/central-auth/con-central-auth-reqs.adoc
  downstream/modules/core/con-execution-environments.adoc
  downstream/modules/dev-guide/con-content-workflows.adoc
  downstream/modules/eda/ref-deploy-eda-controller-with-aap-operator-on-ocp.adoc
  downstream/modules/eda/ref-installing-eda-controller-on-aap.adoc
  downstream/modules/hub/con-repo-rbac.adoc
  downstream/modules/hub/proc-add-user-to-group.adoc
  downstream/modules/hub/proc-assigning-permissions.adoc
  downstream/modules/hub/proc-configure-proxy-remote.adoc
  downstream/modules/hub/proc-create-groups.adoc
  downstream/modules/hub/proc-delete-namespace.adoc
  downstream/modules/hub/proc-provide-remote-access.adoc
  downstream/modules/hub/proc-provide-repository-access.adoc
  downstream/modules/hub/proc-set-community-remote.adoc
  downstream/modules/hub/proc-set-rhcertified-remote.adoc
  downstream/modules/hub/proc_ppah-prepare-rhel-host.adoc
  downstream/modules/hub/ref-variables-connect-hub-sso.adoc
  downstream/modules/platform/proc-add-operator-execution-nodes.adoc
Labels: 2.4

#1233 AAP-22864 updating hyperlink text to be more accurate (#1231)
  downstream/modules/platform/con-pod-specification-mods.adoc
Labels: Needs backport to 2.4, 2.4

#1232 backporting 1232 to 2.3
  downstream/modules/platform/con-pod-specification-mods.adoc
Labels: 2.3, Needs backport to 2.3

#1234 2.3 Update .gitignore
  .gitignore
Labels: 2.3

#1229 Update links to use PlatformVers attribute
  downstream/modules/aap-hardening/con-install-secure-host.adoc
  downstream/modules/aap-hardening/con-network-firewall-services-planning.adoc
  downstream/modules/aap-hardening/con-planning-considerations.adoc
  downstream/modules/aap-hardening/con-platform-components.adoc
  downstream/modules/aap-hardening/ref-private-automation-hub-authentication.adoc
  downstream/modules/aap-hardening/ref-security-variables-install-inventory.adoc
  downstream/modules/builder/proc-installing-builder.adoc
  downstream/modules/central-auth/con-central-auth-reqs.adoc
  downstream/modules/eda/ref-deploy-eda-controller-with-aap-operator-on-ocp.adoc
  downstream/modules/hub/proc-add-user-to-group.adoc
  downstream/modules/hub/proc-assigning-permissions.adoc
  downstream/modules/hub/proc-create-groups.adoc
Labels: Needs backport to 2.4, 2.4

#1237 Update URLs to use BaseURL
  attributes/attributes.adoc
  stories/assembly-aws-upgrade.adoc
  stories/assembly-gcp-intro.adoc
  stories/assembly-gcp-release-notes-24.adoc
  stories/assembly-gcp-upgrade.adoc
  stories/tmp.docx
  stories/topics/con-aws-upgrade-backup-process.adoc
  stories/topics/con-aws-upgrade-restore-from-stack.adoc
  stories/topics/con-azure-about.adoc
  stories/topics/con-gcp-pull-deploy-container-image.adoc
  stories/topics/con-gcp-pull-remove-container-image.adoc
  stories/topics/con-gcp-upgrade-restore-from-stack.adoc
  stories/topics/con-gcp-use-container-image.adoc
  stories/topics/proc-gcp-backup-container-image.adoc
  stories/topics/proc-gcp-deploy-with-new-vpc.adoc
  stories/topics/proc-gcp-generate-restore-yml-file.adoc
  stories/topics/proc-gcp-pull-backup-container-image.adoc
  stories/topics/proc-gcp-restore-container-image.adoc
  stories/topics/proc-gcp-upgrade-pull-container-image.adoc
  stories/topics/tech-note-gcp-upgrade-logging-and-monitoring.adoc
Labels: AAP on clouds

#1241 AAP-20006 Diagram and table update
  downstream/archive/archived-images/aap-network-ports-protocols-314.png
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
  downstream/images/aap-network-ports-protocols.png
Labels: documentation, 2.3, Needs backport to 2.4, Needs backport to 2.3, 2.4

#1244 AAP-20006 Diagram and table update (#1241)
  downstream/archive/archived-images/aap-network-ports-protocols-314.png
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
  downstream/images/aap-network-ports-protocols.png
Labels: Needs backport to 2.4, 2.4

#1245 Update ref-system-requirements.adoc (#1017)
  downstream/modules/platform/ref-system-requirements.adoc
Labels: 2.4

#1247 Create Archive directory
  downstream/archive/archived-images/temp.adoc
Labels: repo

#1238 Adding security section.
  stories/assembly-azure-intro.adoc
  stories/topics/con-azure-security.adoc
Labels: AAP on clouds, AAP on Azure

#1225 Adding attributes for menu selections for 2.4
  downstream/attributes/attributes.adoc
Labels: Ready for review, Needs backport to 2.4, Attributes, 2.4

#1248 Correcting link to Podman docs in EE chapter
  downstream/modules/platform/proc-controller-ee-mount-execution-node.adoc
Labels: documentation, Needs backport to 2.4, Technical review complete, Controller, 2.4

#1252 AAP-22950 updated figure 2.2 (#1239)
  downstream/modules/aap-hardening/con-network-firewall-services-planning.adoc
Labels: Ready for review, 2.4

#1211 Changes to operator mesh setup
  downstream/assemblies/platform/assembly-automation-mesh-operator-aap.adoc
  downstream/modules/platform/proc-define-mesh-node-types.adoc
  downstream/modules/platform/proc-set-up-virtual-machines.adoc
  downstream/modules/platform/ref-operator-mesh-prerequisites.adoc
Labels: documentation, Needs backport to 2.4, Technical review complete, 2.4

#1254 Changes to operator mesh setup (#1211)
  downstream/assemblies/platform/assembly-automation-mesh-operator-aap.adoc
  downstream/modules/platform/proc-define-mesh-node-types.adoc
  downstream/modules/platform/proc-set-up-virtual-machines.adoc
  downstream/modules/platform/ref-operator-mesh-prerequisites.adoc
Labels: Backported to 2.4, 2.4

#1256 Automation Controller Administration Guide/ User Guide typos/Link error?
  downstream/modules/platform/proc-controller-adding-gpg-key.adoc
  downstream/modules/platform/ref-controller-metrics-monitoring.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#1240 Add section on setting up database
  downstream/assemblies/platform/assembly-system-requirements.adoc
  downstream/modules/platform/proc-setup-postgresql-ext-database.adoc
Labels: documentation, Needs backport to 2.4, 2.4

#1258 Add section on setting up database (#1240)
  downstream/assemblies/platform/assembly-system-requirements.adoc
  downstream/modules/platform/proc-setup-postgresql-ext-database.adoc
Labels: Backported to 2.4, 2.4

#1257 Automation Controller Administration Guide/ User Guide typos/Link err…
  downstream/modules/platform/proc-controller-adding-gpg-key.adoc
  downstream/modules/platform/ref-controller-metrics-monitoring.adoc
Labels: documentation, Controller, 2.4

#1255 Correct formatting, spelling, and grammar in Platform Planning Guide
  downstream/assemblies/platform/assembly-aap-architecture.adoc
  downstream/assemblies/platform/assembly-aap-platform-components.adoc
  downstream/assemblies/platform/assembly-attaching-subscriptions.adoc
  downstream/assemblies/platform/assembly-choosing-obtaining-installer.adoc
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
  downstream/assemblies/platform/assembly-system-requirements.adoc
  downstream/modules/platform/con-SM-standalone-contr-non-inst-database.adoc
  downstream/modules/platform/con-about-eda-controller.adoc
  downstream/modules/platform/con-declaring-variables.adoc
  downstream/modules/platform/con-editing-inventory-files.adoc
  downstream/modules/platform/con-single-eda-controller-with-internal-database.adoc
  downstream/modules/platform/proc-benchmark-postgresql.adoc
  downstream/modules/platform/proc-installing-without-internet.adoc
  downstream/modules/platform/proc-securing-secrets-in-inventory.adoc
  downstream/modules/platform/ref-automation-hub-requirements.adoc
  downstream/modules/platform/ref-controller-system-requirements.adoc
  downstream/modules/platform/ref-eda-system-requirements.adoc
  downstream/modules/platform/ref-guidelines-hosts-groups.adoc
  downstream/modules/platform/ref-postgresql-requirements.adoc
  downstream/modules/platform/ref-system-requirements.adoc
  downstream/titles/aap-planning-guide/master.adoc
Labels: Ready for review, Needs backport to 2.4

#1260 Correct formatting, spelling, and grammar in Platform Planning Guide …
  downstream/assemblies/platform/assembly-aap-architecture.adoc
  downstream/assemblies/platform/assembly-aap-platform-components.adoc
  downstream/assemblies/platform/assembly-attaching-subscriptions.adoc
  downstream/assemblies/platform/assembly-choosing-obtaining-installer.adoc
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
  downstream/assemblies/platform/assembly-system-requirements.adoc
  downstream/modules/platform/con-SM-standalone-contr-non-inst-database.adoc
  downstream/modules/platform/con-about-eda-controller.adoc
  downstream/modules/platform/con-declaring-variables.adoc
  downstream/modules/platform/con-editing-inventory-files.adoc
  downstream/modules/platform/con-single-eda-controller-with-internal-database.adoc
  downstream/modules/platform/proc-benchmark-postgresql.adoc
  downstream/modules/platform/proc-installing-without-internet.adoc
  downstream/modules/platform/proc-securing-secrets-in-inventory.adoc
  downstream/modules/platform/ref-automation-hub-requirements.adoc
  downstream/modules/platform/ref-controller-system-requirements.adoc
  downstream/modules/platform/ref-eda-system-requirements.adoc
  downstream/modules/platform/ref-guidelines-hosts-groups.adoc
  downstream/modules/platform/ref-postgresql-requirements.adoc
  downstream/titles/aap-planning-guide/master.adoc
Labels: 2.4

#1261 AAP-23136 Add SaaS on AWS to sync script
  bin/sync_cloud_docs.sh
Labels: AAP on clouds, SaaS on AWS

#1262 Fix broken link in Controller Admin guide
  downstream/modules/platform/proc-define-mesh-node-types.adoc
Labels: Ready for review, Needs backport to 2.4, 2.4

#1263 [Backport] Fix broken link in Controller Admin guide (#1262)
  downstream/modules/platform/proc-define-mesh-node-types.adoc
Labels: Backported to 2.4, 2.4

#1218 Update release notes based on feedback from minimalism session
  downstream/titles/release-notes/master.adoc
  downstream/titles/release-notes/topics/aap-24.adoc
  downstream/titles/release-notes/topics/eda-24.adoc
Labels: Ready for review, Needs backport to 2.4, AAP Release notes

#1259 AAP-23126 Scaffold directories for Ansible as a Service on AWS docs
  attributes/attributes.adoc
  titles/saas-aws/aap-common
  titles/saas-aws/attributes
  titles/saas-aws/docinfo.xml
  titles/saas-aws/images
  titles/saas-aws/master.adoc
  titles/saas-aws/saas-aws.asciidoc
  titles/saas-aws/stories
  titles/saas-aws/stories.adoc
  titles/saas-aws/title-attributes.adoc
Labels: AAP on clouds, SaaS on AWS

#1249 Removed references to out-of-date Ansible version
  downstream/assemblies/dev-guide/assembly-migrate-ansible-versions.adoc
  downstream/modules/builder/con-about-ee.adoc
  downstream/modules/builder/proc-customize-ee-image.adoc
  downstream/modules/dev-guide/proc-create-collections.adoc
  downstream/modules/platform/con-why-ee.adoc
  downstream/modules/platform/con-why-migrate-ansible-29.adoc
  downstream/modules/platform/proc-controller-inv-source-vm-vcenter.adoc
  downstream/modules/platform/proc-install-ansible-colls.adoc
  downstream/modules/platform/proc-update-ee-image-locations.adoc
  downstream/modules/platform/ref-system-requirements.adoc
  downstream/modules/security/con-requirements.adoc
  downstream/modules/security/proc-creating-firewall-rule.adoc
Labels: Needs backport to 2.4, Ready for technical review, 2.4

#1265 Removed references to out-of-date Ansible version (#1249)
  downstream/assemblies/dev-guide/assembly-migrate-ansible-versions.adoc
  downstream/modules/builder/con-about-ee.adoc
  downstream/modules/builder/proc-customize-ee-image.adoc
  downstream/modules/dev-guide/proc-create-collections.adoc
  downstream/modules/platform/con-why-ee.adoc
  downstream/modules/platform/con-why-migrate-ansible-29.adoc
  downstream/modules/platform/proc-controller-inv-source-vm-vcenter.adoc
  downstream/modules/platform/proc-install-ansible-colls.adoc
  downstream/modules/platform/proc-update-ee-image-locations.adoc
  downstream/modules/platform/ref-system-requirements.adoc
  downstream/modules/security/con-requirements.adoc
  downstream/modules/security/proc-creating-firewall-rule.adoc
Labels: Backported to 2.4, 2.4

#1264 Update release notes based on feedback from minimalism session (#1218)
  downstream/titles/release-notes/master.adoc
  downstream/titles/release-notes/topics/aap-24.adoc
  downstream/titles/release-notes/topics/eda-24.adoc
Labels: AAP Release notes, 2.4

#1242 AAP-22347: Updated AAP release notes per feedback from minimalism session
  downstream/titles/release-notes/topics/bundle-installer-24-11.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-12.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-13.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-14.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-21.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-22.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-24.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-6.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-61.adoc
  downstream/titles/release-notes/topics/docs-24.adoc
  downstream/titles/release-notes/topics/hub-464.adoc
  downstream/titles/release-notes/topics/installer-24-2.adoc
  downstream/titles/release-notes/topics/installer-24-3.adoc
  downstream/titles/release-notes/topics/installer-24-4.adoc
  downstream/titles/release-notes/topics/installer-24-5.adoc
  downstream/titles/release-notes/topics/installer-24-6.adoc
Labels: Ready for review, AAP Release notes

#1251 Removing note for rsyslog in controller admin guide
  downstream/assemblies/platform/assembly-controller-logging-aggregation.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#1266 Removing note for rsyslog in controller admin guide (#1251)
  downstream/assemblies/platform/assembly-controller-logging-aggregation.adoc
Labels: documentation, Controller, 2.4

#1267 Correct release note title name
  downstream/titles/release-notes/master.adoc
Labels: Ready for review, Needs backport to 2.4

#1268 Correct release note title name (#1267)
  downstream/titles/release-notes/master.adoc
Labels: 2.4

#1269 Provide URL naming consistency
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
Labels: Backported to 2.4, 2.4

#1271 Add section on setting up database
  downstream/assemblies/platform/assembly-system-requirements.adoc
  downstream/modules/platform/proc-setup-postgresql-ext-database.adoc
Labels: 2.3

#1273 Adding Saas Assemblies as part of AAP-23354
  stories/assembly-saas-install.adoc
  stories/assembly-saas-intro.adoc
  stories/assembly-saas-planning.adoc
  stories/assembly-saas-post-install-config.adoc
Labels: documentation, Ready for review, SaaS on AWS

#1276 Update documentation links
  downstream/modules/platform/con-aap-upgrade-planning.adoc
Labels: Needs backport to 2.4, 2.4

#1277 Update documentation links (#1276)
  downstream/modules/platform/con-aap-upgrade-planning.adoc
Labels: Backported to 2.4, 2.4

#1278 Add bundle-installer-2.4-6.2 to release notes
  downstream/titles/release-notes/master.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-62.adoc
Labels: Ready for review, Needs backport to 2.4, AAP Release notes

#1279 Corrected API version
  downstream/modules/platform/proc-operator-external-db-controller.adoc
  downstream/modules/platform/proc-operator-external-db-hub.adoc
Labels: Needs backport to 2.4, 2.4

#1281 Corrected API version (#1279)
  downstream/modules/platform/proc-operator-external-db-controller.adoc
  downstream/modules/platform/proc-operator-external-db-hub.adoc
Labels: Backported to 2.4, 2.4

#1280 Add bundle-installer-2.4-6.2 to release notes (#1278)
  downstream/titles/release-notes/master.adoc
  downstream/titles/release-notes/topics/bundle-installer-24-62.adoc
Labels: AAP Release notes, 2.4

#1282 Update documentation links
  downstream/modules/platform/con-aap-upgrade-planning.adoc
Labels: Needs backport to 2.4, 2.4

#1283 Update documentation links (#1282)
  downstream/modules/platform/con-aap-upgrade-planning.adoc
Labels: Needs backport to 2.4, 2.4

#1284 Changed attribute value
  downstream/attributes/attributes.adoc
Labels: Needs backport to 2.4, 2.4

#1272 Corrections to controller docs before 2.5 GA
  downstream/assemblies/platform/assembly-ag-controller-clustering.adoc
  downstream/assemblies/platform/assembly-controller-execution-environments.adoc
  downstream/modules/platform/proc-controller-awx-manage-utility.adoc
  downstream/modules/platform/proc-controller-configure-secret-lookups.adoc
  downstream/modules/platform/proc-controller-ee-mount-execution-node.adoc
  downstream/modules/platform/proc-controller-importing-subscriptions.adoc
  downstream/modules/platform/ref-controller-api-considerations.adoc
  downstream/modules/platform/ref-controller-dependencies.adoc
  downstream/modules/platform/ref-controller-group-name-vars-filtering.adoc
  downstream/modules/platform/ref-controller-proj-sign-prerequisites.adoc
  downstream/modules/platform/ref-controller-run-the-builder.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#1285 Changed attribute value (#1284)
  downstream/attributes/attributes.adoc
Labels: Backported to 2.4, 2.4

#1286 Corrections to controller docs before 2.5 GA (#1272)
  downstream/assemblies/platform/assembly-ag-controller-clustering.adoc
  downstream/assemblies/platform/assembly-controller-execution-environments.adoc
  downstream/modules/platform/proc-controller-awx-manage-utility.adoc
  downstream/modules/platform/proc-controller-configure-secret-lookups.adoc
  downstream/modules/platform/proc-controller-ee-mount-execution-node.adoc
  downstream/modules/platform/proc-controller-importing-subscriptions.adoc
  downstream/modules/platform/ref-controller-api-considerations.adoc
  downstream/modules/platform/ref-controller-dependencies.adoc
  downstream/modules/platform/ref-controller-group-name-vars-filtering.adoc
  downstream/modules/platform/ref-controller-proj-sign-prerequisites.adoc
  downstream/modules/platform/ref-controller-run-the-builder.adoc
Labels: documentation, Controller, 2.4

#1287 Changed Satellite version to attribute
  downstream/modules/platform/con-building-an-execution-environment-in-a-disconnected-environment.adoc
  downstream/modules/platform/proc-controller-importing-subscriptions.adoc
  downstream/modules/platform/proc-installing-the-ansible-builder-rpm.adoc
Labels: Needs backport to 2.4, 2.4

#1288 Changed Satellite version to attribute (#1287)
  downstream/modules/platform/con-building-an-execution-environment-in-a-disconnected-environment.adoc
  downstream/modules/platform/proc-controller-importing-subscriptions.adoc
  downstream/modules/platform/proc-installing-the-ansible-builder-rpm.adoc
Labels: Backported to 2.4, 2.4

#1289 [AAP-22627] Commenting out Chapter 9. Not to be included in 2.5
  downstream/titles/aap-operator-installation/master.adoc
Labels: documentation, Ready for review, 2.5

#1291 Update for 2.4 primary menu snippets
  downstream/attributes/attributes.adoc
  downstream/snippets/snip_menu-top-ac.adoc
  downstream/snippets/snip_menu-top-ae.adoc
Labels: Needs backport to 2.4, Ready for technical review, snippets, Attributes, 2.4

#1293 Add NavigatorStart attribute and update Navigator attribute
  downstream/assemblies/navigator/assembly-executing-content.adoc
  downstream/assemblies/navigator/assembly-intro-navigator.adoc
  downstream/assemblies/navigator/assembly-review-ee-navigator.adoc
  downstream/assemblies/navigator/assembly-settings-navigator.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/navigator/con-about-ansible-navigator.adoc
  downstream/modules/navigator/con-about-navigator-settings.adoc
  downstream/modules/navigator/con-navigator-collections.adoc
  downstream/modules/navigator/con-navigator-modes.adoc
  downstream/modules/navigator/proc-review-ansible-config-tui.adoc
  downstream/modules/navigator/proc-review-artifact.adoc
  downstream/modules/navigator/ref-faq-navigator.adoc
  downstream/modules/navigator/ref-navigator-command-summary.adoc
  downstream/modules/navigator/ref-navigator-config-settings.adoc
  downstream/modules/navigator/ref-navigator-general-settings.adoc
  downstream/modules/navigator/ref-navigator-inventory-settings.adoc
  downstream/modules/navigator/ref-navigator-replay-settings.adoc
  downstream/modules/navigator/ref-navigator-run-settings.adoc
  downstream/modules/platform/con-about-navigator.adoc
Labels: Needs backport to 2.4

#1294 Add NavigatorStart attribute and update Navigator attribute (#1293)
  downstream/assemblies/navigator/assembly-executing-content.adoc
  downstream/assemblies/navigator/assembly-intro-navigator.adoc
  downstream/assemblies/navigator/assembly-review-ee-navigator.adoc
  downstream/assemblies/navigator/assembly-settings-navigator.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/navigator/con-about-ansible-navigator.adoc
  downstream/modules/navigator/con-about-navigator-settings.adoc
  downstream/modules/navigator/con-navigator-collections.adoc
  downstream/modules/navigator/con-navigator-modes.adoc
  downstream/modules/navigator/proc-review-ansible-config-tui.adoc
  downstream/modules/navigator/proc-review-artifact.adoc
  downstream/modules/navigator/ref-faq-navigator.adoc
  downstream/modules/navigator/ref-navigator-command-summary.adoc
  downstream/modules/navigator/ref-navigator-config-settings.adoc
  downstream/modules/navigator/ref-navigator-general-settings.adoc
  downstream/modules/navigator/ref-navigator-inventory-settings.adoc
  downstream/modules/navigator/ref-navigator-replay-settings.adoc
  downstream/modules/navigator/ref-navigator-run-settings.adoc
  downstream/modules/platform/con-about-navigator.adoc
Labels: 2.4

#1295 Saas Set up proc (AAP23355)
  stories/topics/proc-saas-set-up.adoc
Labels: documentation, AAP on clouds, SaaS on AWS

#1296 AAP-17190 Create assemblies for devtools doc
  downstream/assemblies/devtools/assembly-developer-workflow.adoc
  downstream/assemblies/devtools/assembly-devtools-install.adoc
  downstream/assemblies/devtools/assembly-devtools-setup.adoc
  downstream/assemblies/devtools/assembly-scaffolding-playbook-directory.adoc
  downstream/assemblies/devtools/assembly-writing-running-playbook.adoc
  downstream/assemblies/devtools/devtools
  downstream/titles/develop-automation-content/dev-guide
  downstream/titles/develop-automation-content/devtools
  downstream/titles/develop-automation-content/master.adoc
Labels: Needs backport to 2.4, 2.4
