Repository ansible/aap-docs, pull requests merged in 2024-08, with the labels that each got.

#1665 [Backport] AAP-19236 - Add assemblies for Access Management
  downstream/assemblies/platform/assembly-controller-organizations.adoc
  downstream/assemblies/platform/assembly-controller-teams.adoc
  downstream/assemblies/platform/assembly-controller-users.adoc
  downstream/assemblies/platform/assembly-gw-resources.adoc
  downstream/modules/platform/proc-gw-organizations-exec-env.adoc
  downstream/modules/platform/proc-gw-team-access-resources.adoc
Labels: Ready for review, 2.5

#1664 Update ordering and hierarchy of HA automation hub sections in VM-install guide
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
Labels: Needs backport to 2.4, Needs backport to 2.5

#1670 2.4 Update ordering and hierarchy of HA automation hub sections in VM-install guide
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
Labels: 2.4

#1669 2.5 Update ordering and hierarchy of HA automation hub sections in VM-install guide (#1664)
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
Labels: 2.5

#1671 Update URL of trial licence
  downstream/modules/platform/ref-controller-trial-evaluation.adoc
Labels: Needs backport to 2.4, Controller, 2.4, 2.5, Needs backport to 2.5

#1673 Update URL of trial licence (#1671)
  downstream/modules/platform/ref-controller-trial-evaluation.adoc
Labels: 2.5, Backported to 2.5

#1672 Update URL of trial licence (#1671)
  downstream/modules/platform/ref-controller-trial-evaluation.adoc
Labels: Backported to 2.4, 2.4

#1652 Update SELinux command
  downstream/modules/platform/proc-install-ha-hub-selinux.adoc
Labels: Needs backport to 2.4, 2.4, 2.5, Needs backport to 2.5

#1674 Update SELinux command (#1652)
  downstream/modules/platform/proc-install-ha-hub-selinux.adoc
Labels: 2.5, Backported to 2.5

#1675 Update SELinux command (#1652)
  downstream/modules/platform/proc-install-ha-hub-selinux.adoc
Labels: Backported to 2.4, 2.4

#1677 AAP-19133 Update existing modules for organizations for 2.5 RBAC changes
  downstream/modules/platform/con-controller-access-organizations.adoc
  downstream/modules/platform/proc-controller-add-organization-user.adoc
  downstream/modules/platform/proc-controller-create-organization.adoc
  downstream/modules/platform/proc-controller-review-organizations.adoc
  downstream/modules/platform/ref-controller-organization-notifications.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#1678 AAP-19133 Update content on teams for 2.5 RBAC changes
  downstream/modules/platform/proc-controller-creating-a-team.adoc
  downstream/modules/platform/proc-controller-user-permissions.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#1680 AAP-19236 fix include statements to include platform/
  downstream/assemblies/platform/assembly-controller-organizations.adoc
  downstream/assemblies/platform/assembly-controller-teams.adoc
  downstream/assemblies/platform/assembly-controller-users.adoc
  downstream/assemblies/platform/assembly-gw-resources.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#1681 AAP-26615: Added info. about creating bundle secret to trust custom CA
  lightspeed/modules/proc_create-connection-secrets.adoc
Labels: Ready for review, Lightspeed

#1679 AAP-19133 Update content on Users for 2.5 RBAC changes
  downstream/modules/platform/con-controller-create-users.adoc
  downstream/modules/platform/proc-controller-creating-a-user.adoc
  downstream/modules/platform/proc-controller-deleting-a-user.adoc
  downstream/modules/platform/ref-controller-user-roles.adoc
  downstream/modules/platform/ref-controller-user-teams.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#1683 [Backport] AAP-19236 fix include statements to include platform/ (#1680)
  downstream/assemblies/platform/assembly-controller-organizations.adoc
  downstream/assemblies/platform/assembly-controller-teams.adoc
  downstream/assemblies/platform/assembly-controller-users.adoc
  downstream/assemblies/platform/assembly-gw-resources.adoc
Labels: Ready for review, 2.5

#1684 [Backport] AAP-19133 Update content on teams for 2.5 RBAC changes (#1678)
  downstream/modules/platform/proc-controller-creating-a-team.adoc
  downstream/modules/platform/proc-controller-user-permissions.adoc
Labels: Ready for review, 2.5

#1685 [Backport] AAP-19133 Update existing modules for organizations for 2.5 RBAC changes (#1677)
  downstream/modules/platform/con-controller-access-organizations.adoc
  downstream/modules/platform/proc-controller-add-organization-user.adoc
  downstream/modules/platform/proc-controller-create-organization.adoc
  downstream/modules/platform/proc-controller-review-organizations.adoc
  downstream/modules/platform/ref-controller-organization-notifications.adoc
Labels: Ready for review, 2.5

#1686 [Backport] AAP-19133 Update content on Users for 2.5 RBAC changes (#1679)
  downstream/modules/platform/con-controller-create-users.adoc
  downstream/modules/platform/proc-controller-creating-a-user.adoc
  downstream/modules/platform/proc-controller-deleting-a-user.adoc
  downstream/modules/platform/ref-controller-user-roles.adoc
  downstream/modules/platform/ref-controller-user-teams.adoc
Labels: Ready for review, 2.5

#1688 Add steps for configuring mTLS authentication for user provided DBs
  downstream/modules/platform/proc-setup-postgresql-ext-database.adoc
Labels: Ready for review, Needs backport to 2.5

#1689 Add description
  downstream/modules/platform/con-controller-settings.adoc
  downstream/modules/platform/proc-controller-configure-system.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#1691 Add description (#1689)
  downstream/modules/platform/con-controller-settings.adoc
  downstream/modules/platform/proc-controller-configure-system.adoc
Labels: 2.5, Backported to 2.5

#1630 AAP-27779 Archive deprecated titles for 2.5
  downstream/archive/archived-titles/analytics/automation-savings-planner/docinfo.xml
  downstream/archive/archived-titles/analytics/automation-savings-planner/master.adoc
  downstream/archive/archived-titles/analytics/automation-savings/docinfo.xml
  downstream/archive/archived-titles/analytics/automation-savings/master.adoc
  downstream/archive/archived-titles/analytics/reports/docinfo.xml
  downstream/archive/archived-titles/analytics/reports/master.adoc
  downstream/archive/archived-titles/controller/controller-getting-started/docinfo.xml
  downstream/archive/archived-titles/controller/controller-getting-started/master.adoc
  downstream/archive/archived-titles/controller/controller-guide/docinfo.xml
  downstream/archive/archived-titles/controller/controller-guide/master.adoc
  downstream/archive/archived-titles/eda/eda-getting-started-guide/docinfo.xml
  downstream/archive/archived-titles/eda/eda-getting-started-guide/master.adoc
  downstream/archive/archived-titles/hub/getting-started/docinfo.xml
  downstream/archive/archived-titles/hub/getting-started/master.adoc
  downstream/titles/analytics/automation-savings-planner/aap-common
  downstream/titles/analytics/automation-savings-planner/analytics
  downstream/titles/analytics/automation-savings-planner/attributes
  downstream/titles/analytics/automation-savings-planner/images
  downstream/titles/analytics/automation-savings/aap-common
  downstream/titles/analytics/automation-savings/analytics
  downstream/titles/analytics/automation-savings/attributes
  downstream/titles/analytics/reports/aap-common
  downstream/titles/analytics/reports/analytics
  downstream/titles/analytics/reports/attributes
  downstream/titles/controller/controller-getting-started/aap-common
  downstream/titles/controller/controller-getting-started/attributes
  downstream/titles/controller/controller-getting-started/images
  downstream/titles/controller/controller-getting-started/platform
  downstream/titles/eda/eda-getting-started-guide/aap-common
  downstream/titles/eda/eda-getting-started-guide/attributes
  downstream/titles/eda/eda-getting-started-guide/eda
  downstream/titles/eda/eda-getting-started-guide/images
  downstream/titles/hub/getting-started/aap-common
  downstream/titles/hub/getting-started/attributes
  downstream/titles/hub/getting-started/hub
Labels: Archive, 2.5

#1589 AAP-27260 Add attributes for docs titles
  downstream/attributes/attributes.adoc
Labels: Ready for review, Attributes, 2.5, Needs backport to 2.5

#1692 2.5 AAP-27260 Add attributes for docs titles (#1589)
  downstream/attributes/attributes.adoc
Labels: Attributes, 2.5

#1694 Fixes #1649 (#1650)
  downstream/modules/platform/proc-add-operator-execution-nodes.adoc
Labels: documentation, 2.4, AAP operator

#1693 Fixes #1649 (#1650)
  downstream/modules/platform/proc-add-operator-execution-nodes.adoc
Labels: documentation, 2.5, AAP operator

#1697 Update inventory file variables for controller and gateway
  downstream/modules/platform/ref-controller-variables.adoc
  downstream/modules/platform/ref-gateway-variables.adoc
Labels: Needs backport to 2.4, Needs backport to 2.5

#1699 2.4 Update inventory file variables for controller and gateway (#1697)
  downstream/modules/platform/ref-controller-variables.adoc
Labels: 2.4

#1698 2.5 Update inventory file variables for controller and gateway (#1697)
  downstream/modules/platform/ref-controller-variables.adoc
  downstream/modules/platform/ref-gateway-variables.adoc
Labels: 2.5

#1700 AAP-18761-A - add assembly for the gateway dashboard
  downstream/assemblies/platform/assembly-gw-dashboard.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#1701 [Backport] AAP-18761-A - add assembly for the gateway dashboard (#1700)
  downstream/assemblies/platform/assembly-gw-dashboard.adoc
Labels: Ready for review, 2.5

#1702 AAP-23515 Doc release notes for PostgreSQL upgrade
  downstream/modules/platform/ref-controller-database-settings.adoc
Labels: Ready for review, AAP Release notes, 2.4

#1704 Update commands (#1703)
  downstream/assemblies/platform/assembly-automation-mesh-operator-aap.adoc
  downstream/modules/platform/con-about-automation-mesh.adoc
  downstream/modules/platform/con-automation-mesh-node-types.adoc
  downstream/modules/platform/proc-set-up-virtual-machines.adoc
  downstream/modules/platform/ref-operator-mesh-prerequisites.adoc
Labels: 2.5, Backported to 2.5

#1706 Add note about execution node (#1705)
  downstream/modules/platform/proc-set-up-virtual-machines.adoc
Labels: 2.5, Backported to 2.5

#1707 AAP-20599: Added info. monitoring Lightspeed onprem deployment
  lightspeed/assemblies/assembly_configuring-lightspeed-onpremise.adoc
  lightspeed/modules/con_overview-lightspeed-onpremise.adoc
  lightspeed/modules/proc_monitor-onpremise-deployment.adoc
Labels: Ready for review, Lightspeed

#1708 Updated default execution environment setting
  downstream/modules/builder/con-ee-precedence.adoc
Labels: documentation, Needs backport to 2.4, 2.4, 2.5, Needs backport to 2.5

#1710 Updated default execution environment setting (#1708)
  downstream/modules/builder/con-ee-precedence.adoc
Labels: Backported to 2.4, 2.4

#1709 Updated default execution environment setting (#1708)
  downstream/modules/builder/con-ee-precedence.adoc
Labels: 2.5, Backported to 2.5

#1662 Convert Getting started with AAP to Asciidoc
  downstream/assemblies/platform/assembly-controller-job-templates.adoc
  downstream/assemblies/platform/assembly-gs-auto-dev.adoc
  downstream/assemblies/platform/assembly-gs-auto-op.adoc
  downstream/assemblies/platform/assembly-gs-key-functionality.adoc
  downstream/assemblies/platform/assembly-gs-platform-admin.adoc
  downstream/assemblies/platform/eda
  downstream/modules/platform/con-gs-ansible-lightspeed.adoc
  downstream/modules/platform/con-gs-ansible-roles.adoc
  downstream/modules/platform/con-gs-auto-dev-about-inv.adoc
  downstream/modules/platform/con-gs-auto-dev-job-templates.adoc
  downstream/modules/platform/con-gs-auto-op-about-inv.adoc
  downstream/modules/platform/con-gs-auto-op-execute-inv.adoc
  downstream/modules/platform/con-gs-auto-op-job-templates.adoc
  downstream/modules/platform/con-gs-automation-content.adoc
  downstream/modules/platform/con-gs-automation-decisions.adoc
  downstream/modules/platform/con-gs-automation-execution-jobs.adoc
  downstream/modules/platform/con-gs-automation-execution.adoc
  downstream/modules/platform/con-gs-automation-mesh.adoc
  downstream/modules/platform/con-gs-build-decision-env.adoc
  downstream/modules/platform/con-gs-config-authentication.adoc
  downstream/modules/platform/con-gs-create-automation-content.adoc
  downstream/modules/platform/con-gs-dashboard-components.adoc
  downstream/modules/platform/con-gs-define-events-rulebooks.adoc
  downstream/modules/platform/con-gs-developer-tools.adoc
  downstream/modules/platform/con-gs-execution-env.adoc
  downstream/modules/platform/con-gs-final-set-up.adoc
  downstream/modules/platform/con-gs-learn-about-collections.adoc
  downstream/modules/platform/con-gs-manage-RBAC.adoc
  downstream/modules/platform/con-gs-manage-collections.adoc
  downstream/modules/platform/con-gs-playbooks.adoc
  downstream/modules/platform/con-gs-rulebook-activations.adoc
  downstream/modules/platform/proc-controller-create-inventory.adoc
  downstream/modules/platform/proc-controller-creating-a-team.adoc
  downstream/modules/platform/proc-controller-getting-started-with-job-templates.adoc
  downstream/modules/platform/proc-gs-add-ee-to-job-template.adoc
  downstream/modules/platform/proc-gs-auto-dev-create-automation-decision-proj.adoc
  downstream/modules/platform/proc-gs-auto-dev-create-automation-execution-proj.adoc
  downstream/modules/platform/proc-gs-auto-dev-create-template.adoc
  downstream/modules/platform/proc-gs-auto-dev-run-template.adoc
  downstream/modules/platform/proc-gs-auto-dev-set-up-decision-env.adoc
  downstream/modules/platform/proc-gs-auto-op-launch-template.adoc
  downstream/modules/platform/proc-gs-auto-op-projects.adoc
  downstream/modules/platform/proc-gs-auto-op-review-job-output.adoc
  downstream/modules/platform/proc-gs-auto-op-review-job-status.adoc
  downstream/modules/platform/proc-gs-logging-in.adoc
  downstream/modules/platform/proc-gs-platform-admin-create-user.adoc
  downstream/modules/platform/proc-gs-publish-to-a-collection.adoc
  downstream/modules/platform/proc-gs-upload-collection.adoc
  downstream/modules/platform/proc-gs-use-base-execution-env.adoc
  downstream/modules/platform/proc-gs-write-playbook.adoc
  downstream/modules/platform/ref-gs-install-config.adoc
  downstream/titles/getting-started/eda
  downstream/titles/getting-started/master.adoc
Labels: documentation, Not ready for peer review, 2.5, Needs backport to 2.5

#1711 Convert Getting started with AAP to Asciidoc (#1662)
  downstream/assemblies/platform/assembly-controller-job-templates.adoc
  downstream/assemblies/platform/assembly-gs-auto-dev.adoc
  downstream/assemblies/platform/assembly-gs-auto-op.adoc
  downstream/assemblies/platform/assembly-gs-key-functionality.adoc
  downstream/assemblies/platform/assembly-gs-platform-admin.adoc
  downstream/assemblies/platform/eda
  downstream/modules/platform/con-gs-ansible-lightspeed.adoc
  downstream/modules/platform/con-gs-ansible-roles.adoc
  downstream/modules/platform/con-gs-auto-dev-about-inv.adoc
  downstream/modules/platform/con-gs-auto-dev-job-templates.adoc
  downstream/modules/platform/con-gs-auto-op-about-inv.adoc
  downstream/modules/platform/con-gs-auto-op-execute-inv.adoc
  downstream/modules/platform/con-gs-auto-op-job-templates.adoc
  downstream/modules/platform/con-gs-automation-content.adoc
  downstream/modules/platform/con-gs-automation-decisions.adoc
  downstream/modules/platform/con-gs-automation-execution-jobs.adoc
  downstream/modules/platform/con-gs-automation-execution.adoc
  downstream/modules/platform/con-gs-automation-mesh.adoc
  downstream/modules/platform/con-gs-build-decision-env.adoc
  downstream/modules/platform/con-gs-config-authentication.adoc
  downstream/modules/platform/con-gs-create-automation-content.adoc
  downstream/modules/platform/con-gs-dashboard-components.adoc
  downstream/modules/platform/con-gs-define-events-rulebooks.adoc
  downstream/modules/platform/con-gs-developer-tools.adoc
  downstream/modules/platform/con-gs-execution-env.adoc
  downstream/modules/platform/con-gs-final-set-up.adoc
  downstream/modules/platform/con-gs-learn-about-collections.adoc
  downstream/modules/platform/con-gs-manage-RBAC.adoc
  downstream/modules/platform/con-gs-manage-collections.adoc
  downstream/modules/platform/con-gs-playbooks.adoc
  downstream/modules/platform/con-gs-rulebook-activations.adoc
  downstream/modules/platform/proc-controller-create-inventory.adoc
  downstream/modules/platform/proc-controller-creating-a-team.adoc
  downstream/modules/platform/proc-controller-getting-started-with-job-templates.adoc
  downstream/modules/platform/proc-gs-add-ee-to-job-template.adoc
  downstream/modules/platform/proc-gs-auto-dev-create-automation-decision-proj.adoc
  downstream/modules/platform/proc-gs-auto-dev-create-automation-execution-proj.adoc
  downstream/modules/platform/proc-gs-auto-dev-create-template.adoc
  downstream/modules/platform/proc-gs-auto-dev-run-template.adoc
  downstream/modules/platform/proc-gs-auto-dev-set-up-decision-env.adoc
  downstream/modules/platform/proc-gs-auto-op-launch-template.adoc
  downstream/modules/platform/proc-gs-auto-op-projects.adoc
  downstream/modules/platform/proc-gs-auto-op-review-job-output.adoc
  downstream/modules/platform/proc-gs-auto-op-review-job-status.adoc
  downstream/modules/platform/proc-gs-logging-in.adoc
  downstream/modules/platform/proc-gs-platform-admin-create-user.adoc
  downstream/modules/platform/proc-gs-publish-to-a-collection.adoc
  downstream/modules/platform/proc-gs-upload-collection.adoc
  downstream/modules/platform/proc-gs-use-base-execution-env.adoc
  downstream/modules/platform/proc-gs-write-playbook.adoc
  downstream/modules/platform/ref-gs-install-config.adoc
  downstream/titles/getting-started/eda
  downstream/titles/getting-started/master.adoc
Labels: documentation, 2.5, Backported to 2.5

#1696 Modified instructions for VM-based mesh
  downstream/assemblies/platform/assembly-setting-up-automation-mesh.adoc
  downstream/modules/platform/con-install-mesh.adoc
  downstream/modules/platform/proc-editing-inventory-file.adoc
  downstream/modules/platform/proc-running-setup-script.adoc
  downstream/titles/aap-installation-guide/master.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#1713 Modified instructions for VM-based mesh (#1696)
  downstream/assemblies/platform/assembly-setting-up-automation-mesh.adoc
  downstream/modules/platform/con-install-mesh.adoc
  downstream/modules/platform/proc-editing-inventory-file.adoc
  downstream/modules/platform/proc-running-setup-script.adoc
  downstream/titles/aap-installation-guide/master.adoc
Labels: 2.5, Backported to 2.5

#1718 Add admonition to use of installer setup script
  downstream/modules/platform/proc-running-setup-script.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#1719 Add admonition to use of installer setup script (#1718)
  downstream/modules/platform/proc-running-setup-script.adoc
Labels: 2.5, Backported to 2.5

#1725 AAP-29215 - Convert overview and auth wizard content
  downstream/modules/platform/con-gw-create-authentication.adoc
  downstream/modules/platform/con-gw-overview-access-auth.adoc
  downstream/modules/platform/con-gw-pluggable-authentication.adoc
  downstream/modules/platform/proc-gw-adjust-mapping-order.adoc
  downstream/modules/platform/proc-gw-configure-auth-details.adoc
  downstream/modules/platform/proc-gw-define-rules-triggers.adoc
  downstream/modules/platform/proc-gw-review-auth-settings.adoc
  downstream/modules/platform/proc-gw-select-auth-type.adoc
Labels: Ready for review, Technical review complete, 2.5, Needs backport to 2.5

#1714 creating con and proc modules for operator-based install
  downstream/modules/platform/con-operator-eda-controller-install.adoc
  downstream/modules/platform/proc-operator-connect-eda-to-controller.adoc
Labels: documentation, Controller, 2.4, 2.5, AAP operator

#1724 AAP-28685: Fix typo in secret example
  downstream/modules/platform/proc-create-secret-key-secret.adoc
Labels: Needs backport to 2.4, Ready for technical review, 2.4, AAP operator

#1727 Fixed broken link to Backup recommendations section (#1723)
  downstream/modules/platform/con-operator-upgrade-prereq.adoc
Labels: documentation, 2.5, AAP operator

#1728 Removing EDA 2.5 with controller 2.4 install steps
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#1729 Removing EDA 2.5 with controller 2.4 install steps (#1728)
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
Labels: documentation, 2.5, Backported to 2.5

#1720 Adding conceptual overview to asciidoc
  downstream/assemblies/platform/assembly-gs-key-functionality.adoc
  downstream/modules/platform/con-gs-ansible-lightspeed.adoc
  downstream/modules/platform/con-gs-automation-content.adoc
  downstream/modules/platform/con-gs-automation-decisions.adoc
  downstream/modules/platform/con-gs-automation-execution.adoc
  downstream/modules/platform/con-gs-automation-mesh.adoc
  downstream/modules/platform/con-gs-dashboard-components.adoc
  downstream/modules/platform/con-gs-developer-tools.adoc
  downstream/modules/platform/con-gs-final-set-up.adoc
  downstream/modules/platform/ref-gs-install-config.adoc
  downstream/titles/getting-started/docinfo.xml
  downstream/titles/getting-started/master.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#1730 Adding conceptual overview to asciidoc (#1720)
  downstream/assemblies/platform/assembly-gs-key-functionality.adoc
  downstream/modules/platform/con-gs-ansible-lightspeed.adoc
  downstream/modules/platform/con-gs-automation-content.adoc
  downstream/modules/platform/con-gs-automation-decisions.adoc
  downstream/modules/platform/con-gs-automation-execution.adoc
  downstream/modules/platform/con-gs-automation-mesh.adoc
  downstream/modules/platform/con-gs-dashboard-components.adoc
  downstream/modules/platform/con-gs-developer-tools.adoc
  downstream/modules/platform/con-gs-final-set-up.adoc
  downstream/modules/platform/ref-gs-install-config.adoc
  downstream/titles/getting-started/docinfo.xml
  downstream/titles/getting-started/master.adoc
Labels: documentation, 2.5, Backported to 2.5

#1731 Fixed broken link to Backup recommendations section (#1723)
  downstream/modules/platform/con-operator-upgrade-prereq.adoc
Labels: documentation, Backported to 2.4, 2.4, AAP operator

#1736 [Doc] System requirements are not clear for "Installing and Configuri…
  downstream/modules/central-auth/con-central-auth-reqs.adoc
Labels: documentation, Needs backport to 2.4, 2.4

#1737 AAP-29215 - Convert overview and auth wizard content (#1725)
  downstream/modules/platform/con-gw-create-authentication.adoc
  downstream/modules/platform/con-gw-overview-access-auth.adoc
  downstream/modules/platform/con-gw-pluggable-authentication.adoc
  downstream/modules/platform/proc-gw-adjust-mapping-order.adoc
  downstream/modules/platform/proc-gw-configure-auth-details.adoc
  downstream/modules/platform/proc-gw-define-rules-triggers.adoc
  downstream/modules/platform/proc-gw-review-auth-settings.adoc
  downstream/modules/platform/proc-gw-select-auth-type.adoc
Labels: Ready for review, 2.5

#1739 [Doc] System requirements are not clear for "Installing and Configuri…
  downstream/modules/central-auth/con-central-auth-reqs.adoc
Labels: documentation, Backported to 2.4, 2.4

#1740 AAP-29276a Devtools doc fixes
  downstream/modules/devtools/proc-devtools-create-aap-job.adoc
  downstream/modules/devtools/proc-devtools-install-rpm.adoc
  downstream/modules/devtools/proc-devtools-save-scm.adoc
Labels: Needs backport to 2.4, 2.4, 2.5, Needs backport to 2.5

#1738 AAP-29276 Add minimum Python 3.10 requirement to navigator doc
  downstream/modules/navigator/proc-installing-navigator-rhel-rpm.adoc
Labels: Ready for review, Needs backport to 2.4, 2.4, 2.5, Needs backport to 2.5

#1745 AAP-29215 - implement peer review and other fixes from PR1725
  downstream/modules/platform/con-gw-pluggable-authentication.adoc
  downstream/modules/platform/proc-gw-configure-auth-details.adoc
  downstream/modules/platform/proc-gw-define-rules-triggers.adoc
  downstream/modules/platform/proc-gw-review-auth-settings.adoc
  downstream/modules/platform/proc-gw-select-auth-type.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#1746 [Backport] AAP-29215 - implement peer review and other fixes from PR1725 (#1745)
  downstream/modules/platform/con-gw-pluggable-authentication.adoc
  downstream/modules/platform/proc-gw-configure-auth-details.adoc
  downstream/modules/platform/proc-gw-define-rules-triggers.adoc
  downstream/modules/platform/proc-gw-review-auth-settings.adoc
  downstream/modules/platform/proc-gw-select-auth-type.adoc
Labels: Ready for review, 2.5

#1747 Document the requirement that upgrade from 2.4 containerized TP is not supported
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/snippets/container-upgrades.adoc
Labels: Needs backport to 2.5

#1749 2.5 Document the requirement that upgrade from 2.4 containerized TP is no…
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/snippets/container-upgrades.adoc
Labels: 2.5

#1750 2.4 AAP-29354 Add Tech Preview notice to Devtools doc
  downstream/titles/develop-automation-content/master.adoc
  downstream/titles/develop-automation-content/snippets
Labels: 2.4

#1752 Updating UI steps after demo
  stories/topics/proc-saas-set-up-private.adoc
Labels: documentation, Ansible on AWS, Ready for review, SaaS on AWS

#1751 AAP-29217 - Convert authentication mapping content
  downstream/modules/platform/con-gw-authenticator-map-examples.adoc
  downstream/modules/platform/con-gw-authenticator-map-triggers.adoc
  downstream/modules/platform/con-gw-authenticator-map-types.adoc
  downstream/modules/platform/proc-gw-allow-mapping.adoc
  downstream/modules/platform/proc-gw-role-mapping.adoc
  downstream/modules/platform/proc-gw-superuser-mapping.adoc
  downstream/modules/platform/ref-controller-organization-mapping.adoc
  downstream/modules/platform/ref-controller-team-mapping.adoc
Labels: Ready for review, 2.5, Backported to 2.5

#1754 [Backport] - AAP-29217 - Convert authentication mapping content (#1751)
  downstream/modules/platform/con-gw-authenticator-map-examples.adoc
  downstream/modules/platform/con-gw-authenticator-map-triggers.adoc
  downstream/modules/platform/con-gw-authenticator-map-types.adoc
  downstream/modules/platform/proc-gw-allow-mapping.adoc
  downstream/modules/platform/proc-gw-role-mapping.adoc
  downstream/modules/platform/proc-gw-superuser-mapping.adoc
  downstream/modules/platform/ref-controller-organization-mapping.adoc
  downstream/modules/platform/ref-controller-team-mapping.adoc
Labels: Ready for review, 2.5

#1757 2.4 AAP-29500 Update subtitle in Devtools doc
  downstream/titles/develop-automation-content/docinfo.xml
Labels: 2.4

#1756 AAP-29499: Added on-prem troubleshooting cross-reference and removed on-prem monitoring content
  lightspeed/assemblies/assembly_configuring-lightspeed-onpremise.adoc
  lightspeed/modules/proc_configure-vscode-extension-onpremise-deployment.adoc
  lightspeed/modules/proc_create-connection-secrets.adoc
  lightspeed/modules/proc_create-lightspeed-instance.adoc
  lightspeed/modules/proc_create-oauth-app.adoc
  lightspeed/modules/proc_troubleshooting-lightspeed-onpremise-config.adoc
  lightspeed/modules/proc_update-connection-secrets.adoc
  lightspeed/modules/proc_update-redirect-uri.adoc
Labels: Ready for review, Lightspeed

#1758 AAP-29504 - Created snippets for repeated authentication information
  downstream/snippets/snip-gw-authentication-additional-auth-fields.adoc
  downstream/snippets/snip-gw-authentication-common-checkboxes.adoc
  downstream/snippets/snip-gw-authentication-next-steps.adoc
  downstream/snippets/snip-gw-authentication-verification.adoc
Labels: Ready for review, snippets, 2.5, Needs backport to 2.5

#1761 AAP-27079: Added info. about delay in recognizing AAP subscription
  lightspeed/modules/proc_configure-vscode-extension-onpremise-deployment.adoc
  lightspeed/modules/proc_configure-vscode-extension.adoc
Labels: Ready for review, Lightspeed

#1735 Document the Metric Collection Utility
  downstream/assemblies/platform/assembly_metrics-utility.adoc
  downstream/modules/platform/proc_configuring-the-metrics-utility.adoc
  downstream/modules/platform/proc_modifying-the-run-schedule.adoc
  downstream/modules/platform/ref_fetching-a-monthly-report.adoc
Labels: documentation, Needs backport to 2.4, 2.4, Main, 2.5, Needs backport to 2.5

#1759 AAP-29218 - Convert managing authentication content
  downstream/modules/platform/proc-gw-authentication-list-view.adoc
  downstream/modules/platform/proc-gw-delete-authenticator.adoc
  downstream/modules/platform/proc-gw-display-auth-details.adoc
  downstream/modules/platform/proc-gw-edit-authenticator.adoc
  downstream/modules/platform/proc-gw-searching-authenticator.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#1762 [Backport] AAP-29218 - Convert managing authentication content (#1759)
  downstream/modules/platform/proc-gw-authentication-list-view.adoc
  downstream/modules/platform/proc-gw-delete-authenticator.adoc
  downstream/modules/platform/proc-gw-display-auth-details.adoc
  downstream/modules/platform/proc-gw-edit-authenticator.adoc
  downstream/modules/platform/proc-gw-searching-authenticator.adoc
Labels: Ready for review, 2.5

#1764 AAP-28861- Saas intro update
  stories/assembly-saas-planning.adoc
  stories/topics/con-saas-automation.adoc
  stories/topics/con-saas-intro.adoc
  stories/topics/ref-saas-egress-model.adoc
  stories/topics/ref-saas-mesh-ingress-model.adoc
Labels: documentation, AAP on clouds, SaaS on AWS

#1755 AAP-25298: Created docs for one-click trials
  lightspeed/assemblies/assembly_setting-up-lightspeed.adoc
  lightspeed/assemblies/assembly_starting-lightspeed-trial.adoc
  lightspeed/modules/con-lightspeed-about.adoc
  lightspeed/modules/con_lightspeed-process.adoc
  lightspeed/modules/con_overview-lightspeed-onpremise.adoc
  lightspeed/modules/con_telemetry-data-collection-notice.adoc
  lightspeed/modules/con_wca-key-model-id.adoc
  lightspeed/modules/proc_create-connection-secrets.adoc
  lightspeed/modules/proc_generate-playbook.adoc
  lightspeed/modules/proc_multi-task-recs.adoc
  lightspeed/modules/proc_provide-feedback.adoc
  lightspeed/modules/proc_single-task-recs.adoc
  lightspeed/modules/proc_start-lightspeed-trial.adoc
  lightspeed/modules/proc_troubleshooting-lightspeed-onpremise-config.adoc
  lightspeed/modules/proc_troubleshooting-vscode.adoc
  lightspeed/modules/proc_view-playbook-explanation.adoc
  lightspeed/titles/lightspeed-release-notes/master.adoc
  lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-august2024.adoc
  lightspeed/titles/lightspeed-user-guide/master.adoc
Labels: Ready for review, Lightspeed

#1765 AAP-20599-update: Documented info. about monitoring Lightspeed on-premise
  lightspeed/assemblies/assembly_configuring-lightspeed-onpremise.adoc
  lightspeed/modules/con_overview-lightspeed-onpremise.adoc
  lightspeed/modules/proc_monitor-onpremise-deployment.adoc
Labels: Ready for review, Lightspeed

#1767 Adding platform admin section to asciidoc (#1734)
  downstream/assemblies/platform/assembly-gs-platform-admin.adoc
  downstream/modules/platform/con-gs-automation-content.adoc
  downstream/modules/platform/con-gs-automation-decisions.adoc
  downstream/modules/platform/con-gs-automation-execution.adoc
  downstream/modules/platform/con-gs-config-authentication.adoc
  downstream/modules/platform/con-gs-manage-RBAC.adoc
  downstream/modules/platform/proc-gs-logging-in.adoc
  downstream/modules/platform/proc-gs-platform-admin-create-user.adoc
  downstream/modules/platform/proc-gs-social-auth-github.adoc
Labels: documentation, 2.5, Backported to 2.5

#1769 AAP-29223 - Create structure for Access management and authentication
  downstream/assemblies/platform/assembly-controller-organizations.adoc
  downstream/assemblies/platform/assembly-gw-config-authentication-type.adoc
  downstream/assemblies/platform/assembly-gw-configure-authentication.adoc
  downstream/assemblies/platform/assembly-gw-managing-access.adoc
  downstream/assemblies/platform/assembly-gw-managing-authentication.adoc
  downstream/assemblies/platform/assembly-gw-mapping.adoc
  downstream/assemblies/platform/assembly-gw-roles.adoc
  downstream/assemblies/platform/assembly-gw-settings.adoc
  downstream/assemblies/platform/assembly-gw-token-based-authentication.adoc
  downstream/modules/platform/ref-controller-organization-notifications.adoc
  downstream/titles/central-auth/docinfo.xml
  downstream/titles/central-auth/master.adoc
  downstream/titles/central-auth/platform
Labels: Ready for review, 2.5, Needs backport to 2.5

#1770 Document the Metric Collection Utility (#1735)
  downstream/assemblies/platform/assembly_metrics-utility.adoc
  downstream/modules/platform/proc_configuring-the-metrics-utility.adoc
  downstream/modules/platform/proc_modifying-the-run-schedule.adoc
  downstream/modules/platform/ref_fetching-a-monthly-report.adoc
Labels: Ready for review, Controller, 2.5, Backported to 2.5

#1773 [Backport] AAP-29223 - Create structure for Access management and authentication (#1769)
  downstream/assemblies/platform/assembly-controller-organizations.adoc
  downstream/assemblies/platform/assembly-gw-config-authentication-type.adoc
  downstream/assemblies/platform/assembly-gw-configure-authentication.adoc
  downstream/assemblies/platform/assembly-gw-managing-access.adoc
  downstream/assemblies/platform/assembly-gw-managing-authentication.adoc
  downstream/assemblies/platform/assembly-gw-mapping.adoc
  downstream/assemblies/platform/assembly-gw-roles.adoc
  downstream/assemblies/platform/assembly-gw-settings.adoc
  downstream/assemblies/platform/assembly-gw-token-based-authentication.adoc
  downstream/modules/platform/ref-controller-organization-notifications.adoc
  downstream/titles/central-auth/docinfo.xml
  downstream/titles/central-auth/master.adoc
  downstream/titles/central-auth/platform
Labels: Ready for review, 2.5

#1776 Updated Schedules information
  downstream/assemblies/platform/assembly-ug-controller-schedules.adoc
  downstream/modules/platform/proc-controller-adding-new-schedule.adoc
  downstream/modules/platform/proc-controller-define-schedule-rules.adoc
Labels: documentation, Controller, 2.5, Needs backport to 2.5

#1775 Installing on Openshift Container Platform - UI updates
  downstream/assemblies/platform/assembly-installing-controller-operator.adoc
  downstream/modules/platform/proc-access-hub-operator-ui.adoc
  downstream/modules/platform/proc-add-controller-access-token.adoc
  downstream/modules/platform/proc-configuring-controller-image-pull-policy.adoc
  downstream/modules/platform/proc-configuring-controller-route-options.adoc
  downstream/modules/platform/proc-controller-ingress-options.adoc
  downstream/modules/platform/proc-create-a-user.adoc
  downstream/modules/platform/proc-create-keycloak-client.adoc
  downstream/modules/platform/proc-create-keycloak-instance.adoc
  downstream/modules/platform/proc-create-keycloak-realm.adoc
  downstream/modules/platform/proc-determine-hub-route.adoc
  downstream/modules/platform/proc-hub-ingress-options.adoc
  downstream/modules/platform/proc-hub-route-options.adoc
  downstream/modules/platform/proc-install-aap-operator.adoc
  downstream/modules/platform/proc-installing-hub-using-operator.adoc
  downstream/modules/platform/proc-installing-the-ansible-platform-operator.adoc
  downstream/modules/platform/proc-operator-access-aap.adoc
  downstream/modules/platform/proc-operator-deploy-central-config.adoc
  downstream/modules/platform/proc-operator-link-components.adoc
  downstream/modules/platform/proc-update-rhsso-client.adoc
Labels: documentation, Ready for review, 2.5, AAP operator

#1779 Installing on Openshift Container Platform - UI updates (#1775)
  downstream/assemblies/platform/assembly-installing-controller-operator.adoc
  downstream/modules/platform/proc-access-hub-operator-ui.adoc
  downstream/modules/platform/proc-add-controller-access-token.adoc
  downstream/modules/platform/proc-configuring-controller-image-pull-policy.adoc
  downstream/modules/platform/proc-configuring-controller-route-options.adoc
  downstream/modules/platform/proc-controller-ingress-options.adoc
  downstream/modules/platform/proc-create-a-user.adoc
  downstream/modules/platform/proc-create-keycloak-client.adoc
  downstream/modules/platform/proc-create-keycloak-instance.adoc
  downstream/modules/platform/proc-create-keycloak-realm.adoc
  downstream/modules/platform/proc-determine-hub-route.adoc
  downstream/modules/platform/proc-hub-ingress-options.adoc
  downstream/modules/platform/proc-hub-route-options.adoc
  downstream/modules/platform/proc-install-aap-operator.adoc
  downstream/modules/platform/proc-installing-hub-using-operator.adoc
  downstream/modules/platform/proc-installing-the-ansible-platform-operator.adoc
  downstream/modules/platform/proc-operator-access-aap.adoc
  downstream/modules/platform/proc-operator-deploy-central-config.adoc
  downstream/modules/platform/proc-operator-link-components.adoc
  downstream/modules/platform/proc-update-rhsso-client.adoc
Labels: documentation, Ready for review, 2.5, AAP operator

#1778 Updated Schedules information (#1776)
  downstream/assemblies/platform/assembly-ug-controller-schedules.adoc
  downstream/modules/platform/proc-controller-adding-new-schedule.adoc
  downstream/modules/platform/proc-controller-define-schedule-rules.adoc
Labels: Controller, 2.5, Backported to 2.5

#1781 Add EDA logging chapter to user guide
  downstream/assemblies/eda/assembly-eda-logging-strategy.adoc
  downstream/modules/eda/ref-eda-logging-samples.adoc
  downstream/titles/eda/eda-user-guide/master.adoc
Labels: Technical review complete, 2.5, Needs backport to 2.5

#1785 Add EDA logging chapter to user guide (#1781)
  downstream/assemblies/eda/assembly-eda-logging-strategy.adoc
  downstream/modules/eda/ref-eda-logging-samples.adoc
  downstream/titles/eda/eda-user-guide/master.adoc
Labels: documentation, 2.5, Backported to 2.5

#1786 AAP-29906: Updated the Starting Lightspeed trial topic with few minor updates
  lightspeed/modules/proc_start-lightspeed-trial.adoc
Labels: Ready for review, Lightspeed

#1787 AAP-29953 Fix YAML indentation in devtools example playbook
  downstream/modules/devtools/proc-devtools-writing-first-playbook.adoc
Labels: Needs backport to 2.4, 2.4, 2.5, Needs backport to 2.5

#1788 2.4 AAP-29953 Fix YAML indentation in devtools example playbook (#1787)
  downstream/modules/devtools/proc-devtools-writing-first-playbook.adoc
Labels: 2.4

#1790 AAP-28751 - Update Hub menu attributes for UI Parity work
  downstream/attributes/attributes.adoc
Labels: Ready for review, Attributes, 2.5, Needs backport to 2.5

#1791 [Backport] AAP-28751 - Update Hub menu attributes for UI Parity work (#1790)
  downstream/attributes/attributes.adoc
Labels: Ready for review, Attributes, 2.5

#1760 AAP-29213 - Convert authentication type content
  downstream/modules/platform/proc-controller-add-organization-user.adoc
  downstream/modules/platform/proc-controller-creating-a-team.adoc
  downstream/modules/platform/proc-controller-creating-a-user.adoc
  downstream/modules/platform/proc-controller-deleting-a-user.adoc
  downstream/modules/platform/proc-controller-github-enterprise-org-settings.adoc
  downstream/modules/platform/proc-controller-github-enterprise-settings.adoc
  downstream/modules/platform/proc-controller-github-enterprise-team-settings.adoc
  downstream/modules/platform/proc-controller-github-organization-setttings.adoc
  downstream/modules/platform/proc-controller-github-settings.adoc
  downstream/modules/platform/proc-controller-github-team-settings.adoc
  downstream/modules/platform/proc-controller-google-oauth2-settings.adoc
  downstream/modules/platform/proc-controller-set-up-LDAP.adoc
  downstream/modules/platform/proc-controller-set-up-SAML.adoc
  downstream/modules/platform/proc-controller-set-up-azure.adoc
  downstream/modules/platform/proc-controller-set-up-generic-oidc.adoc
  downstream/modules/platform/proc-controller-set-up-radius.adoc
  downstream/modules/platform/proc-controller-set-up-tacacs+.adoc
  downstream/modules/platform/proc-controller-user-permissions.adoc
  downstream/modules/platform/proc-gw-config-keycloak-settings.adoc
  downstream/modules/platform/proc-gw-local-authentication.adoc
  downstream/modules/platform/proc-gw-remove-roles-team.adoc
  downstream/modules/platform/proc-gw-remove-roles-user.adoc
  downstream/modules/platform/ref-controller-user-roles.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#1796 Adding deploying redis section
  downstream/modules/platform/proc-operator-deploy-redis.adoc
  downstream/titles/aap-operator-installation/master.adoc
Labels: documentation, Ready for review, 2.5, AAP operator

#1797 Adding deploying redis section (#1796)
  downstream/modules/platform/proc-operator-deploy-redis.adoc
  downstream/titles/aap-operator-installation/master.adoc
Labels: 2.5, AAP operator

#1795 AAP-29834-saas: Saas modules creation for service definition
  stories/assembly-saas-intro.adoc
  stories/assembly-saas-planning.adoc
  stories/assembly-saas-service-definition.adoc
  stories/topics/con-saas-account-management.adoc
  stories/topics/con-saas-application-monitoring-and-customer-audits.adoc
  stories/topics/con-saas-automation-mesh.adoc
  stories/topics/con-saas-backup-and-diaster-recovery.adoc
  stories/topics/con-saas-billing.adoc
  stories/topics/con-saas-connectivity.adoc
  stories/topics/con-saas-control-plane.adoc
  stories/topics/con-saas-customer-access.adoc
  stories/topics/con-saas-deployment-self-service.adoc
  stories/topics/con-saas-dns.adoc
  stories/topics/con-saas-encryption.adoc
  stories/topics/con-saas-execution-plane.adoc
  stories/topics/con-saas-hosted-components.adoc
  stories/topics/con-saas-identity-and-access-management.adoc
  stories/topics/con-saas-infastructure-monitoring.adoc
  stories/topics/con-saas-intro.adoc
  stories/topics/con-saas-limited-support-status.adoc
  stories/topics/con-saas-monitoring.adoc
  stories/topics/con-saas-networking-with-overlapping-CDIR-blocks.adoc
  stories/topics/con-saas-networking.adoc
  stories/topics/con-saas-regions.adoc
  stories/topics/con-saas-responsibilities.adoc
  stories/topics/con-saas-security.adoc
  stories/topics/con-saas-shape.adoc
  stories/topics/con-saas-sla.adoc
  stories/topics/con-saas-sre-access-and-management.adoc
  stories/topics/con-saas-status-notification.adoc
  stories/topics/con-saas-support.adoc
  titles/saas-aws/stories.adoc
Labels: documentation, AAP on clouds, Ansible on AWS, SaaS on AWS

#1792 Backport of AAP-15722: about inventory install file
  downstream/modules/platform/ref-controller-database-settings.adoc
Labels: Ready for review, 2.4

#1763 AAP-25515 EDA Credential requirements for job launches
  downstream/assemblies/eda/assembly-eda-set-up-rhaap-credential.adoc
  downstream/modules/eda/proc-eda-set-up-rhaap-credential.adoc
  downstream/titles/eda/eda-user-guide/master.adoc
Labels: Ready for review, Ready for technical review, 2.5, Needs backport to 2.5

#1800 [Backport] - AAP-29213 - Convert authentication type content (#1760)
  downstream/modules/platform/proc-controller-add-organization-user.adoc
  downstream/modules/platform/proc-controller-creating-a-team.adoc
  downstream/modules/platform/proc-controller-creating-a-user.adoc
  downstream/modules/platform/proc-controller-deleting-a-user.adoc
  downstream/modules/platform/proc-controller-github-enterprise-org-settings.adoc
  downstream/modules/platform/proc-controller-github-enterprise-settings.adoc
  downstream/modules/platform/proc-controller-github-enterprise-team-settings.adoc
  downstream/modules/platform/proc-controller-github-organization-setttings.adoc
  downstream/modules/platform/proc-controller-github-settings.adoc
  downstream/modules/platform/proc-controller-github-team-settings.adoc
  downstream/modules/platform/proc-controller-google-oauth2-settings.adoc
  downstream/modules/platform/proc-controller-set-up-LDAP.adoc
  downstream/modules/platform/proc-controller-set-up-SAML.adoc
  downstream/modules/platform/proc-controller-set-up-azure.adoc
  downstream/modules/platform/proc-controller-set-up-generic-oidc.adoc
  downstream/modules/platform/proc-controller-set-up-radius.adoc
  downstream/modules/platform/proc-controller-set-up-tacacs+.adoc
  downstream/modules/platform/proc-controller-user-permissions.adoc
  downstream/modules/platform/proc-gw-config-keycloak-settings.adoc
  downstream/modules/platform/proc-gw-local-authentication.adoc
  downstream/modules/platform/proc-gw-remove-roles-team.adoc
  downstream/modules/platform/proc-gw-remove-roles-user.adoc
  downstream/modules/platform/ref-controller-user-roles.adoc
Labels: Ready for review, 2.5

#1802 Add procedure to set registry variables
  downstream/assemblies/platform/assembly-inventory-introduction.adoc
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
  downstream/modules/platform/proc-set-registry-username-password.adoc
  downstream/modules/platform/ref-general-inventory-variables.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#1803 Add procedure to set registry variables (#1802)
  downstream/assemblies/platform/assembly-inventory-introduction.adoc
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
  downstream/modules/platform/proc-set-registry-username-password.adoc
  downstream/modules/platform/ref-general-inventory-variables.adoc
Labels: 2.5, Backported to 2.5

#1805 am-formatting-1 - Fix the formatting for the Access management and authentication guide
  downstream/assemblies/platform/assembly-gw-config-authentication-type.adoc
  downstream/assemblies/platform/assembly-gw-configure-authentication.adoc
  downstream/assemblies/platform/assembly-gw-managing-access.adoc
  downstream/assemblies/platform/assembly-gw-managing-authentication.adoc
  downstream/assemblies/platform/assembly-gw-mapping.adoc
  downstream/assemblies/platform/assembly-gw-resources.adoc
  downstream/assemblies/platform/assembly-gw-roles.adoc
  downstream/assemblies/platform/assembly-gw-settings.adoc
  downstream/assemblies/platform/assembly-gw-token-based-authentication.adoc
  downstream/modules/platform/con-gw-activity-stream.adoc
  downstream/modules/platform/con-gw-create-authentication.adoc
  downstream/modules/platform/con-gw-dash-components.adoc
  downstream/modules/platform/con-gw-dash-features.adoc
  downstream/modules/platform/con-gw-managing-access.adoc
  downstream/modules/platform/con-gw-overview-access-auth.adoc
  downstream/modules/platform/con-gw-pluggable-authentication.adoc
  downstream/modules/platform/con-gw-roles.adoc
  downstream/modules/platform/proc-controller-add-organization-user.adoc
  downstream/modules/platform/proc-controller-creating-a-user.adoc
  downstream/modules/platform/proc-controller-github-organization-settings.adoc
  downstream/modules/platform/proc-controller-set-up-SAML.adoc
  downstream/modules/platform/proc-custom-logos-images.adoc
  downstream/modules/platform/proc-gw-add-admin-team.adoc
  downstream/modules/platform/proc-gw-add-team-organization.adoc
  downstream/modules/platform/proc-gw-adjust-mapping-order.adoc
  downstream/modules/platform/proc-gw-configure-auth-details.adoc
  downstream/modules/platform/proc-gw-create-roles.adoc
  downstream/modules/platform/proc-gw-define-rules-triggers.adoc
  downstream/modules/platform/proc-gw-delete-organization.adoc
  downstream/modules/platform/proc-gw-delete-roles.adoc
  downstream/modules/platform/proc-gw-delete-team.adoc
  downstream/modules/platform/proc-gw-edit-roles.adoc
  downstream/modules/platform/proc-gw-organizations-exec-env.adoc
  downstream/modules/platform/proc-gw-remove-roles-team.adoc
  downstream/modules/platform/proc-gw-remove-roles-user.adoc
  downstream/modules/platform/proc-gw-review-auth-settings.adoc
  downstream/modules/platform/proc-gw-roles.adoc
  downstream/modules/platform/proc-gw-select-auth-type.adoc
  downstream/modules/platform/proc-gw-team-access-resources.adoc
  downstream/modules/platform/proc-gw-team-add-user.adoc
  downstream/modules/platform/proc-gw-team-list-view.adoc
  downstream/modules/platform/proc-gw-team-remove-user.adoc
  downstream/modules/platform/proc-gw-user-access-resources.adoc
  downstream/modules/platform/proc-gw-users-list-view.adoc
  downstream/modules/platform/proc-settings-platform-gateway.adoc
  downstream/snippets/snip-gw-authentication-next-steps.adoc
  downstream/snippets/snip-gw-roles-note-multiple-components.adoc
  downstream/titles/central-auth/images
  downstream/titles/central-auth/snippets
Labels: Ready for review, 2.5, Needs backport to 2.5

#1806 am-formatting-1 - Fix the formatting for the Access management guide (#1805)
  downstream/assemblies/platform/assembly-gw-config-authentication-type.adoc
  downstream/assemblies/platform/assembly-gw-configure-authentication.adoc
  downstream/assemblies/platform/assembly-gw-managing-access.adoc
  downstream/assemblies/platform/assembly-gw-managing-authentication.adoc
  downstream/assemblies/platform/assembly-gw-mapping.adoc
  downstream/assemblies/platform/assembly-gw-resources.adoc
  downstream/assemblies/platform/assembly-gw-roles.adoc
  downstream/assemblies/platform/assembly-gw-settings.adoc
  downstream/assemblies/platform/assembly-gw-token-based-authentication.adoc
  downstream/modules/platform/con-gw-activity-stream.adoc
  downstream/modules/platform/con-gw-create-authentication.adoc
  downstream/modules/platform/con-gw-dash-components.adoc
  downstream/modules/platform/con-gw-dash-features.adoc
  downstream/modules/platform/con-gw-managing-access.adoc
  downstream/modules/platform/con-gw-overview-access-auth.adoc
  downstream/modules/platform/con-gw-pluggable-authentication.adoc
  downstream/modules/platform/con-gw-roles.adoc
  downstream/modules/platform/proc-controller-add-organization-user.adoc
  downstream/modules/platform/proc-controller-creating-a-user.adoc
  downstream/modules/platform/proc-controller-github-organization-settings.adoc
  downstream/modules/platform/proc-controller-set-up-SAML.adoc
  downstream/modules/platform/proc-custom-logos-images.adoc
  downstream/modules/platform/proc-gw-add-admin-team.adoc
  downstream/modules/platform/proc-gw-add-team-organization.adoc
  downstream/modules/platform/proc-gw-adjust-mapping-order.adoc
  downstream/modules/platform/proc-gw-configure-auth-details.adoc
  downstream/modules/platform/proc-gw-create-roles.adoc
  downstream/modules/platform/proc-gw-define-rules-triggers.adoc
  downstream/modules/platform/proc-gw-delete-organization.adoc
  downstream/modules/platform/proc-gw-delete-roles.adoc
  downstream/modules/platform/proc-gw-delete-team.adoc
  downstream/modules/platform/proc-gw-edit-roles.adoc
  downstream/modules/platform/proc-gw-organizations-exec-env.adoc
  downstream/modules/platform/proc-gw-remove-roles-team.adoc
  downstream/modules/platform/proc-gw-remove-roles-user.adoc
  downstream/modules/platform/proc-gw-review-auth-settings.adoc
  downstream/modules/platform/proc-gw-roles.adoc
  downstream/modules/platform/proc-gw-select-auth-type.adoc
  downstream/modules/platform/proc-gw-team-access-resources.adoc
  downstream/modules/platform/proc-gw-team-add-user.adoc
  downstream/modules/platform/proc-gw-team-list-view.adoc
  downstream/modules/platform/proc-gw-team-remove-user.adoc
  downstream/modules/platform/proc-gw-user-access-resources.adoc
  downstream/modules/platform/proc-gw-users-list-view.adoc
  downstream/modules/platform/proc-settings-platform-gateway.adoc
  downstream/snippets/snip-gw-authentication-next-steps.adoc
  downstream/snippets/snip-gw-roles-note-multiple-components.adoc
  downstream/titles/central-auth/images
  downstream/titles/central-auth/snippets
Labels: Ready for review, 2.5
