Repository ansible/aap-docs, pull requests merged in 2024-01, with the labels that each got.

#916 AAP-13268-B fixed broken xrefs in PR 886 (#906)
  .vscode/settings.json
  downstream/modules/platform/ref-controller-performance-troubleshooting.adoc
Labels: 2.4

#917 AAP-19239 fix formatting issues for ch 14 Controller Admin Guide
  downstream/modules/platform/ref-controller-metrics-monitoring.adoc
  downstream/modules/platform/ref-controller-settings-to-modify-events.adoc
  downstream/modules/platform/ref-scaling-control-nodes.adoc
Labels: Ready for review, 2.4

#918 AAP-19239 fix formatting issues for ch 14 Controller Admin Guide (#917)
  downstream/modules/platform/ref-controller-metrics-monitoring.adoc
  downstream/modules/platform/ref-controller-settings-to-modify-events.adoc
  downstream/modules/platform/ref-scaling-control-nodes.adoc
Labels: 2.4

#921 Move template files to templates directory
  downstream/templates/aap-rn-template.adoc
  downstream/templates/assembly-rn-template.adoc
  downstream/templates/controller-rn-template.adoc
  downstream/templates/hub-rn-template.adoc
  downstream/templates/operator-rn-template.adoc
Labels: Ready for review, Needs backport to 2.4

#922 Move template files to templates directory (#921)
  downstream/templates/aap-rn-template.adoc
  downstream/templates/assembly-rn-template.adoc
  downstream/templates/controller-rn-template.adoc
  downstream/templates/hub-rn-template.adoc
  downstream/templates/operator-rn-template.adoc
Labels: 2.4

#923 AAP-19195: Removed single-tenant references
  lightspeed/modules/con-lightspeed-about.adoc
  lightspeed/modules/con_lightspeed-key-features.adoc
  lightspeed/modules/con_training-data.adoc
  lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-25oct2023.adoc
Labels: Lightspeed

#925 bp 2.4: AAP-15176 fix broken link in installation guide (#920)
  downstream/modules/platform/ref-hub-configs.adoc
Labels: 2.4

#924 AAP-15176: Fix broken links in controller user guide
  downstream/modules/platform/con-controller-overview-details.adoc
  downstream/modules/platform/proc-controller-create-job-template.adoc
  downstream/modules/platform/ref-controller-credential-machine.adoc
  downstream/modules/platform/ref-controller-group-name-vars-filtering.adoc
Labels: Needs backport to 2.4, Controller, 2.4, Main

#926 Backport to 2.4: AAP-15176 Fix broken links in controller user guide (#924)
  downstream/modules/platform/con-controller-overview-details.adoc
  downstream/modules/platform/proc-controller-create-job-template.adoc
  downstream/modules/platform/ref-controller-credential-machine.adoc
  downstream/modules/platform/ref-controller-group-name-vars-filtering.adoc
Labels: Ready for review, Controller, 2.4

#887 Azure Add RH account sign-in to deployment engine driver
  stories/topics/proc-azure-monitor-deployment-engine.adoc
Labels: AAP on clouds, AAP on Azure, Technical review complete

#929 AAP-19320: Add info. About AAP and IBM WCA trial and paid plans
  lightspeed/modules/con-lightspeed-about.adoc
  lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-25oct2023.adoc
Labels: Lightspeed

#927 AAP-16022 - updated the information to state admin is default userid
  downstream/modules/platform/con-install-scenario-recommendations.adoc
  downstream/modules/platform/proc-verify-controller-installation.adoc
  downstream/modules/platform/proc-verify-eda-controller-installation.adoc
  downstream/modules/platform/proc-verify-hub-installation.adoc
Labels: Ready for review, Needs backport to 2.4, 2.4

#915 AAP-18088: adds info on download count configuration; fixes a namespace error
  downstream/assemblies/platform/assembly-installing-hub-operator.adoc
  downstream/modules/platform/proc-installing-hub-using-operator.adoc
  downstream/modules/platform/ref-ocp-additional-configs.adoc
Labels: 2.3, Needs backport to 2.4, Needs backport to 2.3, Automation Hub, 2.4, Main

#934 Fix missing link in Red Hat AAP Installation Guide (#932)
  downstream/modules/platform/con-aap-installation-on-disconnected-rhel.adoc
Labels: 2.4

#938 AAP-15176: broken link fix in controller admin guide
  downstream/modules/platform/ref-controller-clear-sessions.adoc
Labels: Needs backport to 2.4, Controller, 2.4, Main

#928 Azure: AAP-18006 Automation mesh now available on Azure
  attributes/attributes.adoc
  stories/topics/con-azure-about.adoc
Labels: AAP on clouds, Ready for review, AAP on Azure, Technical review complete

#940 backport to 2.4: AAP-15176 fix link in controller admin guide
  downstream/modules/platform/ref-controller-clear-sessions.adoc
Labels: Controller, 2.4

#947 [Backport] AAP-16022 - updated the information to state admin is default userid (#927)
  downstream/modules/platform/con-install-scenario-recommendations.adoc
  downstream/modules/platform/proc-verify-controller-installation.adoc
  downstream/modules/platform/proc-verify-eda-controller-installation.adoc
  downstream/modules/platform/proc-verify-hub-installation.adoc
Labels: Ready for review, 2.4

#594 AAP-16378 Added ldap-ca.crt for the LDAP certificate selection
  downstream/modules/platform/proc-configuring-controller-ldap-security.adoc
Labels: Ready for review, 2.3, Needs backport to 2.4, Needs backport to 2.3, 2.4

#952 Corrrected links in Controller UG
  downstream/modules/platform/proc-controller-create-job-template.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#955 AAP-19290: Fixed typo in Lightspeed docs
  lightspeed/modules/con_overview-and-best-practices.adoc
Labels: Lightspeed

#956 Added information on LDAP referrals
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
  downstream/modules/platform/ref-ldap-referrals.adoc
Labels: Needs backport to 2.4, Technical review complete, 2.4

#958 Added information on LDAP referrals (#956)
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
  downstream/modules/platform/ref-ldap-referrals.adoc
Labels: Backported to 2.4, 2.4

#961 Azure: update architecture diagrams
  archive/archived-images/aap-19680-aap-on-azure-private-deployment.png
  archive/archived-images/aap-19680-aap-on-azure-public-deployment.png
  images/aap-on-azure-private-deployment.png
  images/aap-on-azure-public-deployment.png
Labels: AAP on clouds, AAP on Azure

#963 Fixing incorrect UI in controller user guide
  downstream/modules/platform/proc-controller-creating-a-user.adoc
  downstream/modules/platform/ref-controller-user-roles.adoc
  downstream/modules/platform/ref-controller-user-teams.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.4

#964 Fixing incorrect UI in controller user guide (#963)
  downstream/modules/platform/proc-controller-creating-a-user.adoc
  downstream/modules/platform/ref-controller-user-roles.adoc
  downstream/modules/platform/ref-controller-user-teams.adoc
Labels: documentation, Backported to 2.4, Controller, 2.4

#966 AAP-19350
  downstream/modules/platform/ref-ldap-config-on-pah.adoc
Labels: Draft, Needs backport to 2.4, Needs backport to 2.3

#968 Remove duplicate automation mesh attribute
  downstream/attributes/attributes.adoc
Labels: Ready for review, Needs backport to 2.4

#969 Remove duplicate automation mesh attribute (#968)
  downstream/attributes/attributes.adoc
Labels: 2.4

#970 Backport 2.3 #966
  downstream/assemblies/.vscode/settings.json
  downstream/modules/platform/ref-ldap-config-on-pah.adoc
  lightspeed/assemblies/.vscode/settings.json
Labels: Ready for review, Needs backport to 2.3

#971 Backport 2.4 966
  downstream/modules/platform/ref-ldap-config-on-pah.adoc
Labels: Ready for review, Backported to 2.4

#972 Create Getting started with Ansible Playbooks guide
  downstream/assemblies/playbooks/asembly-playbook-gs.adoc
  downstream/titles/playbooks/playbooks-getting-started/assemblies
  downstream/titles/playbooks/playbooks-getting-started/attributes
  downstream/titles/playbooks/playbooks-getting-started/images
  downstream/titles/playbooks/playbooks-getting-started/master.adoc
  downstream/titles/playbooks/playbooks-getting-started/modules
  downstream/titles/playbooks/playbooks-getting-started/playbooks
Labels: documentation, Needs backport to 2.4, 2.4

#974 Create Getting started with Ansible Playbooks guide (#972)
  downstream/assemblies/playbooks/asembly-playbook-gs.adoc
  downstream/titles/playbooks/playbooks-getting-started/assemblies
  downstream/titles/playbooks/playbooks-getting-started/attributes
  downstream/titles/playbooks/playbooks-getting-started/images
  downstream/titles/playbooks/playbooks-getting-started/master.adoc
  downstream/titles/playbooks/playbooks-getting-started/modules
  downstream/titles/playbooks/playbooks-getting-started/playbooks
Labels: documentation, Backported to 2.4, 2.4

#975 Updating Repository Organization chart and bullets
  README.adoc
Labels: documentation

#919 AAP17100 - Updated web and task replicas
  downstream/modules/platform/proc-installing-hub-using-operator.adoc
Labels: Ready for review, Needs backport to 2.4, Technical review complete, 2.4

#976 [Backport] AAP17100 - Updated web and task replicas (#919)
  downstream/modules/platform/proc-installing-hub-using-operator.adoc
Labels: 2.4

#948 AAP-14300 Add verification steps for controller backup and restore
  downstream/modules/platform/proc-aap-controller-backup.adoc
  downstream/modules/platform/proc-aap-controller-restore.adoc
  downstream/modules/platform/proc-aap-hub-backup.adoc
Labels: Ready for review, 2.3, Needs backport to 2.4, Needs backport to 2.3, Technical review complete, 2.4

#957 AAP-17700: Updates to Builder documentation
  downstream/assemblies/builder/assembly-definition-file-breakdown.adoc
  downstream/modules/builder/con-additional-build-files.adoc
  downstream/modules/builder/con-additional-custom-build-steps.adoc
  downstream/modules/builder/con-building-definition-file.adoc
  downstream/modules/builder/con-container_file.adoc
  downstream/modules/builder/con-definition-dependencies.adoc
  downstream/modules/builder/con-galaxy-dependencies.adoc
  downstream/modules/builder/con-optional-build-command-arguments.adoc
  downstream/modules/builder/con-python-dependencies.adoc
  downstream/modules/builder/con-system-dependencies.adoc
  downstream/modules/builder/con-why-builder.adoc
  downstream/modules/builder/proc-installing-builder.adoc
  downstream/modules/builder/ref-definition-file-images.adoc
Labels: Needs backport to 2.4, Main

#977 Backport to 2.4: Updates to Builder Documentation
  downstream/assemblies/builder/assembly-definition-file-breakdown.adoc
  downstream/modules/builder/con-additional-build-files.adoc
  downstream/modules/builder/con-additional-custom-build-steps.adoc
  downstream/modules/builder/con-building-definition-file.adoc
  downstream/modules/builder/con-container_file.adoc
  downstream/modules/builder/con-definition-dependencies.adoc
  downstream/modules/builder/con-galaxy-dependencies.adoc
  downstream/modules/builder/con-optional-build-command-arguments.adoc
  downstream/modules/builder/con-python-dependencies.adoc
  downstream/modules/builder/con-system-dependencies.adoc
  downstream/modules/builder/con-why-builder.adoc
  downstream/modules/builder/proc-installing-builder.adoc
  downstream/modules/builder/ref-definition-file-images.adoc
Labels: 2.4

#978 [Backport] AAP-14300 Add verification steps for controller backup and restore (#948)
  downstream/modules/platform/proc-aap-controller-backup.adoc
  downstream/modules/platform/proc-aap-controller-restore.adoc
  downstream/modules/platform/proc-aap-hub-backup.adoc
Labels: 2.3

#979 [Backport] AAP-14300 Add verification steps for controller backup and restore (#948)
  downstream/modules/platform/proc-aap-controller-backup.adoc
  downstream/modules/platform/proc-aap-controller-restore.adoc
  downstream/modules/platform/proc-aap-hub-backup.adoc
Labels: 2.4

#973 AAP-10305 modified hub signing procedures
  downstream/modules/hub/proc-configuring-the-client-to-verify-signatures.adoc
  downstream/modules/hub/proc-deploying-your-system-for-container-signing.adoc
  downstream/modules/hub/proc-pushing-container-images-from-your-local.adoc
Labels: Ready for review, Technical review complete, 2.4

#982 AAP-10305 modified hub signing procedures (#973)
  downstream/modules/automation-hub/proc-configuring-the-client-to-verify-signatures.adoc
  downstream/modules/automation-hub/proc-deploying-your-system-for-container-signing.adoc
  downstream/modules/automation-hub/proc-pushing-container-images-from-your-local.adoc
Labels: Ready for review, 2.3

#985 AAP-20092: Specified the repo Settings button for manual scan
  lightspeed/modules/proc_manually-scan-repo.adoc
Labels: documentation, Lightspeed

#984 AAP-10252: add procedure for LDAP authentication for hub on OCP
  downstream/assemblies/platform/assembly-installing-hub-operator.adoc
  downstream/modules/platform/proc-configure-ldap-hub-ocp.adoc
Labels: 2.3, Needs backport to 2.4, Needs backport to 2.3, Technical review complete, Automation Hub, 2.4, Main

#986 backport to 2.4: AAP-10252 add procedure for LDAP authentication for hub on OCP (#984)
  downstream/assemblies/platform/assembly-installing-hub-operator.adoc
  downstream/modules/platform/proc-configure-ldap-hub-ocp.adoc
Labels: 2.4

#987 Backport to 2.3: AAP-10252 add procedure for LDAP authentication for hub on OCP (#984)
  downstream/assemblies/platform/assembly-installing-hub-operator.adoc
  downstream/modules/platform/proc-configure-ldap-hub-ocp.adoc
Labels: 2.3
