Repository ansible/aap-docs, pull requests merged in 2024-10, with the labels that each got.

#2228 RPM installation guide: Add enterprise inventory file link
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
Labels: documentation, Ready for technical review, Technical review complete, 2.5, Needs backport to 2.5

#2235 AAP-32244 updated links
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#2236 Correct typo in appendix variables section
  downstream/modules/platform/ref-general-inventory-variables.adoc
Labels: 2.5, Needs backport to 2.5

#2237 2.5 Correct typo in appendix variables section (#2236)
  downstream/modules/platform/ref-general-inventory-variables.adoc
Labels: 2.5

#2238 Update git to git-core in containerized install
  downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc
Labels: 2.5, Needs backport to 2.5

#2239 2.5 Update git to git-core in containerized install (#2238)
  downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc
Labels: 2.5

#2240 AAP-32244 updated links (#2235)
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
Labels: Ready for review, 2.5

#2242 AAP-30989 RHDH Add collection naming convention requirements
  downstream/modules/devtools/proc-rhdh-create.adoc
Labels: Needs backport to 2.4, 2.4, 2.5, Needs backport to 2.5

#2241 AAP-29062 RHDH Add requirement for developer hub portal account
  downstream/assemblies/devtools/assembly-rhdh-using.adoc
Labels: Needs backport to 2.4, 2.4, 2.5, Needs backport to 2.5

#2244 AAP-29062 RHDH Add requirement for developer hub portal account (#2241)
  downstream/assemblies/devtools/assembly-rhdh-using.adoc
Labels: 2.5

#2245 AAP-29062 RHDH Add requirement for developer hub portal account (#2241)
  downstream/assemblies/devtools/assembly-rhdh-using.adoc
Labels: 2.4

#2246 2.5 AAP-30989 RHDH Add collection naming convention requirements (#2242)
  downstream/modules/devtools/proc-rhdh-create.adoc
Labels: 2.5

#2247 2.4 AAP-30989 RHDH Add collection naming convention requirements (#2242)
  downstream/modules/devtools/proc-rhdh-create.adoc
Labels: 2.4

#2250 AAP-32244 fixed links in using AA (#2248)
  downstream/modules/analytics/con-jobs-explorer.adoc
  downstream/modules/analytics/proc-ignoring-nested-workflows-jobs.adoc
Labels: Ready for review, 2.5

#2234 [2.5] RPM installation guide: Add enterprise inventory file link (#2228)
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
Labels: documentation, 2.5, Backported to 2.5

#2253 backport to 2.5: minor UI updates (#2233)
  downstream/assemblies/hub/assembly-delete-container.adoc
  downstream/modules/hub/con-approval-pipeline.adoc
  downstream/modules/hub/con-container-registry.adoc
  downstream/modules/hub/proc-add-container-readme.adoc
  downstream/modules/hub/proc-approve-collection.adoc
  downstream/modules/hub/proc-create-credential.adoc
  downstream/modules/hub/proc-export-collection.adoc
  downstream/modules/hub/proc-push-container.adoc
  downstream/modules/hub/proc-pushing-container-images-from-your-local.adoc
  downstream/modules/hub/proc-reject-collections.adoc
  downstream/modules/hub/proc-revert-repository-version.adoc
  downstream/modules/hub/proc-sync-image.adoc
  downstream/modules/hub/proc-tag-image.adoc
Labels: 2.5

#2255 Fix broken link in RPM install guide
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#2257 [2.5] RPM-fix-link:Remove Squiggly line (#2255)
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
Labels: documentation, 2.5, Backported to 2.5

#2256 2.4 AAP-30912 Devtools - Add roles collections chapter (#2148)
  downstream/assemblies/devtools/assembly-devtools-create-roles-collection.adoc
  downstream/assemblies/devtools/assembly-devtools-develop-collections.adoc
  downstream/modules/devtools/con-devtools-plan-roles-collection.adoc
  downstream/modules/devtools/con-devtools-roles-collection-prerequisites.adoc
  downstream/modules/devtools/proc-devtools-create-new-role-in-collection.adoc
  downstream/modules/devtools/proc-devtools-docs-roles-collection.adoc
  downstream/modules/devtools/proc-devtools-migrate-existing-roles-collection.adoc
  downstream/modules/devtools/proc-devtools-molecule-test-roles-collection.adoc
  downstream/modules/devtools/proc-devtools-publish-roles-collection-pah.adoc
  downstream/modules/devtools/proc-devtools-run-roles-collection.adoc
  downstream/modules/devtools/proc-devtools-scaffold-roles-collection.adoc
  downstream/modules/devtools/proc-devtools-use-roles-collections-aap.adoc
  downstream/titles/develop-automation-content/master.adoc
Labels: Draft, 2.4

#2259 Fixed broken links in Installation Guide
  downstream/assemblies/platform/assembly-disconnected-installation.adoc
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
  downstream/modules/platform/con-aap-installation-prereqs.adoc
  downstream/modules/platform/proc-completing-post-installation-tasks.adoc
  downstream/modules/platform/ref-automation-hub-requirements.adoc
  downstream/modules/platform/ref-controller-system-requirements.adoc
  downstream/modules/platform/ref-eda-system-requirements.adoc
  downstream/modules/platform/ref-gateway-variables.adoc
  downstream/modules/platform/ref-postgresql-requirements.adoc
  downstream/modules/platform/ref-system-requirements.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#2251 Edits to UI in using automation execution
  downstream/assemblies/platform/assembly-controller-instances.adoc
  downstream/modules/platform/con-controller-notification-workflow.adoc
  downstream/modules/platform/proc-controller-add-users-job-templates.adoc
  downstream/modules/platform/proc-controller-associate-instances-to-instance-group.adoc
  downstream/modules/platform/proc-controller-create-container-group.adoc
  downstream/modules/platform/proc-controller-create-credential-type.adoc
  downstream/modules/platform/proc-controller-create-credential.adoc
  downstream/modules/platform/proc-controller-create-custom-notifications.adoc
  downstream/modules/platform/proc-controller-create-host.adoc
  downstream/modules/platform/proc-controller-create-insights-credential.adoc
  downstream/modules/platform/proc-controller-create-insights-project.adoc
  downstream/modules/platform/proc-controller-create-instance-group.adoc
  downstream/modules/platform/proc-controller-create-notification-template.adoc
  downstream/modules/platform/proc-controller-customize-pod-spec.adoc
  downstream/modules/platform/proc-controller-inv-source-aap.adoc
  downstream/modules/platform/proc-controller-inv-source-rh-virt.adoc
  downstream/modules/platform/proc-controller-inv-source-terraform.adoc
  downstream/modules/platform/proc-controller-remediate-insights-inventory.adoc
  downstream/modules/platform/proc-controller-set-up-github-webhook.adoc
  downstream/modules/platform/proc-controller-verify-container-group.adoc
  downstream/modules/platform/proc-controller-view-host.adoc
  downstream/modules/platform/ref-controller-content-sourcing.adoc
  downstream/modules/platform/ref-controller-credential-machine.adoc
  downstream/modules/platform/ref-controller-credential-network.adoc
  downstream/modules/platform/ref-controller-credential-openShift.adoc
  downstream/modules/platform/ref-controller-credential-openStack.adoc
  downstream/modules/platform/ref-controller-credential-terraform.adoc
  downstream/modules/platform/ref-controller-credential-vault.adoc
  downstream/modules/platform/ref-removing-instances.adoc
Labels: documentation, Controller, 2.5, Needs backport to 2.5

#2262 Update inventory files to allow for copy/paste
  downstream/modules/platform/proc-installing-containerized-aap.adoc
Labels: 2.5, Needs backport to 2.5

#2261 Edits to UI in using automation execution (#2251)
  downstream/assemblies/platform/assembly-controller-instances.adoc
  downstream/modules/platform/con-controller-notification-workflow.adoc
  downstream/modules/platform/proc-controller-add-users-job-templates.adoc
  downstream/modules/platform/proc-controller-associate-instances-to-instance-group.adoc
  downstream/modules/platform/proc-controller-create-container-group.adoc
  downstream/modules/platform/proc-controller-create-credential-type.adoc
  downstream/modules/platform/proc-controller-create-credential.adoc
  downstream/modules/platform/proc-controller-create-custom-notifications.adoc
  downstream/modules/platform/proc-controller-create-host.adoc
  downstream/modules/platform/proc-controller-create-insights-credential.adoc
  downstream/modules/platform/proc-controller-create-insights-project.adoc
  downstream/modules/platform/proc-controller-create-instance-group.adoc
  downstream/modules/platform/proc-controller-create-notification-template.adoc
  downstream/modules/platform/proc-controller-customize-pod-spec.adoc
  downstream/modules/platform/proc-controller-inv-source-aap.adoc
  downstream/modules/platform/proc-controller-inv-source-rh-virt.adoc
  downstream/modules/platform/proc-controller-inv-source-terraform.adoc
  downstream/modules/platform/proc-controller-remediate-insights-inventory.adoc
  downstream/modules/platform/proc-controller-set-up-github-webhook.adoc
  downstream/modules/platform/proc-controller-verify-container-group.adoc
  downstream/modules/platform/proc-controller-view-host.adoc
  downstream/modules/platform/ref-controller-content-sourcing.adoc
  downstream/modules/platform/ref-controller-credential-machine.adoc
  downstream/modules/platform/ref-controller-credential-network.adoc
  downstream/modules/platform/ref-controller-credential-openShift.adoc
  downstream/modules/platform/ref-controller-credential-openStack.adoc
  downstream/modules/platform/ref-controller-credential-terraform.adoc
  downstream/modules/platform/ref-controller-credential-vault.adoc
  downstream/modules/platform/ref-removing-instances.adoc
Labels: documentation, Controller, 2.5, Backported to 2.5

#2263 2.5 Update inventory files to allow for copy/paste (#2262)
  downstream/modules/platform/proc-installing-containerized-aap.adoc
Labels: 2.5

#2260 Backport 2559 to 25
  downstream/assemblies/platform/assembly-disconnected-installation.adoc
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
  downstream/modules/platform/con-aap-installation-prereqs.adoc
  downstream/modules/platform/proc-completing-post-installation-tasks.adoc
  downstream/modules/platform/ref-automation-hub-requirements.adoc
  downstream/modules/platform/ref-controller-system-requirements.adoc
  downstream/modules/platform/ref-eda-system-requirements.adoc
  downstream/modules/platform/ref-gateway-variables.adoc
  downstream/modules/platform/ref-postgresql-requirements.adoc
  downstream/modules/platform/ref-system-requirements.adoc
Labels: 2.5, Backported to 2.5

#2264 Update inventory file code blocks to allow copy paste
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/topologies/ref-cont-a-env-a.adoc
  downstream/modules/topologies/ref-cont-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-b.adoc
Labels: 2.5, Needs backport to 2.5

#2265 2.5 Update inventory file code blocks to allow copy paste (#2264)
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/topologies/ref-cont-a-env-a.adoc
  downstream/modules/topologies/ref-cont-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-b.adoc
Labels: 2.5

#2266 2.4 Add bundle 2.4-7.4 to release notes
  downstream/titles/release-notes/master.adoc
  downstream/titles/release-notes/topics/installer-24-74.adoc
  downstream/titles/release-notes/topics/installer-version-table.adoc
Labels: 2.4

#2267 AAP-32244 fixed incorrect links
  downstream/assemblies/topologies/assembly-overview-tested-deployment-models.adoc
  downstream/modules/platform/ref-OCP-system-requirements.adoc
  downstream/modules/platform/ref-containerized-system-requirements.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#2243 Adding SME edits from Draft 4
  images/automation_mesh.png
  images/mesh_egress.png
  images/mesh_ingress.png
  stories/assembly-saas-intro.adoc
  stories/assembly-saas-post-install-config.adoc
  stories/assembly-saas-set-up.adoc
  stories/assembly-saas-subscribing.adoc
  stories/topics/con-saas-application-monitoring-and-customer-audits.adoc
  stories/topics/con-saas-automation-mesh.adoc
  stories/topics/con-saas-automation.adoc
  stories/topics/con-saas-backup-and-diaster-recovery.adoc
  stories/topics/con-saas-billing.adoc
  stories/topics/con-saas-connectivity.adoc
  stories/topics/con-saas-control-plane.adoc
  stories/topics/con-saas-customer-access.adoc
  stories/topics/con-saas-dns.adoc
  stories/topics/con-saas-encryption.adoc
  stories/topics/con-saas-execution-plane.adoc
  stories/topics/con-saas-hosted-components.adoc
  stories/topics/con-saas-identity-and-access-management.adoc
  stories/topics/con-saas-infastructure-monitoring.adoc
  stories/topics/con-saas-intro.adoc
  stories/topics/con-saas-limited-support-status.adoc
  stories/topics/con-saas-monitoring.adoc
  stories/topics/con-saas-networking-with-overlapping-CDIR-blocks.adoc
  stories/topics/con-saas-provisioning.adoc
  stories/topics/con-saas-shape.adoc
  stories/topics/con-saas-sre-access-and-management.adoc
  stories/topics/con-saas-status-notification.adoc
  stories/topics/con-saas-support.adoc
  stories/topics/con-saas-updates-and-maintenance.adoc
  stories/topics/proc-saas-set-up-private.adoc
  stories/topics/proc-saas-set-up-public.adoc
  stories/topics/ref-saas-default-configs.adoc
  stories/topics/ref-saas-egress-model.adoc
  stories/topics/ref-saas-mesh-ingress-model.adoc
  stories/topics/ref-saas-planning-configs.adoc
  titles/saas-aws/stories.adoc
Labels: documentation, AAP on clouds, Ready for review, SaaS on AWS

#2258 AAP-31661-update2: Added known issue and deprecated APIs
  downstream/titles/release-notes/topics/aap-25-deprecated-features.adoc
  downstream/titles/release-notes/topics/aap-25-known-issues.adoc
Labels: Ready for review, AAP Release notes, Needs backport to 2.5

#2269 Backport pull request #2258 from main to 2.5
  downstream/titles/release-notes/topics/aap-25-deprecated-features.adoc
  downstream/titles/release-notes/topics/aap-25-known-issues.adoc
Labels: Ready for review, AAP Release notes, 2.5, Backported to 2.5

#2270 backport-2.5-2267
  downstream/assemblies/topologies/assembly-overview-tested-deployment-models.adoc
  downstream/modules/platform/ref-OCP-system-requirements.adoc
  downstream/modules/platform/ref-containerized-system-requirements.adoc
Labels: Ready for review, 2.5

#2268 2.4 Correct formatting issue in 2.4 async release notes
  downstream/titles/release-notes/topics/rpm-24-74.adoc
Labels: 2.4

#2273 AAP-31240: Updated the Telemetry docs per customer ask
  lightspeed/assemblies/assembly_managing-admin-dashboard-telemetry.adoc
  lightspeed/modules/con_telemetry-data-collection-notice.adoc
  lightspeed/modules/con_training-data.adoc
Labels: Ready for review, Lightspeed

#2274 2.5 Add new title for updating aap from 2.5 to 2.5.x (#2271)
  downstream/assemblies/platform/assembly-update-rpm.adoc
  downstream/modules/platform/con-update-planning.adoc
  downstream/modules/platform/proc-update-aap-on-ocp.adoc
  downstream/titles/updating-aap/aap-common
  downstream/titles/updating-aap/attributes
  downstream/titles/updating-aap/docinfo.xml
  downstream/titles/updating-aap/images
  downstream/titles/updating-aap/master.adoc
  downstream/titles/updating-aap/platform
Labels: 2.5

#2272 AAP-30340: Updated code bot docs per getting started improvements
  lightspeed/assemblies/assembly_using-code-bot-for-suggestions.adoc
  lightspeed/images/code-bot-initial-pr.png
  lightspeed/modules/proc_configure-repo-scan.adoc
  lightspeed/modules/proc_install-code-bot.adoc
Labels: Ready for review, Lightspeed

#2275 Update module reference link to ensure title builds successfully
  downstream/titles/updating-aap/master.adoc
Labels: 2.5, Needs backport to 2.5

#2276 2.5 Update module reference link to ensure title builds successfully (#2275)
  downstream/titles/updating-aap/master.adoc
Labels: 2.5

#2279 Update Containerized installation guide
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/platform/proc-add-eda-safe-plugin-var.adoc
  downstream/modules/platform/proc-downloading-containerized-aap.adoc
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc
  downstream/modules/platform/proc-uninstalling-containerized-aap.adoc
  downstream/modules/platform/proc-using-postinstall.adoc
  downstream/modules/platform/ref-accessing-control-auto-hub-eda-control.adoc
  downstream/modules/platform/ref-controller-variables.adoc
  downstream/modules/platform/ref-database-inventory-variables.adoc
  downstream/modules/platform/ref-eda-controller-variables.adoc
  downstream/modules/platform/ref-enabling-automation-hub-collection-and-container-signing.adoc
  downstream/modules/platform/ref-gateway-variables.adoc
  downstream/modules/platform/ref-hub-variables.adoc
  downstream/modules/platform/ref-using-custom-receptor-signing-keys.adoc
Labels: 2.5, Needs backport to 2.5

#2282 Update ansible-core version and PostgreSQL version in topologies
  downstream/modules/topologies/ref-cont-a-env-a.adoc
  downstream/modules/topologies/ref-cont-b-env-a.adoc
  downstream/modules/topologies/ref-ocp-a-env-a.adoc
  downstream/modules/topologies/ref-ocp-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-b.adoc
Labels: 2.5, Needs backport to 2.5

#2283 2.5 Update ansible-core version and PostgreSQL version in topologies (#2282)
  downstream/modules/topologies/ref-cont-a-env-a.adoc
  downstream/modules/topologies/ref-cont-b-env-a.adoc
  downstream/modules/topologies/ref-ocp-a-env-a.adoc
  downstream/modules/topologies/ref-ocp-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-b.adoc
Labels: 2.5

#2284 fixing OCP title
  downstream/titles/aap-operator-installation/docinfo.xml
  downstream/titles/aap-operator-installation/master.adoc
Labels: documentation, 2.5, AAP operator, Needs backport to 2.5

#2285 fixing OCP title (#2284)
  downstream/titles/aap-operator-installation/docinfo.xml
  downstream/titles/aap-operator-installation/master.adoc
Labels: 2.5, AAP operator

#2278 Add disconnected execution environments to doc
  downstream/assemblies/builder/assembly-using-builder.adoc
  downstream/assemblies/builder/platform
  downstream/modules/platform/con-building-an-execution-environment-in-a-disconnected-environment.adoc
  downstream/titles/builder/master.adoc
  downstream/titles/builder/platform
Labels: 2.5, Needs backport to 2.5

#2290 dd-2286 - fix conversion issues in the Updating guide
  downstream/assemblies/platform/assembly-update-container.adoc
  downstream/assemblies/platform/assembly-update-ocp.adoc
  downstream/assemblies/platform/assembly-update-rpm.adoc
  downstream/modules/platform/proc-backup-aap-container.adoc
  downstream/modules/platform/proc-backup-aap-rpm.adoc
  downstream/modules/platform/proc-installing-with-internet.adoc
  downstream/modules/platform/proc-inventory-file-setup-rpm.adoc
  downstream/modules/platform/proc-running-setup-script-for-updates.adoc
  downstream/modules/platform/proc-update-aap-container.adoc
  downstream/modules/platform/proc-update-aap-on-ocp.adoc
  downstream/titles/updating-aap/master.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#2291 dd-2286 - fix conversion issues in the Updating guide (#2290)
  downstream/assemblies/platform/assembly-update-container.adoc
  downstream/assemblies/platform/assembly-update-ocp.adoc
  downstream/assemblies/platform/assembly-update-rpm.adoc
  downstream/modules/platform/proc-backup-aap-container.adoc
  downstream/modules/platform/proc-backup-aap-rpm.adoc
  downstream/modules/platform/proc-installing-with-internet.adoc
  downstream/modules/platform/proc-inventory-file-setup-rpm.adoc
  downstream/modules/platform/proc-running-setup-script-for-updates.adoc
  downstream/modules/platform/proc-update-aap-container.adoc
  downstream/modules/platform/proc-update-aap-on-ocp.adoc
  downstream/titles/updating-aap/master.adoc
Labels: Ready for review, 2.5

#2293 dd-updguide - Add experimental tagk to fix formatting
  downstream/titles/updating-aap/master.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#2294 dd-updguide - Add experimental tagk to fix formatting (#2293)
  downstream/titles/updating-aap/master.adoc
Labels: Ready for review, 2.5

#2297 Updates to updating-aap
  downstream/assemblies/platform/assembly-update-container.adoc
  downstream/assemblies/platform/assembly-update-ocp.adoc
  downstream/assemblies/platform/assembly-update-rpm.adoc
  downstream/modules/platform/proc-backup-aap-container.adoc
  downstream/modules/platform/proc-backup-aap-rpm.adoc
  downstream/modules/platform/proc-installing-with-internet.adoc
  downstream/modules/platform/proc-inventory-file-setup-rpm.adoc
  downstream/titles/updating-aap/master.adoc
Labels: 2.5, Needs backport to 2.5

#2298 2.5 Updates to updating-aap (#2297)
  downstream/assemblies/platform/assembly-update-container.adoc
  downstream/assemblies/platform/assembly-update-ocp.adoc
  downstream/assemblies/platform/assembly-update-rpm.adoc
  downstream/modules/platform/proc-backup-aap-container.adoc
  downstream/modules/platform/proc-backup-aap-rpm.adoc
  downstream/modules/platform/proc-installing-with-internet.adoc
  downstream/modules/platform/proc-inventory-file-setup-rpm.adoc
  downstream/titles/updating-aap/master.adoc
Labels: 2.5

#2299 Updating operator title attributes
  downstream/assemblies/platform/assembly-aap-backup.adoc
  downstream/assemblies/platform/assembly-aap-migration.adoc
  downstream/assemblies/platform/assembly-configure-aap-operator.adoc
  downstream/assemblies/platform/assembly-deploy-eda-controller-on-aap-operator.adoc
  downstream/assemblies/platform/assembly-install-aap-operator.adoc
  downstream/assemblies/platform/assembly-installing-aap-operator-cli.adoc
  downstream/assemblies/platform/assembly-installing-hub-operator.adoc
  downstream/assemblies/platform/assembly-operator-add-execution-nodes.adoc
  downstream/assemblies/platform/assembly-operator-install-planning.adoc
  downstream/assemblies/platform/assembly-operator-upgrade.adoc
  downstream/assemblies/topologies/assembly-ocp-topologies.adoc
  downstream/assemblies/troubleshooting-aap/assembly-troubleshoot-backup-recovery.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/eda/ref-deploy-eda-controller-with-aap-operator-on-ocp.adoc
  downstream/modules/platform/con-aap-migration-prepare.adoc
  downstream/modules/platform/con-about-operator.adoc
  downstream/modules/platform/con-ocp-supported-install.adoc
  downstream/modules/platform/con-operator-upgrade-considerations.adoc
  downstream/modules/platform/con-operator-upgrade-prereq.adoc
  downstream/modules/platform/con-storage-options-for-operator-installation-on-ocp.adoc
  downstream/modules/platform/proc-aap-controller-backup.adoc
  downstream/modules/platform/proc-aap-controller-restore.adoc
  downstream/modules/platform/proc-aap-controller-yaml-backup.adoc
  downstream/modules/platform/proc-aap-create_controller.adoc
  downstream/modules/platform/proc-aap-create_hub.adoc
  downstream/modules/platform/proc-aap-hub-backup.adoc
  downstream/modules/platform/proc-aap-hub-restore.adoc
  downstream/modules/platform/proc-aap-migration-backup.adoc
  downstream/modules/platform/proc-aap-migration.adoc
  downstream/modules/platform/proc-aap-platform-gateway-backup.adoc
  downstream/modules/platform/proc-aap-platform-gateway-restore.adoc
  downstream/modules/platform/proc-configuring-controller-image-pull-policy.adoc
  downstream/modules/platform/proc-configuring-controller-route-options.adoc
  downstream/modules/platform/proc-controller-ingress-options.adoc
  downstream/modules/platform/proc-create-secret-key-secret.adoc
  downstream/modules/platform/proc-deploy-eda-controller-with-aap-operator-ocp.adoc
  downstream/modules/platform/proc-hub-ingress-options.adoc
  downstream/modules/platform/proc-hub-route-options.adoc
  downstream/modules/platform/proc-install-aap-operator.adoc
  downstream/modules/platform/proc-install-cli-aap-operator.adoc
  downstream/modules/platform/proc-installing-hub-using-operator.adoc
  downstream/modules/platform/proc-installing-the-ansible-platform-operator.adoc
  downstream/modules/platform/proc-operator-deploy-central-config.adoc
  downstream/modules/platform/proc-operator-deploy-redis.adoc
  downstream/modules/platform/proc-operator-external-db-controller.adoc
  downstream/modules/platform/proc-operator-external-db-hub.adoc
  downstream/modules/platform/proc-operator-link-components.adoc
  downstream/modules/platform/proc-operator-upgrade.adoc
  downstream/modules/platform/proc-provision-ocp-storage-with-readwritemany.adoc
  downstream/modules/platform/proc-update-aap-on-ocp.adoc
  downstream/modules/platform/ref-operator-ocp-version.adoc
  downstream/titles/aap-operator-installation/master.adoc
  downstream/titles/release-notes/topics/aap-25-fixed-issues.adoc
Labels: Needs backport to 2.4, 2.4, 2.5, AAP operator, Needs backport to 2.5

#2295 Updating UI and links in API overview
  downstream/modules/platform/con-controller-api-basic-auth.adoc
  downstream/modules/platform/con-controller-api-oauth2-token.adoc
  downstream/modules/platform/con-controller-api-sso-auth.adoc
  downstream/modules/platform/con-controller-api-tools.adoc
  downstream/modules/platform/proc-controller-api-session-auth.adoc
Labels: documentation, Controller, 2.5, Needs backport to 2.5

#2301 Updating UI and links in API overview (#2295)
  downstream/modules/platform/con-controller-api-basic-auth.adoc
  downstream/modules/platform/con-controller-api-oauth2-token.adoc
  downstream/modules/platform/con-controller-api-sso-auth.adoc
  downstream/modules/platform/con-controller-api-tools.adoc
  downstream/modules/platform/proc-controller-api-session-auth.adoc
Labels: documentation, Controller, 2.5, Backported to 2.5

#2300 Updating title attributes (#2299)
  downstream/assemblies/platform/assembly-aap-backup.adoc
  downstream/assemblies/platform/assembly-aap-migration.adoc
  downstream/assemblies/platform/assembly-configure-aap-operator.adoc
  downstream/assemblies/platform/assembly-deploy-eda-controller-on-aap-operator.adoc
  downstream/assemblies/platform/assembly-install-aap-operator.adoc
  downstream/assemblies/platform/assembly-installing-aap-operator-cli.adoc
  downstream/assemblies/platform/assembly-installing-hub-operator.adoc
  downstream/assemblies/platform/assembly-operator-add-execution-nodes.adoc
  downstream/assemblies/platform/assembly-operator-install-planning.adoc
  downstream/assemblies/platform/assembly-operator-upgrade.adoc
  downstream/assemblies/topologies/assembly-ocp-topologies.adoc
  downstream/assemblies/troubleshooting-aap/assembly-troubleshoot-backup-recovery.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/eda/ref-deploy-eda-controller-with-aap-operator-on-ocp.adoc
  downstream/modules/platform/con-aap-migration-prepare.adoc
  downstream/modules/platform/con-about-operator.adoc
  downstream/modules/platform/con-ocp-supported-install.adoc
  downstream/modules/platform/con-operator-upgrade-considerations.adoc
  downstream/modules/platform/con-operator-upgrade-prereq.adoc
  downstream/modules/platform/con-storage-options-for-operator-installation-on-ocp.adoc
  downstream/modules/platform/proc-aap-controller-backup.adoc
  downstream/modules/platform/proc-aap-controller-restore.adoc
  downstream/modules/platform/proc-aap-controller-yaml-backup.adoc
  downstream/modules/platform/proc-aap-create_controller.adoc
  downstream/modules/platform/proc-aap-create_hub.adoc
  downstream/modules/platform/proc-aap-hub-backup.adoc
  downstream/modules/platform/proc-aap-hub-restore.adoc
  downstream/modules/platform/proc-aap-migration-backup.adoc
  downstream/modules/platform/proc-aap-migration.adoc
  downstream/modules/platform/proc-aap-platform-gateway-backup.adoc
  downstream/modules/platform/proc-aap-platform-gateway-restore.adoc
  downstream/modules/platform/proc-configuring-controller-image-pull-policy.adoc
  downstream/modules/platform/proc-configuring-controller-route-options.adoc
  downstream/modules/platform/proc-controller-ingress-options.adoc
  downstream/modules/platform/proc-create-secret-key-secret.adoc
  downstream/modules/platform/proc-deploy-eda-controller-with-aap-operator-ocp.adoc
  downstream/modules/platform/proc-hub-ingress-options.adoc
  downstream/modules/platform/proc-hub-route-options.adoc
  downstream/modules/platform/proc-install-aap-operator.adoc
  downstream/modules/platform/proc-install-cli-aap-operator.adoc
  downstream/modules/platform/proc-installing-hub-using-operator.adoc
  downstream/modules/platform/proc-installing-the-ansible-platform-operator.adoc
  downstream/modules/platform/proc-operator-deploy-central-config.adoc
  downstream/modules/platform/proc-operator-deploy-redis.adoc
  downstream/modules/platform/proc-operator-external-db-controller.adoc
  downstream/modules/platform/proc-operator-external-db-hub.adoc
  downstream/modules/platform/proc-operator-link-components.adoc
  downstream/modules/platform/proc-operator-upgrade.adoc
  downstream/modules/platform/proc-provision-ocp-storage-with-readwritemany.adoc
  downstream/modules/platform/proc-update-aap-on-ocp.adoc
  downstream/modules/platform/ref-operator-ocp-version.adoc
  downstream/titles/aap-operator-installation/master.adoc
  downstream/titles/release-notes/topics/aap-25-fixed-issues.adoc
Labels: 2.5, AAP operator

#2302 Updating title attributes (#2299)
  downstream/assemblies/platform/assembly-aap-backup.adoc
  downstream/assemblies/platform/assembly-aap-migration.adoc
  downstream/assemblies/platform/assembly-deploy-eda-controller-on-aap-operator.adoc
  downstream/assemblies/platform/assembly-install-aap-operator.adoc
  downstream/assemblies/platform/assembly-installing-aap-operator-cli.adoc
  downstream/assemblies/platform/assembly-installing-hub-operator.adoc
  downstream/assemblies/platform/assembly-operator-add-execution-nodes.adoc
  downstream/assemblies/platform/assembly-operator-install-planning.adoc
  downstream/assemblies/platform/assembly-operator-upgrade.adoc
  downstream/assemblies/troubleshooting-aap/assembly-troubleshoot-backup-recovery.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/eda/ref-deploy-eda-controller-with-aap-operator-on-ocp.adoc
  downstream/modules/platform/con-aap-migration-prepare.adoc
  downstream/modules/platform/con-about-operator.adoc
  downstream/modules/platform/con-ocp-supported-install.adoc
  downstream/modules/platform/con-operator-upgrade-considerations.adoc
  downstream/modules/platform/con-operator-upgrade-prereq.adoc
  downstream/modules/platform/con-storage-options-for-operator-installation-on-ocp.adoc
  downstream/modules/platform/proc-aap-controller-backup.adoc
  downstream/modules/platform/proc-aap-controller-restore.adoc
  downstream/modules/platform/proc-aap-controller-yaml-backup.adoc
  downstream/modules/platform/proc-aap-create_controller.adoc
  downstream/modules/platform/proc-aap-create_hub.adoc
  downstream/modules/platform/proc-aap-hub-backup.adoc
  downstream/modules/platform/proc-aap-hub-restore.adoc
  downstream/modules/platform/proc-aap-migration-backup.adoc
  downstream/modules/platform/proc-aap-migration.adoc
  downstream/modules/platform/proc-configuring-controller-image-pull-policy.adoc
  downstream/modules/platform/proc-configuring-controller-route-options.adoc
  downstream/modules/platform/proc-controller-ingress-options.adoc
  downstream/modules/platform/proc-create-secret-key-secret.adoc
  downstream/modules/platform/proc-deploy-eda-controller-with-aap-operator-ocp.adoc
  downstream/modules/platform/proc-hub-ingress-options.adoc
  downstream/modules/platform/proc-hub-route-options.adoc
  downstream/modules/platform/proc-install-aap-operator.adoc
  downstream/modules/platform/proc-install-cli-aap-operator.adoc
  downstream/modules/platform/proc-installing-hub-using-operator.adoc
  downstream/modules/platform/proc-installing-the-ansible-platform-operator.adoc
  downstream/modules/platform/proc-operator-external-db-controller.adoc
  downstream/modules/platform/proc-operator-external-db-hub.adoc
  downstream/modules/platform/proc-operator-upgrade.adoc
  downstream/modules/platform/proc-provision-ocp-storage-with-readwritemany.adoc
  downstream/modules/platform/ref-operator-ocp-version.adoc
  downstream/titles/aap-operator-installation/master.adoc
  titles/saas-aws/master.html
Labels: 2.4, AAP operator

#2304 fixing xref (#2303)
  downstream/assemblies/platform/assembly-installing-aap-operator-cli.adoc
  downstream/modules/platform/con-ocp-supported-install.adoc
Labels: 2.5, AAP operator

#2292 Upgrade and Migration guide: Reorganizing assemblies
  downstream/assemblies/platform/assembly-aap-upgrades.adoc
  downstream/assemblies/platform/assembly-aap-upgrading-platform.adoc
  downstream/titles/upgrade/master.adoc
Labels: 2.5, Needs backport to 2.5, event2

#2277 Adding debugging chapter
  downstream/assemblies/platform/assembly-operator-debugging.adoc
  downstream/modules/platform/con-operator-ansible-verbosity.adoc
Labels: documentation, Draft, 2.4, 2.5, AAP operator

#2309 Adding updating receptors section to op-mesh guide
  downstream/assemblies/platform/assembly-automation-mesh-operator-aap.adoc
  downstream/modules/platform/proc-operator-mesh-upgrading-receptors.adoc
Labels: documentation, Needs backport to 2.4, Automation Mesh, 2.4, 2.5, Needs backport to 2.5

#2313 Adding updating receptors section to op-mesh guide (#2309)
  downstream/assemblies/platform/assembly-automation-mesh-operator-aap.adoc
  downstream/modules/platform/proc-operator-mesh-upgrading-receptors.adoc
Labels: Automation Mesh, 2.5

#2312 Adding debugging chapter (#2277)
  downstream/assemblies/platform/assembly-operator-debugging.adoc
  downstream/modules/platform/con-operator-ansible-verbosity.adoc
Labels: 2.4, AAP operator

#2315 adding ID
  downstream/modules/platform/proc-operator-deploy-redis.adoc
Labels: 2.5, AAP operator

#2316 adding ID (#2315)
  downstream/modules/platform/proc-operator-deploy-redis.adoc
Labels: 2.5, AAP operator

#2308 AAP-30808: Upgrade/migration guide asciidoc conversion
  downstream/assemblies/platform/assembly-aap-upgrades.adoc
  downstream/assemblies/platform/assembly-aap-upgrading-platform.adoc
  downstream/modules/platform/con-aap-upgrade-planning.adoc
  downstream/modules/platform/con-aap-upgrades.adoc
  downstream/modules/platform/con-backup-aap.adoc
  downstream/modules/platform/ini/clustered-nodes.ini
  downstream/modules/platform/proc-account-linking.adoc
  downstream/modules/platform/proc-choosing-obtaining-installer.adoc
  downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
  downstream/modules/platform/proc-upgrade-controller-hub-eda-unified-ui.adoc
Labels: Not ready for peer review, 2.5, event2

#2310 Updating the Upgrades chapter of the Installing on OCP doc
  downstream/assemblies/platform/assembly-appendix-operator-crs.adoc
  downstream/assemblies/platform/assembly-configure-aap-operator.adoc
  downstream/assemblies/platform/assembly-install-aap-operator.adoc
  downstream/assemblies/platform/assembly-installing-aap-operator-cli.adoc
  downstream/assemblies/platform/assembly-operator-upgrade.adoc
  downstream/images/Subscription_tab.png
  downstream/images/change_subscription.png
  downstream/modules/platform/con-ocp-supported-install.adoc
  downstream/modules/platform/con-operator-channel-upgrade.adoc
  downstream/modules/platform/con-operator-upgrade-considerations.adoc
  downstream/modules/platform/con-operator-upgrade-overview.adoc
  downstream/modules/platform/con-operator-upgrade-prereq.adoc
  downstream/modules/platform/proc-install-cli-aap-operator.adoc
  downstream/modules/platform/proc-operator-access-aap.adoc
  downstream/modules/platform/proc-operator-create_crs.adoc
  downstream/modules/platform/proc-operator-deploy-central-config.adoc
  downstream/modules/platform/proc-operator-upgrade.adoc
  downstream/modules/platform/ref-operator-crs.adoc
  downstream/titles/aap-operator-installation/master.adoc
Labels: AAP operator, event2

#2325 Containerized installation - update postinstall information
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/platform/proc-downloading-containerized-aap.adoc
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc
  downstream/modules/platform/proc-using-postinstall.adoc
Labels: 2.5, Needs backport to 2.5

#2326 2.5 Containerized installation - update postinstall information (#2325)
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/platform/proc-downloading-containerized-aap.adoc
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc
  downstream/modules/platform/proc-using-postinstall.adoc
Labels: 2.5

#2324 Adding appendix as part of event 2
  downstream/assemblies/platform/assembly-appendix-operator-crs.adoc
  downstream/modules/platform/ref-operator-crs.adoc
Labels: 2.5, AAP operator, event2

#2333 2.5 Add patch 2 release notes (#2332)
  downstream/titles/release-notes/async/aap-25-1-7-oct.adoc
  downstream/titles/release-notes/async/aap-25-2-14-oct.adoc
  downstream/titles/release-notes/master.adoc
Labels: AAP Release notes, 2.5

#2335 Fix incorrect formatting of buttons
  downstream/modules/hub/proc-create-namespace.adoc
  downstream/modules/platform/proc-provision-ocp-storage-with-readwritemany.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#2296 AAP-32987: prep metrics-utility content for publication
  downstream/assemblies/platform/assembly-metrics-utility.adoc
  downstream/assemblies/platform/assembly_metrics-utility.adoc
  downstream/modules/platform/proc-configuring-the-metrics-utility.adoc
  downstream/modules/platform/proc-modifying-the-run-schedule.adoc
  downstream/modules/platform/proc_modifying-the-run-schedule.adoc
  downstream/modules/platform/ref-fetching-a-monthly-report.adoc
  downstream/titles/controller/controller-admin-guide/master.adoc
Labels: Main, 2.5, Needs backport to 2.5

#2337 backport to 2.5: AAP-32987: prep metrics-utility content for publication (#2296)
  downstream/assemblies/platform/assembly-metrics-utility.adoc
  downstream/assemblies/platform/assembly_metrics-utility.adoc
  downstream/modules/platform/proc-configuring-the-metrics-utility.adoc
  downstream/modules/platform/proc-modifying-the-run-schedule.adoc
  downstream/modules/platform/proc_modifying-the-run-schedule.adoc
  downstream/modules/platform/ref-fetching-a-monthly-report.adoc
  downstream/titles/controller/controller-admin-guide/master.adoc
Labels: 2.5

#2338 Updating receptor section
  downstream/modules/platform/proc-operator-mesh-upgrading-receptors.adoc
Labels: documentation, Needs backport to 2.4, Automation Mesh, 2.4, 2.5, Needs backport to 2.5

#2317 linking to auto mesh receptors section
  stories/topics/con-saas-intro.adoc
  stories/topics/con-saas-monitoring.adoc
  stories/topics/con-saas-updates-and-maintenance.adoc
  titles/saas-aws/docinfo.xml
  titles/saas-aws/master.adoc
Labels: documentation, AAP on clouds, Ansible on AWS

#2339 Add gateway variables to example inventory file
  downstream/assemblies/platform/assembly-inventory-introduction.adoc
Labels: 2.5, Needs backport to 2.5

#2340 Backport 2338 to 2.4
  downstream/modules/platform/proc-operator-mesh-upgrading-receptors.adoc
Labels: documentation, Automation Mesh, 2.4

#2341 Updating receptor section (#2338)
  downstream/modules/platform/proc-operator-mesh-upgrading-receptors.adoc
Labels: 2.5

#2342 Add gateway variables to example inventory file (#2339)
  downstream/assemblies/platform/assembly-inventory-introduction.adoc
Labels: 2.5, Backported to 2.5

#2344 Removed context marker to make build work
  downstream/assemblies/platform/assembly-metrics-utility.adoc
  downstream/modules/platform/proc-configuring-the-metrics-utility.adoc
Labels: 2.5, Needs backport to 2.5

#2345 Removed context marker to make build work (#2344)
  downstream/assemblies/platform/assembly-metrics-utility.adoc
  downstream/modules/platform/proc-configuring-the-metrics-utility.adoc
Labels: 2.5, Backported to 2.5

#2334 AAP-32327: adds redis config info to RPM installer guide
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
  downstream/modules/platform/ref-general-inventory-variables.adoc
  downstream/modules/platform/ref-redis-config-enterprise-topology.adoc
Labels: 2.5, event2

#2348 AAP-21556 - org/team/user migration and superuser identification for AAP-24050
  downstream/modules/platform/proc-controller-add-organization-user.adoc
  downstream/modules/platform/proc-gw-editing-a-user.adoc
  downstream/modules/platform/proc-gw-team-add-user.adoc
  downstream/modules/platform/proc-gw-users-list-view.adoc
Labels: Ready for review, event2

#2350 Added RHEL 8.8 to 2.5 system requirements
  downstream/modules/platform/ref-system-requirements.adoc
Labels: 2.5, Needs backport to 2.5

#2351 Added RHEL 8.8 to 2.5 system requirements (#2350)
  downstream/modules/platform/ref-system-requirements.adoc
Labels: 2.5, Backported to 2.5

#2353 Updating OCP version
  downstream/modules/platform/ref-operator-ocp-version.adoc
Labels: 2.5, AAP operator

#2354 updating OCP version (#2353)
  downstream/modules/platform/ref-operator-ocp-version.adoc
Labels: 2.5, AAP operator

#2355 Add note about external server (#2352)
  downstream/modules/platform/proc-install-ha-hub-selinux.adoc
Labels: 2.5, Backported to 2.5

#2349 Adding warning admonition
  stories/assembly-saas-post-install-config.adoc
Labels: documentation, AAP on clouds, Ansible on AWS

#2358 Link fixes in getting started with AAP guide
  downstream/assemblies/platform/assembly-gs-auto-dev.adoc
  downstream/assemblies/platform/assembly-gs-auto-op.adoc
  downstream/modules/platform/con-gs-ansible-roles.adoc
  downstream/modules/platform/con-gs-auto-dev-about-inv.adoc
  downstream/modules/platform/con-gs-auto-op-execute-inv.adoc
  downstream/modules/platform/con-gs-auto-op-job-templates.adoc
  downstream/modules/platform/con-gs-learn-about-collections.adoc
  downstream/modules/platform/proc-creating-ansible-role.adoc
  downstream/modules/platform/proc-gs-add-ee-to-job-template.adoc
  downstream/modules/platform/proc-gs-auto-dev-create-automation-execution-proj.adoc
  downstream/modules/platform/proc-gs-auto-dev-create-template.adoc
  downstream/modules/platform/proc-gs-auto-op-launch-template.adoc
  downstream/modules/platform/proc-gs-eda-set-up-rulebook-activation.adoc
  downstream/modules/platform/proc-gs-publish-to-a-collection.adoc
  downstream/modules/platform/proc-gs-write-playbook.adoc
Labels: Main, 2.5, Needs backport to 2.5

#2359 Backport to 2.5: Link fixes in getting started with AAP guide (#2358)
  downstream/assemblies/platform/assembly-gs-auto-dev.adoc
  downstream/assemblies/platform/assembly-gs-auto-op.adoc
  downstream/modules/platform/con-gs-ansible-roles.adoc
  downstream/modules/platform/con-gs-auto-dev-about-inv.adoc
  downstream/modules/platform/con-gs-auto-op-execute-inv.adoc
  downstream/modules/platform/con-gs-auto-op-job-templates.adoc
  downstream/modules/platform/con-gs-learn-about-collections.adoc
  downstream/modules/platform/proc-creating-ansible-role.adoc
  downstream/modules/platform/proc-gs-add-ee-to-job-template.adoc
  downstream/modules/platform/proc-gs-auto-dev-create-automation-execution-proj.adoc
  downstream/modules/platform/proc-gs-auto-dev-create-template.adoc
  downstream/modules/platform/proc-gs-auto-op-launch-template.adoc
  downstream/modules/platform/proc-gs-eda-set-up-rulebook-activation.adoc
  downstream/modules/platform/proc-gs-publish-to-a-collection.adoc
  downstream/modules/platform/proc-gs-write-playbook.adoc
Labels: 2.5

#2336 [Backport] - Fix incorrect formatting of buttons (#2335)
  downstream/modules/hub/proc-create-namespace.adoc
  downstream/modules/platform/proc-provision-ocp-storage-with-readwritemany.adoc
Labels: Ready for review, 2.5

#2362 removing base url info from warning
  stories/assembly-saas-post-install-config.adoc
Labels: AAP on clouds, Ansible on AWS

#2363 Update must-gather version in troubleshooting guide
  downstream/modules/troubleshooting-aap/proc-troubleshoot-must-gather.adoc
Labels: 2.5, Needs backport to 2.5

#2364 2.5 Update must-gather version in troubleshooting guide (#2363)
  downstream/modules/troubleshooting-aap/proc-troubleshoot-must-gather.adoc
Labels: 2.5

#2361 Updates required from AAP-33302
  downstream/assemblies/platform/assembly-configure-aap-operator.adoc
  downstream/modules/platform/proc-operator-deploy-central-config.adoc
Labels: documentation, 2.5, AAP operator

#2366 Updates required from AAP-33302 (#2361)
  downstream/assemblies/platform/assembly-configure-aap-operator.adoc
  downstream/modules/platform/proc-operator-deploy-central-config.adoc
Labels: 2.5, AAP operator

#2365 AAP-32330 updated planning guide with redis changes
  downstream/modules/platform/con-gw-clustered-redis.adoc
Labels: Ready for review, Needs backport to 2.5, event2

#2367 AAP-31305: Added info. about disabling SSL cert validation in Lightspeed operator
  lightspeed/modules/proc_troubleshooting-lightspeed-onpremise-config.adoc
Labels: Ready for review, Technical review complete, Lightspeed

#2368 AAP-32987: adds metrics-utility content to 2.4 controller admin guide
  downstream/assemblies/platform/assembly-metrics-utility.adoc
  downstream/modules/platform/proc-configuring-the-metrics-utility.adoc
  downstream/modules/platform/proc-modifying-the-run-schedule.adoc
  downstream/modules/platform/ref-fetching-a-monthly-report.adoc
  downstream/titles/controller/controller-admin-guide/master.adoc
Labels: 2.4

#2360 Added descriptions for ca_tls_* variables
  downstream/modules/platform/ref-general-inventory-variables.adoc
Labels: 2.5, Needs backport to 2.5

#2370 Update Containerized installation inventory variable references
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/platform/ref-accessing-control-auto-hub-eda-control.adoc
  downstream/modules/platform/ref-containerized-troubleshoot-install.adoc
Labels: Needs backport to 2.4, 2.5, Needs backport to 2.5

#2371 2.5 Update Containerized installation inventory variable references (#2370)
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/platform/ref-accessing-control-auto-hub-eda-control.adoc
  downstream/modules/platform/ref-containerized-troubleshoot-install.adoc
Labels: 2.5

#2374 AAP-32998: Adds links about OAuth application migration to the Upgrade/Migration guide
  downstream/modules/platform/proc-account-linking.adoc
Labels: 2.5, event2

#2376 Upgrade/migration guide: Adds note about API endpoints
  downstream/modules/platform/con-aap-upgrade-planning.adoc
Labels: 2.5, event2

#2377 Removed post-install steps
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/platform/proc-installing-containerized-aap.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#2379 Removed post-install steps (#2377)
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/platform/proc-installing-containerized-aap.adoc
Labels: 2.5, Backported to 2.5

#2383 Update port variables in Containerized installation
  downstream/modules/platform/ref-accessing-control-auto-hub-eda-control.adoc
Labels: 2.5, Needs backport to 2.5

#2385 2.5 Update port variables in Containerized installation (#2383)
  downstream/modules/platform/ref-accessing-control-auto-hub-eda-control.adoc
Labels: 2.5

#2343 Replace LOG_AGGREGATOR_MAX_DISK_USAGE
  downstream/assemblies/platform/assembly-controller-logging-aggregation.adoc
Labels: 2.5, Backported to 2.5

#2386 Replace LOG_AGGREGATOR_MAX_DISK_USAGE (#2343)
  downstream/assemblies/platform/assembly-controller-logging-aggregation.adoc
Labels: 2.5, Backported to 2.5

#2387 Adding in KCS article required for event2 content
  downstream/modules/platform/proc-operator-upgrade.adoc
Labels: documentation, AAP operator, event2

#2378 AAP-32794 updates
  downstream/modules/platform/proc-cli-get-controller-pwd.adoc
  downstream/modules/platform/proc-install-cli-aap-operator.adoc
Labels: documentation, Draft, 2.5, AAP operator

#2388 AAP-32794 updates (#2378)
  downstream/modules/platform/proc-cli-get-controller-pwd.adoc
  downstream/modules/platform/proc-install-cli-aap-operator.adoc
Labels: 2.5, AAP operator

#2390 Add required vars to cont-b inventory files
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/topologies/ref-cont-b-env-a.adoc
Labels: 2.5, Needs backport to 2.5

#2391 2.5 Add required vars to cont-b inventory files (#2390)
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/topologies/ref-cont-b-env-a.adoc
Labels: 2.5

#2392 Add note to Operator topologies section of Tested deployment models
  downstream/assemblies/topologies/assembly-ocp-topologies.adoc
Labels: 2.5, Needs backport to 2.5

#2393 2.5 Add note to Operator topologies section of Tested deployment models (…
  downstream/assemblies/topologies/assembly-ocp-topologies.adoc
Labels: 2.5

#2394 fix build error
  downstream/modules/platform/proc-install-cli-aap-operator.adoc
Labels: 2.5

#2395 fix build error (#2394)
  downstream/modules/platform/proc-install-cli-aap-operator.adoc
Labels: 2.5, AAP operator

#2397 Updated the note for a backup failure status. (#2329)
  downstream/modules/platform/proc-aap-controller-backup.adoc
Labels: Controller, 2.4

#2396 Updated the note for a backup failure status. (#2329)
  downstream/modules/platform/proc-aap-controller-backup.adoc
Labels: Controller, 2.5

#2398 2.4 Fix title attribute
  downstream/attributes/attributes.adoc
Labels: Attributes, 2.4

#2399 2.4 Fix analytics title attributes
  downstream/attributes/attributes.adoc
Labels: Attributes, 2.4

#2400 AAP-33888 New best practices section
  stories/assembly-saas-aap-best-practices.adoc
  stories/topics/con-saas-automation-for-instance-groups.adoc
  stories/topics/con-saas-sync-with-pah.adoc
  titles/saas-aws/stories.adoc
Labels: AAP on clouds, Ansible on AWS

#2403 2.5 Add conditional text to Horizontal scaling in EDA (#2402)
  downstream/modules/platform/con-hs-eda-controller.adoc
  downstream/titles/aap-containerized-install/master.adoc
Labels: 2.5

#2401 Added controller to hub connection to table
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
Labels: 2.4

#2380 Adding note about duplicate credentials
  downstream/assemblies/platform/assembly-controller-credentials.adoc
Labels: documentation, Needs backport to 2.4, Technical review complete, Controller, 2.4, 2.5, Needs backport to 2.5

#2407 Adding note about duplicate credentials (#2380)
  downstream/assemblies/platform/assembly-controller-credentials.adoc
Labels: documentation, Controller, 2.5, Backported to 2.5

#2408 Adding note about duplicate credentials (#2380)
  downstream/assemblies/platform/assembly-controller-credentials.adoc
Labels: documentation, Backported to 2.4, Controller, 2.4

#2406 Update Redis HA in Tested deployment models
  downstream/modules/topologies/ref-cont-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-b.adoc
Labels: 2.5, event2

#2409 Corrected note format
  downstream/modules/platform/ref-eda-system-requirements.adoc
Labels: 2.5, Needs backport to 2.5

#2410 Corrected note format (#2409)
  downstream/modules/platform/ref-eda-system-requirements.adoc
Labels: 2.5, Backported to 2.5

#2416 Fixes broken links and typos in managing automation content guide
  downstream/assemblies/hub/assembly-delete-container.adoc
  downstream/assemblies/hub/assembly-populate-container-registry.adoc
  downstream/assemblies/hub/assembly-pull-image.adoc
  downstream/assemblies/hub/assembly-setup-container-repository.adoc
  downstream/modules/hub/proc-add-group-to-container-repo.adoc
  downstream/modules/hub/proc-obtain-images.adoc
  downstream/modules/hub/proc-pull-image.adoc
  downstream/modules/hub/proc-pushing-container-images-from-your-local.adoc
  downstream/modules/hub/proc-reject-collections.adoc
  downstream/modules/hub/proc-sync-image.adoc
  downstream/modules/hub/proc-tag-image.adoc
  downstream/modules/platform/con-gs-execution-env.adoc
Labels: Main, 2.5, Needs backport to 2.5

#2417 AAP-34122: moves assembly from upgrading 2.5 to 2.5x to Installing on OCP guide
  downstream/assemblies/platform/assembly-update-ocp.adoc
  downstream/modules/platform/proc-update-aap-on-ocp.adoc
  downstream/titles/aap-operator-installation/master.adoc
  downstream/titles/updating-aap/master.adoc
Labels: Main, 2.5, Needs backport to 2.5

#2418 AAP-30120 Added extra bullet to the admonition in Setting up a rulebook activation section
  downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc
Labels: documentation, Ready for review, Ready for technical review, Technical review complete, 2.5, Needs backport to 2.5

#2420 Backport to 2.5: AAP 34122 moves assembly from upgrading 2.5 to 2.5x to Installing on OCP guide …
  downstream/assemblies/platform/assembly-update-ocp.adoc
  downstream/modules/platform/proc-update-aap-on-ocp.adoc
  downstream/titles/aap-operator-installation/master.adoc
  downstream/titles/updating-aap/master.adoc
Labels: 2.5

#2419 Backport to 2.5: AAP-15176 Fixes broken links and typos in managing automation content guide (#2…
  downstream/assemblies/hub/assembly-delete-container.adoc
  downstream/assemblies/hub/assembly-populate-container-registry.adoc
  downstream/assemblies/hub/assembly-pull-image.adoc
  downstream/assemblies/hub/assembly-setup-container-repository.adoc
  downstream/modules/hub/proc-add-group-to-container-repo.adoc
  downstream/modules/hub/proc-obtain-images.adoc
  downstream/modules/hub/proc-pull-image.adoc
  downstream/modules/hub/proc-pushing-container-images-from-your-local.adoc
  downstream/modules/hub/proc-reject-collections.adoc
  downstream/modules/hub/proc-sync-image.adoc
  downstream/modules/hub/proc-tag-image.adoc
  downstream/modules/platform/con-gs-execution-env.adoc
Labels: 2.5

#2422 Add update content to Containerized installation
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/platform/proc-backup-aap-container.adoc
  downstream/modules/platform/proc-update-aap-container.adoc
Labels: 2.5, Needs backport to 2.5, event2

#2423 2.5 Add update content to Containerized installation (#2422)
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/platform/proc-backup-aap-container.adoc
  downstream/modules/platform/proc-update-aap-container.adoc
Labels: 2.5

#2424 Update RPM-B-ENV-B topology for Redis
  downstream/modules/topologies/ref-rpm-a-env-b.adoc
  downstream/modules/topologies/ref-rpm-b-env-b.adoc
Labels: 2.5, Needs backport to 2.5, event2

#2425 2.5 Update RPM-B-ENV-B topology for Redis (#2424)
  downstream/modules/topologies/ref-rpm-a-env-b.adoc
  downstream/modules/topologies/ref-rpm-b-env-b.adoc
Labels: 2.5, event2

#2427 Add Redis feedback from SME discussion
  downstream/images/rpm-a-env-a.png
  downstream/images/rpm-b-env-a.png
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/topologies/ref-cont-a-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-b.adoc
Labels: 2.5, Needs backport to 2.5, event2

#2431 AAP-29859: Revise first two paragraphs
  downstream/attributes/attributes.adoc
  downstream/modules/platform/proc-account-linking.adoc
  downstream/modules/platform/proc-upgrade-controller-hub-eda-unified-ui.adoc
  downstream/titles/upgrade/docinfo.xml
  downstream/titles/upgrade/master.adoc
Labels: documentation, Title change, 2.5, Needs backport to 2.5

#2432 Minor fixes to correct broken link and doc formatting
  downstream/modules/platform/proc-gs-auto-dev-create-template.adoc
  downstream/titles/builder/master.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#2433 [2.5] AAP-29859: Revise first two paragraphs (#2431)
  downstream/attributes/attributes.adoc
  downstream/modules/platform/proc-account-linking.adoc
  downstream/modules/platform/proc-upgrade-controller-hub-eda-unified-ui.adoc
  downstream/titles/upgrade/docinfo.xml
  downstream/titles/upgrade/master.adoc
Labels: documentation, Title change, 2.5, Backported to 2.5

#2437 Adds SME feedback to RPM upgrade guide
  downstream/modules/platform/con-aap-upgrade-planning.adoc
  downstream/modules/platform/proc-account-linking.adoc
  downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
Labels: 2.5, Needs backport to 2.5, event2

#2435 Minor fixes for PR 2431
  downstream/modules/platform/proc-account-linking.adoc
  downstream/modules/platform/proc-upgrade-controller-hub-eda-unified-ui.adoc
Labels: 2.5, Needs backport to 2.5

#2434 [Backport] Minor fixes to correct broken link and doc formatting (#2432)
  downstream/modules/platform/proc-gs-auto-dev-create-template.adoc
  downstream/titles/builder/master.adoc
Labels: 2.5

#2439 Backport to 2.5: Adds SME feedback to RPM upgrade guide (#2437)
  downstream/modules/platform/con-aap-upgrade-planning.adoc
  downstream/modules/platform/proc-account-linking.adoc
  downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
Labels: 2.5
