Repository ansible/aap-docs, pull requests merged in 2025-09, with the labels that each got.

#4174 Update diagrams and table in network guide. (#4100)
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
  downstream/images/network_client_initiated.png
  downstream/images/network_internally_initiated.png
Labels: 2.6, Backported to 2.6

#4176 Editing RHEM files for DITA (#4175)
  downstream/assemblies/platform/assembly-edge-manager-architecture.adoc
  downstream/assemblies/platform/assembly-edge-manager-install.adoc
  downstream/assemblies/platform/assembly-edge-manager-manage-apps.adoc
  downstream/assemblies/platform/assembly-edge-manager-manage-devices.adoc
  downstream/assemblies/platform/assembly-edge-manager-provisioning-devices.adoc
  downstream/assemblies/platform/assembly-edge-manager-troubleshooting.adoc
  downstream/modules/platform/con-edge-manager-provisioning-openshift-virt.adoc
  downstream/modules/platform/con-edge-manager-view-devices.adoc
  downstream/modules/platform/proc-edge-manager-build-app-packages.adoc
  downstream/modules/platform/proc-edge-manager-monitor-device-resources-cli.adoc
  downstream/modules/platform/proc-edge-manager-provision-cloudinit-config.adoc
  downstream/modules/platform/proc-edge-manager-provision-virt-create.adoc
  downstream/modules/platform/proc-edge-manager-view-device-inventory-ui.adoc
  downstream/modules/platform/ref-edge-manager-config-inline.adoc
  downstream/modules/platform/ref-edge-manager-disruption-parameters.adoc
  downstream/modules/platform/ref-edge-manager-fields-discovery.adoc
  downstream/modules/platform/ref-edge-manager-rule-files.adoc
  downstream/modules/platform/ref-edge-manager-specify-apps-inline.adoc
  downstream/modules/platform/ref-edge-manager-success-threshold.adoc
Labels: Migration, 2.6, Backported to 2.6

#4178 Add procedure to use custom inventory plugin
  downstream/assemblies/platform/assembly-controller-inventories.adoc
  downstream/modules/platform/proc-controller-use-custom-inventory.adoc
Labels: documentation, Controller, 2.5, Needs backport to 2.5, 2.6, Needs backport to 2.6

#4179 Add procedure to use custom inventory plugin (#4178)
  downstream/assemblies/platform/assembly-controller-inventories.adoc
  downstream/modules/platform/proc-controller-use-custom-inventory.adoc
Labels: 2.5, Backported to 2.5

#4180 Add procedure to use custom inventory plugin (#4178)
  downstream/assemblies/platform/assembly-controller-inventories.adoc
  downstream/modules/platform/proc-controller-use-custom-inventory.adoc
Labels: 2.6, Backported to 2.6

#4188 Backport-2.5-4182 to AAP-46220 Applied pre-migration updates to content for chapter 6 (#4182)
  downstream/assemblies/eda/assembly-eda-set-up-rhaap-credential.adoc
  downstream/modules/eda/con-replacing-controller-tokens.adoc
  downstream/modules/eda/proc-eda-delete-controller-token.adoc
  downstream/modules/eda/proc-eda-delete-rulebook-activations-with-cont-tokens.adoc
Labels: documentation, Ready for review, 2.5, Migration

#4167 Added clarification to Terraform backend configuration
  downstream/modules/platform/ref-controller-credential-terraform.adoc
Labels: documentation, Ready for review, Technical review complete, 2.5, Needs backport to 2.5, 2.6, Needs backport to 2.6

#4191 AAP-51163-onprem: Miscellaneous updates to Lightspeed onprem docs
  lightspeed/assemblies/assembly_troubleshooting-lightspeed.adoc
  lightspeed/modules/con_overview-lightspeed-onpremise.adoc
  lightspeed/modules/proc_create-connection-secrets.adoc
  lightspeed/modules/proc_use-rest-api.adoc
  lightspeed/modules/ref_troubleshooting-lightspeed-onpremise-config.adoc
Labels: Ready for review, Lightspeed

#4193 DITA migration changes: Playbooks Getting Started
  downstream/assemblies/playbooks/assembly-intro-to-playbooks.adoc
  downstream/assemblies/playbooks/assembly-networking-playbook.adoc
  downstream/modules/playbooks/proc-build-an-inventory.adoc
  downstream/modules/playbooks/proc-creating-a-playbook.adoc
  downstream/modules/playbooks/proc-run-ansible-network-playbook.adoc
  downstream/modules/playbooks/proc-starting-automation.adoc
  downstream/modules/playbooks/ref-create-variables.adoc
  downstream/modules/playbooks/ref-how-do-playbooks-work.adoc
  downstream/modules/playbooks/ref-how-to-use-ansible-playbooks.adoc
  downstream/modules/playbooks/ref-playbook-execution.adoc
  downstream/modules/playbooks/ref-playbooks-yaml-ini.adoc
  downstream/modules/playbooks/ref-tips-build-inventory.adoc
  downstream/titles/playbooks/playbooks-getting-started/master.adoc
Labels: 2.5, Needs backport to 2.5, 2.6, Needs backport to 2.6

#4195 DITA migration changes: Playbooks Getting Started (#4193)
  downstream/assemblies/playbooks/assembly-intro-to-playbooks.adoc
  downstream/assemblies/playbooks/assembly-networking-playbook.adoc
  downstream/modules/playbooks/proc-build-an-inventory.adoc
  downstream/modules/playbooks/proc-creating-a-playbook.adoc
  downstream/modules/playbooks/proc-run-ansible-network-playbook.adoc
  downstream/modules/playbooks/proc-starting-automation.adoc
  downstream/modules/playbooks/ref-create-variables.adoc
  downstream/modules/playbooks/ref-how-do-playbooks-work.adoc
  downstream/modules/playbooks/ref-how-to-use-ansible-playbooks.adoc
  downstream/modules/playbooks/ref-playbook-execution.adoc
  downstream/modules/playbooks/ref-playbooks-yaml-ini.adoc
  downstream/modules/playbooks/ref-tips-build-inventory.adoc
  downstream/titles/playbooks/playbooks-getting-started/master.adoc
Labels: 2.6, Backported to 2.6

#4197 2.6 Update CIDR IP address (#4196)
  downstream/modules/troubleshooting-aap/proc-troubleshoot-subnet-conflict.adoc
Labels: Backported to 2.6

#4198 2.5 Update CIDR IP address (#4196)
  downstream/modules/troubleshooting-aap/proc-troubleshoot-subnet-conflict.adoc
Labels: Backported to 2.5

#4204 Backport 2.6 4167 for AAP-50894: Clarify Terraform Backend Config in COntroller User Guide
  downstream/modules/platform/ref-controller-credential-terraform.adoc
Labels: documentation, Ready for review, Technical review complete, 2.6, Needs backport to 2.6

#4201 AAP-52550 FAQ content added to planning your upgrade
  downstream/assemblies/platform/assembly-upgrade-faqs.adoc
Labels: 2.6, Needs backport to 2.6

#4207 Backport for 2.6 - AAP 51980: Clarifications for migrating from community to TFE (#4166)
  downstream/assemblies/terraform-aap/assembly-terraform-migrating-from-community.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/terraform-aap/proc-terraform-migrating-from-community.adoc
Labels: documentation, Ready for review, Technical review complete, 2.6, Needs backport to 2.6

#4209 Backport PR #4192 from main to AAP 2.5 branch
  downstream/modules/platform/proc-create-chatbot-config-secret.adoc
Labels: Ready for review, 2.5, Backported to 2.5

#4210 Backport PR4192 from main to AAP 2.6 branch
  downstream/modules/platform/proc-create-chatbot-config-secret.adoc
Labels: Ready for review, 2.6, Backported to 2.6

#4214 AAP-52745: Updating TOC and title of Getting started with Terraform and AAP guide
  downstream/assemblies/terraform-aap/assembly-terraform-product.adoc
  downstream/assemblies/vault-aap/assembly-vault-product.adoc
  downstream/attributes/attributes.adoc
  downstream/titles/terraform-aap/terraform-aap-getting-started/docinfo.xml
  downstream/titles/terraform-aap/terraform-aap-getting-started/master.adoc
  downstream/titles/terraform-aap/terraform-aap-getting-started/vault-aap
Labels: documentation, Ready for review, 2.6, Needs backport to 2.6

#4213 Correct build error in Playbook guide
  downstream/aap-common/gplv3-license.adoc
Labels: 2.5, Needs backport to 2.5, 2.6, Needs backport to 2.6

#4221 Correct statement on RPM installer.
  downstream/modules/aap-hardening/con-deployment-methods.adoc
Labels: 2.5, Needs backport to 2.5, 2.6, Needs backport to 2.6

#4224 2.6 Update containerized troubleshooting vars (#4222)
  downstream/modules/platform/ref-containerized-troubleshoot-install.adoc
Labels: Backported to 2.6

#4225 2.5 Update containerized troubleshooting vars (#4222)
  downstream/modules/platform/ref-containerized-troubleshoot-install.adoc
Labels: Backported to 2.5

#4233 Fixing broken link in OCP backup guide (#4232)
  downstream/modules/platform/proc-aap-platform-pvc-restore.adoc
Labels: 2.6

#4236 Fixing typo in Saas backup table
  stories/topics/con-saas-backup-and-diaster-recovery.adoc
Labels: AAP on clouds, SaaS on AWS

#4235 AsciiDoc conversion for planning your upgrade
  downstream/assemblies/platform/assembly-upgrade-support-matrix.adoc
  downstream/modules/platform/ref-upgrade-rhel-support.adoc
  downstream/modules/platform/ref-upgrade-scenarios-container.adoc
  downstream/modules/platform/ref-upgrade-scenarios-openshift.adoc
  downstream/modules/platform/ref-upgrade-scenarios-rpm.adoc
Labels: Needs backport to 2.6

#4202 AAP-52254 2.6 metrics-utility updates
  downstream/assemblies/platform/assembly-metrics-utility.adoc
  downstream/modules/platform/con-controller-metrics-utility-containerized.adoc
  downstream/modules/platform/con-controller-metrics-utility-ocp.adoc
  downstream/modules/platform/proc-confguring-cron-jobs.adoc
  downstream/modules/platform/proc-configure-a-config-map.adoc
  downstream/modules/platform/proc-controller-metrics-utility-rhel.adoc
  downstream/modules/platform/proc-host-scripts-directories.adoc
  downstream/modules/platform/proc-making-scripts-executable.adoc
Labels: Ready for review, 2.6

#4237 Fixing typo in saas table
  stories/topics/con-saas-backup-and-diaster-recovery.adoc
Labels: AAP on clouds, SaaS on AWS

#4245 2.6 Update Containerized installation (#4243)
  downstream/modules/platform/proc-attaching-subscriptions.adoc
  downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc
  downstream/snippets/cont-tested-system-config.adoc
Labels: Backported to 2.6

#4181 AAP-52256 created modules for automation dashboard guide
  downstream/titles/automation-dashboard/automation-dashboard/assembly-appendix-inventory-file-automation-dashboard.adoc
  downstream/titles/automation-dashboard/automation-dashboard/assembly-view-key-metrics.adoc
  downstream/titles/automation-dashboard/automation-dashboard/automation-dashboard/con-filter-automation-data.adoc
  downstream/titles/automation-dashboard/automation-dashboard/automation-dashboard/con-top-overview-usage.adoc
  downstream/titles/automation-dashboard/automation-dashboard/automation-dashboard/proc-analyzing-costs-savings.adoc
  downstream/titles/automation-dashboard/automation-dashboard/automation-dashboard/proc-installing-automation-dashboard.adoc
  downstream/titles/automation-dashboard/automation-dashboard/automation-dashboard/proc-integrating-automation-dashboard.adoc
  downstream/titles/automation-dashboard/automation-dashboard/automation-dashboard/proc-uninstalling-automation-dashboard.adoc
  downstream/titles/automation-dashboard/automation-dashboard/automation-dashboard/ref-automation-dashboard-inventory-variables.adoc
  downstream/titles/automation-dashboard/master.adoc
Labels: Ready for review, 2.6

#4251 Adding troubleshooting section to generic OIDC (#4250)
  downstream/assemblies/platform/assembly-gw-config-authentication-type.adoc
  downstream/modules/platform/con-gw-troubleshoot-generic-oidc.adoc
  downstream/modules/platform/proc-gw-config-jwt-algorithms.adoc
  downstream/modules/platform/proc-gw-enable-debugging.adoc
  downstream/modules/platform/proc-gw-troubleshoot-oidc-scope-mismatch.adoc
Labels: 2.6, Backported to 2.6

#4293 AAP-53263: 1st set of Asciidoc conversion
  downstream/modules/platform/proc-accessing-rpm-repositories-for-locally-mounted-dvd.adoc
  downstream/modules/platform/proc-installing-the-aap-setup-bundle.adoc
  downstream/modules/platform/proc-setup-postgresql-ext-database.adoc
  downstream/modules/platform/ref-eda-system-requirements.adoc
  downstream/modules/platform/ref-postgresql-requirements.adoc
  downstream/modules/platform/ref-system-requirements.adoc
Labels: Ready for review, 2.6, Needs backport to 2.6

#4295 Backport PR #4293 from main to AAP 2.6 branch.
  downstream/modules/platform/proc-accessing-rpm-repositories-for-locally-mounted-dvd.adoc
  downstream/modules/platform/proc-installing-the-aap-setup-bundle.adoc
  downstream/modules/platform/proc-setup-postgresql-ext-database.adoc
  downstream/modules/platform/ref-eda-system-requirements.adoc
  downstream/modules/platform/ref-postgresql-requirements.adoc
  downstream/modules/platform/ref-system-requirements.adoc
Labels: 2.6, Backported to 2.6

#4296 2.5 backport: AAP-29944: adds content signing for hub on OCP procedure (#4253)
  downstream/assemblies/platform/assembly-installing-hub-operator.adoc
  downstream/modules/platform/proc-content-signing-hub-on-ocp.adoc
Labels: Automation Hub, 2.5, AAP operator

#4292 Adding authenticator timeouts section
  downstream/assemblies/platform/assembly-gw-config-authentication-type.adoc
  downstream/modules/platform/con-gw-configure-auth-timeouts.adoc
  downstream/modules/platform/proc-aap-enable-disable-auth.adoc
  downstream/modules/platform/proc-gw-setting-timeout-values.adoc
Labels: documentation, 2.6, Needs backport to 2.6

#4281 Making edits.
  downstream/titles/automation-dashboard/automation-dashboard/assembly-appendix-inventory-file-automation-dashboard.adoc
  downstream/titles/automation-dashboard/automation-dashboard/assembly-view-key-metrics.adoc
  downstream/titles/automation-dashboard/automation-dashboard/automation-dashboard/con-filter-automation-data.adoc
  downstream/titles/automation-dashboard/automation-dashboard/automation-dashboard/con-top-overview-usage.adoc
  downstream/titles/automation-dashboard/automation-dashboard/automation-dashboard/proc-analyzing-costs-savings.adoc
  downstream/titles/automation-dashboard/automation-dashboard/automation-dashboard/proc-installing-automation-dashboard.adoc
  downstream/titles/automation-dashboard/automation-dashboard/automation-dashboard/proc-integrating-automation-dashboard.adoc
  downstream/titles/automation-dashboard/automation-dashboard/automation-dashboard/proc-uninstalling-automation-dashboard.adoc
  downstream/titles/automation-dashboard/automation-dashboard/automation-dashboard/ref-automation-dashboard-inventory-variables.adoc
Labels: Draft, 2.6, Needs backport to 2.6

#4307 Making edits. (#4281)
  downstream/titles/automation-dashboard/automation-dashboard/assembly-appendix-inventory-file-automation-dashboard.adoc
  downstream/titles/automation-dashboard/automation-dashboard/assembly-view-key-metrics.adoc
  downstream/titles/automation-dashboard/automation-dashboard/automation-dashboard/con-filter-automation-data.adoc
  downstream/titles/automation-dashboard/automation-dashboard/automation-dashboard/con-top-overview-usage.adoc
  downstream/titles/automation-dashboard/automation-dashboard/automation-dashboard/proc-analyzing-costs-savings.adoc
  downstream/titles/automation-dashboard/automation-dashboard/automation-dashboard/proc-installing-automation-dashboard.adoc
  downstream/titles/automation-dashboard/automation-dashboard/automation-dashboard/proc-integrating-automation-dashboard.adoc
  downstream/titles/automation-dashboard/automation-dashboard/automation-dashboard/proc-uninstalling-automation-dashboard.adoc
  downstream/titles/automation-dashboard/automation-dashboard/automation-dashboard/ref-automation-dashboard-inventory-variables.adoc
Labels: 2.6

#4298 AAP-53267: Asciidoc conversion of RPM upgrade guide 2.6
  downstream/assemblies/platform/assembly-aap-upgrading-platform.adoc
  downstream/modules/platform/con-aap-upgrade-planning.adoc
  downstream/modules/platform/con-aap-upgrades.adoc
  downstream/modules/platform/con-upgrade-controller-hub-eda-unified-ui.adoc
  downstream/modules/platform/proc-choosing-obtaining-installer.adoc
  downstream/modules/platform/proc-editing-inventory-file-for-updates.adoc
  downstream/modules/platform/proc-upgrade-controller-hub-eda-unified-services.adoc
  downstream/modules/platform/proc-upgrade-controller-hub-eda-unified-ui.adoc
Labels: 2.6, Needs backport to 2.6

#4315 Update Support matrix for upgrade scenarios
  downstream/attributes/attributes.adoc
  downstream/modules/platform/ref-upgrade-scenarios-container.adoc
  downstream/modules/platform/ref-upgrade-scenarios-openshift.adoc
  downstream/modules/platform/ref-upgrade-scenarios-rpm.adoc
Labels: 2.6, Needs backport to 2.6

#4316 2.6 Update Support matrix for upgrade scenarios (#4315)
  downstream/attributes/attributes.adoc
  downstream/modules/platform/ref-upgrade-scenarios-container.adoc
  downstream/modules/platform/ref-upgrade-scenarios-openshift.adoc
  downstream/modules/platform/ref-upgrade-scenarios-rpm.adoc
Labels: Backported to 2.6

#4327 Backport-2.5-4087 for AAP-51751 Correct part of the description for Source Control URL field
  downstream/modules/eda/proc-eda-set-up-new-project.adoc
Labels: documentation, Ready for review, 2.5, Needs backport to 2.5

#4329 Removing incorrect verbiage as per AAP-49903
  downstream/modules/platform/con-storage-options-for-operator-installation-on-ocp.adoc
Labels: documentation, 2.5, AAP operator, Needs backport to 2.5, 2.6, Needs backport to 2.6

#4332 AAP-51597 edits
  downstream/modules/platform/proc-operator-deploy-redis.adoc
Labels: documentation, 2.5, AAP operator, 2.6

#4333 AAP-51597 edits (#4332)
  downstream/modules/platform/proc-operator-deploy-redis.adoc
Labels: 2.6

#4334 AAP-51597 edits (#4332)
  downstream/modules/platform/proc-operator-deploy-redis.adoc
Labels: 2.5

#4319 2.6 Access Management asciidoc updates
  downstream/assemblies/platform/assembly-gw-mapping.adoc
  downstream/modules/platform/con-gw-pluggable-authentication.adoc
  downstream/modules/platform/proc-gw-using-jinja-syntax-auth-maps.adoc
  downstream/modules/platform/proc-settings-gw-additional-options.adoc
  downstream/modules/platform/ref-upgrade-authentication-movement-2.4-to-2.6.adoc
  downstream/modules/platform/ref-upgrade-manage-org-auth-setting.adoc
  downstream/titles/planning-your-upgrade/master.adoc
Labels: documentation, Needs backport to 2.5, 2.6

#4230 Updating controller API examples
  downstream/assemblies/platform/assembly-controller-api-access-resources.adoc
  downstream/assemblies/platform/assembly-controller-api-auth-methods.adoc
  downstream/assemblies/platform/assembly-controller-api-search.adoc
  downstream/assemblies/platform/assembly-controller-api-sorting.adoc
  downstream/modules/platform/con-controller-api-oauth2-token.adoc
  downstream/modules/platform/proc-controller-api-browsing-api.adoc
  downstream/modules/platform/proc-controller-api-enable-users-oauth.adoc
  downstream/modules/platform/proc-controller-api-filtering.adoc
  downstream/modules/platform/proc-controller-api-search.adoc
  downstream/modules/platform/proc-controller-api-sorting.adoc
  downstream/modules/platform/proc-controller-api-using-pagination.adoc
  downstream/modules/platform/ref-controller-api-config-settings.adoc
  downstream/modules/platform/ref-controller-api-field-lookups.adoc
Labels: Controller, 2.5, Needs backport to 2.5, 2.6, Needs backport to 2.6

#4341 Updating controller API examples (#4230)
  downstream/assemblies/platform/assembly-controller-api-access-resources.adoc
  downstream/assemblies/platform/assembly-controller-api-auth-methods.adoc
  downstream/assemblies/platform/assembly-controller-api-search.adoc
  downstream/assemblies/platform/assembly-controller-api-sorting.adoc
  downstream/modules/platform/con-controller-api-oauth2-token.adoc
  downstream/modules/platform/proc-controller-api-browsing-api.adoc
  downstream/modules/platform/proc-controller-api-enable-users-oauth.adoc
  downstream/modules/platform/proc-controller-api-filtering.adoc
  downstream/modules/platform/proc-controller-api-search.adoc
  downstream/modules/platform/proc-controller-api-sorting.adoc
  downstream/modules/platform/proc-controller-api-using-pagination.adoc
  downstream/modules/platform/ref-controller-api-config-settings.adoc
  downstream/modules/platform/ref-controller-api-field-lookups.adoc
Labels: 2.5, Backported to 2.5

#4343 OCP 2.6 edits for 2.4 to 2.5 legacy (#4342)
  downstream/modules/platform/proc-operator-upgrade.adoc
Labels: 2.6

#4339 Removing legacy auth step from Access Management
  downstream/assemblies/platform/assembly-gw-token-based-authentication.adoc
  downstream/modules/platform/con-gw-pat-migration.adoc
  downstream/modules/platform/proc-controller-github-enterprise-org-settings.adoc
  downstream/modules/platform/proc-controller-github-enterprise-settings.adoc
  downstream/modules/platform/proc-controller-github-enterprise-team-settings.adoc
  downstream/modules/platform/proc-controller-github-organization-settings.adoc
  downstream/modules/platform/proc-controller-github-settings.adoc
  downstream/modules/platform/proc-controller-github-team-settings.adoc
  downstream/modules/platform/proc-controller-google-oauth2-settings.adoc
  downstream/modules/platform/proc-controller-set-up-LDAP.adoc
  downstream/modules/platform/proc-controller-set-up-SAML.adoc
  downstream/modules/platform/proc-controller-set-up-generic-oidc.adoc
  downstream/modules/platform/proc-controller-set-up-radius.adoc
  downstream/modules/platform/proc-controller-set-up-tacacs+.adoc
  downstream/modules/platform/proc-gw-config-keycloak-settings.adoc
  downstream/modules/platform/proc-gw-local-authentication.adoc
Labels: 2.6, Needs backport to 2.6

#4350 2.6 backport: AAP-52315: RBAC docs updates for 2.6 (#4254)
  downstream/assemblies/platform/assembly-controller-organizations.adoc
  downstream/assemblies/platform/assembly-controller-teams.adoc
  downstream/assemblies/platform/assembly-controller-users.adoc
  downstream/assemblies/platform/assembly-gw-managing-access.adoc
  downstream/assemblies/platform/assembly-gw-resources.adoc
  downstream/assemblies/platform/assembly-gw-roles.adoc
  downstream/modules/platform/proc-controller-add-organization-user.adoc
  downstream/modules/platform/proc-controller-create-organization.adoc
  downstream/modules/platform/proc-controller-creating-a-team.adoc
  downstream/modules/platform/proc-controller-creating-a-user.adoc
  downstream/modules/platform/proc-controller-deleting-a-user.adoc
  downstream/modules/platform/proc-controller-organization-notifications.adoc
  downstream/modules/platform/proc-controller-user-permissions.adoc
  downstream/modules/platform/proc-controller-user-roles.adoc
  downstream/modules/platform/proc-gw-add-admin-organization.adoc
  downstream/modules/platform/proc-gw-add-admin-team.adoc
  downstream/modules/platform/proc-gw-add-team-organization.adoc
  downstream/modules/platform/proc-gw-create-roles.adoc
  downstream/modules/platform/proc-gw-delete-roles.adoc
  downstream/modules/platform/proc-gw-delete-team.adoc
  downstream/modules/platform/proc-gw-edit-roles.adoc
  downstream/modules/platform/proc-gw-editing-a-user.adoc
  downstream/modules/platform/proc-gw-organizations-exec-env.adoc
  downstream/modules/platform/proc-gw-remove-roles-team.adoc
  downstream/modules/platform/proc-gw-remove-roles-user.adoc
  downstream/modules/platform/proc-gw-roles.adoc
  downstream/modules/platform/proc-gw-team-access-resources.adoc
  downstream/modules/platform/proc-gw-team-add-user.adoc
  downstream/modules/platform/proc-gw-team-remove-user.adoc
  downstream/modules/platform/proc-gw-user-access-resources.adoc
  downstream/modules/platform/proc-gw-users-list-view.adoc
  downstream/snippets/snip-gw-roles-note-multiple-components.adoc
Labels: 2.6

#4352 AAP-54033: Fix broken links
  downstream/modules/terraform-aap/proc-terraform-building-execution-environment.adoc
  downstream/modules/terraform-aap/proc-terraform-creating-launching-job-template.adoc
  downstream/modules/terraform-aap/proc-terraform-migrating-from-community.adoc
  downstream/modules/vault-aap/con-vault-intro.adoc
  downstream/modules/vault-aap/proc-vault-configuring-kv2-secret-get-lookup.adoc
  downstream/modules/vault-aap/proc-vault-configuring-kv2-secret.adoc
  downstream/modules/vault-aap/proc-vault-creating-credential-type.adoc
Labels: documentation, Ready for review, 2.5, Needs backport to 2.5, 2.6, Needs backport to 2.6

#4353 Backport for 2.5 AAP-54033: Fix broken links (#4352)
  downstream/modules/terraform-aap/proc-terraform-building-execution-environment.adoc
  downstream/modules/terraform-aap/proc-terraform-creating-launching-job-template.adoc
  downstream/modules/terraform-aap/proc-terraform-migrating-from-community.adoc
  downstream/modules/vault-aap/con-vault-intro.adoc
  downstream/modules/vault-aap/proc-vault-configuring-kv2-secret-get-lookup.adoc
  downstream/modules/vault-aap/proc-vault-configuring-kv2-secret.adoc
  downstream/modules/vault-aap/proc-vault-creating-credential-type.adoc
Labels: documentation, Ready for review, 2.5, Needs backport to 2.5

#4354 AAP-52315: updates links in RBAC content
  downstream/modules/platform/proc-controller-add-organization-user.adoc
  downstream/modules/platform/proc-controller-creating-a-team.adoc
  downstream/modules/platform/proc-controller-creating-a-user.adoc
  downstream/modules/platform/proc-gw-add-admin-organization.adoc
  downstream/modules/platform/proc-gw-add-admin-team.adoc
  downstream/modules/platform/proc-gw-add-team-organization.adoc
  downstream/modules/platform/proc-gw-delete-team.adoc
  downstream/modules/platform/proc-gw-editing-a-user.adoc
  downstream/modules/platform/proc-gw-team-add-user.adoc
  downstream/modules/platform/proc-gw-users-list-view.adoc
Labels: 2.6

#4356 2.6 backport: AAP-52315: updates links in RBAC content (#4354)
  downstream/modules/platform/proc-controller-add-organization-user.adoc
  downstream/modules/platform/proc-controller-creating-a-team.adoc
  downstream/modules/platform/proc-controller-creating-a-user.adoc
  downstream/modules/platform/proc-gw-add-admin-organization.adoc
  downstream/modules/platform/proc-gw-add-admin-team.adoc
  downstream/modules/platform/proc-gw-add-team-organization.adoc
  downstream/modules/platform/proc-gw-delete-team.adoc
  downstream/modules/platform/proc-gw-editing-a-user.adoc
  downstream/modules/platform/proc-gw-team-add-user.adoc
  downstream/modules/platform/proc-gw-users-list-view.adoc
Labels: 2.6

#4360 2.4 Automation dashboard docs AAP-52256 (#4264) (#4181) (#4273) (#…
  downstream/attributes/attributes.adoc
  downstream/titles/automation-dashboard/aap-common
  downstream/titles/automation-dashboard/analytics
  downstream/titles/automation-dashboard/attributes
  downstream/titles/automation-dashboard/automation-dashboard/assembly-appendix-inventory-file-automation-dashboard.adoc
  downstream/titles/automation-dashboard/automation-dashboard/assembly-view-key-metrics.adoc
  downstream/titles/automation-dashboard/automation-dashboard/automation-dashboard/con-filter-automation-data.adoc
  downstream/titles/automation-dashboard/automation-dashboard/automation-dashboard/con-top-overview-usage.adoc
  downstream/titles/automation-dashboard/automation-dashboard/automation-dashboard/proc-analyzing-costs-savings.adoc
  downstream/titles/automation-dashboard/automation-dashboard/automation-dashboard/proc-installing-automation-dashboard.adoc
  downstream/titles/automation-dashboard/automation-dashboard/automation-dashboard/proc-integrating-automation-dashboard.adoc
  downstream/titles/automation-dashboard/automation-dashboard/automation-dashboard/proc-uninstalling-automation-dashboard.adoc
  downstream/titles/automation-dashboard/automation-dashboard/automation-dashboard/ref-automation-dashboard-inventory-variables.adoc
  downstream/titles/automation-dashboard/docinfo.xml
  downstream/titles/automation-dashboard/images
  downstream/titles/automation-dashboard/master.adoc
  downstream/titles/automation-dashboard/snippets
Labels: 2.4

#4347 Asciidoc conversion of data movement doc
  downstream/assemblies/platform/assembly-upgrade-authentication-movement-2.4-to-2.6.adoc
  downstream/assemblies/platform/assembly-upgrade-data-movement.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/platform/con-upgrade-manage-org-setting.adoc
  downstream/modules/platform/con-upgrade-nested-team-behavior.adoc
  downstream/modules/platform/ref-upgrade-2.4-to-2.6.adoc
  downstream/modules/platform/ref-upgrade-2.5-2.6-controller.adoc
  downstream/modules/platform/ref-upgrade-2.5-2.6-eda.adoc
  downstream/modules/platform/ref-upgrade-2.5-2.6-hub.adoc
  downstream/modules/platform/ref-upgrade-2.5-to-2.6.adoc
  downstream/modules/platform/ref-upgrade-authentication-movement-2.4-to-2.6.adoc
  downstream/modules/platform/ref-upgrade-azure-auth.adoc
  downstream/modules/platform/ref-upgrade-github-auth.adoc
  downstream/modules/platform/ref-upgrade-google-auth.adoc
  downstream/modules/platform/ref-upgrade-ldap-auth.adoc
  downstream/modules/platform/ref-upgrade-oidc-auth.adoc
  downstream/modules/platform/ref-upgrade-post-upgrade.adoc
  downstream/modules/platform/ref-upgrade-radius-auth.adoc
  downstream/modules/platform/ref-upgrade-saml-auth.adoc
  downstream/modules/platform/ref-upgrade-tacacs-auth.adoc
  downstream/titles/planning-your-upgrade/master.adoc
Labels: 2.6, Needs backport to 2.6

#4362 Asciidoc conversion of data movement doc (#4347)
  downstream/assemblies/platform/assembly-upgrade-authentication-movement-2.4-to-2.6.adoc
  downstream/assemblies/platform/assembly-upgrade-data-movement.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/platform/con-upgrade-manage-org-setting.adoc
  downstream/modules/platform/con-upgrade-nested-team-behavior.adoc
  downstream/modules/platform/ref-upgrade-2.4-to-2.6.adoc
  downstream/modules/platform/ref-upgrade-2.5-2.6-controller.adoc
  downstream/modules/platform/ref-upgrade-2.5-2.6-eda.adoc
  downstream/modules/platform/ref-upgrade-2.5-2.6-hub.adoc
  downstream/modules/platform/ref-upgrade-2.5-to-2.6.adoc
  downstream/modules/platform/ref-upgrade-authentication-movement-2.4-to-2.6.adoc
  downstream/modules/platform/ref-upgrade-azure-auth.adoc
  downstream/modules/platform/ref-upgrade-github-auth.adoc
  downstream/modules/platform/ref-upgrade-google-auth.adoc
  downstream/modules/platform/ref-upgrade-ldap-auth.adoc
  downstream/modules/platform/ref-upgrade-oidc-auth.adoc
  downstream/modules/platform/ref-upgrade-post-upgrade.adoc
  downstream/modules/platform/ref-upgrade-radius-auth.adoc
  downstream/modules/platform/ref-upgrade-saml-auth.adoc
  downstream/modules/platform/ref-upgrade-tacacs-auth.adoc
  downstream/titles/planning-your-upgrade/master.adoc
Labels: 2.6, Backported to 2.6

#4363 Tested deployment models - Operator topologies
  downstream/modules/topologies/ref-ocp-a-env-a.adoc
  downstream/modules/topologies/ref-ocp-b-env-a.adoc
Labels: Needs backport to 2.5, Needs backport to 2.6

#4368 2.5 customized execution-environment.yml file leads to image not of type …
  downstream/modules/builder/proc-customize-ee-image.adoc
Labels: Backported to 2.5

#4373 2.4 Update 2.4 async RNs
  downstream/titles/release-notes/master.adoc
  downstream/titles/release-notes/topics/async-24-20250922.adoc
Labels: AAP Release notes, 2.4

#4345 AAP-53954: Asciidoc conversion of Overview content for Planning your Upgrade guide
  downstream/assemblies/platform/assembly-upgrade-overview.adoc
  downstream/modules/platform/con-aap-upgrade-overview.adoc
Labels: documentation, Ready for review, 2.6, Needs backport to 2.6

#4377 Update for AAP-53954: Added description and links to last row
  downstream/modules/platform/con-aap-upgrade-overview.adoc
Labels: documentation, Ready for review, 2.6, Backported to 2.6, Needs backport to 2.6

#4378 Added description and links to last row (#4377)
  downstream/modules/platform/con-aap-upgrade-overview.adoc
Labels: documentation, Ready for review, 2.6, Needs backport to 2.6

#4398 Add admonitions to explain database use (#4390)
  downstream/modules/topologies/ref-ocp-a-env-a.adoc
  downstream/modules/topologies/ref-ocp-b-env-a.adoc
Labels: 2.5, Backported to 2.5

#4399 Add admonitions to explain database use (#4390)
  downstream/modules/topologies/ref-ocp-a-env-a.adoc
  downstream/modules/topologies/ref-ocp-b-env-a.adoc
Labels: 2.6, Backported to 2.6

#4406 2.5 Adds gateway_uwsgi_processes to inventory appendix (#4109)
  downstream/modules/platform/ref-gateway-variables.adoc
Labels: Backported to 2.5

#4312 AAP-51490: AAP-51490: Asciidoc conversion of Ansible Lightspeed chatbot docs for AAP 2.6 release
  downstream/modules/platform/con-about-lightspeed-intelligent-assistant.adoc
  downstream/modules/platform/proc-configure-custom-mcp-server-chatbot.adoc
  downstream/modules/platform/proc-create-chatbot-config-secret.adoc
  downstream/modules/platform/proc-update-aap-operator-yaml-chatbot.adoc
Labels: 2.6, Needs backport to 2.6

#4409 2.6 AAP-49869 Add Ansible workspaces tech preview guide (#4401)
  downstream/assemblies/devtools/assembly-workspaces-create-launch.adoc
  downstream/assemblies/devtools/assembly-workspaces-develop.adoc
  downstream/assemblies/devtools/assembly-workspaces-intro.adoc
  downstream/assemblies/devtools/assembly-workspaces-management.adoc
  downstream/assemblies/devtools/assembly-workspaces-set-up-devspaces.adoc
  downstream/attributes/attributes.adoc
  downstream/images/devspaces-errors-playbook.png
  downstream/images/devtools-workspaces-architecture.png
  downstream/images/devtools-workspaces-provisioning.png
  downstream/modules/devtools/con-devspaces-auth.adoc
  downstream/modules/devtools/con-devspaces-components.adoc
  downstream/modules/devtools/con-devspaces-create-prerequisites.adoc
  downstream/modules/devtools/con-devspaces-image.adoc
  downstream/modules/devtools/con-devspaces-intro.adoc
  downstream/modules/devtools/proc-devspaces-create-code-workspace-file.adoc
  downstream/modules/devtools/proc-devspaces-create-content.adoc
  downstream/modules/devtools/proc-devspaces-create-devfile.adoc
  downstream/modules/devtools/proc-devspaces-create-repo.adoc
  downstream/modules/devtools/proc-devspaces-delete.adoc
  downstream/modules/devtools/proc-devspaces-edit-content.adoc
  downstream/modules/devtools/proc-devspaces-execute-playbooks.adoc
  downstream/modules/devtools/proc-devspaces-git-auth.adoc
  downstream/modules/devtools/proc-devspaces-install.adoc
  downstream/modules/devtools/proc-devspaces-launch.adoc
  downstream/modules/devtools/proc-devspaces-share-work.adoc
  downstream/modules/devtools/proc-workspaces-delete.adoc
  downstream/titles/ansible-workspaces/aap-common
  downstream/titles/ansible-workspaces/attributes
  downstream/titles/ansible-workspaces/devtools
  downstream/titles/ansible-workspaces/docinfo.xml
  downstream/titles/ansible-workspaces/images
  downstream/titles/ansible-workspaces/master.adoc
  downstream/titles/ansible-workspaces/snippets
Labels: 2.6

#4314 AAP-50437 Remove ansible-plugin-backstage-rhaap-backend-dynamic.tgz
  downstream/assemblies/devtools/assembly-rhdh-intro.adoc
  downstream/assemblies/devtools/assembly-rhdh-ocp-required-installation.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/devtools/proc-devtools-publish-roles-collection-pah.adoc
  downstream/modules/devtools/proc-rhdh-add-plugin-config.adoc
  downstream/modules/devtools/proc-rhdh-create-plugin-registry.adoc
  downstream/modules/devtools/proc-rhdh-download-plugins.adoc
  downstream/modules/devtools/proc-rhdh-install-dynamic-plugins-operator.adoc
  downstream/modules/devtools/proc-rhdh-uninstall-ocp-helm.adoc
  downstream/modules/devtools/proc-rhdh-uninstall-ocp-operator-plugins-cm.adoc
  downstream/modules/devtools/proc-rhdh-update-plugins-helm-version-numbers.adoc
  downstream/modules/devtools/proc-rhdh-update-plugins-operator-version-numbers.adoc
  downstream/modules/devtools/proc-self-service-download-tar.adoc
  downstream/modules/devtools/proc-self-service-setup-registry-image.adoc
  downstream/modules/devtools/ref-rhdh-full-aap-configmap-example.adoc
  downstream/modules/devtools/ref-rhdh-full-helm-chart-ansible-plugins.adoc
  downstream/titles/aap-plugin-rhdh-install/master.adoc
Labels: 2.5, Needs backport to 2.5, 2.6, Needs backport to 2.6

#4412 Release Notes Continuation (#4407)
  downstream/titles/release-notes/topics/aap-25-removed-features.adoc
  downstream/titles/release-notes/topics/aap-26.adoc
  downstream/titles/release-notes/topics/tech-preview.adoc
Labels: documentation, AAP Release notes, 2.6, Backported to 2.6

#4418 Backport-2.5-4413 to AAP-46222 Pre-migration prep for Chapter 8, Using automation decisions
  downstream/assemblies/eda/assembly-eda-rulebook-troubleshooting.adoc
  downstream/modules/eda/proc-eda-activation-keeps-restarting.adoc
  downstream/modules/eda/proc-eda-activation-stuck-pending.adoc
  downstream/modules/eda/proc-eda-cannot-connect-to-controller.adoc
  downstream/modules/eda/proc-eda-event-streams-not-sending-events.adoc
Labels: documentation, 2.5, Needs backport to 2.5, Migration

#4416 AAP-54344: Add more content to Planning Your Upgrade overview content
  downstream/modules/platform/con-aap-upgrade-overview.adoc
Labels: documentation, Ready for review, 2.6, Needs backport to 2.6

#4426 Backport 2.6 for 4416 (Updates to Planning Guide Overview)
  downstream/modules/platform/con-aap-upgrade-overview.adoc
Labels: documentation, Ready for review, 2.6, Needs backport to 2.6

#4423 Backport-2.5-4415 for AAP-46223 Pre-migration work EDA user guide, Chapter 9
  downstream/assemblies/eda/assembly-eda-rule-audit.adoc
  downstream/modules/eda/proc-eda-view-rule-audit-actions.adoc
  downstream/modules/eda/proc-eda-view-rule-audit-details.adoc
  downstream/modules/eda/proc-eda-view-rule-audit-events.adoc
Labels: documentation, Ready for review, 2.5, Needs backport to 2.5

#4424 Backport-2.6-4415 for AAP-46223 Pre-migration work EDA user guide, Chapter 9
  downstream/assemblies/eda/assembly-eda-rule-audit.adoc
  downstream/modules/eda/proc-eda-view-rule-audit-actions.adoc
  downstream/modules/eda/proc-eda-view-rule-audit-details.adoc
  downstream/modules/eda/proc-eda-view-rule-audit-events.adoc
Labels: documentation, Ready for review, Migration, 2.6, Needs backport to 2.6

#4400 AAP-52256-edits edited following final tech review
  downstream/modules/automation-dashboard/proc-installing-automation-dashboard.adoc
  downstream/modules/automation-dashboard/proc-integrating-automation-dashboard.adoc
  downstream/modules/automation-dashboard/proc-uninstalling-automation-dashboard.adoc
  downstream/modules/automation-dashboard/ref-automation-dashboard-inventory-variables.adoc
Labels: Ready for review, Ready for technical review, 2.4, 2.5, 2.6

#4408 AAP-52254-edits final edits for 2.6 metrics-utility docs
  downstream/modules/platform/proc-configure-a-config-map.adoc
  downstream/modules/platform/ref-deduplication-ccsp-ccspv2.adoc
  downstream/modules/platform/ref-select-a-date-range-ccspv2.adoc
  downstream/modules/platform/ref-select-a-date-range.adoc
  downstream/modules/platform/ref-select-report-date-range.adoc
  downstream/modules/platform/ref-show-ephemeral-use.adoc
  downstream/modules/platform/ref-storage-invocation.adoc
Labels: Ready for technical review, 2.6

#4431 AAP-52256-edits edited following final tech review (#4400)
  downstream/modules/automation-dashboard/proc-installing-automation-dashboard.adoc
  downstream/modules/automation-dashboard/proc-integrating-automation-dashboard.adoc
  downstream/modules/automation-dashboard/proc-uninstalling-automation-dashboard.adoc
  downstream/modules/automation-dashboard/ref-automation-dashboard-inventory-variables.adoc
Labels: 2.6

#4432 AAP-52256-edits edited following final tech review (#4400)
  downstream/modules/automation-dashboard/proc-installing-automation-dashboard.adoc
  downstream/modules/automation-dashboard/proc-integrating-automation-dashboard.adoc
  downstream/modules/automation-dashboard/proc-uninstalling-automation-dashboard.adoc
  downstream/modules/automation-dashboard/ref-automation-dashboard-inventory-variables.adoc
Labels: 2.5

#4433 AAP-52256-edits edited following final tech review (#4400)
  downstream/modules/automation-dashboard/proc-installing-automation-dashboard.adoc
  downstream/modules/automation-dashboard/proc-integrating-automation-dashboard.adoc
  downstream/modules/automation-dashboard/proc-uninstalling-automation-dashboard.adoc
  downstream/modules/automation-dashboard/ref-automation-dashboard-inventory-variables.adoc
Labels: 2.4

#4434 Added new edits from draft. (#4414)
  downstream/titles/release-notes/topics/aap-26.adoc
Labels: documentation, AAP Release notes, 2.6, Backported to 2.6

#4438 Add scm configure info (#4435)
  downstream/assemblies/platform/assembly-configure-egress-proxy.adoc
  downstream/modules/platform/proc-controller-scm-ssh-proxy-config.adoc
  downstream/titles/aap-operations-guide/master.adoc
Labels: 2.6, Backported to 2.6

#4429 AAP-49578: DITA migration formatting updates
  downstream/titles/hub/managing-content/master.adoc
Labels: Automation Hub, Migration, 2.6, Needs backport to 2.6

#4444 R.N. - Small edits + Updated platform-intro file. (#4436)
  downstream/titles/release-notes/topics/aap-26-removed-features.adoc
  downstream/titles/release-notes/topics/aap-26.adoc
  downstream/titles/release-notes/topics/platform-intro.adoc
Labels: documentation, AAP Release notes, 2.6, Backported to 2.6

#4446 Added info. about EDA 2.4 upgrade in RPM upgrade guide 2.5
  downstream/assemblies/platform/assembly-aap-upgrading-platform.adoc
  downstream/modules/platform/con-aap-upgrade-planning.adoc
  downstream/modules/platform/con-aap-upgrades.adoc
  downstream/modules/platform/proc-remove-EDA-2.4-db.adoc
Labels: 2.5

#4457 2.6 AAP-52370 update Using self-service portal guide (#4427)
  downstream/assemblies/devtools/assembly-self-service-deregister-templates.adoc
  downstream/assemblies/devtools/assembly-self-service-login.adoc
  downstream/assemblies/devtools/assembly-self-service-rbac.adoc
  downstream/assemblies/devtools/assembly-self-service-using-overview.adoc
  downstream/assemblies/devtools/assembly-self-service-working-templates.adoc
  downstream/attributes/attributes.adoc
  downstream/images/self-service-sign-in-page.png
  downstream/images/self-service-task-history.png
  downstream/images/self-service-templates-view.png
  downstream/images/self-service-unregister-template.png
  downstream/modules/devtools/con-self-service-customize-template.adoc
  downstream/modules/devtools/proc-devtools-install-podman-desktop-wsl.adoc
  downstream/modules/devtools/proc-self-service-add-template.adoc
  downstream/modules/devtools/proc-self-service-deregister-dynamic-templates.adoc
  downstream/modules/devtools/proc-self-service-history.adoc
  downstream/modules/devtools/proc-self-service-launch-template.adoc
  downstream/modules/devtools/proc-self-service-set-up-rbac.adoc
  downstream/modules/devtools/proc-self-service-sign-in.adoc
  downstream/modules/devtools/proc-self-service-templates-page.adoc
  downstream/modules/devtools/proc-self-service-templates-sync.adoc
  downstream/titles/self-service-using/master.adoc
Labels: 2.6

#4456 AAP-54229-update: Self review of RPM upgrade guide 2.6
  downstream/assemblies/platform/assembly-gateway-licensing.adoc
  downstream/assemblies/platform/assembly-platform-install-overview.adoc
  downstream/modules/platform/proc-remove-EDA-2.4-db.adoc
  downstream/modules/platform/ref-upgrade-api-specific-changes.adoc
Labels: 2.6, Needs backport to 2.6

#4467 Update 2.6 release notes - 20251001
  downstream/archive/archived-titles/release-notes/topics/aap-25-2-patch-release-7-oct-2024.adoc
  downstream/archive/archived-titles/release-notes/topics/docs-25.adoc
  downstream/titles/release-notes/master.adoc
  downstream/titles/release-notes/topics/platform-intro.adoc
Labels: AAP Release notes, Needs backport to 2.6

#4468 2.6 Update 2.6 release notes - 20251001 (#4467)
  downstream/archive/archived-titles/release-notes/topics/aap-25-2-patch-release-7-oct-2024.adoc
  downstream/archive/archived-titles/release-notes/topics/docs-25.adoc
  downstream/titles/release-notes/master.adoc
  downstream/titles/release-notes/topics/platform-intro.adoc
Labels: Backported to 2.6

#4471 2.5 Corrects build issue preventing content from showing (#4469)
  downstream/modules/platform/proc-controller-scm-ssh-proxy-config.adoc
Labels: Backported to 2.5

#4472 Formatting updates AsciiDoc/DITA
  downstream/modules/platform/proc-controller-scm-ssh-proxy-config.adoc
Labels: Needs backport to 2.5, Needs backport to 2.6

#4480 AAP-52136
  downstream/modules/platform/con-aap-notifications-feed.adoc
Labels: documentation, 2.6, Needs backport to 2.6

#4483 Backport PR #4455 from main to AAP 2.6 repo
  downstream/modules/platform/con-about-lightspeed-intelligent-assistant.adoc
  downstream/modules/platform/con-using-chatbot.adoc
  downstream/modules/platform/proc-create-chatbot-config-secret.adoc
  downstream/modules/platform/proc-update-aap-operator-yaml-chatbot.adoc
Labels: 2.6, Backported to 2.6
