Repository ansible/aap-docs, pull requests merged in 2025-04, with the labels that each got.

#3197 Adding manage applications chapter to RHEM doc
  downstream/assemblies/platform/assembly-edge-manager-images.adoc
  downstream/assemblies/platform/assembly-edge-manager-manage-apps.adoc
  downstream/modules/platform/con-edge-manager-build-bootc.adoc
  downstream/modules/platform/proc-edge-manager-build-app-packages.adoc
  downstream/modules/platform/proc-edge-manager-create-apps.adoc
  downstream/modules/platform/proc-edge-manager-deploy-apps.adoc
  downstream/modules/platform/proc-edge-manager-manage-apps-cli.adoc
  downstream/titles/edge-manager/edge-manager-user-guide/master.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#3183 [AAP-41175] 2.5 CSRF Management with Operator Docs
  downstream/assemblies/platform/assembly-configure-aap-operator.adoc
  downstream/assemblies/platform/assembly-installing-controller-operator.adoc
  downstream/assemblies/platform/assembly-operator-install-planning.adoc
  downstream/modules/platform/con-operator-csrf-management.adoc
  downstream/modules/platform/proc-controller-ingress-options.adoc
  downstream/modules/platform/proc-hub-ingress-options.adoc
  downstream/modules/platform/proc-operator-config-csrf-gateway.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#3199 Adding manage applications chapter to RHEM doc (#3197)
  downstream/assemblies/platform/assembly-edge-manager-images.adoc
  downstream/assemblies/platform/assembly-edge-manager-manage-apps.adoc
  downstream/modules/platform/con-edge-manager-build-bootc.adoc
  downstream/modules/platform/proc-edge-manager-build-app-packages.adoc
  downstream/modules/platform/proc-edge-manager-create-apps.adoc
  downstream/modules/platform/proc-edge-manager-deploy-apps.adoc
  downstream/modules/platform/proc-edge-manager-manage-apps-cli.adoc
  downstream/titles/edge-manager/edge-manager-user-guide/master.adoc
Labels: documentation, 2.5

#3201 [AAP-41175] 2.5 CSRF Management with Operator Docs (#3183)
  downstream/assemblies/platform/assembly-configure-aap-operator.adoc
  downstream/assemblies/platform/assembly-installing-controller-operator.adoc
  downstream/assemblies/platform/assembly-operator-install-planning.adoc
  downstream/modules/platform/con-operator-csrf-management.adoc
  downstream/modules/platform/proc-controller-ingress-options.adoc
  downstream/modules/platform/proc-hub-ingress-options.adoc
  downstream/modules/platform/proc-operator-config-csrf-gateway.adoc
Labels: documentation, 2.5, AAP operator

#3203 AAP-42782 edits (#3200)
  downstream/modules/platform/proc-operator-upgrade-external-db-gateway.adoc
Labels: documentation, 2.5, AAP operator

#3204 AAP-37304 Document how to edit an existing activation
  downstream/assemblies/eda/assembly-eda-rulebook-activations.adoc
  downstream/modules/eda/proc-eda-edit-rulebook-activation.adoc
Labels: documentation, Ready for review, Technical review complete, 2.5, Needs backport to 2.5

#3206 improving hyperlink accuracy
  downstream/modules/platform/con-operator-csrf-management.adoc
Labels: documentation, 2.5, AAP operator, Needs backport to 2.5

#3207 improving hyperlink accuracy (#3206)
  downstream/modules/platform/con-operator-csrf-management.adoc
Labels: 2.5, AAP operator

#3208 Create snippets for Tested deployment models
  downstream/modules/topologies/ref-cont-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-b.adoc
  downstream/modules/topologies/ref-rpm-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-b.adoc
  downstream/snippets/cont-tested-system-config.adoc
  downstream/snippets/cont-tested-vm-config.adoc
  downstream/snippets/enterprise-topologies.adoc
  downstream/snippets/growth-topologies.adoc
  downstream/snippets/mixed-topologies.adoc
  downstream/snippets/rpm-env-a-tested-system-config.adoc
  downstream/snippets/rpm-env-b-tested-system-config.adoc
  downstream/snippets/rpm-tested-vm-config.adoc
Labels: 2.5, Needs backport to 2.5

#3209 2.5 Create snippets for Tested deployment models (#3208)
  downstream/modules/topologies/ref-cont-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-b.adoc
  downstream/modules/topologies/ref-rpm-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-b.adoc
  downstream/snippets/cont-tested-system-config.adoc
  downstream/snippets/cont-tested-vm-config.adoc
  downstream/snippets/enterprise-topologies.adoc
  downstream/snippets/growth-topologies.adoc
  downstream/snippets/mixed-topologies.adoc
  downstream/snippets/rpm-env-a-tested-system-config.adoc
  downstream/snippets/rpm-env-b-tested-system-config.adoc
  downstream/snippets/rpm-tested-vm-config.adoc
Labels: 2.5, Backported to 2.5

#3210 AAP-42948 Changed all instances of copy to duplicate, per latest platform UI
  downstream/modules/eda/proc-eda-duplicate-credential.adoc
Labels: documentation, Ready for review, 2.5, Delay backport, Needs backport to 2.5

#3213 Updating title of RHEM doc
  downstream/titles/controller/controller-user-guide/docinfo.xml
  downstream/titles/edge-manager/edge-manager-user-guide/docinfo.xml
  downstream/titles/edge-manager/edge-manager-user-guide/master.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#3214 Updating title of RHEM doc (#3213)
  downstream/titles/controller/controller-user-guide/docinfo.xml
  downstream/titles/edge-manager/edge-manager-user-guide/docinfo.xml
  downstream/titles/edge-manager/edge-manager-user-guide/master.adoc
Labels: documentation, 2.5

#3211 AAP-42964 edits
  stories/topics/proc-saas-enabling-aws-privatelink.adoc
Labels: documentation, Ansible on AWS, SaaS on AWS

#3215 Fixing level offset issue
  downstream/assemblies/platform/assembly-operator-install-planning.adoc
Labels: documentation, 2.5, AAP operator

#3216 Fixing level offset issue (#3215)
  downstream/assemblies/platform/assembly-operator-install-planning.adoc
Labels: 2.5, AAP operator

#3202 AAP-40667 edits
  downstream/assemblies/platform/assembly-controller-resource-operator.adoc
  downstream/modules/platform/con-resource-operator-overview.adoc
  downstream/modules/platform/proc-add-controller-access-token.adoc
  downstream/modules/platform/proc-create-a-jobtemplate.adoc
  downstream/modules/platform/proc-create-an-ansiblejob.adoc
  downstream/modules/platform/proc-create-crs-resource-operator.adoc
  downstream/modules/platform/proc-operator-create-controller-credential.adoc
  downstream/modules/platform/proc-operator-create-controller-inventory.adoc
  downstream/modules/platform/proc-operator-create-controller-project.adoc
  downstream/modules/platform/proc-operator-create-controller-schedule.adoc
  downstream/modules/platform/proc-operator-create-controller-workflow-template.adoc
  downstream/modules/platform/proc-operator-create-controller-workflow.adoc
  downstream/modules/platform/proc-use-controller-resource-operator.adoc
Labels: documentation, 2.5, AAP operator, Needs backport to 2.5

#3219 AAP-43262: Fixed code formatting for infra.controller_configuration in table
  downstream/modules/aap-hardening/ref-infrastructure-as-code.adoc
Labels: documentation, Ready for review, 2.5, Needs backport to 2.5

#3220 Fixed code formatting for infra.controller_configuration in table (#3…
  downstream/modules/aap-hardening/ref-infrastructure-as-code.adoc
Labels: documentation, Ready for review, 2.5, Needs backport to 2.5

#3221 AAP-42630: Added prerequisite for RHEL 9.5 issue
  downstream/assemblies/platform/assembly-aap-upgrading-platform.adoc
Labels: 2.5, Needs backport to 2.5

#3222 Backport PR #3221 from main to AAP 2.5
  downstream/assemblies/platform/assembly-aap-upgrading-platform.adoc
Labels: 2.5, Backported to 2.5

#3218 Making edits found in staged preview of RHEM doc
  downstream/assemblies/platform/assembly-edge-manager-device-fleets.adoc
  downstream/assemblies/platform/assembly-edge-manager-intro.adoc
  downstream/assemblies/platform/assembly-edge-manager-manage-devices.adoc
  downstream/modules/platform/con-edge-manager-enroll.adoc
  downstream/modules/platform/con-edge-manager-manage-os-config.adoc
  downstream/modules/platform/proc-edge-manager-config-git-cli.adoc
  downstream/modules/platform/proc-edge-manager-enroll-device-cli.adoc
  downstream/modules/platform/ref-edge-manager-device-lifecycle.adoc
  downstream/modules/platform/ref-edge-manager-device-templates.adoc
  downstream/modules/platform/ref-edge-manager-rule-files.adoc
  downstream/titles/edge-manager/edge-manager-user-guide/master.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#3223 Making edits found in staged preview of RHEM doc (#3218)
  downstream/assemblies/platform/assembly-edge-manager-device-fleets.adoc
  downstream/assemblies/platform/assembly-edge-manager-intro.adoc
  downstream/assemblies/platform/assembly-edge-manager-manage-devices.adoc
  downstream/modules/platform/con-edge-manager-enroll.adoc
  downstream/modules/platform/con-edge-manager-manage-os-config.adoc
  downstream/modules/platform/proc-edge-manager-config-git-cli.adoc
  downstream/modules/platform/proc-edge-manager-enroll-device-cli.adoc
  downstream/modules/platform/ref-edge-manager-device-lifecycle.adoc
  downstream/modules/platform/ref-edge-manager-device-templates.adoc
  downstream/modules/platform/ref-edge-manager-rule-files.adoc
  downstream/titles/edge-manager/edge-manager-user-guide/master.adoc
Labels: 2.5, Backported to 2.5

#3230 AAP-43404: Added content for viewing logs
  lightspeed/assemblies/assembly_developing-ansible-content.adoc
  lightspeed/images/example_view_logs.png
  lightspeed/modules/proc_view-logs.adoc
Labels: Ready for review, Technical review complete, Lightspeed

#3231 Editing container group procedure
  downstream/modules/platform/proc-controller-create-container-group.adoc
Labels: documentation, Controller, 2.5, Needs backport to 2.5

#3233 Editing container group procedure (#3231)
  downstream/modules/platform/proc-controller-create-container-group.adoc
Labels: documentation, Controller, 2.5

#3234 Add extra_settings inventory file vars
  downstream/modules/platform/ref-controller-variables.adoc
  downstream/modules/platform/ref-eda-controller-variables.adoc
  downstream/modules/platform/ref-gateway-variables.adoc
  downstream/modules/platform/ref-hub-variables.adoc
Labels: Technical review complete, 2.5, Needs backport to 2.5

#3236 2.5 Add extra_settings inventory file vars (#3234)
  downstream/modules/platform/ref-controller-variables.adoc
  downstream/modules/platform/ref-eda-controller-variables.adoc
  downstream/modules/platform/ref-gateway-variables.adoc
  downstream/modules/platform/ref-hub-variables.adoc
Labels: 2.5, Backported to 2.5

#3235 Editing container group proc in 2.4 doc
  downstream/modules/platform/proc-controller-create-container-group.adoc
Labels: documentation, Controller, 2.4

#3238 Updated release notes based upon Scott Harwell's suggestions. (#3237)
  downstream/titles/release-notes/async/aap-25-20250409.adoc
Labels: AAP Release notes

#3239 AAP-42630-update: Incorporated Scott Harwell's feedback in RPM upgrade guide
  downstream/assemblies/platform/assembly-aap-upgrading-platform.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#3240 AAP-42630-update: Incorporated feedback in RPM upgrade guide prereq. …
  downstream/assemblies/platform/assembly-aap-upgrading-platform.adoc
Labels: Ready for review, 2.5, Backported to 2.5

#3242 Fixing broken links in Containerized installation
  downstream/modules/hub/proc-deploying-your-system-for-container-signing.adoc
  downstream/modules/platform/ref-general-inventory-variables.adoc
  downstream/modules/platform/ref-receptor-inventory-variables.adoc
Labels: 2.5, Needs backport to 2.5

#3244 AAP-43648 Adding note on EDA 2.4-2.5 support
  downstream/modules/platform/proc-operator-upgrade.adoc
Labels: 2.5, AAP operator

#3245 AAP-43648 Adding note on EDA 2.4-2.5 support (#3244)
  downstream/modules/platform/proc-operator-upgrade.adoc
Labels: documentation, AAP operator

#3246 AAP-43744 updating title for 2.4 and 2.5
  downstream/modules/platform/proc-install-cli-aap-operator.adoc
Labels: documentation, 2.4, 2.5, AAP operator

#3247 AAP-43744 updating title for 2.4 and 2.5 (#3246)
  downstream/modules/platform/proc-install-cli-aap-operator.adoc
Labels: 2.5, AAP operator

#3248 AAP-43744 updating title for 2.4 and 2.5 (#3246)
  downstream/modules/platform/proc-install-cli-aap-operator.adoc
Labels: 2.4, AAP operator

#3249 AAP-43744 sentence to be removed
  downstream/modules/platform/proc-install-cli-aap-operator.adoc
Labels: 2.4, 2.5, AAP operator

#3250 AAP-43744 sentence to be removed (#3249)
  downstream/modules/platform/proc-install-cli-aap-operator.adoc
Labels: 2.4

#3251 AAP-43744 sentence to be removed (#3249)
  downstream/modules/platform/proc-install-cli-aap-operator.adoc
Labels: 2.5, AAP operator

#3252 Adding quick starts directory to AAP repo
  downstream/quick-start-yamls/readme-quickstarts.md
Labels: 2.5

#3253 AAP-43745 Adding quick starts directory to AAP repo (#3252)
  downstream/quick-start-yamls/readme-quickstarts.md
Labels: repo, 2.5, Backported to 2.5

#3254 Adding Quick Starts to AAP repo
  downstream/quick-start-yamls/Ansible-lightspeed.yaml
  downstream/quick-start-yamls/Automation Developer/Getting-started-with-AAP-Automation-Developer.yaml
  downstream/quick-start-yamls/Automation-Operator/Environments-automation-operator.yaml
  downstream/quick-start-yamls/Automation-Operator/Getting-started-with-AAP-automation-operator.yaml
  downstream/quick-start-yamls/Automation-Operator/Inventories-automation-operator.yaml
  downstream/quick-start-yamls/Automation-Operator/Projects-automation-operator.yaml
  downstream/quick-start-yamls/Automation-Operator/Rulebook-activations-automation-operator.yaml
  downstream/quick-start-yamls/Automation-Operator/Templates-automation-operator.yaml
  downstream/quick-start-yamls/Automation-mesh.yaml
  downstream/quick-start-yamls/Build-decision-environment.yaml
  downstream/quick-start-yamls/Build-execution-environment.yaml
  downstream/quick-start-yamls/Create-inventory.yaml
  downstream/quick-start-yamls/Create-project.yaml
  downstream/quick-start-yamls/Create-rulebook-activation.yaml
  downstream/quick-start-yamls/Creating-a-job-template.yaml
  downstream/quick-start-yamls/Platform Admin/Create-organization-platform-admin.yaml
  downstream/quick-start-yamls/Platform Admin/Create-teams-platform-admin.yaml
  downstream/quick-start-yamls/Platform Admin/Create-users-platform-admin.yaml
  downstream/quick-start-yamls/Platform Admin/Dynamic-inventory-platform-admin.yaml
  downstream/quick-start-yamls/Platform Admin/Getting-started-with-AAP-platform-admin.yaml
  downstream/quick-start-yamls/Platform Admin/Review-roles-platform-admin.yaml
Labels: 2.5, Needs backport to 2.5

#3255 Adding Quick Starts to AAP repo (#3254)
  downstream/quick-start-yamls/Ansible-lightspeed.yaml
  downstream/quick-start-yamls/Automation Developer/Getting-started-with-AAP-Automation-Developer.yaml
  downstream/quick-start-yamls/Automation-Operator/Environments-automation-operator.yaml
  downstream/quick-start-yamls/Automation-Operator/Getting-started-with-AAP-automation-operator.yaml
  downstream/quick-start-yamls/Automation-Operator/Inventories-automation-operator.yaml
  downstream/quick-start-yamls/Automation-Operator/Projects-automation-operator.yaml
  downstream/quick-start-yamls/Automation-Operator/Rulebook-activations-automation-operator.yaml
  downstream/quick-start-yamls/Automation-Operator/Templates-automation-operator.yaml
  downstream/quick-start-yamls/Automation-mesh.yaml
  downstream/quick-start-yamls/Build-decision-environment.yaml
  downstream/quick-start-yamls/Build-execution-environment.yaml
  downstream/quick-start-yamls/Create-inventory.yaml
  downstream/quick-start-yamls/Create-project.yaml
  downstream/quick-start-yamls/Create-rulebook-activation.yaml
  downstream/quick-start-yamls/Creating-a-job-template.yaml
  downstream/quick-start-yamls/Platform Admin/Create-organization-platform-admin.yaml
  downstream/quick-start-yamls/Platform Admin/Create-teams-platform-admin.yaml
  downstream/quick-start-yamls/Platform Admin/Create-users-platform-admin.yaml
  downstream/quick-start-yamls/Platform Admin/Dynamic-inventory-platform-admin.yaml
  downstream/quick-start-yamls/Platform Admin/Getting-started-with-AAP-platform-admin.yaml
  downstream/quick-start-yamls/Platform Admin/Review-roles-platform-admin.yaml
Labels: 2.5, Backported to 2.5

#3241 AAP-39723: updates login flow to push EEs to PAH
  downstream/modules/hub/proc-push-container.adoc
Labels: Automation Hub, 2.5, Needs backport to 2.5

#3258 bp 2.5: AAP-3241 corrects login instructions (#3241)
  downstream/modules/hub/proc-push-container.adoc
Labels: Automation Hub, 2.5

#3260 2.5 Update con-devtools-requirements.adoc (#3259)
  downstream/modules/devtools/con-devtools-requirements.adoc
Labels: 2.5

#3261 Update con-devtools-requirements.adoc (#3259)
  downstream/modules/devtools/con-devtools-requirements.adoc
Labels: 2.4

#3232 Update inventory vars for EDA
  downstream/modules/platform/ref-database-inventory-variables.adoc
  downstream/modules/platform/ref-eda-controller-variables.adoc
  downstream/modules/platform/ref-hub-variables.adoc
Labels: Technical review complete, 2.5, Needs backport to 2.5

#3262 2.5 Update inventory vars for EDA (#3232)
  downstream/modules/platform/ref-database-inventory-variables.adoc
  downstream/modules/platform/ref-eda-controller-variables.adoc
  downstream/modules/platform/ref-hub-variables.adoc
Labels: 2.5, Backported to 2.5

#3264 AAP-40546 - Add Migrating LDAP users content to the Upgrade guide
  downstream/assemblies/platform/assembly-aap-post-upgrade.adoc
  downstream/modules/platform/con-aap-legacy-user-login.adoc
  downstream/modules/platform/con-aap-migrate-LDAP-users.adoc
  downstream/modules/platform/proc-aap-migrate-LDAP-users.adoc
  downstream/modules/platform/proc-aap-migrate-SAML-users.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#3266 [Backport] AAP-40546 - Add Migrating LDAP users content to the Upgrade guide (#3264)
  downstream/assemblies/platform/assembly-aap-post-upgrade.adoc
  downstream/modules/platform/con-aap-legacy-user-login.adoc
  downstream/modules/platform/con-aap-migrate-LDAP-users.adoc
  downstream/modules/platform/proc-aap-migrate-LDAP-users.adoc
  downstream/modules/platform/proc-aap-migrate-SAML-users.adoc
Labels: Ready for review, 2.5

#3268 Update IOPS to a standardized 3000
  downstream/modules/platform/ref-controller-capacity-planning-exercise.adoc
  downstream/modules/platform/ref-controller-system-requirements.adoc
  downstream/modules/platform/ref-eda-system-requirements.adoc
  downstream/modules/platform/ref-system-requirements.adoc
  downstream/modules/topologies/ref-rpm-a-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-b.adoc
  downstream/modules/topologies/ref-rpm-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-b.adoc
  downstream/snippets/rpm-tested-vm-config.adoc
Labels: 2.5, Needs backport to 2.5

#3267 AAP-42952: AAP-42952: Added procedure for gathering logs for troubleshooting RPM installation
  downstream/assemblies/platform/assembly-appendix-troubleshoot-rpm-aap.adoc
  downstream/modules/platform/ref-rpm-troubleshoot-generating-logs.adoc
  downstream/titles/aap-installation-guide/master.adoc
Labels: Ready for review, Technical review complete, 2.5, Needs backport to 2.5

#3270 Backport PR # 3267 from main to AAP 2.5 branch
  downstream/assemblies/platform/assembly-appendix-troubleshoot-rpm-aap.adoc
  downstream/modules/platform/ref-rpm-troubleshoot-generating-logs.adoc
  downstream/titles/aap-installation-guide/master.adoc
Labels: Ready for review, 2.5, Backported to 2.5

#3265 AAP-43417 - Update Entra ID configuration to include Group claims info
  downstream/modules/platform/proc-controller-set-up-azure.adoc
Labels: 2.5, Backported to 2.5, Needs backport to 2.5

#3273 AAP-37000: Updated procedure and variables for deploying external db
  downstream/modules/platform/proc-setup-postgresql-ext-database.adoc
Labels: Ready for review, Technical review complete, 2.5, Needs backport to 2.5

#3274 [Backport] AAP-43417 - Update Entra ID configuration to include Group claims info (#3265)
  downstream/modules/platform/proc-controller-set-up-azure.adoc
Labels: Ready for review, 2.5

#3275 Backport pull request #3273 from main to 2.5
  downstream/modules/platform/proc-setup-postgresql-ext-database.adoc
Labels: Ready for review, 2.5, Backported to 2.5

#3277 AAP-43381 Edits - Note on precreated PVCs
  downstream/modules/platform/proc-aap-platform-gateway-backup.adoc
Labels: documentation, 2.5, AAP operator, Needs backport to 2.5

#3278 AAP-43381 Edits - Note on precreated PVCs (#3277)
  downstream/modules/platform/proc-aap-platform-gateway-backup.adoc
Labels: documentation, 2.5, AAP operator

#3279 Adding clarity to additional settings for controller
  downstream/modules/platform/con-controller-additional-settings.adoc
Labels: Controller, 2.5, Needs backport to 2.5

#3280 Adding clarity to additional settings for controller (#3279)
  downstream/modules/platform/con-controller-additional-settings.adoc
Labels: documentation, Controller, 2.5, Backported to 2.5

#3257 AAP-43726 Update links in plug-ins installation guide
  downstream/assemblies/devtools/assembly-rhdh-telemetry-capturing.adoc
  downstream/modules/devtools/proc-rhdh-add-custom-configmap.adoc
  downstream/modules/devtools/proc-rhdh-install-dynamic-plugins-operator.adoc
Labels: Needs backport to 2.4, 2.4, 2.5, Needs backport to 2.5

#3281 2.5 AAP-43726 Update links in plug-ins installation guide (#3257)
  downstream/assemblies/devtools/assembly-rhdh-telemetry-capturing.adoc
  downstream/modules/devtools/proc-rhdh-add-custom-configmap.adoc
  downstream/modules/devtools/proc-rhdh-install-dynamic-plugins-operator.adoc
Labels: 2.5

#3282 2.4 AAP-43726 Update links in plug-ins installation guide (#3257)
  downstream/assemblies/devtools/assembly-rhdh-telemetry-capturing.adoc
  downstream/modules/devtools/proc-rhdh-add-custom-configmap.adoc
  downstream/modules/devtools/proc-rhdh-install-dynamic-plugins-operator.adoc
Labels: 2.4

#3276 AAP-42888 - Add information for support of LDAPUnion for multiple user searches
  downstream/modules/platform/proc-controller-set-up-LDAP.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#3283 [Backport] AAP-42888 - Add information for support of LDAPUnion for multiple user searches (#3276)
  downstream/modules/platform/proc-controller-set-up-LDAP.adoc
Labels: Ready for review, 2.5

#3285 AAP-40219 - add info re: Azure parameters used by AAP/other clarifications
  downstream/modules/platform/proc-controller-set-up-azure.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#3286 AAP-40219 - add info re: Azure parameters used by AAP/other clarifications (#3285)
  downstream/modules/platform/proc-controller-set-up-azure.adoc
Labels: Ready for review, 2.5

#3288 Change copy to duplicate
  downstream/assemblies/platform/assembly-controller-credentials.adoc
  downstream/assemblies/platform/assembly-controller-execution-environments.adoc
  downstream/assemblies/platform/assembly-controller-inventories.adoc
  downstream/assemblies/platform/assembly-controller-projects.adoc
  downstream/assemblies/platform/assembly-ug-controller-job-templates.adoc
  downstream/assemblies/platform/assembly-ug-controller-workflow-job-templates.adoc
Labels: Controller, 2.5, Needs backport to 2.5

#3291 Update Using custom TLS certificates in Containerized installation
  downstream/modules/platform/ref-using-custom-tls-certificates.adoc
Labels: Technical review complete, 2.5, Needs backport to 2.5

#3292 Update python version
  downstream/modules/builder/con-about-ee.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#3293 2.5 Update Using custom TLS certificates in Containerized installation (#3291)
  downstream/modules/platform/ref-using-custom-tls-certificates.adoc
Labels: 2.5, Backported to 2.5

#3294 Update python version (#3292)
  downstream/modules/builder/con-about-ee.adoc
Labels: 2.5, Backported to 2.5

#3295 Troubleshooting-updates: Included additional troubleshooting info
  lightspeed/modules/proc_troubleshooting-vscode.adoc
Labels: Ready for review, Lightspeed

#3297 AAP-42705: Updated the storage requirements for VMs
  downstream/modules/platform/ref-system-requirements.adoc
Labels: 2.5, Needs backport to 2.5

#3298 AAP-42705: Updated the storage requirements for VMs (#3297)
  downstream/modules/platform/ref-system-requirements.adoc
Labels: Ready for review, 2.5, Backported to 2.5

#3287 AAP-39751: Notes that hub does not check other repos for dependencies
  downstream/modules/hub/con-rh-certified-synclist.adoc
  downstream/modules/hub/proc-create-remote.adoc
Labels: Automation Hub, 2.4, 2.5

#3299 AAP-42905 - Corrected gateway token API path
  downstream/modules/platform/ref-controller-refresh-existing-token.adoc
  downstream/modules/platform/ref-controller-revoke-access-token.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#3289 AAP-17406 edits
  downstream/assemblies/platform/assembly-configure-aap-operator.adoc
  downstream/modules/platform/proc-operator-troubleshoot-ext-db.adoc
Labels: documentation, Needs backport to 2.4, 2.4, 2.5, AAP operator, Needs backport to 2.5

#3300 AAP-17406 edits (#3289)
  downstream/assemblies/platform/assembly-configure-aap-operator.adoc
  downstream/modules/platform/proc-operator-troubleshoot-ext-db.adoc
Labels: 2.5

#3301 AAP-17406 edits
  downstream/assemblies/platform/assembly-installing-controller-operator.adoc
  downstream/modules/platform/proc-operator-troubleshoot-ext-db.adoc
Labels: 2.4

#3303 Changed OCP port assignment (#3302)
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
Labels: 2.5, Backported to 2.5

#3304 [Backport] AAP-42905 - Corrected gateway token API path (#3299)
  downstream/modules/platform/ref-controller-refresh-existing-token.adoc
  downstream/modules/platform/ref-controller-revoke-access-token.adoc
Labels: Ready for review, 2.5

#3306 ANSTRAT-1462: Add note about path pulling in the entire directory (#3…
  downstream/modules/platform/proc-controller-configure-jobs.adoc
  downstream/modules/platform/ref-controller-isolation-functionality.adoc
Labels: documentation, Ready for review, 2.5, Needs backport to 2.5

#3305 backport to 2.5: AAP-39751: Notes that hub does not check other repos for dependencies
  downstream/modules/hub/con-rh-certified-synclist.adoc
  downstream/modules/hub/proc-create-remote.adoc
Labels: Automation Hub, 2.5

#3307 backport to 2.4: AAP-39751: Notes that hub does not check other repos for dependencies
  downstream/modules/hub/con-rh-certified-synclist.adoc
  downstream/modules/hub/proc-create-remote.adoc
Labels: Automation Hub, 2.4

#3308 AAP-44196 Adding Tip Admonition
  downstream/assemblies/platform/assembly-appendix-operator-crs.adoc
Labels: documentation, 2.5, AAP operator, Needs backport to 2.5

#3309 AAP-44196 Adding Tip Admonition (#3308)
  downstream/assemblies/platform/assembly-appendix-operator-crs.adoc
Labels: documentation, 2.5, AAP operator

#3315 2.4 Update link to creating roles in Creator guide (#3313)
  downstream/modules/dev-guide/proc-create-role.adoc
Labels: Backported to 2.4, 2.4

#3311 AAP-44016 - Update note that group identifiers must be entered in lowercase
  downstream/modules/platform/con-gw-authenticator-map-triggers.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#3317 [Backport] AAP-44016 - Update note that group identifiers must be entered in lowercase (#3311)
  downstream/modules/platform/con-gw-authenticator-map-triggers.adoc
Labels: Ready for review, 2.5

#3319 AAP-44093 edits and some stray typos
  downstream/modules/platform/proc-aap-create-aap-object.adoc
  downstream/modules/platform/proc-create-secret-key-secret.adoc
  downstream/modules/platform/proc-operator-deploy-redis.adoc
  downstream/modules/platform/proc-operator-upgrade.adoc
Labels: 2.5, AAP operator, Needs backport to 2.5

#3320 AAP-44093 edits and some stray typos (#3319)
  downstream/modules/platform/proc-aap-create-aap-object.adoc
  downstream/modules/platform/proc-create-secret-key-secret.adoc
  downstream/modules/platform/proc-operator-deploy-redis.adoc
  downstream/modules/platform/proc-operator-upgrade.adoc
Labels: 2.5, AAP operator

#3324 2.4 Add attribute for Installer (#3321)
  downstream/attributes/attributes.adoc
Labels: Attributes, 2.4

#3323 2.5 Add attribute for Installer (#3321)
  downstream/attributes/attributes.adoc
Labels: Attributes, 2.5

#3326 Backport PR #3325 from main to AAP 2.5
  downstream/modules/platform/ref-system-requirements.adoc
Labels: 2.5, Backported to 2.5

#3328 AAP-41334: Updates content syncing instructions
  downstream/assemblies/hub/assembly-synclists.adoc
  downstream/modules/hub/con-rh-certified-synclist.adoc
  downstream/modules/hub/proc-create-synclist.adoc
Labels: Automation Hub, 2.5

#3331 Fixing extra note in note
  downstream/modules/platform/proc-operator-deploy-redis.adoc
Labels: documentation, 2.5, AAP operator

#3333 Updating Azure deployment diagrams
  images/aap-on-azure-private-deployment.png
  images/aap-on-azure-public-deployment.png
Labels: documentation, AAP on clouds, AAP on Azure

#3336 bp to 2.5: AAP-41334: Updates content syncing instructions (#3328)
  downstream/assemblies/hub/assembly-synclists.adoc
  downstream/modules/hub/con-rh-certified-synclist.adoc
  downstream/modules/hub/proc-create-synclist.adoc
Labels: Automation Hub, 2.5

#3338 Editing controller job output section
  downstream/modules/platform/ref-controller-performance-troubleshooting.adoc
Labels: documentation, Controller, 2.5

#3341 Editing controller job output section (#3338)
  downstream/modules/platform/ref-controller-performance-troubleshooting.adoc
Labels: documentation, 2.5, Backported to 2.5

#3342 Update Adding execution nodes in Containerized installation
  downstream/modules/platform/ref-adding-execution-nodes.adoc
  downstream/modules/platform/ref-receptor-inventory-variables.adoc
Labels: 2.5, Needs backport to 2.5

#3343 2.5 Update Adding execution nodes in Containerized installation (#3342)
  downstream/modules/platform/ref-adding-execution-nodes.adoc
  downstream/modules/platform/ref-receptor-inventory-variables.adoc
Labels: 2.5, Backported to 2.5

#3344 Updating API references in controller API guide
  downstream/assemblies/platform/assembly-controller-api-search.adoc
  downstream/assemblies/platform/assembly-controller-api-sorting.adoc
  downstream/modules/platform/proc-controller-api-browsing-api.adoc
  downstream/modules/platform/proc-controller-api-sorting.adoc
  downstream/modules/platform/proc-controller-api-using-pagination.adoc
Labels: Controller, 2.5, Needs backport to 2.5

#3256 Update the gateway inventory file vars
  downstream/modules/platform/ref-eda-controller-variables.adoc
  downstream/modules/platform/ref-gateway-variables.adoc
  downstream/modules/platform/ref-general-inventory-variables.adoc
  downstream/modules/platform/ref-hub-variables.adoc
Labels: Technical review complete, 2.5, Needs backport to 2.5

#3346 2.5 Update the gateway inventory file vars (#3256)
  downstream/modules/platform/ref-eda-controller-variables.adoc
  downstream/modules/platform/ref-gateway-variables.adoc
  downstream/modules/platform/ref-general-inventory-variables.adoc
  downstream/modules/platform/ref-hub-variables.adoc
Labels: 2.5, Backported to 2.5

#3322 Update chapter on metric-utility
  downstream/assemblies/platform/assembly-ag-controller-backup-and-restore.adoc
  downstream/assemblies/platform/assembly-metrics-utility.adoc
  downstream/modules/platform/proc-configure-a-config-map.adoc
  downstream/modules/platform/proc-configuring-the-metrics-utility.adoc
  downstream/modules/platform/proc-deploy-controller.adoc
  downstream/modules/platform/proc-modifying-the-run-schedule.adoc
  downstream/modules/platform/ref-ccsp.adoc
  downstream/modules/platform/ref-configuring-metrics-utility.adoc
  downstream/modules/platform/ref-controller-cluster-instance-behavior.adoc
  downstream/modules/platform/ref-fetching-a-monthly-report.adoc
  downstream/modules/platform/ref-renewal-guidance.adoc
  downstream/modules/platform/ref-report-types.adoc
  downstream/modules/platform/ref-select-a-date-range.adoc
  downstream/modules/platform/ref-show-ephemeral-use.adoc
  downstream/modules/platform/ref-storage-invocation.adoc
  downstream/modules/platform/ref-supported-storage.adoc
Labels: Controller, 2.5, Needs backport to 2.5

#3350 Backport PR #3349 from main to AAP 2.5 branch.
  downstream/modules/platform/ref-eda-controller-variables.adoc
  downstream/modules/platform/ref-gateway-variables.adoc
Labels: 2.5, Backported to 2.5

#3351 AAP-44016 - removed case-sensitive statement
  downstream/modules/platform/con-gw-authenticator-map-triggers.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#3352 AAP-43404-rn: Added release notes blurb and other minor updates
  lightspeed/modules/proc_view-logs.adoc
  lightspeed/titles/lightspeed-release-notes/master.adoc
  lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-20march2025.adoc
  lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-28april2025.adoc
Labels: Ready for review, Technical review complete, Lightspeed

#3353 [Backport] AAP-44016 - removed case-sensitive statement (#3351)
  downstream/modules/platform/con-gw-authenticator-map-triggers.adoc
Labels: Ready for review, 2.5

#3355 Removing section not applicable to 2.5 docs
  downstream/assemblies/platform/assembly-configure-aap-operator.adoc
Labels: 2.5, AAP operator, Needs backport to 2.5

#3310 Update general inventory file vars appendix
  downstream/assemblies/platform/assembly-appendix-inventory-file-vars.adoc
  downstream/modules/platform/ref-controller-variables.adoc
  downstream/modules/platform/ref-general-inventory-variables.adoc
  downstream/modules/platform/ref-redis-inventory-variables.adoc
Labels: Technical review complete, 2.5, Needs backport to 2.5

#3358 AAP-43858 AAP-43859 Fix YAML syntax in RHDH operator install
  downstream/modules/devtools/proc-rhdh-operator-add-sidecar-container.adoc
  downstream/modules/devtools/proc-rhdh-uninstall-ocp-operator-sidecar-container.adoc
Labels: Needs backport to 2.4, 2.4, 2.5, Needs backport to 2.5

#3357 2.5 Update general inventory file vars appendix (#3310)
  downstream/assemblies/platform/assembly-appendix-inventory-file-vars.adoc
  downstream/modules/platform/ref-controller-variables.adoc
  downstream/modules/platform/ref-general-inventory-variables.adoc
  downstream/modules/platform/ref-redis-inventory-variables.adoc
Labels: 2.5, Backported to 2.5

#3359 2.5 AAP-43858 AAP-43859 Fix YAML syntax in RHDH operator install (#3358)
  downstream/modules/devtools/proc-rhdh-operator-add-sidecar-container.adoc
  downstream/modules/devtools/proc-rhdh-uninstall-ocp-operator-sidecar-container.adoc
Labels: 2.5

#3360 2.4 AAP-43858 AAP-43859 Fix YAML syntax in RHDH operator install (#3358)
  downstream/modules/devtools/proc-rhdh-operator-add-sidecar-container.adoc
  downstream/modules/devtools/proc-rhdh-uninstall-ocp-operator-sidecar-container.adoc
Labels: 2.4

#3361 Adding content from RHEM upstream to chapter 7 (#3340)
  downstream/assemblies/platform/assembly-edge-manager-manage-apps.adoc
  downstream/modules/platform/ref-edge-manager-specify-apps-inline.adoc
Labels: documentation, 2.5, Backported to 2.5

#3362 Adding `rollout policies` to RHEM doc (#3334)
  downstream/assemblies/platform/assembly-edge-manager-device-fleets.adoc
  downstream/modules/platform/con-edge-manager-device-selection-strat.adoc
  downstream/modules/platform/con-edge-manager-device-targeting.adoc
  downstream/modules/platform/con-edge-manager-limit-device.adoc
  downstream/modules/platform/con-edge-manager-rollout-device-selection.adoc
  downstream/modules/platform/con-edge-manager-rollout-disruption.adoc
  downstream/modules/platform/proc-edge-manager-add-devices-cli.adoc
  downstream/modules/platform/proc-edge-manager-add-devices-ui.adoc
  downstream/modules/platform/ref-edge-manager-disruption-parameters.adoc
  downstream/modules/platform/ref-edge-manager-success-threshold.adoc
Labels: documentation, 2.5, Backported to 2.5

#3366 AAP-44580 edits
  stories/topics/con-saas-deployment-self-service.adoc
Labels: documentation, AAP on clouds, SaaS on AWS

#3368 Add web UI steps to RHEM doc
  downstream/assemblies/platform/assembly-edge-manager-manage-devices.adoc
  downstream/modules/platform/proc-edge-manager-access-devices-web-ui.adoc
  downstream/modules/platform/proc-edge-manager-view-device-inventory-cli.adoc
  downstream/modules/platform/proc-edge-manager-view-device-inventory-ui.adoc
  downstream/modules/platform/proc-edge-manager-view-device-labels-ui.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#3364 Update Templates with new information
  downstream/assemblies/platform/assembly-ug-controller-job-templates.adoc
  downstream/assemblies/platform/assembly-ug-controller-workflow-job-templates.adoc
  downstream/images/delete-button.png
  downstream/modules/platform/con-controller-view-completed-jobs.adoc
  downstream/modules/platform/proc-controller-copy-a-job-template.adoc
  downstream/modules/platform/proc-controller-copy-workflow-job-template.adoc
  downstream/modules/platform/proc-controller-create-job-template.adoc
  downstream/modules/platform/proc-controller-create-workflow-template.adoc
  downstream/modules/platform/proc-controller-delete-job-template.adoc
  downstream/modules/platform/proc-controller-launch-job-template.adoc
Labels: documentation, Controller, 2.5, Delay backport, Needs backport to 2.5
