Repository ansible/aap-docs, pull requests merged in 2025-06, with the labels that each got.

#3597 [Backport] AAP-45614 - Doc changes to reflect change to Mapping UI tab updates (#3594)
  downstream/assemblies/platform/assembly-gw-configure-authentication.adoc
  downstream/images/am-apple-team-map-example.png
  downstream/images/am-do-not-escalate-privileges.png
  downstream/images/am-escalate-privileges.png
  downstream/images/am-mapping-order.png
  downstream/images/am-org-mapping-full-annotation.png
  downstream/images/am-org-mapping.png
  downstream/modules/platform/con-gw-create-authentication.adoc
  downstream/modules/platform/proc-controller-github-enterprise-org-settings.adoc
  downstream/modules/platform/proc-controller-github-enterprise-settings.adoc
  downstream/modules/platform/proc-controller-github-enterprise-team-settings.adoc
  downstream/modules/platform/proc-controller-github-organization-settings.adoc
  downstream/modules/platform/proc-controller-github-settings.adoc
  downstream/modules/platform/proc-controller-github-team-settings.adoc
  downstream/modules/platform/proc-controller-google-oauth2-settings.adoc
  downstream/modules/platform/proc-controller-set-up-LDAP.adoc
  downstream/modules/platform/proc-controller-set-up-SAML.adoc
  downstream/modules/platform/proc-controller-set-up-azure.adoc
  downstream/modules/platform/proc-controller-set-up-generic-oidc.adoc
  downstream/modules/platform/proc-controller-set-up-radius.adoc
  downstream/modules/platform/proc-controller-set-up-tacacs+.adoc
  downstream/modules/platform/proc-gw-adjust-mapping-order.adoc
  downstream/modules/platform/proc-gw-allow-mapping.adoc
  downstream/modules/platform/proc-gw-config-keycloak-settings.adoc
  downstream/modules/platform/proc-gw-configure-auth-details.adoc
  downstream/modules/platform/proc-gw-define-rules-triggers.adoc
  downstream/modules/platform/proc-gw-local-authentication.adoc
  downstream/modules/platform/proc-gw-role-mapping.adoc
  downstream/modules/platform/proc-gw-select-auth-type.adoc
  downstream/modules/platform/proc-gw-superuser-mapping.adoc
  downstream/modules/platform/ref-controller-organization-mapping.adoc
  downstream/modules/platform/ref-controller-team-mapping.adoc
  downstream/snippets/snip-gw-mapping-next-steps.adoc
  downstream/titles/central-auth/master.adoc
Labels: Ready for review, 2.5

#3598 AAP-45517: AAP-45517: Corrected the version no. in upgrade doc
  downstream/modules/platform/con-aap-upgrade-planning.adoc
  downstream/modules/platform/proc-upgrade-controller-hub-eda-unified-ui.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#3604 Fixing OCP links (#3603)
  downstream/modules/platform/con-operator-csrf-management.adoc
  downstream/modules/platform/con-operator-custom-resources.adoc
  downstream/modules/platform/con-operator-upgrade-considerations.adoc
Labels: 2.5

#3608 AAP-47171 Update link to RHDH docs
  downstream/assemblies/devtools/assembly-rhdh-telemetry-capturing.adoc
Labels: Needs backport to 2.4, 2.5, Needs backport to 2.5

#3610 2.4 AAP-47171 Update link to RHDH docs (#3608)
  downstream/assemblies/devtools/assembly-rhdh-telemetry-capturing.adoc
Labels: 2.4

#3609 2.5 AAP-47171 Update link to RHDH docs (#3608)
  downstream/assemblies/devtools/assembly-rhdh-telemetry-capturing.adoc
Labels: 2.5

#3611 Add VMware-ESXi to inventory plugin types. (#3588)
  downstream/assemblies/platform/assembly-controller-inventories.adoc
  downstream/assemblies/platform/assembly-controller-inventory-templates.adoc
  downstream/modules/platform/proc-controller-add-source.adoc
  downstream/modules/platform/proc-controller-inv-source-vm-esxi.adoc
  downstream/modules/platform/ref-controller-inventory-plugins.adoc
  downstream/modules/platform/ref-controller-inventory-sources.adoc
Labels: documentation, Controller, 2.5, Backported to 2.5

#3613 Refactor execution environments doc
  downstream/aap-common/apache-2.0-license.adoc
  downstream/aap-common/gplv3-license-text.adoc
  downstream/aap-common/open-source-apache.adoc
  downstream/aap-common/open-source-gnu3.adoc
  downstream/assemblies/builder/assembly-common-ee-scenarios.adoc
  downstream/assemblies/builder/assembly-intro-to-builder.adoc
  downstream/assemblies/builder/assembly-populate-container-registry.adoc
  downstream/assemblies/builder/assembly-publishing-exec-env.adoc
  downstream/assemblies/builder/assembly-using-builder.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/builder/con-about-ee.adoc
  downstream/modules/builder/con-additional-build-files.adoc
  downstream/modules/builder/con-additional-custom-build-steps.adoc
  downstream/modules/builder/con-building-definition-file.adoc
  downstream/modules/builder/con-container_file.adoc
  downstream/modules/builder/con-definition-dependencies.adoc
  downstream/modules/builder/con-definition-file-breakdown.adoc
  downstream/modules/builder/con-ee-precedence.adoc
  downstream/modules/builder/con-optional-build-command-arguments.adoc
  downstream/modules/builder/con-python-dependencies.adoc
  downstream/modules/builder/con-system-dependencies.adoc
  downstream/modules/builder/con-why-builder.adoc
  downstream/modules/builder/con-why-ee.adoc
  downstream/modules/builder/proc-creating-containerfile-no-image.adoc
  downstream/modules/builder/proc-customize-ee-image.adoc
  downstream/modules/builder/proc-executing-build.adoc
  downstream/modules/builder/proc-installing-builder.adoc
  downstream/modules/builder/ref-build-args-base-image.adoc
  downstream/modules/builder/ref-definition-file-images.adoc
  downstream/modules/builder/ref-example-yaml-image-files.adoc
  downstream/modules/builder/ref-scenario-update-hub-ca-cert.adoc
  downstream/modules/builder/ref-scenario-using-authentication-ee.adoc
  downstream/modules/platform/con-building-an-execution-environment-in-a-disconnected-environment.adoc
  downstream/modules/platform/proc-creating-the-custom-execution-environment-definition.adoc
  downstream/modules/platform/proc-update-ee-image-locations.adoc
  downstream/modules/platform/proc-uploading-the-custom-execution-environment-to-the-private-hub.adoc
  downstream/titles/builder/master.adoc
Labels: documentation, Draft, Ready for technical review, 2.5, Needs backport to 2.5

#3616 Refactor execution environments doc (#3613)
  downstream/aap-common/apache-2.0-license.adoc
  downstream/aap-common/gplv3-license-text.adoc
  downstream/aap-common/open-source-apache.adoc
  downstream/aap-common/open-source-gnu3.adoc
  downstream/assemblies/builder/assembly-common-ee-scenarios.adoc
  downstream/assemblies/builder/assembly-intro-to-builder.adoc
  downstream/assemblies/builder/assembly-populate-container-registry.adoc
  downstream/assemblies/builder/assembly-publishing-exec-env.adoc
  downstream/assemblies/builder/assembly-using-builder.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/builder/con-about-ee.adoc
  downstream/modules/builder/con-additional-build-files.adoc
  downstream/modules/builder/con-additional-custom-build-steps.adoc
  downstream/modules/builder/con-building-definition-file.adoc
  downstream/modules/builder/con-container_file.adoc
  downstream/modules/builder/con-definition-dependencies.adoc
  downstream/modules/builder/con-definition-file-breakdown.adoc
  downstream/modules/builder/con-ee-precedence.adoc
  downstream/modules/builder/con-optional-build-command-arguments.adoc
  downstream/modules/builder/con-python-dependencies.adoc
  downstream/modules/builder/con-system-dependencies.adoc
  downstream/modules/builder/con-why-builder.adoc
  downstream/modules/builder/con-why-ee.adoc
  downstream/modules/builder/proc-creating-containerfile-no-image.adoc
  downstream/modules/builder/proc-customize-ee-image.adoc
  downstream/modules/builder/proc-executing-build.adoc
  downstream/modules/builder/proc-installing-builder.adoc
  downstream/modules/builder/ref-build-args-base-image.adoc
  downstream/modules/builder/ref-definition-file-images.adoc
  downstream/modules/builder/ref-example-yaml-image-files.adoc
  downstream/modules/builder/ref-scenario-update-hub-ca-cert.adoc
  downstream/modules/builder/ref-scenario-using-authentication-ee.adoc
  downstream/modules/platform/con-building-an-execution-environment-in-a-disconnected-environment.adoc
  downstream/modules/platform/proc-creating-the-custom-execution-environment-definition.adoc
  downstream/modules/platform/proc-update-ee-image-locations.adoc
  downstream/modules/platform/proc-uploading-the-custom-execution-environment-to-the-private-hub.adoc
  downstream/titles/builder/master.adoc
Labels: documentation, 2.5, Backported to 2.5

#3593 AAP-39301: Adds domain of interest info to getting started with AAP guide
  downstream/assemblies/platform/assembly-gs-auto-dev.adoc
  downstream/assemblies/platform/assembly-gs-key-functionality.adoc
  downstream/modules/platform/proc-set-domain-of-interest.adoc
Labels: 2.5, Needs backport to 2.5

#3620 Correct file for pre-migration
  downstream/assemblies/platform/assembly-deprovisioning-mesh.adoc
  downstream/modules/platform/proc-deprovision-group.adoc
  downstream/modules/platform/proc-deprovision-isolated-groups.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#3628 AAP-47163 Examples fixed for DITA
  stories/topics/con-azure-infrastructure-usage.adoc
  stories/topics/proc-azure-accessing-aap.adoc
Labels: AAP on clouds, AAP on Azure

#3629 Correct file for pre-migration (#3620)
  downstream/assemblies/platform/assembly-deprovisioning-mesh.adoc
  downstream/modules/platform/proc-deprovision-group.adoc
  downstream/modules/platform/proc-deprovision-isolated-groups.adoc
Labels: documentation, 2.5, Backported to 2.5

#3630 Premigration tasks for Automation mesh (#3619)
  downstream/assemblies/platform/assembly-deprovisioning-mesh.adoc
  downstream/modules/platform/proc-deprovision-isolated-nodes.adoc
  downstream/modules/platform/proc-deprovisioning-mesh-nodes.adoc
Labels: 2.5, Backported to 2.5

#3632 Correct admonition format (#3631)
  downstream/modules/platform/proc-deprovision-isolated-groups.adoc
  downstream/modules/platform/proc-deprovision-isolated-nodes.adoc
Labels: Automation Mesh, 2.5, Backported to 2.5

#3635 Update hub_shared_data_path to add req format
  downstream/modules/platform/proc-cont-aap-hub-storage.adoc
  downstream/modules/platform/ref-hub-variables.adoc
Labels: 2.5, Needs backport to 2.5

#3633 Reformat example blocks
  downstream/modules/platform/proc-deprovision-group.adoc
  downstream/modules/platform/proc-deprovisioning-mesh-nodes.adoc
Labels: Automation Mesh, 2.5, Needs backport to 2.5

#3636 2.5 Update hub_shared_data_path to add req format (#3635)
  downstream/modules/platform/proc-cont-aap-hub-storage.adoc
  downstream/modules/platform/ref-hub-variables.adoc
Labels: 2.5, Backported to 2.5

#3634 AAP on Azure DITA prep
  stories/assembly-azure-connecting-to-aap.adoc
  stories/assembly-azure-deploy.adoc
  stories/assembly-azure-hub-spoke-peering.adoc
  stories/assembly-azure-install-prerequisites.adoc
  stories/assembly-azure-install.adoc
  stories/assembly-azure-support.adoc
  stories/topics/con-azure-pricing.adoc
  stories/topics/proc-azure-cancel-deployment.adoc
  stories/topics/proc-azure-configure-ad-sso.adoc
  stories/topics/proc-azure-create-registered-app.adoc
  stories/topics/proc-azure-create-service-principal.adoc
  stories/topics/proc-azure-find-cluster-cidr.adoc
  stories/topics/proc-azure-generating-secrets.adoc
  stories/topics/proc-azure-hub-spoke-peering.adoc
  stories/topics/proc-azure-monitor-deployment-engine.adoc
  stories/topics/proc-azure-nw-access-details.adoc
  stories/topics/proc-azure-nw-peering-aap-subnet.adoc
  stories/topics/proc-azure-outbound-route.adoc
  stories/topics/proc-azure-peer-vwan-hub-to-aap.adoc
  stories/topics/proc-azure-provisioning-aap.adoc
  stories/topics/proc-azure-route-to-azure.adoc
  stories/topics/proc-azure-route-to-vnets.adoc
  stories/topics/proc-azure-update-route-tables.adoc
  stories/topics/ref-azure-deploy-engine-interface.adoc
  stories/topics/ref-azure-license-association.adoc
  stories/topics/ref-azure-maintain-your-service-principles.adoc
  stories/topics/ref-azure-nw-private-deploy-az-hosted-vm.adoc
  stories/topics/ref-azure-nw-private-deploy-vpn.adoc
  stories/topics/ref-azure-nw-private-deploy.adoc
  stories/topics/ref-azure-nw-public-deploy.adoc
  stories/topics/ref-azure-resource-providers.adoc
  stories/topics/ref-azure-resource-quotas.adoc
Labels: documentation, AAP on Azure

#3637 Pre-migration updates
  downstream/archive/archived-modules/platform/proc-cont-aap-hub-storage.adoc
  downstream/archive/archived-modules/platform/proc-setup-postgresql-ext-database-containerized.adoc
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/assemblies/platform/assembly-configure-hub-storage.adoc
  downstream/assemblies/platform/assembly-setup-postgresql-ext-database.adoc
  downstream/modules/platform/proc-add-eda-safe-plugin-var.adoc
  downstream/modules/platform/proc-configure-ext-db-mtls.adoc
  downstream/modules/platform/proc-configure-hub-azure-storage.adoc
  downstream/modules/platform/proc-configure-hub-nfs-storage.adoc
  downstream/modules/platform/proc-configure-hub-s3-storage.adoc
  downstream/modules/platform/proc-enabling-automation-hub-collection-and-container-signing.adoc
  downstream/modules/platform/proc-hs-eda-setup.adoc
  downstream/modules/platform/proc-setup-ext-db-with-admin-creds.adoc
  downstream/modules/platform/proc-setup-ext-db-without-admin-creds.adoc
  downstream/modules/topologies/ref-ocp-a-env-a.adoc
Labels: 2.5, Needs backport to 2.5

#3638 AAP-47475 Archive unused titles
  downstream/archive/archived-titles/controller/controller-getting-started/docinfo.xml
  downstream/archive/archived-titles/controller/controller-getting-started/master.adoc
  downstream/archive/archived-titles/eda/eda-getting-started-guide/docinfo.xml
  downstream/archive/archived-titles/eda/eda-getting-started-guide/master.adoc
  downstream/archive/archived-titles/hub/getting-started/docinfo.xml
  downstream/archive/archived-titles/hub/getting-started/master.adoc
  downstream/titles/controller/controller-getting-started/aap-common
  downstream/titles/controller/controller-getting-started/attributes
  downstream/titles/controller/controller-getting-started/images
  downstream/titles/controller/controller-getting-started/platform
  downstream/titles/eda/eda-getting-started-guide/aap-common
  downstream/titles/eda/eda-getting-started-guide/attributes
  downstream/titles/eda/eda-getting-started-guide/eda
  downstream/titles/eda/eda-getting-started-guide/images
  downstream/titles/hub/getting-started/aap-common
  downstream/titles/hub/getting-started/attributes
  downstream/titles/hub/getting-started/hub
Labels: Archive

#3624 Editing controller files for DITA
  downstream/assemblies/platform/assembly-ag-instance-and-container-groups.adoc
  downstream/assemblies/platform/assembly-controller-inventories.adoc
  downstream/assemblies/platform/assembly-controller-pac.adoc
  downstream/assemblies/platform/assembly-metrics-utility.adoc
  downstream/assemblies/platform/assembly-ug-controller-job-templates.adoc
  downstream/modules/platform/con-configuring-the-metrics-utility.adoc
  downstream/modules/platform/con-controller-container-groups.adoc
  downstream/modules/platform/proc-configure-a-config-map.adoc
  downstream/modules/platform/proc-configure-pac-enforcement.adoc
  downstream/modules/platform/proc-controller-add-source.adoc
  downstream/modules/platform/proc-controller-config-notifications-source.adoc
  downstream/modules/platform/proc-controller-create-container-group.adoc
  downstream/modules/platform/proc-controller-create-service-account.adoc
  downstream/modules/platform/proc-controller-enable-provision-callbacks.adoc
  downstream/modules/platform/proc-controller-inv-source-terraform.adoc
  downstream/modules/platform/proc-controller-metrics-utility-ocp.adoc
  downstream/modules/platform/proc-controller-metrics-utility-rhel.adoc
  downstream/modules/platform/proc-controller-modify-run-schedule-OCP.adoc
  downstream/modules/platform/proc-controller-obtaining-subscriptions-manifest.adoc
  downstream/modules/platform/proc-controller-use-REST-manually.adoc
  downstream/modules/platform/proc-define-mesh-node-types.adoc
  downstream/modules/platform/proc-deploy-controller.adoc
  downstream/modules/platform/proc-modifying-the-run-schedule.adoc
  downstream/modules/platform/proc-pac-add-policy-to-inventory.adoc
  downstream/modules/platform/proc-pac-add-policy-to-org.adoc
  downstream/modules/platform/proc-pac-add-policy-to-template.adoc
Labels: documentation, Controller, 2.5, Needs backport to 2.5

#3644 Reformat example blocks (#3633)
  downstream/modules/platform/proc-deprovision-group.adoc
  downstream/modules/platform/proc-deprovisioning-mesh-nodes.adoc
Labels: Automation Mesh, 2.5, Backported to 2.5

#3640 AAP-47075 Archive getting started content
  downstream/archive/archived-assemblies/builder/assembly-definition-file-breakdown.adoc
  downstream/archive/archived-assemblies/eda/assembly-about-event-driven-ansible-automation.adoc
  downstream/archive/archived-assemblies/eda/assembly-ansible-rulebooks.adoc
  downstream/archive/archived-assemblies/eda/assembly-installation-eda-controller.adoc
  downstream/archive/archived-assemblies/eda/assembly-using-eda-controller.adoc
  downstream/archive/archived-assemblies/hub/assembly-configure-hub-primary.adoc
  downstream/archive/archived-assemblies/hub/assembly-hub-create-api-token.adoc
  downstream/archive/archived-assemblies/hub/assembly-hub-overview.adoc
  downstream/archive/archived-assemblies/hub/assembly-uploading-content-hub.adoc
  downstream/archive/archived-assemblies/hub/assembly-user-access.adoc
  downstream/archive/archived-assemblies/hub/assembly-view-only-access.adoc
  downstream/archive/archived-assemblies/platform/assembly-controller-dashboard.adoc
  downstream/archive/archived-assemblies/platform/assembly-controller-job-templates.adoc
  downstream/archive/archived-assemblies/platform/assembly-controller-managing-subscriptions.adoc
  downstream/archive/archived-modules/eda/con-about-event-driven-ansible.adoc
  downstream/archive/archived-modules/eda/con-decision-environments.adoc
  downstream/archive/archived-modules/eda/con-rulebook-actions.adoc
  downstream/archive/archived-modules/eda/ref-deploy-eda-controller-with-aap-operator-on-ocp.adoc
  downstream/archive/archived-modules/eda/ref-eda-controller-tasks.adoc
  downstream/archive/archived-modules/eda/ref-installing-eda-controller-on-aap.adoc
  downstream/archive/archived-modules/hub/con-enable-view-only.adoc
  downstream/archive/archived-modules/hub/con-user-access.adoc
  downstream/archive/archived-modules/hub/proc-add-user-to-group.adoc
  downstream/archive/archived-modules/hub/proc-assigning-permissions.adoc
  downstream/archive/archived-modules/hub/proc-configure-automation-hub-server-cli.adoc
  downstream/archive/archived-modules/hub/proc-configure-automation-hub-server-gui.adoc
  downstream/archive/archived-modules/hub/proc-create-super-users.adoc
  downstream/archive/archived-modules/hub/proc-create-users.adoc
  downstream/archive/archived-modules/hub/proc-delete-user.adoc
  downstream/archive/archived-modules/hub/proc-upload-collection.adoc
  downstream/archive/archived-modules/hub/ref-permissions.adoc
  downstream/archive/archived-modules/platform/con-controller-host-metric-utilities.adoc
  downstream/archive/archived-modules/platform/proc-controller-adding-subscription-manually.adoc
  downstream/archive/archived-modules/platform/proc-controller-api-endpoint-functions.adoc
  downstream/archive/archived-modules/platform/proc-controller-attaching-subscriptions.adoc
  downstream/archive/archived-modules/platform/proc-controller-importing-subscriptions.adoc
  downstream/archive/archived-modules/platform/proc-controller-obtaining-subscriptions-manifest.adoc
  downstream/archive/archived-modules/platform/proc-controller-obtaining-subscriptions.adoc
  downstream/archive/archived-modules/platform/proc-controller-run-job-template.adoc
  downstream/archive/archived-modules/platform/proc-controller-viewing-dashboard.adoc
  downstream/archive/archived-modules/platform/proc-gw-configure-auth-details.adoc
  downstream/archive/archived-modules/platform/proc-gw-review-auth-settings.adoc
Labels: Archive

#3645 Fixing saas procs to adhere to DITA
  stories/topics/proc-saas-set-up-private.adoc
  stories/topics/proc-saas-set-up-public.adoc
Labels: documentation, Ansible on AWS, SaaS on AWS

#3657 AAP-47457 Analytics Data Dictionary (#3656)
  downstream/assemblies/analytics/assembly-data-dictionary.adoc
  downstream/titles/analytics/master.adoc
Labels: Analytics, 2.5

#3666 2.5 Update using custom TLS certs (#3648)
  downstream/archive/archived-modules/platform/ref-using-custom-tls-certificates.adoc
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/assemblies/platform/assembly-using-custom-tls-certificates.adoc
  downstream/modules/platform/con-certs-per-service-considerations.adoc
  downstream/modules/platform/con-installer-generated-certs.adoc
  downstream/modules/platform/con-receptor-cert-considerations.adoc
  downstream/modules/platform/proc-provide-custom-ca-cert.adoc
  downstream/modules/platform/proc-provide-custom-tls-certs-per-service.adoc
  downstream/modules/platform/proc-use-custom-ca-certs.adoc
Labels: 2.5, Backported to 2.5

#3659 Adding domains of interest module to controller
  downstream/assemblies/platform/assembly-ug-controller-job-templates.adoc
  downstream/modules/platform/proc-set-domain-of-interest.adoc
  downstream/modules/platform/ref-controller-intro-job-template.adoc
Labels: documentation, Controller, 2.5, Needs backport to 2.5

#3669 Update automation mesh for DITA migration (#3667)
  downstream/assemblies/platform/assembly-mesh-design-patterns.adoc
  downstream/assemblies/platform/assembly-planning-mesh.adoc
  downstream/assemblies/platform/assembly-setting-up-automation-mesh.adoc
  downstream/modules/platform/con-automation-mesh-node-types.adoc
  downstream/modules/platform/con-install-mesh.adoc
  downstream/modules/platform/ref-mesh-minimum-resilient-config.adoc
Labels: Automation Mesh, 2.5, Backported to 2.5

#3672 Backport PR #3642 from main to AAP 2.5 repo.
  downstream/modules/platform/con-aap-upgrades.adoc
Labels: 2.5, Backported to 2.5

#3671 Add link to ocp-b.env-a CR
  downstream/modules/topologies/ref-ocp-b-env-a.adoc
Labels: 2.5, Needs backport to 2.5

#3673 2.5 Add link to ocp-b.env-a CR (#3671)
  downstream/modules/topologies/ref-ocp-b-env-a.adoc
Labels: 2.5, Backported to 2.5

#3674 Update Operator Mesh for DITA migration
  downstream/assemblies/platform/assembly-automation-mesh-operator-aap.adoc
  downstream/modules/platform/proc-define-mesh-node-types.adoc
  downstream/modules/platform/proc-operator-mesh-upgrading-receptors.adoc
  downstream/modules/platform/proc-pulling-the-secret.adoc
  downstream/modules/platform/proc-run-jobs-on-execution-nodes.adoc
Labels: Automation Mesh, 2.5, Needs backport to 2.5

#3660 AAP-45856-A Updated metrics-utility content (2)
  downstream/modules/platform/proc-configure-a-config-map.adoc
  downstream/modules/platform/proc-controller-metrics-utility-ocp.adoc
  downstream/modules/platform/proc-controller-metrics-utility-rhel.adoc
  downstream/modules/platform/proc-deploy-controller.adoc
  downstream/modules/platform/proc-modifying-the-run-schedule.adoc
  downstream/modules/platform/ref-fetching-a-monthly-report.adoc
Labels: Ready for review, Technical review complete, 2.5

#3675 Update Operator Mesh for DITA migration (#3674)
  downstream/assemblies/platform/assembly-automation-mesh-operator-aap.adoc
  downstream/modules/platform/proc-define-mesh-node-types.adoc
  downstream/modules/platform/proc-operator-mesh-upgrading-receptors.adoc
  downstream/modules/platform/proc-pulling-the-secret.adoc
  downstream/modules/platform/proc-run-jobs-on-execution-nodes.adoc
Labels: Automation Mesh, 2.5, Backported to 2.5

#3677 AAP-45856-A Updated metrics-utility content (2) (#3660)
  downstream/modules/platform/proc-configure-a-config-map.adoc
  downstream/modules/platform/proc-controller-metrics-utility-ocp.adoc
  downstream/modules/platform/proc-controller-metrics-utility-rhel.adoc
  downstream/modules/platform/proc-deploy-controller.adoc
  downstream/modules/platform/proc-modifying-the-run-schedule.adoc
  downstream/modules/platform/ref-fetching-a-monthly-report.adoc
Labels: Ready for review, 2.5

#3679 Correct link in Peers section
  downstream/modules/platform/con-automation-mesh-node-types.adoc
Labels: Automation Mesh, 2.5, Needs backport to 2.5

#3680 AAP-47158 DITA pre-migration tasks: Ansible Inside
  .gitignore
  ansible-inside/stories/assembly-ansible-inside-install-rhsm.adoc
  ansible-inside/stories/assembly-ansible-inside-install.adoc
  ansible-inside/stories/assembly-reporting-file-location.adoc
  ansible-inside/stories/assembly-reporting-intro.adoc
  ansible-inside/stories/assembly-reporting-return.adoc
  ansible-inside/topics/proc-ansible-inside-install-rhsm-all.adoc
  ansible-inside/topics/proc-ansible-inside-install-rhsm-individual.adoc
  ansible-inside/topics/proc-ansible-inside-install-rhsm.adoc
Labels: Ansible Inside, Migration

#3681 Correct link in Peers section (#3679)
  downstream/modules/platform/con-automation-mesh-node-types.adoc
Labels: Automation Mesh, 2.5, Backported to 2.5

#3682 AAP-43213-update: Corrected an attribute
  lightspeed/modules/con_overview-lightspeed-onpremise.adoc
  lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-29may2025.adoc
Labels: Lightspeed

#3683 AAP-47754: updates attribute for policy settings
  downstream/attributes/attributes.adoc
Labels: Attributes, 2.5

#3689 Correct broken link in builder doc
  downstream/modules/builder/proc-installing-builder.adoc
Labels: 2.5, Needs backport to 2.5

#3690 Correct broken link in builder doc (#3689)
  downstream/modules/builder/proc-installing-builder.adoc
Labels: 2.5, Backported to 2.5

#3664 AAP-47553: PaC docs add reminder to configure global and resource settings
  downstream/assemblies/platform/assembly-controller-pac.adoc
  downstream/modules/platform/proc-configure-pac-enforcement.adoc
  downstream/modules/platform/proc-configure-pac-settings.adoc
  downstream/modules/platform/proc-controller-find-subscription.adoc
Labels: Controller, 2.5, Needs backport to 2.5

#3692 Backport-2.5-3687 (AAP-47655) Reorganized xrefs to reflect current chapter arrangement
  downstream/assemblies/eda/assembly-eda-user-guide-overview.adoc
Labels: documentation, Ready for review, 2.5

#3665 AAP-40717 EDA logging enhancements in the EDA user guide
  downstream/assemblies/eda/assembly-eda-rulebook-troubleshooting.adoc
Labels: documentation, Ready for technical review, Not ready for peer review, 2.5

#3699 DITA migration changes for Builder doc (#3691)
  downstream/assemblies/builder/assembly-common-ee-scenarios.adoc
  downstream/assemblies/builder/assembly-using-builder.adoc
  downstream/modules/builder/con-additional-custom-build-steps.adoc
  downstream/modules/builder/con-build-an-ee-with-env-variables.adoc
  downstream/modules/builder/con-build-ee-with-env-vars-for-galaxy.adoc
  downstream/modules/builder/con-building-definition-file.adoc
  downstream/modules/builder/con-galaxy-dependencies.adoc
  downstream/modules/builder/con-optional-build-command-arguments.adoc
  downstream/modules/builder/con-python-dependencies.adoc
  downstream/modules/builder/con-system-dependencies.adoc
  downstream/modules/builder/proc-customize-ee-image.adoc
  downstream/modules/builder/proc-executing-build.adoc
  downstream/modules/builder/proc-installing-builder.adoc
  downstream/modules/builder/ref-example-yaml-image-files.adoc
  downstream/modules/platform/con-building-an-execution-environment-in-a-disconnected-environment.adoc
  downstream/modules/platform/proc-creating-the-custom-execution-environment-definition.adoc
  downstream/modules/platform/proc-update-ee-image-locations.adoc
Labels: 2.5, Backported to 2.5

#3703 Updating controller API overview (#3670)
  downstream/modules/platform/proc-controller-api-session-auth.adoc
  downstream/titles/controller/controller-api-overview/master.adoc
Labels: documentation, 2.5, Backported to 2.5

#3707 AAP-46319: Added licensing topics to RPM install guide
  downstream/titles/aap-installation-guide/master.adoc
Labels: 2.5, Needs backport to 2.5

#3708 Add clarification to database for topologies
  downstream/modules/topologies/ref-rpm-a-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-b.adoc
Labels: 2.5, Needs backport to 2.5

#3709 2.5 Add clarification to database for topologies (#3708)
  downstream/modules/topologies/ref-rpm-a-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-b.adoc
Labels: 2.5, Backported to 2.5

#3685 DITA migration changes for Hardening guide
  downstream/assemblies/aap-hardening/assembly-hardening-aap.adoc
  downstream/assemblies/aap-hardening/assembly-intro-to-aap-hardening.adoc
  downstream/modules/aap-hardening/con-automation-use-secrets.adoc
  downstream/modules/aap-hardening/con-dns-ntp-service-planning.adoc
  downstream/modules/aap-hardening/con-network-firewall-services-planning.adoc
  downstream/modules/aap-hardening/con-platform-components.adoc
  downstream/modules/aap-hardening/con-rbac.adoc
  downstream/modules/aap-hardening/proc-configure-centralized-logging.adoc
  downstream/modules/aap-hardening/proc-configure-ldap-logging.adoc
  downstream/modules/aap-hardening/proc-implement-security-control.adoc
  downstream/modules/aap-hardening/proc-implement-security-controller.adoc
  downstream/modules/aap-hardening/proc-implement-security-for-admin.adoc
  downstream/modules/aap-hardening/ref-aap-operational-secrets.adoc
  downstream/modules/aap-hardening/ref-configure-centralized-logging.adoc
  downstream/modules/aap-hardening/ref-dns.adoc
  downstream/modules/aap-hardening/ref-infrastructure-as-code.adoc
  downstream/modules/aap-hardening/ref-sensitive-variables-install-inventory.adoc
  downstream/modules/platform/proc-controller-set-up-logging.adoc
  downstream/titles/aap-hardening/master.pdf
Labels: 2.5, Needs backport to 2.5

#3710 DITA migration changes for Hardening guide (#3685)
  downstream/assemblies/aap-hardening/assembly-hardening-aap.adoc
  downstream/assemblies/aap-hardening/assembly-intro-to-aap-hardening.adoc
  downstream/modules/aap-hardening/con-automation-use-secrets.adoc
  downstream/modules/aap-hardening/con-dns-ntp-service-planning.adoc
  downstream/modules/aap-hardening/con-network-firewall-services-planning.adoc
  downstream/modules/aap-hardening/con-platform-components.adoc
  downstream/modules/aap-hardening/con-rbac.adoc
  downstream/modules/aap-hardening/proc-configure-centralized-logging.adoc
  downstream/modules/aap-hardening/proc-configure-ldap-logging.adoc
  downstream/modules/aap-hardening/proc-implement-security-control.adoc
  downstream/modules/aap-hardening/proc-implement-security-controller.adoc
  downstream/modules/aap-hardening/proc-implement-security-for-admin.adoc
  downstream/modules/aap-hardening/ref-aap-operational-secrets.adoc
  downstream/modules/aap-hardening/ref-configure-centralized-logging.adoc
  downstream/modules/aap-hardening/ref-dns.adoc
  downstream/modules/aap-hardening/ref-infrastructure-as-code.adoc
  downstream/modules/aap-hardening/ref-sensitive-variables-install-inventory.adoc
  downstream/modules/platform/proc-controller-set-up-logging.adoc
  downstream/titles/aap-hardening/master.pdf
Labels: 2.5, Backported to 2.5, Migration

#3712 2.5 Update default backup dir location (#3711)
  downstream/modules/platform/proc-backup-aap-container.adoc
  downstream/modules/platform/proc-restore-aap-container.adoc
Labels: 2.5, Backported to 2.5

#3713 Backport PR #3706 from main branch to AAP 2.5 branch
  downstream/titles/aap-installation-guide/master.adoc
Labels: 2.5, Backported to 2.5

#3702 Updating CLI command for Edge manager
  downstream/modules/platform/con-edge-manager-build-bootc.adoc
  downstream/modules/platform/proc-edge-manager-install-CLI.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#3717 DITA migration updates: Ch 16
  downstream/assemblies/platform/assembly-controller-hosts.adoc
  downstream/modules/platform/proc-controller-create-host.adoc
  downstream/modules/platform/proc-controller-view-host.adoc
Labels: documentation, Controller, 2.5, Needs backport to 2.5, Migration

#3647 OCP Dita pre-migration fixes
  downstream/assemblies/platform/assembly-aap-migration.adoc
  downstream/assemblies/platform/assembly-aap-post-upgrade.adoc
  downstream/assemblies/platform/assembly-installing-aap-operator-cli.adoc
  downstream/modules/platform/con-aap-migrate-SAML-users.adoc
  downstream/modules/platform/con-aap-migrate-normal-users.adoc
  downstream/modules/platform/con-post-migration-cleanup.adoc
  downstream/modules/platform/proc-aap-migrate-admin-users.adoc
  downstream/modules/platform/proc-cli-get-controller-address.adoc
  downstream/modules/platform/proc-cli-get-controller-pwd-decode.adoc
  downstream/modules/platform/proc-cli-get-controller-pwd.adoc
  downstream/modules/platform/proc-operator-create-controller-credential.adoc
  downstream/modules/platform/proc-post-migration-cleanup.adoc
  downstream/modules/platform/proc-post-migration-delete-instance.adoc
  downstream/modules/platform/proc-post-migration-unlink-db.adoc
  downstream/modules/platform/ref-aap-considerations-for-migrate-admin-users.adoc
  downstream/modules/platform/ref-aap-considerations-for-migrate-normal-users.adoc
Labels: AAP operator

#3720 OCP Dita pre-migration fixes (#3647)
  downstream/assemblies/platform/assembly-aap-migration.adoc
  downstream/assemblies/platform/assembly-aap-post-upgrade.adoc
  downstream/assemblies/platform/assembly-installing-aap-operator-cli.adoc
  downstream/modules/platform/con-aap-migrate-SAML-users.adoc
  downstream/modules/platform/con-aap-migrate-normal-users.adoc
  downstream/modules/platform/con-post-migration-cleanup.adoc
  downstream/modules/platform/proc-aap-migrate-admin-users.adoc
  downstream/modules/platform/proc-cli-get-controller-address.adoc
  downstream/modules/platform/proc-cli-get-controller-pwd-decode.adoc
  downstream/modules/platform/proc-cli-get-controller-pwd.adoc
  downstream/modules/platform/proc-operator-create-controller-credential.adoc
  downstream/modules/platform/proc-post-migration-cleanup.adoc
  downstream/modules/platform/proc-post-migration-delete-instance.adoc
  downstream/modules/platform/proc-post-migration-unlink-db.adoc
  downstream/modules/platform/ref-aap-considerations-for-migrate-admin-users.adoc
  downstream/modules/platform/ref-aap-considerations-for-migrate-normal-users.adoc
Labels: 2.5

#3724 AAP-47158 Ansible inside - update registry proc for migration
  ansible-inside/stories/assembly-ansible-inside-install-registry.adoc
  ansible-inside/stories/assembly-ansible-inside-install.adoc
  ansible-inside/topics/proc-ansible-inside-install-registry.adoc
  ansible-inside/topics/proc-ansible-inside-pull-ee-registry.adoc
  ansible-inside/topics/ref-ansible-inside-rhel8-ees.adoc
  ansible-inside/topics/ref-ansible-inside-rhel9-ees.adoc
Labels: Ansible Inside, Migration

#3726 Add controller and database descriptions (#3725)
  downstream/assemblies/platform/assembly-aap-platform-components.adoc
  downstream/modules/platform/con-about-controller.adoc
  downstream/modules/platform/con-about-postgres.adoc
Labels: 2.5, Backported to 2.5

#3727 Add missing sections
  downstream/assemblies/platform/assembly-aap-platform-components.adoc
  downstream/modules/platform/con-about-controller.adoc
  downstream/modules/platform/con-about-postgres.adoc
Labels: 2.4

#3731 Correct broken link in Containerized installation
  downstream/modules/platform/ref-cont-aap-system-requirements.adoc
Labels: 2.5, Needs backport to 2.5

#3734 DITA migration changes: CUG Ch 19
  downstream/assemblies/platform/assembly-controller-instances.adoc
  downstream/modules/platform/proc-define-mesh-node-types.adoc
Labels: Controller, 2.5, Needs backport to 2.5, Migration

#3737 DITA migration changes: CUG Ch 19 (#3734)
  downstream/assemblies/platform/assembly-controller-instances.adoc
  downstream/modules/platform/proc-define-mesh-node-types.adoc
Labels: 2.5, Backported to 2.5

#3733 AAP-46216 Modular and migration compliance for Using automation decisions, chapter 3
  downstream/assemblies/eda/assembly-eda-credential-types.adoc
  downstream/modules/eda/con-credential-types-injector-config.adoc
  downstream/modules/eda/con-credential-types-input-config.adoc
  downstream/modules/eda/con-custom-credential-types.adoc
  downstream/modules/eda/proc-eda-set-up-credential-types.adoc
Labels: documentation, Ready for review, 2.5, Needs backport to 2.5

#3738 bp to 2.5: AAP-48159 Modular structure edits for AEM migration
  downstream/assemblies/platform/assembly-gs-auto-dev.adoc
  downstream/assemblies/platform/assembly-gs-auto-op.adoc
  downstream/modules/hub/proc-create-api-token-pah.adoc
  downstream/modules/hub/proc-create-api-token.adoc
  downstream/modules/hub/proc-create-requirements-file.adoc
  downstream/modules/platform/con-gs-about-builder.adoc
  downstream/modules/platform/proc-gs-add-ee-to-job-template.adoc
  downstream/modules/platform/proc-gs-use-base-execution-env.adoc
  downstream/modules/platform/ref-gs-about-container-registries.adoc
Labels: 2.5, Migration

#3739 DITA migration changes for CUG Ch 20
  downstream/assemblies/platform/assembly-controller-execution-environments.adoc
  downstream/modules/platform/proc-controller-ee-mount-execution-node.adoc
  downstream/modules/platform/proc-controller-troubleshoot-ee-mount.adoc
  downstream/modules/platform/proc-controller-use-an-exec-env.adoc
  downstream/modules/platform/ref-controller-build-exec-envs.adoc
  downstream/modules/platform/ref-controller-building-exec-env.adoc
  downstream/modules/platform/ref-controller-install-builder.adoc
Labels: documentation, Controller, 2.5, Needs backport to 2.5, Migration

#3741 Update Tested deployment models
  downstream/modules/topologies/ref-cont-a-env-a.adoc
  downstream/modules/topologies/ref-cont-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-b.adoc
  downstream/modules/topologies/ref-rpm-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-b.adoc
  downstream/snippets/cont-tested-system-config.adoc
  downstream/snippets/cont-tested-vm-config.adoc
  downstream/snippets/rpm-env-a-tested-system-config.adoc
  downstream/snippets/rpm-env-b-tested-system-config.adoc
  downstream/snippets/rpm-tested-vm-config.adoc
Labels: 2.5, Needs backport to 2.5

#3742 2.5 Update Tested deployment models (#3741)
  downstream/modules/topologies/ref-cont-a-env-a.adoc
  downstream/modules/topologies/ref-cont-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-b.adoc
  downstream/modules/topologies/ref-rpm-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-b.adoc
  downstream/snippets/cont-tested-system-config.adoc
  downstream/snippets/cont-tested-vm-config.adoc
  downstream/snippets/rpm-env-a-tested-system-config.adoc
  downstream/snippets/rpm-env-b-tested-system-config.adoc
  downstream/snippets/rpm-tested-vm-config.adoc
Labels: 2.5, Backported to 2.5

#3743 Editing controller files for DITA (#3728)
  downstream/assemblies/platform/assembly-controller-inventories.adoc
  downstream/modules/platform/proc-controller-add-groups-to-groups.adoc
  downstream/modules/platform/proc-controller-add-groups.adoc
  downstream/modules/platform/proc-controller-add-hosts.adoc
  downstream/modules/platform/proc-controller-add-source.adoc
  downstream/modules/platform/proc-controller-adding-inv-permissions.adoc
  downstream/modules/platform/proc-controller-adding-new-inventory.adoc
  downstream/modules/platform/proc-controller-amazon-ec2.adoc
  downstream/modules/platform/proc-controller-azure-resource-manager.adoc
  downstream/modules/platform/proc-controller-config-notifications-source.adoc
  downstream/modules/platform/proc-controller-inv-source-aap.adoc
  downstream/modules/platform/proc-controller-inv-source-gce.adoc
  downstream/modules/platform/proc-controller-inv-source-insights.adoc
  downstream/modules/platform/proc-controller-inv-source-open-shift-virt.adoc
  downstream/modules/platform/proc-controller-inv-source-openstack.adoc
  downstream/modules/platform/proc-controller-inv-source-rh-virt.adoc
  downstream/modules/platform/proc-controller-inv-source-satellite.adoc
  downstream/modules/platform/proc-controller-inv-source-terraform.adoc
  downstream/modules/platform/proc-controller-inv-source-vm-esxi.adoc
  downstream/modules/platform/proc-controller-inv-source-vm-vcenter.adoc
  downstream/modules/platform/proc-controller-remove-inv-permissions.adoc
  downstream/modules/platform/proc-controller-run-ad-hoc-commands.adoc
  downstream/modules/platform/proc-controller-sourced-from-project.adoc
  downstream/modules/platform/ref-controller-constructed-inventories.adoc
  downstream/modules/platform/ref-controller-export-old-scripts.adoc
  downstream/modules/platform/ref-controller-filter-environ-variables.adoc
  downstream/modules/platform/ref-controller-filter-hosts-cpu-type.adoc
  downstream/modules/platform/ref-controller-group-name-vars-filtering.adoc
  downstream/modules/platform/ref-controller-inv-ansible-facts.adoc
  downstream/modules/platform/ref-controller-inv-debugging-tips.adoc
  downstream/modules/platform/ref-controller-inv-nested-groups.adoc
  downstream/modules/platform/ref-controller-inventory-plugins.adoc
  downstream/modules/platform/ref-controller-inventory-sources.adoc
  downstream/modules/platform/ref-controller-smart-host-filter.adoc
  downstream/modules/platform/ref-controller-smart-inventories.adoc
  downstream/modules/platform/ref-controller-view-completed-jobs.adoc
  downstream/modules/platform/ref-controller-view-edit-inv-groups.adoc
Labels: documentation, Controller, 2.5, Backported to 2.5

#3744 Update inventory file vars
  downstream/modules/platform/ref-controller-variables.adoc
  downstream/modules/platform/ref-general-inventory-variables.adoc
  downstream/modules/platform/ref-redis-inventory-variables.adoc
Labels: 2.5, Needs backport to 2.5

#3748 2.5 Update ansible-core version reqs for containerized AAP (#3676)
  downstream/attributes/attributes.adoc
  downstream/modules/platform/ref-system-requirements.adoc
  downstream/modules/topologies/ref-ocp-a-env-a.adoc
  downstream/modules/topologies/ref-ocp-b-env-a.adoc
  downstream/snippets/cont-tested-system-config.adoc
  downstream/snippets/rpm-env-a-tested-system-config.adoc
  downstream/snippets/rpm-env-b-tested-system-config.adoc
Labels: 2.5, Backported to 2.5
