Repository ansible/aap-docs, pull requests merged in 2025-01, with the labels that each got.

#2736 Minor correction to container group procedure
  downstream/modules/platform/proc-controller-create-container-group.adoc
Labels: Controller, 2.5, Needs backport to 2.5

#2737 Minor correction to container group procedure (#2736)
  downstream/modules/platform/proc-controller-create-container-group.adoc
Labels: 2.5, Backported to 2.5

#2738 Removing cleanup string from controller docs
  downstream/assemblies/platform/assembly-controller-management-jobs.adoc
Labels: documentation, Needs backport to 2.4, Controller, 2.5, Needs backport to 2.5

#2739 Removing cleanup string from controller docs (#2738)
  downstream/assemblies/platform/assembly-controller-management-jobs.adoc
Labels: documentation, Controller, 2.5, Backported to 2.5

#2740 Removing cleanup string from controller docs (#2738)
  downstream/assemblies/platform/assembly-controller-management-jobs.adoc
Labels: documentation, Backported to 2.4, Controller, 2.4

#2741 Update RHEL requirements for containerized installation
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
Labels: 2.5, Needs backport to 2.5

#2742 2.5 Update RHEL requirements for containerized installation (#2741)
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
Labels: 2.5, Backported to 2.5

#2745 2.5 AAP-35970: AAP-35970: Added IBM Z arch test support in RPM topologies…
  downstream/modules/topologies/ref-rpm-a-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-b.adoc
  downstream/modules/topologies/ref-rpm-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-b.adoc
Labels: 2.5, Backported to 2.5

#2749 Updating cancellation information
  stories/topics/con-saas-deployment-self-service.adoc
Labels: AAP on clouds, SaaS on AWS

#2730 Added notice that OAuth and LDAP data migration is not supported in the platform ui
  downstream/assemblies/platform/assembly-controller-applications.adoc
  downstream/modules/platform/proc-controller-set-up-LDAP.adoc
Labels: Ready for technical review, 2.5, Needs backport to 2.5

#2751 [Backport] Added notice that OAuth and LDAP data migration is not supported in the platform ui (#2730)
  downstream/assemblies/platform/assembly-controller-applications.adoc
  downstream/modules/platform/proc-controller-set-up-LDAP.adoc
Labels: Ready for review, 2.5

#2752 AAP-38268 - corrected typo
  downstream/modules/platform/proc-settings-gw-security-options.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#2754 2.5 Update eda config procedures in Containerized installation (#2753)
  downstream/modules/platform/con-hs-eda-controller.adoc
  downstream/modules/platform/proc-add-eda-safe-plugin-var.adoc
  downstream/modules/platform/proc-hs-eda-setup.adoc
Labels: 2.5, Backported to 2.5

#2755 [Backport] AAP-38268 - corrected typo (#2752)
  downstream/modules/platform/proc-settings-gw-security-options.adoc
Labels: 2.5

#2756 Convert inventory file codeblocks into snippets for reuse
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/topologies/ref-cont-a-env-a.adoc
  downstream/modules/topologies/ref-cont-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-b.adoc
  downstream/modules/topologies/ref-rpm-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-b.adoc
  downstream/snippets/inventory-cont-a-env-a.adoc
  downstream/snippets/inventory-cont-b-env-a.adoc
  downstream/snippets/inventory-rpm-a-env-a.adoc
  downstream/snippets/inventory-rpm-a-env-b.adoc
  downstream/snippets/inventory-rpm-b-env-a.adoc
  downstream/snippets/inventory-rpm-b-env-b.adoc
Labels: 2.5, Needs backport to 2.5

#2757 2.5 Convert inventory file codeblocks into snippets for reuse (#2756)
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/topologies/ref-cont-a-env-a.adoc
  downstream/modules/topologies/ref-cont-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-b.adoc
  downstream/modules/topologies/ref-rpm-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-b.adoc
  downstream/snippets/inventory-cont-a-env-a.adoc
  downstream/snippets/inventory-cont-b-env-a.adoc
  downstream/snippets/inventory-rpm-a-env-a.adoc
  downstream/snippets/inventory-rpm-a-env-b.adoc
  downstream/snippets/inventory-rpm-b-env-a.adoc
  downstream/snippets/inventory-rpm-b-env-b.adoc
Labels: 2.5, Backported to 2.5

#2759 AAP-38561 - Corrected superuser mapping content
  downstream/modules/platform/proc-gw-role-mapping.adoc
  downstream/modules/platform/proc-gw-superuser-mapping.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#2760 [Backport] AAP-28561 - Corrected superuser mapping content (#2759)
  downstream/modules/platform/proc-gw-role-mapping.adoc
  downstream/modules/platform/proc-gw-superuser-mapping.adoc
Labels: Ready for review, 2.5

#2748 Changes to mesh ingress information
  downstream/modules/platform/proc-connecting-nodes-through-mesh-ingress.adoc
Labels: Ready for technical review, 2.5, Needs backport to 2.5

#2763 Changes to mesh ingress information (#2748)
  downstream/modules/platform/proc-connecting-nodes-through-mesh-ingress.adoc
Labels: 2.5, Backported to 2.5

#2764 Update redis colocation info for Containerized enterprise topology
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/platform/ref-general-inventory-variables.adoc
  downstream/modules/topologies/ref-cont-b-env-a.adoc
  downstream/snippets/redis-colocation-containerized.adoc
Labels: 2.5, Needs backport to 2.5

#2762 Removed postgres message
  downstream/modules/platform/proc-setup-postgresql-ext-database.adoc
Labels: Needs backport to 2.4, 2.4, 2.5, Needs backport to 2.5

#2765 2.5 Update redis colocation info for Containerized enterprise topology (#…
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/platform/ref-general-inventory-variables.adoc
  downstream/modules/topologies/ref-cont-b-env-a.adoc
  downstream/snippets/redis-colocation-containerized.adoc
Labels: 2.5, Backported to 2.5

#2766 Removed postgres message (#2762)
  downstream/modules/platform/proc-setup-postgresql-ext-database.adoc
Labels: 2.5, Backported to 2.5

#2767 Adding further info/example for advanced search
  downstream/assemblies/platform/assembly-controller-search.adoc
  downstream/images/Advanced-search-error.png
Labels: documentation, Controller, 2.4

#2772 Correct note formatting
  downstream/modules/platform/proc-connecting-nodes-through-mesh-ingress.adoc
Labels: 2.5, Needs backport to 2.5

#2773 Correct note formatting (#2772)
  downstream/modules/platform/proc-connecting-nodes-through-mesh-ingress.adoc
Labels: 2.5, Backported to 2.5

#2743 Adding Transparent SAML Login proc in AAP 2.5
  downstream/assemblies/platform/assembly-gw-config-authentication-type.adoc
  downstream/modules/platform/proc-controller-configure-transparent-SAML.adoc
  downstream/modules/platform/proc-controller-set-up-SAML.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#2774 Adding Transparent SAML Login proc in AAP 2.5 (#2743)
  downstream/assemblies/platform/assembly-gw-config-authentication-type.adoc
  downstream/modules/platform/proc-controller-configure-transparent-SAML.adoc
  downstream/modules/platform/proc-controller-set-up-SAML.adoc
Labels: 2.5, Backported to 2.5

#2777 Update external db config for containerized installation
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/assemblies/platform/assembly-appendix-inventory-file-vars.adoc
  downstream/modules/platform/proc-setup-postgresql-ext-database.adoc
  downstream/modules/platform/ref-controller-variables.adoc
  downstream/modules/platform/ref-eda-controller-variables.adoc
  downstream/modules/platform/ref-gateway-variables.adoc
  downstream/modules/platform/ref-hub-variables.adoc
Labels: 2.5, Needs backport to 2.5

#2778 2.5 Update external db config for containerized installation (#2777)
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/assemblies/platform/assembly-appendix-inventory-file-vars.adoc
  downstream/modules/platform/proc-setup-postgresql-ext-database.adoc
  downstream/modules/platform/ref-controller-variables.adoc
  downstream/modules/platform/ref-eda-controller-variables.adoc
  downstream/modules/platform/ref-gateway-variables.adoc
  downstream/modules/platform/ref-hub-variables.adoc
Labels: 2.5, Backported to 2.5

#2781 AAP-36580 added a note that explicitly states 6 VMs are required
  downstream/modules/platform/con-gw-clustered-redis.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#2782 [Backport] AAP-36580 added a note that explicitly states 6 VMs are required (#2781)
  downstream/modules/platform/con-gw-clustered-redis.adoc
Labels: Ready for review, 2.5

#2784 2.5 Comment out procedure until feature is released
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
Labels: 2.5

#2783 AAP-38563: Corrected the broken AAP guide URLs
  lightspeed/modules/con_overview-lightspeed-onpremise.adoc
  lightspeed/modules/proc_monitor-onpremise-deployment.adoc
  lightspeed/modules/proc_multi-task-recs.adoc
  lightspeed/modules/proc_single-task-recs.adoc
Labels: Ready for review, Lightspeed

#2786 Add redis_cluster_ip to inventory vars appendix
  downstream/modules/platform/ref-general-inventory-variables.adoc
Labels: 2.5, Needs backport to 2.5

#2787 2.5 Add redis_cluster_ip to inventory vars appendix (#2786)
  downstream/modules/platform/ref-general-inventory-variables.adoc
Labels: 2.5, Backported to 2.5

#2775 Correcting pull the secret section
  downstream/modules/platform/proc-pulling-the-secret.adoc
Labels: 2.5, Backported to 2.5

#2788 Correcting pull the secret section (#2775)
  downstream/modules/platform/proc-pulling-the-secret.adoc
Labels: 2.5, Backported to 2.5

#2791 Replace instances of platform gateway with attributes
  downstream/assemblies/platform/assembly-HA-redis.adoc
  downstream/assemblies/platform/assembly-configure-aap-operator.adoc
  downstream/assemblies/platform/assembly-gw-settings.adoc
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
  downstream/modules/platform/con-aap-upgrade-planning.adoc
  downstream/modules/platform/con-about-platform-gateway.adoc
  downstream/modules/platform/con-controller-api-basic-auth.adoc
  downstream/modules/platform/con-controller-api-oauth2-token.adoc
  downstream/modules/platform/con-controller-custom-logos.adoc
  downstream/modules/platform/con-controller-settings.adoc
  downstream/modules/platform/con-gw-activity-stream.adoc
  downstream/modules/platform/con-gw-cache-queue.adoc
  downstream/modules/platform/con-gw-clustered-redis.adoc
  downstream/modules/platform/con-ocp-supported-install.adoc
  downstream/modules/platform/con-resource-operator-overview.adoc
  downstream/modules/platform/proc-access-hub-operator-ui.adoc
  downstream/modules/platform/proc-add-controller-access-token.adoc
  downstream/modules/platform/proc-configuring-controller-ldap-security.adoc
  downstream/modules/platform/proc-custom-logos-images.adoc
  downstream/modules/platform/proc-operator-aap-faq.adoc
  downstream/modules/platform/proc-operator-access-aap.adoc
  downstream/modules/platform/proc-operator-deploy-central-config.adoc
  downstream/modules/platform/proc-operator-link-components.adoc
  downstream/modules/platform/proc-operator-upgrade.adoc
  downstream/modules/platform/proc-settings-gw-additional-options.adoc
  downstream/modules/platform/proc-settings-gw-custom-login.adoc
  downstream/modules/platform/proc-settings-gw-password-security.adoc
  downstream/modules/platform/proc-settings-gw-security-options.adoc
  downstream/modules/platform/proc-settings-gw-session-options.adoc
  downstream/modules/platform/proc-settings-platform-gateway.adoc
  downstream/modules/platform/ref-eda-controller-variables.adoc
  downstream/modules/platform/ref-gateway-controller-ext-db.adoc
  downstream/modules/platform/ref-gateway-controller-hub-eda-ext-db.adoc
  downstream/modules/platform/ref-gateway-controller-hub-ext-db.adoc
  downstream/modules/platform/ref-gateway-system-requirements.adoc
  downstream/modules/platform/ref-guidelines-hosts-groups.adoc
  downstream/modules/platform/ref-system-requirements.adoc
  downstream/modules/platform/ref-using-custom-tls-certificates.adoc
  downstream/snippets/snip-gateway-component-description.adoc
  downstream/titles/release-notes/topics/aap-25-changed-features.adoc
  downstream/titles/release-notes/topics/aap-25-deprecated-features.adoc
  downstream/titles/release-notes/topics/aap-25-removed-features.adoc
  downstream/titles/release-notes/topics/aap-25.adoc
  downstream/titles/release-notes/topics/platform-intro.adoc
Labels: 2.5, Needs backport to 2.5

#2792 2.5 Replace instances of platform gateway with attributes (#2791)
  downstream/assemblies/platform/assembly-HA-redis.adoc
  downstream/assemblies/platform/assembly-configure-aap-operator.adoc
  downstream/assemblies/platform/assembly-gw-settings.adoc
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
  downstream/modules/platform/con-aap-upgrade-planning.adoc
  downstream/modules/platform/con-about-platform-gateway.adoc
  downstream/modules/platform/con-controller-api-basic-auth.adoc
  downstream/modules/platform/con-controller-api-oauth2-token.adoc
  downstream/modules/platform/con-controller-custom-logos.adoc
  downstream/modules/platform/con-controller-settings.adoc
  downstream/modules/platform/con-gw-activity-stream.adoc
  downstream/modules/platform/con-gw-cache-queue.adoc
  downstream/modules/platform/con-gw-clustered-redis.adoc
  downstream/modules/platform/con-ocp-supported-install.adoc
  downstream/modules/platform/con-resource-operator-overview.adoc
  downstream/modules/platform/proc-access-hub-operator-ui.adoc
  downstream/modules/platform/proc-add-controller-access-token.adoc
  downstream/modules/platform/proc-configuring-controller-ldap-security.adoc
  downstream/modules/platform/proc-custom-logos-images.adoc
  downstream/modules/platform/proc-operator-aap-faq.adoc
  downstream/modules/platform/proc-operator-access-aap.adoc
  downstream/modules/platform/proc-operator-deploy-central-config.adoc
  downstream/modules/platform/proc-operator-link-components.adoc
  downstream/modules/platform/proc-operator-upgrade.adoc
  downstream/modules/platform/proc-settings-gw-additional-options.adoc
  downstream/modules/platform/proc-settings-gw-custom-login.adoc
  downstream/modules/platform/proc-settings-gw-password-security.adoc
  downstream/modules/platform/proc-settings-gw-security-options.adoc
  downstream/modules/platform/proc-settings-gw-session-options.adoc
  downstream/modules/platform/proc-settings-platform-gateway.adoc
  downstream/modules/platform/ref-eda-controller-variables.adoc
  downstream/modules/platform/ref-gateway-controller-ext-db.adoc
  downstream/modules/platform/ref-gateway-controller-hub-eda-ext-db.adoc
  downstream/modules/platform/ref-gateway-controller-hub-ext-db.adoc
  downstream/modules/platform/ref-gateway-system-requirements.adoc
  downstream/modules/platform/ref-guidelines-hosts-groups.adoc
  downstream/modules/platform/ref-system-requirements.adoc
  downstream/modules/platform/ref-using-custom-tls-certificates.adoc
  downstream/snippets/snip-gateway-component-description.adoc
  downstream/titles/release-notes/topics/aap-25-changed-features.adoc
  downstream/titles/release-notes/topics/aap-25-deprecated-features.adoc
  downstream/titles/release-notes/topics/aap-25-removed-features.adoc
  downstream/titles/release-notes/topics/aap-25.adoc
  downstream/titles/release-notes/topics/platform-intro.adoc
Labels: 2.5, Backported to 2.5

#2793 AAP-38369: Updated a crossreference to point to downstream docs
  downstream/modules/platform/ref-postgresql-requirements.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#2794 AAP-38369: Updated a crossreference to point to downstream docs (#2793)
  downstream/modules/platform/ref-postgresql-requirements.adoc
Labels: Ready for review, 2.5, Backported to 2.5

#2776 Updating workflow visualizer proc 2.5
  downstream/images/ug-wf-add-template.png
  downstream/images/ug-wf-approval-node.png
  downstream/images/ug-wf-create-sibling-node.png
  downstream/images/ug-wf-dropdown-list.png
  downstream/images/ug-wf-editor-convergent-node-all.png
  downstream/modules/platform/proc-controller-build-workflow.adoc
  downstream/modules/platform/proc-controller-building-nodes-scenarios.adoc
  downstream/modules/platform/proc-controller-edit-nodes.adoc
  downstream/modules/platform/ref-controller-approval-nodes.adoc
Labels: documentation, Controller, 2.5, Needs backport to 2.5

#2797 Updating workflow visualizer proc 2.5 (#2776)
  downstream/images/ug-wf-add-template.png
  downstream/images/ug-wf-approval-node.png
  downstream/images/ug-wf-create-sibling-node.png
  downstream/images/ug-wf-dropdown-list.png
  downstream/images/ug-wf-editor-convergent-node-all.png
  downstream/modules/platform/proc-controller-build-workflow.adoc
  downstream/modules/platform/proc-controller-building-nodes-scenarios.adoc
  downstream/modules/platform/proc-controller-edit-nodes.adoc
  downstream/modules/platform/ref-controller-approval-nodes.adoc
Labels: documentation, Controller, 2.5, Backported to 2.5

#2798 2.5 Add registry_username and registry_password proc to Containerized ins…
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/platform/proc-set-registry-username-password.adoc
  downstream/modules/platform/ref-general-inventory-variables.adoc
Labels: 2.5, Backported to 2.5

#2799 correcting broken URL
  downstream/modules/platform/ref-general-inventory-variables.adoc
Labels: 2.5, Needs backport to 2.5

#2800 2.5 correcting broken URL (#2799)
  downstream/modules/platform/ref-general-inventory-variables.adoc
Labels: 2.5, Backported to 2.5

#2805 Relnote 2.5.20250122
  downstream/titles/release-notes/async/aap-25-20250122.adoc
Labels: AAP Release notes

#2806 2.5 Relnote 2.5.20250122 (#2805)
  downstream/titles/release-notes/async/aap-25-20250122.adoc
Labels: AAP Release notes, 2.5

#2807 AAP-38856 updated note to specify that colocation limitation is specific to RPM
  downstream/modules/platform/con-gw-clustered-redis.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#2808 AAP-38856 updated note to specify that colocation limitation is specific to RPM (#2807)
  downstream/modules/platform/con-gw-clustered-redis.adoc
Labels: Ready for review, 2.5

#2809 Replaced missing variable
  downstream/modules/platform/ref-hub-variables.adoc
Labels: 2.5, Needs backport to 2.5

#2810 Replaced missing variable (#2809)
  downstream/modules/platform/ref-hub-variables.adoc
Labels: 2.5, Backported to 2.5

#2815 AAP-39144: Added troubleshooting info. For proxy-releted vscode errors
  lightspeed/modules/proc_troubleshooting-vscode.adoc
Labels: Ready for review, Lightspeed

#2822 AAP-31257: corrects typos and attributes in the managing automation content guide
  downstream/modules/hub/proc-adding-containers-remotely-to-the-automation-hub.adoc
  downstream/modules/hub/proc-pushing-container-images-from-your-local.adoc
Labels: Automation Hub, 2.5, Needs backport to 2.5

#2823 backport to 2.5: AAP-31257: corrects typos and attributes in the managing automation content guide (#2822)
  downstream/modules/hub/proc-adding-containers-remotely-to-the-automation-hub.adoc
  downstream/modules/hub/proc-pushing-container-images-from-your-local.adoc
Labels: Automation Hub, 2.5

#2824 Update automation content signing content for Containerized installation
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/platform/ref-configuring-inventory-file.adoc
  downstream/modules/platform/ref-enabling-automation-hub-collection-and-container-signing.adoc
  downstream/modules/platform/ref-hub-variables.adoc
Labels: 2.5, Needs backport to 2.5

#2825 2.5 Update automation content signing content for Containerized installat…
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/platform/ref-configuring-inventory-file.adoc
  downstream/modules/platform/ref-enabling-automation-hub-collection-and-container-signing.adoc
  downstream/modules/platform/ref-hub-variables.adoc
Labels: 2.5, Backported to 2.5

#2819 AAP-38758 Removed the unsupported Mutual TLS entry
  downstream/modules/eda/con-event-streams.adoc
Labels: documentation, Ready for review, Technical review complete, 2.5, Needs backport to 2.5

#2826 Backport -2.5-2819 (AAP-38758) Removed the unsupported Mutual TLS entry
  downstream/modules/eda/con-event-streams.adoc
Labels: documentation, Ready for review, Needs backport to 2.5

#2830 Removed information regarding role mapping from superuser mapping
  downstream/modules/platform/proc-gw-superuser-mapping.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#2832 2.4 AAP-39409 Add directory for SVG files (#2827)
  downstream/images/svg/extensions.svg
Labels: 2.4

#2831 2.5 AAP-39409 Add directory for SVG files (#2827)
  downstream/images/svg/extensions.svg
Labels: 2.5

#2834 Lightspeed: AAP-39409 Add directory for SVG files
  lightspeed/images/extensions.svg
Labels: Lightspeed

#2836 removed information regarding role mapping from superuser mapping (#2830)
  downstream/modules/platform/proc-gw-superuser-mapping.adoc
Labels: Ready for review, 2.5

#2837 2.5 Uncomment proc-setup-postgresql-ext-database now that the functionali…
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
Labels: 2.5

#2770 AAP-30609 updated script for installing with internet access
  downstream/modules/platform/proc-installing-with-internet.adoc
Labels: Ready for technical review, 2.5

#2838 AAP-30609 updated script for installing with internet access (#2770)
  downstream/modules/platform/proc-installing-with-internet.adoc
Labels: Ready for review, 2.5

#2835 Add svg images to directory.
  downstream/images/svg/OCP-A_Env-A-R.svg
  downstream/images/svg/OCP-B_Env-A-R.svg
  downstream/images/svg/extensions.svg
  downstream/images/svg/st_CONT_B_Env_A-R.svg
  downstream/images/svg/st_Cont-A_Env-A-R.svg
  downstream/images/svg/st_Network-R.svg
  downstream/images/svg/st_Proxy.svg
  downstream/images/svg/st_RPM_A_Env_A-R.svg
  downstream/images/svg/st_RPM_A_Env_B-R.svg
  downstream/images/svg/st_RPM_B_Env_A-R.svg
  downstream/images/svg/st_RPM_B_Env_B.svg
Labels: 2.5, Needs backport to 2.5

#2839 Add svg images to directory. (#2835)
  downstream/images/svg/OCP-A_Env-A-R.svg
  downstream/images/svg/OCP-B_Env-A-R.svg
  downstream/images/svg/extensions.svg
  downstream/images/svg/st_CONT_B_Env_A-R.svg
  downstream/images/svg/st_Cont-A_Env-A-R.svg
  downstream/images/svg/st_Network-R.svg
  downstream/images/svg/st_Proxy.svg
  downstream/images/svg/st_RPM_A_Env_A-R.svg
  downstream/images/svg/st_RPM_A_Env_B-R.svg
  downstream/images/svg/st_RPM_B_Env_A-R.svg
  downstream/images/svg/st_RPM_B_Env_B.svg
Labels: 2.5, Backported to 2.5

#2841 Correct typos, spelling, grammar to improve readability
  downstream/assemblies/troubleshooting-aap/assembly-troubleshoot-controller.adoc
  downstream/modules/platform/con-hs-eda-controller.adoc
  downstream/modules/platform/proc-backup-aap-container.adoc
  downstream/modules/platform/proc-downloading-containerized-aap.adoc
  downstream/modules/platform/proc-hs-eda-setup.adoc
  downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc
  downstream/modules/platform/proc-reinstalling-containerized-aap.adoc
  downstream/modules/platform/proc-uninstalling-containerized-aap.adoc
  downstream/modules/platform/proc-update-aap-container.adoc
  downstream/modules/platform/ref-database-inventory-variables.adoc
  downstream/modules/platform/ref-general-inventory-variables.adoc
  downstream/modules/platform/ref-hub-variables.adoc
  downstream/modules/platform/ref-using-custom-receptor-signing-keys.adoc
  downstream/modules/platform/ref-using-custom-tls-certificates.adoc
  downstream/modules/topologies/ref-ocp-b-env-a.adoc
  downstream/snippets/container-upgrades.adoc
Labels: 2.5, Needs backport to 2.5

#2842 2.5 Correct typos, spelling, grammar to improve readability (#2841)
  downstream/assemblies/troubleshooting-aap/assembly-troubleshoot-controller.adoc
  downstream/modules/platform/con-hs-eda-controller.adoc
  downstream/modules/platform/proc-backup-aap-container.adoc
  downstream/modules/platform/proc-downloading-containerized-aap.adoc
  downstream/modules/platform/proc-hs-eda-setup.adoc
  downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc
  downstream/modules/platform/proc-reinstalling-containerized-aap.adoc
  downstream/modules/platform/proc-uninstalling-containerized-aap.adoc
  downstream/modules/platform/proc-update-aap-container.adoc
  downstream/modules/platform/ref-database-inventory-variables.adoc
  downstream/modules/platform/ref-general-inventory-variables.adoc
  downstream/modules/platform/ref-hub-variables.adoc
  downstream/modules/platform/ref-using-custom-receptor-signing-keys.adoc
  downstream/modules/platform/ref-using-custom-tls-certificates.adoc
  downstream/modules/topologies/ref-ocp-b-env-a.adoc
  downstream/snippets/container-upgrades.adoc
Labels: 2.5, Backported to 2.5

#2840 Update CONT-A to include RAM requirement for bundled install
  downstream/archive/archived-snippets/known-issue-container-content-syncing.adoc
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/platform/ref-configuring-inventory-file.adoc
  downstream/modules/topologies/ref-cont-a-env-a.adoc
Labels: Technical review complete, 2.5, Needs backport to 2.5

#2844 2.5 Update CONT-A to include RAM requirement for bundled install (#2840)
  downstream/archive/archived-snippets/known-issue-container-content-syncing.adoc
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/platform/ref-configuring-inventory-file.adoc
  downstream/modules/topologies/ref-cont-a-env-a.adoc
Labels: 2.5, Backported to 2.5

#2847 AAP-37837: Added repo. selection prerequisite for RPM installation
  downstream/modules/platform/ref-system-requirements.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#2848 Backport pull request #2847 from main to 2.5
  downstream/modules/platform/ref-system-requirements.adoc
Labels: Ready for review, 2.5, Backported to 2.5

#2845 Adding remove_auditors to 2.4 controller user guide
  downstream/modules/platform/ref-controller-organization-mapping.adoc
Labels: documentation, Controller, 2.4

#2849 Adding missing tab info to 2.x version
  stories/topics/proc-azure-provisioning-aap.adoc
Labels: AAP on clouds, AAP on Azure

#2850 Adding flight control files to repo
  downstream/assemblies/flight-control/flight-control
  downstream/titles/flight-control/flight-control-user-guide/aap-common
  downstream/titles/flight-control/flight-control-user-guide/attributes
  downstream/titles/flight-control/flight-control-user-guide/docinfo.xml
  downstream/titles/flight-control/flight-control-user-guide/flight-control
  downstream/titles/flight-control/flight-control-user-guide/images
  downstream/titles/flight-control/flight-control-user-guide/master.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#2852 Adding flight control files to repo (#2850)
  downstream/assemblies/flight-control/flight-control
  downstream/titles/flight-control/flight-control-user-guide/aap-common
  downstream/titles/flight-control/flight-control-user-guide/attributes
  downstream/titles/flight-control/flight-control-user-guide/docinfo.xml
  downstream/titles/flight-control/flight-control-user-guide/flight-control
  downstream/titles/flight-control/flight-control-user-guide/images
  downstream/titles/flight-control/flight-control-user-guide/master.adoc
Labels: documentation, 2.5, Backported to 2.5

#2851 Update receptor inventory file vars in appendix
  downstream/modules/platform/ref-controller-variables.adoc
  downstream/modules/platform/ref-receptor-inventory-variables.adoc
Labels: Technical review complete, 2.5, Needs backport to 2.5

#2854 2.5 Update receptor inventory file vars in appendix (#2851)
  downstream/modules/platform/ref-controller-variables.adoc
  downstream/modules/platform/ref-receptor-inventory-variables.adoc
Labels: 2.5, Backported to 2.5

#2821 AAP-34599: updates procedure for signing EEs
  downstream/modules/hub/proc-adding-an-execution-environment.adoc
  downstream/modules/hub/proc-deploying-your-system-for-container-signing.adoc
Labels: Automation Hub, 2.5, Needs backport to 2.5

#2855 backport to 2.5: AAP-34599: updates procedure for signing EEs (#2821)
  downstream/modules/hub/proc-adding-an-execution-environment.adoc
  downstream/modules/hub/proc-deploying-your-system-for-container-signing.adoc
Labels: Automation Hub, 2.5
