Repository ansible/aap-docs, pull requests merged in 2025-05, with the labels that each got.

#3372 Update tested topology support wording
  downstream/assemblies/topologies/assembly-overview-tested-deployment-models.adoc
  downstream/modules/aap-hardening/ref-architecture.adoc
  downstream/snippets/container-upgrades.adoc
  downstream/titles/release-notes/async/aap-25-3-28-oct.adoc
  downstream/titles/release-notes/topics/aap-25.adoc
Labels: 2.5, Needs backport to 2.5

#3373 2.5 Update tested topology support wording (#3372)
  downstream/assemblies/topologies/assembly-overview-tested-deployment-models.adoc
  downstream/modules/aap-hardening/ref-architecture.adoc
  downstream/snippets/container-upgrades.adoc
  downstream/titles/release-notes/async/aap-25-3-28-oct.adoc
  downstream/titles/release-notes/topics/aap-25.adoc
Labels: 2.5, Backported to 2.5

#1419 fix indents execution environment definition
  downstream/modules/builder/con-building-definition-file.adoc
Labels: 2.5, Needs backport to 2.5

#3374 2.5 fix indents executiion environment definition (#1419)
  downstream/modules/builder/con-building-definition-file.adoc
Labels: 2.5, Backported to 2.5

#1869 fix repo name in README
  README.adoc
Labels: 2.5, Needs backport to 2.5

#3375 2.5 fix repo name (#1869)
  README.adoc
Labels: 2.5, Backported to 2.5

#3377 2.5 fix url (#2686)
  downstream/modules/platform/ref-controller-launch-jobs-with-curl.adoc
Labels: 2.5, Backported to 2.5

#3376 Change copy to duplicate (#3288)
  downstream/assemblies/platform/assembly-controller-credentials.adoc
  downstream/assemblies/platform/assembly-controller-execution-environments.adoc
  downstream/assemblies/platform/assembly-controller-inventories.adoc
  downstream/assemblies/platform/assembly-controller-projects.adoc
  downstream/assemblies/platform/assembly-ug-controller-job-templates.adoc
  downstream/assemblies/platform/assembly-ug-controller-workflow-job-templates.adoc
Labels: 2.5, Backported to 2.5

#3370 AAP-40199 improvements to LDAP configuration content
  downstream/modules/platform/proc-controller-set-up-LDAP.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#3380 [Backport] AAP-40199 improvements to LDAP configuration content (#3370)
  downstream/modules/platform/proc-controller-set-up-LDAP.adoc
Labels: Ready for review, 2.5

#3365 Backport-2.5-3147 (AAP-37305) Document how to copy an existing rulebook activation (#3147)
  downstream/assemblies/eda/assembly-eda-rulebook-activations.adoc
  downstream/modules/eda/proc-eda-copy-rulebook-activation.adoc
Labels: documentation, Technical review complete, Peer review complete, 2.5

#3381 Add compression vars to backup proc for Containerized installation
  downstream/modules/platform/proc-backup-aap-container.adoc
  downstream/modules/platform/ref-controller-variables.adoc
  downstream/modules/platform/ref-database-inventory-variables.adoc
  downstream/modules/platform/ref-eda-controller-variables.adoc
  downstream/modules/platform/ref-gateway-variables.adoc
  downstream/modules/platform/ref-general-inventory-variables.adoc
  downstream/modules/platform/ref-hub-variables.adoc
  downstream/modules/platform/ref-receptor-inventory-variables.adoc
  downstream/modules/platform/ref-redis-inventory-variables.adoc
Labels: 2.5, Needs backport to 2.5

#3383 2.5 Update chapter on metric-utility (#3322)
  downstream/assemblies/platform/assembly-ag-controller-backup-and-restore.adoc
  downstream/assemblies/platform/assembly-metrics-utility.adoc
  downstream/modules/platform/proc-configure-a-config-map.adoc
  downstream/modules/platform/proc-configuring-the-metrics-utility.adoc
  downstream/modules/platform/proc-deploy-controller.adoc
  downstream/modules/platform/proc-modifying-the-run-schedule.adoc
  downstream/modules/platform/ref-ccsp.adoc
  downstream/modules/platform/ref-configuring-metrics-utility.adoc
  downstream/modules/platform/ref-controller-cluster-instance-behavior.adoc
  downstream/modules/platform/ref-fetching-a-monthly-report.adoc
  downstream/modules/platform/ref-renewal-guidance.adoc
  downstream/modules/platform/ref-report-types.adoc
  downstream/modules/platform/ref-select-a-date-range.adoc
  downstream/modules/platform/ref-show-ephemeral-use.adoc
  downstream/modules/platform/ref-storage-invocation.adoc
  downstream/modules/platform/ref-supported-storage.adoc
Labels: 2.5

#3339 AAP 44162 AAP-44161 Add docs for portal
  downstream/attributes/attributes.adoc
  downstream/modules/devtools/proc-rhdh-update-plugin-registry.adoc
  downstream/titles/aap-plugin-rhdh-install/docinfo.xml
  downstream/titles/self-service-install/aap-common
  downstream/titles/self-service-install/attributes
  downstream/titles/self-service-install/devtools
  downstream/titles/self-service-install/docinfo.xml
  downstream/titles/self-service-install/images
  downstream/titles/self-service-install/master.adoc
  downstream/titles/self-service-install/snippets
  downstream/titles/self-service-using/aap-common
  downstream/titles/self-service-using/attributes
  downstream/titles/self-service-using/devtools
  downstream/titles/self-service-using/docinfo.xml
  downstream/titles/self-service-using/images
  downstream/titles/self-service-using/master.adoc
  downstream/titles/self-service-using/snippets
Labels: Attributes, 2.5, Needs backport to 2.5

#3386 2.5 AAP 44162 AAP-44161 Add docs for portal (#3339)
  downstream/attributes/attributes.adoc
  downstream/modules/devtools/proc-rhdh-update-plugin-registry.adoc
  downstream/titles/self-service-install/aap-common
  downstream/titles/self-service-install/attributes
  downstream/titles/self-service-install/devtools
  downstream/titles/self-service-install/docinfo.xml
  downstream/titles/self-service-install/images
  downstream/titles/self-service-install/master.adoc
  downstream/titles/self-service-install/snippets
  downstream/titles/self-service-using/aap-common
  downstream/titles/self-service-using/attributes
  downstream/titles/self-service-using/devtools
  downstream/titles/self-service-using/docinfo.xml
  downstream/titles/self-service-using/images
  downstream/titles/self-service-using/master.adoc
  downstream/titles/self-service-using/snippets
Labels: 2.5

#3348 Backport 2.5 3284 Changes admonition from IMPORTANT to NOTE, per discussion
  downstream/assemblies/eda/assembly-eda-credentials.adoc
  downstream/modules/eda/proc-eda-set-up-rulebook-activation.adoc
Labels: documentation, Technical review complete, Peer review complete, 2.5

#3392 2.5 AAP-45307 Release notes for AAP self-service tech preview (#3391)
  downstream/attributes/attributes.adoc
  downstream/titles/release-notes/topics/aap-25.adoc
  downstream/titles/release-notes/topics/snippets
Labels: AAP Release notes, 2.5

#3388 AAP-41275: Added chatbot docs
  downstream/assemblies/platform/assembly-configure-aap-operator.adoc
  downstream/assemblies/platform/assembly-deploying-chatbot-operator.adoc
  downstream/assemblies/platform/assembly-install-aap-operator.adoc
  downstream/attributes/attributes.adoc
  downstream/images/aap-ansible-lightspeed-intelligent-assistant.png
  downstream/images/chatbot-icon.png
  downstream/images/sun-icon.png
  downstream/modules/platform/con-using-chatbot.adoc
  downstream/modules/platform/proc-create-chatbot-config-secret.adoc
  downstream/modules/platform/proc-install-aap-operator-chatbot.adoc
  downstream/modules/platform/proc-install-aap-operator.adoc
  downstream/modules/platform/proc-operator-link-components.adoc
  downstream/modules/platform/proc-update-aap-operator-yaml-chatbot.adoc
  downstream/titles/aap-operator-installation/master.adoc
Labels: 2.5, Needs backport to 2.5

#3327 Backport-2.5-3210 (AAP-42948) Changed all instances of copy to duplicate in Credentials chapter
  downstream/modules/eda/proc-eda-duplicate-credential.adoc
Labels: documentation, Ready for review, Technical review complete, 2.5

#3396 AAP-45308 Self-service Install and usage guides (#3394)
  downstream/assemblies/devtools/assembly-self-service-deregister-templates.adoc
  downstream/assemblies/devtools/assembly-self-service-feedback.adoc
  downstream/assemblies/devtools/assembly-self-service-rbac.adoc
  downstream/assemblies/devtools/assembly-self-service-scm-credentials-private-repos.adoc
  downstream/assemblies/devtools/assembly-self-service-using-overview.adoc
  downstream/assemblies/devtools/assembly-self-service-using-prereqs.adoc
  downstream/assemblies/devtools/assembly-self-service-using-repo-setup.adoc
  downstream/assemblies/devtools/assembly-self-service-working-templates.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/devtools/proc-self-service-add-scm-credentials-aap.adoc
  downstream/modules/devtools/proc-self-service-add-template.adoc
  downstream/modules/devtools/proc-self-service-create-collection-repo.adoc
  downstream/modules/devtools/proc-self-service-create-pattern-loader-repo.adoc
  downstream/modules/devtools/proc-self-service-deregister-dynamic-templates.adoc
  downstream/modules/devtools/proc-self-service-deregister-preinstalled-templates.adoc
  downstream/modules/devtools/proc-self-service-export-collection-pah.adoc
  downstream/modules/devtools/proc-self-service-launch-template.adoc
  downstream/modules/devtools/proc-self-service-set-up-rbac.adoc
  downstream/modules/devtools/proc-self-service-share-credentials-aap.adoc
  downstream/modules/devtools/proc-self-service-verify-rbac.adoc
  downstream/titles/release-notes/topics/aap-25.adoc
  downstream/titles/self-service-using/docinfo.xml
  downstream/titles/self-service-using/master.adoc
Labels: 2.5

#3384 AAP-42568 - restructing doc
  downstream/assemblies/platform/assembly-install-aap-gateway.adoc
  downstream/assemblies/platform/assembly-operator-configure-aap-components.adoc
  downstream/assemblies/platform/assembly-operator-configure-gateway.adoc
  downstream/assemblies/platform/assembly-operator-install-operator.adoc
  downstream/modules/platform/proc-operator-access-aap.adoc
  downstream/modules/platform/proc-operator-upgrade.adoc
  downstream/modules/platform/proc-update-aap-on-ocp.adoc
  downstream/titles/aap-operator-installation/master.adoc
Labels: documentation, Draft, 2.5, AAP operator

#3397 Backport 3384 to 2.5
  downstream/assemblies/platform/assembly-install-aap-gateway.adoc
  downstream/assemblies/platform/assembly-operator-configure-aap-components.adoc
  downstream/assemblies/platform/assembly-operator-configure-gateway.adoc
  downstream/assemblies/platform/assembly-operator-install-operator.adoc
  downstream/modules/platform/proc-operator-access-aap.adoc
  downstream/modules/platform/proc-operator-upgrade.adoc
  downstream/modules/platform/proc-update-aap-on-ocp.adoc
  downstream/titles/aap-operator-installation/master.adoc
Labels: 2.5

#3398 Removing sections no longer required as gateway exists
  downstream/assemblies/platform/assembly-aap-backup.adoc
Labels: documentation, 2.5, AAP operator, Needs backport to 2.5

#3399 Removing sections no longer required as gateway exists (#3398)
  downstream/assemblies/platform/assembly-aap-backup.adoc
Labels: 2.5

#3395 AAP-45308 AAP Self Service installation guide
  downstream/assemblies/devtools/assembly-self-service-about.adoc
  downstream/assemblies/devtools/assembly-self-service-accessing-deployment.adoc
  downstream/assemblies/devtools/assembly-self-service-create-ocp-registry.adoc
  downstream/assemblies/devtools/assembly-self-service-create-ocp-secrets.adoc
  downstream/assemblies/devtools/assembly-self-service-generate-scm-tokens.adoc
  downstream/assemblies/devtools/assembly-self-service-helm-install.adoc
  downstream/assemblies/devtools/assembly-self-service-installation-overview.adoc
  downstream/assemblies/devtools/assembly-self-service-preinstall-config.adoc
  downstream/assemblies/devtools/assembly-self-service-rbac.adoc
  downstream/assemblies/devtools/assembly-self-service-scm-credentials-private-repos.adoc
  downstream/assemblies/devtools/assembly-self-service-telemetry-capture.adoc
  downstream/assemblies/devtools/assembly-self-service-using-repo-setup.adoc
  downstream/assemblies/devtools/assembly-self-service-view-deployment.adoc
  downstream/assemblies/devtools/assembly-self-service-working-templates.adoc
  downstream/images/rhaap-sign-in-page.png
  downstream/images/self-service-create-oauth-app.png
  downstream/images/self-service-plugin-registry.png
  downstream/images/self-service-pod-env-variables.png
  downstream/images/self-service-sign-in-page.png
  downstream/images/self-service-templates-view.png
  downstream/images/self-service-verify-helm-install.png
  downstream/images/self-service-view-deployment-logs.png
  downstream/images/self-service-view-install-messages.png
  downstream/modules/devtools/con-installation-prereqs.adoc
  downstream/modules/devtools/proc-self-service-add-deployment-url-oauth-app.adoc
  downstream/modules/devtools/proc-self-service-create-gh-pat.adoc
  downstream/modules/devtools/proc-self-service-create-gl-pat.adoc
  downstream/modules/devtools/proc-self-service-create-oauth-app.adoc
  downstream/modules/devtools/proc-self-service-create-ocp-auth-secrets.adoc
  downstream/modules/devtools/proc-self-service-create-scm-secrets.adoc
  downstream/modules/devtools/proc-self-service-download-tar.adoc
  downstream/modules/devtools/proc-self-service-generate-oauth-token.adoc
  downstream/modules/devtools/proc-self-service-install-helm-from-catalog.adoc
  downstream/modules/devtools/proc-self-service-install-verify.adoc
  downstream/modules/devtools/proc-self-service-ocp-project-setup.adoc
  downstream/modules/devtools/proc-self-service-setup-registry-image.adoc
  downstream/modules/devtools/proc-self-service-sign-in.adoc
  downstream/modules/devtools/proc-self-service-view-configmap.adoc
  downstream/modules/devtools/proc-self-service-view-deployment-logs.adoc
  downstream/titles/self-service-install/master.adoc
Labels: 2.5, Needs backport to 2.5

#3402 2.5 AAP-45308 AAP Self Service installation guide (#3395)
  downstream/assemblies/devtools/assembly-self-service-about.adoc
  downstream/assemblies/devtools/assembly-self-service-accessing-deployment.adoc
  downstream/assemblies/devtools/assembly-self-service-create-ocp-registry.adoc
  downstream/assemblies/devtools/assembly-self-service-create-ocp-secrets.adoc
  downstream/assemblies/devtools/assembly-self-service-generate-scm-tokens.adoc
  downstream/assemblies/devtools/assembly-self-service-helm-install.adoc
  downstream/assemblies/devtools/assembly-self-service-installation-overview.adoc
  downstream/assemblies/devtools/assembly-self-service-preinstall-config.adoc
  downstream/assemblies/devtools/assembly-self-service-rbac.adoc
  downstream/assemblies/devtools/assembly-self-service-scm-credentials-private-repos.adoc
  downstream/assemblies/devtools/assembly-self-service-telemetry-capture.adoc
  downstream/assemblies/devtools/assembly-self-service-using-repo-setup.adoc
  downstream/assemblies/devtools/assembly-self-service-view-deployment.adoc
  downstream/assemblies/devtools/assembly-self-service-working-templates.adoc
  downstream/images/rhaap-sign-in-page.png
  downstream/images/self-service-create-oauth-app.png
  downstream/images/self-service-plugin-registry.png
  downstream/images/self-service-pod-env-variables.png
  downstream/images/self-service-sign-in-page.png
  downstream/images/self-service-templates-view.png
  downstream/images/self-service-verify-helm-install.png
  downstream/images/self-service-view-deployment-logs.png
  downstream/images/self-service-view-install-messages.png
  downstream/modules/devtools/con-installation-prereqs.adoc
  downstream/modules/devtools/proc-self-service-add-deployment-url-oauth-app.adoc
  downstream/modules/devtools/proc-self-service-create-gh-pat.adoc
  downstream/modules/devtools/proc-self-service-create-gl-pat.adoc
  downstream/modules/devtools/proc-self-service-create-oauth-app.adoc
  downstream/modules/devtools/proc-self-service-create-ocp-auth-secrets.adoc
  downstream/modules/devtools/proc-self-service-create-scm-secrets.adoc
  downstream/modules/devtools/proc-self-service-download-tar.adoc
  downstream/modules/devtools/proc-self-service-generate-oauth-token.adoc
  downstream/modules/devtools/proc-self-service-install-helm-from-catalog.adoc
  downstream/modules/devtools/proc-self-service-install-verify.adoc
  downstream/modules/devtools/proc-self-service-ocp-project-setup.adoc
  downstream/modules/devtools/proc-self-service-setup-registry-image.adoc
  downstream/modules/devtools/proc-self-service-sign-in.adoc
  downstream/modules/devtools/proc-self-service-view-configmap.adoc
  downstream/modules/devtools/proc-self-service-view-deployment-logs.adoc
  downstream/titles/self-service-install/master.adoc
Labels: 2.5

#3405 2.5 Add gathering logs proc to Containerized installation (#3401)
  downstream/assemblies/platform/assembly-appendix-troubleshoot-containerized-aap.adoc
  downstream/modules/platform/proc-containerized-troubleshoot-gathering-logs.adoc
Labels: 2.5, Backported to 2.5

#3407 AAP-45308 Update OAuth Redirect URL placeholder replacement
  downstream/images/self-service-generate-oauth-token.png
  downstream/modules/devtools/proc-self-service-add-deployment-url-oauth-app.adoc
  downstream/modules/devtools/proc-self-service-create-oauth-app.adoc
  downstream/modules/devtools/proc-self-service-generate-oauth-token.adoc
Labels: 2.5, Backported to 2.5

#3406 AAP-41275: Added chatbot docs (#3388)
  downstream/assemblies/platform/assembly-deploying-chatbot-operator.adoc
  downstream/assemblies/platform/assembly-install-aap-gateway.adoc
  downstream/assemblies/platform/assembly-install-aap-operator.adoc
  downstream/attributes/attributes.adoc
  downstream/images/aap-ansible-lightspeed-intelligent-assistant.png
  downstream/images/chatbot-icon.png
  downstream/images/sun-icon.png
  downstream/modules/platform/con-using-chatbot.adoc
  downstream/modules/platform/proc-create-chatbot-config-secret.adoc
  downstream/modules/platform/proc-install-aap-operator-chatbot.adoc
  downstream/modules/platform/proc-install-aap-operator.adoc
  downstream/modules/platform/proc-operator-link-components.adoc
  downstream/modules/platform/proc-update-aap-operator-yaml-chatbot.adoc
  downstream/titles/aap-operator-installation/master.adoc
Labels: 2.5, Backported to 2.5

#3410 Minor formatting fixes highlighted by the SME
  downstream/modules/platform/proc-controller-set-up-LDAP.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#3411 [Backport] Minor formatting fixes highlighted by the SME (#3410)
  downstream/modules/platform/proc-controller-set-up-LDAP.adoc
Labels: Ready for review, 2.5

#3414 Rename delete icon
  downstream/modules/platform/proc-controller-delete-job-template.adoc
Labels: Controller, 2.5, Needs backport to 2.5

#3415 Rename delete icon (#3414)
  downstream/modules/platform/proc-controller-delete-job-template.adoc
Labels: Controller, 2.5, Backported to 2.5

#3416 2.5 Add Rootless Podman and NFS info to Containerized installation (#3400)
  downstream/modules/platform/ref-cont-aap-system-requirements.adoc
Labels: 2.5, Backported to 2.5

#3417 Updating controller API endpoints (#3363)
  downstream/modules/platform/con-controller-api-basic-auth.adoc
Labels: documentation, 2.5, Backported to 2.5

#3419 adding in missing module
  downstream/titles/aap-operator-installation/master.adoc
Labels: 2.5, Needs backport to 2.5

#3421 AAP-45308 Add sync frequency section to portal install doc (#3418)
  downstream/assemblies/devtools/assembly-self-service-accessing-deployment.adoc
  downstream/assemblies/devtools/assembly-self-service-create-ocp-registry.adoc
  downstream/assemblies/devtools/assembly-self-service-deregister-templates.adoc
  downstream/modules/devtools/proc-self-service-create-ocp-auth-secrets.adoc
  downstream/modules/devtools/proc-self-service-install-helm-from-catalog.adoc
  downstream/modules/devtools/proc-self-service-ocp-project-setup.adoc
  downstream/modules/devtools/proc-self-service-setup-registry-image.adoc
  downstream/modules/devtools/proc-self-service-sync-frequency.adoc
Labels: 2.5

#3425 AAP-45307 Delete release note for self service tech preview
  downstream/titles/release-notes/topics/aap-25.adoc
Labels: AAP Release notes, 2.5, Needs backport to 2.5

#3429 Update local disk req for CONT installs
  downstream/modules/platform/proc-downloading-containerized-aap.adoc
  downstream/snippets/cont-tested-vm-config.adoc
Labels: 2.5, Needs backport to 2.5

#3379 Adding install steps to RHEM doc
  downstream/assemblies/platform/assembly-edge-manager-install.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/platform/con-edge-manager-agent-service.adoc
  downstream/modules/platform/con-edge-manager-api-server.adoc
  downstream/modules/platform/con-edge-manager-set-up-oauth.adoc
  downstream/modules/platform/proc-edge-manager-bootc.adoc
  downstream/modules/platform/proc-edge-manager-install-rpm-package.adoc
  downstream/modules/platform/proc-edge-manager-integrate-aap.adoc
  downstream/modules/platform/proc-edge-manager-oauth-auto.adoc
  downstream/modules/platform/proc-edge-manager-oauth-manually.adoc
  downstream/modules/platform/ref-edge-manager-certificates.adoc
  downstream/modules/platform/ref-edge-manager-config-inline.adoc
  downstream/titles/edge-manager/edge-manager-user-guide/master.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#3432 AAP-43543 - Unpublish LDAP case sensitivity changes until code release
  downstream/modules/platform/proc-controller-set-up-LDAP.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#3433 [Backport] AAP-43543 - Unpublish LDAP case sensitivity changes until code release (#3432)
  downstream/modules/platform/proc-controller-set-up-LDAP.adoc
Labels: 2.5

#3435 Add a menu attribute for Settings>Policy
  downstream/attributes/attributes.adoc
Labels: Ready for review, Attributes, 2.5, Needs backport to 2.5

#3436 [Backport] Add a menu attribute for Settings>Policy (#3435)
  downstream/attributes/attributes.adoc
Labels: Attributes, 2.5

#3438 Adding install steps to RHEM doc (#3379)
  downstream/assemblies/platform/assembly-edge-manager-install.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/platform/con-edge-manager-agent-service.adoc
  downstream/modules/platform/con-edge-manager-api-server.adoc
  downstream/modules/platform/con-edge-manager-set-up-oauth.adoc
  downstream/modules/platform/proc-edge-manager-bootc.adoc
  downstream/modules/platform/proc-edge-manager-install-rpm-package.adoc
  downstream/modules/platform/proc-edge-manager-integrate-aap.adoc
  downstream/modules/platform/proc-edge-manager-oauth-auto.adoc
  downstream/modules/platform/proc-edge-manager-oauth-manually.adoc
  downstream/modules/platform/ref-edge-manager-certificates.adoc
  downstream/modules/platform/ref-edge-manager-config-inline.adoc
  downstream/titles/edge-manager/edge-manager-user-guide/master.adoc
Labels: documentation, 2.5, Backported to 2.5

#3431 Correcting any errors found in staged view of RHEM doc
  downstream/assemblies/platform/assembly-edge-manager-intro.adoc
  downstream/modules/platform/con-edge-manager-agent-service.adoc
  downstream/modules/platform/con-edge-manager-build-bootc.adoc
  downstream/modules/platform/proc-edge-manager-build-bootc-image.adoc
  downstream/modules/platform/proc-edge-manager-integrate-aap.adoc
  downstream/modules/platform/proc-edge-manager-oauth-manually.adoc
  downstream/modules/platform/ref-edge-manager-config-inline.adoc
  downstream/modules/platform/ref-edge-manager-device-lifecycle.adoc
  downstream/modules/platform/ref-edge-manager-rule-files.adoc
  downstream/titles/edge-manager/edge-manager-user-guide/docinfo.xml
Labels: documentation, 2.5, Needs backport to 2.5

#3439 Correcting any errors found in staged view of RHEM doc (#3431)
  downstream/assemblies/platform/assembly-edge-manager-intro.adoc
  downstream/modules/platform/con-edge-manager-agent-service.adoc
  downstream/modules/platform/con-edge-manager-build-bootc.adoc
  downstream/modules/platform/proc-edge-manager-build-bootc-image.adoc
  downstream/modules/platform/proc-edge-manager-integrate-aap.adoc
  downstream/modules/platform/proc-edge-manager-oauth-manually.adoc
  downstream/modules/platform/ref-edge-manager-config-inline.adoc
  downstream/modules/platform/ref-edge-manager-device-lifecycle.adoc
  downstream/modules/platform/ref-edge-manager-rule-files.adoc
  downstream/titles/edge-manager/edge-manager-user-guide/docinfo.xml
Labels: documentation, 2.5, Backported to 2.5

#3437 AAP-45542 Self-service release notes and fixes
  downstream/assemblies/devtools/assembly-self-service-about.adoc
  downstream/assemblies/devtools/assembly-self-service-installation-overview.adoc
  downstream/assemblies/devtools/assembly-self-service-ocp-project.adoc
  downstream/assemblies/devtools/assembly-self-service-preinstall-config.adoc
  downstream/images/self-service-create-oauth-app.png
  downstream/modules/devtools/con-installation-prereqs.adoc
  downstream/modules/devtools/proc-self-service-add-deployment-url-oauth-app.adoc
  downstream/modules/devtools/proc-self-service-add-scm-credentials-aap.adoc
  downstream/modules/devtools/proc-self-service-create-oauth-app.adoc
  downstream/modules/devtools/proc-self-service-download-tar.adoc
  downstream/modules/devtools/proc-self-service-ocp-project-setup-ui.adoc
  downstream/modules/devtools/proc-self-service-ocp-project-setup.adoc
  downstream/titles/release-notes/topics/tech-preview.adoc
Labels: 2.5, Needs backport to 2.5

#3440 AAP-45542 Self-service release notes and fixes (#3437)
  downstream/assemblies/devtools/assembly-self-service-about.adoc
  downstream/assemblies/devtools/assembly-self-service-installation-overview.adoc
  downstream/assemblies/devtools/assembly-self-service-ocp-project.adoc
  downstream/assemblies/devtools/assembly-self-service-preinstall-config.adoc
  downstream/images/self-service-create-oauth-app.png
  downstream/modules/devtools/con-installation-prereqs.adoc
  downstream/modules/devtools/proc-self-service-add-deployment-url-oauth-app.adoc
  downstream/modules/devtools/proc-self-service-add-scm-credentials-aap.adoc
  downstream/modules/devtools/proc-self-service-create-oauth-app.adoc
  downstream/modules/devtools/proc-self-service-download-tar.adoc
  downstream/modules/devtools/proc-self-service-ocp-project-setup-ui.adoc
  downstream/modules/devtools/proc-self-service-ocp-project-setup.adoc
  downstream/titles/release-notes/topics/tech-preview.adoc
Labels: AAP Release notes, 2.5

#3434 AAP-40838: creates policy as code assemblies and modules
  downstream/assemblies/platform/assembly-controller-pac.adoc
  downstream/modules/platform/con-pac-policies-rules.adoc
  downstream/modules/platform/proc-configure-pac-enforcement.adoc
  downstream/modules/platform/proc-configure-pac-settings.adoc
  downstream/modules/platform/proc-enable-pac.adoc
  downstream/modules/platform/proc-pac-add-policy-to-inventory.adoc
  downstream/modules/platform/proc-pac-add-policy-to-org.adoc
  downstream/modules/platform/proc-pac-add-policy-to-template.adoc
  downstream/modules/platform/ref-pac-inputs-outputs.adoc
  downstream/titles/controller/controller-admin-guide/master.adoc
Labels: Controller, 2.5, Needs backport to 2.5

#3442 Bp to 2.5: AAP-40838: creates policy as code assemblies and modules (#3434)
  downstream/assemblies/platform/assembly-controller-pac.adoc
  downstream/modules/platform/con-pac-policies-rules.adoc
  downstream/modules/platform/proc-configure-pac-enforcement.adoc
  downstream/modules/platform/proc-configure-pac-settings.adoc
  downstream/modules/platform/proc-enable-pac.adoc
  downstream/modules/platform/proc-pac-add-policy-to-inventory.adoc
  downstream/modules/platform/proc-pac-add-policy-to-org.adoc
  downstream/modules/platform/proc-pac-add-policy-to-template.adoc
  downstream/modules/platform/ref-pac-inputs-outputs.adoc
  downstream/titles/controller/controller-admin-guide/master.adoc
Labels: Controller, 2.5

#3443 Updating RHEM install steps
  downstream/modules/platform/proc-edge-manager-install-rpm-package.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#3444 Updating RHEM install steps (#3443)
  downstream/modules/platform/proc-edge-manager-install-rpm-package.adoc
Labels: documentation, 2.5, Backported to 2.5

#3446 Adding changes from AAP-45701 to reset main
  downstream/modules/platform/proc-edge-manager-install-rpm-package.adoc
Labels: 2.5, Needs backport to 2.5

#3450 AAP-40838: PaC minor edits based on SME feedback
  downstream/modules/platform/proc-configure-pac-settings.adoc
Labels: Controller, 2.5

#3451 Backport to 2.5: AAP-40838: minor edits based on SME feedback (#3450)
  downstream/modules/platform/proc-configure-pac-settings.adoc
Labels: Controller, 2.5

#3413 AAP-41334: Updates info on requirements files in Managing automation content
  downstream/assemblies/hub/assembly-managing-cert-valid-content.adoc
  downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc
  downstream/assemblies/hub/assembly-synclists.adoc
  downstream/modules/hub/proc-create-requirements-file.adoc
  downstream/modules/hub/proc-create-synclist.adoc
  downstream/modules/hub/proc-set-rhcertified-remote.adoc
Labels: Automation Hub, 2.5, Needs backport to 2.5

#3452 AAP-45780 Remove outdated modules
  downstream/assemblies/platform/assembly-aap-recovery.adoc
Labels: 2.5, AAP operator

#3453 Removing recovery modules that are no longer needed as everything is …
  downstream/assemblies/platform/assembly-aap-recovery.adoc
Labels: 2.5, AAP operator

#3448 Add job template variables to using automation execution
  downstream/assemblies/platform/assembly-ug-controller-job-templates.adoc
  downstream/modules/platform/ref-controller-job-template-variables.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#3456 Add job template variables to using automation execution (#3448)
  downstream/assemblies/platform/assembly-ug-controller-job-templates.adoc
  downstream/modules/platform/ref-controller-job-template-variables.adoc
Labels: documentation, 2.5, Backported to 2.5

#3457 2.5 Update Containerized installation (#3454)
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/platform/proc-containerized-troubleshoot-gathering-logs.adoc
  downstream/modules/platform/proc-downloading-containerized-aap.adoc
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc
  downstream/modules/platform/ref-cont-aap-system-requirements.adoc
  downstream/modules/platform/ref-using-custom-tls-certificates.adoc
Labels: 2.5, Backported to 2.5

#3449 Ansible Plugins 1.5 - updates to plug-ins installation doc
  downstream/assemblies/devtools/assembly-rhdh-ocp-required-installation.adoc
  downstream/modules/devtools/proc-rhdh-add-plugin-config.adoc
  downstream/modules/devtools/proc-rhdh-configure-showcase-location.adoc
  downstream/modules/devtools/proc-rhdh-create-plugin-registry.adoc
  downstream/modules/devtools/proc-rhdh-download-plugins.adoc
  downstream/modules/devtools/proc-rhdh-install-dynamic-plugins-operator.adoc
  downstream/modules/devtools/proc-rhdh-uninstall-ocp-helm.adoc
  downstream/modules/devtools/proc-rhdh-uninstall-ocp-operator-plugins-cm.adoc
  downstream/modules/devtools/proc-rhdh-uninstall-ocp-operator.adoc
  downstream/modules/devtools/proc-rhdh-update-plugins-helm-version-numbers.adoc
  downstream/modules/devtools/proc-rhdh-update-plugins-operator-version-numbers.adoc
  downstream/modules/devtools/proc-self-service-download-tar.adoc
  downstream/modules/devtools/proc-self-service-setup-registry-image.adoc
  downstream/modules/devtools/ref-rhdh-full-aap-configmap-example.adoc
  downstream/modules/devtools/ref-rhdh-full-helm-chart-ansible-plugins.adoc
Labels: Needs backport to 2.4, 2.4, 2.5, Needs backport to 2.5

#3458 2.5 Update names and configmap for ansible-plugins 1.5 (#3449)
  downstream/assemblies/devtools/assembly-rhdh-ocp-required-installation.adoc
  downstream/modules/devtools/proc-rhdh-add-plugin-config.adoc
  downstream/modules/devtools/proc-rhdh-configure-showcase-location.adoc
  downstream/modules/devtools/proc-rhdh-create-plugin-registry.adoc
  downstream/modules/devtools/proc-rhdh-download-plugins.adoc
  downstream/modules/devtools/proc-rhdh-install-dynamic-plugins-operator.adoc
  downstream/modules/devtools/proc-rhdh-uninstall-ocp-helm.adoc
  downstream/modules/devtools/proc-rhdh-uninstall-ocp-operator-plugins-cm.adoc
  downstream/modules/devtools/proc-rhdh-uninstall-ocp-operator.adoc
  downstream/modules/devtools/proc-rhdh-update-plugins-helm-version-numbers.adoc
  downstream/modules/devtools/proc-rhdh-update-plugins-operator-version-numbers.adoc
  downstream/modules/devtools/proc-self-service-download-tar.adoc
  downstream/modules/devtools/proc-self-service-setup-registry-image.adoc
  downstream/modules/devtools/ref-rhdh-full-aap-configmap-example.adoc
  downstream/modules/devtools/ref-rhdh-full-helm-chart-ansible-plugins.adoc
Labels: 2.5

#3459 bp to 2.5:AAP-41334: Updates info on requirements files in Managing automation …
  downstream/assemblies/hub/assembly-managing-cert-valid-content.adoc
  downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc
  downstream/assemblies/hub/assembly-synclists.adoc
  downstream/modules/hub/proc-create-requirements-file.adoc
  downstream/modules/hub/proc-create-synclist.adoc
  downstream/modules/hub/proc-set-rhcertified-remote.adoc
Labels: Automation Hub, 2.5

#3445 Self-service: Rename; add proc to disable telemetry
  downstream/assemblies/devtools/assembly-self-service-telemetry-capture.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/devtools/con-self-service-telemetry-data.adoc
  downstream/modules/devtools/proc-self-service-add-deployment-url-oauth-app.adoc
  downstream/modules/devtools/proc-self-service-install-verify.adoc
  downstream/modules/devtools/proc-self-service-ocp-project-setup.adoc
  downstream/modules/devtools/proc-self-service-setup-registry-image.adoc
  downstream/modules/devtools/proc-self-service-sync-frequency.adoc
  downstream/modules/devtools/proc-self-service-telemetry-disable.adoc
  downstream/modules/devtools/proc-self-service-view-configmap.adoc
  downstream/modules/devtools/proc-self-service-view-deployment-logs.adoc
  downstream/titles/self-service-install/docinfo.xml
  downstream/titles/self-service-install/master.adoc
Labels: 2.5, Needs backport to 2.5

#3463 Correct typo in Creating and consuming execution environments
  downstream/modules/builder/con-additional-build-files.adoc
Labels: Needs backport to 2.4, 2.4, 2.5, Needs backport to 2.5

#3462 AAP-45863 edits
  stories/topics/con-saas-connectivity.adoc
Labels: AAP on clouds, Ansible on AWS, SaaS on AWS

#3465 2.5 Self-service: Rename; add proc to disable telemetry (#3445)
  downstream/assemblies/devtools/assembly-self-service-telemetry-capture.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/devtools/con-self-service-telemetry-data.adoc
  downstream/modules/devtools/proc-self-service-add-deployment-url-oauth-app.adoc
  downstream/modules/devtools/proc-self-service-install-verify.adoc
  downstream/modules/devtools/proc-self-service-ocp-project-setup.adoc
  downstream/modules/devtools/proc-self-service-setup-registry-image.adoc
  downstream/modules/devtools/proc-self-service-sync-frequency.adoc
  downstream/modules/devtools/proc-self-service-telemetry-disable.adoc
  downstream/modules/devtools/proc-self-service-view-configmap.adoc
  downstream/modules/devtools/proc-self-service-view-deployment-logs.adoc
  downstream/titles/self-service-install/docinfo.xml
  downstream/titles/self-service-install/master.adoc
Labels: 2.5

#3464 2.5 Correct typo in Creating and consuming execution environments (#3463)
  downstream/modules/builder/con-additional-build-files.adoc
Labels: 2.5, Backported to 2.5

#3466 2.4 Correct typo in Creating and consuming execution environments (#3463)
  downstream/modules/builder/con-additional-build-files.adoc
Labels: Backported to 2.4, 2.4

#3467 Rename AAP self-service user guide
  downstream/titles/self-service-using/docinfo.xml
  downstream/titles/self-service-using/master.adoc
Labels: 2.5, Needs backport to 2.5

#3468 2.5 Rename AAP self-service user guide (#3467)
  downstream/titles/self-service-using/docinfo.xml
  downstream/titles/self-service-using/master.adoc
Labels: 2.5

#3469 Update ansible inventory vars
  downstream/modules/platform/ref-ansible-inventory-variables.adoc
Labels: 2.5, Needs backport to 2.5

#3470 2.5 Update ansible inventory vars (#3469)
  downstream/modules/platform/ref-ansible-inventory-variables.adoc
Labels: 2.5, Backported to 2.5

#3441 AAP-40838: PaC input/output table
  downstream/assemblies/platform/assembly-controller-pac.adoc
  downstream/modules/platform/proc-pac-add-policy-to-inventory.adoc
  downstream/modules/platform/proc-pac-add-policy-to-org.adoc
  downstream/modules/platform/proc-pac-add-policy-to-template.adoc
  downstream/modules/platform/ref-pac-inputs-outputs.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#3471 AAP-40838: PaC input/output table (#3441)
  downstream/assemblies/platform/assembly-controller-pac.adoc
  downstream/modules/platform/proc-pac-add-policy-to-inventory.adoc
  downstream/modules/platform/proc-pac-add-policy-to-org.adoc
  downstream/modules/platform/proc-pac-add-policy-to-template.adoc
  downstream/modules/platform/ref-pac-inputs-outputs.adoc
Labels: Controller, 2.5

#3474 AAP-45195: AAP-45195: Updated docs with new model_verify_ssl key
  lightspeed/modules/proc_create-connection-secrets.adoc
  lightspeed/modules/proc_troubleshooting-lightspeed-onpremise-config.adoc
Labels: Lightspeed

#3475 Performing migration checklist review for OCP Performance considerations
  downstream/assemblies/platform/assembly-configure-controller-OCP.adoc
  downstream/assemblies/platform/assembly-control-plane-adjustments.adoc
  downstream/assemblies/platform/assembly-pod-spec-modifications.adoc
  downstream/assemblies/platform/assembly-specify-dedicated-nodes.adoc
  downstream/modules/platform/con-alternative-capacity-limits.adoc
  downstream/modules/platform/con-pod-specification-mods.adoc
  downstream/modules/platform/proc-configure-controller-OCP.adoc
  downstream/modules/platform/proc-customizing-pod-specs.adoc
  downstream/modules/platform/proc-enable-pods-ref-images.adoc
  downstream/modules/platform/proc-specify-nodes-job-execution.adoc
  downstream/modules/platform/ref-assign-pods-to-nodes.adoc
  downstream/modules/platform/ref-container-resource-requirements.adoc
  downstream/modules/platform/ref-requests-limits.adoc
  downstream/modules/platform/ref-resource-management-pods-containers.adoc
  downstream/modules/platform/ref-resource-types.adoc
  downstream/modules/platform/ref-schedule-jobs-worker-nodes.adoc
  downstream/modules/platform/ref-set-custom-pod-timeout.adoc
  downstream/modules/platform/ref-set-requests-limits-for-containers.adoc
  downstream/titles/ocp_performance_guide/master.adoc
Labels: documentation, Draft, 2.4, 2.5, AAP operator

#3480 Performing migration checklist review (#3475)
  downstream/assemblies/platform/assembly-configure-controller-OCP.adoc
  downstream/assemblies/platform/assembly-control-plane-adjustments.adoc
  downstream/assemblies/platform/assembly-pod-spec-modifications.adoc
  downstream/assemblies/platform/assembly-specify-dedicated-nodes.adoc
  downstream/modules/platform/con-alternative-capacity-limits.adoc
  downstream/modules/platform/con-pod-specification-mods.adoc
  downstream/modules/platform/proc-configure-controller-OCP.adoc
  downstream/modules/platform/proc-customizing-pod-specs.adoc
  downstream/modules/platform/proc-enable-pods-ref-images.adoc
  downstream/modules/platform/proc-specify-nodes-job-execution.adoc
  downstream/modules/platform/ref-assign-pods-to-nodes.adoc
  downstream/modules/platform/ref-container-resource-requirements.adoc
  downstream/modules/platform/ref-requests-limits.adoc
  downstream/modules/platform/ref-resource-management-pods-containers.adoc
  downstream/modules/platform/ref-resource-types.adoc
  downstream/modules/platform/ref-schedule-jobs-worker-nodes.adoc
  downstream/modules/platform/ref-set-custom-pod-timeout.adoc
  downstream/modules/platform/ref-set-requests-limits-for-containers.adoc
  downstream/titles/ocp_performance_guide/master.adoc
Labels: 2.5, AAP operator

#3481 Performing migration checklist review (#3475)
  downstream/assemblies/platform/assembly-configure-controller-OCP.adoc
  downstream/assemblies/platform/assembly-control-plane-adjustments.adoc
  downstream/assemblies/platform/assembly-pod-spec-modifications.adoc
  downstream/assemblies/platform/assembly-specify-dedicated-nodes.adoc
  downstream/modules/platform/con-alternative-capacity-limits.adoc
  downstream/modules/platform/con-pod-specification-mods.adoc
  downstream/modules/platform/proc-configure-controller-OCP.adoc
  downstream/modules/platform/proc-customizing-pod-specs.adoc
  downstream/modules/platform/proc-enable-pods-ref-images.adoc
  downstream/modules/platform/proc-specify-nodes-job-execution.adoc
  downstream/modules/platform/ref-assign-pods-to-nodes.adoc
  downstream/modules/platform/ref-container-resource-requirements.adoc
  downstream/modules/platform/ref-requests-limits.adoc
  downstream/modules/platform/ref-resource-management-pods-containers.adoc
  downstream/modules/platform/ref-resource-types.adoc
  downstream/modules/platform/ref-schedule-jobs-worker-nodes.adoc
  downstream/modules/platform/ref-set-custom-pod-timeout.adoc
  downstream/modules/platform/ref-set-requests-limits-for-containers.adoc
  downstream/titles/ocp_performance_guide/master.adoc
Labels: 2.4, AAP operator

#3476 OCP backup and restore module checklist review
  downstream/assemblies/platform/assembly-aap-backup-recovery.adoc
  downstream/assemblies/platform/assembly-aap-backup.adoc
  downstream/assemblies/platform/assembly-aap-recovery.adoc
  downstream/assemblies/platform/assembly-aap-troubleshoot-backup-recovery.adoc
  downstream/modules/platform/con-aap-backup-recommendations.adoc
  downstream/modules/platform/con-aap-backup-recovery.adoc
  downstream/modules/platform/proc-aap-platform-gateway-backup.adoc
  downstream/modules/platform/proc-aap-platform-gateway-restore.adoc
  downstream/modules/platform/proc-troubleshoot-same-name.adoc
Labels: documentation, Draft, 2.5, AAP operator

#3482 OCP backup and restore moduel checklist review (#3476)
  downstream/assemblies/platform/assembly-aap-backup-recovery.adoc
  downstream/assemblies/platform/assembly-aap-backup.adoc
  downstream/assemblies/platform/assembly-aap-recovery.adoc
  downstream/assemblies/platform/assembly-aap-troubleshoot-backup-recovery.adoc
  downstream/modules/platform/con-aap-backup-recommendations.adoc
  downstream/modules/platform/con-aap-backup-recovery.adoc
  downstream/modules/platform/proc-aap-platform-gateway-backup.adoc
  downstream/modules/platform/proc-aap-platform-gateway-restore.adoc
  downstream/modules/platform/proc-troubleshoot-same-name.adoc
Labels: 2.5, AAP operator

#3479 Module review checklist for Installing on OCP
  downstream/assemblies/platform/assembly-install-aap-operator.adoc
  downstream/assemblies/platform/assembly-installing-aap-operator-cli.adoc
  downstream/assemblies/platform/assembly-operator-install-operator.adoc
  downstream/assemblies/platform/assembly-operator-install-planning.adoc
  downstream/modules/platform/con-about-operator.adoc
  downstream/modules/platform/con-ocp-supported-install.adoc
  downstream/modules/platform/con-operator-additional-resources.adoc
  downstream/modules/platform/con-operator-csrf-management.adoc
  downstream/modules/platform/con-operator-custom-resources.adoc
  downstream/modules/platform/proc-install-aap-operator-chatbot.adoc
  downstream/modules/platform/proc-install-aap-operator.adoc
  downstream/modules/platform/proc-install-cli-aap-operator.adoc
  downstream/modules/platform/proc-operator-link-components.adoc
  downstream/modules/platform/ref-operator-ocp-version.adoc
Labels: documentation, 2.5, AAP operator

#3477 Update self-service telemetry disable method
  downstream/modules/devtools/proc-self-service-telemetry-disable.adoc
Labels: 2.5, Needs backport to 2.5

#3485 2.5 Update self-service telemetry disable method (#3477)
  downstream/modules/devtools/proc-self-service-telemetry-disable.adoc
Labels: 2.5

#3484 Update RPM-A-ENV-B inventory file
  downstream/snippets/inventory-rpm-a-env-b.adoc
Labels: Technical review complete, 2.5, Needs backport to 2.5

#3486 2.5 Update RPM-A-ENV-B inventory file (#3484)
  downstream/snippets/inventory-rpm-a-env-b.adoc
Labels: 2.5, Backported to 2.5

#3487 AAP-28022 - Added note re: access for Remote Registries
  downstream/modules/platform/proc-gw-team-access-resources.adoc
  downstream/modules/platform/proc-gw-user-access-resources.adoc
Labels: Ready for review, 2.5

#3488 [Backport] AAP-28022 - Added not re: access for Remote Registries (#3487)
  downstream/modules/platform/proc-gw-team-access-resources.adoc
  downstream/modules/platform/proc-gw-user-access-resources.adoc
Labels: Ready for review, 2.5

#3494 Applying mod doc checklist to 2.4 version
  downstream/assemblies/platform/assembly-aap-backup-recovery.adoc
  downstream/assemblies/platform/assembly-aap-backup.adoc
  downstream/assemblies/platform/assembly-aap-recovery.adoc
  downstream/assemblies/platform/assembly-aap-troubleshoot-backup-recovery.adoc
  downstream/modules/platform/con-aap-backup-recommendations.adoc
  downstream/modules/platform/con-aap-backup-recovery.adoc
  downstream/modules/platform/proc-aap-controller-backup.adoc
  downstream/modules/platform/proc-aap-controller-restore.adoc
  downstream/modules/platform/proc-aap-controller-yaml-backup.adoc
  downstream/modules/platform/proc-aap-controller-yaml-restore.adoc
  downstream/modules/platform/proc-aap-hub-backup.adoc
  downstream/modules/platform/proc-aap-hub-restore.adoc
  downstream/modules/platform/proc-troubleshoot-same-name.adoc
Labels: 2.4, AAP operator

#3497 Backport PR #3491 from main branch to AAP 2.5 branch
  downstream/assemblies/platform/assembly-deploying-chatbot-operator.adoc
Labels: Ready for review, 2.5, Backported to 2.5

#3490 AAP-45080 Updates to ensure mod doc compliance
  downstream/assemblies/platform/assembly-controller-search.adoc
  downstream/modules/platform/ref-controller-other-search-considerations.adoc
  downstream/modules/platform/ref-controller-search-sort.adoc
  downstream/modules/platform/ref-controller-search-tips.adoc
  downstream/modules/platform/ref-controller-search-values-related-fields.adoc
  downstream/modules/platform/ref-controller-values-for-search-fields.adoc
Labels: documentation, Peer review complete, 2.5, Needs backport to 2.5

#3489 AAP-45079 Using automation execution UI and modular compliance chapter 3
  downstream/assemblies/platform/assembly-controller-user-interface.adoc
  downstream/modules/platform/con-controller-administration.adoc
  downstream/modules/platform/con-controller-infrastructure.adoc
  downstream/modules/platform/con-controller-settings.adoc
Labels: documentation, Peer review complete, 2.5, Needs backport to 2.5

#3501 AAP-41334: reorganizes syncing procedures for clarity + adds KB on resource requirements
  downstream/assemblies/hub/assembly-validated-content.adoc
  downstream/modules/hub/con-token-management-hub.adoc
  downstream/modules/hub/proc-create-synclist.adoc
  downstream/modules/hub/proc-set-community-remote.adoc
  downstream/modules/hub/proc-set-rhcertified-remote.adoc
Labels: Automation Hub, 2.5, Needs backport to 2.5

#3502 bp to 2.5:AAP-41334: reorganizes syncing procedures for clarity + adds KB on re…
  downstream/assemblies/hub/assembly-validated-content.adoc
  downstream/modules/hub/con-token-management-hub.adoc
  downstream/modules/hub/proc-create-synclist.adoc
  downstream/modules/hub/proc-set-community-remote.adoc
  downstream/modules/hub/proc-set-rhcertified-remote.adoc
Labels: Automation Hub, 2.5

#3503 Update troubleshooting section of Containerized installation to adhere to modular docs guidelines
  downstream/assemblies/platform/assembly-appendix-troubleshoot-containerized-aap.adoc
  downstream/modules/platform/proc-containerized-troubleshoot-gathering-logs.adoc
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/platform/ref-containerized-troubleshoot-config.adoc
  downstream/modules/platform/ref-containerized-troubleshoot-diagnosing.adoc
  downstream/modules/platform/ref-containerized-troubleshoot-install.adoc
  downstream/modules/platform/ref-containerized-troubleshoot-ref.adoc
Labels: 2.5, Needs backport to 2.5

#3504 2.5 Update troubleshooting section of Containerized installation to adhere to modular docs guidelines (#3503)
  downstream/assemblies/platform/assembly-appendix-troubleshoot-containerized-aap.adoc
  downstream/modules/platform/proc-containerized-troubleshoot-gathering-logs.adoc
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/platform/ref-containerized-troubleshoot-config.adoc
  downstream/modules/platform/ref-containerized-troubleshoot-diagnosing.adoc
  downstream/modules/platform/ref-containerized-troubleshoot-install.adoc
  downstream/modules/platform/ref-containerized-troubleshoot-ref.adoc
Labels: 2.5, Backported to 2.5

#3505 Fixing spacing in assemblies and ensuring parent context is present
  downstream/assemblies/platform/assembly-aap-migration.adoc
  downstream/assemblies/platform/assembly-appendix-operator-crs.adoc
  downstream/assemblies/platform/assembly-controller-resource-operator.adoc
  downstream/assemblies/platform/assembly-deploying-chatbot-operator.adoc
  downstream/assemblies/platform/assembly-installing-controller-operator.adoc
  downstream/assemblies/platform/assembly-installing-hub-operator.adoc
  downstream/assemblies/platform/assembly-operator-upgrade.adoc
  downstream/assemblies/platform/assembly-update-ocp.adoc
  downstream/modules/platform/proc-operator-create_crs.adoc
Labels: 2.5, AAP operator

#3506 Add spaces between module refs in troubleshooting assembly
  downstream/assemblies/platform/assembly-appendix-troubleshoot-containerized-aap.adoc
Labels: 2.5, Needs backport to 2.5

#3507 2.5 Add spaces between module refs in troubleshooting assembly (#3506)
  downstream/assemblies/platform/assembly-appendix-troubleshoot-containerized-aap.adoc
Labels: 2.5, Backported to 2.5

#3508 Fixing spacing in assemblies and ensuring parent context is present (…
  downstream/assemblies/platform/assembly-aap-migration.adoc
  downstream/assemblies/platform/assembly-appendix-operator-crs.adoc
  downstream/assemblies/platform/assembly-controller-resource-operator.adoc
  downstream/assemblies/platform/assembly-deploying-chatbot-operator.adoc
  downstream/assemblies/platform/assembly-installing-controller-operator.adoc
  downstream/assemblies/platform/assembly-installing-hub-operator.adoc
  downstream/assemblies/platform/assembly-operator-upgrade.adoc
  downstream/assemblies/platform/assembly-update-ocp.adoc
  downstream/modules/platform/proc-operator-create_crs.adoc
Labels: 2.5, AAP operator

#3492 Update CUG Ch1 for UI and modular compliance
  downstream/assemblies/platform/assembly-UG-overview.adoc
  downstream/modules/platform/con-controller-fips-support.adoc
  downstream/modules/platform/con-controller-overview-api.adoc
  downstream/modules/platform/con-controller-overview-auth-enhance.adoc
  downstream/modules/platform/con-controller-overview-automation.adoc
  downstream/modules/platform/con-controller-overview-backup-restore.adoc
  downstream/modules/platform/con-controller-overview-cloud-autoscaling.adoc
  downstream/modules/platform/con-controller-overview-cluster-manage.adoc
  downstream/modules/platform/con-controller-overview-details.adoc
  downstream/modules/platform/con-controller-overview-exploration.adoc
  downstream/modules/platform/con-controller-overview-galaxy.adoc
  downstream/modules/platform/con-controller-overview-host-limits.adoc
  downstream/modules/platform/con-controller-overview-integrations.adoc
  downstream/modules/platform/con-controller-overview-inventory-plugins.adoc
  downstream/modules/platform/con-controller-overview-job-distribution.adoc
  downstream/modules/platform/con-controller-overview-notifiers.adoc
  downstream/modules/platform/con-controller-overview-openstack.adoc
  downstream/modules/platform/con-controller-overview-rbac.adoc
  downstream/modules/platform/con-controller-overview-remote-exec.adoc
  downstream/modules/platform/con-controller-overview-secret-management.adoc
  downstream/modules/platform/con-controller-overview-tracking.adoc
  downstream/modules/platform/con-controller-overview-virtual-envs.adoc
  downstream/modules/platform/con-controller-overview-workflow-enhancements.adoc
Labels: documentation, Controller, 2.5, Needs backport to 2.5

#3509 Tidying up 2.4 assembly
  downstream/assemblies/platform/assembly-aap-migration.adoc
  downstream/assemblies/platform/assembly-controller-resource-operator.adoc
  downstream/assemblies/platform/assembly-deploy-eda-controller-on-aap-operator.adoc
  downstream/assemblies/platform/assembly-installing-hub-operator.adoc
  downstream/assemblies/platform/assembly-operator-install-planning.adoc
  downstream/assemblies/platform/assembly-operator-upgrade.adoc
  downstream/assemblies/platform/assembly-using-rhsso-operator-with-automation-hub.adoc
  downstream/titles/aap-operator-installation/master.adoc
Labels: 2.4, AAP operator

#3513 Update CUG Ch1 for UI and modular compliance (#3492)
  downstream/assemblies/platform/assembly-UG-overview.adoc
  downstream/modules/platform/con-controller-fips-support.adoc
  downstream/modules/platform/con-controller-overview-api.adoc
  downstream/modules/platform/con-controller-overview-auth-enhance.adoc
  downstream/modules/platform/con-controller-overview-automation.adoc
  downstream/modules/platform/con-controller-overview-backup-restore.adoc
  downstream/modules/platform/con-controller-overview-cloud-autoscaling.adoc
  downstream/modules/platform/con-controller-overview-cluster-manage.adoc
  downstream/modules/platform/con-controller-overview-details.adoc
  downstream/modules/platform/con-controller-overview-exploration.adoc
  downstream/modules/platform/con-controller-overview-galaxy.adoc
  downstream/modules/platform/con-controller-overview-host-limits.adoc
  downstream/modules/platform/con-controller-overview-integrations.adoc
  downstream/modules/platform/con-controller-overview-inventory-plugins.adoc
  downstream/modules/platform/con-controller-overview-job-distribution.adoc
  downstream/modules/platform/con-controller-overview-notifiers.adoc
  downstream/modules/platform/con-controller-overview-openstack.adoc
  downstream/modules/platform/con-controller-overview-rbac.adoc
  downstream/modules/platform/con-controller-overview-remote-exec.adoc
  downstream/modules/platform/con-controller-overview-secret-management.adoc
  downstream/modules/platform/con-controller-overview-tracking.adoc
  downstream/modules/platform/con-controller-overview-virtual-envs.adoc
  downstream/modules/platform/con-controller-overview-workflow-enhancements.adoc
Labels: documentation, Controller, 2.5, Backported to 2.5

#3512 Azure mod doc checklist review
  stories/assembly-azure-connecting-to-aap.adoc
  stories/assembly-azure-deploy.adoc
  stories/assembly-azure-install-prerequisites.adoc
  stories/assembly-azure-intro.adoc
  stories/assembly-azure-post-deployment-requirements.adoc
  titles/aap-on-azure/stories.adoc
Labels: AAP on clouds, AAP on Azure

#3518 Update system requirements for Containerized installation (#3493)
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/platform/proc-backup-aap-container.adoc
  downstream/modules/platform/proc-downloading-containerized-aap.adoc
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/platform/proc-preparing-the-managed-nodes-for-containerized-installation.adoc
  downstream/modules/platform/proc-restore-aap-container.adoc
  downstream/modules/platform/proc-uninstalling-containerized-aap.adoc
  downstream/modules/platform/proc-update-aap-container.adoc
  downstream/modules/platform/ref-configuring-inventory-file.adoc
  downstream/modules/platform/ref-cont-aap-system-requirements.adoc
  downstream/modules/platform/ref-containerized-system-requirements.adoc
Labels: 2.5, Backported to 2.5

#3519 correct broken xref
  downstream/modules/platform/proc-update-aap-container.adoc
Labels: 2.5, Needs backport to 2.5

#3521 Update inventory file vars appendix for mod docs
  downstream/assemblies/platform/assembly-appendix-inventory-file-vars.adoc
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
  downstream/modules/eda/ref-installing-eda-controller-on-aap.adoc
  downstream/modules/hub/ref-variables-connect-hub-sso.adoc
  downstream/modules/platform/con-aap-installation-on-disconnected-rhel.adoc
  downstream/modules/platform/con-controller-additional-settings.adoc
  downstream/modules/platform/proc-change-ssl-installer.adoc
  downstream/modules/platform/ref-ansible-inventory-variables.adoc
  downstream/modules/platform/ref-controller-variables.adoc
  downstream/modules/platform/ref-database-inventory-variables.adoc
  downstream/modules/platform/ref-eda-controller-variables.adoc
  downstream/modules/platform/ref-gateway-controller-hub-eda-ext-db.adoc
  downstream/modules/platform/ref-gateway-variables.adoc
  downstream/modules/platform/ref-general-inventory-variables.adoc
  downstream/modules/platform/ref-hub-variables.adoc
  downstream/modules/platform/ref-images-inventory-variables.adoc
  downstream/modules/platform/ref-receptor-inventory-variables.adoc
  downstream/modules/platform/ref-redis-inventory-variables.adoc
  downstream/snippets/inventory-cont-a-env-a.adoc
  downstream/snippets/inventory-cont-b-env-a.adoc
  downstream/snippets/inventory-rpm-a-env-a.adoc
  downstream/snippets/inventory-rpm-a-env-b.adoc
  downstream/snippets/inventory-rpm-b-env-a.adoc
  downstream/snippets/inventory-rpm-b-env-b.adoc
Labels: 2.5, Needs backport to 2.5

#3522 2.5 Update inventory file vars appendix for mod docs (#3521)
  downstream/assemblies/platform/assembly-appendix-inventory-file-vars.adoc
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
  downstream/modules/eda/ref-installing-eda-controller-on-aap.adoc
  downstream/modules/hub/ref-variables-connect-hub-sso.adoc
  downstream/modules/platform/con-aap-installation-on-disconnected-rhel.adoc
  downstream/modules/platform/con-controller-additional-settings.adoc
  downstream/modules/platform/proc-change-ssl-installer.adoc
  downstream/modules/platform/ref-ansible-inventory-variables.adoc
  downstream/modules/platform/ref-controller-variables.adoc
  downstream/modules/platform/ref-database-inventory-variables.adoc
  downstream/modules/platform/ref-eda-controller-variables.adoc
  downstream/modules/platform/ref-gateway-controller-hub-eda-ext-db.adoc
  downstream/modules/platform/ref-gateway-variables.adoc
  downstream/modules/platform/ref-general-inventory-variables.adoc
  downstream/modules/platform/ref-hub-variables.adoc
  downstream/modules/platform/ref-images-inventory-variables.adoc
  downstream/modules/platform/ref-receptor-inventory-variables.adoc
  downstream/modules/platform/ref-redis-inventory-variables.adoc
  downstream/snippets/inventory-cont-a-env-a.adoc
  downstream/snippets/inventory-cont-b-env-a.adoc
  downstream/snippets/inventory-rpm-a-env-a.adoc
  downstream/snippets/inventory-rpm-a-env-b.adoc
  downstream/snippets/inventory-rpm-b-env-a.adoc
  downstream/snippets/inventory-rpm-b-env-b.adoc
Labels: 2.5, Backported to 2.5

#3523 Update Ch 6 Job Templates for UI and migration (#3510)
  downstream/assemblies/platform/assembly-ug-controller-job-templates.adoc
  downstream/modules/platform/con-controller-surveys.adoc
  downstream/modules/platform/proc-controller-adding-permissions.adoc
  downstream/modules/platform/proc-controller-create-job-template.adoc
  downstream/modules/platform/proc-controller-delete-job-template.adoc
  downstream/modules/platform/proc-controller-launch-job-template.adoc
  downstream/modules/platform/ref-controller-intro-job-template.adoc
  downstream/modules/platform/ref-controller-job-template-variables.adoc
Labels: documentation, Controller, 2.5, Backported to 2.5

#3517 AAP-46197: improves table formatting for readability
  downstream/modules/platform/ref-pac-inputs-outputs.adoc
Labels: Controller, 2.5, Needs backport to 2.5

#3515 Modularizing chapter 8 of controller user guide
  downstream/assemblies/platform/assembly-ug-controller-workflow-job-templates.adoc
  downstream/modules/platform/con-controller-work-with-permissions.adoc
  downstream/modules/platform/con-controller-workflow-notifications.adoc
  downstream/modules/platform/proc-controller-build-workflow.adoc
  downstream/modules/platform/proc-controller-copy-workflow-job-template.adoc
  downstream/modules/platform/proc-controller-create-workflow-template.adoc
Labels: documentation, Controller, 2.5, Needs backport to 2.5

#3524 Modularizing chapter 8 of controller user guide (#3515)
  downstream/assemblies/platform/assembly-ug-controller-workflow-job-templates.adoc
  downstream/modules/platform/con-controller-work-with-permissions.adoc
  downstream/modules/platform/con-controller-workflow-notifications.adoc
  downstream/modules/platform/proc-controller-build-workflow.adoc
  downstream/modules/platform/proc-controller-copy-workflow-job-template.adoc
  downstream/modules/platform/proc-controller-create-workflow-template.adoc
Labels: documentation, Controller, 2.5, Backported to 2.5

#3525 Backport to 2.5: AAP-46197: Updates table formatting for readability
  downstream/modules/platform/ref-pac-inputs-outputs.adoc
Labels: Controller, 2.5

#3526 Modularizing chapter 9 of controller user guide
  downstream/assemblies/platform/assembly-ug-controller-workflows.adoc
  downstream/modules/platform/con-controller-role-based-access-controls.adoc
  downstream/modules/platform/ref-controller-intro-job-template.adoc
  downstream/modules/platform/ref-controller-workflows-extra-variables.adoc
Labels: documentation, Controller, 2.5, Needs backport to 2.5

#3527 AAP-45761: Added docs and attributes for Azure OpenAI support
  downstream/assemblies/platform/assembly-deploying-chatbot-operator.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/platform/con-about-lightspeed-intelligent-assistant.adoc
  downstream/modules/platform/proc-create-chatbot-config-secret.adoc
Labels: Technical review complete, 2.5, Needs backport to 2.5

#3531 Update assembly-aap-containerized-installation to follow mod docs gui…
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/hub/proc-deploying-your-system-for-container-signing.adoc
  downstream/modules/platform/proc-backup-aap-container.adoc
  downstream/modules/platform/proc-cont-aap-hub-storage.adoc
  downstream/modules/platform/proc-enabling-automation-hub-collection-and-container-signing.adoc
  downstream/modules/platform/proc-restore-aap-container.adoc
  downstream/modules/platform/proc-uninstalling-containerized-aap.adoc
  downstream/modules/platform/proc-update-aap-container.adoc
  downstream/modules/platform/ref-adding-execution-nodes.adoc
  downstream/modules/platform/ref-cont-aap-system-requirements.adoc
  downstream/modules/platform/ref-eda-controller-variables.adoc
  downstream/modules/platform/ref-general-inventory-variables.adoc
  downstream/modules/platform/ref-receptor-inventory-variables.adoc
Labels: 2.5, Needs backport to 2.5

#3532 2.5 Update assembly-aap-containerized-installation to follow mod docs gui…
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/hub/proc-deploying-your-system-for-container-signing.adoc
  downstream/modules/platform/proc-backup-aap-container.adoc
  downstream/modules/platform/proc-cont-aap-hub-storage.adoc
  downstream/modules/platform/proc-enabling-automation-hub-collection-and-container-signing.adoc
  downstream/modules/platform/proc-restore-aap-container.adoc
  downstream/modules/platform/proc-uninstalling-containerized-aap.adoc
  downstream/modules/platform/proc-update-aap-container.adoc
  downstream/modules/platform/ref-adding-execution-nodes.adoc
  downstream/modules/platform/ref-cont-aap-system-requirements.adoc
  downstream/modules/platform/ref-eda-controller-variables.adoc
  downstream/modules/platform/ref-general-inventory-variables.adoc
  downstream/modules/platform/ref-receptor-inventory-variables.adoc
Labels: 2.5, Backported to 2.5

#3534 2.5 Mod docs review of Tested deployment models (#3533)
  downstream/assemblies/topologies/assembly-container-topologies.adoc
  downstream/assemblies/topologies/assembly-ocp-topologies.adoc
  downstream/assemblies/topologies/assembly-overview-tested-deployment-models.adoc
  downstream/assemblies/topologies/assembly-rpm-topologies.adoc
  downstream/modules/topologies/ref-installation-deployment-models.adoc
  downstream/modules/topologies/ref-mesh-nodes.adoc
  downstream/modules/topologies/ref-rpm-a-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-b.adoc
Labels: 2.5, Backported to 2.5

#3536 Modularizing chapter 10 of controller user guide (#3535)
  downstream/assemblies/platform/assembly-ug-controller-schedules.adoc
  downstream/modules/platform/proc-controller-add-new-schedule-from-resource.adoc
  downstream/modules/platform/proc-controller-adding-new-schedule.adoc
  downstream/modules/platform/proc-controller-define-schedule-exceptions.adoc
  downstream/modules/platform/proc-controller-define-schedule-rules.adoc
Labels: documentation, Controller, 2.5, Backported to 2.5

#3537 Mod docs update for assembly-horizontal-scaling.adoc
  downstream/assemblies/platform/assembly-horizontal-scaling.adoc
  downstream/modules/platform/con-hs-eda-controller.adoc
  downstream/modules/platform/proc-hs-eda-setup.adoc
  downstream/titles/aap-containerized-install/master.adoc
Labels: 2.5, Needs backport to 2.5

#3540 Modularizing chapter 11 of controller user guide (#3539)
  downstream/assemblies/platform/assembly-controller-projects.adoc
  downstream/modules/platform/proc-controller-adding-a-project.adoc
  downstream/modules/platform/proc-controller-updating-a-project.adoc
  downstream/modules/platform/proc-projects-manage-playbooks-manually.adoc
  downstream/modules/platform/proc-scm-git-subversion.adoc
  downstream/modules/platform/proc-scm-insights.adoc
  downstream/modules/platform/ref-projects-collections-support.adoc
  downstream/modules/platform/ref-projects-galaxy-support.adoc
  downstream/modules/platform/ref-projects-manage-playbooks-with-source-control.adoc
  downstream/modules/platform/ref-work-with-permissions.adoc
Labels: 2.5, Backported to 2.5

#3541 Re-adding the LDAP case sensitivity details for publication 5/28
  downstream/modules/platform/proc-controller-set-up-LDAP.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#3546 [Backport] AAP-42977 - Add service account details to Settings and Subscriptions content (#3545)
  downstream/assemblies/platform/assembly-aap-activate.adoc
  downstream/modules/platform/proc-aap-activate-with-credentials.adoc
  downstream/modules/platform/proc-controller-configure-subscriptions.adoc
Labels: Ready for review, 2.5

#3354 AAP-44919: updates procedure for finding your subscription
  downstream/modules/platform/proc-gs-logging-in.adoc
Labels: 2.5

#3530 AAP-45411: adds module on deleting collections
  downstream/assemblies/hub/assembly-working-with-namespaces.adoc
  downstream/modules/hub/proc-delete-collection.adoc
Labels: Automation Hub, 2.5

#3549 bp to 2.5: AAP-45411: adds module on deleting collections (#3530)
  downstream/assemblies/hub/assembly-working-with-namespaces.adoc
  downstream/modules/hub/proc-delete-collection.adoc
Labels: 2.5

#3548 AAP-44816 Add Advanced configurations chapter, including settings.py & grpc_settings.py
  downstream/assemblies/platform/assembly-aap-advanced-config.adoc
  downstream/modules/platform/con-grpc-settings-py.adoc
  downstream/modules/platform/con-loading-impacts-grpc-settings.adoc
  downstream/modules/platform/con-loading-order-grpc-settings.adoc
  downstream/modules/platform/con-settings-py.adoc
  downstream/titles/aap-operations-guide/master.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#3552 [Backport] AAP-44816 Add Advanced configurations chapter, including settings.py & grpc_settings.py (#3548)
  downstream/assemblies/platform/assembly-aap-advanced-config.adoc
  downstream/modules/platform/con-grpc-settings-py.adoc
  downstream/modules/platform/con-loading-impacts-grpc-settings.adoc
  downstream/modules/platform/con-loading-order-grpc-settings.adoc
  downstream/modules/platform/con-settings-py.adoc
  downstream/titles/aap-operations-guide/master.adoc
Labels: Ready for review, 2.5

#3555 Check and prepare Ch7 for migration (#3553)
  downstream/assemblies/platform/assembly-ug-controller-job-slicing.adoc
  downstream/images/ug-sliced-job-shown-jobs-list-view.png
  downstream/modules/platform/con-controller-job-slice-considerations.adoc
  downstream/modules/platform/ref-controller-job-slice-execution-behavior.adoc
Labels: documentation, Controller, 2.5, Backported to 2.5

#3560 Update and prepare CH12 for migration (#3557)
  downstream/assemblies/platform/assembly-controller-project-signing.adoc
  downstream/images/project-update-launch-cache-timeout.png
  downstream/modules/platform/proc-controller-adding-gpg-key.adoc
  downstream/modules/platform/ref-controller-intro-proj-sign.adoc
  downstream/modules/platform/ref-controller-proj-sign-prerequisites.adoc
Labels: documentation, Controller, 2.5, Backported to 2.5, Needs backport to 2.5

#3564 Updating controller link in 2.4 planning guide
  downstream/modules/platform/ref-postgresql-requirements.adoc
Labels: documentation, 2.4

#3572 AAP-45761-update: Corrected a formatting error
  downstream/modules/platform/con-about-lightspeed-intelligent-assistant.adoc
Labels: 2.5, Needs backport to 2.5

#3573 Backport PR #3572 from main branch to AAP 2.5 branch
  downstream/modules/platform/con-about-lightspeed-intelligent-assistant.adoc
Labels: 2.5, Backported to 2.5

#3581 2.5 Add assembly-gateway-licensing.adoc to Containerized installation gui…
  downstream/titles/aap-containerized-install/master.adoc
Labels: 2.5, Backported to 2.5

#3574 AAP-43213: AAP-43213: Added info. about hybrid deployment model
  lightspeed/assemblies/assembly_configuring-lightspeed-onpremise.adoc
  lightspeed/modules/con_overview-lightspeed-onpremise.adoc
  lightspeed/modules/proc_create-connection-secrets.adoc
  lightspeed/titles/lightspeed-release-notes/master.adoc
  lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-11dec2024.adoc
  lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-20march2025.adoc
  lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-28april2025.adoc
  lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-29may2025.adoc
  lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-august2024.adoc
Labels: Lightspeed

#3575 AAP-44919: updates subscription procedure
  downstream/assemblies/platform/assembly-gs-platform-admin.adoc
  downstream/modules/platform/proc-adding-a-subscription.adoc
  downstream/modules/platform/proc-gs-logging-in.adoc
Labels: Not ready for peer review, 2.5, Needs backport to 2.5

#3586 backport to 2.5: AAP-44919: updates subscription procedure (#3575)
  downstream/assemblies/platform/assembly-gs-platform-admin.adoc
  downstream/modules/platform/proc-adding-a-subscription.adoc
  downstream/modules/platform/proc-gs-logging-in.adoc
Labels: 2.5

#3589 Adding License assembly to OCP
  downstream/titles/aap-operator-installation/master.adoc
Labels: documentation, 2.5, Delay backport, AAP operator

#3590 Adding License assembly to OCP (#3589)
  downstream/titles/aap-operator-installation/master.adoc
Labels: 2.5

#3592 bp to 2.5: AAP-44919: fixes formatting error (#3591)
  downstream/modules/platform/proc-adding-a-subscription.adoc
Labels: 2.5

#3595 AAP-43751 - Add changes for token expiration change
  downstream/assemblies/platform/assembly-gw-token-based-authentication.adoc
  downstream/modules/platform/ref-gw-request-token-after-expiration.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5
