Repository ansible/aap-docs, pull requests merged in 2025-07, with the labels that each got.

#3754 2.5 Update CONT RHEL requirements (#3746)
  downstream/snippets/cont-tested-system-config.adoc
  downstream/titles/release-notes/async/aap-25-20250702.adoc
Labels: 2.5, Backported to 2.5

#3757 DITA migration changes for CUG CH 21
  downstream/assemblies/platform/assembly-controller-ee-setup-reference.adoc
  downstream/modules/platform/ref-controller-ee-configuration-options.adoc
Labels: documentation, Controller, 2.5, Needs backport to 2.5, Migration

#3758 DITA migration changes for CUG CH 21 (#3757)
  downstream/assemblies/platform/assembly-controller-ee-setup-reference.adoc
  downstream/modules/platform/ref-controller-ee-configuration-options.adoc
Labels: documentation, Controller, 2.5, Backported to 2.5, Migration

#3760 bp to 2.5: AAP-45907: removes mentions of feature flag from PaC docs (#3654)
  downstream/assemblies/platform/assembly-controller-pac.adoc
Labels: Controller, 2.5

#3761 Updating Note about Microsoft Entra IDs
  downstream/modules/platform/proc-controller-set-up-azure.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#3764 Documentation incorrectly states using unique IDs is mandatory for Mi…
  downstream/modules/platform/proc-controller-set-up-azure.adoc
Labels: 2.5, Needs backport to 2.5

#3765 Documentation incorrectly states using unique IDs is mandatory for Mi…
  downstream/modules/platform/proc-controller-set-up-azure.adoc
Labels: 2.5, Backported to 2.5

#3775 2.5 update broken link (#3773)
  downstream/assemblies/aap-migration/assembly-source-containerized.adoc
  downstream/assemblies/aap-migration/assembly-source-rpm.adoc
Labels: 2.5, Backported to 2.5

#3774 Improving RHEM install and CLI steps
  downstream/assemblies/platform/assembly-edge-manager-images.adoc
  downstream/assemblies/platform/assembly-edge-manager-install.adoc
  downstream/modules/platform/con-edge-manager-os-img-script.adoc
  downstream/modules/platform/proc-edge-manager-image-build.adoc
  downstream/modules/platform/proc-edge-manager-install-CLI.adoc
  downstream/modules/platform/proc-edge-manager-install-rpm-package.adoc
  downstream/modules/platform/proc-edge-manager-integrate-aap.adoc
  downstream/modules/platform/proc-edge-manager-log-into-CLI.adoc
  downstream/modules/platform/proc-edge-manager-oauth-auto.adoc
  downstream/modules/platform/proc-edge-manager-oauth-manually.adoc
  downstream/modules/platform/proc-edge-manager-request-cert.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#3776 Improving RHEM install and CLI steps (#3774)
  downstream/assemblies/platform/assembly-edge-manager-images.adoc
  downstream/assemblies/platform/assembly-edge-manager-install.adoc
  downstream/modules/platform/con-edge-manager-os-img-script.adoc
  downstream/modules/platform/proc-edge-manager-image-build.adoc
  downstream/modules/platform/proc-edge-manager-install-CLI.adoc
  downstream/modules/platform/proc-edge-manager-install-rpm-package.adoc
  downstream/modules/platform/proc-edge-manager-integrate-aap.adoc
  downstream/modules/platform/proc-edge-manager-log-into-CLI.adoc
  downstream/modules/platform/proc-edge-manager-oauth-auto.adoc
  downstream/modules/platform/proc-edge-manager-oauth-manually.adoc
  downstream/modules/platform/proc-edge-manager-request-cert.adoc
Labels: documentation, 2.5, Backported to 2.5

#3367 AAP-44664 edits
  downstream/modules/platform/proc-operator-scaling-down-aap.adoc
  downstream/titles/aap-operator-installation/master.adoc
Labels: documentation, 2.5, AAP operator

#3777 AAP-44664 edits (#3367)
  downstream/modules/platform/proc-operator-scaling-down-aap.adoc
  downstream/titles/aap-operator-installation/master.adoc
Labels: 2.5

#3778 Modularizing chapter 24 of controller user guide
  downstream/assemblies/platform/assembly-controller-activity-stream.adoc
Labels: documentation, Controller, 2.5, Needs backport to 2.5

#3780 Archive RPM-ENV-B topology content
  downstream/archive/archived-images/rpm-a-env-b.png
  downstream/archive/archived-images/rpm-b-env-b.png
  downstream/archive/archived-modules/topologies/ref-rpm-a-env-b.adoc
  downstream/archive/archived-modules/topologies/ref-rpm-b-env-b.adoc
  downstream/archive/archived-snippets/inventory-rpm-a-env-b.adoc
  downstream/archive/archived-snippets/inventory-rpm-b-env-b.adoc
  downstream/archive/archived-snippets/mixed-topologies.adoc
  downstream/archive/archived-snippets/rpm-env-b-tested-system-config.adoc
  downstream/assemblies/topologies/assembly-rpm-topologies.adoc
  downstream/modules/topologies/ref-installation-deployment-models.adoc
  downstream/titles/release-notes/topics/aap-25.adoc
Labels: 2.5, Needs backport to 2.5

#3781 2.5 Archive RPM-ENV-B topology content (#3780)
  downstream/archive/archived-images/rpm-a-env-b.png
  downstream/archive/archived-images/rpm-b-env-b.png
  downstream/archive/archived-modules/topologies/ref-rpm-a-env-b.adoc
  downstream/archive/archived-modules/topologies/ref-rpm-b-env-b.adoc
  downstream/archive/archived-snippets/inventory-rpm-a-env-b.adoc
  downstream/archive/archived-snippets/inventory-rpm-b-env-b.adoc
  downstream/archive/archived-snippets/mixed-topologies.adoc
  downstream/archive/archived-snippets/rpm-env-b-tested-system-config.adoc
  downstream/assemblies/topologies/assembly-rpm-topologies.adoc
  downstream/modules/topologies/ref-installation-deployment-models.adoc
  downstream/titles/release-notes/topics/aap-25.adoc
Labels: 2.5, Backported to 2.5

#3788 Backport-2.5-3722 to AAP-46213 Modularization & migration prep
  downstream/assemblies/eda/assembly-eda-credentials.adoc
  downstream/modules/eda/con-credentials-list-view.adoc
  downstream/modules/eda/proc-eda-delete-credential.adoc
  downstream/modules/eda/proc-eda-duplicate-credential.adoc
  downstream/modules/eda/proc-eda-edit-credential.adoc
  downstream/modules/eda/proc-eda-set-up-credential.adoc
Labels: documentation, Ready for review, 2.5, Migration

#3789 Backport-2.5-3733 to AAP-46216 Modularization & migration prep
  downstream/assemblies/eda/assembly-eda-credential-types.adoc
  downstream/modules/eda/con-credential-types-injector-config.adoc
  downstream/modules/eda/con-credential-types-input-config.adoc
  downstream/modules/eda/con-custom-credential-types.adoc
  downstream/modules/eda/proc-eda-set-up-credential-types.adoc
Labels: documentation, Ready for review, 2.5, Migration

#3786 AAP-49075: Dita premigration edits for RPM install and upgrade guides…
  downstream/assemblies/platform/assembly-aap-upgrading-platform.adoc
  downstream/assemblies/platform/assembly-system-requirements.adoc
  downstream/modules/platform/proc-choosing-obtaining-installer-no-internet.adoc
  downstream/modules/platform/proc-choosing-obtaining-installer.adoc
  downstream/modules/platform/proc-postgresql-enable-mtls-authentication.adoc
  downstream/modules/platform/proc-postgresql-use-custom-certificates.adoc
  downstream/modules/platform/proc-setup-postgresql-ext-database.adoc
Labels: 2.5, Needs backport to 2.5

#3790 Backport PR #3786 from main branch to AAP 2.5 branch
  downstream/assemblies/platform/assembly-aap-upgrading-platform.adoc
  downstream/assemblies/platform/assembly-system-requirements.adoc
  downstream/modules/platform/proc-choosing-obtaining-installer-no-internet.adoc
  downstream/modules/platform/proc-choosing-obtaining-installer.adoc
  downstream/modules/platform/proc-postgresql-enable-mtls-authentication.adoc
  downstream/modules/platform/proc-postgresql-use-custom-certificates.adoc
  downstream/modules/platform/proc-setup-postgresql-ext-database.adoc
Labels: 2.5, Backported to 2.5

#3791 AAP-48159: adds content type statement to procedure modules
  downstream/modules/hub/proc-add-container-readme.adoc
  downstream/modules/hub/proc-add-group-to-container-repo.adoc
  downstream/modules/hub/proc-adding-an-execution-environment.adoc
  downstream/modules/hub/proc-adding-collections-repository.adoc
  downstream/modules/hub/proc-adding-containers-remotely-to-the-automation-hub.adoc
  downstream/modules/hub/proc-approve-collection.adoc
  downstream/modules/hub/proc-basic-repo-sync.adoc
  downstream/modules/hub/proc-configure-ansible-galaxy-cli-verify.adoc
  downstream/modules/hub/proc-configure-content-signing-on-pah.adoc
  downstream/modules/hub/proc-configuring-the-client-to-verify-signatures.adoc
  downstream/modules/hub/proc-create-api-token-pah.adoc
  downstream/modules/hub/proc-create-api-token.adoc
  downstream/modules/hub/proc-create-content-developers.adoc
  downstream/modules/hub/proc-create-credential.adoc
  downstream/modules/hub/proc-create-namespace.adoc
  downstream/modules/hub/proc-create-remote.adoc
  downstream/modules/hub/proc-create-repository.adoc
  downstream/modules/hub/proc-create-synclist.adoc
  downstream/modules/hub/proc-delete-collection.adoc
  downstream/modules/hub/proc-delete-namespace.adoc
  downstream/modules/hub/proc-deploying-your-system-for-container-signing.adoc
  downstream/modules/hub/proc-downloading-signature-public-keys.adoc
  downstream/modules/hub/proc-edit-namespace.adoc
  downstream/modules/hub/proc-export-collection.adoc
  downstream/modules/hub/proc-import-collection.adoc
  downstream/modules/hub/proc-obtain-images.adoc
  downstream/modules/hub/proc-provide-remote-access.adoc
  downstream/modules/hub/proc-provide-repository-access.adoc
  downstream/modules/hub/proc-pull-image.adoc
  downstream/modules/hub/proc-push-container.adoc
  downstream/modules/hub/proc-pushing-container-images-from-your-local.adoc
  downstream/modules/hub/proc-reject-collections.adoc
  downstream/modules/hub/proc-revert-repository-version.adoc
  downstream/modules/hub/proc-review-collection-imports.adoc
  downstream/modules/hub/proc-set-community-remote.adoc
  downstream/modules/hub/proc-set-rhcertified-remote.adoc
  downstream/modules/hub/proc-tag-image.adoc
  downstream/modules/hub/proc-tag-pulled-image.adoc
  downstream/modules/hub/proc-uploading-collections.adoc
  downstream/modules/hub/proc-using-content-signing-services-in-pah.adoc
  downstream/modules/hub/proc-using-podman-ensure-image-signed.adoc
  downstream/modules/hub/proc-using-policies-with-signed-images.adoc
  downstream/modules/hub/ref-container-permissions.adoc
Labels: Automation Hub, 2.5, Migration

#3795 Editing controller files for DITA (#3794)
  downstream/assemblies/platform/assembly-ug-controller-notifications.adoc
  downstream/modules/platform/con-controller-configure-hostname-notifications.adoc
  downstream/modules/platform/con-controller-enable-notifications.adoc
  downstream/modules/platform/con-controller-notification-hierarchy.adoc
  downstream/modules/platform/con-controller-notification-types.adoc
  downstream/modules/platform/con-controller-notification-workflow.adoc
  downstream/modules/platform/proc-controller-create-custom-notifications.adoc
  downstream/modules/platform/proc-controller-create-notification-template.adoc
  downstream/modules/platform/proc-controller-reset-tower-base.adoc
  downstream/modules/platform/ref-controller-notification-email.adoc
  downstream/modules/platform/ref-controller-notification-grafana.adoc
  downstream/modules/platform/ref-controller-notification-irc.adoc
  downstream/modules/platform/ref-controller-notification-mattermost.adoc
  downstream/modules/platform/ref-controller-notification-rocketchat.adoc
  downstream/modules/platform/ref-controller-notification-slack.adoc
  downstream/modules/platform/ref-controller-notification-twilio.adoc
  downstream/modules/platform/ref-controller-notification-webhook-payloads.adoc
  downstream/modules/platform/ref-controller-notification-webhook.adoc
  downstream/modules/platform/ref-controller-notifications-api.adoc
Labels: documentation, Controller, 2.5, Backported to 2.5

#3800 AAP-48159: DITA updates: fixes heading issue
  downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc
  downstream/modules/hub/proc-basic-repo-sync.adoc
  downstream/modules/hub/proc-create-api-token-pah.adoc
  downstream/modules/hub/proc-create-api-token.adoc
  downstream/modules/hub/proc-obtain-images.adoc
  downstream/modules/hub/proc-offline-token-active.adoc
Labels: Automation Hub, 2.5, Migration

#3802 Remove unnecessary parameter
  downstream/modules/platform/ref-controller-analytics-gathering.adoc
Labels: documentation, Controller, 2.5, Needs backport to 2.5

#3804 Remove unnecessary parameter (#3802)
  downstream/modules/platform/ref-controller-analytics-gathering.adoc
Labels: documentation, Controller, 2.5, Backported to 2.5

#3806 Editing controller files for DITA
  downstream/assemblies/platform/assembly-ug-controller-attributes-custom-notifications.adoc
  downstream/modules/platform/ref-controller-supported-attributes.adoc
Labels: documentation, Controller, 2.5, Needs backport to 2.5

#3807 Editing controller files for DITA (#3806)
  downstream/assemblies/platform/assembly-ug-controller-attributes-custom-notifications.adoc
  downstream/modules/platform/ref-controller-supported-attributes.adoc
Labels: documentation, 2.5, Backported to 2.5

#3809 AAP-48519: fixes backporting mistake
  downstream/modules/hub/proc-create-api-token.adoc
Labels: Migration

#3811 Editing controller files for DITA
  downstream/assemblies/platform/assembly-ug-controller-work-with-webhooks.adoc
  downstream/modules/platform/proc-controller-set-up-github-webhook.adoc
  downstream/modules/platform/proc-controller-set-up-gitlab-webhook.adoc
  downstream/modules/platform/proc-controller-view-payload-output.adoc
Labels: documentation, Controller, 2.5, Needs backport to 2.5

#3810 AAP-34014-remove: Removed doc update for model anonymization functionality
  lightspeed/modules/proc_create-connection-secrets.adoc
  lightspeed/titles/lightspeed-release-notes/modules/ref-release-notes.adoc
Labels: Lightspeed

#3814 Removing outdated CRs (#3813)
  downstream/modules/platform/ref-operator-crs.adoc
Labels: 2.5

#3815 AAP-48959: Removed Matrix feedback note from Lightspeed docs
  lightspeed/modules/proc_provide-feedback.adoc
Labels: Ready for review, Lightspeed

#3830 Updating migration section as per AAP-49300
  downstream/assemblies/platform/assembly-aap-migration.adoc
Labels: documentation, 2.5, AAP operator, Needs backport to 2.5

#3831 Updating migration section as per AAP-49300 (#3830)
  downstream/assemblies/platform/assembly-aap-migration.adoc
Labels: 2.5, AAP operator

#3818 Ansible DITA readiness
  downstream/assemblies/platform/assembly-appendix-troubleshoot-rpm-aap.adoc
  downstream/assemblies/troubleshooting-aap/assembly-diagnosing-the-problem.adoc
  downstream/assemblies/troubleshooting-aap/assembly-troubleshoot-jobs.adoc
  downstream/modules/aap-migration/proc-ocp-target-import.adoc
  downstream/modules/platform/con-certs-per-service-considerations.adoc
  downstream/modules/platform/con-hs-eda-controller.adoc
  downstream/modules/platform/con-hs-eda-sizing-scaling.adoc
  downstream/modules/platform/proc-backup-aap-container.adoc
  downstream/modules/platform/proc-configure-hub-azure-storage.adoc
  downstream/modules/platform/proc-configure-hub-s3-storage.adoc
  downstream/modules/platform/proc-containerized-troubleshoot-gathering-logs.adoc
  downstream/modules/platform/proc-downloading-containerized-aap.adoc
  downstream/modules/platform/proc-enabling-automation-hub-collection-and-container-signing.adoc
  downstream/modules/platform/proc-hs-eda-setup.adoc
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/platform/proc-preparing-the-managed-nodes-for-containerized-installation.adoc
  downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc
  downstream/modules/platform/proc-rpm-troubleshoot-generating-logs.adoc
  downstream/modules/platform/proc-uninstalling-containerized-aap.adoc
  downstream/modules/platform/proc-update-aap-container.adoc
  downstream/modules/platform/ref-configuring-inventory-file.adoc
  downstream/modules/platform/ref-containerized-troubleshoot-ref.adoc
  downstream/modules/platform/ref-database-inventory-variables.adoc
  downstream/modules/platform/ref-hub-variables.adoc
  downstream/modules/platform/ref-receptor-inventory-variables.adoc
  downstream/modules/troubleshooting-aap/proc-troubleshoot-job-permissions.adoc
  downstream/modules/troubleshooting-aap/proc-troubleshoot-job-resolve-module.adoc
  downstream/modules/troubleshooting-aap/proc-troubleshoot-job-timeout.adoc
  downstream/modules/troubleshooting-aap/proc-troubleshoot-must-gather.adoc
Labels: 2.5, Needs backport to 2.5

#3832 2.5 Ansible DITA readiness (#3818)
  downstream/assemblies/platform/assembly-appendix-troubleshoot-rpm-aap.adoc
  downstream/assemblies/troubleshooting-aap/assembly-diagnosing-the-problem.adoc
  downstream/assemblies/troubleshooting-aap/assembly-troubleshoot-jobs.adoc
  downstream/modules/aap-migration/proc-ocp-target-import.adoc
  downstream/modules/platform/con-certs-per-service-considerations.adoc
  downstream/modules/platform/con-hs-eda-controller.adoc
  downstream/modules/platform/con-hs-eda-sizing-scaling.adoc
  downstream/modules/platform/proc-backup-aap-container.adoc
  downstream/modules/platform/proc-configure-hub-azure-storage.adoc
  downstream/modules/platform/proc-configure-hub-s3-storage.adoc
  downstream/modules/platform/proc-containerized-troubleshoot-gathering-logs.adoc
  downstream/modules/platform/proc-downloading-containerized-aap.adoc
  downstream/modules/platform/proc-enabling-automation-hub-collection-and-container-signing.adoc
  downstream/modules/platform/proc-hs-eda-setup.adoc
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/platform/proc-preparing-the-managed-nodes-for-containerized-installation.adoc
  downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc
  downstream/modules/platform/proc-rpm-troubleshoot-generating-logs.adoc
  downstream/modules/platform/proc-uninstalling-containerized-aap.adoc
  downstream/modules/platform/proc-update-aap-container.adoc
  downstream/modules/platform/ref-configuring-inventory-file.adoc
  downstream/modules/platform/ref-containerized-troubleshoot-ref.adoc
  downstream/modules/platform/ref-database-inventory-variables.adoc
  downstream/modules/platform/ref-hub-variables.adoc
  downstream/modules/platform/ref-receptor-inventory-variables.adoc
  downstream/modules/troubleshooting-aap/proc-troubleshoot-job-permissions.adoc
  downstream/modules/troubleshooting-aap/proc-troubleshoot-job-resolve-module.adoc
  downstream/modules/troubleshooting-aap/proc-troubleshoot-job-timeout.adoc
  downstream/modules/troubleshooting-aap/proc-troubleshoot-must-gather.adoc
Labels: 2.5, Backported to 2.5, Migration

#3834 Add client_request_timeout to inventory vars
  downstream/modules/platform/ref-general-inventory-variables.adoc
Labels: 2.5, Needs backport to 2.5

#3825 AAP-47376: Creating new guide and content for Terraform and AAP integration.
  downstream/aap-common/aap-common
  downstream/assemblies/terraform-aap/assembly-terraform-integrating-from-aap.adoc
  downstream/assemblies/terraform-aap/assembly-terraform-integrating-from-terraform.adoc
  downstream/assemblies/terraform-aap/assembly-terraform-introduction.adoc
  downstream/assemblies/terraform-aap/assembly-terraform-migrating-from-community.adoc
  downstream/assemblies/terraform-aap/terraform-aap
  downstream/attributes/attributes.adoc
  downstream/images/ee-create-new.png
  downstream/modules/terraform-aap/con-terraform-intro.adoc
  downstream/modules/terraform-aap/proc-terraform-building-execution-environment.adoc
  downstream/modules/terraform-aap/proc-terraform-creating-credential.adoc
  downstream/modules/terraform-aap/proc-terraform-creating-launching-job-template.adoc
  downstream/modules/terraform-aap/proc-terraform-migrating-from-community.adoc
  downstream/titles/terraform-aap/terraform-aap-getting-started/aap-common
  downstream/titles/terraform-aap/terraform-aap-getting-started/attributes
  downstream/titles/terraform-aap/terraform-aap-getting-started/docinfo.xml
  downstream/titles/terraform-aap/terraform-aap-getting-started/images
  downstream/titles/terraform-aap/terraform-aap-getting-started/master.adoc
  downstream/titles/terraform-aap/terraform-aap-getting-started/terraform-aap
Labels: documentation, Ready for review, 2.5, Needs backport to 2.5

#3836 Backport AAP-47376: Creating new guide and content for Terraform and AAP integ…
  downstream/aap-common/aap-common
  downstream/assemblies/terraform-aap/assembly-terraform-integrating-from-aap.adoc
  downstream/assemblies/terraform-aap/assembly-terraform-integrating-from-terraform.adoc
  downstream/assemblies/terraform-aap/assembly-terraform-introduction.adoc
  downstream/assemblies/terraform-aap/assembly-terraform-migrating-from-community.adoc
  downstream/assemblies/terraform-aap/terraform-aap
  downstream/attributes/attributes.adoc
  downstream/images/ee-create-new.png
  downstream/modules/terraform-aap/con-terraform-intro.adoc
  downstream/modules/terraform-aap/proc-terraform-building-execution-environment.adoc
  downstream/modules/terraform-aap/proc-terraform-creating-credential.adoc
  downstream/modules/terraform-aap/proc-terraform-creating-launching-job-template.adoc
  downstream/modules/terraform-aap/proc-terraform-migrating-from-community.adoc
  downstream/titles/terraform-aap/terraform-aap-getting-started/aap-common
  downstream/titles/terraform-aap/terraform-aap-getting-started/attributes
  downstream/titles/terraform-aap/terraform-aap-getting-started/docinfo.xml
  downstream/titles/terraform-aap/terraform-aap-getting-started/images
  downstream/titles/terraform-aap/terraform-aap-getting-started/master.adoc
  downstream/titles/terraform-aap/terraform-aap-getting-started/terraform-aap
Labels: documentation, Ready for review, 2.5, Needs backport to 2.5

#3841 Editing controller files for DITA (#3839)
  downstream/assemblies/platform/assembly-ag-controller-config.adoc
  downstream/assemblies/platform/assembly-controller-improving-performance.adoc
  downstream/modules/platform/con-controller-metrics-monitor-controller.adoc
  downstream/modules/platform/con-websocket-setup.adoc
  downstream/modules/platform/proc-controller-disabling-live-events.adoc
  downstream/modules/platform/proc-create-password-hashes.adoc
  downstream/modules/platform/ref-controller-capacity-instance-container.adoc
  downstream/modules/platform/ref-controller-capacity-planning-exercise.adoc
  downstream/modules/platform/ref-controller-database-settings.adoc
  downstream/modules/platform/ref-controller-logging-settings.adoc
  downstream/modules/platform/ref-controller-settings-control-execution-nodes.adoc
  downstream/modules/platform/ref-controller-settings-job-events.adoc
  downstream/modules/platform/ref-controller-settings-to-modify-events.adoc
  downstream/modules/platform/ref-controller-web-service-tuning.adoc
  downstream/modules/platform/ref-encrypting-plaintext-passwords.adoc
  downstream/modules/platform/ref-scaling-control-nodes.adoc
  downstream/modules/platform/ref-scaling-hop-nodes.adoc
  downstream/titles/controller/controller-admin-guide/master.adoc
Labels: documentation, Controller, 2.5, Backported to 2.5

#3840 DITA readiness phase two (#3837)
  downstream/assemblies/platform/assembly-gateway-licensing.adoc
  downstream/assemblies/platform/assembly-install-aap-operator.adoc
  downstream/assemblies/platform/assembly-installing-aap-operator-cli.adoc
  downstream/assemblies/platform/assembly-installing-controller-operator.adoc
  downstream/assemblies/platform/assembly-installing-hub-operator.adoc
  downstream/modules/platform/con-aap-migrate-SAML-users.adoc
  downstream/modules/platform/con-aap-migrate-normal-users.adoc
  downstream/modules/platform/con-operator-upgrade-overview.adoc
  downstream/modules/platform/con-storage-options-for-operator-installation-on-ocp.adoc
  downstream/modules/platform/proc-aap-add-merge-subscriptions.adoc
  downstream/modules/platform/proc-aap-create-subscription-allocation.adoc
  downstream/modules/platform/proc-aap-generate-manifest-file.adoc
  downstream/modules/platform/proc-access-hub-operator-ui.adoc
  downstream/modules/platform/proc-account-linking.adoc
  downstream/modules/platform/proc-add-controller-access-token.adoc
  downstream/modules/platform/proc-add-operator-execution-nodes.adoc
  downstream/modules/platform/proc-attaching-subscriptions.adoc
  downstream/modules/platform/proc-cli-get-controller-address.adoc
  downstream/modules/platform/proc-configuring-controller-image-pull-policy.adoc
  downstream/modules/platform/proc-controller-ingress-options.adoc
  downstream/modules/platform/proc-create-a-connection-secret.adoc
  downstream/modules/platform/proc-create-an-ansiblejob.adoc
  downstream/modules/platform/proc-hub-ingress-options.adoc
  downstream/modules/platform/proc-install-aap-operator.adoc
  downstream/modules/platform/proc-operator-access-aap.adoc
  downstream/modules/platform/proc-operator-config-csrf-gateway.adoc
  downstream/modules/platform/proc-operator-create-controller-inventory.adoc
  downstream/modules/platform/proc-operator-create-controller-project.adoc
  downstream/modules/platform/proc-operator-create-controller-schedule.adoc
  downstream/modules/platform/proc-operator-create-controller-workflow-template.adoc
  downstream/modules/platform/proc-operator-create-controller-workflow.adoc
  downstream/modules/platform/proc-operator-create_crs.adoc
  downstream/modules/platform/proc-operator-deploy-central-config.adoc
  downstream/modules/platform/proc-operator-deploy-redis.adoc
  downstream/modules/platform/proc-operator-external-db-controller.adoc
  downstream/modules/platform/proc-operator-external-db-gateway.adoc
  downstream/modules/platform/proc-operator-external-db-hub.adoc
  downstream/modules/platform/proc-operator-scaling-down-aap.adoc
  downstream/modules/platform/proc-operator-upgrade.adoc
  downstream/modules/platform/proc-provision-ocp-storage-amazon-s3.adoc
  downstream/modules/platform/proc-provision-ocp-storage-azure-blob.adoc
  downstream/modules/platform/proc-verify-network-connectivity.adoc
  downstream/modules/platform/ref-controller-trial-evaluation.adoc
  downstream/modules/platform/ref-operator-ocp-version.adoc
  downstream/titles/aap-operator-installation/my_module_files.txt
Labels: 2.5, Migration

#3843 DITA migration changes. CUG Ch 22
  downstream/assemblies/platform/assembly-controller-credentials.adoc
  downstream/modules/platform/con-controller-access-GCE-in-a-playbook.adoc
  downstream/modules/platform/con-controller-access-machine-credentials-playbook.adoc
  downstream/modules/platform/con-controller-how-credentials-work.adoc
  downstream/modules/platform/proc-controller-add-users-job-templates.adoc
  downstream/modules/platform/proc-controller-create-credential.adoc
  downstream/modules/platform/ref-controller-access-azure-resources-in-playbook.adoc
  downstream/modules/platform/ref-controller-access-controller-creds-in-playbook.adoc
  downstream/modules/platform/ref-controller-access-ec2-credentials-in-playbook.adoc
  downstream/modules/platform/ref-controller-access-network-creds-playbook.adoc
  downstream/modules/platform/ref-controller-access-virt-creds-in-playbook.adoc
  downstream/modules/platform/ref-controller-access-vmware-creds-in-playbook.adoc
  downstream/modules/platform/ref-controller-aws-secrets-lookup.adoc
  downstream/modules/platform/ref-controller-credential-GCE.adoc
  downstream/modules/platform/ref-controller-credential-aap.adoc
  downstream/modules/platform/ref-controller-credential-aws.adoc
  downstream/modules/platform/ref-controller-credential-azure-key.adoc
  downstream/modules/platform/ref-controller-credential-azure-resource.adoc
  downstream/modules/platform/ref-controller-credential-centrify-vault.adoc
  downstream/modules/platform/ref-controller-credential-cyberark-central.adoc
  downstream/modules/platform/ref-controller-credential-cyberark-conjur.adoc
  downstream/modules/platform/ref-controller-credential-galaxy-hub.adoc
  downstream/modules/platform/ref-controller-credential-hashiCorp-vault.adoc
  downstream/modules/platform/ref-controller-credential-machine.adoc
  downstream/modules/platform/ref-controller-credential-network.adoc
  downstream/modules/platform/ref-controller-credential-openShift.adoc
  downstream/modules/platform/ref-controller-credential-openStack.adoc
  downstream/modules/platform/ref-controller-credential-satellite.adoc
  downstream/modules/platform/ref-controller-credential-terraform.adoc
  downstream/modules/platform/ref-controller-credential-thycotic-server.adoc
  downstream/modules/platform/ref-controller-credential-thycotic-vault.adoc
  downstream/modules/platform/ref-controller-credential-types.adoc
  downstream/modules/platform/ref-controller-credential-virtualization.adoc
  downstream/modules/platform/ref-controller-credential-vmware-vcenter.adoc
  downstream/modules/platform/ref-controller-multiple-connection-protocols.adoc
Labels: Controller, 2.5, Needs backport to 2.5, Migration

#3845 AAP-47376: Updated content for AAP-47376
  downstream/assemblies/terraform-aap/assembly-terraform-integrating-from-terraform.adoc
  downstream/assemblies/terraform-aap/assembly-terraform-migrating-from-community.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/terraform-aap/con-terraform-intro.adoc
  downstream/modules/terraform-aap/proc-terraform-creating-credential.adoc
  downstream/modules/terraform-aap/proc-terraform-migrating-from-community.adoc
  downstream/titles/terraform-aap/terraform-aap-getting-started/docinfo.xml
Labels: documentation, Ready for review, Technical review complete, 2.5, Needs backport to 2.5

#3851 DITA migration changes. CUG Ch 22 (#3843)
  downstream/assemblies/platform/assembly-controller-credentials.adoc
  downstream/modules/platform/con-controller-access-GCE-in-a-playbook.adoc
  downstream/modules/platform/con-controller-access-machine-credentials-playbook.adoc
  downstream/modules/platform/con-controller-how-credentials-work.adoc
  downstream/modules/platform/proc-controller-add-users-job-templates.adoc
  downstream/modules/platform/proc-controller-create-credential.adoc
  downstream/modules/platform/ref-controller-access-azure-resources-in-playbook.adoc
  downstream/modules/platform/ref-controller-access-controller-creds-in-playbook.adoc
  downstream/modules/platform/ref-controller-access-ec2-credentials-in-playbook.adoc
  downstream/modules/platform/ref-controller-access-network-creds-playbook.adoc
  downstream/modules/platform/ref-controller-access-virt-creds-in-playbook.adoc
  downstream/modules/platform/ref-controller-access-vmware-creds-in-playbook.adoc
  downstream/modules/platform/ref-controller-aws-secrets-lookup.adoc
  downstream/modules/platform/ref-controller-credential-GCE.adoc
  downstream/modules/platform/ref-controller-credential-aap.adoc
  downstream/modules/platform/ref-controller-credential-aws.adoc
  downstream/modules/platform/ref-controller-credential-azure-key.adoc
  downstream/modules/platform/ref-controller-credential-azure-resource.adoc
  downstream/modules/platform/ref-controller-credential-centrify-vault.adoc
  downstream/modules/platform/ref-controller-credential-cyberark-central.adoc
  downstream/modules/platform/ref-controller-credential-cyberark-conjur.adoc
  downstream/modules/platform/ref-controller-credential-galaxy-hub.adoc
  downstream/modules/platform/ref-controller-credential-hashiCorp-vault.adoc
  downstream/modules/platform/ref-controller-credential-machine.adoc
  downstream/modules/platform/ref-controller-credential-network.adoc
  downstream/modules/platform/ref-controller-credential-openShift.adoc
  downstream/modules/platform/ref-controller-credential-openStack.adoc
  downstream/modules/platform/ref-controller-credential-satellite.adoc
  downstream/modules/platform/ref-controller-credential-terraform.adoc
  downstream/modules/platform/ref-controller-credential-thycotic-server.adoc
  downstream/modules/platform/ref-controller-credential-thycotic-vault.adoc
  downstream/modules/platform/ref-controller-credential-types.adoc
  downstream/modules/platform/ref-controller-credential-virtualization.adoc
  downstream/modules/platform/ref-controller-credential-vmware-vcenter.adoc
  downstream/modules/platform/ref-controller-multiple-connection-protocols.adoc
Labels: documentation, Controller, 2.5, Backported to 2.5, Migration

#3853 2.5 Updates to Containerized installation (#3852)
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/assemblies/platform/assembly-setup-postgresql-ext-database.adoc
  downstream/modules/platform/proc-backup-aap-container.adoc
  downstream/modules/platform/proc-downloading-containerized-aap.adoc
  downstream/modules/platform/proc-enable-hstore-extension.adoc
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/platform/proc-reinstalling-containerized-aap.adoc
  downstream/modules/platform/proc-set-registry-username-password.adoc
  downstream/modules/platform/proc-setup-ext-db-without-admin-creds.adoc
  downstream/modules/platform/proc-uninstalling-containerized-aap.adoc
  downstream/modules/platform/proc-update-aap-container.adoc
  downstream/modules/platform/ref-ansible-inventory-variables.adoc
  downstream/modules/platform/ref-configuring-inventory-file.adoc
  downstream/modules/platform/ref-cont-aap-system-requirements.adoc
  downstream/modules/platform/ref-containerized-troubleshoot-install.adoc
Labels: 2.5, Backported to 2.5

#3855 updates system requirements for topologies
  downstream/snippets/cont-tested-system-config.adoc
  downstream/snippets/rpm-env-a-tested-system-config.adoc
Labels: 2.5, Needs backport to 2.5

#3827 AAP-48687: Added info. about disk space for /var/backups
  downstream/modules/platform/ref-controller-backup-restore-considerations.adoc
  downstream/modules/platform/ref-system-requirements.adoc
Labels: 2.5, Needs backport to 2.5

#3857 Backport PR #3827 from main to AAP 2.5 branch
  downstream/modules/platform/ref-controller-backup-restore-considerations.adoc
  downstream/modules/platform/ref-system-requirements.adoc
Labels: 2.5, Backported to 2.5

#3859 Editing controller files for DITA
  downstream/assemblies/platform/assembly-inventory-file-importing.adoc
  downstream/modules/platform/ref-controller-scm-inv-source-fields.adoc
Labels: documentation, Controller, 2.5, Needs backport to 2.5

#3860 Editing controller files for DITA (#3859)
  downstream/assemblies/platform/assembly-inventory-file-importing.adoc
  downstream/modules/platform/ref-controller-scm-inv-source-fields.adoc
Labels: 2.5, Backported to 2.5

#3866 Editing controller files for DITA (#3864)
  downstream/assemblies/platform/assembly-controller-pac.adoc
  downstream/modules/platform/proc-configure-pac-settings.adoc
  downstream/modules/platform/ref-pac-inputs-outputs.adoc
Labels: 2.5, Backported to 2.5

#3865 DITA migration changes: CUG Ch 28
  downstream/assemblies/platform/assembly-ug-controller-setting-up-insights.adoc
  downstream/modules/platform/con-controller-create-insights-inventory.adoc
  downstream/modules/platform/proc-controller-create-insights-credential.adoc
  downstream/modules/platform/proc-controller-remediate-insights-inventory.adoc
Labels: Controller, 2.5, Needs backport to 2.5, Migration

#3867 DITA migration changes: CUG Ch 28 (#3865)
  downstream/assemblies/platform/assembly-ug-controller-setting-up-insights.adoc
  downstream/modules/platform/con-controller-create-insights-inventory.adoc
  downstream/modules/platform/proc-controller-create-insights-credential.adoc
  downstream/modules/platform/proc-controller-remediate-insights-inventory.adoc
Labels: documentation, Controller, 2.5, Backported to 2.5, Migration

#3869 DITA migration changes: CUG Ch 29 (#3868)
  downstream/assemblies/platform/assembly-controller-best-practices.adoc
  downstream/modules/platform/ref-controller-autoscaling.adoc
  downstream/modules/platform/ref-controller-continuous-integration.adoc
  downstream/modules/platform/ref-controller-file-directory-structure.adoc
  downstream/modules/platform/ref-controller-inv-variable-management.adoc
  downstream/modules/platform/ref-controller-large-host-counts.adoc
  downstream/modules/platform/ref-controller-source-control.adoc
  downstream/modules/platform/ref-controller-use-dynamic-inv-sources.adoc
Labels: documentation, Controller, 2.5, Backported to 2.5, Migration

#3871 DITA migration changes: CUG Glossary
  downstream/assemblies/platform/assembly-controller-glossary.adoc
Labels: documentation, Controller, 2.5, Needs backport to 2.5, Migration

#3872 AAP-49823: Replace text with attributes and run vale dita check
  downstream/assemblies/terraform-aap/assembly-terraform-integrating-from-aap.adoc
  downstream/modules/terraform-aap/con-terraform-intro.adoc
  downstream/modules/terraform-aap/proc-terraform-building-execution-environment.adoc
  downstream/modules/terraform-aap/proc-terraform-creating-credential.adoc
  downstream/modules/terraform-aap/proc-terraform-creating-launching-job-template.adoc
  downstream/modules/terraform-aap/proc-terraform-migrating-from-community.adoc
Labels: documentation, Ready for review, 2.5, Needs backport to 2.5

#3873 Backport for AAP-49823: Replace text with attributes and run vale dita check (#3872)
  downstream/assemblies/terraform-aap/assembly-terraform-integrating-from-aap.adoc
  downstream/modules/terraform-aap/con-terraform-intro.adoc
  downstream/modules/terraform-aap/proc-terraform-building-execution-environment.adoc
  downstream/modules/terraform-aap/proc-terraform-creating-credential.adoc
  downstream/modules/terraform-aap/proc-terraform-creating-launching-job-template.adoc
  downstream/modules/terraform-aap/proc-terraform-migrating-from-community.adoc
Labels: documentation, Ready for review, 2.5, Needs backport to 2.5

#3876 DITA migration changes: CUG Glossary (#3871)
  downstream/assemblies/platform/assembly-controller-glossary.adoc
Labels: documentation, Controller, 2.5, Backported to 2.5, Migration

#3877 Fixing broke link in CUG
  downstream/modules/platform/ref-controller-building-exec-env.adoc
Labels: documentation, Controller, 2.5, Needs backport to 2.5

#3874 AAP-49578: DITA conversion, xrefs to links in Managing automation content guide
  downstream/archive/archived-assemblies/hub/assembly-hub-create-api-token.adoc
  downstream/archive/archived-assemblies/hub/assembly_ppah-installation.adoc
  downstream/assemblies/hub/assembly-collection-import-export.adoc
  downstream/assemblies/hub/assembly-container-user-access.adoc
  downstream/assemblies/hub/assembly-managing-cert-valid-content.adoc
  downstream/assemblies/hub/assembly-populate-container-registry.adoc
  downstream/assemblies/hub/assembly-pull-image.adoc
  downstream/assemblies/hub/assembly-remote-management.adoc
  downstream/assemblies/hub/assembly-repo-management.adoc
  downstream/assemblies/hub/assembly-setup-container-repository.adoc
  downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc
  downstream/assemblies/hub/assembly-synclists.adoc
Labels: 2.5, Needs backport to 2.5, Migration

#3782 Asciidoc conversion of hardening guide changes
  downstream/assemblies/aap-hardening/assembly-hardening-aap.adoc
  downstream/assemblies/aap-hardening/assembly-managed-node-configuration.adoc
  downstream/images/cont-b-env-a.png
  downstream/modules/aap-hardening/con-create-dedicated-service-account.adoc
  downstream/modules/aap-hardening/con-hashicorp-vault-external-secrets.adoc
  downstream/modules/aap-hardening/con-more_compliance-profile-considerations.adoc
  downstream/modules/aap-hardening/con-rhel-node-configuration.adoc
  downstream/modules/aap-hardening/proc-configure-hashicorp-credentials.adoc
  downstream/modules/aap-hardening/proc-configure-hashicorp-vault.adoc
  downstream/modules/aap-hardening/proc-configure-ssh-private-key.adoc
  downstream/modules/aap-hardening/proc-configure-sudo-for-service-account.adoc
  downstream/modules/aap-hardening/proc-create-fapolicyd-rules.adoc
  downstream/modules/aap-hardening/proc-fapolicyd-permissive-mode.adoc
  downstream/modules/aap-hardening/proc-install-containerized-deployment.adoc
  downstream/modules/aap-hardening/proc-install-rpm-deployment.adoc
  downstream/modules/aap-hardening/proc-pam-access-for-service-accounts.adoc
  downstream/modules/aap-hardening/proc-sensitive-variables-install-inventory.adoc
  downstream/modules/aap-hardening/proc-ssh-auth-for-service-account.adoc
  downstream/modules/aap-hardening/ref-architecture.adoc
  downstream/modules/aap-hardening/ref-fapolicyd-on-rhel.adoc
  downstream/modules/aap-hardening/ref-sensitive-variables-install-inventory.adoc
  downstream/titles/aap-hardening/master.adoc
Labels: AAP Hardening, 2.5, Needs backport to 2.5

#3886 Fixing ID in notification feed module
  downstream/modules/platform/con-aap-notifications-feed.adoc
  downstream/titles/aap-planning-guide/master.adoc
Labels: documentation, 2.5

#3884 DITA migration tasks: Add doc type to licences
  downstream/aap-common/apache-2.0-license.adoc
  downstream/aap-common/gplv3-license-text.adoc
  downstream/aap-common/open-source-apache.adoc
  downstream/aap-common/open-source-gnu3.adoc
Labels: 2.5, Needs backport to 2.5

#3885 Asciidoc conversion of hardening guide changes (#3782)
  downstream/assemblies/aap-hardening/assembly-hardening-aap.adoc
  downstream/assemblies/aap-hardening/assembly-managed-node-configuration.adoc
  downstream/images/cont-b-env-a.png
  downstream/modules/aap-hardening/con-create-dedicated-service-account.adoc
  downstream/modules/aap-hardening/con-hashicorp-vault-external-secrets.adoc
  downstream/modules/aap-hardening/con-more_compliance-profile-considerations.adoc
  downstream/modules/aap-hardening/con-rhel-node-configuration.adoc
  downstream/modules/aap-hardening/proc-configure-hashicorp-credentials.adoc
  downstream/modules/aap-hardening/proc-configure-hashicorp-vault.adoc
  downstream/modules/aap-hardening/proc-configure-ssh-private-key.adoc
  downstream/modules/aap-hardening/proc-configure-sudo-for-service-account.adoc
  downstream/modules/aap-hardening/proc-create-fapolicyd-rules.adoc
  downstream/modules/aap-hardening/proc-fapolicyd-permissive-mode.adoc
  downstream/modules/aap-hardening/proc-install-containerized-deployment.adoc
  downstream/modules/aap-hardening/proc-install-rpm-deployment.adoc
  downstream/modules/aap-hardening/proc-pam-access-for-service-accounts.adoc
  downstream/modules/aap-hardening/proc-sensitive-variables-install-inventory.adoc
  downstream/modules/aap-hardening/proc-ssh-auth-for-service-account.adoc
  downstream/modules/aap-hardening/ref-architecture.adoc
  downstream/modules/aap-hardening/ref-fapolicyd-on-rhel.adoc
  downstream/modules/aap-hardening/ref-sensitive-variables-install-inventory.adoc
  downstream/titles/aap-hardening/master.adoc
Labels: AAP Hardening, 2.5, Backported to 2.5

#3890 DITA migration tasks: Add doc type to licences (#3884)
  downstream/aap-common/apache-2.0-license.adoc
  downstream/aap-common/gplv3-license-text.adoc
  downstream/aap-common/open-source-apache.adoc
  downstream/aap-common/open-source-gnu3.adoc
Labels: 2.5, Backported to 2.5

#3891 Editing controller files for DITA (#3888)
  downstream/assemblies/platform/assembly-aap-activate.adoc
  downstream/assemblies/platform/assembly-controller-metrics.adoc
  downstream/assemblies/platform/assembly-controller-subscription-management.adoc
  downstream/modules/platform/proc-controller-awx-manage-utility.adoc
  downstream/modules/platform/proc-controller-set-up-prometheus.adoc
  downstream/modules/platform/proc-view-hosts-in-ui.adoc
Labels: Controller, 2.5

#3896 Fixed attribute error
  downstream/modules/aap-hardening/proc-configure-hashicorp-credentials.adoc
Labels: AAP Hardening, 2.5, Needs backport to 2.5

#3897 Corrected spelling error
  downstream/modules/aap-hardening/proc-configure-sudo-for-service-account.adoc
Labels: 2.5, Needs backport to 2.5

#3898 Fixed attribute error (#3896)
  downstream/modules/aap-hardening/proc-configure-hashicorp-credentials.adoc
Labels: 2.5, Backported to 2.5

#3899 Corrected spelling error (#3897)
  downstream/modules/aap-hardening/proc-configure-sudo-for-service-account.adoc
Labels: 2.5, Backported to 2.5

#3902 Update release attribute and docinfo to 2.6
  downstream/attributes/attributes.adoc
  downstream/titles/aap-containerized-install/docinfo.xml
  downstream/titles/aap-hardening/docinfo.xml
  downstream/titles/aap-installation-guide/docinfo.xml
  downstream/titles/aap-migration/docinfo.xml
  downstream/titles/aap-operations-guide/docinfo.xml
  downstream/titles/aap-operator-backup/docinfo.xml
  downstream/titles/aap-operator-installation/docinfo.xml
  downstream/titles/aap-planning-guide/docinfo.xml
  downstream/titles/aap-plugin-rhdh-install/docinfo.xml
  downstream/titles/analytics/docinfo.xml
  downstream/titles/automation-mesh/docinfo.xml
  downstream/titles/builder/docinfo.xml
  downstream/titles/central-auth/docinfo.xml
  downstream/titles/controller/controller-admin-guide/docinfo.xml
  downstream/titles/controller/controller-api-overview/docinfo.xml
  downstream/titles/controller/controller-user-guide/docinfo.xml
  downstream/titles/develop-automation-content/docinfo.xml
  downstream/titles/eda/eda-user-guide/docinfo.xml
  downstream/titles/edge-manager/edge-manager-user-guide/docinfo.xml
  downstream/titles/getting-started/docinfo.xml
  downstream/titles/hub/managing-content/docinfo.xml
  downstream/titles/navigator-guide/docinfo.xml
  downstream/titles/ocp_performance_guide/docinfo.xml
  downstream/titles/operator-mesh/docinfo.xml
  downstream/titles/playbooks/playbooks-getting-started/docinfo.xml
  downstream/titles/playbooks/playbooks-reference/docinfo.xml
  downstream/titles/release-notes/docinfo.xml
  downstream/titles/security-guide/docinfo.xml
  downstream/titles/self-service-install/docinfo.xml
  downstream/titles/self-service-using/docinfo.xml
  downstream/titles/terraform-aap/terraform-aap-getting-started/docinfo.xml
  downstream/titles/topologies/docinfo.xml
  downstream/titles/troubleshooting-aap/docinfo.xml
  downstream/titles/upgrade/docinfo.xml
Labels: Attributes, 2.6, Needs backport to 2.6

#3903 2.6 Update release attribute and docinfo to 2.6 (#3902)
  downstream/attributes/attributes.adoc
  downstream/titles/aap-containerized-install/docinfo.xml
  downstream/titles/aap-hardening/docinfo.xml
  downstream/titles/aap-installation-guide/docinfo.xml
  downstream/titles/aap-migration/docinfo.xml
  downstream/titles/aap-operations-guide/docinfo.xml
  downstream/titles/aap-operator-backup/docinfo.xml
  downstream/titles/aap-operator-installation/docinfo.xml
  downstream/titles/aap-planning-guide/docinfo.xml
  downstream/titles/aap-plugin-rhdh-install/docinfo.xml
  downstream/titles/analytics/docinfo.xml
  downstream/titles/automation-mesh/docinfo.xml
  downstream/titles/builder/docinfo.xml
  downstream/titles/central-auth/docinfo.xml
  downstream/titles/controller/controller-admin-guide/docinfo.xml
  downstream/titles/controller/controller-api-overview/docinfo.xml
  downstream/titles/controller/controller-user-guide/docinfo.xml
  downstream/titles/develop-automation-content/docinfo.xml
  downstream/titles/eda/eda-user-guide/docinfo.xml
  downstream/titles/edge-manager/edge-manager-user-guide/docinfo.xml
  downstream/titles/getting-started/docinfo.xml
  downstream/titles/hub/managing-content/docinfo.xml
  downstream/titles/navigator-guide/docinfo.xml
  downstream/titles/ocp_performance_guide/docinfo.xml
  downstream/titles/operator-mesh/docinfo.xml
  downstream/titles/playbooks/playbooks-getting-started/docinfo.xml
  downstream/titles/playbooks/playbooks-reference/docinfo.xml
  downstream/titles/release-notes/docinfo.xml
  downstream/titles/security-guide/docinfo.xml
  downstream/titles/self-service-install/docinfo.xml
  downstream/titles/self-service-using/docinfo.xml
  downstream/titles/terraform-aap/terraform-aap-getting-started/docinfo.xml
  downstream/titles/topologies/docinfo.xml
  downstream/titles/troubleshooting-aap/docinfo.xml
  downstream/titles/upgrade/docinfo.xml
Labels: Attributes, 2.6

#3904 Add sync scripts for AAP 2.6
  bin/sync_docs.sh
  bin/sync_ocp_latest.sh
Labels: repo, 2.6

#3905 2.6: Archive 2.5 updating doc
  downstream/archive/archived-titles/updating-aap/docinfo.xml
  downstream/archive/archived-titles/updating-aap/master.adoc
  downstream/titles/updating-aap/aap-common
  downstream/titles/updating-aap/attributes
  downstream/titles/updating-aap/images
  downstream/titles/updating-aap/platform
Labels: Archive, 2.6

#3907 2.6 Update Containerized installation for AAP 2.6 (#3906)
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/platform/proc-downloading-containerized-aap.adoc
  downstream/modules/platform/proc-enabling-automation-hub-collection-and-container-signing.adoc
  downstream/modules/platform/proc-restore-aap-container.adoc
  downstream/modules/platform/proc-update-aap-container.adoc
  downstream/modules/platform/ref-containerized-troubleshoot-ref.adoc
  downstream/modules/platform/ref-images-inventory-variables.adoc
  downstream/snippets/cont-tested-system-config.adoc
  downstream/snippets/inventory-cont-a-env-a.adoc
  downstream/snippets/inventory-cont-b-env-a.adoc
Labels: 2.6, Backported to 2.6

#3910 Fixing table headers in crsf section of OCP guide
  downstream/modules/platform/proc-operator-config-csrf-gateway.adoc
  downstream/modules/platform/ref-operator-ocp-version.adoc
Labels: documentation, 2.5, AAP operator

#3911 Fixing table headers in crsf section of OCP guide (#3910)
  downstream/modules/platform/proc-operator-config-csrf-gateway.adoc
  downstream/modules/platform/ref-operator-ocp-version.adoc
Labels: 2.5

#3912 Create AAP 2.6 inventory files for Tested deployment models
  downstream/snippets/inventory-rpm-a-env-a.adoc
  downstream/snippets/inventory-rpm-b-env-a.adoc
Labels: 2.6, Needs backport to 2.6

#3915 updating Containerized installation (#3914)
  downstream/modules/platform/proc-enabling-automation-hub-collection-and-container-signing.adoc
Labels: Backported to 2.6

#3916 2.5 updating Containerized installation (#3914)
  downstream/modules/platform/proc-enabling-automation-hub-collection-and-container-signing.adoc
Labels: Backported to 2.5

#3917 DITA migration changes: Security automation
  downstream/assemblies/security/assembly-firewall-policy-manage.adoc
  downstream/assemblies/security/assembly-idps.adoc
  downstream/modules/security/con-about-firewall-policy-management.adoc
  downstream/modules/security/con-automate-idps-rules.adoc
  downstream/modules/security/con-automating-firewall-rules.adoc
  downstream/modules/security/con-requirements.adoc
  downstream/modules/security/proc-creating-firewall-rule.adoc
  downstream/modules/security/proc-creating-idps-rule.adoc
  downstream/modules/security/proc-deleting-firewall-rule.adoc
  downstream/modules/security/proc-verifying-idps-install.adoc
Labels: 2.5, Needs backport to 2.5, 2.6, Needs backport to 2.6

#3924 Updating gitignore and pg
  .gitignore
  downstream/modules/platform/proc-operator-external-db-controller.adoc
Labels: Backported to 2.4, 2.4

#3918 Update backup/restore note
  downstream/assemblies/platform/assembly-ag-controller-backup-and-restore.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5, 2.6, Needs backport to 2.6

#3925 2.6 Update backup/restore note (#3918)
  downstream/assemblies/platform/assembly-ag-controller-backup-and-restore.adoc
Labels: 2.6, Backported to 2.6

#3930 Bp to 2.5: AAP-45952: adds PaC info to getting started guide intro (#3922)
  downstream/modules/platform/con-gs-automation-execution.adoc
Labels: Migration, 2.6

#3929 AAP-50441-migration-edits
  downstream/modules/aap-migration/con-migration-process-overview.adoc
Labels: documentation, 2.5, Needs backport to 2.5, 2.6, Needs backport to 2.6

#3932 AAP-50575 edits
  .gitignore
  .vale.ini
  stories/topics/con-saas-backup-and-diaster-recovery.adoc
Labels: AAP on clouds, SaaS on AWS

#3933 AAP-50441-migration-edits (#3929)
  downstream/modules/aap-migration/con-migration-process-overview.adoc
Labels: 2.5, AAP operator

#3934 AAP-50441-migration-edits (#3929)
  downstream/modules/aap-migration/con-migration-process-overview.adoc
Labels: AAP operator, 2.6

#3936 Update Tested deployment models for 2.6
  downstream/modules/topologies/ref-installation-deployment-models.adoc
  downstream/modules/topologies/ref-ocp-a-env-a.adoc
  downstream/snippets/rpm-env-a-tested-system-config.adoc
  downstream/titles/topologies/master.adoc
Labels: 2.6, Needs backport to 2.6

#3939 Adding callback URL field info to OIDC auth section (#3883)
  downstream/modules/platform/proc-controller-set-up-generic-oidc.adoc
Labels: 2.5, Backported to 2.5

#3940 DITA migration changes: CAG Ch 8
  downstream/assemblies/platform/assembly-controller-log-files.adoc
  downstream/modules/platform/ref-controller-log-files.adoc
Labels: Controller, 2.5, Needs backport to 2.5, Migration, 2.6, Needs backport to 2.6

#3947 Updating main with PG tweaks
  downstream/modules/platform/proc-operator-external-db-controller.adoc
  downstream/modules/platform/proc-operator-external-db-gateway.adoc
  downstream/modules/platform/proc-operator-external-db-hub.adoc
Labels: AAP operator, 2.6, Backported to 2.6

#3946 Add backup/restore note to Containerized installation
  downstream/modules/platform/proc-backup-aap-container.adoc
  downstream/modules/platform/proc-restore-aap-container.adoc
Labels: 2.5, Needs backport to 2.5, 2.6, Needs backport to 2.6

#3948 2.6 Add backup/restore note to Containerized installation (#3946)
  downstream/modules/platform/proc-backup-aap-container.adoc
  downstream/modules/platform/proc-restore-aap-container.adoc
Labels: 2.6, Backported to 2.6

#3949 2.5 Add backup/restore note to Containerized installation (#3946)
  downstream/modules/platform/proc-backup-aap-container.adoc
  downstream/modules/platform/proc-restore-aap-container.adoc
Labels: 2.5, Backported to 2.5

#3951 2.6 Update controller version (#3950)
  downstream/assemblies/platform/assembly-aap-upgrading-platform.adoc
Labels: Backported to 2.6

#3952 2.5 Update controller version (#3950)
  downstream/assemblies/platform/assembly-aap-upgrading-platform.adoc
Labels: Backported to 2.5

#3954 DITA migration changes: CAG Ch 9 (#3953)
  downstream/assemblies/platform/assembly-controller-logging-aggregation.adoc
  downstream/modules/platform/proc-controller-set-up-logging.adoc
  downstream/modules/platform/ref-controller-activity-stream-schema.adoc
  downstream/modules/platform/ref-controller-job-status-changes.adoc
  downstream/modules/platform/ref-controller-log-aggregators.adoc
  downstream/modules/platform/ref-controller-logs.adoc
  downstream/modules/platform/ref-controller-scan-fact-tracking-schema.adoc
  downstream/modules/platform/ref-controller-troubleshoot-logging.adoc
Labels: 2.5, Backported to 2.5

#3957 Add reference to AWS
  downstream/assemblies/platform/assembly-planning-mesh.adoc
Labels: Automation Mesh, 2.5, Needs backport to 2.5, 2.6, Needs backport to 2.6

#3958 Add reference to AWS (#3957)
  downstream/assemblies/platform/assembly-planning-mesh.adoc
Labels: Automation Mesh, 2.5, Backported to 2.5

#3935 Corrected links
  downstream/modules/platform/ref-controller-credential-hashiCorp-vault.adoc
  downstream/modules/platform/ref-controller-credential-network.adoc
Labels: 2.5, Needs backport to 2.5, 2.6, Needs backport to 2.6

#3961 Corrected links (#3935)
  downstream/modules/platform/ref-controller-credential-hashiCorp-vault.adoc
  downstream/modules/platform/ref-controller-credential-network.adoc
Labels: 2.6, Backported to 2.6

#3964 AAP-50126: Updated PG 13 to PG 15 references
  downstream/modules/platform/ref-controller-variables.adoc
  downstream/modules/platform/ref-postgresql-requirements.adoc
  downstream/modules/platform/ref-system-requirements.adoc
Labels: 2.4
