Repository ansible/aap-docs, pull requests merged in 2025-02, with the labels that each got.

#2843 Azure 2.5
  stories/assembly-azure-install-prerequisites.adoc
  stories/assembly-azure-intro.adoc
  stories/assembly-azure-post-deployment-requirements.adoc
  stories/assembly-azure-support.adoc
  stories/topics/con-azure-about.adoc
  stories/topics/con-azure-architecture.adoc
  stories/topics/con-azure-infrastructure-usage.adoc
  stories/topics/con-azure-pricing.adoc
  stories/topics/con-azure-private-access.adoc
  stories/topics/con-azure-private-dns.adoc
  stories/topics/proc-azure-cancel-deployment.adoc
  stories/topics/proc-azure-configure-ad-sso.adoc
  stories/topics/proc-azure-nw-access-details.adoc
  stories/topics/proc-azure-nw-private-deploy-az-hosted-vm.adoc
  stories/topics/proc-azure-nw-private-deploy-vpn.adoc
  stories/topics/proc-azure-nw-private-deploy.adoc
  stories/topics/proc-azure-nw-public-deploy.adoc
  stories/topics/proc-azure-provisioning-aap.adoc
  stories/topics/proc-azure-resource-providers.adoc
Labels: documentation, AAP on clouds, AAP on Azure, 2.5

#2863 updtaing platformvers attribute
  attributes/attributes.adoc
Labels: AAP on clouds, AAP on Azure

#2864 Adding edits from AAP-38722
  downstream/modules/platform/proc-post-migration-cleanup.adoc
Labels: documentation, 2.4, 2.5, AAP operator

#2865 Adding edits from AAP-38722 (#2864)
  downstream/modules/platform/proc-post-migration-cleanup.adoc
Labels: 2.5, AAP operator

#2866 Adding edits from AAP-38722 (#2864)
  downstream/modules/platform/proc-post-migration-cleanup.adoc
Labels: 2.4, AAP operator

#2868 Clouds Update image for AAP 2.5 in Azure doc
  images/aap-on-azure-private-deployment.png
  images/aap-on-azure-public-deployment.png
  stories/assembly-azure-network-peering.adoc
  stories/topics/con-azure-entitling-subscription.adoc
  stories/topics/con-azure-infrastructure-usage.adoc
  stories/topics/con-azure-pricing.adoc
  stories/topics/proc-azure-accessing-aap.adoc
  stories/topics/proc-azure-configure-ad-sso.adoc
  stories/topics/proc-azure-nw-direct-peering.adoc
  stories/topics/proc-azure-nw-peering-aap-subnet.adoc
  stories/topics/proc-azure-nw-private-deploy.adoc
  stories/topics/proc-azure-nw-public-deploy.adoc
  stories/topics/proc-azure-provisioning-aap.adoc
  stories/topics/proc-azure-resource-quotas.adoc
Labels: AAP on clouds, AAP on Azure

#2870 Remove snippet from known issues as it is resolved
  downstream/titles/release-notes/topics/aap-25-known-issues.adoc
Labels: 2.5, Needs backport to 2.5

#2871 Remove snippet from known issues as it is resolved (#2870)
  downstream/titles/release-notes/topics/aap-25-known-issues.adoc
Labels: 2.5, Backported to 2.5

#2853 Creating Flight Control troubleshooting section
  downstream/assemblies/flight-control/flight-control
  downstream/assemblies/platform/assembly-flight-control-troubleshooting.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/platform/proc-flight-control-generate-device-log.adoc
  downstream/modules/platform/proc-flight-control-view-device-config.adoc
  downstream/titles/flight-control/flight-control-user-guide/docinfo.xml
  downstream/titles/flight-control/flight-control-user-guide/flight-control
  downstream/titles/flight-control/flight-control-user-guide/master.adoc
  downstream/titles/flight-control/flight-control-user-guide/platform
Labels: documentation, 2.5, Needs backport to 2.5

#2872 Creating Flight Control troubleshooting section (#2853)
  downstream/assemblies/flight-control/flight-control
  downstream/assemblies/platform/assembly-flight-control-troubleshooting.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/platform/proc-flight-control-generate-device-log.adoc
  downstream/modules/platform/proc-flight-control-view-device-config.adoc
  downstream/titles/flight-control/flight-control-user-guide/docinfo.xml
  downstream/titles/flight-control/flight-control-user-guide/flight-control
  downstream/titles/flight-control/flight-control-user-guide/master.adoc
  downstream/titles/flight-control/flight-control-user-guide/platform
Labels: documentation, 2.5, Backported to 2.5

#2867 Updating awx to AutomationController
  downstream/modules/platform/proc-aap-controller-yaml-backup.adoc
  downstream/modules/platform/proc-aap-controller-yaml-restore.adoc
  downstream/modules/platform/proc-configuring-controller-ldap-security.adoc
  downstream/modules/platform/proc-verify-network-connectivity.adoc
Labels: documentation, 2.5, AAP operator

#2856 AAP-34599: adds additional resources block to containerized guide
  downstream/modules/platform/ref-enabling-automation-hub-collection-and-container-signing.adoc
Labels: Automation Hub, 2.5, Needs backport to 2.5, Containerized AAP

#2875 Updating awx to AutomationController (#2867)
  downstream/modules/platform/proc-aap-controller-yaml-backup.adoc
  downstream/modules/platform/proc-aap-controller-yaml-restore.adoc
  downstream/modules/platform/proc-configuring-controller-ldap-security.adoc
  downstream/modules/platform/proc-verify-network-connectivity.adoc
Labels: documentation, 2.5, AAP operator

#2876 Removing Lightspeed from code block
  downstream/modules/platform/ref-operator-crs.adoc
Labels: documentation, 2.5, AAP operator

#2877 removing lightspeed from code block (#2876)
  downstream/modules/platform/ref-operator-crs.adoc
Labels: documentation, 2.5, AAP operator

#2879 Fix xref in hub module
  downstream/modules/hub/proc-deploying-your-system-for-container-signing.adoc
Labels: 2.5, Needs backport to 2.5

#2880 2.5 Fix xref in hub module (#2879)
  downstream/modules/hub/proc-deploying-your-system-for-container-signing.adoc
Labels: 2.5

#2881 Remove text before link
  downstream/modules/hub/proc-deploying-your-system-for-container-signing.adoc
Labels: 2.5, Backported to 2.5

#2882 2.5 Remove text before link (#2881)
  downstream/modules/hub/proc-deploying-your-system-for-container-signing.adoc
Labels: 2.5

#2883 backport to 2.5: AAP-34599: adds additional resources block to containerized guide
  downstream/modules/platform/ref-enabling-automation-hub-collection-and-container-signing.adoc
Labels: Automation Hub, 2.5, Containerized AAP

#2885 2.5 xref formatting fix in Managing automation content guide(#2874)(#2884)
  downstream/modules/hub/proc-deploying-your-system-for-container-signing.adoc
Labels: 2.5

#2887 Correct formatting of logging section
  downstream/modules/platform/proc-controller-set-up-logging.adoc
Labels: 2.5, Needs backport to 2.5

#2890 2.5 Update topology diagrams (#2889)
  downstream/images/cont-a-env-a.png
  downstream/images/cont-b-env-a.png
  downstream/images/ocp-a-env-a.png
  downstream/images/ocp-b-env-a.png
  downstream/images/rpm-a-env-a.png
  downstream/images/rpm-a-env-b.png
  downstream/images/rpm-b-env-a.png
  downstream/images/rpm-b-env-b.png
Labels: 2.5, Backported to 2.5

#2892 Update storage backend options for more clarity (#2869)
  downstream/modules/platform/ref-configuring-inventory-file.adoc
  downstream/modules/platform/ref-ha-hub-reqs.adoc
  downstream/modules/platform/ref-hub-variables.adoc
Labels: 2.5, Backported to 2.5

#2893 Update containerized installation ext db configuration
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/assemblies/platform/assembly-appendix-inventory-file-vars.adoc
  downstream/modules/platform/proc-setup-postgresql-ext-database-containerized.adoc
  downstream/modules/platform/proc-setup-postgresql-ext-database.adoc
  downstream/modules/platform/ref-ansible-inventory-variables.adoc
  downstream/modules/platform/ref-controller-variables.adoc
  downstream/modules/platform/ref-database-inventory-variables.adoc
  downstream/modules/platform/ref-eda-controller-variables.adoc
  downstream/modules/platform/ref-gateway-variables.adoc
  downstream/modules/platform/ref-general-inventory-variables.adoc
  downstream/modules/platform/ref-hub-variables.adoc
  downstream/modules/platform/ref-receptor-inventory-variables.adoc
Labels: 2.5, Needs backport to 2.5

#2894 2.5 Update containerized installation ext db configuration (#2893)
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/assemblies/platform/assembly-appendix-inventory-file-vars.adoc
  downstream/modules/platform/proc-setup-postgresql-ext-database-containerized.adoc
  downstream/modules/platform/proc-setup-postgresql-ext-database.adoc
  downstream/modules/platform/ref-ansible-inventory-variables.adoc
  downstream/modules/platform/ref-controller-variables.adoc
  downstream/modules/platform/ref-database-inventory-variables.adoc
  downstream/modules/platform/ref-eda-controller-variables.adoc
  downstream/modules/platform/ref-gateway-variables.adoc
  downstream/modules/platform/ref-general-inventory-variables.adoc
  downstream/modules/platform/ref-hub-variables.adoc
  downstream/modules/platform/ref-receptor-inventory-variables.adoc
Labels: 2.5, Backported to 2.5

#2896 AAP-37377: Updates attribute in Managing automation content
  downstream/modules/hub/proc-adding-an-execution-environment.adoc
  downstream/modules/hub/proc-configuring-the-client-to-verify-signatures.adoc
  downstream/modules/hub/proc-using-podman-ensure-image-signed.adoc
Labels: Automation Hub, 2.5, Needs backport to 2.5

#2897 Backport to 2.5: AAP-37377 Updates attribute in Managing automation content guide
  downstream/modules/hub/proc-adding-an-execution-environment.adoc
  downstream/modules/hub/proc-configuring-the-client-to-verify-signatures.adoc
  downstream/modules/hub/proc-using-podman-ensure-image-signed.adoc
Labels: Automation Hub, 2.5

#2899 [Backport] AAP-40016 - Adding post upgrade details to address escalated customer pain points (#2898)
  downstream/assemblies/platform/assembly-aap-post-upgrade.adoc
  downstream/assemblies/platform/assembly-aap-upgrading-platform.adoc
  downstream/modules/platform/con-aap-migrate-normal-users.adoc
  downstream/modules/platform/con-aap-upgrade-planning.adoc
  downstream/modules/platform/con-aap-upgrades.adoc
  downstream/modules/platform/proc-aap-migrate-SAML-users.adoc
  downstream/modules/platform/proc-aap-migrate-admin-users.adoc
  downstream/modules/platform/proc-account-linking.adoc
  downstream/modules/platform/proc-running-setup-script-for-updates.adoc
  downstream/titles/upgrade/master.adoc
Labels: 2.5

#2790 AAP-36632-update: TOC restructure of Ansible Lightspeed User Guide
  lightspeed/archive/archived-assemblies/assembly_configuring-custom-models.adoc
  lightspeed/archive/archived-assemblies/assembly_configuring-vscode-extension.adoc
  lightspeed/archive/archived-assemblies/assembly_generating-playbooks.adoc
  lightspeed/archive/archived-assemblies/assembly_logging-in-lightspeed-admin-portal.adoc
  lightspeed/archive/archived-assemblies/assembly_logging-in-out-portal.adoc
  lightspeed/archive/archived-assemblies/assembly_requesting-task-recommendations.adoc
  lightspeed/assemblies/assembly_administering-ansible-lightspeed.adoc
  lightspeed/assemblies/assembly_developing-ansible-content.adoc
  lightspeed/assemblies/assembly_setting-up-lightspeed.adoc
  lightspeed/modules/con_ansible-content-parser.adoc
  lightspeed/modules/con_config-custom-models.adoc
  lightspeed/modules/con_config-vs-code-extension.adoc
  lightspeed/modules/con_log-into-portal-auto-dev.adoc
  lightspeed/modules/con_playbook-generation-best-practices.adoc
  lightspeed/modules/con_playbook-generation.adoc
  lightspeed/modules/con_task-recommendations.adoc
  lightspeed/modules/con_telemetry-data-collection-notice.adoc
  lightspeed/modules/con_view-manage-admin-dashboard-telemetry.adoc
  lightspeed/modules/proc_configure-vscode-extension-onpremise-deployment.adoc
  lightspeed/modules/proc_create-deploy-custom-model-ibm.adoc
  lightspeed/modules/proc_generate-playbook.adoc
  lightspeed/modules/proc_generate-training-data-set.adoc
  lightspeed/modules/proc_install-content-parser.adoc
  lightspeed/modules/proc_log-into-portal-auto-dev.adoc
  lightspeed/modules/proc_multi-task-recs.adoc
  lightspeed/modules/proc_single-task-recs.adoc
  lightspeed/modules/proc_start-lightspeed-trial.adoc
  lightspeed/modules/proc_troubleshooting-vscode.adoc
  lightspeed/modules/proc_view-playbook-explanation.adoc
  lightspeed/modules/proc_view-training-matches.adoc
  lightspeed/titles/lightspeed-user-guide/master.adoc
Labels: Ready for review, Lightspeed

#2903 2.5 Add restore procedure to Containerized installation (#2902)
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/platform/proc-backup-aap-container.adoc
  downstream/modules/platform/proc-restore-aap-container.adoc
  downstream/modules/platform/ref-general-inventory-variables.adoc
Labels: 2.5, Backported to 2.5

#2904 Correct custom resource definition
  downstream/modules/platform/ref-operator-crs.adoc
Labels: 2.5, Needs backport to 2.5

#2905 Correct custom resource definition (#2904)
  downstream/modules/platform/ref-operator-crs.adoc
Labels: 2.5, Backported to 2.5

#2907 AAP-38726 - Removed incorrect access notes for org admin for tokens/apps
  downstream/modules/platform/ref-gw-access-rules-apps-tokens.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#2910 [AAP-38821] Namespace-Scoped Deployments in OCP and Topology
  downstream/assemblies/platform/assembly-install-aap-operator.adoc
  downstream/modules/platform/proc-install-aap-operator.adoc
  downstream/modules/topologies/ref-ocp-a-env-a.adoc
Labels: documentation, 2.5, AAP operator

#2911 [AAP-38821] Namespace-Scoped Deployments in OCP and Topology (#2910)
  downstream/assemblies/platform/assembly-install-aap-operator.adoc
  downstream/modules/platform/proc-install-aap-operator.adoc
  downstream/modules/topologies/ref-ocp-a-env-a.adoc
Labels: documentation, 2.5, AAP operator

#2912 Add hstore proc to Containerized installation
  downstream/modules/platform/proc-enable-hstore-extension.adoc
  downstream/modules/platform/proc-setup-postgresql-ext-database-containerized.adoc
Labels: 2.5, Needs backport to 2.5

#2913 2.5 Add hstore proc to Containerized installation (#2912)
  downstream/modules/platform/proc-enable-hstore-extension.adoc
  downstream/modules/platform/proc-setup-postgresql-ext-database-containerized.adoc
Labels: 2.5, Backported to 2.5

#2909 AAP-38098: Added troubleshooting info. for controller API connection error
  downstream/assemblies/troubleshooting-aap/assembly-troubleshoot-upgrade.adoc
  downstream/modules/platform/con-aap-upgrade-planning.adoc
  downstream/modules/troubleshooting-aap/proc-troubleshoot-upgrade-issues.adoc
  downstream/titles/troubleshooting-aap/master.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#2916 AAP-40122 - Adding feedback and peer review changes to Post upgrade content
  downstream/assemblies/platform/assembly-aap-post-upgrade.adoc
  downstream/modules/platform/con-aap-migrate-normal-users.adoc
  downstream/modules/platform/proc-aap-migrate-SAML-users.adoc
  downstream/modules/platform/proc-aap-migrate-admin-users.adoc
Labels: Ready for review, 2.5, Backported to 2.5

#2918 AAP-32834 2.4 specific changes
  downstream/modules/platform/proc-install-aap-operator.adoc
Labels: documentation, 2.4, AAP operator

#2917 Adding CR details to Installing chapter
  downstream/modules/platform/proc-install-aap-operator.adoc
Labels: documentation, 2.5, AAP operator

#2919 Adding CR details to Installing chapter (#2917)
  downstream/modules/platform/proc-install-aap-operator.adoc
Labels: documentation, 2.5, AAP operator

#2923 [Backport] AAP-40122 - Adding feedback and peer review changes to Post upgrade content (#2916)
  downstream/assemblies/platform/assembly-aap-post-upgrade.adoc
  downstream/modules/platform/con-aap-migrate-normal-users.adoc
  downstream/modules/platform/proc-aap-migrate-SAML-users.adoc
  downstream/modules/platform/proc-aap-migrate-admin-users.adoc
Labels: Ready for review, 2.5

#2921 AAP-40078 updated important note
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
Labels: Ready for review, 2.5

#2924 AAP-40078 updated important note (#2921)
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
Labels: Ready for review, 2.5

#2925 AAP-39927 Added descriptions for the service level administrator checkboxes
  downstream/modules/platform/proc-gw-editing-a-user.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#2926 AAP-39927 Added descriptions for the service level administrator checkboxes (#2925)
  downstream/modules/platform/proc-gw-editing-a-user.adoc
Labels: Ready for review, 2.5

#2931 AAP-40325: updates ansible core version in EE guide
  downstream/modules/builder/con-about-ee.adoc
Labels: 2.5, Needs backport to 2.5

#2932 backport to 2.5: AAP-40325: updates ansible core version in EE guide (#2931)
  downstream/modules/builder/con-about-ee.adoc
Labels: 2.5

#2933 40016 - Adding post upgrade assembly to the OCP guide
  downstream/assemblies/platform/assembly-operator-upgrade.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#2934 Correct port no typo in CONT topologies
  downstream/modules/topologies/ref-cont-a-env-a.adoc
  downstream/modules/topologies/ref-cont-b-env-a.adoc
Labels: 2.5, Needs backport to 2.5

#2935 2.5 Correct port no typo in CONT topologies (#2934)
  downstream/modules/topologies/ref-cont-a-env-a.adoc
  downstream/modules/topologies/ref-cont-b-env-a.adoc
Labels: 2.5, Backported to 2.5

#2873 Adding Managing devices section to repo
  downstream/assemblies/platform/assembly-edge-manager-manage-devices.adoc
  downstream/assemblies/platform/assembly-edge-manager-troubleshooting.adoc
  downstream/modules/platform/con-edge-manager-access-devices.adoc
  downstream/modules/platform/proc-edge-manager-access-devices-cli.adoc
  downstream/modules/platform/proc-edge-manager-access-devices-web-ui.adoc
  downstream/modules/platform/proc-edge-manager-create-apps.adoc
  downstream/modules/platform/proc-edge-manager-generate-device-log.adoc
  downstream/modules/platform/proc-edge-manager-manage-apps-cli.adoc
  downstream/modules/platform/proc-edge-manager-manage-apps-ui.adoc
  downstream/modules/platform/proc-edge-manager-manage-apps.adoc
  downstream/modules/platform/proc-edge-manager-monitor-device-resources-cli.adoc
  downstream/modules/platform/proc-edge-manager-monitor-device-resources-web-ui.adoc
  downstream/modules/platform/proc-edge-manager-view-device-config.adoc
  downstream/modules/platform/ref-edge-manager-device-lifecycle.adoc
  downstream/modules/platform/ref-edge-manager-monitor-device.adoc
  downstream/titles/flight-control/flight-control-user-guide/master.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#2936 Adding Managing devices section to repo (#2873)
  downstream/assemblies/platform/assembly-edge-manager-manage-devices.adoc
  downstream/assemblies/platform/assembly-edge-manager-troubleshooting.adoc
  downstream/modules/platform/con-edge-manager-access-devices.adoc
  downstream/modules/platform/proc-edge-manager-access-devices-cli.adoc
  downstream/modules/platform/proc-edge-manager-access-devices-web-ui.adoc
  downstream/modules/platform/proc-edge-manager-create-apps.adoc
  downstream/modules/platform/proc-edge-manager-generate-device-log.adoc
  downstream/modules/platform/proc-edge-manager-manage-apps-cli.adoc
  downstream/modules/platform/proc-edge-manager-manage-apps-ui.adoc
  downstream/modules/platform/proc-edge-manager-manage-apps.adoc
  downstream/modules/platform/proc-edge-manager-monitor-device-resources-cli.adoc
  downstream/modules/platform/proc-edge-manager-monitor-device-resources-web-ui.adoc
  downstream/modules/platform/proc-edge-manager-view-device-config.adoc
  downstream/modules/platform/ref-edge-manager-device-lifecycle.adoc
  downstream/modules/platform/ref-edge-manager-monitor-device.adoc
  downstream/titles/flight-control/flight-control-user-guide/master.adoc
Labels: documentation, 2.5, Backported to 2.5

#2940 [Backport] 40016 - Adding post upgrade assembly to the OCP guide (#2933)
  downstream/assemblies/platform/assembly-operator-upgrade.adoc
Labels: Ready for review, 2.5

#2941 AAP-39910 - Added SME draft review feedback
  downstream/modules/platform/proc-aap-migrate-SAML-users.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#2942 [Backport] AAP-39910 - Added SME draft review feedback (#2941)
  downstream/modules/platform/proc-aap-migrate-SAML-users.adoc
Labels: Ready for review, 2.5

#2945 Edits for AAP-38748 (#2944)
  downstream/modules/platform/proc-create-keycloak-instance.adoc
  downstream/modules/platform/proc-operator-external-db-gateway.adoc
  downstream/modules/platform/ref-operator-crs.adoc
Labels: documentation, 2.5, AAP operator

#2946 AAP-40078 updated important note (#2921)
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
Labels: 2.3

#2948 AAP-40435 - Typo fix
  downstream/modules/platform/proc-operator-deploy-redis.adoc
Labels: documentation, 2.5, AAP operator

#2949 Typo fix (#2948)
  downstream/modules/platform/proc-operator-deploy-redis.adoc
Labels: documentation, 2.5, AAP operator

#2943 AAP-40425: updates admonition about container image pulls in Managing automation content
  downstream/assemblies/hub/assembly-populate-container-registry.adoc
Labels: Automation Hub, 2.5, Needs backport to 2.5

#2950 Backport to 2.5: AAP-4025 updates admonition about container image pulls in hub guide (#2943)
  downstream/assemblies/hub/assembly-populate-container-registry.adoc
Labels: Automation Hub, 2.5

#2951 Backport to 2.4: AAP-40425 updates admonition about container image pulls in hub guide (#2943)
  downstream/assemblies/hub/assembly-populate-container-registry.adoc
Labels: Automation Hub, 2.4

#2952 Backport to 2.3: AAP-40425 updates admonition for pulling container images
  downstream/assemblies/hub/assembly-populate-container-registry.adoc
Labels: 2.3, Automation Hub

#2953 AAP-37455 - added information for re-enabling the audience in keycloak
  downstream/modules/platform/proc-gw-config-keycloak-settings.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#2954 [Backport] AAP-37455 - added information for re-enabling the audience in keycloak (#2953)
  downstream/modules/platform/proc-gw-config-keycloak-settings.adoc
Labels: Ready for review, 2.5

#2955 Removing sections no longer required for 2.5 docs
  downstream/assemblies/platform/assembly-installing-hub-operator.adoc
  downstream/titles/aap-operator-installation/master.adoc
Labels: documentation, 2.5, AAP operator

#2956 Removing sections no longer required for 2.5 docs (#2955)
  downstream/assemblies/platform/assembly-installing-hub-operator.adoc
  downstream/titles/aap-operator-installation/master.adoc
Labels: documentation, 2.5, AAP operator

#2959 Fixing note formatting (#2958)
  downstream/modules/platform/ref-operator-crs.adoc
Labels: 2.5, AAP operator

#2696 AAP-36668 Update RPMs and EEs for Ansible Inside 1.3
  ansible-inside/topics/proc-ansible-inside-install-registry.adoc
  ansible-inside/topics/ref-ansible-inside-prereqs.adoc
Labels: Ansible Inside

#2939 Adding Edge manager config section to repo
  downstream/assemblies/platform/assembly-edge-manager-config.adoc
  downstream/modules/platform/ref-edge-manager-additional-fields.adoc
  downstream/modules/platform/ref-edge-manager-field-selectors.adoc
  downstream/modules/platform/ref-edge-manager-fields-discovery.adoc
  downstream/modules/platform/ref-edge-manager-supported-operators.adoc
  downstream/titles/flight-control/flight-control-user-guide/master.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#2960 Adding Edge manager config section to repo (#2939)
  downstream/assemblies/platform/assembly-edge-manager-config.adoc
  downstream/modules/platform/ref-edge-manager-additional-fields.adoc
  downstream/modules/platform/ref-edge-manager-field-selectors.adoc
  downstream/modules/platform/ref-edge-manager-fields-discovery.adoc
  downstream/modules/platform/ref-edge-manager-supported-operators.adoc
  downstream/titles/flight-control/flight-control-user-guide/master.adoc
Labels: documentation, 2.5, Backported to 2.5

#2961 Update port numbers in tested deployment models
  downstream/images/cont-b-env-a.png
  downstream/modules/topologies/ref-cont-a-env-a.adoc
  downstream/modules/topologies/ref-cont-b-env-a.adoc
  downstream/modules/topologies/ref-mesh-nodes.adoc
  downstream/modules/topologies/ref-ocp-a-env-a.adoc
  downstream/modules/topologies/ref-ocp-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-b.adoc
  downstream/modules/topologies/ref-rpm-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-b.adoc
Labels: 2.5, Needs backport to 2.5

#2963 Add Edge Manager install to AAP repo
  downstream/assemblies/platform/assembly-edge-manager-install.adoc
  downstream/titles/edge-manager/edge-manager-user-guide/aap-common
  downstream/titles/edge-manager/edge-manager-user-guide/attributes
  downstream/titles/edge-manager/edge-manager-user-guide/docinfo.xml
  downstream/titles/edge-manager/edge-manager-user-guide/images
  downstream/titles/edge-manager/edge-manager-user-guide/master.adoc
  downstream/titles/edge-manager/edge-manager-user-guide/platform
Labels: documentation, 2.5, Needs backport to 2.5

#2964 Add Edge Manager install to AAP repo (#2963)
  downstream/assemblies/platform/assembly-edge-manager-install.adoc
  downstream/titles/edge-manager/edge-manager-user-guide/aap-common
  downstream/titles/edge-manager/edge-manager-user-guide/attributes
  downstream/titles/edge-manager/edge-manager-user-guide/docinfo.xml
  downstream/titles/edge-manager/edge-manager-user-guide/images
  downstream/titles/edge-manager/edge-manager-user-guide/master.adoc
  downstream/titles/edge-manager/edge-manager-user-guide/platform
Labels: documentation, 2.5, Backported to 2.5

#2962 2.5 Update port numbers in tested deployment models (#2961)
  downstream/images/cont-b-env-a.png
  downstream/modules/topologies/ref-cont-a-env-a.adoc
  downstream/modules/topologies/ref-cont-b-env-a.adoc
  downstream/modules/topologies/ref-mesh-nodes.adoc
  downstream/modules/topologies/ref-ocp-a-env-a.adoc
  downstream/modules/topologies/ref-ocp-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-b.adoc
  downstream/modules/topologies/ref-rpm-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-b.adoc
Labels: 2.5, Backported to 2.5

#2957 Edits to creating a secret key section
  downstream/modules/platform/proc-create-secret-key-secret.adoc
Labels: documentation, 2.4, 2.5, AAP operator

#2968 AAP-39409 Ansible Inside Add directory for SVG files
  ansible-inside/images/svg/vscode-extensions-icon.svg
Labels: Ansible Inside

#2969 Edits to creating a secret key section (#2957)
  downstream/modules/platform/proc-create-secret-key-secret.adoc
Labels: documentation, 2.4, AAP operator

#2970 Edits to creating a secret key section (#2957)
  downstream/modules/platform/proc-create-secret-key-secret.adoc
Labels: documentation, 2.5, AAP operator

#2891 AAP-34926 updated Planning guide organization
  downstream/assemblies/platform/assembly-aap-platform-components.adoc
  downstream/titles/aap-planning-guide/master.adoc
Labels: Ready for review, Technical review complete, 2.5, Needs backport to 2.5

#2972 AAP-34926 updated Planning guide organization (#2891)
  downstream/assemblies/platform/assembly-aap-platform-components.adoc
  downstream/titles/aap-planning-guide/master.adoc
Labels: Ready for review, 2.5

#2973 AAP-34926A fixed typo
  downstream/assemblies/platform/assembly-aap-platform-components.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#2974 AAP-34926A fixed typo (#2973)
  downstream/assemblies/platform/assembly-aap-platform-components.adoc
Labels: Ready for review, 2.5

#2967 AAP-40475 - added link to demo video
  downstream/assemblies/platform/assembly-aap-post-upgrade.adoc
  downstream/modules/platform/con-aap-migrate-normal-users.adoc
  downstream/modules/platform/proc-aap-migrate-SAML-users.adoc
  downstream/modules/platform/proc-account-linking.adoc
Labels: 2.5, Needs backport to 2.5

#2976 [Backport] AAP-40475 - added link to demo video (#2967)
  downstream/assemblies/platform/assembly-aap-post-upgrade.adoc
  downstream/modules/platform/con-aap-migrate-normal-users.adoc
  downstream/modules/platform/proc-aap-migrate-SAML-users.adoc
  downstream/modules/platform/proc-account-linking.adoc
Labels: Ready for review, 2.5

#2977 AAP-40151 - added note about adding users and teams to organizations
  downstream/modules/platform/proc-controller-user-permissions.adoc
  downstream/modules/platform/ref-controller-user-roles.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#2980 [Backport] AAP-40151 - added note about adding users and teams to organizations (#2977)
  downstream/modules/platform/proc-controller-user-permissions.adoc
  downstream/modules/platform/ref-controller-user-roles.adoc
Labels: Ready for review, 2.5

#2981 AAP-40690: Corrected the auth_api_url value
  lightspeed/modules/proc_create-connection-secrets.adoc
Labels: Ready for review, Lightspeed

#2982 AAP-40686: AAP-40686: Updated the Lightspeed User Guide with latest IBM doc URLs
  lightspeed/modules/con_overview-lightspeed-onpremise.adoc
  lightspeed/modules/proc_create-connection-secrets.adoc
Labels: Ready for review, Lightspeed

#2983 Add rhel 8 to RPM topologies
  downstream/modules/topologies/ref-rpm-a-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-b.adoc
  downstream/modules/topologies/ref-rpm-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-b.adoc
Labels: 2.5, Needs backport to 2.5

#2987 Release notes for the 2.5.20250225 async release. (#2986)
  downstream/titles/release-notes/async/aap-25-20250225.adoc
  downstream/titles/release-notes/master.adoc
Labels: AAP Release notes, Backported to 2.5

#2988 Feb 25 async release notes - fix typo
  downstream/titles/release-notes/async/aap-25-20250225.adoc
Labels: AAP Release notes, 2.5, Backported to 2.5

#2989 2.5 Feb 25 async release notes - fix typo (#2988)
  downstream/titles/release-notes/async/aap-25-20250225.adoc
Labels: AAP Release notes, 2.5

#2985 Update using custom TLS certs ref
  downstream/modules/platform/ref-controller-variables.adoc
  downstream/modules/platform/ref-database-inventory-variables.adoc
  downstream/modules/platform/ref-eda-controller-variables.adoc
  downstream/modules/platform/ref-gateway-variables.adoc
  downstream/modules/platform/ref-receptor-inventory-variables.adoc
  downstream/modules/platform/ref-using-custom-tls-certificates.adoc
Labels: Technical review complete, 2.5, Needs backport to 2.5

#2994 Correct version in Controller UG
  downstream/modules/platform/ref-controller-proj-sign-prerequisites.adoc
Labels: 2.5, Needs backport to 2.5

#2995 Correct version in Controller UG (#2994)
  downstream/modules/platform/ref-controller-proj-sign-prerequisites.adoc
Labels: 2.5, Backported to 2.5

#2996 2.5 Update using custom TLS certs ref (#2985)
  downstream/modules/platform/ref-controller-variables.adoc
  downstream/modules/platform/ref-database-inventory-variables.adoc
  downstream/modules/platform/ref-eda-controller-variables.adoc
  downstream/modules/platform/ref-gateway-variables.adoc
  downstream/modules/platform/ref-receptor-inventory-variables.adoc
  downstream/modules/platform/ref-using-custom-tls-certificates.adoc
Labels: 2.5, Backported to 2.5

#2997 Update code-blocks in Containerized installation
  downstream/modules/platform/con-hs-eda-controller.adoc
  downstream/modules/platform/ref-containerized-troubleshoot-install.adoc
  downstream/modules/platform/ref-enabling-automation-hub-collection-and-container-signing.adoc
Labels: 2.5, Needs backport to 2.5

#2998 2.5 Update code-blocks in Containerized installation (#2997)
  downstream/modules/platform/con-hs-eda-controller.adoc
  downstream/modules/platform/ref-containerized-troubleshoot-install.adoc
  downstream/modules/platform/ref-enabling-automation-hub-collection-and-container-signing.adoc
Labels: 2.5, Backported to 2.5

#2922 Changes to hardening guide
  downstream/assemblies/aap-hardening/assembly-hardening-aap.adoc
  downstream/images/workflow.png
  downstream/modules/aap-hardening/con-automation-use-secrets.adoc
  downstream/modules/aap-hardening/con-compliance-profile-considerations.adoc
  downstream/modules/aap-hardening/con-credential-management-planning.adoc
  downstream/modules/aap-hardening/con-deployment-methods.adoc
  downstream/modules/aap-hardening/con-external-credential-vault.adoc
  downstream/modules/aap-hardening/con-logging-log-capture.adoc
  downstream/modules/aap-hardening/con-planning-considerations.adoc
  downstream/modules/aap-hardening/con-product-overview.adoc
  downstream/modules/aap-hardening/con-protect-sensitive-data-no-log.adoc
  downstream/modules/aap-hardening/con-rhel-host-planning.adoc
  downstream/modules/aap-hardening/proc-configure-centralized-logging.adoc
  downstream/modules/aap-hardening/proc-disaster-recovery-operations.adoc
  downstream/modules/aap-hardening/proc-fapolicyd.adoc
  downstream/modules/aap-hardening/proc-file-systems-mounted-noexec.adoc
  downstream/modules/aap-hardening/proc-install-user-pki.adoc
  downstream/modules/aap-hardening/proc-namespaces.adoc
  downstream/modules/aap-hardening/ref-aap-operational-secrets.adoc
  downstream/modules/aap-hardening/ref-architecture.adoc
  downstream/modules/aap-hardening/ref-infrastructure-as-code.adoc
  downstream/modules/aap-hardening/ref-interactive-session-timeout.adoc
  downstream/modules/aap-hardening/ref-ntp.adoc
  downstream/modules/aap-hardening/ref-security-variables-install-inventory.adoc
  downstream/modules/aap-hardening/ref-sudo-nopasswd.adoc
  downstream/modules/platform/proc-controller-set-up-logging.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#3000 Updating platform version with attribute
  downstream/modules/platform/proc-add-operator-execution-nodes.adoc
Labels: documentation, 2.5, AAP operator

#3001 Updating platform version with attribute (#3000)
  downstream/modules/platform/proc-add-operator-execution-nodes.adoc
Labels: documentation, 2.5, AAP operator

#3004 AAP-4020 - Updates to improve SAML configuration procedure
  downstream/modules/platform/proc-controller-set-up-SAML.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#3005 [Backport] AAP-4020 - Updates to improve SAML configuration procedure (#3004)
  downstream/modules/platform/proc-controller-set-up-SAML.adoc
Labels: Ready for review, 2.5

#3006 Fixed broken step formatting
  downstream/modules/platform/proc-controller-set-up-SAML.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#3007 [Backport] Fixed broken step formatting (#3006)
  downstream/modules/platform/proc-controller-set-up-SAML.adoc
Labels: Ready for review, 2.5

#3008 Further updates to access rules section
  downstream/modules/platform/ref-gw-access-rules-apps-tokens.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#3009 [Backport] Further updates to access rules section (#3008)
  downstream/modules/platform/ref-gw-access-rules-apps-tokens.adoc
Labels: Ready for review, 2.5
