Repository ansible/aap-docs, pull requests merged in 2025-10, with the labels that each got.

#4492 Updating AAP YAML for chapter 3.4 (#4491)
  downstream/modules/platform/ref-operator-crd-customize.adoc
Labels: 2.6

#4494 Replaced broken link with new link.
  downstream/modules/platform/ref-container-resource-requirements.adoc
Labels: documentation, 2.6, Needs backport to 2.6

#4495 Updates the RPM upgrade guide attributes
  downstream/attributes/attributes.adoc
Labels: Needs backport to 2.6

#4503 Updates broken links in various 2.6 guides
  downstream/assemblies/troubleshooting-aap/assembly-troubleshoot-playbooks.adoc
  downstream/modules/platform/proc-aap-generate-manifest-file.adoc
  downstream/modules/troubleshooting-aap/proc-troubleshoot-aap-packages.adoc
Labels: Needs backport to 2.5, Needs backport to 2.6

#4502 Fix release version in self-service install doc
  downstream/titles/self-service-install/docinfo.xml
Labels: 2.5

#4505 2.5 Updates broken links in various 2.6 guides (#4503)
  downstream/assemblies/troubleshooting-aap/assembly-troubleshoot-playbooks.adoc
  downstream/modules/platform/proc-aap-generate-manifest-file.adoc
  downstream/modules/troubleshooting-aap/proc-troubleshoot-aap-packages.adoc
Labels: Backported to 2.5

#4508 Post release update for planning your upgrade guide
  downstream/assemblies/platform/assembly-upgrade-faqs.adoc
Labels: 2.6, Needs backport to 2.6

#4509 Post release update for planning your upgrade guide (#4508)
  downstream/assemblies/platform/assembly-upgrade-faqs.adoc
Labels: 2.6

#4512 Fixing build issue for acccess management 2.5
  downstream/modules/platform/con-gw-overview-access-auth.adoc
  downstream/modules/platform/proc-aap-enable-disable-auth.adoc
Labels: 2.5

#4460 Update Attaching your subscription troubleshooting
  downstream/modules/platform/proc-attaching-subscriptions.adoc
Labels: Technical review complete, Needs backport to 2.5, Needs backport to 2.6

#4530 2.5 Update Attaching your subscription troubleshooting (#4460)
  downstream/modules/platform/proc-attaching-subscriptions.adoc
Labels: Backported to 2.5

#4532 AAP-44042 edits for custom host name (#4528)
  downstream/modules/platform/proc-configuring-controller-route-options.adoc
  downstream/modules/platform/proc-hub-route-options.adoc
Labels: 2.5

#4536 test-title creating new guide - performance tuning for aap (#4477)
  downstream/titles/performance-tuning/aap-common
  downstream/titles/performance-tuning/attributes
  downstream/titles/performance-tuning/docinfo.xml
  downstream/titles/performance-tuning/images
  downstream/titles/performance-tuning/master.adoc
  downstream/titles/performance-tuning/platform
  downstream/titles/performance-tuning/snippets
Labels: Ready for review, 2.6

#4537 test-title creating new guide - performance tuning for aap (#4477)
  downstream/titles/performance-tuning/aap-common
  downstream/titles/performance-tuning/attributes
  downstream/titles/performance-tuning/docinfo.xml
  downstream/titles/performance-tuning/images
  downstream/titles/performance-tuning/master.adoc
  downstream/titles/performance-tuning/platform
  downstream/titles/performance-tuning/snippets
Labels: Ready for review, 2.5

#4542 AAP-54924 edits (#4534)
  downstream/assemblies/platform/assembly-operator-configure-gateway.adoc
  downstream/modules/platform/ref-operator-aap-faq.adoc
  downstream/modules/platform/ref-operator-crd-customize.adoc
Labels: 2.5

#4544 Backport-2.5-4526 to AAP-46228 Pre-migration work EDA user guide, Chapter 12
  downstream/assemblies/eda/assembly-eda-event-filter-plugins.adoc
  downstream/modules/eda/con-eda-author-event-filters.adoc
Labels: documentation, Ready for review, 2.5, Needs backport to 2.5, Migration

#4547 AAP-46228 Pre-migration work EDA user guide, Chapter 13
  downstream/assemblies/eda/assembly-eda-logging-strategy.adoc
  downstream/modules/eda/ref-eda-logging-samples.adoc
Labels: documentation, Ready for review, 2.5, Needs backport to 2.5, Migration, 2.6, Needs backport to 2.6

#4554 Backport-2.5-4547 to AAP-46230 Pre-migration work EDA user guide, Chapter 13
  downstream/assemblies/eda/assembly-eda-logging-strategy.adoc
  downstream/modules/eda/ref-eda-logging-samples.adoc
Labels: documentation, Ready for review, 2.5, Needs backport to 2.5, Migration

#4555 Backport-2.6-4547 to AAP-46230 Pre-migration work EDA user guide, Chapter 13
  downstream/assemblies/eda/assembly-eda-logging-strategy.adoc
  downstream/modules/eda/ref-eda-logging-samples.adoc
Labels: documentation, Ready for review, Migration, 2.6, Needs backport to 2.6

#4564 Added file again.
  downstream/modules/platform/proc-configure-pg-extra-settings.adoc
Labels: documentation, AAP operator, 2.6, Backported to 2.6

#4567 2.5 backport: AAP-54971: Adds note about collection size limit for uploading to hub docs
  downstream/modules/hub/proc-uploading-collections.adoc
Labels: Automation Hub, 2.5

#4568 2.6 backport: AAP-54971: Adds note about collection size limit for uploading to hub…
  downstream/modules/hub/proc-uploading-collections.adoc
Labels: Automation Hub, 2.6

#4566 AAP 55092: Fix Xrefs in GS with Hasi/AAP guide
  downstream/modules/terraform-aap/proc-terraform-migrating-from-community.adoc
Labels: documentation, Ready for review, 2.5, Needs backport to 2.5, 2.6, Needs backport to 2.6

#4570 Backport 2.5: AAP 55092: Fix Xrefs in GS with Hasi/AAP guide (#4566)
  downstream/modules/terraform-aap/proc-terraform-migrating-from-community.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#4571 Backport 2.6: AAP 55092: Fix Xrefs in GS with Hasi/AAP guide (#4566)
  downstream/modules/terraform-aap/proc-terraform-migrating-from-community.adoc
Labels: documentation, 2.6, Needs backport to 2.6

#4573 2.5 backport: AAP-55095: updates language around subscriptions, removes references …
  downstream/assemblies/platform/assembly-gateway-licensing.adoc
  downstream/modules/platform/ref-controller-node-counting.adoc
  downstream/modules/platform/ref-controller-trial-evaluation.adoc
Labels: 2.5

#4572 2.6 backport: AAP-55095: updates language around subscriptions, removes references to licenses
  downstream/assemblies/platform/assembly-gateway-licensing.adoc
  downstream/modules/platform/ref-controller-node-counting.adoc
  downstream/modules/platform/ref-controller-trial-evaluation.adoc
Labels: 2.6

#4578 2.5 Updates Renewing and changing SSL certs (#4576)
  downstream/archive/archived-modules/platform/proc-change-ssl-controller.adoc
  downstream/archive/archived-modules/platform/proc-change-ssl-eda-controller.adoc
  downstream/archive/archived-modules/platform/proc-change-ssl-hub.adoc
  downstream/assemblies/platform/assembly-changing-ssl-certs-keys.adoc
  downstream/modules/platform/proc-change-ssl-installer.adoc
  downstream/modules/platform/proc-change-ssl-manual-rpm.adoc
  downstream/modules/platform/proc-renew-ssl-cert.adoc
Labels: Backported to 2.5

#4579 Backup and Restore CQA edits (#4574)
  downstream/assemblies/platform/assembly-aap-backup.adoc
  downstream/assemblies/platform/assembly-aap-recovery.adoc
  downstream/modules/platform/proc-aap-platform-ext-DB-restore.adoc
  downstream/modules/platform/proc-aap-platform-gateway-backup.adoc
  downstream/modules/platform/proc-aap-platform-gateway-restore.adoc
  downstream/modules/platform/proc-aap-platform-pvc-restore.adoc
  downstream/modules/platform/proc-troubleshoot-same-name.adoc
Labels: 2.6

#4584 AAP-55160 updated playbook (#4581)
  downstream/modules/automation-dashboard/proc-installing-automation-dashboard.adoc
  downstream/modules/automation-dashboard/proc-integrating-automation-dashboard.adoc
Labels: 2.4

#4585 Add containerized install to VM-mesh description (#4575)
  downstream/modules/platform/con-install-mesh.adoc
  downstream/modules/platform/proc-editing-inventory-file.adoc
  downstream/modules/platform/proc-running-setup-script.adoc
Labels: 2.6, Backported to 2.6

#4533 Self-service: Clarify RBAC
  downstream/assemblies/devtools/assembly-self-service-about.adoc
  downstream/modules/devtools/con-self-service-customize-template.adoc
  downstream/modules/devtools/proc-rhdh-create.adoc
  downstream/modules/devtools/proc-self-service-add-template.adoc
  downstream/modules/devtools/proc-self-service-set-up-rbac.adoc
  downstream/modules/devtools/ref-self-service-interactive-demo.adoc
Labels: 2.5, Needs backport to 2.5, 2.6, Needs backport to 2.6

#4598 ocp-perf-guide-cqa (#4596)
  downstream/assemblies/platform/assembly-configure-controller-OCP.adoc
  downstream/assemblies/platform/assembly-control-plane-adjustments.adoc
  downstream/assemblies/platform/assembly-pod-spec-modifications.adoc
  downstream/assemblies/platform/assembly-specify-dedicated-nodes.adoc
  downstream/modules/platform/con-alternative-capacity-limits.adoc
  downstream/modules/platform/con-pod-specification-mods.adoc
  downstream/modules/platform/proc-configure-controller-OCP.adoc
  downstream/modules/platform/proc-customizing-pod-specs.adoc
  downstream/modules/platform/proc-enable-pods-ref-images.adoc
  downstream/modules/platform/proc-specify-nodes-job-execution.adoc
  downstream/modules/platform/ref-assign-pods-to-nodes.adoc
  downstream/modules/platform/ref-container-resource-requirements.adoc
  downstream/modules/platform/ref-requests-limits.adoc
  downstream/modules/platform/ref-resource-management-pods-containers.adoc
  downstream/modules/platform/ref-resource-types.adoc
  downstream/modules/platform/ref-schedule-jobs-worker-nodes.adoc
  downstream/modules/platform/ref-set-custom-pod-timeout.adoc
  downstream/modules/platform/ref-set-requests-limits-for-containers.adoc
Labels: 2.5

#4602 2.5 release notes - update portal name
  downstream/attributes/attributes.adoc
  downstream/titles/release-notes/topics/aap-25.adoc
  downstream/titles/release-notes/topics/tech-preview.adoc
Labels: AAP Release notes, 2.5

#4599 Clearing confusion.
  downstream/modules/platform/proc-operator-upgrade.adoc
Labels: documentation, 2.5, AAP operator, Needs backport to 2.5, 2.6, Needs backport to 2.6

#4490 AAP-51774: Formatting for DITA migration
  downstream/assemblies/hub/assembly-collections-and-content-signing-in-pah.adoc
  downstream/assemblies/hub/assembly-container-user-access.adoc
  downstream/assemblies/hub/assembly-managing-private-collections.adoc
  downstream/assemblies/hub/assembly-syncing-to-cloud-repo.adoc
  downstream/assemblies/hub/assembly-synclists.adoc
  downstream/assemblies/hub/assembly-validated-content.adoc
  downstream/assemblies/hub/assembly-working-with-namespaces.adoc
  downstream/assemblies/hub/assembly-working-with-signed-containers.adoc
  downstream/modules/hub/con-approval-pipeline.adoc
  downstream/modules/hub/con-approval.adoc
  downstream/modules/hub/con-repo-rbac.adoc
  downstream/modules/hub/con-token-management-hub.adoc
  downstream/modules/hub/proc-adding-an-execution-environment.adoc
  downstream/modules/hub/proc-adding-collections-repository.adoc
  downstream/modules/hub/proc-adding-containers-remotely-to-the-automation-hub.adoc
  downstream/modules/hub/proc-approve-collection.adoc
  downstream/modules/hub/proc-configure-ansible-galaxy-cli-verify.adoc
  downstream/modules/hub/proc-configure-content-signing-on-pah.adoc
  downstream/modules/hub/proc-configuring-the-client-to-verify-signatures.adoc
  downstream/modules/hub/proc-create-api-token-pah.adoc
  downstream/modules/hub/proc-create-api-token.adoc
  downstream/modules/hub/proc-create-content-developers.adoc
  downstream/modules/hub/proc-create-credential.adoc
  downstream/modules/hub/proc-create-namespace.adoc
  downstream/modules/hub/proc-create-remote.adoc
  downstream/modules/hub/proc-create-repository.adoc
  downstream/modules/hub/proc-create-requirements-file.adoc
  downstream/modules/hub/proc-create-synclist.adoc
  downstream/modules/hub/proc-delete-collection.adoc
  downstream/modules/hub/proc-delete-namespace.adoc
  downstream/modules/hub/proc-deploying-your-system-for-container-signing.adoc
  downstream/modules/hub/proc-downloading-signature-public-keys.adoc
  downstream/modules/hub/proc-edit-namespace.adoc
  downstream/modules/hub/proc-export-collection.adoc
  downstream/modules/hub/proc-import-collection.adoc
  downstream/modules/hub/proc-offline-token-active.adoc
  downstream/modules/hub/proc-provide-remote-access.adoc
  downstream/modules/hub/proc-provide-repository-access.adoc
  downstream/modules/hub/proc-pushing-container-images-from-your-local.adoc
  downstream/modules/hub/proc-reject-collections.adoc
  downstream/modules/hub/proc-revert-repository-version.adoc
  downstream/modules/hub/proc-review-collection-imports.adoc
  downstream/modules/hub/proc-set-community-remote.adoc
  downstream/modules/hub/proc-set-rhcertified-remote.adoc
  downstream/modules/hub/proc-sync-image.adoc
  downstream/modules/hub/proc-uploading-collections.adoc
  downstream/modules/hub/proc-using-content-signing-services-in-pah.adoc
  downstream/modules/hub/proc-using-podman-ensure-image-signed.adoc
  downstream/modules/hub/proc-using-policies-with-signed-images.adoc
  downstream/modules/platform/proc-adding-a-subscription.adoc
Labels: Not ready for peer review, 2.5, Needs backport to 2.5, Migration, 2.6, Needs backport to 2.6

#4611 Remove smart inventory reference (#4610)
  downstream/modules/platform/con-controller-benefits-fact-caching.adoc
Labels: 2.6, Backported to 2.6

#4612 Remove smart inventory reference (#4610)
  downstream/modules/platform/con-controller-benefits-fact-caching.adoc
Labels: 2.5, Backported to 2.5

#4613 Backport - accept incoming changes - AAP-54930
  downstream/modules/platform/proc-operator-upgrade.adoc
Labels: documentation, 2.5, AAP operator, Backported to 2.5

#4614 Backport - Clearing confusion. (#4599) -AAP-54930
  downstream/modules/platform/proc-operator-upgrade.adoc
Labels: documentation, AAP operator, 2.6, Backported to 2.6

#4616 Correct values
  downstream/assemblies/platform/assembly-controller-ee-setup-reference.adoc
  downstream/modules/platform/ref-controller-config-options.adoc
  downstream/modules/platform/ref-controller-ee-configuration-options.adoc
Labels: Controller, 2.5, Needs backport to 2.5, 2.6, Needs backport to 2.6

#4619 Fixing command typo in aap-migration (#4615)
  downstream/modules/aap-migration/proc-ocp-target-import.adoc
Labels: 2.6

#4621 2.6 Updates the Ansible Automation Platform migration guide (#4618)
  downstream/modules/aap-migration/con-artifact-structure.adoc
  downstream/modules/aap-migration/con-containerized-to-ocp-prerequisites.adoc
  downstream/modules/aap-migration/con-manifest-file.adoc
  downstream/modules/aap-migration/con-rpm-to-containerized-prerequisites.adoc
  downstream/modules/aap-migration/con-rpm-to-ocp-prerequisites.adoc
  downstream/modules/aap-migration/con-secrets-file.adoc
  downstream/modules/aap-migration/proc-containerized-post-import.adoc
  downstream/modules/aap-migration/proc-containerized-source-environment-export.adoc
  downstream/modules/aap-migration/proc-containerized-target-import.adoc
  downstream/modules/aap-migration/proc-containerized-target-prep.adoc
  downstream/modules/aap-migration/proc-containerized-validation.adoc
  downstream/modules/aap-migration/proc-managed-post-import.adoc
  downstream/modules/aap-migration/proc-ocp-target-import.adoc
  downstream/modules/aap-migration/proc-rpm-source-environment-export.adoc
  downstream/modules/aap-migration/ref-migration-artifact-checklist.adoc
Labels: Backported to 2.6

#4625 Correct values (#4616)
  downstream/assemblies/platform/assembly-controller-ee-setup-reference.adoc
  downstream/modules/platform/ref-controller-config-options.adoc
  downstream/modules/platform/ref-controller-ee-configuration-options.adoc
Labels: 2.5, Backported to 2.5

#4628 Updating managing auth chapter (#4624)
  downstream/assemblies/platform/assembly-gw-managing-authentication.adoc
  downstream/modules/platform/con-gw-gcp-network-port-limits.adoc
  downstream/modules/platform/proc-gw-gcp-increase-port-limits.adoc
Labels: 2.5, Backported to 2.5

#4631 Containerized installation doc updates
  downstream/assemblies/platform/assembly-upgrade-infrastructure-changes.adoc
  downstream/modules/aap-migration/con-introduction-and-objectives.adoc
  downstream/modules/aap-migration/proc-ocp-target-import.adoc
  downstream/modules/platform/proc-backup-aap-container.adoc
  downstream/modules/platform/proc-configure-haproxy-load-balancer.adoc
  downstream/modules/platform/proc-configure-local-repo-reposync.adoc
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/platform/proc-restore-aap-container.adoc
  downstream/modules/platform/proc-update-aap-container.adoc
  downstream/modules/platform/ref-configuring-inventory-file.adoc
  downstream/modules/platform/ref-cont-aap-system-requirements.adoc
  downstream/snippets/cont-tested-system-config.adoc
  downstream/titles/release-notes/topics/aap-26.adoc
Labels: Needs backport to 2.5, Needs backport to 2.6

#4638 Backport - Editing attribute to view. (#4635)
  downstream/modules/builder/proc-installing-builder.adoc
Labels: documentation, 2.6, Backported to 2.6

#4639 AAP-55074 - Changed the attribute to 2.6
  downstream/modules/builder/proc-installing-builder.adoc
Labels: documentation, 2.6, Needs backport to 2.6

#4603 2.5 release notes: add portal known issues
  downstream/titles/release-notes/topics/aap-25-known-issues.adoc
Labels: AAP Release notes, 2.5

#4601 2.6 Release notes: add issues for self-service
  downstream/titles/release-notes/topics/aap-26-known-issues.adoc
Labels: AAP Release notes, 2.6
