Repository ansible/aap-docs, pull requests merged in 2025-03, with the labels that each got.

#3002 Creating Private link Assembly and modules
  attributes/attributes.adoc
  stories/assembly-saas-private-link.adoc
  stories/topics/con-saas-how-private-link-works.adoc
  stories/topics/con-saas-private-link-benefits.adoc
  stories/topics/proc-saas-enabling-aws-privatelink.adoc
  titles/saas-aws/stories.adoc
Labels: documentation, AAP on clouds, Ansible on AWS

#3012 Adding auto_upgrade instructions
  downstream/modules/platform/proc-operator-deploy-central-config.adoc
Labels: documentation, 2.5, AAP operator, Needs backport to 2.5

#3014 Adding auto_upgrade instructions (#3012)
  downstream/modules/platform/proc-operator-deploy-central-config.adoc
Labels: documentation, 2.5, AAP operator

#3011 Add async release notes 20250305
  downstream/titles/release-notes/async/aap-25-20250305.adoc
  downstream/titles/release-notes/master.adoc
Labels: Technical review complete, AAP Release notes, 2.5, Needs backport to 2.5

#3016 2.5 Add async release notes 20250305 (#3011)
  downstream/titles/release-notes/async/aap-25-20250305.adoc
  downstream/titles/release-notes/master.adoc
Labels: AAP Release notes, 2.5, Backported to 2.5

#2975 AAP-36148: adds note reminding users that basic auth/service accounts are not supported for hub authentication
  downstream/modules/hub/con-token-management-hub.adoc
Labels: Automation Hub, 2.5, Needs backport to 2.5

#3017 [BP 2.5] AAP-36148: adds note reminding users that basic auth/service accounts…
  downstream/modules/hub/con-token-management-hub.adoc
Labels: Automation Hub, 2.5

#3018 [Bp 2.4] AAP-36148: adds note reminding users that basic auth/service accounts are not supported in hub
  downstream/assemblies/hub/assembly-hub-create-api-token.adoc
Labels: Automation Hub, 2.4

#3019 AAP-36632-rn: Updated Lightspeed Release Notes URLs
  lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-11dec2024.adoc
  lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-15feb2024.adoc
  lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-7march2024.adoc
  lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-june2024.adoc
Labels: Ready for review, Lightspeed

#3015 Adding Git Hub app token proc
  downstream/assemblies/platform/assembly-controller-secret-management.adoc
  downstream/modules/platform/proc-controller-configure-secret-lookups.adoc
  downstream/modules/platform/proc-controller-github-app-token.adoc
Labels: documentation, Controller, 2.5, Needs backport to 2.5

#3020 Adding Git Hub app token proc (#3015)
  downstream/assemblies/platform/assembly-controller-secret-management.adoc
  downstream/modules/platform/proc-controller-configure-secret-lookups.adoc
  downstream/modules/platform/proc-controller-github-app-token.adoc
Labels: 2.5, Backported to 2.5

#3021 Added note about search restriction
  downstream/assemblies/platform/assembly-ug-controller-job-templates.adoc
  downstream/modules/platform/ref-controller-search-tips.adoc
Labels: 2.5, Needs backport to 2.5

#2990 Update hub inventory vars
  downstream/modules/platform/ref-hub-variables.adoc
Labels: Technical review complete, 2.5, Needs backport to 2.5

#3025 Automation hub variables - Appendix Inventory file variables improvem…
  downstream/modules/platform/ref-hub-variables.adoc
Labels: 2.5, Needs backport to 2.5

#3026 2.5 Automation hub variables - Appendix Inventory file variables improvem…
  downstream/modules/platform/ref-hub-variables.adoc
Labels: 2.5, Backported to 2.5

#3029 Move websocket content to controller admin
  downstream/assemblies/platform/assembly-controller-improving-performance.adoc
  downstream/modules/platform/con-websocket-setup.adoc
  downstream/modules/platform/proc-configuring-discovery.adoc
  downstream/titles/aap-operations-guide/master.adoc
Labels: documentation, Controller, 2.5, Needs backport to 2.5

#3030 Move websocket content to controller admin (#3029)
  downstream/assemblies/platform/assembly-controller-improving-performance.adoc
  downstream/modules/platform/con-websocket-setup.adoc
  downstream/modules/platform/proc-configuring-discovery.adoc
  downstream/titles/aap-operations-guide/master.adoc
Labels: documentation, Controller, 2.5, Backported to 2.5

#3036 Yaml fix - AAP-40548 (#3034)
  downstream/modules/platform/proc-create-secret-key-secret.adoc
Labels: documentation, 2.5, AAP operator

#3031 Adding system requirements notes
  downstream/assemblies/platform/assembly-install-aap-operator.adoc
  downstream/modules/platform/con-about-operator.adoc
  downstream/modules/platform/con-operator-upgrade-prereq.adoc
Labels: documentation, 2.5, AAP operator, Needs backport to 2.5

#3035 Further edits to GitHub App config
  downstream/images/credentials-create-github-app-lookup-credential.png
  downstream/images/credentials-github-app-target-secret-info.png
  downstream/images/project-create-git-github-app.png
  downstream/images/project-sync-github-app.png
  downstream/modules/platform/proc-controller-github-app-token.adoc
Labels: documentation, Controller, 2.5, Needs backport to 2.5

#3040 Move encrypting passwords to controller admin.
  downstream/assemblies/platform/assembly-controller-improving-performance.adoc
  downstream/modules/platform/ref-encrypting-plaintext-passwords.adoc
  downstream/titles/aap-operations-guide/master.adoc
Labels: documentation, Controller, 2.5, Needs backport to 2.5

#3041 Move encrypting passwords to controller admin. (#3040)
  downstream/assemblies/platform/assembly-controller-improving-performance.adoc
  downstream/modules/platform/ref-encrypting-plaintext-passwords.adoc
  downstream/titles/aap-operations-guide/master.adoc
Labels: 2.5, Backported to 2.5

#3033 AAP-40672 Devtools - modify devcontainer creation
  downstream/modules/devtools/proc-devtools-install-container.adoc
Labels: 2.5, Needs backport to 2.5

#3042 2.5 AAP-40672 Devtools - modify devcontainer creation (#3033)
  downstream/modules/devtools/proc-devtools-install-container.adoc
Labels: 2.5

#3043 2.4 AAP-40672 Devtools - modify devcontainer creation (#3033)
  downstream/modules/devtools/proc-devtools-install-container.adoc
Labels: 2.4

#3046 AAP-40555 edits (#3032)
  downstream/assemblies/platform/assembly-aap-migration.adoc
  downstream/modules/platform/proc-aap-create-aap-object.adoc
  downstream/modules/platform/proc-aap-migration.adoc
Labels: documentation, 2.5, AAP operator

#2965 Adding first 5 sections to managing devices section
  downstream/assemblies/platform/assembly-edge-manager-manage-devices.adoc
  downstream/modules/platform/con-edge-manager-enroll.adoc
  downstream/modules/platform/con-edge-manager-labels.adoc
  downstream/modules/platform/con-edge-manager-manage-os-config.adoc
  downstream/modules/platform/con-edge-manager-update-os.adoc
  downstream/modules/platform/con-edge-manager-view-devices.adoc
  downstream/modules/platform/proc-edge-manager-enroll-device-cli.adoc
  downstream/modules/platform/proc-edge-manager-update-labels.adoc
  downstream/modules/platform/proc-edge-manager-update-os-cli.adoc
  downstream/modules/platform/proc-edge-manager-view-device-inventory.adoc
  downstream/modules/platform/proc-edge-manager-view-devices-cli.adoc
  downstream/modules/platform/ref-edge-manager-monitor-device.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#3047 Adding first 5 sections to managing devices section (#2965)
  downstream/assemblies/platform/assembly-edge-manager-manage-devices.adoc
  downstream/modules/platform/con-edge-manager-enroll.adoc
  downstream/modules/platform/con-edge-manager-labels.adoc
  downstream/modules/platform/con-edge-manager-manage-os-config.adoc
  downstream/modules/platform/con-edge-manager-update-os.adoc
  downstream/modules/platform/con-edge-manager-view-devices.adoc
  downstream/modules/platform/proc-edge-manager-enroll-device-cli.adoc
  downstream/modules/platform/proc-edge-manager-update-labels.adoc
  downstream/modules/platform/proc-edge-manager-update-os-cli.adoc
  downstream/modules/platform/proc-edge-manager-view-device-inventory.adoc
  downstream/modules/platform/proc-edge-manager-view-devices-cli.adoc
  downstream/modules/platform/ref-edge-manager-monitor-device.adoc
Labels: documentation, 2.5, Backported to 2.5

#3048 Remove port from diagram and table
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
  downstream/images/aap-network-ports-protocols.png
Labels: 2.5, Needs backport to 2.5

#3049 Remove port from diagram and table (#3048)
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
  downstream/images/aap-network-ports-protocols.png
Labels: 2.5, Backported to 2.5

#3052 Correct port service type
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
Labels: 2.5, Needs backport to 2.5

#3053 Correct port service type (#3052)
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
Labels: 2.5, Backported to 2.5

#3054 AAP-41404 Update devtools RPM installation
  downstream/modules/devtools/proc-devtools-install-rpm.adoc
Labels: Needs backport to 2.4, 2.5, Needs backport to 2.5

#3058 Update install proc for Containerized installation
  downstream/modules/platform/proc-downloading-containerized-aap.adoc
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc
Labels: 2.5, Needs backport to 2.5

#3059 2.5 Update install proc for Containerized installation (#3058)
  downstream/modules/platform/proc-downloading-containerized-aap.adoc
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/platform/proc-preparing-the-rhel-host-for-containerized-installation.adoc
Labels: 2.5, Backported to 2.5

#3065 AAP-40833 edits
  downstream/assemblies/platform/assembly-installing-hub-operator.adoc
  downstream/modules/platform/proc-aap-add-allowed-registries.adoc
Labels: documentation, 2.4, 2.5, AAP operator

#3067 AAP-40833 edits (#3065)
  downstream/assemblies/platform/assembly-installing-hub-operator.adoc
  downstream/modules/platform/proc-aap-add-allowed-registries.adoc
Labels: documentation, 2.5, AAP operator

#3066 AAP-40833 2.4 edits
  downstream/assemblies/platform/assembly-using-rhsso-operator-with-automation-hub.adoc
  downstream/modules/platform/proc-aap-add-allowed-registries.adoc
Labels: documentation, 2.4, AAP operator

#3024 Adding note about connecting steps in WF visualizer
  downstream/modules/platform/proc-controller-build-workflow.adoc
Labels: documentation, Controller, 2.5, Needs backport to 2.5

#3068 Adding note about connecting steps in WF visualizer (#3024)
  downstream/modules/platform/proc-controller-build-workflow.adoc
Labels: documentation, Controller, 2.5

#3070 Add callout for RHEL support in aap-docs
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/platform/ref-system-requirements.adoc
  downstream/modules/topologies/ref-cont-a-env-a.adoc
  downstream/modules/topologies/ref-cont-b-env-a.adoc
  downstream/modules/topologies/ref-ocp-a-env-a.adoc
  downstream/modules/topologies/ref-ocp-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-b.adoc
  downstream/modules/topologies/ref-rpm-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-b.adoc
  downstream/snippets/cont-tested-system-config.adoc
  downstream/snippets/cont-tested-vm-config.adoc
Labels: 2.5, Needs backport to 2.5

#3071 2.5 Add callout for RHEL support in aap-docs (#3070)
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/platform/ref-system-requirements.adoc
  downstream/modules/topologies/ref-cont-a-env-a.adoc
  downstream/modules/topologies/ref-cont-b-env-a.adoc
  downstream/modules/topologies/ref-ocp-a-env-a.adoc
  downstream/modules/topologies/ref-ocp-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-b.adoc
  downstream/modules/topologies/ref-rpm-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-b.adoc
  downstream/snippets/cont-tested-system-config.adoc
  downstream/snippets/cont-tested-vm-config.adoc
Labels: 2.5, Backported to 2.5

#2818 AAP-36381 - add required statement to User Permanent ID field
  downstream/modules/platform/proc-controller-set-up-SAML.adoc
Labels: 2.5, Needs backport to 2.5

#3044 Update controller inventory vars
  downstream/modules/platform/ref-controller-variables.adoc
Labels: Ready for technical review, 2.5, Needs backport to 2.5

#3075 Adding Edge Manager intro/overview to docs (#2991)
  downstream/assemblies/platform/assembly-edge-manager-intro.adoc
  downstream/modules/platform/con-edge-manager-core-capabilities.adoc
  downstream/titles/edge-manager/edge-manager-user-guide/master.adoc
Labels: documentation, 2.5, Backported to 2.5

#3076 AAP-41879 - Adding new regions
  stories/topics/con-saas-backup-and-diaster-recovery.adoc
Labels: documentation, AAP on clouds, Ansible on AWS, SaaS on AWS

#3077 Correct diagrams and port numbers
  downstream/images/cont-b-env-a.png
  downstream/images/rpm-b-env-a.png
  downstream/modules/topologies/ref-cont-a-env-a.adoc
  downstream/modules/topologies/ref-cont-b-env-a.adoc
  downstream/modules/topologies/ref-mesh-nodes.adoc
  downstream/modules/topologies/ref-ocp-a-env-a.adoc
  downstream/modules/topologies/ref-ocp-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-b.adoc
  downstream/modules/topologies/ref-rpm-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-b.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#3078 Correct diagrams and port numbers (#3077)
  downstream/images/cont-b-env-a.png
  downstream/images/rpm-b-env-a.png
  downstream/modules/topologies/ref-cont-a-env-a.adoc
  downstream/modules/topologies/ref-cont-b-env-a.adoc
  downstream/modules/topologies/ref-mesh-nodes.adoc
  downstream/modules/topologies/ref-ocp-a-env-a.adoc
  downstream/modules/topologies/ref-ocp-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-b.adoc
  downstream/modules/topologies/ref-rpm-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-b.adoc
Labels: 2.5, Backported to 2.5

#3082 Add verification to containerized install proc
  downstream/archive/archived-modules/platform/ref-accessing-control-auto-hub-eda-control.adoc
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/platform/proc-reinstalling-containerized-aap.adoc
  downstream/modules/platform/proc-uninstalling-containerized-aap.adoc
  downstream/modules/platform/ref-gateway-variables.adoc
Labels: 2.5, Needs backport to 2.5

#3083 2.5 Add verification to containerized install proc (#3082)
  downstream/archive/archived-modules/platform/ref-accessing-control-auto-hub-eda-control.adoc
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/platform/proc-reinstalling-containerized-aap.adoc
  downstream/modules/platform/proc-uninstalling-containerized-aap.adoc
  downstream/modules/platform/ref-gateway-variables.adoc
Labels: 2.5, Backported to 2.5

#2979 Adding k8s section to Edge Manager doc
  downstream/assemblies/platform/assembly-edge-manager-config.adoc
  downstream/assemblies/platform/assembly-edge-manager-intro.adoc
  downstream/modules/platform/ref-edge-manager-auth-resources.adoc
  downstream/modules/platform/ref-edge-manager-rbac-auth.adoc
  downstream/modules/platform/ref-edge-manager-rbac-roles.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#3084 Adding service account info to controller docs (#2978)
  downstream/modules/platform/proc-controller-configure-analytics.adoc
  downstream/modules/platform/proc-controller-create-insights-credential.adoc
Labels: documentation, Controller, 2.5, Backported to 2.5

#3087 Removing Insights updates from service account work (#3086)
  downstream/modules/platform/proc-controller-create-insights-credential.adoc
Labels: documentation, Controller, 2.5, Backported to 2.5

#3088 Fix broken links in hardening guide
  downstream/modules/aap-hardening/con-planning-considerations.adoc
  downstream/modules/platform/proc-controller-set-up-logging.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#3089 Fix broken links in hardening guide (#3088)
  downstream/modules/aap-hardening/con-planning-considerations.adoc
  downstream/modules/platform/proc-controller-set-up-logging.adoc
Labels: 2.5, Backported to 2.5

#3092 AAP-42122: Fixed typo in topologies
  downstream/titles/topologies/docinfo.xml
Labels: documentation, Ready for review, 2.5, Needs backport to 2.5

#3093 Backport-2.5-3092: AAP-42122 Fixed typo in topologies (#3092)
  downstream/titles/topologies/docinfo.xml
Labels: documentation, 2.5

#3091 Update jump host information
  downstream/modules/platform/ref-controller-set-up-jump-host.adoc
Labels: documentation, Controller, 2.5, Needs backport to 2.5

#3094 Update jump host information (#3091)
  downstream/modules/platform/ref-controller-set-up-jump-host.adoc
Labels: 2.5, Backported to 2.5

#3079 Adding RHEM architecture section to repo
  downstream/assemblies/platform/assembly-edge-manager-architecture.adoc
  downstream/modules/platform/con-edge-manager-agent-service.adoc
  downstream/modules/platform/con-edge-manager-api-server.adoc
  downstream/titles/edge-manager/edge-manager-user-guide/master.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#3098 Adding RHEM architecture section to repo (#3079)
  downstream/assemblies/platform/assembly-edge-manager-architecture.adoc
  downstream/modules/platform/con-edge-manager-agent-service.adoc
  downstream/modules/platform/con-edge-manager-api-server.adoc
  downstream/titles/edge-manager/edge-manager-user-guide/master.adoc
Labels: documentation, 2.5, Backported to 2.5

#3057 Adding final sections to manage devices chapter
  downstream/assemblies/platform/assembly-edge-manager-manage-devices.adoc
  downstream/modules/platform/con-edge-manager-config-providers.adoc
  downstream/modules/platform/proc-edge-manager-update-os-cli.adoc
  downstream/modules/platform/ref-edge-manager-K8s-cluster.adoc
  downstream/modules/platform/ref-edge-manager-config-git-repo.adoc
  downstream/modules/platform/ref-edge-manager-config-http.adoc
  downstream/modules/platform/ref-edge-manager-config-inline.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#3099 Adding final sections to manage devices chapter (#3057)
  downstream/assemblies/platform/assembly-edge-manager-manage-devices.adoc
  downstream/modules/platform/con-edge-manager-config-providers.adoc
  downstream/modules/platform/proc-edge-manager-update-os-cli.adoc
  downstream/modules/platform/ref-edge-manager-K8s-cluster.adoc
  downstream/modules/platform/ref-edge-manager-config-git-repo.adoc
  downstream/modules/platform/ref-edge-manager-config-http.adoc
  downstream/modules/platform/ref-edge-manager-config-inline.adoc
Labels: documentation, 2.5, Backported to 2.5

#3101 Add attributes for topologies (#3100)
  downstream/assemblies/platform/assembly-aap-architecture.adoc
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/assemblies/topologies/assembly-overview-tested-deployment-models.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/platform/ref-configuring-inventory-file.adoc
  downstream/modules/topologies/ref-cont-a-env-a.adoc
  downstream/modules/topologies/ref-cont-b-env-a.adoc
  downstream/modules/topologies/ref-ocp-a-env-a.adoc
  downstream/modules/topologies/ref-ocp-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-a.adoc
  downstream/modules/topologies/ref-rpm-a-env-b.adoc
  downstream/modules/topologies/ref-rpm-b-env-a.adoc
  downstream/modules/topologies/ref-rpm-b-env-b.adoc
  downstream/snippets/enterprise-topologies.adoc
  downstream/snippets/growth-topologies.adoc
  downstream/snippets/mixed-topologies.adoc
  downstream/titles/release-notes/topics/aap-25.adoc
Labels: 2.5, Backported to 2.5

#3102 Adding authentication section to RHEM doc
  downstream/assemblies/platform/assembly-edge-manager-config.adoc
  downstream/assemblies/platform/assembly-edge-manager-rbac-auth.adoc
  downstream/titles/edge-manager/edge-manager-user-guide/master.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#3103 Adding authentication section to RHEM doc (#3102)
  downstream/assemblies/platform/assembly-edge-manager-config.adoc
  downstream/assemblies/platform/assembly-edge-manager-rbac-auth.adoc
  downstream/titles/edge-manager/edge-manager-user-guide/master.adoc
Labels: documentation, 2.5, Backported to 2.5

#3104 Update "Using custom TLS certificates" in Containerized installation
  downstream/modules/platform/ref-using-custom-tls-certificates.adoc
Labels: 2.5, Needs backport to 2.5

#3105 2.5 Update "Using custom TLS certificates" in Containerized installation …
  downstream/modules/platform/ref-using-custom-tls-certificates.adoc
Labels: 2.5, Backported to 2.5

#3108 Adding RHEM device enrollment chapter
  downstream/assemblies/platform/assembly-edge-manager-device-enroll.adoc
  downstream/modules/platform/con-edge-manager-enroll-meth.adoc
  downstream/titles/edge-manager/edge-manager-user-guide/master.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#3109 Adding RHEM device enrollment chapter (#3108)
  downstream/assemblies/platform/assembly-edge-manager-device-enroll.adoc
  downstream/modules/platform/con-edge-manager-enroll-meth.adoc
  downstream/titles/edge-manager/edge-manager-user-guide/master.adoc
Labels: documentation, 2.5, Backported to 2.5

#3003 Adding service account info to 2.4 docs
  downstream/modules/platform/proc-controller-create-insights-credential.adoc
  downstream/modules/platform/ref-controller-automation-analytics.adoc
Labels: documentation, Controller, 2.4

#3111 AAP-39112: Developed docs for Lightspeed REST API
  lightspeed/assemblies/assembly_administering-ansible-lightspeed.adoc
  lightspeed/assemblies/assembly_configuring-lightspeed-onpremise.adoc
  lightspeed/assemblies/assembly_starting-lightspeed-trial.adoc
  lightspeed/modules/con_overview-lightspeed-onpremise.adoc
  lightspeed/modules/proc_monitor-onpremise-deployment.adoc
  lightspeed/modules/proc_multi-task-recs.adoc
  lightspeed/modules/proc_remove-seat-licenses.adoc
  lightspeed/modules/proc_use-rest-api.adoc
Labels: Ready for review, Lightspeed

#3106 AAP-38389 Ext DB upgrade edits
  downstream/assemblies/platform/assembly-configure-aap-operator.adoc
  downstream/modules/platform/proc-operator-upgrade-external-db-gateway.adoc
Labels: documentation, Draft, 2.5, AAP operator, Needs backport to 2.5

#3112 AAP-38389 Ext DB upgrade edits (#3106)
  downstream/assemblies/platform/assembly-configure-aap-operator.adoc
  downstream/modules/platform/proc-operator-upgrade-external-db-gateway.adoc
Labels: documentation, 2.5, AAP operator

#3113 Adding ca-central-1 and it's backup us-east-2
  stories/topics/con-saas-backup-and-diaster-recovery.adoc
Labels: documentation, AAP on clouds, SaaS on AWS

#3107 Update and refactor Operations Guide
  downstream/assemblies/platform/assembly-aap-activate.adoc
  downstream/assemblies/platform/assembly-changing-ssl-certs-keys.adoc
  downstream/assemblies/platform/assembly-configure-egress-proxy.adoc
  downstream/assemblies/platform/assembly-configuring-proxy-support.adoc
  downstream/modules/hub/proc-set-community-remote.adoc
  downstream/modules/platform/con-known-proxies.adoc
  downstream/modules/platform/con-sticky-sessions.adoc
  downstream/modules/platform/proc-change-ssl-controller.adoc
  downstream/modules/platform/proc-change-ssl-installer.adoc
  downstream/modules/platform/proc-configure-known-proxies.adoc
  downstream/modules/platform/proc-configuring-reverse-proxy.adoc
  downstream/modules/platform/proc-controller-proxy-settings.adoc
  downstream/modules/platform/proc-enable-proxy-support.adoc
  downstream/modules/platform/proc-proxy-AWS-inventory-sync.adoc
  downstream/modules/platform/proc-renew-ssl-cert.adoc
  downstream/modules/platform/proc-set-EDA-proxy.adoc
  downstream/modules/platform/ref-automation-mesh-proxy.adoc
  downstream/modules/platform/ref-system-proxy-config.adoc
  downstream/modules/platform/ref_proxy-backends.adoc
  downstream/titles/aap-operations-guide/master.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#3114 Update and refactor Operations Guide (#3107)
  downstream/assemblies/platform/assembly-aap-activate.adoc
  downstream/assemblies/platform/assembly-changing-ssl-certs-keys.adoc
  downstream/assemblies/platform/assembly-configure-egress-proxy.adoc
  downstream/assemblies/platform/assembly-configuring-proxy-support.adoc
  downstream/modules/hub/proc-set-community-remote.adoc
  downstream/modules/platform/con-known-proxies.adoc
  downstream/modules/platform/con-sticky-sessions.adoc
  downstream/modules/platform/proc-change-ssl-controller.adoc
  downstream/modules/platform/proc-change-ssl-installer.adoc
  downstream/modules/platform/proc-configure-known-proxies.adoc
  downstream/modules/platform/proc-configuring-reverse-proxy.adoc
  downstream/modules/platform/proc-controller-proxy-settings.adoc
  downstream/modules/platform/proc-enable-proxy-support.adoc
  downstream/modules/platform/proc-proxy-AWS-inventory-sync.adoc
  downstream/modules/platform/proc-renew-ssl-cert.adoc
  downstream/modules/platform/proc-set-EDA-proxy.adoc
  downstream/modules/platform/ref-automation-mesh-proxy.adoc
  downstream/modules/platform/ref-system-proxy-config.adoc
  downstream/modules/platform/ref_proxy-backends.adoc
  downstream/titles/aap-operations-guide/master.adoc
Labels: documentation, 2.5, Backported to 2.5

#3110 AAP-34928: Developed docs for create and explain roles
  lightspeed/assemblies/assembly_developing-ansible-content.adoc
  lightspeed/images/lightspeed-role-explanation.png
  lightspeed/modules/con_role-creation.adoc
  lightspeed/modules/proc_create-roles.adoc
  lightspeed/modules/proc_view-role-explanation.adoc
  lightspeed/titles/lightspeed-release-notes/master.adoc
  lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-20march2025.adoc
Labels: Ready for review, Lightspeed

#3117 AAP-41743 Missing Information About Port 8443 being required for EDA in Network port table
  downstream/assemblies/platform/assembly-network-ports-protocols.adoc
Labels: documentation, Ready for review, Ready for technical review, 2.5, Needs backport to 2.5

#3115 AAP-42064: Add unmasking requirements to gateway for RPM Installation …
  downstream/modules/platform/ref-gateway-system-requirements.adoc
Labels: documentation, Ready for review, 2.5, Needs backport to 2.5

#3119 AAP-39133: Added backup procedure with new compression variables
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
  downstream/modules/platform/con-backup-aap.adoc
  downstream/modules/platform/ref-general-inventory-variables.adoc
Labels: Ready for review, Technical review complete, 2.5, Needs backport to 2.5

#3121 Backport-2.5-42064 for AAP-42064: Add unmasking requirements to gateway for RPM Installation…
  downstream/modules/platform/ref-gateway-system-requirements.adoc
Labels: documentation, Ready for review, 2.5

#3122 AAP-34928-update: Added URLs in release notes blurb
  lightspeed/modules/proc_configure-vscode-extension.adoc
  lightspeed/titles/lightspeed-release-notes/modules/lightspeed-rn-20march2025.adoc
Labels: Ready for review, Lightspeed

#3123 Backport pull request #3119 from main to AAP 2.5
  downstream/assemblies/platform/assembly-platform-install-scenario.adoc
  downstream/modules/platform/con-backup-aap.adoc
  downstream/modules/platform/ref-general-inventory-variables.adoc
Labels: 2.5, Backported to 2.5

#3010 AAP-36737 - Improvements to the authentication mapping content
  downstream/assemblies/platform/assembly-gw-mapping.adoc
  downstream/images/am-apple-team.png
  downstream/images/am-do-not-escalate-privileges.png
  downstream/images/am-escalate-privileges.png
  downstream/images/am-mapping-order.png
  downstream/images/am-org-mapping-full-annotation.png
  downstream/images/am-org-mapping.png
  downstream/modules/platform/con-gw-authenticator-map-examples.adoc
  downstream/modules/platform/con-gw-authenticator-map-triggers.adoc
  downstream/modules/platform/con-gw-review-mapping-results.adoc
  downstream/modules/platform/con-gw-understanding-authenticator-mapping.adoc
  downstream/modules/platform/proc-gw-adjust-mapping-order.adoc
  downstream/modules/platform/proc-gw-allow-mapping.adoc
  downstream/modules/platform/ref-controller-organization-mapping.adoc
  downstream/modules/platform/ref-controller-team-mapping.adoc
  downstream/snippets/snip-gw-authentication-additional-auth-fields.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#3124 AAP-41494 - Add new Auto migrate users setting to auth procedures
  downstream/modules/platform/proc-controller-github-enterprise-org-settings.adoc
  downstream/modules/platform/proc-controller-github-enterprise-settings.adoc
  downstream/modules/platform/proc-controller-github-enterprise-team-settings.adoc
  downstream/modules/platform/proc-controller-github-organization-settings.adoc
  downstream/modules/platform/proc-controller-github-settings.adoc
  downstream/modules/platform/proc-controller-github-team-settings.adoc
  downstream/modules/platform/proc-controller-google-oauth2-settings.adoc
  downstream/modules/platform/proc-controller-set-up-LDAP.adoc
  downstream/modules/platform/proc-controller-set-up-SAML.adoc
  downstream/modules/platform/proc-controller-set-up-azure.adoc
  downstream/modules/platform/proc-controller-set-up-generic-oidc.adoc
  downstream/modules/platform/proc-controller-set-up-radius.adoc
  downstream/modules/platform/proc-controller-set-up-tacacs+.adoc
  downstream/modules/platform/proc-gw-config-keycloak-settings.adoc
  downstream/modules/platform/proc-gw-local-authentication.adoc
  downstream/snippets/snip-gw-authentication-auto-migrate.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#3116 Adding device fleets chapter to RHEM doc
  downstream/assemblies/platform/assembly-edge-manager-device-fleets.adoc
  downstream/modules/platform/proc-edge-manager-select-devices.adoc
  downstream/modules/platform/ref-edge-manager-device-selection.adoc
  downstream/modules/platform/ref-edge-manager-device-templates.adoc
  downstream/titles/edge-manager/edge-manager-user-guide/master.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#3129 Adding device fleets chapter to RHEM doc (#3116)
  downstream/assemblies/platform/assembly-edge-manager-device-fleets.adoc
  downstream/modules/platform/proc-edge-manager-select-devices.adoc
  downstream/modules/platform/ref-edge-manager-device-selection.adoc
  downstream/modules/platform/ref-edge-manager-device-templates.adoc
  downstream/titles/edge-manager/edge-manager-user-guide/master.adoc
Labels: documentation, 2.5, Backported to 2.5

#3132 [Backport] AAP-36737 - Improvements to the authentication mapping content (#3010)
  downstream/assemblies/platform/assembly-gw-mapping.adoc
  downstream/images/am-apple-team.png
  downstream/images/am-do-not-escalate-privileges.png
  downstream/images/am-escalate-privileges.png
  downstream/images/am-mapping-order.png
  downstream/images/am-org-mapping-full-annotation.png
  downstream/images/am-org-mapping.png
  downstream/modules/platform/con-gw-authenticator-map-examples.adoc
  downstream/modules/platform/con-gw-authenticator-map-triggers.adoc
  downstream/modules/platform/con-gw-review-mapping-results.adoc
  downstream/modules/platform/con-gw-understanding-authenticator-mapping.adoc
  downstream/modules/platform/proc-gw-adjust-mapping-order.adoc
  downstream/modules/platform/proc-gw-allow-mapping.adoc
  downstream/modules/platform/ref-controller-organization-mapping.adoc
  downstream/modules/platform/ref-controller-team-mapping.adoc
  downstream/snippets/snip-gw-authentication-additional-auth-fields.adoc
Labels: Ready for review, 2.5

#3133 [Backport] AAP-41494 - Add new Auto migrate users field to auth procedures (#3124)
  downstream/modules/platform/proc-controller-github-enterprise-org-settings.adoc
  downstream/modules/platform/proc-controller-github-enterprise-settings.adoc
  downstream/modules/platform/proc-controller-github-enterprise-team-settings.adoc
  downstream/modules/platform/proc-controller-github-organization-settings.adoc
  downstream/modules/platform/proc-controller-github-settings.adoc
  downstream/modules/platform/proc-controller-github-team-settings.adoc
  downstream/modules/platform/proc-controller-google-oauth2-settings.adoc
  downstream/modules/platform/proc-controller-set-up-LDAP.adoc
  downstream/modules/platform/proc-controller-set-up-SAML.adoc
  downstream/modules/platform/proc-controller-set-up-azure.adoc
  downstream/modules/platform/proc-controller-set-up-generic-oidc.adoc
  downstream/modules/platform/proc-controller-set-up-radius.adoc
  downstream/modules/platform/proc-controller-set-up-tacacs+.adoc
  downstream/modules/platform/proc-gw-config-keycloak-settings.adoc
  downstream/modules/platform/proc-gw-local-authentication.adoc
  downstream/snippets/snip-gw-authentication-auto-migrate.adoc
Labels: Ready for review, 2.5

#3134 AAP-42276: Fixed broken link to containerized installation requirements
  downstream/modules/platform/ref-containerized-system-requirements.adoc
Labels: documentation, Ready for review, 2.5, Needs backport to 2.5

#3136 Fixing formatting issues with the access management guide
  downstream/images/am-apple-team-map-example.png
  downstream/modules/platform/con-gw-understanding-authenticator-mapping.adoc
  downstream/modules/platform/proc-aap-generate-manifest-file.adoc
Labels: 2.5, Needs backport to 2.5

#3137 [Backport] Fixing formatting issues with the access management guide (#3136)
  downstream/images/am-apple-team-map-example.png
  downstream/modules/platform/con-gw-understanding-authenticator-mapping.adoc
  downstream/modules/platform/proc-aap-generate-manifest-file.adoc
Labels: 2.5

#3130 Adding building images chapter to RHEM doc
  downstream/assemblies/platform/assembly-edge-manager-images-.adoc
  downstream/modules/platform/con-edge-manager-buildtime-runtime.adoc
  downstream/modules/platform/con-edge-manager-drop-dir.adoc
  downstream/modules/platform/con-edge-manager-os-img-script.adoc
  downstream/modules/platform/con-edge-manager-usr-dir.adoc
  downstream/modules/platform/proc-edge-manager-image-build.adoc
  downstream/modules/platform/ref-edge-manager-images-special-considerations.adoc
  downstream/titles/edge-manager/edge-manager-user-guide/master.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#3138 Adding building images chapter to RHEM doc (#3130)
  downstream/assemblies/platform/assembly-edge-manager-images-.adoc
  downstream/modules/platform/con-edge-manager-buildtime-runtime.adoc
  downstream/modules/platform/con-edge-manager-drop-dir.adoc
  downstream/modules/platform/con-edge-manager-os-img-script.adoc
  downstream/modules/platform/con-edge-manager-usr-dir.adoc
  downstream/modules/platform/proc-edge-manager-image-build.adoc
  downstream/modules/platform/ref-edge-manager-images-special-considerations.adoc
  downstream/titles/edge-manager/edge-manager-user-guide/master.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#3139 Backport-2.5-3134 for AAP-42276: Fixed broken link to containerized installation requiremen…
  downstream/modules/platform/ref-containerized-system-requirements.adoc
Labels: documentation, Ready for review, 2.5, Needs backport to 2.5

#3141 Adding procedure section of RHEM building images
  downstream/assemblies/platform/assembly-edge-manager-images.adoc
  downstream/modules/platform/con-edge-manager-build-prereq.adoc
  downstream/modules/platform/con-edge-manager-build.adoc
  downstream/modules/platform/proc-edge-manager-build-bootc-image.adoc
  downstream/modules/platform/proc-edge-manager-build-sign-image.adoc
  downstream/modules/platform/proc-edge-manager-image-pullsecrets.adoc
  downstream/modules/platform/proc-edge-manager-install-CLI.adoc
  downstream/modules/platform/proc-edge-manager-request-cert.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#3142 Adding procedure section of RHEM building images (#3141)
  downstream/assemblies/platform/assembly-edge-manager-images.adoc
  downstream/modules/platform/con-edge-manager-build-prereq.adoc
  downstream/modules/platform/con-edge-manager-build.adoc
  downstream/modules/platform/proc-edge-manager-build-bootc-image.adoc
  downstream/modules/platform/proc-edge-manager-build-sign-image.adoc
  downstream/modules/platform/proc-edge-manager-image-pullsecrets.adoc
  downstream/modules/platform/proc-edge-manager-install-CLI.adoc
  downstream/modules/platform/proc-edge-manager-request-cert.adoc
Labels: documentation, 2.5, Backported to 2.5

#3144 AAP-42027: Added automation controller v4.5 in upgrade prerequirements
  downstream/assemblies/platform/assembly-aap-upgrading-platform.adoc
  downstream/modules/platform/con-aap-upgrade-planning.adoc
  downstream/modules/platform/proc-upgrade-controller-hub-eda-unified-ui.adoc
Labels: 2.5, Needs backport to 2.5

#3143 AAP-42061: Removed extra "s" from Getting Started guide
  downstream/modules/platform/con-gs-execution-env.adoc
Labels: documentation, Ready for review, 2.5, Needs backport to 2.5

#3146 Backport-2.5-3143: AAP-42061 - Removed extra s from Getting Started guide (#3143)
  downstream/modules/platform/con-gs-execution-env.adoc
Labels: documentation, Ready for review, 2.5, Needs backport to 2.5

#3145 Backport pull request #3144 from main to 2.5
  downstream/assemblies/platform/assembly-aap-upgrading-platform.adoc
  downstream/modules/platform/con-aap-upgrade-planning.adoc
  downstream/modules/platform/proc-upgrade-controller-hub-eda-unified-ui.adoc
Labels: Ready for review, 2.5, Backported to 2.5

#3148 AAP-42467
  stories/topics/con-saas-encryption.adoc
Labels: documentation, AAP on clouds, SaaS on AWS

#3149 Fixing titles to be uniform
  downstream/assemblies/platform/assembly-installing-aap-operator-cli.adoc
  downstream/assemblies/platform/assembly-operator-upgrade.adoc
  downstream/assemblies/platform/assembly-update-ocp.adoc
Labels: documentation, 2.5, AAP operator

#3150 Fixing titles to be uniform (#3149)
  downstream/assemblies/platform/assembly-installing-aap-operator-cli.adoc
  downstream/assemblies/platform/assembly-operator-upgrade.adoc
  downstream/assemblies/platform/assembly-update-ocp.adoc
Labels: documentation, 2.5, AAP operator

#3126 AAP-40573 release notes - ansible plug-ins
  downstream/titles/release-notes/async/aap-25-20250312.adoc
  downstream/titles/release-notes/topics/aap-25-fixed-issues.adoc
Labels: Needs backport to 2.4, AAP Release notes, Needs backport to 2.5

#3151 Correct typo
  downstream/modules/aap-hardening/ref-interactive-session-timeout.adoc
Labels: AAP Hardening, 2.5, Backported to 2.5

#3153 Correct typo (#3151)
  downstream/modules/aap-hardening/ref-interactive-session-timeout.adoc
Labels: AAP Hardening, 2.5, Backported to 2.5

#3147 AAP-37305 Document how to copy an existing rulebook activation
  downstream/assemblies/eda/assembly-eda-rulebook-activations.adoc
  downstream/modules/eda/proc-eda-copy-rulebook-activation.adoc
Labels: documentation, Ready for technical review, Not ready for peer review, 2.5, Needs backport to 2.5

#3160 AAP-42232 - Add External application link details
  downstream/assemblies/platform/assembly-controller-applications.adoc
  downstream/modules/platform/proc-controller-create-application.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#3162 Adding final sections to RHEM building images
  downstream/modules/platform/proc-edge-manager-sign-disk-image.adoc
  downstream/modules/platform/proc-edge-manager-virt.adoc
  downstream/modules/platform/proc-edge-manager-vmware.adoc
  downstream/modules/platform/ref-edge-manager-platform-requirements.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#3164 Adding final sections to RHEM building images (#3162)
  downstream/modules/platform/proc-edge-manager-sign-disk-image.adoc
  downstream/modules/platform/proc-edge-manager-virt.adoc
  downstream/modules/platform/proc-edge-manager-vmware.adoc
  downstream/modules/platform/ref-edge-manager-platform-requirements.adoc
Labels: 2.5, Backported to 2.5

#3165 Update structure of Containerized installation
  downstream/assemblies/platform/assembly-aap-containerized-installation.adoc
  downstream/modules/platform/proc-backup-aap-container.adoc
  downstream/modules/platform/proc-configure-haproxy-load-balancer.adoc
  downstream/modules/platform/proc-cont-aap-hub-storage.adoc
  downstream/modules/platform/proc-downloading-containerized-aap.adoc
  downstream/modules/platform/proc-installing-containerized-aap.adoc
  downstream/modules/platform/proc-restore-aap-container.adoc
  downstream/modules/platform/proc-update-aap-container.adoc
  downstream/modules/platform/ref-configuring-inventory-file.adoc
  downstream/modules/platform/ref-cont-aap-system-requirements.adoc
  downstream/snippets/inventory-cont-a-env-a.adoc
Labels: 2.5, Needs backport to 2.5

#3170 [Backport] AAP-42232 - Add External application link details (#3160)
  downstream/assemblies/platform/assembly-controller-applications.adoc
  downstream/modules/platform/proc-controller-create-application.adoc
Labels: Ready for review, 2.5

#3171 AAP-42638: removes info about analytics opt-in in first login process
  downstream/modules/platform/proc-gs-logging-in.adoc
Labels: Analytics, 2.5, Needs backport to 2.5

#3172 Backport to 2.5:AAP-42638 removes info about analytics opt-in in first login process (#3171)
  downstream/modules/platform/proc-gs-logging-in.adoc
Labels: Analytics, 2.5

#3161 AAP-41292 connectivity clarity edits
  stories/topics/con-saas-automation.adoc
  stories/topics/ref-saas-egress-model.adoc
  stories/topics/ref-saas-mesh-ingress-model.adoc
Labels: documentation, AAP on clouds, Ansible on AWS, SaaS on AWS

#3174 Conditionalize assembly to include in two guides (#3173)
  downstream/assemblies/platform/assembly-aap-activate.adoc
Labels: 2.5, Backported to 2.5

#3167 Adding provisioning section to RHEM doc
  downstream/assemblies/platform/assembly-edge-manager-provisioning-devices.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/platform/con-edge-manager-provisioning-openshift-virt.adoc
  downstream/modules/platform/con-edge-manager-provisioning-physical.adoc
  downstream/modules/platform/proc-edge-manager-provision-cloudinit-config.adoc
  downstream/modules/platform/proc-edge-manager-provision-virt-create.adoc
  downstream/titles/edge-manager/edge-manager-user-guide/master.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#3175 Adding provisioning section to RHEM doc (#3167)
  downstream/assemblies/platform/assembly-edge-manager-provisioning-devices.adoc
  downstream/attributes/attributes.adoc
  downstream/modules/platform/con-edge-manager-provisioning-openshift-virt.adoc
  downstream/modules/platform/con-edge-manager-provisioning-physical.adoc
  downstream/modules/platform/proc-edge-manager-provision-cloudinit-config.adoc
  downstream/modules/platform/proc-edge-manager-provision-virt-create.adoc
  downstream/titles/edge-manager/edge-manager-user-guide/master.adoc
Labels: documentation, 2.5, Backported to 2.5

#3181 41494 - removed details about migrating via the API
  downstream/modules/platform/proc-aap-migrate-SAML-users.adoc
Labels: Ready for review, 2.5, Needs backport to 2.5

#3182 [Backport] - 41494 - removed details about migrating via the API (#3181)
  downstream/modules/platform/proc-aap-migrate-SAML-users.adoc
Labels: Ready for review, 2.5, Backported to 2.5

#3125 Update database inventory vars
  downstream/modules/platform/ref-database-inventory-variables.adoc
Labels: Technical review complete, 2.5, Needs backport to 2.5

#3184 2.5 Update database inventory vars (#3125)
  downstream/modules/platform/ref-database-inventory-variables.adoc
Labels: 2.5, Backported to 2.5

#3185 AAP-39432 edits
  downstream/modules/platform/proc-configuring-controller-ldap-security.adoc
Labels: documentation, 2.5, AAP operator, Needs backport to 2.5

#3187 corrects formatting
  downstream/modules/platform/ref-database-inventory-variables.adoc
Labels: 2.5, Needs backport to 2.5

#3188 2.5 corrects formatting (#3187)
  downstream/modules/platform/ref-database-inventory-variables.adoc
Labels: 2.5, Backported to 2.5

#3186 AAP-39432 edits (#3185)
  downstream/modules/platform/proc-configuring-controller-ldap-security.adoc
Labels: documentation, 2.5, AAP operator

#3189 Managing devices chapter edits (#3176)
  downstream/assemblies/platform/assembly-edge-manager-architecture.adoc
  downstream/assemblies/platform/assembly-edge-manager-config.adoc
  downstream/assemblies/platform/assembly-edge-manager-manage-apps.adoc
  downstream/assemblies/platform/assembly-edge-manager-manage-devices.adoc
  downstream/modules/platform/con-edge-manager-device-enroll.adoc
  downstream/modules/platform/con-edge-manager-enroll-meth.adoc
  downstream/modules/platform/con-edge-manager-enroll.adoc
  downstream/modules/platform/con-edge-manager-labels.adoc
  downstream/modules/platform/con-edge-manager-manage-os-config.adoc
  downstream/modules/platform/con-edge-manager-view-devices.adoc
  downstream/modules/platform/proc-edge-manager-enroll-device-cli.adoc
  downstream/modules/platform/proc-edge-manager-view-devices-cli.adoc
  downstream/modules/platform/ref-edge-manager-additional-fields.adoc
  downstream/modules/platform/ref-edge-manager-field-selectors.adoc
  downstream/modules/platform/ref-edge-manager-fields-discovery.adoc
  downstream/titles/edge-manager/edge-manager-user-guide/master.adoc
Labels: documentation, 2.5, Backported to 2.5

#3140 Update inventory vars for images vars
  downstream/modules/platform/ref-images-inventory-variables.adoc
Labels: Technical review complete, 2.5, Needs backport to 2.5

#3191 2.5 Update inventory vars for images vars (#3140)
  downstream/modules/platform/ref-images-inventory-variables.adoc
Labels: 2.5, Backported to 2.5

#3192 Adding second part of Manage devices section
  downstream/assemblies/platform/assembly-edge-manager-install.adoc
  downstream/assemblies/platform/assembly-edge-manager-manage-devices.adoc
  downstream/modules/platform/con-edge-manager-manage-os-config.adoc
  downstream/modules/platform/con-edge-manager-rbac-auth.adoc
  downstream/modules/platform/proc-edge-manager-config-git-cli.adoc
  downstream/modules/platform/proc-edge-manager-monitor-device-resources-cli.adoc
  downstream/modules/platform/proc-edge-manager-sign-disk-image.adoc
  downstream/modules/platform/ref-edge-manager-auth-resources.adoc
  downstream/modules/platform/ref-edge-manager-config-inline.adoc
  downstream/modules/platform/ref-edge-manager-device-lifecycle.adoc
  downstream/modules/platform/ref-edge-manager-monitor-device.adoc
  downstream/modules/platform/ref-edge-manager-rule-files.adoc
  downstream/titles/edge-manager/edge-manager-user-guide/master.adoc
Labels: documentation, 2.5, Needs backport to 2.5

#3193 Adding second part of Manage devices section (#3192)
  downstream/assemblies/platform/assembly-edge-manager-install.adoc
  downstream/assemblies/platform/assembly-edge-manager-manage-devices.adoc
  downstream/modules/platform/con-edge-manager-manage-os-config.adoc
  downstream/modules/platform/con-edge-manager-rbac-auth.adoc
  downstream/modules/platform/proc-edge-manager-config-git-cli.adoc
  downstream/modules/platform/proc-edge-manager-monitor-device-resources-cli.adoc
  downstream/modules/platform/proc-edge-manager-sign-disk-image.adoc
  downstream/modules/platform/ref-edge-manager-auth-resources.adoc
  downstream/modules/platform/ref-edge-manager-config-inline.adoc
  downstream/modules/platform/ref-edge-manager-device-lifecycle.adoc
  downstream/modules/platform/ref-edge-manager-monitor-device.adoc
  downstream/modules/platform/ref-edge-manager-rule-files.adoc
  downstream/titles/edge-manager/edge-manager-user-guide/master.adoc
Labels: documentation, 2.5, Backported to 2.5

#3194 Update DB requirements for Containerized installation
  downstream/modules/platform/proc-setup-postgresql-ext-database-containerized.adoc
  downstream/modules/platform/ref-cont-aap-system-requirements.adoc
Labels: 2.5, Needs backport to 2.5

#3195 2.5 Update DB requirements for Containerized installation (#3194)
  downstream/modules/platform/proc-setup-postgresql-ext-database-containerized.adoc
  downstream/modules/platform/ref-cont-aap-system-requirements.adoc
Labels: 2.5, Backported to 2.5
