Repository ansible/aap-docs, pull requests merged in 2025-08, with the labels that each got.

#3969 Menu formatting fix
  downstream/modules/platform/proc-controller-review-organizations.adoc
Labels: 2.5, 2.6

#3970 Bp to 2.5: fixes menu formatting in one module (#3969)
  downstream/modules/platform/proc-controller-review-organizations.adoc
Labels: 2.5

#3971 bp to 2.6: fixes menu formatting in one module (#3969)
  downstream/modules/platform/proc-controller-review-organizations.adoc
Labels: 2.6

#3981 DITA migration changes: CAG Ch13
  downstream/assemblies/platform/assembly-controller-secret-management.adoc
  downstream/modules/platform/proc-controller-configure-secret-lookups.adoc
  downstream/modules/platform/ref-aws-secrets-manager-lookup.adoc
  downstream/modules/platform/ref-controller-metadata-credential-input.adoc
Labels: Controller, 2.5, Needs backport to 2.5, Migration, 2.6, Needs backport to 2.6

#3982 Add redis cert considerations
  downstream/assemblies/platform/assembly-using-custom-tls-certificates.adoc
  downstream/modules/platform/con-redis-cert-considerations.adoc
Labels: Needs backport to 2.5, Needs backport to 2.6

#3987 DITA migration changes(2.6) CAG Ch 13
  downstream/assemblies/platform/assembly-controller-secret-management.adoc
  downstream/modules/platform/proc-controller-configure-secret-lookups.adoc
  downstream/modules/platform/ref-aws-secrets-manager-lookup.adoc
  downstream/modules/platform/ref-controller-metadata-credential-input.adoc
Labels: 2.6, Backported to 2.6

#3986 Add container details table
  downstream/modules/platform/ref-containerized-troubleshoot-diagnosing.adoc
Labels: Needs backport to 2.5, Needs backport to 2.6

#3988 2.6 Add container details table (#3986)
  downstream/modules/platform/ref-containerized-troubleshoot-diagnosing.adoc
Labels: Backported to 2.6

#3989 2.5 Add container details table (#3986)
  downstream/modules/platform/ref-containerized-troubleshoot-diagnosing.adoc
Labels: Backported to 2.5

#3991 2.6 Update nginx_tls_protocols default value (#3990)
  downstream/modules/platform/ref-controller-variables.adoc
  downstream/modules/platform/ref-eda-controller-variables.adoc
  downstream/modules/platform/ref-gateway-variables.adoc
  downstream/modules/platform/ref-hub-variables.adoc
Labels: 2.6, Backported to 2.6

#3994 Backport-2.5-3980 for AAP-46217 Pre-migration compliance for Chpt 4
  downstream/assemblies/eda/assembly-eda-projects.adoc
  downstream/modules/eda/con-credentials-list-view.adoc
  downstream/modules/eda/con-eda-projects-list-view.adoc
  downstream/modules/eda/proc-eda-delete-project.adoc
  downstream/modules/eda/proc-eda-editing-a-project.adoc
Labels: documentation, Ready for review, 2.5

#3972 AAP-45594: Removes references to component tabs in RBAC docs
  downstream/modules/platform/proc-controller-add-organization-user.adoc
  downstream/modules/platform/proc-gw-create-roles.adoc
  downstream/modules/platform/proc-gw-delete-roles.adoc
  downstream/modules/platform/proc-gw-edit-roles.adoc
  downstream/modules/platform/proc-gw-editing-a-user.adoc
  downstream/modules/platform/proc-gw-roles.adoc
  downstream/modules/platform/proc-gw-team-add-user.adoc
Labels: 2.6, Needs backport to 2.6

#3997 Bp to 2.6: AAP-45594: Removes references to component tabs in RBAC docs (#3972)
  downstream/modules/platform/proc-controller-add-organization-user.adoc
  downstream/modules/platform/proc-gw-create-roles.adoc
  downstream/modules/platform/proc-gw-delete-roles.adoc
  downstream/modules/platform/proc-gw-edit-roles.adoc
  downstream/modules/platform/proc-gw-editing-a-user.adoc
  downstream/modules/platform/proc-gw-roles.adoc
  downstream/modules/platform/proc-gw-team-add-user.adoc
Labels: 2.6

#3999 DITA fixes for ocp backup and performancde guides
  downstream/modules/platform/con-pod-specification-mods.adoc
  downstream/modules/platform/proc-aap-platform-gateway-backup.adoc
  downstream/modules/platform/proc-customizing-pod-specs.adoc
  downstream/modules/platform/proc-enable-pods-ref-images.adoc
  downstream/modules/platform/proc-specify-nodes-job-execution.adoc
  downstream/modules/platform/proc-troubleshoot-same-name.adoc
  downstream/modules/platform/ref-assign-pods-to-nodes.adoc
  downstream/modules/platform/ref-resource-types.adoc
  downstream/modules/platform/ref-set-custom-pod-timeout.adoc
Labels: documentation, 2.5, AAP operator, Migration, 2.6

#4003 DITA fixes for ocp backup and performancde guides (#3999)
  downstream/modules/platform/con-pod-specification-mods.adoc
  downstream/modules/platform/proc-aap-platform-gateway-backup.adoc
  downstream/modules/platform/proc-customizing-pod-specs.adoc
  downstream/modules/platform/proc-enable-pods-ref-images.adoc
  downstream/modules/platform/proc-specify-nodes-job-execution.adoc
  downstream/modules/platform/proc-troubleshoot-same-name.adoc
  downstream/modules/platform/ref-assign-pods-to-nodes.adoc
  downstream/modules/platform/ref-resource-types.adoc
  downstream/modules/platform/ref-set-custom-pod-timeout.adoc
Labels: 2.5, Migration

#4006 2.6 AAP-44556 Add registry check in devtools doc (#4000)
  downstream/modules/devtools/proc-devtools-setup-registry-redhat-io.adoc
Labels: 2.6

#4007 AAP-44558 Devtools: Add info about VSCode workspaces
  downstream/modules/devtools/proc-devtools-extension-settings.adoc
Labels: 2.5, Needs backport to 2.5, 2.6, Needs backport to 2.6

#4017 2.5 Add External Redis support statement (#4013)
  downstream/modules/topologies/ref-rpm-b-env-a.adoc
  downstream/snippets/redis-colocation-containerized.adoc
Labels: Backported to 2.5

#4018 Adding OAuth2 token creation chapter (#4012)
  downstream/assemblies/platform/assembly-gw-token-based-authentication.adoc
  downstream/modules/platform/con-gw-manage-oauth2-external-users.adoc
  downstream/modules/platform/proc-gw-enable-oauth2-external-users.adoc
  downstream/modules/platform/proc-gw-oauth2-security-controls.adoc
Labels: 2.5, Backported to 2.5

#4014 AAP-49196 2.6 OCP updates
  downstream/assemblies/platform/assembly-aap-migration.adoc
  downstream/assemblies/platform/assembly-install-aap-gateway.adoc
  downstream/assemblies/platform/assembly-operator-upgrade.adoc
  downstream/images/AAP-2.6-channels.png
  downstream/images/AAP-2.6-view.png
  downstream/modules/platform/con-ocp-supported-install.adoc
  downstream/modules/platform/con-operator-channel-upgrade.adoc
  downstream/modules/platform/con-operator-upgrade-overview.adoc
  downstream/modules/platform/proc-install-cli-aap-operator.adoc
  downstream/modules/platform/proc-operator-deploy-central-config.adoc
  downstream/modules/platform/proc-operator-upgrade.adoc
Labels: documentation, AAP operator, 2.6, Needs backport to 2.6

#4022 DITA migration changes: CAG Ch14
  downstream/assemblies/platform/assembly-ag-controller-secret-handling.adoc
  downstream/modules/platform/ref-controller-connection-security.adoc
  downstream/modules/platform/ref-controller-external-access.adoc
  downstream/modules/platform/ref-controller-managed-nodes.adoc
Labels: documentation, Controller, 2.5, Needs backport to 2.5, Migration, 2.6, Needs backport to 2.6

#4024 DITA migration changes: CAG Ch14 (#4022)
  downstream/assemblies/platform/assembly-ag-controller-secret-handling.adoc
  downstream/modules/platform/ref-controller-connection-security.adoc
  downstream/modules/platform/ref-controller-external-access.adoc
  downstream/modules/platform/ref-controller-managed-nodes.adoc
Labels: Migration, 2.6, Backported to 2.6

#4026 AAP-51375 Migration: Change devtools xrefs to links (#4025)
  downstream/assemblies/devtools/assembly-rhdh-subscription-warnings.adoc
  downstream/modules/devtools/con-devtools-requirements.adoc
  downstream/modules/devtools/con-devtools-roles-collection-prerequisites.adoc
  downstream/modules/devtools/proc-devtools-install-container.adoc
  downstream/modules/devtools/proc-devtools-install-vscode-extension.adoc
  downstream/modules/devtools/proc-rhdh-configure-devtools-server.adoc
  downstream/modules/devtools/proc-rhdh-configure-showcase-location.adoc
  downstream/modules/devtools/proc-rhdh-warning-invalid-aap-config.adoc
  downstream/modules/devtools/proc-self-service-create-oauth-app.adoc
  downstream/modules/devtools/ref-rhdh-dashboard.adoc
Labels: 2.5, Migration

#4033 DITA migration changes: CAG Ch15
  downstream/assemblies/platform/assembly-ag-controller-security-best-practices.adoc
  downstream/modules/platform/con-controller-granting-access.adoc
  downstream/modules/platform/con-controller-understand-architecture.adoc
  downstream/modules/platform/ref-controller-available-resources.adoc
  downstream/modules/platform/ref-controller-django-password-policies.adoc
  downstream/modules/platform/ref-controller-existing-security.adoc
Labels: 2.6

#4029 DITA Readiness - Related Links
  downstream/archive/archived-assemblies/builder/assembly-definition-file-breakdown.adoc
  downstream/archive/archived-assemblies/dev-guide/assembly-migrate-ansible-versions.adoc
  downstream/archive/archived-assemblies/dev-guide/assembly-tools-components.adoc
  downstream/archive/archived-assemblies/platform/assembly-supported-installation-scenarios.adoc
  downstream/archive/archived-assemblies/platform/assembly-using-rhsso-operator-with-automation-hub.adoc
  downstream/archive/archived-modules/aap-hardening/ref-complex-patching-scenarios.adoc
  downstream/archive/archived-modules/devtools/proc-create-molecule-scenario.adoc
  downstream/archive/archived-modules/devtools/proc-rhdh-add-additional-scm.adoc
  downstream/archive/archived-modules/devtools/ref-devtools-run-roles-collection.adoc
  downstream/assemblies/devtools/assembly-devtools-create-roles-collection.adoc
  downstream/assemblies/devtools/assembly-devtools-extension-set-language.adoc
  downstream/assemblies/devtools/assembly-devtools-install.adoc
  downstream/assemblies/platform/assembly-configuring-proxy-support.adoc
  downstream/assemblies/platform/assembly-controller-secret-management.adoc
  downstream/assemblies/platform/assembly-platform-install-overview.adoc
  downstream/modules/aap-hardening/con-platform-components.adoc
  downstream/modules/devtools/proc-devtools-extension-run-ansible-navigator.adoc
  downstream/modules/devtools/proc-devtools-extension-set-language.adoc
  downstream/modules/devtools/proc-devtools-extension-set-persistant-file.adoc
  downstream/modules/devtools/proc-devtools-extension-settings.adoc
  downstream/modules/devtools/proc-devtools-install-vscode-extension.adoc
  downstream/modules/devtools/proc-devtools-migrate-existing-roles-collection.adoc
  downstream/modules/devtools/proc-rhdh-add-plugin-software-templates.adoc
  downstream/modules/devtools/proc-rhdh-configure-pah-url.adoc
  downstream/modules/devtools/proc-rhdh-create.adoc
Labels: 2.5, Migration, 2.6

#4039 DITA Readiness - Related Links (#4029)
  downstream/archive/archived-assemblies/builder/assembly-definition-file-breakdown.adoc
  downstream/archive/archived-assemblies/dev-guide/assembly-migrate-ansible-versions.adoc
  downstream/archive/archived-assemblies/dev-guide/assembly-tools-components.adoc
  downstream/archive/archived-assemblies/platform/assembly-supported-installation-scenarios.adoc
  downstream/archive/archived-assemblies/platform/assembly-using-rhsso-operator-with-automation-hub.adoc
  downstream/archive/archived-modules/aap-hardening/ref-complex-patching-scenarios.adoc
  downstream/archive/archived-modules/devtools/proc-create-molecule-scenario.adoc
  downstream/archive/archived-modules/devtools/proc-rhdh-add-additional-scm.adoc
  downstream/archive/archived-modules/devtools/ref-devtools-run-roles-collection.adoc
  downstream/assemblies/devtools/assembly-devtools-create-roles-collection.adoc
  downstream/assemblies/devtools/assembly-devtools-extension-set-language.adoc
  downstream/assemblies/devtools/assembly-devtools-install.adoc
  downstream/assemblies/platform/assembly-configuring-proxy-support.adoc
  downstream/assemblies/platform/assembly-controller-secret-management.adoc
  downstream/assemblies/platform/assembly-platform-install-overview.adoc
  downstream/modules/aap-hardening/con-platform-components.adoc
  downstream/modules/devtools/proc-devtools-extension-run-ansible-navigator.adoc
  downstream/modules/devtools/proc-devtools-extension-set-language.adoc
  downstream/modules/devtools/proc-devtools-extension-set-persistant-file.adoc
  downstream/modules/devtools/proc-devtools-extension-settings.adoc
  downstream/modules/devtools/proc-devtools-install-vscode-extension.adoc
  downstream/modules/devtools/proc-devtools-migrate-existing-roles-collection.adoc
  downstream/modules/devtools/proc-rhdh-add-plugin-software-templates.adoc
  downstream/modules/devtools/proc-rhdh-configure-pah-url.adoc
  downstream/modules/devtools/proc-rhdh-create.adoc
Labels: Migration, 2.6

#4044 DITA migration changes (2.6): CAG Ch 16
  downstream/assemblies/platform/assembly-controller-awx-manage-utility.adoc
  downstream/modules/platform/ref-controller-cleanup-old-data.adoc
  downstream/modules/platform/ref-controller-cluster-management.adoc
  downstream/modules/platform/ref-controller-inventory-import.adoc
Labels: Controller, Migration, 2.6

#4028 AAP-49985 Removal of max_running_activations setting references in AAP documentation
  downstream/modules/eda/con-characterizing-your-workload.adoc
  downstream/modules/eda/con-modifying-simultaneous-activations.adoc
  downstream/modules/eda/proc-eda-activation-stuck-pending.adoc
  downstream/modules/eda/proc-modifying-activations-after-install.adoc
  downstream/modules/eda/proc-modifying-activations-during-install.adoc
  downstream/modules/platform/con-operator-custom-resources.adoc
  downstream/modules/platform/ref-eda-controller-variables.adoc
  downstream/modules/platform/ref-eda-system-requirements.adoc
  downstream/modules/platform/ref-gateway-controller-hub-eda-ext-db.adoc
  downstream/modules/platform/ref-operator-crs.adoc
Labels: documentation, Ready for review, Technical review complete, 2.6, Needs backport to 2.6

#4057 DITA Readiness - Navigator modules
  downstream/modules/navigator/proc-review-ansible-config-tui.adoc
  downstream/modules/navigator/proc-review-artifact.adoc
  downstream/modules/navigator/proc-review-docs-tui.adoc
  downstream/modules/navigator/ref-faq-navigator.adoc
Labels: 2.5, Migration, 2.6

#4063 DITA Readiness - Navigator modules (#4057)
  downstream/modules/navigator/proc-review-ansible-config-tui.adoc
  downstream/modules/navigator/proc-review-artifact.adoc
  downstream/modules/navigator/proc-review-docs-tui.adoc
  downstream/modules/navigator/ref-faq-navigator.adoc
Labels: 2.6

#4065 Add controller logs for containerized AAP
  downstream/assemblies/platform/assembly-controller-log-files.adoc
  downstream/modules/platform/ref-controller-log-files-containerized.adoc
  downstream/modules/platform/ref-controller-log-files.adoc
Labels: 2.5, Needs backport to 2.5, 2.6, Needs backport to 2.6

#4067 2.6 Add controller logs for containerized AAP (#4065)
  downstream/assemblies/platform/assembly-controller-log-files.adoc
  downstream/modules/platform/ref-controller-log-files-containerized.adoc
  downstream/modules/platform/ref-controller-log-files.adoc
Labels: 2.6, Backported to 2.6

#4068 2.5 Add controller logs for containerized AAP (#4065)
  downstream/assemblies/platform/assembly-controller-log-files.adoc
  downstream/modules/platform/ref-controller-log-files-containerized.adoc
  downstream/modules/platform/ref-controller-log-files.adoc
Labels: 2.5, Backported to 2.5

#4066 Correct links in controller guides
  downstream/assemblies/platform/assembly-controller-glossary.adoc
  downstream/modules/platform/ref-controller-activity-stream-schema.adoc
  downstream/modules/platform/ref-controller-credential-hashiCorp-vault.adoc
  downstream/modules/platform/ref-controller-credential-network.adoc
  downstream/modules/platform/ref-controller-log-aggregators.adoc
  downstream/modules/platform/ref-controller-old-job-history.adoc
Labels: Controller, 2.5, Needs backport to 2.5

#4069 Correct links in controller guides (#4066)
  downstream/assemblies/platform/assembly-controller-glossary.adoc
  downstream/modules/platform/ref-controller-activity-stream-schema.adoc
  downstream/modules/platform/ref-controller-credential-hashiCorp-vault.adoc
  downstream/modules/platform/ref-controller-credential-network.adoc
  downstream/modules/platform/ref-controller-log-aggregators.adoc
  downstream/modules/platform/ref-controller-old-job-history.adoc
Labels: 2.5, Backported to 2.5

#4070 Correct links for 2.6 controller docs
  downstream/assemblies/platform/assembly-controller-glossary.adoc
  downstream/modules/platform/ref-controller-activity-stream-schema.adoc
  downstream/modules/platform/ref-controller-credential-hashiCorp-vault.adoc
  downstream/modules/platform/ref-controller-credential-network.adoc
  downstream/modules/platform/ref-controller-log-aggregators.adoc
  downstream/modules/platform/ref-controller-old-job-history.adoc
Labels: Controller, 2.6

#4072 Editing access management files for DITA (#4047)
  downstream/assemblies/platform/assembly-gw-mapping.adoc
  downstream/modules/platform/con-gw-authenticator-map-examples.adoc
  downstream/modules/platform/con-gw-authenticator-map-triggers.adoc
  downstream/modules/platform/con-gw-authenticator-map-types.adoc
  downstream/modules/platform/con-gw-understanding-authenticator-mapping.adoc
  downstream/modules/platform/proc-aap-enable-disable-auth.adoc
  downstream/modules/platform/proc-controller-apps-create-tokens.adoc
  downstream/modules/platform/proc-controller-organization-mapping.adoc
  downstream/modules/platform/proc-controller-team-mapping.adoc
  downstream/modules/platform/proc-gw-allow-mapping.adoc
  downstream/modules/platform/proc-gw-role-mapping.adoc
  downstream/modules/platform/ref-controller-token-session-management.adoc
Labels: documentation, Migration, 2.6, Backported to 2.6

#4073 Editing access management files for DITA (#4047)
  downstream/assemblies/platform/assembly-gw-mapping.adoc
  downstream/modules/platform/con-gw-authenticator-map-examples.adoc
  downstream/modules/platform/con-gw-authenticator-map-triggers.adoc
  downstream/modules/platform/con-gw-authenticator-map-types.adoc
  downstream/modules/platform/con-gw-understanding-authenticator-mapping.adoc
  downstream/modules/platform/proc-aap-enable-disable-auth.adoc
  downstream/modules/platform/proc-controller-apps-create-tokens.adoc
  downstream/modules/platform/proc-controller-organization-mapping.adoc
  downstream/modules/platform/proc-controller-team-mapping.adoc
  downstream/modules/platform/proc-gw-allow-mapping.adoc
  downstream/modules/platform/proc-gw-role-mapping.adoc
  downstream/modules/platform/ref-controller-token-session-management.adoc
Labels: 2.5, Backported to 2.5, Migration

#4074 Editing access management files for DITA
  downstream/assemblies/platform/assembly-controller-organizations.adoc
  downstream/assemblies/platform/assembly-controller-teams.adoc
  downstream/assemblies/platform/assembly-controller-users.adoc
  downstream/assemblies/platform/assembly-gw-managing-access.adoc
  downstream/assemblies/platform/assembly-gw-roles.adoc
  downstream/assemblies/platform/assembly-gw-settings.adoc
  downstream/modules/platform/con-controller-access-organizations.adoc
  downstream/modules/platform/proc-controller-creating-a-user.adoc
  downstream/modules/platform/proc-controller-organization-notifications.adoc
  downstream/modules/platform/proc-controller-user-permissions.adoc
  downstream/modules/platform/proc-controller-user-roles.adoc
  downstream/modules/platform/proc-gw-delete-roles.adoc
  downstream/modules/platform/proc-gw-delete-team.adoc
  downstream/modules/platform/proc-gw-edit-roles.adoc
  downstream/modules/platform/proc-gw-editing-a-user.adoc
  downstream/modules/platform/proc-gw-remove-roles-user.adoc
  downstream/modules/platform/proc-gw-select-auth-type.adoc
  downstream/modules/platform/proc-gw-team-access-resources.adoc
  downstream/modules/platform/proc-gw-team-add-user.adoc
Labels: 2.5, Needs backport to 2.5, Migration, 2.6, Needs backport to 2.6

#4075 Editing access management files for DITA (#4074)
  downstream/assemblies/platform/assembly-controller-organizations.adoc
  downstream/assemblies/platform/assembly-controller-teams.adoc
  downstream/assemblies/platform/assembly-controller-users.adoc
  downstream/assemblies/platform/assembly-gw-managing-access.adoc
  downstream/assemblies/platform/assembly-gw-roles.adoc
  downstream/assemblies/platform/assembly-gw-settings.adoc
  downstream/modules/platform/con-controller-access-organizations.adoc
  downstream/modules/platform/proc-controller-creating-a-user.adoc
  downstream/modules/platform/proc-controller-organization-notifications.adoc
  downstream/modules/platform/proc-controller-user-permissions.adoc
  downstream/modules/platform/proc-controller-user-roles.adoc
  downstream/modules/platform/proc-gw-delete-roles.adoc
  downstream/modules/platform/proc-gw-delete-team.adoc
  downstream/modules/platform/proc-gw-edit-roles.adoc
  downstream/modules/platform/proc-gw-editing-a-user.adoc
  downstream/modules/platform/proc-gw-remove-roles-user.adoc
  downstream/modules/platform/proc-gw-select-auth-type.adoc
  downstream/modules/platform/proc-gw-team-access-resources.adoc
  downstream/modules/platform/proc-gw-team-add-user.adoc
Labels: Migration, 2.6, Backported to 2.6

#4080 AAP-51442: broken link correction and module relocation
  downstream/assemblies/platform/assembly-gs-key-functionality.adoc
  downstream/modules/platform/con-aap-notifications-feed.adoc
  downstream/titles/getting-started/master.adoc
Labels: 2.5, Needs backport to 2.5, 2.6, Needs backport to 2.6

#4081 Bp to 2.5: AAP-51442 fixes rss feed flagged as broken link and moves one module
  downstream/assemblies/platform/assembly-gs-key-functionality.adoc
  downstream/modules/platform/con-aap-notifications-feed.adoc
  downstream/titles/getting-started/master.adoc
Labels: 2.5

#4084 AAP-51371 DITA AuthorLine Updates.
  downstream/archive/archived-modules/builder/con-ansible-config-file-path.adoc
  downstream/archive/archived-modules/platform/proc-aap-controller-yaml-restore.adoc
  downstream/archive/archived-modules/platform/proc-controller-host-metrics.adoc
  downstream/archive/archived-modules/platform/proc-creating-a-secret.adoc
  downstream/archive/archived-modules/platform/proc-creating-controller-form-view.adoc
  downstream/assemblies/platform/assembly-controller-projects.adoc
  downstream/modules/aap-hardening/con-protect-sensitive-data-no-log.adoc
  downstream/modules/builder/con-galaxy-dependencies.adoc
  downstream/modules/platform/con-controller-fips-support.adoc
  downstream/modules/platform/con-controller-overview-api.adoc
  downstream/modules/platform/con-controller-overview-auth-enhance.adoc
  downstream/modules/platform/con-controller-overview-automation.adoc
  downstream/modules/platform/con-controller-overview-backup-restore.adoc
  downstream/modules/platform/con-controller-overview-cloud-autoscaling.adoc
  downstream/modules/platform/con-controller-overview-cluster-manage.adoc
  downstream/modules/platform/con-controller-overview-exploration.adoc
  downstream/modules/platform/con-controller-overview-galaxy.adoc
  downstream/modules/platform/con-controller-overview-host-limits.adoc
  downstream/modules/platform/con-controller-overview-inventory-plugins.adoc
  downstream/modules/platform/con-controller-overview-notifiers.adoc
  downstream/modules/platform/con-controller-overview-openstack.adoc
  downstream/modules/platform/con-controller-overview-rbac.adoc
  downstream/modules/platform/con-controller-overview-remote-exec.adoc
  downstream/modules/platform/con-controller-overview-secret-management.adoc
  downstream/modules/platform/con-controller-overview-tracking.adoc
  downstream/modules/platform/con-controller-overview-virtual-envs.adoc
  downstream/modules/platform/con-controller-overview-workflow-enhancements.adoc
  downstream/modules/platform/con-gw-activity-stream.adoc
  downstream/modules/platform/proc-controller-proxy-settings.adoc
  downstream/modules/platform/proc-deprovision-isolated-groups.adoc
  downstream/modules/platform/proc-deprovision-isolated-nodes.adoc
  downstream/modules/platform/proc-enable-proxy-support.adoc
  downstream/modules/platform/proc-set-EDA-proxy.adoc
  downstream/modules/platform/ref-automation-mesh-proxy.adoc
  downstream/modules/platform/ref-deprovisioning.adoc
  downstream/modules/platform/ref-renewal-guidance.adoc
  downstream/modules/platform/ref-report-types.adoc
  downstream/modules/platform/ref-system-proxy-config.adoc
  downstream/modules/platform/ref_proxy-backends.adoc
  downstream/modules/playbooks/proc-starting-automation.adoc
  downstream/modules/playbooks/ref-create-variables.adoc
  downstream/modules/playbooks/ref-run-network-command.adoc
  downstream/modules/playbooks/ref-use-meta-groups.adoc
Labels: 2.5, Needs backport to 2.5, 2.6, Needs backport to 2.6

#4090 AAP-51371 DITA AuthorLine Updates. (#4084)
  downstream/archive/archived-modules/builder/con-ansible-config-file-path.adoc
  downstream/archive/archived-modules/platform/proc-aap-controller-yaml-restore.adoc
  downstream/archive/archived-modules/platform/proc-controller-host-metrics.adoc
  downstream/archive/archived-modules/platform/proc-creating-a-secret.adoc
  downstream/archive/archived-modules/platform/proc-creating-controller-form-view.adoc
  downstream/assemblies/platform/assembly-controller-projects.adoc
  downstream/modules/aap-hardening/con-protect-sensitive-data-no-log.adoc
  downstream/modules/builder/con-galaxy-dependencies.adoc
  downstream/modules/platform/con-controller-fips-support.adoc
  downstream/modules/platform/con-controller-overview-api.adoc
  downstream/modules/platform/con-controller-overview-auth-enhance.adoc
  downstream/modules/platform/con-controller-overview-automation.adoc
  downstream/modules/platform/con-controller-overview-backup-restore.adoc
  downstream/modules/platform/con-controller-overview-cloud-autoscaling.adoc
  downstream/modules/platform/con-controller-overview-cluster-manage.adoc
  downstream/modules/platform/con-controller-overview-exploration.adoc
  downstream/modules/platform/con-controller-overview-galaxy.adoc
  downstream/modules/platform/con-controller-overview-host-limits.adoc
  downstream/modules/platform/con-controller-overview-inventory-plugins.adoc
  downstream/modules/platform/con-controller-overview-notifiers.adoc
  downstream/modules/platform/con-controller-overview-openstack.adoc
  downstream/modules/platform/con-controller-overview-rbac.adoc
  downstream/modules/platform/con-controller-overview-remote-exec.adoc
  downstream/modules/platform/con-controller-overview-secret-management.adoc
  downstream/modules/platform/con-controller-overview-tracking.adoc
  downstream/modules/platform/con-controller-overview-virtual-envs.adoc
  downstream/modules/platform/con-controller-overview-workflow-enhancements.adoc
  downstream/modules/platform/con-gw-activity-stream.adoc
  downstream/modules/platform/proc-controller-proxy-settings.adoc
  downstream/modules/platform/proc-deprovision-isolated-groups.adoc
  downstream/modules/platform/proc-deprovision-isolated-nodes.adoc
  downstream/modules/platform/proc-enable-proxy-support.adoc
  downstream/modules/platform/proc-set-EDA-proxy.adoc
  downstream/modules/platform/ref-automation-mesh-proxy.adoc
  downstream/modules/platform/ref-deprovisioning.adoc
  downstream/modules/platform/ref-renewal-guidance.adoc
  downstream/modules/platform/ref-report-types.adoc
  downstream/modules/platform/ref-system-proxy-config.adoc
  downstream/modules/platform/ref_proxy-backends.adoc
  downstream/modules/playbooks/proc-starting-automation.adoc
  downstream/modules/playbooks/ref-create-variables.adoc
  downstream/modules/playbooks/ref-run-network-command.adoc
  downstream/modules/playbooks/ref-use-meta-groups.adoc
Labels: 2.6

#4086 Changes to system and gateway settings
  downstream/assemblies/platform/assembly-ag-controller-config.adoc
  downstream/assemblies/platform/assembly-gw-settings.adoc
  downstream/modules/platform/proc-controller-configure-system.adoc
  downstream/modules/platform/proc-controller-set-up-azure.adoc
  downstream/modules/platform/proc-gw-define-rules-triggers.adoc
  downstream/modules/platform/proc-gw-settings-insights-settings.adoc
  downstream/modules/platform/proc-settings-gw-additional-options.adoc
  downstream/modules/platform/proc-settings-gw-authentication.adoc
  downstream/modules/platform/proc-settings-gw-security-options.adoc
Labels: documentation, Controller, 2.6

#4103 Minor formatting update to fix a heading in Troubleshooting AAP
  downstream/assemblies/troubleshooting-aap/assembly-troubleshoot-jobs.adoc
Labels: 2.5, Needs backport to 2.5, 2.6, Needs backport to 2.6

#4105 backport to 2.6: Minor formatting update to fix a heading in the Troubleshooting AAP guide (#4103)
  downstream/assemblies/troubleshooting-aap/assembly-troubleshoot-jobs.adoc
Labels: 2.6

#4101 AAP-51877 edits to Hub variables and backup sections
  downstream/modules/platform/proc-backup-aap-container.adoc
  downstream/modules/platform/ref-hub-variables.adoc
Labels: documentation, 2.5, Needs backport to 2.5, Containerized AAP, 2.6, Needs backport to 2.6

#4108 AAP-51877 edits to Hub variables and backup sections (#4101)
  downstream/modules/platform/proc-backup-aap-container.adoc
  downstream/modules/platform/ref-hub-variables.adoc
Labels: Containerized AAP, 2.6

#4031 Updating RHEM container image build
  downstream/modules/platform/proc-edge-manager-build-bootc-image.adoc
  downstream/modules/platform/proc-edge-manager-virt.adoc
  downstream/modules/platform/proc-edge-manager-vmware.adoc
Labels: 2.5, Needs backport to 2.5, 2.6, Needs backport to 2.6

#4113 Refactor Chapter 6 of Operating AAP guide
  downstream/assemblies/platform/assembly-changing-ssl-certs-keys.adoc
  downstream/modules/platform/proc-change-ssl-installer.adoc
Labels: Not ready for peer review, Needs backport to 2.5, Needs backport to 2.6

#4114 2.6 Refactor Chapter 6 of Operating AAP guide (#4113)
  downstream/assemblies/platform/assembly-changing-ssl-certs-keys.adoc
  downstream/modules/platform/proc-change-ssl-installer.adoc
Labels: Backported to 2.6

#4120 Fixing typo
  downstream/modules/platform/ref-automation-mesh-proxy.adoc
Labels: Needs backport to 2.5, Needs backport to 2.6

#4124 Editing controller files for DITA
  downstream/assemblies/platform/assembly-ag-controller-usability-analytics.adoc
  downstream/modules/platform/ref-controller-automation-analytics.adoc
  downstream/modules/platform/ref-controller-cred-type-counts-json.adoc
  downstream/modules/platform/ref-controller-data-collection-details.adoc
Labels: documentation, 2.5, Needs backport to 2.5, Migration, 2.6, Needs backport to 2.6

#4126 Editing controller files for DITA (#4124)
  downstream/assemblies/platform/assembly-ag-controller-usability-analytics.adoc
  downstream/modules/platform/ref-controller-automation-analytics.adoc
  downstream/modules/platform/ref-controller-cred-type-counts-json.adoc
  downstream/modules/platform/ref-controller-data-collection-details.adoc
Labels: 2.5, Backported to 2.5

#4129 Fixing typo in link (#4128)
  downstream/modules/platform/proc-aap-platform-pvc-restore.adoc
Labels: 2.5

#4131 2.5 Adds postgres_extra_settings to inventory appendix (#4059)
  downstream/modules/platform/ref-database-inventory-variables.adoc
Labels: Backported to 2.5

#4137 Update RHEL 10 reqs for containerized
  downstream/snippets/cont-tested-system-config.adoc
  downstream/titles/release-notes/async/aap-25-20250702.adoc
Labels: Needs backport to 2.5, Needs backport to 2.6

#4138 2.6 Update RHEL 10 reqs for containerized (#4137)
  downstream/snippets/cont-tested-system-config.adoc
  downstream/titles/release-notes/async/aap-25-20250702.adoc
Labels: Backported to 2.6

#4139 2.5 Update RHEL 10 reqs for containerized (#4137)
  downstream/snippets/cont-tested-system-config.adoc
  downstream/titles/release-notes/async/aap-25-20250702.adoc
Labels: Backported to 2.5

#4135 Adding redirect to automation mesh guide
  stories/topics/ref-saas-egress-model.adoc
Labels: AAP on clouds, SaaS on AWS

#4140 Edits for the OCP part of AAP-51783 (#4136)
  downstream/assemblies/platform/assembly-operator-add-execution-nodes.adoc
Labels: 2.5

#4142 Updating team mapping section
  downstream/modules/platform/proc-controller-team-mapping.adoc
Labels: documentation, 2.5, Needs backport to 2.5, 2.6, Needs backport to 2.6

#4144 Updating team mapping section (#4142)
  downstream/modules/platform/proc-controller-team-mapping.adoc
Labels: documentation, 2.5, Backported to 2.5

#4143 Updating team mapping section (#4142)
  downstream/modules/platform/proc-controller-team-mapping.adoc
Labels: documentation, 2.6, Backported to 2.6

#4146 Editing controller files for DITA (#4127)
  downstream/assemblies/platform/assembly-ag-controller-tips-and-tricks.adoc
  downstream/assemblies/platform/assembly-ag-controller-troubleshooting.adoc
  downstream/modules/platform/proc-controller-config-jump-hosts-inventory.adoc
  downstream/modules/platform/proc-controller-configure-keyfile-SSH.adoc
  downstream/modules/platform/proc-controller-ec2-vpc-instances.adoc
  downstream/modules/platform/ref-controller-reuse-external-database-fail.adoc
  downstream/modules/platform/ref-controller-set-up-jump-host.adoc
Labels: 2.5, Backported to 2.5

#4145 Editing controller files for DITA (#4127)
  downstream/assemblies/platform/assembly-ag-controller-tips-and-tricks.adoc
  downstream/assemblies/platform/assembly-ag-controller-troubleshooting.adoc
  downstream/modules/platform/proc-controller-config-jump-hosts-inventory.adoc
  downstream/modules/platform/proc-controller-configure-keyfile-SSH.adoc
  downstream/modules/platform/proc-controller-ec2-vpc-instances.adoc
  downstream/modules/platform/ref-controller-reuse-external-database-fail.adoc
  downstream/modules/platform/ref-controller-set-up-jump-host.adoc
Labels: 2.6, Backported to 2.6

#4152 AAP-52118: fixes two broken links in Configuring automation execution
  downstream/modules/platform/ref-controller-activity-stream-schema.adoc
  downstream/modules/platform/ref-controller-log-aggregators.adoc
Labels: 2.5, Needs backport to 2.5, 2.6, Needs backport to 2.6

#4094 New Assembly and modules for OCP (AAP-51782)
  downstream/assemblies/platform/assembly-operator-troubleshoot.adoc
  downstream/modules/platform/con-operator-understand-operator-logs.adoc
  downstream/modules/platform/proc-operator-collect-diagnostic-data.adoc
  downstream/modules/platform/proc-operator-config-log-verbosity.adoc
  downstream/modules/platform/proc-operator-crd-config-parameters.adoc
  downstream/modules/platform/proc-operator-debug-crashing-pods.adoc
  downstream/modules/platform/proc-operator-inspect-k8s-resource.adoc
  downstream/modules/platform/proc-operator-viewing-events.adoc
  downstream/modules/platform/proc-viewing-operator-logs.adoc
  downstream/modules/platform/ref-operator-core-aap-resources.adoc
  downstream/modules/platform/ref-operator-standard-k8s-resources.adoc
  downstream/titles/aap-operator-installation/master.adoc
Labels: documentation, 2.5, AAP operator, Needs backport to 2.5, 2.6, Needs backport to 2.6

#4156 New Assembly and modules for OCP (AAP-51782) (#4094)
  downstream/assemblies/platform/assembly-operator-troubleshoot.adoc
  downstream/modules/platform/con-operator-understand-operator-logs.adoc
  downstream/modules/platform/proc-operator-collect-diagnostic-data.adoc
  downstream/modules/platform/proc-operator-config-log-verbosity.adoc
  downstream/modules/platform/proc-operator-crd-config-parameters.adoc
  downstream/modules/platform/proc-operator-debug-crashing-pods.adoc
  downstream/modules/platform/proc-operator-inspect-k8s-resource.adoc
  downstream/modules/platform/proc-operator-viewing-events.adoc
  downstream/modules/platform/proc-viewing-operator-logs.adoc
  downstream/modules/platform/ref-operator-core-aap-resources.adoc
  downstream/modules/platform/ref-operator-standard-k8s-resources.adoc
  downstream/titles/aap-operator-installation/master.adoc
Labels: 2.6

#4157 New Assembly and modules for OCP (AAP-51782) (#4094)
  downstream/assemblies/platform/assembly-operator-troubleshoot.adoc
  downstream/modules/platform/con-operator-understand-operator-logs.adoc
  downstream/modules/platform/proc-operator-collect-diagnostic-data.adoc
  downstream/modules/platform/proc-operator-config-log-verbosity.adoc
  downstream/modules/platform/proc-operator-crd-config-parameters.adoc
  downstream/modules/platform/proc-operator-debug-crashing-pods.adoc
  downstream/modules/platform/proc-operator-inspect-k8s-resource.adoc
  downstream/modules/platform/proc-operator-viewing-events.adoc
  downstream/modules/platform/proc-viewing-operator-logs.adoc
  downstream/modules/platform/ref-operator-core-aap-resources.adoc
  downstream/modules/platform/ref-operator-standard-k8s-resources.adoc
  downstream/titles/aap-operator-installation/master.adoc
Labels: 2.5

#4159 2.5 Adds changing certs proc for containerized aap (#4155)
  downstream/assemblies/platform/assembly-changing-ssl-certs-keys.adoc
  downstream/modules/platform/proc-change-tls-certs-installer.adoc
Labels: Backported to 2.5

#4160 AAP-52126 New assembly and modules
  downstream/assemblies/platform/assembly-operator-customize-aap.adoc
  downstream/modules/platform/proc-operator-crd-config-parameters-ui.adoc
  downstream/modules/platform/proc-operator-defining-nested-parameter.adoc
  downstream/titles/aap-operator-installation/master.adoc
Labels: AAP operator, Needs backport to 2.5, Needs backport to 2.6

#4162 adding in link to core AAP resouces (#4161)
  downstream/modules/platform/proc-operator-config-log-verbosity.adoc
Labels: 2.5

#4164 AAP-52126 New assembly and modules (#4160)
  downstream/assemblies/platform/assembly-operator-customize-aap.adoc
  downstream/modules/platform/proc-operator-crd-config-parameters-ui.adoc
  downstream/modules/platform/proc-operator-defining-nested-parameter.adoc
  downstream/titles/aap-operator-installation/master.adoc
Labels: 2.5
